shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/TCLStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/PostgreSQLStatementParser.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLTCLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/tcl/PrepareTransactionStatement.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/postgresql/tcl/PostgreSQLPrepareTransactionStatement.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/tcl/TCLStatementAssert.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/tcl/impl/PrepareTransactionStatementAssert.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/tcl/PrepareTransactionTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/tcl/prepare-transaction.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/tcl/prepare-transaction.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml

Ref https://github.com/apache/shardingsphere/issues/18496 & https://github.com/apache/shardingsphere/issues/14104
- Add PREPARE TRANSACTION grammar
- Support parsing PREPARE TRANSACTION in PostgreSQL
- Add test

support PREPARE TRANSACTION statement in PostgreSQL

---

shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtil.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtilTest.java

Fixes #17466.
- fix NullPointerException when execute select union statement contains subquery

Fix NullPointerException when execute select union statement contains subquery

---

shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLInventoryDumperTest.java

Fixes #15707.
- rename MySQLJdbcDumperTest to MySQLInventoryDumperTest
- add more test case for YEAR_DATE_TYPE in MySQLInventoryDumper

Improve unit test of MySQLInventoryDumper

---

shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java

Revise #18161.
COM_STMT_PREPARE doesn't execute any statement. Handling autocommit in COM_STMT_EXECUTE is enough.

Remove transaction logic from MySQLComStmtPrepareExecutor

---

shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/DriverDataSourceCache.java
shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java
shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURLTest.java

Fixes #18968.
- use byte stream to load config file when use ShardingSphere Driver with SpringBoot fatjar

Use byte stream to load config file when use ShardingSphere Driver with SpringBoot fatjar

---

shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/session/ConnectionSession.java

Related to #18756.
We have avoided instance of ConnectionSession being used concurrently at normal command phase, and we don't need methods of AtomicBoolean.

Use primitive boolean in ConnectionSession

---

shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/text/distsql/ral/common/updatable/AlterTransactionRuleHandlerTest.java

NullPointerException occurred, but the exception was caught in codes, which made the test passed.
https://github.com/apache/shardingsphere/runs/7268140573?check_suite_focus=true#step:6:12870

Fix exception in AlterTransactionRuleHandlerTest

---

shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/AssistQueryAndPlainInsertColumnsTokenGeneratorTest.java

Reverts apache/shardingsphere#19004
The assertion is incorrect. It should not assert size only, we need to assert more element details in the collection.

Revert "add tests"

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/sharding/ComplexShardingStrategyConfiguration.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/sharding/HintShardingStrategyConfiguration.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/sharding/NoneShardingStrategyConfiguration.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/sharding/ShardingStrategyConfiguration.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/sharding/StandardShardingStrategyConfiguration.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShardingTableRuleQueryResultSet.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShardingTableRuleQueryResultSetTest.java
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/db/show_rules.xml
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/db/show_table_rule.xml
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting/show_rules.xml
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting/show_table_rule.xml
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting_and_encrypt/show_rules.xml
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting_and_encrypt/show_table_rule.xml
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/readwrite_splitting/show_rules.xml
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/readwrite_splitting/show_table_rule.xml
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/sharding_governance/mysql/show_rules.xml
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/sharding_governance/mysql/show_table_rule.xml
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/tbl/show_rules.xml
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/tbl/show_table_rule.xml

The `xxx_strategy_type` is incorrect, `inline` is not a type of strategy.
```sq
mysql> show sharding table rules\G;
*************************** 1. row ***************************
table: t_order_item
actual_data_nodes: ds_${0..1}.t_order_item_${0..1}
actual_data_sources:
database_strategy_type: inline
database_sharding_column: user_id
database_sharding_algorithm_type: inline
database_sharding_algorithm_props: algorithm-expression=t_order_item_${user_id % 2}
table_strategy_type: inline
table_sharding_column: order_id
table_sharding_algorithm_type: inline
table_sharding_algorithm_props: algorithm-expression=t_order_item_${order_id % 2}
key_generate_column: id
key_generator_type: snowflake
key_generator_props:
```
```sql
mysql> show sharding table rules\G;
*************************** 1. row …
```

Update strategy result of `SHOW SHARDING TABLE RULES`

---

shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ReadwriteSplittingRuleQueryResultSet.java
shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ReadwriteSplittingRuleQueryResultSetTest.java

Fixes #19084.
Fix IllegalStateException when `SHOW READWRITE_SPLITTING RULES` with empty rule configuration.

Fixes IllegalStateException for #19084.

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/BaseRule.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/DDLStatement.g4
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/alter-sequence.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/alter-sequence.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml

Ref #17848 .
- Proofread `ALTER SEQUENCE`grammar
- Add Tests

Proofread ALTER SEQUENCE grammar + add test cases

---

shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/instance/ComputeNodeInstance.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/distsql/ral/queryable/ShowInstanceHandler.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/distsql/ral/updatable/LabelInstanceHandler.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/distsql/ral/updatable/UnlabelInstanceHandler.java

Use empty list to init labels of ComputeNodeInstance

---

shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptForUseDefaultInsertColumnsTokenGenerator.java
shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptAssignmentTokenGeneratorTest.java
shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptForUseDefaultInsertColumnsTokenGeneratorTest.java

Fixes #15819.
- Add unit test.
- fix NPE when previousSQLTokens is null.
- remov EncryptAssignmentTokenGeneratorTest to `package org.apache.shardingsphere.encrypt.rewrite.token.generator`

Add unit test for EncryptForUseDefaultInsertColumnsTokenGenerator

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/ddl/impl/ShardingCreateIndexStatementValidator.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/ddl/ShardingCreateIndexStatementValidatorTest.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/decorator/model/ShardingSphereSchema.java
shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/ShardingSphereSchemaTest.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/distsql/ral/common/constant/DistSQLScriptConstants.java
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CreateIndexStatementHandler.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CreateTableStatementHandler.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/opengauss/ddl/OpenGaussCreateIndexStatement.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/postgresql/ddl/PostgreSQLCreateIndexStatement.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CreateIndexStatementHandlerTest.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CreateTableStatementHandlerTest.java

Fixes #19104.
- support create index if not exists statement for PostgreSQL and openGauss

Support create index if not exists statement for PostgreSQL and openGauss

---

shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/ClusterContextManagerCoordinator.java

Fixes #19008 .
-
split ContextManager.alterSchema() to 2 methods
-

split ContextManager.alterSchema() to 2 methods

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/BaseRule.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleAlterMaterializedViewLogStatement.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/ddl/AlterMaterializedViewLogStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/alter-materialized-view-log.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/alter-materialized-view-log.xml

Ref https://github.com/apache/shardingsphere/issues/6480 & https://github.com/apache/shardingsphere/issues/18389
- Add `ALTER MATERIALIZED VIEW LOG`  grammar
- Support parsing `ALTER MATERIALIZED VIEW LOG` in Oracle
- Add test

Support parsing `ALTER MATERIALIZED VIEW LOG` in Oracle

---

shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/merge/dal/show/EncryptShowColumnsMergedResult.java
shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/metadata/EncryptSchemaMetaDataDecorator.java
shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptTable.java
shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/test/java/org/apache/shardingsphere/encrypt/merge/dal/show/MergedEncryptShowColumnsMergedResultTest.java
shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/test/java/org/apache/shardingsphere/encrypt/metadata/EncryptSchemaMetaDataDecoratorTest.java
shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/test/java/org/apache/shardingsphere/encrypt/rule/EncryptTableTest.java
shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-boot-starter/src/test/java/org/apache/shardingsphere/spring/boot/SpringBootStarterTest.java

Fixes #19418.
- fix wrong encrypt rewrite result due to incorrect order of metadata

Fix wrong encrypt rewrite result due to incorrect order of metadata

---

shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-core/src/main/java/org/apache/shardingsphere/readwritesplitting/checker/AbstractReadwriteSplittingRuleConfigurationChecker.java
shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-core/src/test/java/org/apache/shardingsphere/readwritesplitting/checker/AlgorithmProvidedReadwriteSplittingRuleConfigurationCheckerTest.java
shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-core/src/test/java/org/apache/shardingsphere/readwritesplitting/checker/ReadwriteSplittingRuleConfigurationCheckerTest.java

Fixes #19102.
- add duplicate datasource check logic for ReadwriteSplitting

Add duplicate datasource check logic for ReadwriteSplitting

---

shardingsphere-kernel/shardingsphere-authority/shardingsphere-authority-core/src/main/java/org/apache/shardingsphere/authority/checker/AuthorityChecker.java
shardingsphere-kernel/shardingsphere-authority/shardingsphere-authority-core/src/test/java/org/apache/shardingsphere/authority/checker/AuthorityCheckerTest.java

Revise #14161.
The overhead of construct error message is always present even the check passed.

Reduce redundant overhead in AuthorityChecker

---

shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintUtils.java

Reduce overhead of split empty value in SQLHintUtils

---

shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/MySQLAdminExecutorCreator.java

Fixes #18528 
- modify  method ```create()``` in MySQLAdminExecutorCreator, add logic about checking count of params , not just consider the first parameter.
-
My test case as follow in my code:
```
mysql> select version(), @@sql_mode;
```
```
mysql> select current_user(), @@sql_mode;
```
and it doesn't affect the existing logic

fix issue #18528

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/datetime/IntervalShardingAlgorithm.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/datetime/IntervalShardingAlgorithmTest.java

Fixes #19636.
- Refactor `org.apache.shardingsphere.sharding.algorithm.sharding.datetime.IntervalShardingAlgorithm#parseMonth` .
- Update unit tests.

Fix the failed conversion of Month related classes on IntervalShardingAlgorithm

---

shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-core/src/test/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryRuleTest.java

Fixes NPE when DatabaseDiscoveryRuleTest running alone.
ScheduleContextFactory.getInstance() return null when ScheduleContextFactory.init not be called.

fix DatabaseDiscoveryRuleTest NPE

---

pom.xml
shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/release-docs/LICENSE
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/SQLNodeConverterEngine.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/expression/impl/BetweenExpressionConverter.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/expression/impl/BinaryOperationExpressionConverter.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/expression/impl/ExistsSubqueryExpressionConverter.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/expression/impl/FunctionConverter.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/expression/impl/InExpressionConverter.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/expression/impl/ListExpressionConverter.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/from/impl/SimpleTableConverter.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/from/impl/SubqueryTableConverter.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/orderby/item/ColumnOrderByItemConverter.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/projection/impl/AggregationProjectionConverter.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/projection/impl/ColumnProjectionConverter.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/projection/impl/ExpressionProjectionConverter.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/projection/impl/SubqueryProjectionConverter.java

Fixes #19735.
- update pom.xml .
- update LICENSE.
- Handle deprecated methods and deprecated classes in the following classes. 
- `org.apache.shardingsphere.infra.federation.optimizer.converter.segment.expression.impl.InExpressionConverter`
- `org.apache.shardingsphere.infra.federation.optimizer.converter.segment.projection.impl.AggregationProjectionConverter`
- etc.

Update Apache Calcite to 1.30.0 to improve GraalVM support

---

shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/TextProtocolBackendHandlerFactoryTest.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/RDLBackendHandlerFactoryTest.java

For #7522.
- Add test cases for RDL (3 branches) in TextProtocolBackendHandlerFactory

Add test cases for RDL (3 branches) in TextProtocolBackendHandlerFactoryTest

---

shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/datasource/ShardingSphereDataSource.java
shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/datasource/ShardingSphereDataSourceTest.java

Remove SQLParserRuleConfiguration when use ShardingSphere-JDBC cluster mode

---

.github/workflows/ci-daily.yml
.github/workflows/ci.yml

- There are too many skipped CI when we create a Pull Request.
- There are too much redundancies in ci.yml.

Separate schedule CI from ci.yml

---

shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-namespace/src/test/java/org/apache/shardingsphere/spring/namespace/fixture/FixtureClusterPersistRepository.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/fixture/ClusterPersistRepositoryFixture.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/ProcessListClusterPersistRepositoryFixture.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/ClusterPersistRepository.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-etcd/src/main/java/org/apache/shardingsphere/mode/repository/cluster/etcd/EtcdRepository.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/CuratorZookeeperRepository.java
shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/test/java/org/apache/shardingsphere/proxy/fixture/ClusterPersistRepositoryFixture.java
shardingsphere-test/shardingsphere-integration-driver-test/src/test/java/org/apache/shardingsphere/driver/fixture/TestClusterPersistRepository.java

- Remove `getSequentialId()`  method in cluster mode

Remove useless method

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/DDLStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/PostgreSQLStatementParser.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/ddl/AlterStatisticsStatement.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/postgresql/ddl/PostgreSQLAlterStatisticsStatement.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/ddl/AlterStatisticsStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/alter-statistics.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/alter-statistics.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml

Ref #17848 .
- Proofread `ALTER STATISTICS` grammar
- Support parsing `ALTER STATISTICS` in PostgreSQL
- Add tests

Support parsing `ALTER STATISTICS` in PostgreSQL

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/antlr4/imports/mysql/DDLStatement.g4
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/alter-table.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/create-table.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/alter-table.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/create-table.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml

Ref #19824.
- optimize MySQL visible/invisible parse of create/alter table statements

Optimize MySQL visible/invisible parse of create/alter table statements

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/scaling/distsql/handler/converter/ShardingScalingRuleStatementConverter.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/test/java/org/apache/shardingsphere/scaling/distsql/handler/query/ShardingScalingRulesQueryResultSetTest.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/config/rule/data/pipeline/PipelineInputConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/config/rule/data/pipeline/PipelineOutputConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/config/rule/rulealtered/OnRuleAlteredActionConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/pojo/data/pipeline/YamlPipelineInputConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/pojo/data/pipeline/YamlPipelineOutputConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/data/pipeline/YamlPipelineInputConfigurationSwapper.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/data/pipeline/YamlPipelineOutputConfigurationSwapper.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/rulealtered/YamlOnRuleAlteredActionConfigurationSwapper.java
shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/rulealtered/YamlOnRuleAlteredActionConfigurationSwapperTest.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredContext.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/prepare/InventoryTaskSplitter.java

Fixes #19879.
- Extract InputConfiguration and OutputConfiguration from OnRuleAlteredActionConfiguration. And also OnRuleAlteredActionConfiguration, YamlOnRuleAlteredActionConfigurationSwapper

Extract InputConfiguration and OutputConfiguration from OnRuleAlteredActionConfiguration

---

shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptAssignmentParameterRewriter.java
shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.java
shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptInsertValueParameterRewriter.java
shardingsphere-infra/shardingsphere-infra-rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/parameter/builder/impl/StandardParameterBuilder.java
shardingsphere-infra/shardingsphere-infra-rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/parameter/builder/impl/GroupedParameterBuilderTest.java
shardingsphere-infra/shardingsphere-infra-rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/parameter/builder/impl/StandardParameterBuilderTest.java
shardingsphere-test/shardingsphere-rewrite-test/src/test/resources/scenario/mix/case/query-with-cipher/dml/insert/insert-column.xml

Fixes #19888.
- optimize logic of StandardParameterBuilder#getParameters to group by parameters by original index
- add rewrite test case
- remove useless removeIndexAndParameters

Fix wrong parameter rewrite when use sharding and encrypt

---

shardingsphere-distsql/shardingsphere-distsql-parser/src/main/antlr4/imports/RALStatement.g4
shardingsphere-distsql/shardingsphere-distsql-parser/src/main/antlr4/org/apache/shardingsphere/distsql/parser/autogen/KernelDistSQLStatement.g4
shardingsphere-distsql/shardingsphere-distsql-parser/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java
shardingsphere-distsql/shardingsphere-distsql-statement/src/main/java/org/apache/shardingsphere/distsql/parser/statement/ral/queryable/ShowInstanceListStatement.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowInstanceListHandler.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/QueryableRALStatementAssert.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/queryable/ShowInstanceListStatementAssert.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/ShowInstanceListStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ral/queryable.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ral/queryable.xml

Fixes #19765 , Change relevant class name of the `SHOW INSTANCE LIST` syntax to ShowInstanceListXxx.

ShowInstanceXxx renamed to ShowInstanceListXxx.

---

shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/job/progress/listener/PipelineJobProgressListener.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/AbstractImporter.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/listener/DefaultPipelineJobProgressListener.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/persist/PipelineJobProgressPersistContext.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/persist/PipelineJobProgressPersistService.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/IncrementalTask.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryTask.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJob.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJobPreparer.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/prepare/InventoryTaskSplitter.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/scaling/core/job/importer/ImporterFactory.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/importer/MySQLImporter.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/importer/OpenGaussImporter.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/importer/PostgreSQLImporter.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/api/impl/GovernanceRepositoryAPIImplTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/fixture/FixtureImporter.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/fixture/FixturePipelineJobProgressListener.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/importer/AbstractImporterTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/task/IncrementalTaskTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryTaskTest.java

Related to #19457.
- Rename PipelineJobPersistCallback to PipelineJobProgressListener
- Simplify PipelineJobProgressListener methods; Rename methods;
- Rename PipelineJobPersistContext to PipelineJobProgressPersistContext; Move to pipeline-core module;
- Rename RuleAlteredJobPersistService to PipelineJobProgressPersistService; Move to common package;
- Rename method names of PipelineJobProgressPersistService;

Revise job progress persistence

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/DDLStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/PostgreSQLStatementParser.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/ddl/AlterSubscriptionStatement.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/postgresql/ddl/PostgreSQLAlterSubscriptionStatement.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/ddl/AlterSubscriptionStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/alter-subscription.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/alter-subscription.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml

Ref #17848 .
- Proofread `ALTER SUBSCRIPTION` grammar
- Support parsing `ALTER SUBSCRIPTION` in PostgreSQL
- Add tests

Support Parsing `ALTER SUBSCRIPTION` in PostgreSQL

---

shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/context/PipelineJobContext.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/task/PipelineTasksRunner.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/GovernanceRepositoryAPI.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/GovernanceRepositoryAPIImpl.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/RuleAlteredJobAPIImpl.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/PipelineJobExecutor.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/PipelineJobCenter.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/persist/PipelineJobProgressPersistService.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJob.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJobContext.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJobScheduler.java

- Rename RuleAlteredJobCenter to PipelineJobCenter
- Add PipelineTasksRunner
- Add PipelineJobContext
- Extend PipelineJob
- Simplify PipelineJobCenter methods
- Refactor job progress persistence parameter for common usage, GovernanceRepositoryAPI and PipelineJobProgressPersistService

Refactor RuleAlteredJobCenter for common usage

---

CODE_OF_CONDUCT.md
docs/community/content/contribute/code-conduct.cn.md
docs/community/content/contribute/code-conduct.en.md
src/resources/code-style-idea.xml

Purpose:
- Easier to import code style schema in IDEA
- Keep unified code style on original files even users format code; Java importing and line breaks might be changed if code style is not set up
- Easier to update code style schema
Process:
1. Download [shardingsphere-settings.jar]( https://shardingsphere.apache.org/community/data/shardingsphere-settings.jar ) and unzip, import `codestyles/Default _1_.xml`
2. Do some testing for a long time
3. Export it as `code-style-idea.xml`
- Add `code-style-idea.xml`
Changes in `code-style-idea.xml` comparing to original `codestyles/Default _1_.xml`:
1, Add `LINE_SEPARATOR` option, limit to `\n`
2, Remove `<option name="KEEP_LINE_BREAKS" value="false" />` and `<option …

Add and update IDEA code style schema

---

shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-core/src/main/java/org/apache/shardingsphere/readwritesplitting/checker/AbstractReadwriteSplittingRuleConfigurationChecker.java
shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-core/src/main/java/org/apache/shardingsphere/readwritesplitting/rule/ReadwriteSplittingRule.java
shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-core/src/test/java/org/apache/shardingsphere/readwritesplitting/checker/ReadwriteSplittingRuleConfigurationCheckerTest.java
shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-boot-starter/src/test/java/org/apache/shardingsphere/spring/boot/SpringBootStarterTest.java
shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-boot-starter/src/test/java/org/apache/shardingsphere/spring/boot/jndi/SpringBootJNDIDataSourceTest.java
shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-boot-starter/src/test/resources/application-jndi.properties
shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-boot-starter/src/test/resources/application.properties

support Cartesian Product for readWriteConfig, add check database for writedatasoucename

---

shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/JDBCBackendConnection.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/vertx/VertxBackendConnection.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/JDBCBackendConnectionTest.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/MockConnectionUtil.java

Fix cross-database data source confusion

---

shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/context/PipelineJobContext.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/context/PipelineProcessContext.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/context/AbstractPipelineProcessContext.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJobContext.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJobPreparer.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJobScheduler.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/prepare/InventoryTaskSplitter.java

Purpose:
- Prepare for RuleAlteredJobPreparer / RuleAlteredJobScheduler / InventoryTaskSplitter as common usage classes
- Add getJobProcessContext method in PipelineJobContext
- Refactor RuleAlteredJobContext.getRuleAlteredJobContext()

Add standard PipelineJobContext.getJobProcessContext

---

shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-executor/src/main/java/org/apache/shardingsphere/infra/federation/executor/advanced/resultset/FederationResultSet.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-executor/src/test/java/org/apache/shardingsphere/infra/federation/executor/advanced/result/FederationResultSetTest.java

Ref #13091.
- optimize createColumnLabelAndIndexMap logic in FederationResultSet
- add unit test for FederationResultSet

Fix SQLFeatureNotSupportedException when execute federation sql with AdvancedFederationExecutor

---

.gitignore

For #19536.
- Ignore vscode's configuration file in .gitignore.
- This will improve the experience of using the VS Code-based IDE and avoid passing personal configuration files into other PRs.

Ignore vscode's configuration file in .gitignore

---

shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlJobItemIncrementalTasksProgressSwapper.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlJobItemInventoryTasksProgressSwapper.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlJobProgressSwapperTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/resources/job-progress-failure.yaml

Related to #19940.
- Improve job item tasks progress swapper, make it compatible with null value, avoid possible NPE in ShowScalingJobStatusQueryResultSet
- Improve YamlJobProgressSwapperTest, 1) test swapToYaml and swapToObject, 2) test job-progress-failure.yaml secenario

Improve job progress swapper

---

shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/listener/SessionConnectionListener.java

- Generate worker id on re-register in cluster mode

Generate worker id on re-register in cluster mode

---

shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-namespace/src/test/java/org/apache/shardingsphere/spring/namespace/fixture/FixtureClusterPersistRepository.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/ClusterLockPersistService.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/fixture/ClusterPersistRepositoryFixture.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/ProcessListClusterPersistRepositoryFixture.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/ClusterPersistRepository.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-etcd/src/main/java/org/apache/shardingsphere/mode/repository/cluster/etcd/EtcdRepository.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-etcd/src/main/java/org/apache/shardingsphere/mode/repository/cluster/etcd/lock/EtcdInternalLockHolder.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/CuratorZookeeperRepository.java
shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/test/java/org/apache/shardingsphere/proxy/fixture/ClusterPersistRepositoryFixture.java
shardingsphere-test/shardingsphere-integration-driver-test/src/test/java/org/apache/shardingsphere/driver/fixture/TestClusterPersistRepository.java

- Rename tryLock to persistLock in ClusterPersistRepository

Rename tryLock to persistLock in ClusterPersistRepository

---

pom.xml
shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/release-docs/LICENSE

Fixes #20120.
- update pom.xml and LICENSE.

Update Gson to 2.9.1 to avoid CVE

---

shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/PipelineJobPublicAPI.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/job/yaml/YamlPipelineJobConfiguration.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/rulealtered/yaml/YamlRuleAlteredJobConfiguration.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/PipelineJobAPI.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/RuleAlteredJobAPI.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/RuleAlteredJobAPIImpl.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryIncrementalTasksRunner.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJobWorker.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/test/java/org/apache/shardingsphere/data/pipeline/core/fixture/RuleAlteredJobAPIFixture.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/api/impl/RuleAlteredJobAPIImplTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/util/JobConfigurationBuilder.java

- Extract start job method to PipelineJobAPI and AbstractPipelineJobAPIImpl
- Rename getJobConfig; Rename extendJobConfiguration

Extract start job method to PipelineJobAPI for common usage

---

shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/listener/PipelineContextManagerLifecycleListener.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/PipelineJobWorker.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/rulealtered/RuleAlteredJobWorker.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/resources/META-INF/services/org.apache.shardingsphere.mode.manager.listener.ContextManagerLifecycleListener

Fixes #20127 .
- Rename RuleAlteredContextManagerLifecycleListener to PipelineContextManagerLifecycleListener
- Move PipelineContextManagerLifecycleListener to org.apache.shardingsphere.data.pipeline.core.listener package
- Add PipelineJobWorker class and Move initWorkerIfNecessary method from RuleAlteredJobWorker to PipelineJobWorker

Refactor RuleAlteredContextManagerLifecycleListener for common usage

---

shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-namespace/pom.xml
shardingsphere-proxy/shardingsphere-proxy-backend/pom.xml
shardingsphere-proxy/shardingsphere-proxy-bootstrap/pom.xml

Fixes #19913.
- Remove unnecessary import for standalone-mode-repository-jdbc-h2 module

Remove unnecessary import for standalone-mode-repository-jdbc-h2 module

---

pom.xml

Revise #11629.
The parameter `aggregate` has been deprecated since 2.5 and removed in 3.x.
https://github.com/apache/maven-javadoc-plugin/blob/95f7724c0b8382256caaa294e1a36e6e3a466aab/src/main/java/org/apache/maven/plugin/javadoc/AbstractJavadocMojo.java#L441-L448

Remove nonexistent parameter from maven-javadoc-plugin

---

shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/OracleSchemaMetaDataLoader.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/orderby/item/ExpressionOrderByItemConverter.java
shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/converter/segment/orderby/item/OrderByItemConverterUtil.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineDistributedBarrier.java
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
shardingsphere-test/shardingsphere-optimize-test/src/test/java/org/apache/shardingsphere/infra/federation/converter/parameterized/engine/SQLNodeConvertEngineParameterizedTest.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/dml/select-aggregate.xml

Ref https://github.com/apache/shardingsphere/issues/19580.
- optimize PostgreSQL, openGauss order by item parse logic
- support convert order by item segment to SqlNode

Optimize PostgreSQL, openGauss order by item parse and convert to SqlNode

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/BaseRule.g4
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/dml/select.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/dml/select.xml

Fixes #19795 .
- support like operator with escape 
-
-

support like operator with escape for postgres

---

shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/instance/ComputeNodeInstance.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/listener/SessionConnectionListener.java

Fixes #20155.
- Optimize worker-id generate when proxy is re-registered in cluster mode

Optimize worker-id generate when proxy is re-registered in cluster mode

---

shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/generator/PipelineDDLGenerator.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/datasource/AbstractDataSourcePreparer.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/datasource/PrepareTargetTablesParameter.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobPreparer.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/prepare/datasource/MySQLDataSourcePreparer.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/prepare/datasource/OpenGaussDataSourcePreparer.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/prepare/datasource/PostgreSQLDataSourcePreparer.java

Revise #20207
-  Improve DDL generate.

Improve DDL genereate method at migration prepare

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/MigrateTableUpdater.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.distsql.update.RALUpdater
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/antlr4/imports/migration/Keyword.g4
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/antlr4/imports/migration/RALStatement.g4
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/java/org/apache/shardingsphere/migration/distsql/parser/core/MigrationDistSQLStatementVisitor.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-statement/src/main/java/org/apache/shardingsphere/migration/distsql/statement/MigrateTableStatement.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/migration/UpdatableScalingRALStatementAssert.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/migration/update/MigrateTableStatementAssert.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/migration/MigrateTableStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ral/migration.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ral/migration.xml

- Add MIGRATE TABLE DistSQL parsing, e.g. MIGRATE TABLE ds_0.t_order INTO sharding_db.t_order;

Add MIGRATE TABLE DistSQL parsing

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/data/pipeline/ShardingRuleAlteredJobConfigurationPreparer.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/converter/ShardingScalingRuleStatementConverter.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/test/java/org/apache/shardingsphere/scaling/distsql/handler/query/ShardingScalingRulesQueryResultSetTest.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/config/rule/data/pipeline/PipelineProcessConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/config/rule/data/pipeline/PipelineReadConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/config/rule/data/pipeline/PipelineWriteConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/config/rule/rulealtered/OnRuleAlteredActionConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/pojo/data/pipeline/YamlPipelineProcessConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/pojo/data/pipeline/YamlPipelineReadConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/pojo/data/pipeline/YamlPipelineWriteConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/pojo/rule/YamlOnRuleAlteredActionConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/data/pipeline/YamlPipelineInputConfigurationSwapper.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/data/pipeline/YamlPipelineOutputConfigurationSwapper.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/data/pipeline/YamlPipelineProcessConfigurationSwapper.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/data/pipeline/YamlPipelineReadConfigurationSwapper.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/data/pipeline/YamlPipelineWriteConfigurationSwapper.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/rulealtered/YamlOnRuleAlteredActionConfigurationSwapper.java
shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/data/pipeline/YamlPipelineProcessConfigurationSwapperTest.java
shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/rulealtered/YamlOnRuleAlteredActionConfigurationSwapperTest.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/context/PipelineProcessContext.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/DataConsistencyChecker.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/context/AbstractPipelineProcessContext.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/InventoryTaskSplitter.java

- Rename PipelineProcessConfiguration related input and output to read and write, and also Yaml config and swapper
OnRuleAlteredActionConfiguration won't be changed for now, and also related DistSQL, else scaling IT can not pass. We'll refactor it later.

Rename PipelineProcessConfiguration related input and output to read and write

---

shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/job/JobType.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/PipelineAPIFactory.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/GovernanceRepositoryAPIImpl.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/constant/DataPipelineConstants.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/PipelineJobExecutor.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNode.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJob.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/test/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNodeTest.java

- Refactor pipeline job path in registry center; Compatible with ejob namespace
- Improve PipelineMetaDataNode and unit test, PipelineJobExecutor pattern
```
pipeline/
jobs/
```

Refactor pipeline job path in registry center

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/AddMigrationSourceResourceUpdater.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/ApplyMigrationUpdater.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/DropMigrationUpdater.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/MigrateTableUpdater.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/ResetMigrationUpdater.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/RestoreMigrationSourceWritingUpdater.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/StartMigrationUpdater.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/StopMigrationSourceWritingUpdater.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/StopMigrationUpdater.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/distsql/update/RALUpdater.java
shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/fixture/FixtureRALUpdater.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/migration/update/UpdatableMigrationRALBackendHandler.java

Purpose:
- Support `add migration source resource` and `migrate table` DistSQL to get current logical database
- RALUpdater, add databaseName parameter; And also UpdatableMigrationRALBackendHandler, RALBackendHandlerFactory

Refactor RALUpdater, add databaseName parameter

---

shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/database/ShardingSphereDatabase.java
shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/metadata/database/ShardingSphereDatabaseTest.java

Fixes #20287.
- fix wrong singleTableDataNodes when execute reloadRules

Fix wrong singleTableDataNodes when execute reloadRules

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/AddMigrationSourceResourceUpdater.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNode.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/test/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNodeTest.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/migration/query/QueryableScalingRALBackendHandler.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/migration/query/QueryableScalingRALBackendHandlerFactory.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/migration/update/UpdatableScalingRALBackendHandler.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/migration/query/QueryableScalingRALBackendHandlerFactoryTest.java

- Recover RAL backend handler class name
- Remove checkDatabaseName in UpdatableScalingRALBackendHandler. Reivse previous PR 20286

Recover RAL backend handler class name and checkDatabaseName

---

shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/migration/query/QueryableScalingRALBackendHandler.java

Fixes #20290.
- Change QueryableScalingRALBackendHandler extends hierarchy, from `extends DatabaseRequiredBackendHandler` to `implements ProxyBackendHandler`

Make scaling query DistSQL could be executed when no database selected

---

shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/pojo/data/pipeline/YamlPipelineProcessConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/pojo/data/pipeline/YamlPipelineReadConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/pojo/data/pipeline/YamlPipelineWriteConfiguration.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/MigrationJobPublicAPI.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/PipelineJobPublicAPI.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/GovernanceRepositoryAPI.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/PipelineMetaDataPersistService.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/GovernanceRepositoryAPIImpl.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/PipelineDataSourcePersistService.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/PipelineProcessConfigurationPersistService.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/context/AbstractPipelineProcessContext.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/PipelineMetaDataException.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNode.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineProcessConfigurationUtils.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/test/java/org/apache/shardingsphere/data/pipeline/core/fixture/MigrationJobAPIFixture.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/api/impl/MigrationJobAPIImplTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/api/impl/PipelineProcessConfigurationPersistServiceTest.java

Part of #19421. And also to implement new feature for migration job.
- Extract PipelineMetaDataPersistService interface, used for `dataSources` and `processConfig` impl; Refactor dataSources impl; Add processConfig impl PipelineProcessConfigurationPersistService
- Impl create/alter/show ProcessConfiguration in pipeline job API

Impl create/alter/show ProcessConfiguration in pipeline job API

---

shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineProcessConfigurationUtils.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJob.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobItemContext.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/api/impl/GovernanceRepositoryAPIImplTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/api/impl/MigrationJobAPIImplTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/DataConsistencyCheckerTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/prepare/InventoryTaskSplitterTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/task/IncrementalTaskTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryTaskTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineContextUtil.java

- Refactor MigrationJobItemContext for better unit test
- Read process config from registry center on buildPipelineProcessContext

Refactor MigrationJobItemContext for better unit test

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/MigrateTableUpdater.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/antlr4/imports/migration/RALStatement.g4
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/java/org/apache/shardingsphere/migration/distsql/parser/core/MigrationDistSQLStatementVisitor.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-statement/src/main/java/org/apache/shardingsphere/migration/distsql/statement/MigrateTableStatement.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/pojo/CreateMigrationJobParameter.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/migration/update/MigrateTableStatementAssert.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/migration/MigrateTableStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ral/migration.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ral/migration.xml

Related to #20270.
e.g.
```
MIGRATE TABLE ds_0.public.t_order INTO sharding_db.t_order;
```
- Add schema support for MIGRATE TABLE DistSQL

MIGRATE TABLE DistSQL support define schema name

---

docs/community/content/contribute/contributor.en.md

correct [dev list]link to `TEAM`
Fixes https://github.com/apache/shardingsphere/issues/20405
- Fix `Developer List` link error in https://shardingsphere.apache.org/community/en/contribute/contributor/#developer-flow 
-
-

[Doc Error]correct [dev list]link

---

shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/response/header/query/impl/MySQLQueryHeaderBuilder.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/response/header/query/impl/MySQLQueryHeaderBuilderTest.java

Fixes #20437.
-When the logical table is empty, the primary key should be verified from the physical table

fix navicat throw "There is no primary key here." (#20437)

---

shardingsphere-distsql/shardingsphere-distsql-parser/src/main/antlr4/imports/RALStatement.g4
shardingsphere-distsql/shardingsphere-distsql-parser/src/main/antlr4/org/apache/shardingsphere/distsql/parser/autogen/KernelDistSQLStatement.g4
shardingsphere-distsql/shardingsphere-distsql-parser/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java
shardingsphere-distsql/shardingsphere-distsql-statement/src/main/java/org/apache/shardingsphere/distsql/parser/statement/ral/updatable/DropMigrationProcessConfigurationStatement.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/pojo/data/pipeline/YamlPipelineProcessConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/pojo/data/pipeline/YamlPipelineReadConfiguration.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/yaml/config/pojo/data/pipeline/YamlPipelineWriteConfiguration.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/PipelineJobPublicAPI.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineProcessConfigurationUtils.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/test/java/org/apache/shardingsphere/data/pipeline/core/fixture/MigrationJobAPIFixture.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/test/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineProcessConfigurationUtilsTest.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/DropMigrationProcessConfigurationUpdater.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.distsql.update.RALUpdater
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/migration/UpdatableScalingRALStatementAssert.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/migration/update/DropMigrationProcessConfigurationStatementAssert.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/migration/DropMigrationProcessConfigurationStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ral/migration.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ral/migration.xml

- Add DROP MIGRATION PROCESS CONFIGURATION DistSQL parsing, e.g. `DROP MIGRATION PROCESS CONFIGURATION '/READ/RATE_LIMITER';`
- Add API impl

Add DROP MIGRATION PROCESS CONFIGURATION DistSQL and api impl

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/MigrateTableUpdater.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/datasource/AbstractDataSourcePreparer.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/datasource/PrepareTargetTablesParameter.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryIncrementalTasksRunner.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJob.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobPreparer.java

Purpose:
- If there's condition will cause error, then fail-fast. 2 special cases were verified.
- Improve case 1: No target database is defined
- Improve case 2: Source table name and target table name are different

Add pre-check for migration job to fail-fast

---

shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/model/ExecuteProcessContext.java
shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/model/ExecuteProcessUnit.java
shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/model/yaml/BatchYamlExecuteProcessContext.java
shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/model/yaml/YamlExecuteProcessContext.java
shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/process/GovernanceExecuteProcessReporter.java
shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/process/ShowProcessListManager.java
shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/process/GovernanceExecuteProcessReporterTest.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/ClusterContextManagerCoordinator.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/ClusterContextManagerCoordinatorTest.java

Ref #20531.
- use Map instead of Collection to optimize processUnits call performance
- move processStatements foreach to ExecuteProcessContext
- use ExecuteProcessContext instead of YamlExecuteProcessContext in ShowProcessListManager
- remove useless logic for report method after sql units execute

Reduce foreach call times and object create times

---

.github/workflows/it.yml

Purpose:
- When Integration Test workflow is changed (it.yml), it might cause `shardingsphere-integration-test-suite` module run Integration Test in Continuous Integration, but this module's Continuous Integration won't be triggered for now. So if we do not check it, then it might cause issue after PR is merged, e.g. #20556.
- Verify Suite CI Run in IT

Verify Suite CI Run in IT

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/PostgreSQLStatementParser.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/postgresql/ddl/PostgreSQLAlterTriggerStatement.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/alter-trigger.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/alter-trigger.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml

Ref #17848 
- Proofread `ALTER TRIGGER` grammar
- Support Parsing `ALTER TRIGGER` in PostgreSQL
- Adds tests

Support Parsing `ALTER TRIGGER` in PostgreSQL

---

shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLCharacterSet.java
shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/test/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLCharacterSetTest.java
shardingsphere-dialect-exception/shardingsphere-dialect-exception-core/src/main/java/org/apache/shardingsphere/dialect/exception/connection/UnknownCollationException.java
shardingsphere-dialect-exception/shardingsphere-mysql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/mysql/mapper/MySQLDialectExceptionMapper.java
shardingsphere-dialect-exception/shardingsphere-mysql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/mysql/vendor/MySQLVendorError.java
shardingsphere-dialect-exception/shardingsphere-mysql-dialect-exception/src/test/java/org/apache/shardingsphere/dialect/mysql/mapper/MySQLDialectExceptionMapperTest.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/mysql/executor/MySQLSetCharsetExecutor.java
shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/authentication/MySQLAuthenticationEngine.java

Add UnknownCollationException

---

shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/parser/ParserErrorListener.java
shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/parser/SQLParserExecutor.java

Fixes #18455 .
-  add sql parser error detail to ParseCancellationException
the error msg like this:
Error Code: 11000. You have an error in your SQL syntax: select 4 as expected, /* 1 + /*!01000 8 + */ 2 + */ 4 LIMIT 0, 1000 ;syntax error at line 1, position 49, near [@8,49:49='*',<18>,1:49], no viable alternative at input 'select4asexpected,/* 1 + /*!01000 8 + */2+*'

add sql parser error detail to ParseCancellationException

---

shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/constant/DistSQLScriptConstants.java
shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/parser/SQLParserErrorListener.java
shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/parser/SQLParserExecutor.java

Ref #20662.
- Optimize SQLParserErrorListener code style
```
mysql> select * from t_order where order_id = 1 likee 1;
ERROR 11000 (42000): You have an error in your SQL syntax: select * from t_order where order_id = 1 likee 1, no viable alternative at input '=1likee' at line 1, position 41, near [@8,41:45='likee',<780>,1:41]
mysql> java;
ERROR 11000 (42000): You have an error in your SQL syntax: java, no viable alternative at input 'java' at line 1, position 0, near [@0,0:3='java',<780>,1:0]
```

Optimize SQLParserErrorListener code style

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/DDLStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/PostgreSQLKeyword.g4

For #17844 
- Add a missing keyword for `cursorOption` in [PostgreSQL Declare Statement](https://www.postgresql.org/docs/current/sql-declare.html).

Add a missing keyword in PostgreSQL Declare Statement

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/rule/TableRule.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/rule/TableRuleTest.java

Fixes #20746.
- fix binding table check exception when sharding table ends with number

Fix binding table check exception when sharding table ends with number

---

shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/DropSchemaStatementHandlerTest.java

Add more unit test for DropSchemaStatementHandler

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/InsertStatementHandler.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/postgresql/dml/PostgreSQLInsertStatement.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/dml/insert.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/dml/insert.xml

Fixes #20506 .
- add support for parse OptOnConflict for postgres
- add parser visitor
-add test case
and run the test case provided by the issue, insert successfully.

add support for parse OptOnConflict for postgres

---

shardingsphere-infra/shardingsphere-infra-rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/InsertValue.java
shardingsphere-infra/shardingsphere-infra-rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/InsertValueTest.java

Related to #20797.
The parameter index was minus 1 in SQL parser, so we need to plus 1 when rewriting SQL.

Set proper index for PostgreSQL positional parameters

---

.github/workflows/ci.yml
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationJobStatusQueryResultSet.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/ingest/DumperConfiguration.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/context/PipelineJobItemContext.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/job/progress/InventoryIncrementalJobItemProgress.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/job/progress/JobItemIncrementalTasksProgress.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/InventoryIncrementalJobItemAPIImpl.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlInventoryIncrementalJobItemProgress.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlInventoryIncrementalJobItemProgressSwapper.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlJobItemIncrementalTasksProgress.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlJobItemIncrementalTasksProgressSwapper.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/PipelineJobPreparerUtils.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobItemContext.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationTaskConfiguration.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/job/progress/InventoryIncrementalJobItemProgressTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlInventoryIncrementalJobItemProgressSwapperTest.java
shardingsphere-test/shardingsphere-pipeline-test/src/test/resources/job-progress-all-finished.yaml
shardingsphere-test/shardingsphere-pipeline-test/src/test/resources/job-progress-failure.yaml
shardingsphere-test/shardingsphere-pipeline-test/src/test/resources/job-progress-running.yaml
shardingsphere-test/shardingsphere-pipeline-test/src/test/resources/job-progress.yaml

Part of #19421.
- Move dataSourceName from YamlJobItemIncrementalTasksProgress to InventoryIncrementalJobItemProgress
- Simplify JobItemIncrementalTasksProgress
- Add dataSourceName in JobItemContext and MigrationTaskConfiguration
---

Refactor dataSourceName in job item progress structure

---

shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/PipelineJobWorker.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNodeWatcher.java

Fixes #20885.
- Rename PipelineJobExecutor to PipelineMetaDataNodeWatcher
- Move PipelineMetaDataNodeWatcher to package `org.apache.shardingsphere.data.pipeline.core.metadata.node`
---

Rename and move PipelineJobExecutor

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleDropIndexTypeStatement.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/ddl/DropIndexTypeStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/drop-index-type.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/drop-index-type.xml

Ref https://github.com/apache/shardingsphere/issues/6480 
- Add DROP INDEX TYPE grammar
- Support parsing DROP INDEX TYPE in Oracle
- Add test
---

Support parsing DROP INDEX TYPE in Oracle

---

shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-executor/shardingsphere-sql-federation-executor-advanced/src/main/java/org/apache/shardingsphere/sqlfederation/advanced/resultset/FederationResultSetMetaData.java

Fixes #20987.
- fix Cannot find JDBC type '0' in PostgreSQL column type exception
---

Fix Cannot find JDBC type '0' in PostgreSQL column type exception

---

shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-env/src/test/java/org/apache/shardingsphere/test/integration/env/container/atomic/storage/config/impl/StorageContainerConfigurationFactory.java
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-env/src/test/java/org/apache/shardingsphere/test/integration/env/container/atomic/storage/config/impl/mysql/MySQLContainerConfigurationFactory.java
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/framework/container/compose/DockerContainerComposer.java
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/util/DockerImageVersion.java
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/resources/env/mysql/mysql8/my.cnf

- Add MySQL auth plugin case at migration IT
---

Add MySQL 8 auth plugin case at migration IT

---

shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SQLUtilTest.java

Add unit tests for the following Methods: isReadOnly, trimComment, trimSemicolon
Fixes #20362.
- Add test for isReadOnly
- Add test for trimComment
- Add test for trimSemiColon
---

20362 Add More Unit Tests for SQLUtil to increase coverage

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleDropPluggableDatabaseStatement.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/ddl/DropPluggableDatabaseStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/drop-pluggable-database.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/drop-pluggable-database.xml

Ref https://github.com/apache/shardingsphere/issues/6480
- Add `DROP PLUGGABLE DATABASE` grammar
- Support parsing `DROP PLUGGABLE DATABASE` in Oracle
- Add test
---

Support parsing DROP PLUGGABLE DATABASE in Oracle

---

CODE_OF_CONDUCT.md
docs/community/content/involved/conduct/code.cn.md
docs/community/content/involved/conduct/code.en.md

Fixes #19845.
- Update CODE_OF_CONDUCT about `assertThat`.
---

Update CODE_OF_CONDUCT about assertThat

---

shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceChecker.java
shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceCheckerTest.java

- Fix PostgreSQL check data source permission when using rolsuper
---

Fix PostgreSQL check data source permission when using rolsuper

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/AddMigrationSourceResourceUpdater.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/CommitMigrationUpdater.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/RollbackMigrationUpdater.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/distsql/update/RALUpdater.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/migration/query/QueryableScalingRALBackendHandler.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/migration/update/UpdatableScalingRALBackendHandler.java

- Recover throw SQLException for ScalingRALBackendHandler and RALUpdater execute method
---

Recover throw SQLException for ScalingRALBackendHandler and RALUpdater execute method

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/ShardingSQLRouter.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/ShardingRouteEngineFactory.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/unicast/ShardingUnicastRoutingEngine.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/ShardingRouteEngineFactoryTest.java
shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/unicast/ShardingUnicastRoutingEngineTest.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/context/ConnectionContext.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/context/datasource/PreferredDataSourceProvider.java
shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/CacheableExecutorConnectionManager.java
shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ConnectionManager.java
shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/JDBCBackendConnection.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/session/ConnectionSession.java
shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/JDBCBackendConnectionTest.java

Fixes #21125.
Query of broadcast table will be routed randomly.
Query of broadcast table reused cached connections.

Reuse cached connections as possible when unicast sharding

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleDropLibraryStatement.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/ddl/DropLibraryStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/drop-library.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/drop-library.xml

Ref https://github.com/apache/shardingsphere/issues/6480
- Add `DROP LIBRARY`  grammar
- Support parsing `DROP LIBRARY` in Oracle
- Add test
---

Support parsing DROP LIBRARY in Oracle

---

.github/PULL_REQUEST_TEMPLATE
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-showprocesslist/src/test/java/org/apache/shardingsphere/test/integration/showprocesslist/container/composer/ClusterShowProcessListContainerComposer.java
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/container/config/ProxyClusterContainerConfigurationFactory.java
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/container/config/ProxyStandaloneContainerConfigurationFactory.java

- refactor some constants
- change the default option for pre-check.
---

Refactor : refactor some constants and change the default option for PR template

---

shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/ShardingRouteEngineFactory.java
shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/decorator/model/ShardingSphereSchema.java
shardingsphere-infra/shardingsphere-infra-context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/CreateViewStatementSchemaRefresher.java
shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/decider/SingleTableSQLFederationDecider.java
shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/test/java/org/apache/shardingsphere/singletable/decider/SingleTableSQLFederationDeciderTest.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-executor/shardingsphere-sql-federation-executor-advanced/src/main/java/org/apache/shardingsphere/sqlfederation/advanced/AdvancedSQLFederationExecutor.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-executor/shardingsphere-sql-federation-executor-core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/FilterableTableScanExecutor.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-executor/shardingsphere-sql-federation-executor-core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/TranslatableTableScanExecutor.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-executor/shardingsphere-sql-federation-executor-original/src/main/java/org/apache/shardingsphere/sqlfederation/original/OriginalSQLFederationExecutor.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/expander/ShardingSphereViewExpander.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/filter/FilterableDatabase.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/filter/FilterableSchema.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/filter/FilterableTable.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/translatable/FederationTranslatableTable.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/util/SQLFederationDataTypeUtil.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/util/SQLFederationPlannerUtil.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLOptimizeEngineTest.java
shardingsphere-test/shardingsphere-rewrite-test/src/test/resources/scenario/sharding/config/sharding-rule.yaml

Ref #19580.
- use ShardingUnicastRoutingEngine for sql federation create view, alter view and drop view statement
- correct create view metadata refresh logic
- add sql federation decide logic for view
- register view metadata for sql federation
- add ShardingSphereViewExpander for expand view statement
---

Support view expand and execute for sql federation

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleDropMaterializedViewLogStatement.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleDropMaterializedViewStatement.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleDropMaterializedZonemapStatement.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/ddl/DropMaterializedViewLogStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/ddl/DropMaterializedZonemapStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/drop-materialized-view-log.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/drop-materialized-zonemap.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/drop-materialized-view-log.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/drop-materialized-zonemap.xml

Ref https://github.com/apache/shardingsphere/issues/6480
- Add `dropMaterializedView, dropMaterializedViewLog, dropMaterializedZonemap` grammar
- Support parsing `dropMaterializedView, dropMaterializedViewLog, and dropMaterializedZonemap` in Oracle
- Add test
---

Support parsing dropMaterializedView/ViewLog/Zonemap in Oracle

---

shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/FrontendChannelInboundHandler.java

For #20896.
- Fix finish connection if not exist executionId.
- Fix run `FrontendChannelInboundHandlerTest` occur error log.
```
Exception in thread "ShardingSphere-Command-0" java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111)
at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
at org.apache.shardingsphere.mode.process.ShowProcessListManager.removeProcessStatement(ShowProcessListManager.java:116)
at org.apache.shardingsphere.mode.process.GovernanceExecuteProcessReporter.reportRemove(GovernanceExecuteProcessReporter.java:78)
at org.apache.shardingsphere.infra.executor.sql.process.ExecutePr …
```

Fix finish connection if not exist executionId.

---

.github/workflows/ci-daily.yml

- change the scope for Windows long path solution
---

Refactor : change the scope for longpath solution since system scope doesn't work

---

docs/community/content/involved/release/elasticjob-ui.cn.md
docs/community/content/involved/release/elasticjob-ui.en.md
docs/community/content/involved/release/elasticjob.cn.md
docs/community/content/involved/release/elasticjob.en.md
docs/community/content/involved/release/shardingsphere-on-cloud.cn.md
docs/community/content/involved/release/shardingsphere-on-cloud.en.md
docs/community/content/involved/release/shardingsphere.en.md

Ref #21200.
- fix commmunity documnet build error according to wrong header format in on cloud release guide
---

Fix commmunity documnet build error according to wrong header format in on cloud release guide

---

shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-executor/shardingsphere-sql-federation-executor-advanced/src/main/java/org/apache/shardingsphere/sqlfederation/advanced/AdvancedSQLFederationExecutor.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/expander/ShardingSphereViewExpander.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/util/SQLFederationPlannerUtil.java
shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLOptimizeEngineTest.java
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/dql/dql-integration-test-cases.xml

Fixes #21220.
- add ENUMERABLE_LIMIT_RULE to support select limit statement when use sql federation
---

Add ENUMERABLE_LIMIT_RULE to support select limit statement when use sql federation

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-opengauss/src/main/antlr4/imports/opengauss/DMLStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/DMLStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
shardingsphere-test/shardingsphere-optimize-test/src/test/java/org/apache/shardingsphere/infra/federation/converter/parameterized/engine/SQLNodeConverterEngineParameterizedTest.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/dml/select-pagination.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/dml/select-pagination.xml

Fixes #21231.
Fixed #11025.
- support openGauss select offset, count statement parse
- remove useless syntax in PostgreSQL grammar
- add sql parse test case and sql node convert test case
---

Support openGauss select offset, count statement parse and remove useless syntax in PostgreSQL grammar

---

.github/workflows/ci-daily.yml
.github/workflows/ci.yml

Revise #21188.
#21188 broke the basic boundary testing of JDK compatibility of ShardingSphere.

Add Java 19 to ci.yml and Bump Java to 19 in ci-daily

---

shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java

- Use `null == xxx` instead of `null != xxx` for first priority
- Remove `else` or `else if` return in last code statement
---

For code format

---

shardingsphere-infra/shardingsphere-infra-binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/ddl/AlterViewStatementContextTest.java
shardingsphere-infra/shardingsphere-infra-context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/AlterViewStatementSchemaRefresher.java
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-sqlserver/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/SQLServerStatement.g4
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/impl/SQLServerDDLStatementSQLVisitor.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/ddl/AlterViewStatement.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/AlterViewStatementHandler.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/ddl/MySQLAlterViewStatement.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/sqlserver/ddl/SQLServerAlterViewStatement.java
shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/AlterViewStatementHandlerTest.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/ddl/DDLStatementAssert.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/ddl/impl/AlterViewStatementAssert.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/ddl/impl/CreateViewStatementAssert.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/ddl/impl/DropViewStatementAssert.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/ddl/AlterViewStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/ddl/DropViewStatementTestCase.java
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/alter-view.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/drop-view.xml
shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/alter-view.xml

Fixes #21230.
Ref https://github.com/apache/shardingsphere/issues/19580.
- optimize alter view/drop view parse logic
- add assert logic for alter view/drop view
- add test case for alter view definition
- fix alter view refresher bug
---

Optimize alter view/drop view parse logic and fix alter view refresher bug

---

shardingsphere-mode/shardingsphere-mode-type/pom.xml
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/pom.xml
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/pom.xml
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/ConsulRepository.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/ShardingSphereConsulClient.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/ShardingSphereQueryParams.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/lock/ConsulInternalLockHolder.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/lock/ConsulInternalLockProvider.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/props/ConsulProperties.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/props/ConsulPropertyKey.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/main/resources/META-INF.services/org.apache.shardingsphere.mode.repository.cluster.ClusterPersistRepository
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/test/java/org/apache/shardingsphere/mode/repository/cluster/consul/ConsulRepositoryTest.java
shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/test/java/org/apache/shardingsphere/mode/repository/cluster/consul/props/ConsulPropertiesTest.java

New feature for support consul register center， so far 5.2.1 shardingsphere cluster mode repository support zk,etcd,nacos,but not support consul, but consul is very welcome used config center,so support consul is more perfect
- config support persist to consul
- lock implements by consul and support reentrant
- support watch key update,add,delete event
- support persist ephemeral node
---

Cluster mode repository support consul register center

---

distribution/proxy/src/main/release-docs/LICENSE
proxy/bootstrap/pom.xml

- Add license declare for Nacos and its dependencies
---

Add license declare for Nacos and its dependencies

---

distribution/proxy/src/main/release-docs/LICENSE
infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/YamlEngine.java
infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/constructor/ShardingSphereYamlConstructor.java
infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/representer/ShardingSphereYamlRepresenter.java
infra/util/src/test/java/org/apache/shardingsphere/infra/util/yaml/representer/ShardingSphereYamlRepresenterTest.java
pom.xml

Fixes #21048.
- Update Snakeyaml to 1.33 to open 3MB limit . Refer to https://bitbucket.org/snakeyaml/snakeyaml/issues/553/loaderoptionssetcodepointlimit-not-honored .
- Maybe related to https://github.com/apache/shardingsphere/issues/21211, https://github.com/apache/shardingsphere/issues/21083 .
---

Update Snakeyaml to 1.33 and open YAML 3MB limit

---

distribution/proxy/src/main/release-docs/LICENSE
proxy/bootstrap/pom.xml

Reverts apache/shardingsphere#21343
The dependencies are too heavy.
Nacos is optional for ShardingSphere, I just revert this PR.

Revert "Add license declare for Nacos and its dependencies"

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationProjection.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationProjectionTest.java
kernel/sql-federation/executor/advanced/src/main/java/org/apache/shardingsphere/sqlfederation/advanced/resultset/SQLFederationResultSet.java
kernel/sql-federation/executor/advanced/src/test/java/org/apache/shardingsphere/sqlfederation/advanced/result/SQLFederationResultSetTest.java
kernel/sql-federation/optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLOptimizeEngineTest.java
src/resources/checkstyle.xml
test/integration-test/test-suite/src/test/resources/cases/dql/dql-integration-test-cases.xml

Fixes #21379.
- fix wrong column label when execute aggregation function with PostgreSQL/openGauss database
- add unit test and integration test
- modify checkstyle static import
---

Fix wrong column label when execute aggregation function with PostgreSQL/openGauss database

---

docs/blog/content/material/committer.en.md
docs/blog/content/material/proxy.en.md

Hello from Hacktoberfest :)
The link to github.com/sharding-sphere/sharding-sphere/ is vulnerable to repojacking (it redirects to the orignial project that changed name), you should change the link to the current name of the project. if you won't change the link, an attacker can open the linked repository and attacks users that trust your links

Change link of repojacking vulnerable link

---

.github/workflows/ci.yml
.github/workflows/nightly-ci.yml

Fixes #21404 .
- move javadoc test from ci to nightly ci
- refactor the ci install to concurrent
---

Refactor : move some jobs take time from ci to nightly ci

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/decider/ShardingSQLFederationDecider.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/decider/ShardingSQLFederationDeciderTest.java
test/integration-test/test-suite/src/test/resources/cases/dql/dql-integration-test-cases.xml

Fixes #21384.
- adjust sharding sql federation decider logic when execute cross join with pagination
- add unit test and integration test
---

Adjust sharding sql federation decider logic when execute cross join with pagination

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/decider/ShardingSQLFederationDecider.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementContext.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/SQLNodeConverterEngine.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/type/CombineOperatorConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/util/SQLFederationPlannerUtil.java
kernel/sql-federation/optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/type/CombineOperatorConverterTest.java
sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/dml/SelectStatement.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtil.java
sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtilTest.java
test/optimize/src/test/java/org/apache/shardingsphere/infra/federation/converter/parameterized/engine/SQLNodeConverterEngineParameterizedTest.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/dml/impl/SelectStatementAssert.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/dml/SelectStatementTestCase.java
test/parser/src/main/resources/case/ddl/create-view.xml
test/parser/src/main/resources/case/dml/select-union.xml

Fixes #21420.
- support select intersect, except statement in sql federation
- refactor combine operator parse
---

Support select intersect, except statement in sql federation and refactor combine operator parse

---

docs/document/content/user-manual/shardingsphere-proxy/observability/_index.cn.md
docs/document/content/user-manual/shardingsphere-proxy/observability/_index.en.md

Fixes #20936.
- Add simple methods for use in container environments in the observability section
---

Add simple methods for use in container environments in the observability section

---

kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/FilterableTableScanExecutor.java
kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/TranslatableTableScanExecutor.java
kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/row/SQLFederationRowEnumerator.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/SQLNodeConverterEngine.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/statement/select/SelectStatementConverter.java
mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/fixture/ClusterPersistRepositoryFixture.java
proxy/bootstrap/src/test/java/org/apache/shardingsphere/proxy/fixture/ClusterPersistRepositoryFixture.java
test/integration-test/test-suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
test/optimize/src/test/java/org/apache/shardingsphere/infra/federation/converter/parameterized/engine/SQLNodeConverterEngineParameterizedTest.java
test/parser/src/main/resources/case/dml/select-union.xml
test/parser/src/main/resources/sql/supported/dml/select-union.xml

Fixes #21417.
- optimize combine statement convert logic when statement contains order by and limit
- optimize SQLFederationRowEnumerator logic for combine statement
- add unit test and integration test
---

Optimize combine statement convert logic and SQLFederationRowEnumerator logic

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckStatusQueryResultSet.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/InventoryIncrementalJobPublicAPI.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/check/consistency/DataConsistencyCheckResult.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/pojo/ConsistencyCheckJobProgressInfo.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/pojo/PipelineJobMetaData.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/InventoryIncrementalJobAPI.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractInventoryIncrementalJobAPIImpl.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/SingleTableInventoryDataConsistencyChecker.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobAPIImpl.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationDataConsistencyChecker.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/yaml/metadata/YamlPipelineColumnMetaData.java
test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/base/BaseITCase.java
test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/AbstractMigrationITCase.java
test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/api/impl/MigrationJobAPIImplTest.java
test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/util/JobConfigurationBuilder.java

Related to #21441.
- Revise show migration check status DistSQL impl
- Clean unused dataConsistencyCheck methods; Improve dataConsistencyCheck unit test
- Fix getJobProgressInfo
- Real test on 140 millions records table, fix issues
TODO
- Do CRC32_MATCH block by block, so there will be growing progress, but not from 0 just to 100 after a long time
---

Revise show migration check status DistSQL impl; Clean unused dataConsistencyCheck methods

---

kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/spi/check/consistency/DataConsistencyCalculateAlgorithm.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/AbstractDataConsistencyCalculateAlgorithm.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJob.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobAPIImpl.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckTasksRunner.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJob.java
test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/fixture/DataConsistencyCalculateAlgorithmFixture.java

- Fix getJobProgressInfo when check job is stopped
- Ignore exception persistence when check canceling
- Clean error message before checking
---

Improve consistency check job stop/cancel/progress

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckStatusQueryResultSet.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PipelineJobHasAlreadyFinishedException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobAPIImpl.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java

- Migration job stop cascade latest check job
- Start consistency check job do not throw exception when check job is finished
- Fix wrong column of remaining_seconds
- Ignore related consistency check job error on start/stop/commit/rollback
---

Migration job stop cascade latest consistency check job

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/DefaultImporter.java
kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClient.java

the merge method may merge INSERT and DELETE operations, so calculatate count before merge 
- Calculate processed records count before merged operation
- Improve mysql client reconnect
---

Improve processed records count calculatation at pipeline increment task.

---

examples/pom.xml

- upgrade the snakeyaml version to 1.33 in exmaple module to fix the compile error
---

Fix : upgrade the snakeyaml version to 1.33 in exmaple module to fix the compile error

---

.github/workflows/it.yml
test/integration-test/test-suite/src/test/java/org/apache/shardingsphere/test/integration/engine/ddl/BaseDDLIT.java
test/integration-test/test-suite/src/test/resources/cases/ddl/ddl-integration-test-cases.xml

Fixes #20932.
- Fix ddl initial SQL execute occasional exception in cluster mode
---

Fix ddl initial SQL execute occasional exception in cluster mode

---

.github/workflows/nightly-ci.yml

- revert the windows long name solution
---

Refactor : revert the windows long name solution

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/InlineShardingAlgorithm.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/InlineShardingAlgorithmTest.java

Fixes #18647.
- Fix inline sharding algorithm with big values
- Remove modification of expressions for negative numbers
---

Fix inline sharding algorithm with big values

---

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding.cn.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding.en.md

Change resourceName to dataNodeName for `dataNode`.

Fix wrong dataNode interpretation in RDL doc.

---

mode/type/cluster/repository/provider/zookeeper-curator/src/test/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/CuratorZookeeperRepositoryTest.java

Fixes #21434.
- Added test to return num of children set with multiple argument constructor
- Added test to return zero when using default constructor
---

Add unit tests to cover CuratorZookeeperRepository.getNumChildren method

---

proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/config/ProxyConfigurationLoader.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/config/ProxyConfigurationLoaderTest.java
proxy/backend/src/test/resources/conf/empty/server.yaml

Fixes #20457.
- Allow `server.yaml` configuration to be completely empty
- Allow the authority configuration to be null, use default root user
---

Fixes #20457, allows to start proxy without configuring authority rule.

---

docs/document/content/reference/distsql/syntax/rql/rule-query/sharding/show-default-sharding-strategy.cn.md
docs/document/content/reference/distsql/syntax/rql/rule-query/sharding/show-default-sharding-strategy.en.md

-Update RQL show default sharding strategy documents
---

Update RQL show default sharding strategy documents

---

agent/plugins/tracing/test/pom.xml
dialect-exception/postgresql/src/test/java/org/apache/shardingsphere/dialect/postgresql/message/ServerErrorMessageBuilderTest.java
distribution/proxy/src/main/release-docs/LICENSE
docs/document/content/user-manual/shardingsphere-proxy/startup/bin.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/bin.en.md
examples/pom.xml
infra/common/src/test/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesTest.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
kernel/transaction/type/xa/provider/atomikos/pom.xml
mode/type/cluster/repository/provider/etcd/src/main/java/org/apache/shardingsphere/mode/repository/cluster/etcd/EtcdRepository.java
pom.xml
proxy/frontend/reactive-core/src/test/java/org/apache/shardingsphere/proxy/frontend/reactive/protocol/ReactiveDatabaseProtocolFrontendEngineFactoryTest.java
test/common/pom.xml
test/integration-test/transaction/pom.xml
test/parser/pom.xml

For #21347.
- Introduce `junit-vintage-engine` to support unit testing inside GraalVM Native Image. Reference https://github.com/graalvm/native-build-tools/issues/53 .
- Update netty to `4.1.84` to get the new automatically generate native-image `conditional` metadata for `ChannelHandler` implementations. See https://github.com/netty/netty/pull/12794 .
- Update `logback` to match graalvm reachability metadata at https://github.com/oracle/graalvm-reachability-metadata/tree/master/metadata/ch.qos.logback/logback-classic/1.2.11 .
- Update `maven-surefire-plugin` to milestone version to automatically handle use of `org.junit.platform:junit-platform-launcher`. Reference https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#testing-support-v …

Update library to serve building GraalVM Native Image

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngine.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngineTest.java
infra/common/src/main/java/org/apache/shardingsphere/infra/exception/SchemaNotFoundException.java
kernel/single-table/core/src/main/java/org/apache/shardingsphere/singletable/route/validator/ddl/SingleTableDropSchemaMetadataValidator.java
kernel/single-table/core/src/test/java/org/apache/shardingsphere/singletable/route/validator/ddl/SingleTableDropSchemaMetadataValidatorTest.java

Fixes #19814.
```sql
postgres=> select * from t_order;
ERROR:  Cannot invoke "org.apache.shardingsphere.infra.metadata.database.schema.decorator.model.ShardingSphereSchema.getVisibleColumnNames(String)" because the return value of "java.util.Map.get(Object)" is null
```
```sql
postgres=> select * from t_order;
ERROR:  Schema `public` does not exist.
```
- Check schema exists before use it
---

Fix null exception for #19814

---

.github/workflows/nightly-graalvm-image.yml
distribution/proxy-native/Dockerfile
distribution/proxy-native/pom.xml
distribution/proxy-native/src/main/assembly/shardingsphere-proxy-native-binary-distribution.xml
distribution/proxy-native/src/main/release-docs/LICENSE
distribution/proxy-native/src/main/release-docs/NOTICE
distribution/proxy-native/src/main/release-docs/README.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-Janino.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-animal-sniffer.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-antlr4-runtime.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-asm.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-atomikos.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-bcprov-jdk15on.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-checker-qual.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-h2.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-jnanoid.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-jta.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-jts.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-logback.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-mchange-commons-java.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-opengauss-jdbc.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-perfmark.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-postgresql.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-protobuf-java.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-slf4j.txt
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-vertx-core.txt

For #21347.
- Add Release Profile for `distribution/proxy-native`.
- Update GraalVM Native Build Tools to `0.9.16`.
- Add the corresponding LICENSE.
- Fixes the wrong Docker Base Image in the Dockerfile, because the current GraalVM Native Build Tools is still using dynamic linking instead of static linking, which requires more system library support.
- Switched CI from https://github.com/graalvm/graalvm-ce-builds  to https://github.com/graalvm/graalvm-ce-dev-builds  for faster resolution of earlier issues. This is mainly because a series of fixes related to the file system for GraalVM Native Image is currently only in the dev build of GraalVM, and we need to verify it earlier. Issues like https://github.com/oracle/graal/issues/5020 and …

Add Release Profile for `distribution/proxy-native`

---

features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/api/config/rule/EncryptColumnRuleConfiguration.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptColumn.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptRule.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptTable.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/config/rule/YamlEncryptColumnRuleConfiguration.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/swapper/rule/YamlEncryptColumnRuleConfigurationSwapper.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/checker/AlgorithmProvidedEncryptRuleConfigurationCheckerTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/checker/EncryptRuleConfigurationCheckerTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dal/show/DecoratedEncryptShowCreateTableMergedResultTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dal/show/MergedEncryptShowCreateTableMergedResultTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/impl/EncryptAlterTableTokenGeneratorTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/impl/EncryptCreateTableTokenGeneratorTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/impl/EncryptProjectionTokenGeneratorTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptGeneratorBaseTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/EncryptColumnTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/EncryptRuleTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/rule/YamlEncryptColumnRuleConfigurationSwapperTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/rule/YamlEncryptTableRuleConfigurationSwapperTest.java
features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/converter/EncryptRuleStatementConverter.java
features/encrypt/spring/spring-namespace/src/main/java/org/apache/shardingsphere/encrypt/spring/namespace/parser/EncryptRuleBeanDefinitionParser.java
features/encrypt/spring/spring-namespace/src/main/java/org/apache/shardingsphere/encrypt/spring/namespace/tag/EncryptRuleBeanDefinitionTag.java
features/encrypt/spring/spring-namespace/src/main/resources/META-INF/namespace/encrypt.xsd

Ref #20435.
-add the fuzzyQueryColumn and fuzzyQueryEncryptorName
---

add the fuzzyQueryColumn and fuzzyQueryEncryptorName

---

features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/spi/context/EncryptContext.java
kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/ShardingSphereTransactionManagerEngine.java
kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/rule/TransactionRule.java
kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/rule/builder/TransactionRuleBuilder.java
kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/spi/ShardingSphereTransactionManager.java
kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/ConnectionTransactionTest.java
kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/ShardingSphereTransactionManagerEngineTest.java
kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/core/fixture/OtherShardingSphereTransactionManagerFixture.java
kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/core/fixture/ShardingSphereTransactionManagerFixture.java
kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/rule/TransactionRuleTest.java
kernel/transaction/distsql/handler/src/main/java/org/apache/shardingsphere/transaction/distsql/handler/update/AlterTransactionRuleStatementUpdater.java
kernel/transaction/distsql/handler/src/test/java/org/apache/shardingsphere/transaction/distsql/handler/query/TransactionRuleQueryResultSetTest.java
kernel/transaction/distsql/handler/src/test/java/org/apache/shardingsphere/transaction/distsql/handler/update/AlterTransactionRuleStatementUpdaterTest.java
kernel/transaction/type/base/seata-at/src/main/java/org/apache/shardingsphere/transaction/base/seata/at/SeataATShardingSphereTransactionManager.java
kernel/transaction/type/base/seata-at/src/test/java/org/apache/shardingsphere/transaction/base/seata/at/SeataATShardingSphereTransactionManagerTest.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/XAShardingSphereTransactionManager.java
kernel/transaction/type/xa/core/src/test/java/org/apache/shardingsphere/transaction/xa/XAShardingSphereTransactionManagerTest.java

Ref #21481.
- support heterogeneous databases in single logic database for TransactionRule init
- remove useless instanceContent in TransactionRule
---

Support heterogeneous databases in single logic database for TransactionRule init

---

.github/workflows/nightly-build.yml

For #21347.
- Fix nightly builds of GraalVM Native Image .
- The Log at https://github.com/apache/shardingsphere/actions/runs/3298856474/jobs/5441511861 shows that the CI of GraalVM Native Image is broken.  This question first came from https://github.com/apache/shardingsphere/pull/21677. 
- Refer to https://github.com/apache/shardingsphere/issues/21347#issuecomment-1287302217 .
---

Fix nightly builds of GraalVM Native Image

---

kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/executor/AbstractLifecycleExecutor.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/GovernanceRepositoryAPIImpl.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/DefaultImporter.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/InventoryDumper.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/IncrementalTask.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryIncrementalTasksRunner.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryTask.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckTasksRunner.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJob.java

- Improve migration job stopping. 1) Dumping data on DB, 2) Importing data on DB, 3) Blocking on queue, 4) Job onFailure on any of task failure, 5) Stop whole job in cluster on failure but not just current instance.
---

Improve migration job stopping

---

proxy/bootstrap/src/main/java/org/apache/shardingsphere/proxy/version/ShardingSphereProxyVersion.java
proxy/bootstrap/src/test/java/org/apache/shardingsphere/proxy/version/ShardingSphereProxyVersionTest.java
proxy/bootstrap/src/test/resources/META-INF/services/org.apache.shardingsphere.proxy.frontend.spi.DatabaseProtocolFrontendEngine

Fixes #21769.
- fix no spi implement exception when config different protocolType and storageType
---

Fix no spi implement exception when config different protocolType and storageType

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java

in order to register before `updateJobConfiguration`, make sure parent node already persist
- Improve pipeline barrier register time
-
-
---

Improve pipeline barrier register time

---

jdbc/spring/core/spring-boot-starter/src/main/java/org/apache/shardingsphere/spring/boot/ShardingSphereAutoConfiguration.java
jdbc/spring/core/spring-boot-starter/src/main/java/org/apache/shardingsphere/spring/boot/rule/LocalRulesCondition.java
jdbc/spring/core/spring-boot-starter/src/main/java/org/apache/shardingsphere/spring/boot/rule/ShardingSphereSpringBootCondition.java
jdbc/spring/core/spring-boot-starter/src/test/java/org/apache/shardingsphere/spring/boot/SpringBootStarterWithoutRulesTest.java
jdbc/spring/core/spring-boot-starter/src/test/resources/application-no-rules.properties

Fixes #21775.
- Modify `SHARDING_PREFIX` in `LocalRulesCondition` to make springboot application startup successfully with no rules.
---

fix issue: startup application with springboot failed when no rules config.

---

sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
test/parser/src/main/resources/case/ddl/create-table.xml
test/parser/src/main/resources/sql/supported/ddl/create-table.xml

Fix oracle parsing does not support varchar2 specified type
Fixes #21805.
-  Fix oracle parsing does not support varchar2 specified type
---

 Fix oracle parsing does not support varchar2 specified type(#21805)

---

sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Comments.g4
test/parser/src/main/resources/case/dml/select.xml
test/parser/src/main/resources/sql/supported/dml/select-comment.xml

Fix oracle parse comment without whitespace.

---

sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4
test/parser/src/main/resources/case/dml/select.xml
test/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #21804.
- Support oracle listagg function and start with connect by claus parse
---

Support oracle listagg function and start with connect by claus parse

---

test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/createtable/CreateTableSQLGeneratorIT.java

- Fix create table sql generator IT using mysql 8
-
-
---

Fix create table sql generator IT using mysql 8

---

mode/type/cluster/repository/provider/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/ConsulRepository.java
mode/type/cluster/repository/provider/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/lock/ConsulDistributedLockHolder.java
mode/type/cluster/repository/provider/consul/src/test/java/org/apache/shardingsphere/mode/repository/cluster/consul/ConsulRepositoryTest.java

Consul repository support use localhost consul agent if not config server list
for example:
-- one:
ClusterPersistRepositoryConfiguration clusterPersistRepositoryConfiguration = new ClusterPersistRepositoryConfiguration("Consul", "", "", new Properties())
consul type repository support serverLists param is empty, if is empty, use the default localhost.
Others Changes proposed in this pull request:
- remove the code of no relation with lock from ConsulDistributedLockHolder
- improve the unit test  performance

Consul repository support use localhost consul agent if not config server list

---

test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/RALStatementAssert.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/HintRALStatementAssert.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/hint/AddShardingHintTableValueStatementAssert.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/AddShardingHintTableValueStatementTestCase.java
test/parser/src/main/resources/case/ral/hint.xml

Fixes #[21468](https://github.com/apache/shardingsphere/issues/21468).
-
-  HintRALStatementAssert created for all Hint SQL parsing test cases, RAL statement are extended by Update, 
Query and Hint.
-  comparing logic table name and sharding value for query
---

Added SQL parser test case for AddShardingHintTableValueStatement

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractSimplePipelineJob.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/OraclePipelineSQLBuilder.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJob.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJob.java

Part of #19421.
- Extract stop() / prepare() to AbstractPipelineJob
- Add AbstractSimplePipelineJob
---

Extract more methods to AbstractPipelineJob and AbstractSimplePipelineJob for common usage

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ExecuteEngine.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/IncrementalTask.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryIncrementalTasksRunner.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryTask.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/PipelineTask.java
test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/execute/ExecuteEngineTest.java
test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/task/IncrementalTaskTest.java
test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryTaskTest.java

- Refactor PipelineTask.start return Collection<CompletableFuture<?>>. Make sure any task thread failure will break job.
- Remove unused ExecuteEngine.submitAll
---

Refactor PipelineTask.start futures handling

---

kernel/data-pipeline/core/pom.xml
kernel/data-pipeline/dialect/mysql/pom.xml
kernel/data-pipeline/dialect/postgresql/pom.xml
proxy/backend/pom.xml

Suggestion of @RaigorJiang 
- Replace project.parent.version to project.version, for better code style
---

Use unified project.version in pom.xml

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/data/pipeline/ShardingColumnsExtractorImpl.java
features/sharding/core/src/main/resources/META-INF/services/org.apache.shardingsphere.data.pipeline.spi.sharding.ShardingColumnsExtractor
infra/util/src/main/java/org/apache/shardingsphere/infra/util/exception/external/sql/ShardingSphereSQLException.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/data/pipeline/datasource/creator/ShardingSpherePipelineDataSourceCreator.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/spi/sharding/ShardingColumnsExtractor.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/spi/sharding/ShardingColumnsExtractorFactory.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/CRC32MatchDataConsistencyCalculateAlgorithm.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/AbstractMigrationITCase.java
test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/general/MySQLMigrationGeneralIT.java
test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralIT.java
test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/framework/helper/ScalingCaseHelper.java
test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/util/AutoIncrementKeyGenerateAlgorithm.java
test/integration-test/scaling/src/test/resources/env/common/migration-command.xml
test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/spi/sharding/ShardingColumnsExtractorFactoryTest.java

Currently, shardingColumnsMap is always empty for migration job, UPDATE/DELETE SQL in incremental task doesn't include sharding columns in condition, so the logic SQL will be routed broadcastly, it might hurt performance.
shardingColumnsMap was set before, it should be set up again.
- Add ShardingColumnsExtractor and implementation
- Use shardingColumnsMap for migration job
- Update related migration IT: t_order use user_id as sharding column; Some improvement of IT
- Fix bugs found in real test: 1) sharding strategy type should be case-insensitive, 2) error message in ShardingSphereSQLException is missed
---

Add sharding columns in SQL condition for migration incremental task

---

features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/converter/DatabaseDiscoveryRuleStatementConverter.java
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/converter/DatabaseDiscoveryRuleStatementConverterTest.java
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/AlterDatabaseDiscoveryRuleStatementUpdaterTest.java
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/CreateDatabaseDiscoveryRuleStatementUpdaterTest.java

Fixes #21816.
- Revise database discovery type name format
- Change database discovery type name format to lowercase
---

Revise database discovery type name format

---

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/type/memory/AbstractMemoryQueryResult.java
infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/memory/JDBCMemoryQueryResultTest.java

- Improve AbstractMemoryQueryResult.wasNull
---

Improve AbstractMemoryQueryResult.wasNull

---

test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/mysql/DynamicLoadingMySQLParserParameterizedIT.java
test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/postgresql/DynamicLoadingPostgreSQLParserParameterizedIT.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/DynamicLoadingSQLParserParameterizedTest.java

Follows #22006.
- restructure DynamicLoadingSQLParserParameterizedTest with URI
- modify DynamicLoadingMySQLParserParameterizedTestIT, DynamicLoadingPostgreSQLParserParameterizedTestIT
---

Restructure DynamicLoadingSQLParserParameterizedTest with URI

---

test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/base/DynamicLoadingSQLParserParameterizedTest.java
test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/mysql/DynamicLoadingMySQLParserParameterizedIT.java
test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/postgresql/DynamicLoadingPostgreSQLParserParameterizedIT.java

- add ServiceProviderNotFoundServerException
- resize empty result to 3
- add databaseType as 3rd param
---

Fix wrong number of arguments on IT of dynamic loading SQL case

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchCalculatedResultTest.java

- Reuse EqualsBuilder in DATA_MATCH impl, reduce new objects creation
- Add CalculatedResult unit test for DATA_MATCH
---

Reuse EqualsBuilder in CalculatedResult; Add CalculatedResult unit test

---

test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/env/IntegrationTestEnvironment.java
test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/result/CSVResultGenerator.java
test/integration-test/sql-parser/src/test/resources/env/it-env.properties

for #21999
- refactor the CSV generator to avoid the multi-thread issue
-  add customized report path
---

Refactor : refactor the CSV generator to avoid the multi-thread issue

---

test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/result/SQLParserResultProcessorManager.java

- add license for the SQLParserResultProcessorManager
---

Fix : add missing license for the SQLParserResultProcessorManager

---

features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/checker/ReadwriteSplittingRuleStatementChecker.java
features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/AlterReadwriteSplittingRuleStatementUpdater.java
features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/CreateReadwriteSplittingRuleStatementUpdater.java
features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/DropReadwriteSplittingRuleStatementUpdater.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/AlterStorageUnitBackendHandler.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/RegisterStorageUnitBackendHandler.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/UnregisterStorageUnitBackendHandler.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/rule/SetDefaultSingleTableStorageUnitStatementUpdater.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/RegisterStorageUnitBackendHandlerTest.java

For #22039.
- Enhanced distsql verification of rdl type in storage unit and readwrite splitting
---

Enhanced DistSQL verification of RDL type in storage and readwrite splitting

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/builder/dialect/PostgreSQLShardingSphereDataBuilder.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/data/builder/PostgreSQLShardingSphereDataBuilderTest.java

For #22052.
- Add pg_class and pg_namespace's info to ShardingSphere Data
---

Add pg_class and pg_namespace's info to ShardingSphere Data

---

infra/datetime/type/database/pom.xml

- Remove sharding-core dependency for database-datetime infra module (infra module should not depend on sharding-core module which is part of features module)
---

Remove sharding-core dependency for database-datetime infra module

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptPredicateEqualRightValueToken.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptPredicateInRightValueToken.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/EncryptPreparedStatementTest.java

Fix equals for EncryptPredicateEqualRightValueToken.

Fix equals for EncryptPredicateEqualRightValueToken.

---

test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/distsql/ral/impl/HintRALStatementAssert.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/distsql/ral/impl/hint/SetReadwriteSplittingHintStatementAssert.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/jaxb/cases/domain/statement/distsql/ral/SetReadwriteSplittingHintStatementTestCase.java
test/parser/src/main/resources/case/ral/hint.xml
test/parser/src/test/java/org/apache/shardingsphere/test/sql/parser/internal/DistSQLParserParameterizedTest.java

For #21460.
- Add test unit for SetReadwriteSplittingHintStatement.
---

test(issue-21460): SetReadwriteSplittingHintStatement

---

test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/distsql/ral/impl/HintRALStatementAssert.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/distsql/ral/impl/hint/ShowReadwriteSplittingHintStatusStatementAssert.java

Fixes #21461.
- Add test unit for ShowReadwriteSplittingHintStatusStatement.
---

test(issue-21461): ShowReadwriteSplittingHintStatusStatement

---

features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryDataSourceRule.java
features/db-discovery/core/src/test/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryDataSourceRuleTest.java
features/db-discovery/core/src/test/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryRuleTest.java
features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/strategy/type/DynamicReadwriteSplittingStrategy.java
features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/strategy/type/DynamicReadwriteSplittingStrategyTest.java

Fixes #22197
- optimize DatabaseDiscoveryDataSourceRule getDataSourceMapper logic
- optimize DynamicReadwriteSplittingStrategy getAllDataSources logic
---

Optimize DatabaseDiscoveryDataSourceRule getDataSourceMapper logic and DynamicReadwriteSplittingStrategy getAllDataSources logic

---

sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
test/parser/src/main/resources/case/dml/select-expression.xml
test/parser/src/main/resources/sql/supported/dml/select-expression.xml

For #22052.
- Fix parsing not like operator missing whitespace.
---

Fix parsing not like operator missing whitespace.

---

test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/distsql/ral/impl/HintRALStatementAssert.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/distsql/ral/impl/hint/ShowShardingHintStatusStatementAssert.java

For #21464.
- Add test unit for ShowShardingHintStatusStatement.
- Rename readwrite-splitting hint status
Particularly Notes:  SQL statement `<show-sharding-hint-status sql-case-id="show-sharding-hint-status" />`  has already been in the XML file `hint.xml`
---

test(issue-21464): ShowShardingHintStatusStatement

---

test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/distsql/ral/impl/HintRALStatementAssert.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/distsql/ral/impl/hint/ClearReadwriteSplittingHintStatementAssert.java

For #21463.
- Add test unit for ClearReadwriteSplittingHintStatement.
Particularly Notes: SQL statement `<distsql-case id="clear-readwrite-splitting-hint-source" value="CLEAR READWRITE_SPLITTING HINT" />`has already been in the XML file `hint.xml`
---

test(issue-21463): ClearReadwriteSplittingHintStatement

---

infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesValidator.java

Hi @terrymanu 
I noticed your comment on "DataSourceProperties Validator".
> // TODO check why catch exception here, can it simplify to catch SQLException and ShardingSphereInternalException?
After some research, I found that there are two kinds of exceptions that can occur when executing the `checkFailFast` method:
1. **SQLException**, such as wrong password
2. **RuntimeException**, such as missing connector driver
Among them, `RuntimeException` is thrown by `com.zaxxer.hikari.util.DriverDataSource` when the driver fails to load, the code is as shown in the figure:
So, I change `Exception` to `SQLException` and `RuntimeException` now.
---

Change Exception to SQLException and RuntimeException when validate storage unit.

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/like/CharDigestLikeEncryptAlgorithm.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/algorithm/like/CharDigestLikeEncryptAlgorithmTest.java

-Optimize CharDigestLikeEncryptAlgorithm uppercase letter encryption effect
---

Optimize CharDigestLikeEncryptAlgorithm uppercase letter encryption effect

---

proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/postgresql/PostgreSQLAdminExecutorCreator.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/admin/postgresql/PostgreSQLAdminExecutorCreatorTest.java

For #22052.
- Use kernel to support pg_class and pg_namespace.
---

Adjust PostgreSQLAdminExecutorCreator logic for using kernel to support pg_class and pg_namespace.

---

kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiateHandler.java

- Remove pipeline incremental task connecting MySQL use default database
---

Remove pipeline incremental task connecting MySQL use default database

---

sql-parser/dialect/mysql/src/test/java/org/apache/shardingsphere/sql/parser/mysql/external/ExternalMySQLParserParameterizedIT.java
sql-parser/dialect/mysql/src/test/java/org/apache/shardingsphere/sql/parser/mysql/internal/InternalMySQLParserParameterizedIT.java
sql-parser/dialect/mysql/src/test/java/org/apache/shardingsphere/sql/parser/mysql/internal/InternalUnsupportedMySQLParserParameterizedIT.java
sql-parser/dialect/opengauss/src/test/java/org/apache/shardingsphere/sql/parser/opengauss/InternalOpenGaussParserParameterizedIT.java
sql-parser/dialect/opengauss/src/test/java/org/apache/shardingsphere/sql/parser/opengauss/InternalUnsupportedOpenGaussParserParameterizedIT.java
sql-parser/dialect/oracle/src/test/java/org/apache/shardingsphere/sql/parser/oracle/InternalOracleParserParameterizedIT.java
sql-parser/dialect/oracle/src/test/java/org/apache/shardingsphere/sql/parser/oracle/InternalUnsupportedOracleParserParameterizedIT.java
sql-parser/dialect/postgresql/src/test/java/org/apache/shardingsphere/sql/parser/postgresql/external/ExternalPostgreSQLParserParameterizedIT.java
sql-parser/dialect/postgresql/src/test/java/org/apache/shardingsphere/sql/parser/postgresql/internal/InternalPostgreSQLParserParameterizedIT.java
sql-parser/dialect/postgresql/src/test/java/org/apache/shardingsphere/sql/parser/postgresql/internal/InternalUnsupportedPostgreSQLParserParameterizedIT.java
sql-parser/dialect/sql92/src/test/java/org/apache/shardingsphere/sql/parser/sql92/InternalSQL92ParserParameterizedIT.java
sql-parser/dialect/sql92/src/test/java/org/apache/shardingsphere/sql/parser/sql92/InternalUnsupportedSQL92ParserParameterizedIT.java
sql-parser/dialect/sqlserver/src/test/java/org/apache/shardingsphere/sql/parser/sqlserver/InternalSQLServerParserParameterizedIT.java
sql-parser/dialect/sqlserver/src/test/java/org/apache/shardingsphere/sql/parser/sqlserver/InternalUnsupportedSQLServerParserParameterizedIT.java
test/common/src/main/java/org/apache/shardingsphere/test/runner/parallel/impl/DefaultParallelRunnerExecutor.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/external/engine/ExternalSQLParserParameterizedIT.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/engine/InternalSQLParserParameterizedIT.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/engine/InternalUnsupportedSQLParserParameterizedIT.java
test/parser/src/test/java/org/apache/shardingsphere/test/sql/parser/internal/InternalDistSQLParserParameterizedIT.java

- Rename SQLParserParameterizedIT to ExternalSQLParserParameterizedIT
- Rename SQLParserParameterizedTest to InternalSQLParserParameterizedIT

Rename SQL parser IT test engine names

---

sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleDMLStatementSQLVisitor.java
sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/XmlExistsFunctionSegment.java
test/parser/src/main/resources/case/dml/select.xml
test/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #22265.
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/XMLEXISTS.html#GUID-3D0D90DB-3D4F-4685-AFF6-72B6250624B9
---

Update Oracle SQL XMLEXISTS function parse

---

mode/type/cluster/repository/provider/consul/pom.xml

There are 1 security vulnerabilities found in org.apache.httpcomponents:httpclient 4.5.5
- [CVE-2020-13956](https://www.oscs1024.com/hd/CVE-2020-13956)
Upgrade org.apache.httpcomponents:httpclient from 4.5.5 to 4.5.13 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
Signed-off-by:pen4<948453219@qq.com>

fix(sec): upgrade org.apache.httpcomponents:httpclient to 4.5.13

---

sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleDMLStatementSQLVisitor.java
sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/XmlPiFunctionSegment.java
test/parser/src/main/resources/case/dml/select.xml
test/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #22311.
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/XMLPI.html#GUID-142604E3-7999-4803-9DF5-28BDC0701571
---

Update Oracle SQL XMLPI function parse

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/TableTokenGenerator.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/context/ShardingSQLRewriteContextDecoratorTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/TableTokenGeneratorTest.java

Fixes #21594.
- fix wrong rewrite result when part of logical table name of the binding table is consistent with the actual table name, and some are inconsistent
- add unit test for TableTokenGenerator
New rewrite result:
```sql
mysql> preview select * from t_order o inner join t_order_item i on o.user_id = i.user_id where o.user_id = 1;
+------------------+-----------------------------------------------------------------------------------------------------+
| data_source_name | actual_sql                                                                                          |
+------------------+-----------------------------------------------------------------------------------------------------+
| ds_1             | select * from t_order o inner …
```

Fix wrong rewrite result when part of logical table name of the binding table is consistent with the actual table name, and some are inconsistent

---

sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleDMLStatementSQLVisitor.java
sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/XmlSerializeFunctionSegment.java
test/parser/src/main/resources/case/dml/select.xml
test/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #22331.
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/XMLSERIALIZE.html#GUID-F2D5ECE7-3838-4DD5-BE8F-2AEE7890AA1C
---

Update Oracle SQL XMLSERIALIZE function parse

---

features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java
features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/segment/table/AbstractTableRuleSegment.java

- Remove unused inner class EmptyTableRuleSegment
- Revise related visitor
---

Remove unused inner class EmptyTableRuleSegment

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/common/SchemaMetaDataLoader.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/OpenGaussSchemaMetaDataLoader.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/PostgreSQLSchemaMetaDataLoader.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/spi/DialectSchemaMetaDataLoader.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/common/SchemaMetaDataLoaderTest.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/common/SchemaTableNamesLoaderTest.java
kernel/single-table/core/src/main/java/org/apache/shardingsphere/singletable/datanode/SingleTableDataNodeLoader.java

- merge DialectSchemaMetaDataLoader#loadSchemaNames to SchemaMetaDataLoader#loadSchemaNames method
- adjust private method sequence in OpenGaussSchemaMetaDataLoader and PostgreSQLSchemaMetaDataLoader
- add unit test for SchemaMetaDataLoader#loadSchemaNames
---

Merge DialectSchemaMetaDataLoader#loadSchemaNames to SchemaMetaDataLoader#loadSchemaNames method

---

README.md
README_ZH.md

- fix the incorrect link of roadmap
---

Fix : fix the incorrect link of roadmap

---

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/db-discovery.cn.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/db-discovery.en.md
features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/DropDatabaseDiscoveryRuleStatementUpdater.java
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/DropDatabaseDiscoveryRuleStatementUpdaterTest.java

For #22358.
- Remove unused discovery type and discovery heartbeat while dropping DB discovery rule
- Update doucument
---

Improve DistSQL DROP DB_DISCOVERY RULE

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AbstractDropShardingRuleUpdater.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropDefaultStrategyStatementUpdater.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleStatementUpdater.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/DropDefaultShardingStrategyStatementUpdaterTest.java

For #22358.
- Remove unused algorithms while dropping the default sharding strategy
- Add related test
---

Improve DistSQL DROP DEFAULT SHARDING (DATABASE | TABLE) STRATEGY

---

sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4
sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleDMLStatementSQLVisitor.java
sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/XmlNameSpaceStringAsIdentifierSegment.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/XmlNameSpacesClauseSegment.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/XmlTableColumnSegment.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/XmlTableFunctionSegment.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/XmlTableOptionsSegment.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/table/XmlTableSegment.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/segment/table/TableAssert.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/cases/parser/domain/segment/impl/expr/ExpectedXmlTableFunction.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/cases/parser/domain/segment/impl/table/ExpectedXmlTable.java
test/parser/src/main/resources/case/dml/select.xml
test/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #22362.
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/XMLTABLE.html#GUID-C4A32C58-33E5-4CF1-A1FE-039550D3ECFA
The Default string clause can only exist one in a XMLnamespaces clause(as figure shown below) we need to throw an exception when the user input more than one Default string clause in a XMLnamespaces. I have marked TODO in XMLnamespaces visitor.
---

Update Oracle SQL XMLTABLE function parse

---

docs/community/content/involved/conduct/code.cn.md

- Fix unit test documentation typo
---

Fix unit test documentation typo

---

features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/converter/ReadwriteSplittingRuleStatementConverterTest.java
kernel/parser/distsql/handler/src/test/java/org/apache/shardingsphere/parser/distsql/handler/query/SQLParserRuleQueryResultSetTest.java

- Use is() to replace containsString()
-
-
---

Use is() to replace containsString()

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngine.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngineTest.java
test/integration-test/test-suite/src/test/resources/cases/dql/dql-integration-test-cases.xml

Fixes #22355.
- support select join using projection in ResultSetMetaData for MySQL
- add unit test for ProjectionEngine
- add integration test case for MySQL
---

Support select join using projection in ResultSetMetaData for MySQL

---

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/from/impl/JoinTableConverter.java
test/optimize/src/test/java/org/apache/shardingsphere/infra/federation/converter/parameterized/engine/SQLNodeConverterEngineParameterizedTest.java

Ref #22359.
- support MySQL, PostgreSQL and openGauss natural join sql statement convert to sql node
- add sql node convert test case
---

Support MySQL, PostgreSQL and openGauss natural join sql statement convert to sql node

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngine.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngineTest.java
test/integration-test/test-suite/src/test/resources/cases/dql/dql-integration-test-cases.xml

Fixes #22359.
- support MySQL, PostgreSQL and openGauss select natural join statement
- add unit test for ProjectionEngine
---

Support MySQL, PostgreSQL and openGauss select natural join statement

---

test/integration-test/test-suite/src/test/resources/cases/rql/dataset/encrypt_and_readwrite_splitting/count_single_table_rule.xml
test/integration-test/test-suite/src/test/resources/cases/rql/dataset/encrypt_and_readwrite_splitting/show_encrypt_rules.xml
test/integration-test/test-suite/src/test/resources/cases/rql/dataset/encrypt_and_readwrite_splitting/show_single_tables.xml
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/actual/dataset.xml
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/actual/init-sql/h2/actual-encrypt_read_ds-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/actual/init-sql/h2/actual-encrypt_write_ds-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/actual/init-sql/mysql/01-actual-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/actual/init-sql/opengauss/01-actual-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/actual/init-sql/oracle/01-actual-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/actual/init-sql/postgresql/01-actual-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/actual/init-sql/sqlserver/01-actual-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/expected/dataset.xml
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/expected/init-sql/h2/01-expected-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/expected/init-sql/mysql/01-expected-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/expected/init-sql/opengauss/01-expected-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/expected/init-sql/oracle/01-expected-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/expected/init-sql/postgresql/01-expected-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/data/expected/init-sql/sqlserver/01-expected-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/proxy/conf/mysql/config-encrypt-readwrite-splitting.yaml
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/proxy/conf/opengauss/config-encrypt-readwrite-splitting.yaml
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/proxy/conf/postgresql/config-encrypt-readwrite-splitting.yaml
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/rules.yaml

Ref https://github.com/apache/shardingsphere/issues/21286.
- add t_merchant standard table structure for encrypt_and_readwrite_splitting scenario
- add t_merchant init data for encrypt_and_readwrite_splitting scenario
- adjust test case
---

Add t_merchant standard table in encrypt_and_readwrite_splitting scenario

---

test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/actual/dataset.xml
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/actual/init-sql/h2/01-actual-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/actual/init-sql/mysql/01-actual-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/actual/init-sql/opengauss/01-actual-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/actual/init-sql/oracle/01-actual-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/actual/init-sql/postgresql/01-actual-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/actual/init-sql/sqlserver/01-actual-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/expected/dataset.xml
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/expected/init-sql/h2/01-expected-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/expected/init-sql/mysql/01-expected-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/expected/init-sql/opengauss/01-expected-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/expected/init-sql/oracle/01-expected-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/expected/init-sql/postgresql/01-expected-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/data/expected/init-sql/sqlserver/01-expected-init.sql
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/proxy/conf/mysql/config-encrypt-shadow.yaml
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/proxy/conf/opengauss/config-encrypt-shadow.yaml
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/proxy/conf/postgresql/config-encrypt-shadow.yaml
test/integration-test/test-suite/src/test/resources/env/scenario/encrypt_shadow/rules.yaml

Ref https://github.com/apache/shardingsphere/issues/21286.
- add t_merchant standard table structure for encrypt_shadow scenario
- add t_merchant init data for encrypt_shadow scenario
---

Add t_merchant standard table in encrypt_shadow scenario

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/GovernanceRepositoryAPI.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/GovernanceRepositoryAPIImpl.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNode.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNodeTest.java
kernel/data-pipeline/scenario/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobAPIImpl.java
kernel/data-pipeline/scenario/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/api/impl/ConsistencyCheckJobAPIImplTest.java

- Rename CheckLatestJobId to LatestCheckJobId, includes: get/persist/deleteCheckLatestJobId
- Rename jobId to parentJobId for repository consistency check methods parameter
---

Rename CheckLatestJobId to LatestCheckJobId

---

sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
test/optimize/src/test/java/org/apache/shardingsphere/infra/federation/converter/parameterized/engine/SQLNodeConverterEngineParameterizedTest.java
test/parser/src/main/resources/sql/supported/dml/select-geometric.xml

Ref #22528.
- optimize PostgreSQL and openGauss binary operator projection parse logic
- add sql node convert test
---

Optimize PostgreSQL and openGauss binary operator projection parse logic

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptLiteralAssignmentToken.java
kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/FilterableTableScanExecutor.java
kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/TranslatableTableScanExecutor.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/LiteralExpressionConverter.java
sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
sql-parser/dialect/sql92/src/main/java/org/apache/shardingsphere/sql/parser/sql92/visitor/statement/impl/SQL92StatementSQLVisitor.java
sql-parser/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/impl/SQLServerStatementSQLVisitor.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/SQLUtil.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/value/literal/impl/NullLiteralValue.java
test/optimize/src/test/java/org/apache/shardingsphere/infra/federation/converter/parameterized/engine/SQLNodeConverterEngineParameterizedTest.java
test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java
test/parser/src/main/resources/case/dml/insert.xml
test/parser/src/main/resources/case/dml/replace.xml
test/parser/src/main/resources/case/dml/select.xml
test/parser/src/main/resources/case/dml/update.xml
test/parser/src/main/resources/sql/supported/dml/select.xml
test/rewrite/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/update/update.xml

Fixes #22528.
- Optimize mysql, oracle, sqlserver and sql92 null projection parse
- support convert to sqlnode
- add sql parse and sql convert test case
---

Optimize mysql, oracle, sqlserver and sql92 null projection parse and support convert to sqlnode

---

proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/advance/ParseDistSQLHandlerTest.java

Fixes #22518.
-
The flakiness of the tests is because Json objects are being compared and the ordering of the elements in the generated json strings may not be deterministic.
Using the gson [JsonParser](https://stackoverflow.com/questions/2253750/testing-two-json-objects-for-equality-ignoring-child-order-in-java/9065247#9065247).parseString(), the json strings are converted to json parse trees. 
The generated parse trees are then compared for equality in the assertions, ignoring the order of the child elements. 
The tests pass using [NonDex](https://github.com/TestingResearchIllinois/NonDex) after this change.
---

Use gson JSONParser for asserting JSON equality deterministically

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/datetime/IntervalShardingAlgorithm.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/datetime/IntervalShardingAlgorithmTest.java

For https://github.com/apache/shardingsphere/issues/21347#issuecomment-1330025024 .
- Add support for `java.sql.Date` in IntervalShardingAlgorithm
- Add the corresponding unit test.
- Refer to #20255 .
---

Add support for `java.sql.Date` in IntervalShardingAlgorithm

---

docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md

Fixes #21051.
- Fixes documentation for building GraalVM Native Image.
---

Fixes documentation for building GraalVM Native Image

---

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/datetime/IntervalShardingAlgorithmTest.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/DatabaseCommunicationEngine.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/exception/RuleNotExistedException.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/exception/StorageUnitNotExistedException.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/executor/AbstractDatabaseMetadataExecutor.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/mysql/executor/UnicastResourceShowExecutor.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/data/impl/UnicastDatabaseBackendHandler.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/hint/executor/ShowShardingHintStatusExecutor.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/PreviewHandler.java

Fixes #22595.
Optimize RuleNotExistedException and StorageUnitNotExistedException.
---

Optimize RuleNotExistedException and StorageUnitNotExistedException.

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptTable.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/EncryptTableTest.java

Fix insert encrypt values into plain columns when config columns and sql columns are inconsistent capitalization.
---

Fix insert encrypt values into plain columns.

---

docs/document/content/user-manual/shardingsphere-proxy/migration/usage.cn.md
docs/document/content/user-manual/shardingsphere-proxy/migration/usage.en.md
test/e2e/pipeline/src/test/resources/env/mysql/01-initdb.sql
test/e2e/pipeline/src/test/resources/env/opengauss/01-initdb.sql
test/e2e/pipeline/src/test/resources/env/postgresql/01-initdb.sql

- Update heterogeneous migration example for openGauss. English doc missed one SQL.
- Update migration permission doc. Permission is different in source and target. Uncompleted, need to do for PostgreSQL and openGauss, and also E2E test permission initialization.
---

Update heterogeneous migration example and migration permission doc

---

test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/HintRALStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/hint/ClearHintStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/hint/ClearShardingHintStatementAssert.java

Fixes #21458,#21469
- Add ClearHintStatementAssert
- Add ClearShardingHintStatementAssert
---

Add ClearHintStatementAssert and ClearShardingHintStatementAssert

---

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java

fromclasspath with mutiple ClassLoaders
Fixes #22658
- Add `getResourceAsStream` to load configuration file from classpath by using mutiple ClassLoaders which could be helpful to fix https://github.com/quarkiverse/quarkus-shardingsphere-jdbc/issues/74
---

Make sure ShardingSphereDriver can load configuration file from classpath with mutiple ClassLoaders

---

kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClient.java
kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/PasswordEncryption.java
kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/PasswordEncryptionTest.java

1. avoid `lastBinlogEvent` is null when init
2. triggers reconnection when timeout happened,  no reconnection when manually stopped
- Improve MySQL incremental client reconnect and close
---

Improve MySQL incremental client reconnect and close

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/decider/ShardingSQLFederationDecider.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/decider/ShardingSQLFederationDeciderTest.java

Fixes #22432.
- fix wrong decide result when execute same sharding condition subquery with sql federation
---

Fix wrong decide result when execute same sharding condition subquery with sql federation

---

features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/constant/DatabaseDiscoveryOrder.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/constant/EncryptOrder.java
features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/constant/ReadwriteSplittingOrder.java
features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/constant/ShadowOrder.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/constant/ShardingOrder.java
features/sharding/plugin/cache/src/main/java/org/apache/shardingsphere/sharding/cache/rule/builder/ShardingCacheRuleBuilder.java
features/sharding/plugin/cache/src/main/java/org/apache/shardingsphere/sharding/cache/yaml/swapper/YamlShardingCacheRuleConfigurationSwapper.java
features/sharding/plugin/cache/src/test/java/org/apache/shardingsphere/sharding/cache/rule/builder/ShardingCacheRuleBuilderTest.java
features/sharding/plugin/cache/src/test/java/org/apache/shardingsphere/sharding/cache/yaml/swapper/YamlShardingCacheRuleConfigurationSwapperTest.java

- remove useless ALGORITHM_PROVIDER_ORDER for spring usage
---

Remove useless ALGORITHM_PROVIDER_ORDER for spring usage

---

docs/document/themes/hugo-theme-learn/layouts/partials/language.html

Signed-off-by: Junfeng <i@jacob953.com>
Fixes #22827.
- replace 'document/[\w|-]\*' with 'document/[^/]\*'.
---

Correct the RE expression at the language.html

---

test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/show_authority_rule.xml
test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/show_dist_variable_where_name_equal_sql_show.xml
test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/show_dist_variables.xml
test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/show_sql_parse_rule.xml
test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/show_status_from_readwrite_splitting_rules.xml
test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/show_transaction_rule.xml
test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/standalone/show_authority_rule.xml
test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/standalone/show_dist_variable_where_name_equal_sql_show.xml
test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/standalone/show_dist_variables.xml
test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/standalone/show_sql_parse_rule.xml
test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/standalone/show_status_from_readwrite_splitting_rules.xml
test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/standalone/show_transaction_rule.xml
test/e2e/suite/src/test/resources/cases/ral/ral-integration-test-cases.xml

The second, third, fourth, fifth, tenth, and eleventh task of #20867.
- add test case for SHOW STATUS FROM READWRITE_SPLITTING RULES
- add test case for SHOW AUTHORITY RULE
- add test case for SHOW TRANSACTION RULE
- add test case for SHOW SQL_PARSER RULE
- add test case for SHOW DIST VARIABLES
- add test case for SHOW SHOW DIST VARIABLE WHERE name = sql_show
---

Add some integration test case for DistSQL RAL

---

sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java
sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractorTest.java

Fixes #22820.
- fix create view index out of range exception when view contains set operator
---

Fix create view index out of range exception when view contains set operator

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/SchemaMetaDataLoaderEngine.java

Since having default load for metadata if dialect load has errors. So log level should be debug is ok.
- Change dialect load error log lever from error to debug.
---

Change dialect load error log lever from error to debug.

---

features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskBeforeSpecialCharAlgorithm.java
features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/MaskBeforeSpecialCharAlgorithmTest.java

Ref #22759 .
-add MASK_BEFORE_SPECIAL_CHAR Algorithm
---

Implement MASK_BEFORE_SPECIAL_CHAR Algorithm

---

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/util/ResultSetUtil.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSetTest.java

Fixes #22736.
- Make ShardingSphereResultSet always tries to transform the target class.
---

Make ShardingSphereResultSet always tries to transform the target class

---

agent/core/src/test/java/org/apache/shardingsphere/agent/core/advisor/ClassAdvisorRegistryFactoryTest.java
agent/core/src/test/java/org/apache/shardingsphere/agent/core/advisor/ClassAdvisorRegistryTest.java

Signed-off-by: Junfeng <i@jacob953.com>
Fixes #22861.
- Add test cases for agent-core advisors
---

Add test cases for agent-core advisors

---

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/orderby/item/ColumnOrderByItemConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/orderby/item/ExpressionOrderByItemConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/orderby/item/IndexOrderByItemConverter.java
test/e2e/suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
test/it/optimizer/src/test/java/org/apache/shardingsphere/test/it/optimize/SQLNodeConverterEngineIT.java

Fixes #22826.
- support sql federation nulls last, nulls first operator
- add sql node convert unit test
---

Support sql federation nulls last, nulls first operator

---

distsql/handler/src/main/java/org/apache/shardingsphere/distsql/handler/exception/algorithm/InvalidAlgorithmConfigurationException.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/checker/ShardingTableRuleStatementChecker.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/checker/ShardingRuleStatementCheckerTest.java
features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/segment/table/AutoTableRuleSegment.java

Fixes #22816.
- Optimize the error message when sharding algorithm type does not match
```sql
CREATE SHARDING TABLE RULE apploginlogs(
RESOURCES(ds_write_test_common),
SHARDING_COLUMN=CreationTime,
TYPE(NAME=“INTERVAL”, PROPERTIES(“datetime-pattern”=“yyyy-MM-dd HH:mm:ss”,“datetime-interval-unit”=“MONTHS”,“datetime-interval-amount”=“1”,“sharding-suffix-pattern”=“yyyyMM”,“datetime-lower”=“2016-01-01 00:00:00”,“datetime-upper”=“2099-12-31 00:00:00”))
);
ERROR 19150 (44000): Invalid sharding algorithms [INTERVAL]
```
---

Optimize the verification of auto table algorithm type

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngine.java
test/e2e/suite/src/test/resources/cases/dql/dql-integration-test-cases.xml

- Fix sub query ShorthandProjection missing column.
---

Fix sub query ShorthandProjection missing column.

---

infra/common/src/main/java/org/apache/shardingsphere/infra/instance/metadata/InstanceMetaDataBuilderFactory.java
infra/common/src/main/java/org/apache/shardingsphere/infra/instance/metadata/jdbc/JDBCInstanceMetaData.java
infra/common/src/main/java/org/apache/shardingsphere/infra/instance/metadata/proxy/ProxyInstanceMetaData.java
infra/common/src/test/java/org/apache/shardingsphere/infra/instance/metadata/InstanceMetaDataBuilderFactoryTest.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/connection/ConnectionManagerTest.java
kernel/traffic/core/src/test/java/org/apache/shardingsphere/traffic/algorithm/engine/TrafficEngineTest.java
kernel/traffic/core/src/test/java/org/apache/shardingsphere/traffic/algorithm/loadbalance/RandomTrafficLoadBalanceAlgorithmTest.java
kernel/traffic/core/src/test/java/org/apache/shardingsphere/traffic/algorithm/loadbalance/RoundRobinTrafficLoadBalanceAlgorithmTest.java
mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/pojo/ComputeNodeData.java
mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/service/ComputeNodeStatusService.java
mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/watcher/ComputeNodeStateChangedWatcher.java
mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/service/ComputeNodeStatusServiceTest.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodeInfoHandler.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodesHandler.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodeInfoHandlerTest.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodesHandlerTest.java
test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/show_compute_nodes.xml
test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/standalone/show_compute_nodes.xml

Fixes #22918 .
```
mysql> show compute nodes;
+--------------------------------------+---------------+------+--------+-----------+-----------+--------+----------------+
| instance_id                          | host          | port | status | mode_type | worker_id | labels | version        |
+--------------------------------------+---------------+------+--------+-----------+-----------+--------+----------------+
| 563b7e44-89e7-4b98-b837-588461fea09b | 192.168.0.105 | 3307 | OK     | Cluster   | -1        |        | 5.3.1-SNAPSHOT |
| d3a2a283-effb-4c21-991e-f6ebfcd4f606 | 192.168.0.105 | 3307 | OK     | Cluster   | -1        |        | 5.3.1-SNAPSHOT |
+--------------------------------------+---------------+------+--------+-----------+-----------+--------+----------------+
```

SHOW COMPUTE NODES support display ShardingSphere-Proxy & ShardingSphere-JDBC version

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/encrypt/AESEncryptAlgorithm.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/encrypt/RC4EncryptAlgorithm.java
test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/cases/assertion/IntegrationTestCase.java
test/e2e/suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
test/e2e/suite/src/test/resources/cases/rql/dataset/encrypt/show_encrypt_rules.xml
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/dataset.xml
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/init-sql/h2/01-actual-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/init-sql/mysql/01-actual-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/init-sql/opengauss/01-actual-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/init-sql/oracle/01-actual-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/init-sql/postgresql/01-actual-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/init-sql/sqlserver/01-actual-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/proxy/conf/mysql/config-encrypt.yaml
test/e2e/suite/src/test/resources/env/scenario/encrypt/proxy/conf/opengauss/config-encrypt.yaml
test/e2e/suite/src/test/resources/env/scenario/encrypt/proxy/conf/postgresql/config-encrypt.yaml
test/e2e/suite/src/test/resources/env/scenario/encrypt/rules.yaml

Fixes #23003.
- fix AESEncryptAlgorithm decrypt exception when config char type with PostgreSQL and openGauss
- add integration test case for AESEncryptAlgorithm and CharDigestLikeEncryptAlgorithm
---

Fix AESEncryptAlgorithm decrypt exception when config char type with PostgreSQL and openGauss

---

.gitattributes

- add eot and ttf file to .gitattributes to avoid newline formatting
---

Add eot and ttf file to .gitattributes to avoid newline formatting

---

test/e2e/suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
test/e2e/suite/src/test/resources/cases/rql/dataset/encrypt/show_encrypt_rule.xml
test/e2e/suite/src/test/resources/cases/rql/dataset/encrypt/show_encrypt_rules.xml
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/dataset.xml
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/init-sql/h2/01-actual-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/init-sql/mysql/01-actual-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/init-sql/opengauss/01-actual-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/init-sql/oracle/01-actual-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/init-sql/postgresql/01-actual-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/actual/init-sql/sqlserver/01-actual-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/expected/dataset.xml
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/expected/init-sql/h2/01-expected-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/expected/init-sql/mysql/01-expected-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/expected/init-sql/opengauss/01-expected-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/expected/init-sql/oracle/01-expected-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/expected/init-sql/postgresql/01-expected-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/data/expected/init-sql/sqlserver/01-expected-init.sql
test/e2e/suite/src/test/resources/env/scenario/encrypt/proxy/conf/mysql/config-encrypt.yaml
test/e2e/suite/src/test/resources/env/scenario/encrypt/proxy/conf/opengauss/config-encrypt.yaml
test/e2e/suite/src/test/resources/env/scenario/encrypt/proxy/conf/postgresql/config-encrypt.yaml
test/e2e/suite/src/test/resources/env/scenario/encrypt/rules.yaml

Ref #21286.
- refactor t_user init sql and data in encrypt scenario
- adjust some encrypt test case and modify comments
---

Refactor t_user init sql and data in encrypt scenario and adjust some encrypt test case

---

agent/plugins/metrics/core/src/test/java/org/apache/shardingsphere/agent/metrics/core/advice/SQLParserEngineAdviceTest.java
distsql/parser/src/main/antlr4/imports/Keyword.g4
distsql/parser/src/main/antlr4/imports/RDLStatement.g4
distsql/parser/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java
distsql/statement/src/main/java/org/apache/shardingsphere/distsql/parser/statement/rdl/create/RegisterStorageUnitStatement.java
kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/utils/AutoCommitUtilsTest.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/RegisterStorageUnitBackendHandler.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/RegisterStorageUnitBackendHandlerTest.java

The first task of #22844.
- Add `IF NOT EXISTS` to the `register storage unit` statement
---

Add `IF NOT EXISTS` to `register storage unit` statement

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryIncrementalTasksRunner.java

- Fix CompletableFuture.anyOf missing callback in tasks runner
---

Fix CompletableFuture.anyOf missing callback in tasks runner

---

distsql/statement/src/main/java/org/apache/shardingsphere/distsql/parser/segment/converter/DataSourceSegmentsConverter.java
distsql/statement/src/test/java/org/apache/shardingsphere/distsql/parser/segment/converter/DataSourceSegmentsConverterTest.java
kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/RegisterMigrationSourceStorageUnitUpdater.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/AlterStorageUnitBackendHandler.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/RegisterStorageUnitBackendHandler.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/RegisterStorageUnitBackendHandlerTest.java

Ref #23066.
- Decouple `RegisterStorageUnitBackendHandler` and `ReadwriteSplittingRuleConfiguration`
- Check logical data source names when there is `if not exists`
- Update test cases.
---

Optimize register storage unit handler.

---

proxy/backend/pom.xml

Since the distsql-handler module already depends on core, remove the core dependencies.

Remove redundant dependencies of feature core for shardingsphere-proxy-backend

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateShardingTableReferenceRuleStatementUpdater.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/CreateShardingTableReferenceRuleStatementUpdaterTest.java
features/sharding/distsql/parser/src/main/antlr4/imports/sharding/RDLStatement.g4
features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java
features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/statement/CreateShardingTableReferenceRuleStatement.java

The third task of #22844.
- Add `IF NOT EXISTS` to `create sharding table reference rule`
---

Add `IF NOT EXISTS` to `create sharding table reference rule`

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateShardingTableReferenceRuleStatementUpdater.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/executor/AbstractDatabaseMetaDataExecutor.java

Fixes #23115.
```sql
--
(0 rows)
```
```sql
table_schema | table_name | column_name | data_type | type_type | character_maximum_length | column_comment | modifier | is_nullable | column_default | is_autoinc | sequence_name | enum_values | numeric_precision | numeric_scale | size | is_pkey | dimension 
--------------+------------+-------------+-----------+-----------+--------------------------+----------------+----------+-------------+----------------+------------+---------------+-------------+-------------------+---------------+------+---------+-----------
(0 rows)
```
---

Keep column labels when the result set of querying metadata is empty.

---

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt.cn.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt.en.md

For #22964
- QUERY_WITH_CIPHER_COLUMN supports column-level settings
---

Update DistSQL doc about encrypt rule

---

features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/CreateDatabaseDiscoveryRuleStatementUpdater.java
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/CreateDatabaseDiscoveryRuleStatementUpdaterTest.java
features/db-discovery/distsql/parser/src/main/antlr4/imports/db-discovery/Keyword.g4
features/db-discovery/distsql/parser/src/main/antlr4/imports/db-discovery/RDLStatement.g4
features/db-discovery/distsql/parser/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/parser/core/DatabaseDiscoveryDistSQLStatementVisitor.java
features/db-discovery/distsql/statement/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/parser/statement/CreateDatabaseDiscoveryRuleStatement.java

The seventh task of #22844.
- Add `IF NOT EXISTS` to `create db_discovery rule`
---

Add `IF NOT EXISTS` to `create db_discovery rule`

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/Projection.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationDistinctProjection.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationProjection.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/ColumnProjection.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/DerivedProjection.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/ExpressionProjection.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/ParameterMarkerProjection.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/ShorthandProjection.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/SubqueryProjection.java
test/e2e/suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-subquery.xml
test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-plain/dml/select/select-subquery.xml

Fixes #23163.
- fix encrypt shorthand expansion when execute subquery statement
---

Fix encrypt shorthand expansion when execute subquery statement

---

proxy/bootstrap/src/main/resources/conf/server.yaml

For #20736 .
- fixes sqlCommentParseEnabled default value to `false` for SQL hint. 
---

fixes sqlCommentParseEnabled default value to `false` for SQL hint.

---

sql-parser/dialect/opengauss/src/main/antlr4/imports/opengauss/DMLStatement.g4
sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
sql-parser/dialect/postgresql/src/main/antlr4/imports/postgresql/DMLStatement.g4
sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
test/e2e/suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
test/it/optimizer/src/test/java/org/apache/shardingsphere/test/it/optimize/SQLNodeConverterEngineIT.java
test/it/parser/src/main/resources/case/dml/select-pagination.xml
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select-pagination.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #22822.
- Optimize PostgreSQL, openGauss select fetech statement parse
- add more integration test for fetch statement when use sql federation
---

Optimize PostgreSQL, openGauss select fetech statement parse and add more integration test

---

infra/util/src/main/java/org/apache/shardingsphere/infra/util/spi/ShardingSphereServiceLoader.java

Avoid JDK-8161372 in ShardingSphereServiceLoader

---

features/mask/distsql/parser/src/main/java/org/apache/shardingsphere/mask/distsql/parser/core/MaskDistSQLStatementVisitor.java

Ref: #23138.
Fix bug in #23207.
- add database name visitor
---

Fix `count mask rule`

---

features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryDataSourceRule.java
features/db-discovery/core/src/test/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryDataSourceRuleTest.java
features/db-discovery/core/src/test/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryRuleTest.java
features/mask/distsql/parser/src/main/java/org/apache/shardingsphere/mask/distsql/parser/core/MaskDistSQLStatementVisitor.java

Ref #23133.
- adjust DatabaseDiscoveryDataSourceRule getDataSourceMapper for primary datasource first
---

Adjust DatabaseDiscoveryDataSourceRule getDataSourceMapper for primary datasource first

---

features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/query/CountMaskRuleResultSetTest.java

Ref: #23138.
add unit test for #23207.
- Add `count mask rule` DistSQL unit test
---

Add `count mask rule` DistSQL unit test

---

features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/converter/MaskRuleStatementConverterTest.java

Ref: #23138.
- Add `MaskRuleStatementConverter` unit test
---

Add `MaskRuleStatementConverter` unit test

---

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/reserved-word.cn.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/reserved-word.en.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/usage/_index.cn.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/usage/_index.en.md

- Fix DistSQL documents display order issue
---

Fix DistSQL documents display order issue

---

agent/plugins/metrics/type/prometheus/pom.xml
agent/plugins/tracing/type/pom.xml
agent/pom.xml

Fixes #23318.
- exclude H2 dependency from agent plugins
---
---

Refactor : exclude H2 dependency from agent plugins (#23318)

---

proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/EncryptRuleConfigurationImportChecker.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationHandler.java

- Add `EncryptRuleConfigurationImportChecker` for `ImportDatabaseConfigurationHandler`
---

Add `EncryptRuleConfigurationImportChecker`

---

proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/DBDiscoveryRuleConfigurationImportCheckerTest.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/DbDiscoveryRuleConfigurationImportCheckerTest.java

- add `DbDiscoveryRuleConfigurationImportCheckerTest`
---

Add unit test for `DatabaseDiscoveryRuleConfigurationImportChecker`

---

features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/CreateDatabaseDiscoveryHeartbeatStatementUpdater.java
features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/CreateDatabaseDiscoveryRuleStatementUpdater.java
features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/CreateDatabaseDiscoveryTypeStatementUpdater.java
features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdater.java
features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/update/CreateMaskRuleStatementUpdater.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateBroadcastTableRuleStatementUpdater.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateShardingTableReferenceRuleStatementUpdater.java

- Remove currentRuleConfig non-null judgment for create rule updaters
---

Remove currentRuleConfig non-null judgment for create rule updaters

---

test/e2e/agent/plugins/jaeger/pom.xml
test/e2e/agent/plugins/jaeger/src/test/assembly/bin/start.sh
test/e2e/agent/plugins/jaeger/src/test/assembly/shardingsphere-proxy-agent-jaeger-assembly.xml
test/e2e/agent/plugins/jaeger/src/test/resources/docker/agent/conf/agent.yaml
test/e2e/agent/plugins/jaeger/src/test/resources/docker/docker-compose.yml
test/e2e/agent/plugins/jaeger/src/test/resources/docker/proxy/conf/config-db.yaml
test/e2e/agent/plugins/jaeger/src/test/resources/docker/proxy/conf/logback.xml
test/e2e/agent/plugins/jaeger/src/test/resources/docker/proxy/conf/server.yaml
test/e2e/agent/plugins/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/ZipkinPluginE2EIT.java

for #23135 
- add compose file and config files for jaeger E2E test
---

Add jaeger compose

---

features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/CreateDatabaseDiscoveryRuleStatementUpdater.java
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/CreateDatabaseDiscoveryRuleStatementUpdaterTest.java

For #22844 , refactor ifNotExists of DB_DISCOVERY RULE.
---

Refactor ifNotExists of DB_DISCOVERY RULE.

---

features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/AlterDatabaseDiscoveryRuleStatementUpdater.java
features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/CreateDatabaseDiscoveryRuleStatementUpdater.java
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/AlterDatabaseDiscoveryRuleStatementUpdaterTest.java
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/CreateDatabaseDiscoveryRuleStatementUpdaterTest.java
features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/checker/ReadwriteSplittingRuleStatementChecker.java
features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/AlterReadwriteSplittingRuleStatementUpdaterTest.java
features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/CreateReadwriteSplittingRuleStatementUpdaterTest.java
features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/checker/ShadowRuleStatementChecker.java
features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/AlterShadowRuleStatementUpdaterTest.java
features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/CreateShadowRuleStatementUpdaterTest.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/checker/ShardingTableRuleStatementChecker.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/resource/ShardingSphereResourceMetaData.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/DatabaseDiscoveryRuleConfigurationImportChecker.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/ReadwriteSplittingRuleConfigurationImportChecker.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/ShadowRuleConfigurationImportChecker.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/ShardingRuleConfigurationImportChecker.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/AlterReadwriteSplittingStorageUnitStatusStatementHandler.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/database/DatabaseOperateBackendHandlerFactoryTest.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/DistSQLBackendHandlerFactoryTest.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/DBDiscoveryRuleConfigurationImportCheckerTest.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/ReadwriteSplittingRuleConfigurationImportCheckerTest.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/ShardingRuleConfigurationImportCheckerTest.java

- Rename `resource` to `data source`
---

Rename `resource` to `data source`

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/OracleSchemaMetaDataLoader.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/OracleSchemaMetaDataLoaderTest.java

Fixes #23013 .
- Added null value handling to resolve NPM issues when obtaining metadata in Oracle12.2 environment.
- Added unit test for it.
---

Fix NPM on Oracle 12.2 when load column metadata

---

features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/checker/ShardingRuleStatementCheckerTest.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/converter/ShardingRuleStatementConverterTest.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/AlterShardingTableRuleStatementUpdaterTest.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/CreateShardingTableRuleStatementUpdaterTest.java
features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/segment/table/TableRuleSegment.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/OracleSchemaMetaDataLoader.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/OracleSchemaMetaDataLoaderTest.java

- remove useless constructor for `TableRuleSegment`
---

remove useless constructor for `TableRuleSegment`

---

infra/common/src/main/java/org/apache/shardingsphere/infra/database/type/DatabaseTypeEngine.java
infra/common/src/test/java/org/apache/shardingsphere/infra/database/type/DatabaseTypeEngineTest.java
infra/common/src/test/java/org/apache/shardingsphere/infra/fixture/InfraLongLengthPrefixDatabaseTypeFixture.java
infra/common/src/test/resources/META-INF/services/org.apache.shardingsphere.infra.database.type.DatabaseType

- Support more precise matching by prefix length.
---

Support more precise matching by prefix length.

---

distribution/proxy/Dockerfile
test/e2e/agent/plugins/jaeger/Dockerfile
test/e2e/agent/plugins/metrics/Dockerfile
test/e2e/agent/plugins/opentelemetry/Dockerfile
test/e2e/agent/plugins/zipkin/Dockerfile
test/e2e/fixture/Dockerfile

Fixes #23486.
- `openjdk:8-jdk-alpine` -> `eclipse-temurin:8-jdk-alpine`
- `openjdk:17-jdk-slim` -> `eclipse-temurin:17-jdk`

Migrate openjdk to eclipse-temurin

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ExecuteEngine.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/IncrementalTask.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryTask.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/execute/ExecuteEngineTest.java

- Refactor AbstractSimplePipelineJob.execute to blocking, so elasticjob could know exact lifecycle of job
---

Refactor AbstractSimplePipelineJob.execute to blocking

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateBroadcastTableRuleStatementUpdater.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/CreateBroadcastTableRuleStatementUpdaterTest.java

For #22844 , refactor ifNotExists of CREATE BROADCAST TABLE RULE.
---

Refactor ifNotExists of CREATE BROADCAST TABLE RULE.

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/insert/values/InsertSelectContext.java
proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareParameterMarkerExtractor.java
proxy/frontend/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutor.java
sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDALStatementSQLVisitor.java
sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleDMLStatementSQLVisitor.java
sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
sql-parser/dialect/sql92/src/main/java/org/apache/shardingsphere/sql/parser/sql92/visitor/statement/impl/SQL92DMLStatementSQLVisitor.java
sql-parser/dialect/sql92/src/main/java/org/apache/shardingsphere/sql/parser/sql92/visitor/statement/impl/SQL92StatementSQLVisitor.java
sql-parser/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/impl/SQLServerStatementSQLVisitor.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/simple/ParameterMarkerExpressionSegment.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/pagination/ParameterMarkerPaginationValueSegment.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/ParameterMarkerSegment.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/AbstractSQLStatement.java

Fixes #23380.
- Remove the field parameterCount in AbstractSQLStatement to eliminate the risk of inconsistency
---

Remove the field parameterCount in AbstractSQLStatement

---

docs/community/content/involved/release/shardingsphere.cn.md
docs/community/content/involved/release/shardingsphere.en.md

- Update ShardingSphere Release Guide based on 5.3.1 release operations
- Reduce operation errors
- Simplify operation
- Speed up operation
1, In `Prepare Branch for Release` stage, optimize git clone from local repository instead of remote repository.
Before:
```
git clone --branch ${name} https://github.com/apache/shardingsphere.git ~/shardingsphere
```
After:
```
cd ~
git clone ~/open_source/shardingsphere
```
2, In `Deploy the Release` stage, optimize git clone from local repository instead of remote repository by `-DlocalCheckout=true`.
Before:
```
mvn release:prepare -Prelease -Darguments="-DskipTests -Dspotless.apply.skip=true" -DautoVersionSubmodules=true -DpushChanges=false -Dusername=${Github 用户名}
[INFO] 2/3 …
```

Update Apache ShardingSphere Release Guide

---

test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/distsql/rdl/ShadowRuleAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/distsql/rdl/ShardingTableReferenceRuleAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/alter/AlterRuleStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/alter/impl/AlterDatabaseDiscoveryRuleStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/create/CreateRuleStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/create/impl/CreateDatabaseDiscoveryRuleStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/distsql/rdl/ExpectedDatabaseDiscoveryDefinitionRule.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/distsql/rdl/ExpectedShadowRule.java
test/it/parser/src/main/resources/case/rdl/alter.xml
test/it/parser/src/main/resources/case/rdl/create.xml

- add `name` for `sharding table reference rule`
- refactor `CreateDatabaseDiscoveryRuleStatementAssert` and `AlterDatabaseDiscoveryRuleStatementAssert`
- unify `name` and `rule-name` in test cases
---

Optimise DistSQL parser test

---

test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/drop/impl/DropEncryptRuleStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/drop/impl/DropMaskRuleStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/drop/impl/DropShadowRuleStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/drop/impl/DropShardingTableReferenceRulesStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/drop/impl/DropShardingTableRuleStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rdl/rule/dbdiscovery/DropDatabaseDiscoveryRuleStatementTestCase.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rdl/rule/encrypt/DropEncryptRuleStatementTestCase.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rdl/rule/mask/DropMaskRuleStatementTestCase.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rdl/rule/readwritesplitting/DropReadwriteSplittingRuleStatementTestCase.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rdl/rule/shadow/DropShadowRuleStatementTestCase.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rdl/rule/sharding/DropShardingTableReferenceRuleStatementTestCase.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rdl/rule/sharding/DropShardingTableRuleStatementTestCase.java
test/it/parser/src/main/resources/case/rdl/drop.xml

- Unify `table` and `rule` to `rule-name` in DistSQL `drop rule` parser test cases
---

Unify `table` and `rule` in DistSQL parser test cases

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateShardingTableReferenceRuleStatementUpdater.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/CreateShardingTableReferenceRuleStatementUpdaterTest.java

For #22844 , refactor ifNotExists of CREATE SHARDING TABLE REFERENCE RULE.
---

Refactor ifNotExists of CREATE SHARDING TABLE REFERENCE RULE.

---

agent/README.md
distribution/proxy/src/main/resources/bin/start.sh

Fixes #23541
- set agent start with proxy if the switch set to -g
---

Refactor : set agent start with proxy if the switch set to -g (#23541)

---

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/sharding/show-sharding-table-rule.cn.md

- fix `show sharding table rule` DistSQL document
---

fix `show sharding table rule` DistSQL document

---

.github/workflows/nightly-e2e.yml

- it's not necessary to execute agent E2E in nightly job
---

Refactor : remove the agent E2E from nightly job

---

docs/community/content/involved/release/shardingsphere-on-cloud.cn.md
docs/community/content/involved/release/shardingsphere-on-cloud.en.md
docs/community/content/involved/release/shardingsphere.en.md

Update ShardingSphere on Cloud Release Guide based on 0.1.2 release operations.
- Extend some steps with more details
- Add `Finish the Release` section, includes 5 steps. Some steps are moved here, and some new steps are added

Update Apache ShardingSphere on Cloud Release Guide

---

kernel/traffic/core/src/main/java/org/apache/shardingsphere/traffic/executor/TrafficExecutor.java
kernel/traffic/core/src/test/java/org/apache/shardingsphere/traffic/executor/TrafficExecutorTest.java

Fixes #23653.
- fix connection is closed exception caused by TrafficExecutor close logic
---

Fix connection is closed exception caused by TrafficExecutor close logic

---

.github/workflows/nightly-build-artifact.yml
distribution/proxy-native/pom.xml
distribution/proxy-native/src/main/release-docs/LICENSE
distribution/proxy/src/main/release-docs/LICENSE
pom.xml

For #21347.
- Use GraalVM CE 22.3.1 instead of GraalVM CE 23.0 Dev. Refer to https://github.com/apache/shardingsphere/actions/runs/3998084528/jobs/6860258580 and https://github.com/graalvm/setup-graalvm/pull/31 .
- Update OpenGauss JDBC to 3.1.0-og to match GraalVM reachability metadata. Refer to https://github.com/oracle/graalvm-reachability-metadata/pull/168 .
- Update Commons DBCP2 to 2.9.0 to match GraalVM reachability metadata in the future nativeTest. Refer to https://github.com/oracle/graalvm-reachability-metadata/issues/202 .
- Update native-maven-plugin to 0.9.19 to output richer Native Image build logs. Refer to https://graalvm.github.io/native-build-tools/latest/index.html#changelog .
---
Before committing this PR, I'm sure that I have …

Use GraalVM CE 22.3.1 to fix Nightly Build

---

proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/rule/ShowDefaultSingleTableStorageUnitExecutor.java
proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactoryTest.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/ShowDefaultSingleTableStorageUnitExecutorTest.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/ShowSingleTableExecutorTest.java

- Replace `DefaultSingleTableStorageUnitResultSet` with `ShowDefaultSingleTableStorageUnitExecutor`
---

Refactor `DefaultSingleTableStorageUnitResultSet`

---

proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/rule/ShowRulesUsedStorageUnitExecutor.java
proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/ShowRulesUsedStorageUnitExecutorTest.java

- Replace `RulesUsedStorageUnitResultSet` with `ShowRulesUsedStorageUnitExecutor`
---

Refactor `RulesUsedStorageUnitResultSet`

---

proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/rule/CountSingleTableExecutor.java
proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/CountSingleTableExecutorTest.java

For: #23772 
- Replace `CountSingleTableResultSet` with `CountSingleTableExecutor`
---

Replace `CountSingleTableResultSet` with `CountSingleTableExecutor`

---

docs/document/content/test-manual/integration-test/_index.cn.md
docs/document/content/test-manual/integration-test/_index.en.md

Fixes #23759.
- add document for remote debug testcontainer
---

Add : add document for remote debug testcontainer (#23759)

---

proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/rule/ShowLogicalTableExecutor.java
proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/ShowLogicalTableExecutorTest.java

For #23772.
- Replace `LogicalTableResultSet` with `ShowLogicalTableExecutor`
---

Replace `LogicalTableResultSet` with `ShowLogicalTableExecutor`

---

features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/ShowDatabaseDiscoveryRuleExecutor.java
features/db-discovery/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/ShowDatabaseDiscoveryRuleExecutorTest.java

For #23772.
- Replace `DatabaseDiscoveryRuleResultSet` with `ShowDatabaseDiscoveryRuleExecutor`
---

Refactor `DatabaseDiscoveryRuleResultSet` 

---

features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/ShowDatabaseDiscoveryTypeExecutor.java
features/db-discovery/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/db-discovery/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/DatabaseDiscoveryTypeResultSetTest.java
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/ShowDatabaseDiscoveryTypeExecutorTest.java
mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java

For #23772.
- Replace `DatabaseDiscoveryTypeResultSet` with `ShowDatabaseDiscoveryTypeExecutor`
---

Refactor `DatabaseDiscoveryTypeResultSet` 

---

features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/ShowDatabaseDiscoveryHeartbeatExecutor.java
features/db-discovery/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/db-discovery/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/DatabaseDiscoveryHeartbeatResultSetTest.java
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/ShowDatabaseDiscoveryHeartbeatExecutorTest.java

For #23772.
- Replace `DatabaseDiscoveryHeartbeatResultSet` with `ShowDatabaseDiscoveryHeartbeatExecutor`
---

Refactor `DatabaseDiscoveryHeartbeatResultSet`

---

features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/query/ShowEncryptRuleExecutor.java
features/encrypt/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/query/ShowEncryptRuleExecutorTest.java

For #23772.
- Replace `EncryptRuleResultSet` with `ShowEncryptRuleExecutor`
---

Replace `EncryptRuleResultSet` with `ShowEncryptRuleExecutor`

---

infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/pool/creator/DataSourcePoolCreator.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/api/yaml/YamlShardingSphereDataSourceFactory.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/data/pipeline/datasource/creator/ShardingSpherePipelineDataSourceCreator.java

- Refactor ShardingSpherePipelineDataSourceCreator to use YamlShardingSphereDataSourceFactory, replace ShardingSphereDataSourceFactory, it's more fundemental and flexible, and code could be simplified in ShardingSpherePipelineDataSourceCreator
- Close created data sources in DataSourcePoolCreator.create when failure and cache disabled, to avoid possible data source leak
- Clone new YamlRootConfiguration in ShardingSpherePipelineDataSourceCreator.createPipelineDataSource, to avoid possible data corruption in original yamlRootConfig
---

Improve pipeline data source creator

---

features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ShowReadwriteSplittingRuleExecutor.java
features/readwrite-splitting/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ShowReadwriteSplittingRuleExecutorTest.java

For #23772.
- Replace `ReadwriteSplittingRuleResultSet` with `ShowReadwriteSplittingRuleExecutor`
---

Refactor `ReadwriteSplittingRuleResultSet`

---

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/kernel/model/ExecutionGroupContext.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/kernel/model/ExecutionGroupReportContext.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/raw/RawExecutor.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/AbstractExecutionPrepareEngine.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/ExecutionPrepareEngine.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/ExecuteProcessEngine.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/ExecuteProcessReporter.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/model/ExecuteProcessContext.java
infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/kernel/ExecutorEngineTest.java
infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/jdbc/JDBCExecutorTest.java
infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/process/ExecuteProcessReporterTest.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/DriverJDBCExecutor.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/batch/BatchPreparedStatementExecutor.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/executor/batch/BatchPreparedStatementExecutorTest.java
kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/FilterableTableScanExecutor.java
kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/TranslatableTableScanExecutor.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/executor/ProxyJDBCExecutor.java
proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java
proxy/frontend/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutor.java

- Refactor ExecutionGroupContext none-final fields
- add new ExecutionGroupReportContext
---

Refactor ExecutionGroupContext none-final fields and add new ExecutionGroupReportContext

---

.github/workflows/ci.yml
.github/workflows/docker-release.yml
.github/workflows/e2e-agent.yml
.github/workflows/e2e-discovery.yml
.github/workflows/e2e-pipeline.yml
.github/workflows/e2e-showprocesslist.yml
.github/workflows/e2e-transaction.yml
.github/workflows/e2e.yml
.github/workflows/nightly-build-artifact.yml
.github/workflows/nightly-build-example.yml
.github/workflows/nightly-ci.yml
.github/workflows/nightly-e2e.yml
.github/workflows/nightly-sql-parser.yml
pom.xml

It sould be helpful to fix https://github.com/apache/shardingsphere/issues/19990 and https://github.com/apache/shardingsphere/issues/20935
- Force to use `JDK 11` above to build shardingsphere
- We still run all the e2e tests on `JDK 8` to make sure there is no compatitable issues.
- https://github.com/apache/shardingsphere/issues/19990 which needs to run `antlr-maven-plugin` to generate the parser classes. The antlr Tool are only for `JDK 11` after upgrading to 4.10.1. So if upgrading `antlr`, it will force user to build shardingsphere with `JDK 11`
It seems that we need to support  `JDK 8` for a long time. There is no such plan to drop it, see the relevant discussion https://lists.apache.org/thread/kgtfx5vnw73o61lkvdshyfvjfvvzk3js
Before committing …

Force to build on JDK 11+

---

features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/query/ShowShadowTableRuleExecutor.java
features/shadow/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/shadow/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowTableRuleExecutorTest.java

For #23772.
- Replace `ShadowTableRuleResultSet` with `ShowShadowTableRuleExecutor`
---

Replace `ShadowTableRuleResultSet` with `ShowShadowTableRuleExecutor`

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingAuditorsExecutor.java
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingAuditorsExecutorTest.java

For #23772.
- Replace `ShardingAuditorsResultSet` with `ShowShardingAuditorsExecutor`
---

Replace `ShardingAuditorsResultSet` with `ShowShardingAuditorsExecutor`

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingTableRulesUsedAlgorithmExecutor.java
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRulesUsedAlgorithmExecutorTest.java

For #23772.
- Replace `ShardingTableRulesUsedAlgorithmResultSet` with `ShowShardingTableRulesUsedAlgorithmExecutor`
---

Refactor `ShardingTableRulesUsedAlgorithmResultSet`

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingTableRulesUsedKeyGeneratorExecutor.java
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRulesUsedKeyGeneratorResultSetTest.java

For #23772.
- Replace `ShowShardingTableRulesUsedKeyGeneratorResultSet` with `ShowShardingTableRulesUsedKeyGeneratorExecutor`
---

Refactor `ShowShardingTableRulesUsedKeyGeneratorResultSet` 

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingTableRulesUsedAuditorExecutor.java
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRulesUsedAuditorExecutorTest.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/ShowDefaultSingleTableStorageUnitExecutorTest.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/ShowSingleTableExecutorTest.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/ShowStorageUnitExecutorTest.java

For #23772.
- Replace `ShardingTableRulesUsedAuditorResultSet` with `ShowShardingTableRulesUsedAuditorExecutor`
---

Refactor `ShardingTableRulesUsedAuditorResultSet`

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowUnusedShardingAlgorithmsExecutor.java
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowUnusedShardingAlgorithmsExecutorTest.java

For #23772.
- Replace `UnusedShardingAlgorithmsResultSet` with `ShowUnusedShardingAlgorithmsExecutor`
---

Refactor `UnusedShardingAlgorithmsResultSet`

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowUnusedShardingKeyGeneratorExecutor.java
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowUnusedShardingKeyGeneratorExecutorTest.java

For #23772.
- Replace `UnusedShardingKeyGeneratorResultSet` with `ShowUnusedShardingKeyGeneratorExecutor`
---

Refactor `UnusedShardingKeyGeneratorResultSet`

---

agent/core/src/main/java/org/apache/shardingsphere/agent/core/log/AgentLoggerClassLoaderFactory.java
distribution/agent/src/main/assembly/shardingsphere-agent-binary-distribution.xml

Fixes #23868.
- Change the lib directory of the agent package to log-lib
---

Change the lib directory of the agent package to log-lib

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowUnusedShardingAuditorsExecutor.java
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowUnusedShardingAuditorsExecutorTest.java

For #23772.
- Replace `UnusedShardingAuditorsResultSet` with `ShowUnusedShardingAuditorsExecutor`
---

Refactor `UnusedShardingAuditorsResultSet`

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/CountShardingRuleExecutor.java
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/CountShardingRuleExecutorTest.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRulesUsedKeyGeneratorExecutorTest.java

Fixes #23772.
- Replace `CountShardingRuleResultSet` with `CountShardingRuleExecutor`
---

Replace `CountShardingRuleResultSet` with `CountShardingRuleExecutor`

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingTableReferenceRuleExecutor.java
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableReferenceRuleExecutorTest.java

For #23772.
- Replace `ShardingTableReferenceRuleResultSet` with `ShowShardingTableReferenceRuleExecutor`
---

Refactor `ShardingTableReferenceRuleResultSet`

---

test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/show_status_from_readwrite_splitting_rules.xml

Related to #23881, fix CI failed.
cause: `toLowerCase()` was removed.

Fix RAL CI failed.

---

.github/workflows/nightly-build-artifact.yml
distribution/proxy-native/Dockerfile
distribution/proxy-native/pom.xml
distribution/proxy-native/src/main/release-docs/LICENSE
distribution/proxy-native/src/main/release-docs/licenses/LICENSE-truffle-api.txt
distribution/proxy/src/main/release-docs/LICENSE
distribution/proxy/src/main/release-docs/licenses/LICENSE-truffle-api.txt
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
infra/util-groovy/pom.xml
infra/util-groovy/src/main/java/org/apache/shardingsphere/infra/util/groovy/expr/HotspotInlineExpressionParser.java
infra/util-groovy/src/test/java/org/apache/shardingsphere/infra/util/groovy/expr/HotspotInlineExpressionParserTest.java
infra/util/pom.xml
infra/util/src/main/java/org/apache/shardingsphere/infra/util/expr/EspressoInlineExpressionParser.java
infra/util/src/main/java/org/apache/shardingsphere/infra/util/expr/InlineExpressionParser.java
pom.xml

For #21347 and #22899.
- Introduce Truffle Espresso to make GroovyShell available under GraalVM Native Image
- Update GraalVM Reachability Metadata Repository to 0.2.6
- **Do not merge, this PR has not yet dealt with Maven Plugin related issues**
---

Introduce Truffle Espresso to make GroovyShell available under GraalVM Native Image

---

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/driver/jdbc/JDBCExecutorCallback.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/hook/SPISQLExecutionHook.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/hook/SQLExecutionHook.java
infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/jdbc/JDBCExecutorCallbackTest.java
infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/hook/SPISQLExecutionHookTest.java
infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/hook/fixture/SQLExecutionHookFixture.java
kernel/transaction/type/base/seata-at/src/main/java/org/apache/shardingsphere/transaction/base/seata/at/SeataATShardingSphereTransactionManager.java
kernel/transaction/type/base/seata-at/src/main/java/org/apache/shardingsphere/transaction/base/seata/at/SeataTransactionalSQLExecutionHook.java
kernel/transaction/type/base/seata-at/src/main/java/org/apache/shardingsphere/transaction/base/seata/at/SeataXIDContext.java
kernel/transaction/type/base/seata-at/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.executor.sql.hook.SQLExecutionHook
kernel/transaction/type/base/seata-at/src/test/java/org/apache/shardingsphere/transaction/base/seata/at/SeataIDContextTest.java
kernel/transaction/type/base/seata-at/src/test/java/org/apache/shardingsphere/transaction/base/seata/at/SeataTransactionalSQLExecutionHookTest.java

Ref #23884.
- Replace ExecutorDataMap with SeataXIDContext in SeataTransactionalSQLExecutionHook
- Rename TransactionalSQLExecutionHook to SeataTransactionalSQLExecutionHook
---

Replace ExecutorDataMap with SeataXIDContext in SeataTransactionalSQLExecutionHook

---

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/driver/jdbc/JDBCExecutorCallback.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/raw/RawExecutor.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/ExecuteProcessEngine.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/ExecuteProcessReporter.java
infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/jdbc/JDBCExecutorCallbackTest.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/DriverExecutor.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/DriverJDBCExecutor.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/batch/BatchPreparedStatementExecutor.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/callback/ExecuteQueryCallback.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/callback/impl/PreparedStatementExecuteQueryCallback.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/callback/impl/StatementExecuteQueryCallback.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/executor/batch/BatchPreparedStatementExecutorTest.java
kernel/sql-federation/api/src/main/java/org/apache/shardingsphere/sqlfederation/spi/SQLFederationExecutor.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/rule/SQLFederationRule.java
kernel/sql-federation/executor/advanced/src/main/java/org/apache/shardingsphere/sqlfederation/advanced/AdvancedSQLFederationExecutor.java
kernel/sql-federation/executor/advanced/src/test/java/org/apache/shardingsphere/sqlfederation/advanced/AdvancedSQLFederationExecutorTest.java
kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/FilterableTableScanExecutor.java
kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/TranslatableTableScanExecutor.java
kernel/sql-federation/executor/core/src/test/java/org/apache/shardingsphere/sqlfederation/executor/FilterableTableScanExecutorTest.java
kernel/sql-federation/executor/original/src/main/java/org/apache/shardingsphere/sqlfederation/original/OriginalSQLFederationExecutor.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/DatabaseCommunicationEngine.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/executor/ProxyJDBCExecutor.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/executor/callback/ProxyJDBCExecutorCallback.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/PreviewHandler.java
proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java
proxy/frontend/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutor.java

Ref #23884.
- remove useless eventBusContext in JDBCExecutorCallback and other usecase
- remove useless report method in ExecuteProcessReporter
---

Remove useless eventBusContext in JDBCExecutorCallback and other usecase

---

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/ExecuteProcessReporter.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/model/ExecuteProcessContext.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/model/ExecuteProcessUnit.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/model/yaml/YamlExecuteProcessContext.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/model/yaml/YamlExecuteProcessUnit.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/mysql/executor/ShowProcessListExecutor.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/admin/mysql/executor/ShowProcessListExecutorTest.java

Ref #23884.
- Unify ExecuteProcessStatusEnum variable name to processStatus
---

Unify ExecuteProcessStatusEnum variable name to processStatus

---

.github/workflows/e2e-agent.yml
.gitignore
distsql/parser/pom.xml
features/db-discovery/distsql/parser/pom.xml
features/encrypt/distsql/parser/pom.xml
features/mask/distsql/parser/pom.xml
features/readwrite-splitting/distsql/parser/pom.xml
features/shadow/distsql/parser/pom.xml
features/sharding/distsql/parser/pom.xml
kernel/authority/distsql/parser/pom.xml
kernel/data-pipeline/distsql/parser/pom.xml
kernel/parser/distsql/parser/pom.xml
kernel/sql-federation/optimizer/pom.xml
kernel/sql-translator/distsql/parser/pom.xml
kernel/traffic/distsql/parser/pom.xml
kernel/transaction/distsql/parser/pom.xml
pom.xml
sql-parser/dialect/mysql/pom.xml
sql-parser/dialect/opengauss/pom.xml
sql-parser/dialect/oracle/pom.xml
sql-parser/dialect/pom.xml
sql-parser/dialect/postgresql/pom.xml
sql-parser/dialect/sql92/pom.xml
sql-parser/dialect/sqlserver/pom.xml

Fixes #19990.
- Bump antlr4 to 4.10.1
- Only run `antlr4-maven-plugin` in JDK 11
- Add generated sources in JDK 8
- After merging this PR, we should clarify on docs and wiki that it needs to use **JDK 11** to build sources at first as it can generate codes for the g4 parseres.
---

Upgrade antlr4 to 4.10.1

---

features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/CountShadowRuleExecutorTest.java
kernel/authority/distsql/handler/src/main/java/org/apache/shardingsphere/authority/distsql/handler/ShowAuthorityRuleExecutor.java
kernel/authority/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.QueryableRALExecutor
kernel/authority/distsql/handler/src/test/java/org/apache/shardingsphere/authority/distsql/handler/ShowAuthorityRuleExecutorTest.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowTableMetaDataExecutor.java
proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.QueryableRALExecutor
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowTableMetaDataExecutorTest.java

For #23854.
- Replace `ShowTableMetaDataHandler` with `ShowTableMetaDataExecutor`
---

Replace `ShowTableMetaDataHandler` with `ShowTableMetaDataExecutor`

---

proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowStatusFromReadwriteSplittingRulesExecutor.java
proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.QueryableRALExecutor
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowStatusFromReadwriteSplittingRulesExecutorTest.java

For #23854.
- Replace `ShowStatusFromReadwriteSplittingRulesHandler` with `ShowStatusFromReadwriteSplittingRulesExecutor`
---

Refactor `ShowStatusFromReadwriteSplittingRulesHandler`

---

distsql/statement/src/main/java/org/apache/shardingsphere/distsql/parser/statement/ral/scaling/QueryableScalingRALStatement.java
kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationListExecutor.java
kernel/data-pipeline/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.QueryableRALExecutor
kernel/data-pipeline/distsql/handler/src/test/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationListExecutorTest.java

For #23854.
- Replace `ShowMigrationListResultSet` with `ShowMigrationListExecutor`
---

Replace `ShowMigrationListResultSet` with `ShowMigrationListExecutor`

---

kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationJobStatusExecutor.java
kernel/data-pipeline/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.QueryableRALExecutor
kernel/data-pipeline/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
kernel/data-pipeline/distsql/handler/src/test/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationJobStatusExecutorTest.java

For #23854.
- Replace `ShowMigrationJobStatusResultSet` with `ShowMigrationJobStatusExecutor`
---

Refactor `ShowMigrationJobStatusResultSet`

---

kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckStatusExecutor.java
kernel/data-pipeline/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.QueryableRALExecutor
kernel/data-pipeline/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
kernel/data-pipeline/distsql/handler/src/test/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckStatusExecutorTest.java

For #23854.
- Replace `ShowMigrationCheckStatusResultSet` with `ShowMigrationCheckStatusExecutor`
---

Refactor `ShowMigrationCheckStatusResultSet`

---

kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationSourceStorageUnitsExecutor.java
kernel/data-pipeline/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.QueryableRALExecutor
kernel/data-pipeline/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
kernel/data-pipeline/distsql/handler/src/test/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationSourceStorageUnitsExecutorTest.java

For #23854.
- Replace `ShowMigrationSourceStorageUnitsResultSet` with `ShowMigrationSourceStorageUnitsExecutor`
---

Refactor `ShowMigrationSourceStorageUnitsResultSet`

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/datasource/AbstractDataSourcePreparer.java
kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/prepare/datasource/OpenGaussDataSourcePreparer.java

- Move special prepareTargetSchemas impl to OpenGaussDataSourcePreparer
- Move special executeTargetTableSQL impl to OpenGaussDataSourcePreparer
---

Extract openGauss special impl from AbstractDataSourcePreparer to OpenGaussDataSourcePreparer

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/resource/ShardingSphereResourceMetaData.java

Fix storage type NPE causing the proxy to fail to start with -f
Fixes #24028.
-
---

Fix storage type NPE causing the proxy to fail to start with -f(#24028)

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/loader/PipelineTableMetaDataUtil.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/AbstractMigrationE2EIT.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java

- Fix data consistency check failed, when table with only unique keys
- Improve pipeline E2E
---

Fix data consistency check failed, when table with only unique keys

---

proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/QueryableRALBackendHandler.java
proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/QueryableRALBackendHandlerTest.java

Fixes #23930.
- Add test for `QueryableRALBackendHandler`
---

Add test for `QueryableRALBackendHandler`

---

kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/check/consistency/DataConsistencyCalculateParameter.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/spi/sqlbuilder/PipelineSQLBuilder.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/SingleTableInventoryDataConsistencyChecker.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/AbstractStreamingDataConsistencyCalculateAlgorithm.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/AbstractPipelineSQLBuilder.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/CloseUtil.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/fixture/FixturePipelineSQLBuilder.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithmTest.java

- Refactor DATA_MATCH consistency check by one query. Prepare for any index structure table's data consistency check.
---

Refactor DATA_MATCH consistency check by one query

---

sql-parser/dialect/mysql/src/main/antlr4/imports/mysql/DDLStatement.g4
test/it/parser/src/main/resources/case/ddl/create-procedure.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-procedure.xml

- Fix mysql create procedure syntax error.
---

Fix mysql create procedure syntax error.

---

kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/position/PrimaryKeyPosition.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/position/PrimaryKeyPositionFactory.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/position/UnsupportedKeyPosition.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/spi/sqlbuilder/PipelineSQLBuilder.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/InventoryDumper.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlJobItemInventoryTasksProgressSwapper.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/InventoryTaskSplitter.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/AbstractPipelineSQLBuilder.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/fixture/FixturePipelineSQLBuilder.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/check/consistency/MigrationDataConsistencyChecker.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/base/PipelineBaseE2EIT.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/container/compose/NativeContainerComposer.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/param/PipelineTestParameter.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/watcher/PipelineWatcher.java
test/e2e/pipeline/src/test/resources/env/common/migration-command.xml
test/e2e/pipeline/src/test/resources/env/common/none.xml
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/ingest/position/NoUniqueKeyPositionTest.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/ingest/position/UnsupportedKeyPositionTest.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/prepare/InventoryTaskSplitterTest.java

Related to #22500 
- Pipeline job support any type of single column unique key table
- Refactor NoUniqueKeyMigrationE2EIT to IndexesMigrationE2EIT; Refactor mysql.xml to none.xml
- Add special type single column unique key migration E2E
---

Pipeline job support any type of single column unique key table

---

test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/watcher/PipelineWatcher.java

- Refactor PipelineWatcher to ease troubleshooting. Print message on `succeeded/failed` just after unit test method finished, we could search `pipeline E2E failed` to locate it.
---

Refactor PipelineWatcher to ease troubleshooting

---

test/e2e/discovery/pom.xml
test/e2e/discovery/src/test/java/org/apache/shardingsphere/test/e2e/discovery/build/DiscoveryRuleBuilder.java
test/e2e/discovery/src/test/java/org/apache/shardingsphere/test/e2e/discovery/cases/base/BaseDiscoveryE2EIT.java
test/e2e/discovery/src/test/java/org/apache/shardingsphere/test/e2e/discovery/command/DiscoveryDistSQLCommand.java
test/e2e/discovery/src/test/java/org/apache/shardingsphere/test/e2e/discovery/pojo/DistSQLCommandPOJO.java
test/e2e/discovery/src/test/resources/env/common/discovery-command.xml

Refactor db-discovery it use awaitility framework replace sleep

---

.github/workflows/nightly-build-artifact.yml
distribution/proxy-native/Dockerfile
distribution/proxy-native/pom.xml
distribution/proxy-native/src/main/assembly/shardingsphere-proxy-native-binary-distribution.xml
distribution/proxy-native/src/main/release-docs/LICENSE
distribution/proxy/src/main/release-docs/LICENSE
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
infra/util-groovy/pom.xml
infra/util-groovy/src/main/java/org/apache/shardingsphere/infra/util/groovy/expr/HotspotInlineExpressionParser.java
infra/util/src/main/java/org/apache/shardingsphere/infra/util/expr/EspressoInlineExpressionParser.java
pom.xml

For #23873 and #21347.
- Fix nightly builds of ShardingSphere Proxy Native. Refer to https://github.com/apache/shardingsphere/actions/runs/4076339389/jobs/7023936873 .
- Fix release profile of ShardingSphere Proxy Native. Previously this Profile did not contain GraalVM Native Image binaries. Since the Release Profile is always executed after the Native Profile for ShardingSphere Proxy Native, it is a more reasonable choice to merge the two profiles.
- Update protobuf-java-util to match GraalVM reachability metadata. Reference https://github.com/oracle/graalvm-reachability-metadata/pull/167 .
- Update zookeeper to resolve ZOOKEEPER-4460 that prevents GraalVM Native Image from compiling, see https://github.com/oracle/graalvm-reachability-metadata/issues …

Fix nightly builds and release profile of ShardingSphere Proxy Native

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/engine/representer/processor/NoneYamlTupleProcessor.java
proxy/backend/src/test/resources/expected/export-database-configuration.yaml

Fixes #24074.
- Refactor `NoneYamlTupleProcessor`
---

Refactor `NoneYamlTupleProcessor`

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateDefaultShardingStrategyStatementUpdater.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/CreateDefaultShardingStrategyStatementUpdaterTest.java
features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java
proxy/frontend/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/authentication/MySQLAuthenticationEngineTest.java

For #23835.
- Make CREATE DEFAULT SHARDING STRATEGY support `None`ShardingStrategy TYPE
---

Make CREATE DEFAULT SHARDING STRATEGY support `None`ShardingStrategy TYPE

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterDefaultShardingStrategyStatementUpdater.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/AlterDefaultShardingStrategyStatementUpdaterTest.java
features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java

For #23835.
- Make ALTER DEFAULT SHARDING STRATEGY support `NoneShardingStrategy` TYPE
---

Make ALTER DEFAULT SHARDING STRATEGY support `NoneShardingStrategy` TYPE

---

features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/ShowDatabaseDiscoveryRuleExecutor.java
features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/ShowDatabaseDiscoveryRuleExecutorTest.java
features/db-discovery/distsql/parser/src/main/antlr4/imports/db-discovery/RQLStatement.g4
features/db-discovery/distsql/parser/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/parser/core/DatabaseDiscoveryDistSQLStatementVisitor.java
features/db-discovery/distsql/statement/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/parser/statement/ShowDatabaseDiscoveryRulesStatement.java

For #24158.
- Make `ShowDatabaseDiscoveryRule`support query specified rule with rule name
---

Make `ShowDatabaseDiscoveryRule`support query specified rule

---

features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/ShowDatabaseDiscoveryRuleExecutor.java
features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ShowReadwriteSplittingRuleExecutor.java
features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ShowReadwriteSplittingRuleExecutorTest.java
features/readwrite-splitting/distsql/parser/src/main/antlr4/imports/readwrite-splitting/RQLStatement.g4
features/readwrite-splitting/distsql/parser/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/parser/core/ReadwriteSplittingDistSQLStatementVisitor.java
features/readwrite-splitting/distsql/statement/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/parser/statement/ShowReadwriteSplittingRulesStatement.java

For #24158.
- Make `ShowReadwriteSplittingRule`support query specified rule with rule name
---

Make `ShowReadwriteSplittingRule`support query specified rule

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingTableReferenceRuleExecutor.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableReferenceRuleExecutorTest.java
features/sharding/distsql/parser/src/main/antlr4/imports/sharding/RQLStatement.g4
features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java
features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/statement/ShowShardingTableReferenceRulesStatement.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSet.java

For #24158.
- Make `ShowShardingTableReferenceRule`support query specified rule with rule name
---

Make `ShowShardingTableReferenceRule`support query specified rule

---

jdbc/core/src/main/java/org/apache/shardingsphere/driver/data/pipeline/datasource/creator/ShardingSpherePipelineDataSourceCreator.java

It's temp way in #24146.
- Recover max-connections-size-per-query setting to enable streaming query in pipeline job
---

Recover max-connections-size-per-query setting to enable streaming query in pipeline job

---

test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalSQLParserIT.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalSQLParserTestParameter.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/sql/SQLCases.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/sql/jaxb/SQLCase.java

- Add visitorType in sql parse it for more visit type test
---

Add visitorType in sql parse it for more visit type test

---

kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/position/PrimaryKeyPositionFactory.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/InventoryDumper.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java

- Fix multi unique key migration ignore inventory task when the first type is number
---

Fix multi unique key migration ignore inventory task when the first type is number

---

mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/ClusterModeContextManagerTest.java

Fixes #23123 .
https://github.com/apache/shardingsphere/issues/23123
Added test case for ClusterModeContextManager
- [✔️] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [✔️] I have self-reviewed the commit code.
- [✔️] I have (or in comment I request) added corresponding labels for the pull request.
- [✔️] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [✔️] I have made corresponding changes to the documentation.
- [✔️] I have added corresponding unit tests for my changes.

Add test case for ClusterModeContextManager

---

features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/api/sharding/standard/PreciseShardingValue.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/mod/HashModShardingAlgorithm.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/InsertClauseShardingConditionEngine.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/value/ListShardingConditionValue.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/strategy/type/standard/StandardShardingStrategy.java
features/sharding/plugin/cache/src/main/java/org/apache/shardingsphere/sharding/cache/checker/ShardingRouteCacheableChecker.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/ShardingSphereDriverTest.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURLManagerTest.java
jdbc/core/src/test/resources/config/driver/foo-driver-fixture.yaml
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java

Fixes #24210.
- Add unit test: insert data into varbinary column table
- Update IndexesMigrationE2EIT to test varbinary sharding column
- Support inserting data into varbinary sharding column table. Remove or replace related `Comparable<?>` for sharding algorithm `hash_mod`
sharding algorithm `mod` is not supported for varbinary, since `ModShardingAlgorithm.cutShardingValue`:
```
private BigInteger cutShardingValue(final Comparable<?> shardingValue) {
ShardingSpherePreconditions.checkState(shardingValue.toString().length() - stopOffset > startOffset, () -> new ShardingValueOffsetException(shardingValue, startOffset, stopOffset));
return 0 == startOffset && 0 == stopOffset ? getBigInteger(shardingValue) : new …
```

Support inserting data into varbinary sharding column table with hash_mod sharding algorithm

---

kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java

- Fix migration job target jdbc url changed. JdbcQueryPropertiesExtension will extend jdbc url parameters when job running, it's not necessary to change it in job configuration; once it's persisted in job cfg and there's imcompatible parameter, it's hard to update it.
- Improve migration job source initialization
- Extract createYamlJobConfiguration from createJobAndStart
---

Fix migration job target jdbc url parameters changed in job configuration

---

docs/document/content/user-manual/error-code/sql-error-code.cn.md
docs/document/content/user-manual/error-code/sql-error-code.en.md
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/swapper/ShardingRuleConfigurationConverter.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/ShardingRuleConfigurationConverterTest.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableNodesExecutorTest.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/data/pipeline/datasource/creator/ShardingSpherePipelineDataSourceCreator.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/metadata/NoAnyRuleExistsException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sharding/ShardingColumnsExtractor.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/RulesMigrationE2EIT.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java

- ShardingRuleConfigurationConverter.java is refactored, return Optional
- ShardingColumnsExtractor.getShardingColumnsMap return empty map if sharding rule doesn't exist
- ShardingSpherePipelineDataSourceCreator.createPipelineDataSource support sharding rule absent
- In MigrationJobAPI.createJobConfigAndStart, check rules empty or not, sharding rule could be absent
- Add RulesMigrationE2EIT, includes: 1) no any rule, 2) only encrypt rule.
---

Support proxy sharding rule absent for migration job

---

features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/rule/ReadwriteSplittingRule.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/constant/DistSQLScriptConstants.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationExecutor.java
proxy/backend/core/src/test/resources/conf/convert/config-sharding.yaml
proxy/backend/core/src/test/resources/expected/convert-sharding.yaml

For #23823.
- Add `none` sharding strategy type for `ConvertYamlConfigurationExecutor`
---

Add `none` sharding strategy type for `ConvertYamlConfigurationExecutor`

---

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/constant/DistSQLScriptConstants.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationExecutor.java
proxy/backend/core/src/test/resources/expected/convert-mix.yaml
proxy/backend/core/src/test/resources/expected/convert-sharding.yaml

For #23823.
- Add default sharding strategy for `ConvertYamlConfigurationExecutor`
---

Add default sharding strategy for `ConvertYamlConfigurationExecutor`

---

docs/document/content/test-manual/integration-test/_index.cn.md
docs/document/content/test-manual/integration-test/_index.en.md

- Fix e2e test compilation documentation
---

Fix e2e test compilation documentation

---

kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/datasource/MySQLJdbcQueryPropertiesExtension.java
kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/datasource/MySQLJdbcQueryPropertiesExtensionTest.java

refer: https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-result-sets.html
- Add netTimeoutForStreamingResults param at MySQLJdbcQueryPropertiesExtension
---

Add netTimeoutForStreamingResults param at MySQLJdbcQueryPropertiesExtension

---

examples/pom.xml
kernel/transaction/type/base/seata-at/pom.xml
kernel/transaction/type/base/seata-at/src/test/java/org/apache/shardingsphere/transaction/base/seata/at/fixture/MockMessageHandler.java

For #21347.
- Update seata-all to handle cglib breaking unit test execution with GraalVM Tracing Agent.
- Adapt to the changes made by Seata 1.6.x. Refer to https://github.com/seata/seata/issues/5343#issuecomment-1431053066 .
---

Update seata-all to handle cglib breaking unit test execution with GraalVM Tracing Agent

---

examples/pom.xml
kernel/transaction/type/base/seata-at/pom.xml
kernel/transaction/type/base/seata-at/src/test/java/org/apache/shardingsphere/transaction/base/seata/at/fixture/MockMessageHandler.java

- This reverts commit d7ccd647
---

Revert #24177 Seata upgrade error

---

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/algorithm.cn.md

The configuration of shadow algorithms is wrong, loadBalancers should be changed to shadowAlgorithms.
Fixes #24191.
-
- In the Chinese document of YAML algorithm configuration, the shadow algorithm configuration item changes `loadBalancers` to `shadowAlgorithms`.
---

Correct the Shadow Algorithm Chinese document

---

sql-parser/dialect/mysql/src/main/antlr4/imports/mysql/TCLStatement.g4
test/it/parser/src/main/resources/case/tcl/begin-transaction.xml
test/it/parser/src/main/resources/sql/supported/tcl/begin-transcation.xml

according to official documentation, **BEGIN** statement has an optional keyword '**WORK**'
syntax:
```
BEGIN [WORK]
```

Fix grammar for mysql begin statement

---

db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/binlog/row/column/value/string/MySQLBinaryString.java
db-protocol/mysql/src/test/java/org/apache/shardingsphere/db/protocol/mysql/packet/binlog/row/column/value/string/MySQLVarcharBinlogProtocolValueTest.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineJdbcUtils.java
kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLIncrementalDumper.java
kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLBinlogEventPacketDecoderTest.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/base/PipelineBaseE2EIT.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java

- Compatible with BINARY/VARBINARY column type in MySQL binlog parsing
---

Compatible with BINARY/VARBINARY column type in MySQL binlog parsing

---

sql-parser/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select-special-function.xml

Fixes #24398 
Added support for all possible Mysql queries for Extract function
(reference : MySQL documentation)

support for Extract Function

---

kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/datasource/MySQLJdbcQueryPropertiesExtension.java
kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/datasource/MySQLJdbcQueryPropertiesExtensionTest.java

Currently, `useServerPrepStmts` is set to `true` in `MySQLDataSourceMetaData`, and it's `false` by default in MySQL JDBC driver.
Set `useServerPrepStmts=true` will cause too many prepared statements in MySQL server. It could be verified by SQLs:
```
SHOW GLOBAL STATUS LIKE '%prepared_stmt_count%';
SELECT * FROM performance_schema.prepared_statements_instances;
```
By default, `max_prepared_stmt_count` in MySQL is `16382`.
If there're thousands of sharding tables, then it might cause error: `Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)`.
And set `useServerPrepStmts=true` might hurt batch insert performance.
So `useServerPrepStmts` will be set to `false` in pipeline job.
Ref [MySQL Connector/J]( …

Add useServerPrepStmts=false for pipeline job on MySQL

---

test/e2e/suite/src/test/resources/cases/dql/dql-integration-select-expression.xml
test/e2e/suite/src/test/resources/cases/ral/ral-integration-set.xml
test/e2e/suite/src/test/resources/cases/ral/ral-integration-show.xml

Ref #24540.
- Revert SHOW DIST VARIABLES test case for e2e build
---

Revert SHOW DIST VARIABLES test case for e2e build

---

kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/check/consistency/DataConsistencyCalculateParameter.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/ingest/DumperConfiguration.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/ingest/InventoryDumperConfiguration.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/metadata/ColumnName.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/metadata/model/PipelineTableMetaData.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/spi/sqlbuilder/PipelineSQLBuilder.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/SingleTableInventoryDataConsistencyChecker.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/DataSourceImporter.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/InventoryDumper.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/AbstractPipelineSQLBuilder.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/fixture/FixturePipelineSQLBuilder.java
kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLIncrementalDumper.java
kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLIncrementalDumperTest.java
kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALEventConverter.java
kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALEventConverterTest.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/check/consistency/MigrationDataConsistencyChecker.java
test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/fixture/FixtureColumnValueReader.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/spi/sqlbuilder/PipelineSQLBuilderTest.java
test/it/pipeline/src/test/resources/META-INF/services/org.apache.shardingsphere.data.pipeline.spi.ingest.dumper.ColumnValueReader

- Compatible with inventory dump, use custom columns to ingest data and write into target
- Compatible with incremental dump, use custom columns to filter columns and write into target
- Compatible with data consistency check, use custom columns to ingest and calculate
- Refactor WALEventConverter
- Add unit test for WALEventConverter and MySQLIncrementalDumper, to verify columns filtering. Add unit test for AbstractPipelineSQLBuilder, to verify SQL building.
- Remove BasicColumnValueReader, add H2 SPI impl FixtureColumnValueReader
---

Support custom columns in pipeline job

---

kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/context/job/CDCJobItemContext.java
kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/ack/CDCAckPosition.java
kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/util/CDCDataRecordUtil.java
kernel/data-pipeline/cdc/core/src/test/java/org/apache/shardingsphere/data/pipeline/cdc/core/ack/CDCAckHolderTest.java

- Fix incorrect count under concurrency of CDC job 
- Fix incremental task not starting correctly after job restart, the status will reset at InventoryIncrementalTasksRunner, so need remove at init
---

Fix incorrect count under concurrency of CDC job

---

.github/workflows/e2e.yml
.github/workflows/nightly-e2e.yml
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/MySQLContainer.java

for #24575.
- update timeout for `db` scenario
- set the mysql default docker image version to 5.1.39
---

Refactor : refactor the timeout for db scenario (#24575)

---

db-protocol/mysql/src/test/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/protocol/MySQLTimeBinaryProtocolValueTest.java

Fixes #24557.
When the time zone is New Zealand, `assertWriteWithTwelveBytes` will fail, because the time zone of New Zealand is `GMT+12`, and the `hourOfDay` corresponding to GMT 0 o'clock is `12`, which will cause `writeInt1(12)` to be called twice.
---

Fixes #24557

---

features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/RDLStatement.g4
kernel/time-service/type/database/pom.xml
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java

- Remove useless resourceDefinition in `encrypt/RDLStatement.g4`
- Fix a dependency version in pom.xml
---

Remove useless resourceDefinition in `encrypt/RDLStatement.g4`

---

src/resources/checkstyle.xml
src/resources/checkstyle_ci.xml

This reverts commit cd9737c0a8231b581b70cf9c4c3c8b8f56e558cd.
Related to #19708
Since the `org.mockito.quality.Strictness#LENIENT` which is an equivalent of `org.mockito.junit.MockitoJUnitRunner.Silent` was widely used recently, the checkstyle rules were broken.

Revert broken checkstyle rule about Mockito Strictness

---

sql-parser/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
sql-parser/dialect/mysql/src/main/antlr4/imports/mysql/MySQLKeyword.g4
sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml
test/it/parser/src/main/resources/sql/unsupported/unsupported.xml

Fixes #24398 .
1.  Added support for this in ANTLR :
[CAST(timestamp_value AT TIME ZONE timezone_specifier AS DATETIME[(precision)])]
(https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast)
2. Optimised MySQLStatementSQLVisitor#visitCastFunction

support for CAST Function

---

sql-parser/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
test/it/parser/src/main/resources/case/dml/select-expression.xml
test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml

Fixes #24424.
- support mysql [member of](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_member-of) grammar, 
---

Fixes #24424, support mysql member of grammar

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java

- Remove useless method in ShardingRule
---

Remove useless method in ShardingRule

---

.github/workflows/nightly-ci.yml

Fixes #24653.
- refactor JDK 8 for nightly CI
---

Refactor : add JDK 8 CI in nightly CI (#24653)

---

test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/engine/E2EContainerComposer.java
test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/engine/dql/BaseDQLE2EIT.java

- Fix sql federation e2e test error when logical datasource change
---

Fix sql federation e2e test error when logical datasource change

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/SingleTableInventoryDataConsistencyChecker.java

- Enable concurrent CRC32 match on source and target
---

Enable concurrent CRC32 match on source and target

---

kernel/logging/core/src/main/java/org/apache/shardingsphere/logging/yaml/swapper/YamlLoggingRuleConfigurationSwapper.java

Fixes  #24728.
- refactor YamlLoggingRuleConfigurationSwapper
---

Refactor YamlLoggingRuleConfigurationSwapper

---

features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/checker/ReadwriteSplittingRuleConfigurationChecker.java
features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/checker/ReadwriteSplittingRuleConfigurationCheckerTest.java

- fix ReadwriteRule checkReadeDataSource and test(The problem is that the readwrite splitting rule the slave dataSource are not verified as expected) 
---

fix ReadwriteRule checkReadeDataSource and test

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/job/JobStatus.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/InventoryTaskSplitter.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryIncrementalTasksRunner.java
kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/task/ConsistencyCheckTasksRunner.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/prepare/MigrationJobPreparer.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java

- Return inventory position if it's present in InventoryTaskSplitter, remove PREPARING_FAILURE check
- Remove FAILURE job item progress persistence: PREPARING_FAILURE, EXECUTE_INVENTORY_TASK_FAILURE, EXECUTE_INCREMENTAL_TASK_FAILURE, CONSISTENCY_CHECK_FAILURE
---

Improve pipeline job failure status persistence and usage

---

proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/command/CommandExecutorTask.java

- Print expected type of exception when debug is enabled in proxy. For better troubleshooting, since exception might be thrown in unexpected scenario (e.g. bug), though the exception type is expected. Then we could run DistSQL `SET DIST VARIABLE system_log_level='DEBUG';` to get exception stack trace.
---

Print expected type of exception when debug is enabled in proxy

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
infra/common/src/main/resources/schema/mysql/information_schema/innodb_ft_config.yaml
infra/common/src/main/resources/schema/mysql/information_schema/innodb_ft_default_stopword.yaml
infra/common/src/main/resources/schema/mysql/information_schema/innodb_ft_deleted.yaml
infra/common/src/main/resources/schema/mysql/information_schema/innodb_ft_index_cache.yaml
infra/common/src/main/resources/schema/mysql/information_schema/innodb_ft_index_table.yaml
infra/common/src/main/resources/schema/mysql/information_schema/innodb_lock_waits.yaml
infra/common/src/main/resources/schema/mysql/information_schema/innodb_locks.yaml
infra/common/src/main/resources/schema/mysql/information_schema/innodb_metrics.yaml
infra/common/src/main/resources/schema/mysql/information_schema/innodb_sys_columns.yaml
infra/common/src/main/resources/schema/mysql/information_schema/innodb_sys_datafiles.yaml
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_ft_config.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_ft_default_stopword.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_ft_deleted.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_ft_index_cache.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_ft_index_table.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_lock_waits.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_locks.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_metrics.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_sys_columns.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_sys_datafiles.xml
test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema.xml

For #24662 .
- Add more mysql information schema tables
---

Add more mysql information schema tables

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateDefaultShardingStrategyStatementUpdater.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/CreateDefaultShardingStrategyStatementUpdaterTest.java

Fixes #24770.
- Remove sharding rule configuration check in `CreateDefaultShardingStrategyStatementUpdater`
---

Fix create default sharding strategy while sharding rule configuration is null

---

docs/document/content/user-manual/common-config/sql-hint.cn.md
docs/document/content/user-manual/common-config/sql-hint.en.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/readwrite-splitting/hint.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/readwrite-splitting/hint.en.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/sharding/hint.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/sharding/hint.en.md

- Add new sql hint document and move sharding, readwrite-splitting sql hint document to new document
---

Add new sql hint document and move sharding, readwrite-splitting sql hint document to new document

---

distribution/proxy/src/main/resources/bin/start.sh

Fixes #24892
-
as title.
Test steps:
1. use this script to build the image.
```docker
FROM alpine AS prepare
ARG APP_NAME="apache-shardingsphere-5.3.2-SNAPSHOT-shardingsphere-proxy-bin"
ENV LOCAL_PATH /opt/shardingsphere-proxy
ADD target/${APP_NAME}.tar.gz /opt
RUN mv /opt/${APP_NAME} ${LOCAL_PATH} && mkdir -p ${LOCAL_PATH}/ext-lib
FROM eclipse-temurin:17-jdk
MAINTAINER ShardingSphere "dev@shardingsphere.apache.org"
ENV LOCAL_PATH /opt/shardingsphere-proxy
ENV IS_DOCKER true
COPY --from=prepare ${LOCAL_PATH} ${LOCAL_PATH}
ENTRYPOINT ${LOCAL_PATH}/bin/start.sh ${PORT} -g
```
2. uncomment `/opt/shardingsphere-proxy/agent/conf/agent.yaml`
```
plugins:
logging:
File:
props:
level: "INFO"
metrics:
Prometheus:
host:  "localhost"
port: 9090
props: …
```

Specifying the agent argument in Docker env

---

infra/util/src/main/java/org/apache/shardingsphere/infra/util/expr/EspressoInlineExpressionParser.java
infra/util/src/test/java/org/apache/shardingsphere/infra/util/expr/InlineExpressionParserTest.java

For #24902.
- Fix wrong classpath in Espresso context. 
- For #24902 and https://github.com/apache/shardingsphere/commit/7ee273dd209c6b93c6b8f3b1a18049e112c75202 .
---

Fix wrong classpath in Espresso context

---

test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-join.xml
test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-projection.xml

- Modify select join statement e2e
I made some modifications to the order of the join test cases to make it clearer,
First sort by join type:
JOIN
INNER JOIN
FULL JOIN
CROSS JOIN
LEFT JOIN
RIGHT JOIN
Then sort by join clause:
ON,USING,NATURAL
Then sort by where..order by clause:
WHERE...ORDER BY...
---

Modify select join statement e2e

---

distribution/proxy-native/src/main/release-docs/LICENSE
distribution/proxy/src/main/release-docs/LICENSE
examples/pom.xml
kernel/transaction/type/base/seata-at/pom.xml
kernel/transaction/type/base/seata-at/src/test/java/org/apache/shardingsphere/transaction/base/seata/at/SeataATShardingSphereTransactionManagerTest.java
kernel/transaction/type/base/seata-at/src/test/java/org/apache/shardingsphere/transaction/base/seata/at/fixture/MockMessageHandler.java
pom.xml

Fixes #24177 and #24382.
- Update seata-all to handle cglib breaking unit test execution with GraalVM Tracing Agent. Refer to https://github.com/apache/shardingsphere/pull/24177 .  
- Update netty to get graalvm reachability metadata for `io.netty:netty-transport-classes-epoll`. Refer to https://github.com/netty/netty/pull/13242 and https://github.com/netty/netty/pull/13158 .
- For https://github.com/apache/shardingsphere/issues/21347 .
---

Update seata-all and netty to fix nativeTest in GraalVM Native Build Tools

---

kernel/data-pipeline/core/pom.xml
kernel/transaction/type/base/seata-at/pom.xml

- Exclude com.sun:tools and com.sun:jconsole in seata-at module
- Remove non-existing shardingsphere-schedule-core module dependency. `shardingsphere-schedule-core` module was removed in #24956
---

Fix local install failure

---

features/readwrite-splitting/distsql/parser/src/main/antlr4/imports/readwrite-splitting/Keyword.g4

For #24906.
- remove AUTO_AWARE_RESOURCE in readwrite-splitting DistSQL.

For #24906, remove AUTO_AWARE_RESOURCE in readwrite-splitting DistSQL.

---

kernel/data-pipeline/cdc/protocol/pom.xml

refer https://github.com/trustin/os-maven-plugin#issues-with-eclipse-m2e-or-other-ides
because the extensions already exists at root pom
- Remove non-essential extensions
---

Remove non-essential extensions at CDC protocol module

---

kernel/data-pipeline/cdc/client/src/test/java/org/apache/shardingsphere/data/pipeline/cdc/client/util/ProtobufAnyValueConverterTest.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/context/PipelineContextKeyTest.java

Use assertThat to instead of assertEquals.
---

Use assertThat to instead of assertEquals

---

kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/executor/GlobalClockTransactionHook.java
kernel/global-clock/type/tso/provider/redis/pom.xml
kernel/global-clock/type/tso/provider/redis/src/main/java/org/apache/shardingsphere/globalclock/type/tso/provider/RedisTSOProperties.java
kernel/global-clock/type/tso/provider/redis/src/main/java/org/apache/shardingsphere/globalclock/type/tso/provider/RedisTSOProvider.java

For https://github.com/apache/shardingsphere/issues/24519
* Add RedisTSOProvider of GlobalClock
---

add RedisTSOProvider of GlobalClock

---

kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClient.java

Many exceptions cannot be resolved even after reconnecting, so remove it.
- Remove reconnect when exception caught at MySQLClient
---

Remove reconnect when exception caught at MySQLClient

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/ImporterConfiguration.java
kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLIncrementalDumper.java
kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALEventConverter.java

It is possible that MySQL is case-sensitive in table names, so keep origin table name
- Keep original table name at MySQL incremental task
---

Keep original table name in pipeline incremental task

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/util/SystemSchemaUtils.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/util/SystemSchemaUtilsTest.java

Fixes #25109.
- fix object not found exception when config opengauss schema name as database name
---

Fix object not found exception when config opengauss schema name as database name

---

features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/checker/ReadwriteSplittingRuleStatementChecker.java
features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/AlterReadwriteSplittingRuleStatementUpdaterTest.java
features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/CreateReadwriteSplittingRuleStatementUpdaterTest.java
infra/common/src/main/java/org/apache/shardingsphere/infra/rule/identifier/type/exportable/constant/ExportableConstants.java

- Refactor checkDuplicateRuleNames of ReadwriteSplittingRuleStatementChecker
- Updata related test cases
---

Refactor checkDuplicateRuleNames of ReadwriteSplittingRuleStatementChecker

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
infra/common/src/main/resources/schema/mysql/performance_schema/events_statements_current.yaml
infra/common/src/main/resources/schema/mysql/performance_schema/events_statements_history.yaml
infra/common/src/main/resources/schema/mysql/performance_schema/events_statements_history_long.yaml
infra/common/src/main/resources/schema/mysql/performance_schema/events_statements_summary_by_account_by_event_name.yaml
infra/common/src/main/resources/schema/mysql/performance_schema/events_statements_summary_by_digest.yaml
infra/common/src/main/resources/schema/mysql/performance_schema/events_statements_summary_by_host_by_event_name.yaml
infra/common/src/main/resources/schema/mysql/performance_schema/events_statements_summary_by_program.yaml
infra/common/src/main/resources/schema/mysql/performance_schema/events_statements_summary_by_thread_by_event_name.yaml
infra/common/src/main/resources/schema/mysql/performance_schema/events_statements_summary_by_user_by_event_name.yaml
infra/common/src/main/resources/schema/mysql/performance_schema/events_statements_summary_global_by_event_name.yaml
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_statements_current.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_statements_history.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_statements_history_long.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_statements_summary_by_account_by_event_name.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_statements_summary_by_digest.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_statements_summary_by_host_by_event_name.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_statements_summary_by_program.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_statements_summary_by_thread_by_event_name.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_statements_summary_by_user_by_event_name.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_statements_summary_global_by_event_name.xml
test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema.xml

For #24662 .
- Add more mysql performance_schema tables
---
- [v] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.

Add more mysql performance_schema tables

---

features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/YamlReadwriteSplittingRuleConfigurationSwapper.java

- Add check for `dataSourceRuleConfig.getTransactionalReadQueryStrategy()` is null
---

Fix swap ReadwriteSplittingDataSourceRuleConfiguration to YAML

---

db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/binlog/row/column/value/time/MySQLDatetime2BinlogProtocolValue.java
infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/pool/creator/DataSourceReflection.java
kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/datasource/config/impl/ShardingSpherePipelineDataSourceConfiguration.java
kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClient.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLTimeTypesMigrationE2EIT.java

refer https://dev.mysql.com/doc/refman/8.0/en/datetime.html
MySQL may have the datetime value wiht '0000-00-00 00:00:00', but the value is illegal for `LocalDateTime` at java.
- Fix the error of incremental tasks caused by datetime containing zero value in MySQL
- Fix MySQLClient always print error log when decode binlog failed.
---

Fix the error of incremental tasks caused by datetime containing zero value in MySQL

---

db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescription.java
db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLRowDescriptionPacket.java
proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/Portal.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PortalTest.java

when using with gorm ,   select int column,     gorm  will check  valueFormat in the row description  to decide how to deal with the column value , but  the format is always  0(text),  then gorm treat  int8 array as string, then it failed to convert 
cuz format = 0, then `strconv.ParseUint(string(src), 10, 64)`
error message as follows:
convert field 0 failed: strconv.ParseInt: parsing "\x00\x00\x00\x00\x00\x00\x00\x16": invalid syntax [437.417ms] [rows:0] INSERT INTO "t_student_info_copy" ("student_name","id") VALUES ('go name',22) RETURNING "id" &{0xc0000ee510 convert field 0 failed: strconv.ParseInt: parsing "\x00\x00\x00\x00\x00\x00\x00\x16": invalid syntax 0 0xc000242380 0}

pg, set valueformat of row description in bind command

---

docs/document/content/dev-manual/transaction.cn.md
docs/document/content/dev-manual/transaction.en.md
docs/document/content/user-manual/error-code/sql-error-code.cn.md
docs/document/content/user-manual/error-code/sql-error-code.en.md
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/XAShardingSphereTransactionManager.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/datasource/checker/DataSourcePrivilegeChecker.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/datasource/checker/DefaultDataSourcePrivilegeChecker.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/datasource/checker/dialect/MySQLDataSourcePrivilegeChecker.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/exception/XATransactionCheckPrivilegeFailedException.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/exception/XATransactionPrivilegeException.java
kernel/transaction/type/xa/core/src/main/resources/META-INF/services/org.apache.shardingsphere.transaction.xa.jta.datasource.checker.DataSourcePrivilegeChecker
kernel/transaction/type/xa/core/src/test/java/org/apache/shardingsphere/transaction/xa/jta/datasource/checker/MySQLDataSourcePrivilegeCheckerTest.java

- Add xa transaction data source privilege checker
---

Add xa transaction data source privilege checker

---

.github/workflows/nightly-build-artifact.yml
distribution/proxy-native/access-filter.json
distribution/proxy-native/caller-filter.json
distribution/proxy-native/pom.xml
distribution/proxy-native/src/main/release-docs/LICENSE
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
infra/util/pom.xml
infra/util/src/main/java/org/apache/shardingsphere/infra/util/expr/EspressoInlineExpressionParser.java
pom.xml

For #21347.
- Initialize the collectReachabilityMetadata Maven Task of all module. Since https://github.com/graalvm/native-build-tools/issues/403 is not closed, it is inconvenient to collect GraalVM Reachability Metadata in Conditional form.
- Modify the name of the `native` profile to `release.native`, and simplify the command line parameters used in the document.
- Update GraalVM Native Build Tools to 0.9.21.
---

Initialize the generateStandardMetadata Maven Profile of all module

---

.github/workflows/ci.yml
.github/workflows/nightly-ci.yml
agent/core/src/main/java/org/apache/shardingsphere/agent/core/builder/AgentTransformer.java
agent/pom.xml

Fixes #25126.
- Update Byte Buddy to 1.14.4.
- Reference https://github.com/raphw/byte-buddy/commit/52479e4fd0dd50595786089bd00de2be750e8031 and https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/23.1.0-dev-20230414_0206 .
- Associated with https://github.com/apache/shardingsphere/issues/25054 .
---

Supports compilation through OpenJDK 20 and its downstream distributions

---

agent/core/src/test/java/org/apache/shardingsphere/agent/core/plugin/PluginContextTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariableExecutorTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesExecutorTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableUpdaterTest.java

- Add reset for property AGENT_PLUGINS_ENABLED in unit test
---

Add reset for property AGENT_PLUGINS_ENABLED in unit test

---

features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/route/qualified/type/QualifiedReadwriteSplittingPrimaryDataSourceRouterTest.java

Add test cases for QualifiedReadwriteSplittingPrimaryDataSourceRouter.

---

kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/ingest/InventoryDumperConfiguration.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PipelineImporterJobWriteException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/DataSourceImporter.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/InventoryDumper.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/migration/check/consistency/MigrationDataConsistencyCheckerTest.java

Optimize the error message display when importer job write failed and exceeded the required number of retries
- Improve pipeline importer job write exception
- Add transaction isolation at inventory dump config
- Improve unit test
---

Improve pipeline importer job write exception

---

infra/common/src/main/java/org/apache/shardingsphere/infra/config/props/temporary/TemporaryConfigurationProperties.java
infra/common/src/main/java/org/apache/shardingsphere/infra/config/props/temporary/TemporaryConfigurationPropertyKey.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaData.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataJobWorker.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariableExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableUpdater.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariableExecutorTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesExecutorTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableUpdaterTest.java

- Rename internal props to temporary props, to prevent users misuse it, because these configuration items are temporary experimental configurations and may be deleted at any time.
---

Rename internal props to temporary props

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/ShardingStatementValidatorFactory.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/impl/ShardingLoadDataStatementValidator.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/impl/ShardingLoadXMLStatementValidator.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/SQLStatementContextFactory.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/LoadDataStatementContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/LoadXMLStatementContext.java
sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDMLStatementSQLVisitor.java
sql-parser/engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/dml/MySQLLoadDataStatement.java
sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/dml/MySQLLoadXMLStatement.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/DMLStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/LoadDataStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/LoadXMLStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/dml/LoadDataStatementTestCase.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/dml/LoadXMLStatementTestCase.java
test/it/parser/src/main/resources/case/dml/load-data.xml
test/it/parser/src/main/resources/case/dml/load-xml.xml
test/it/parser/src/main/resources/sql/supported/dml/load-data.xml
test/it/parser/src/main/resources/sql/supported/dml/load-xml.xml

Fixes #25227.
- Support mysql load data, load xml statement for single table, broadcast table
- add unit test for sql parser
---

Support mysql load data, load xml statement for single table, broadcast table

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dal/show/ShowCreateTableMergedResult.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTable.java
infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/schema/swapper/YamlTableSwapper.java
infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/index/AlterIndexStatementSchemaRefresher.java
infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/index/CreateIndexStatementSchemaRefresher.java
infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/index/DropIndexStatementSchemaRefresher.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/translatable/FederationTranslatableTable.java

Fixes #25234.
- Fix NullPointerException when execute information schema query with sql federation
---

Fix NullPointerException when execute information schema query with sql federation

---

pom.xml

Build failed with error Could not find resource 'src/resources/spotless/java.xml' if working dir is not root of ShardingSphere

---

kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/channel/PipelineChannel.java
kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/importer/SocketSinkImporter.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/DataSourceImporter.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/MultiplexMemoryPipelineChannel.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/SimpleMemoryPipelineChannel.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/MultiplexMemoryPipelineChannelTest.java
kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLIncrementalDumperTest.java
kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLWALDumperTest.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/importer/DataSourceImporterTest.java

Related to #22500 
- Refactor PipelineChannel.fetchRecords, remove hard-coded seconds time unit
- Reduce CDC fetching records waiting time
---

Reduce CDC fetching records waiting time

---

agent/core/pom.xml
agent/core/src/main/java/org/apache/shardingsphere/agent/core/ShardingSphereAgent.java
agent/core/src/main/java/org/apache/shardingsphere/agent/core/advisor/executor/type/ConstructorAdviceExecutor.java
agent/core/src/main/java/org/apache/shardingsphere/agent/core/advisor/executor/type/InstanceMethodAdviceExecutor.java
agent/core/src/main/java/org/apache/shardingsphere/agent/core/advisor/executor/type/StaticMethodAdviceExecutor.java
agent/core/src/main/java/org/apache/shardingsphere/agent/core/plugin/PluginContext.java
agent/core/src/main/java/org/apache/shardingsphere/agent/core/util/AgentReflectionUtils.java
agent/core/src/test/java/org/apache/shardingsphere/agent/core/plugin/PluginContextTest.java
agent/plugins/core/src/main/java/org/apache/shardingsphere/agent/plugin/core/recorder/MethodTimeRecorder.java
agent/pom.xml
infra/common/src/main/java/org/apache/shardingsphere/infra/config/props/ConfigurationPropertyKey.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/enums/VariableEnum.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariableExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableUpdater.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariableExecutorTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableUpdatableRALBackendHandlerTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableUpdaterTest.java

Fixes #25371.
- Moved `agent_plugins_enabled` variable to global props
---

Moved agent_plugins_enabled variable to global props

---

mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/subscriber/ProcessListChangedSubscriber.java
mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/event/KillProcessCompletedEvent.java
mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/watcher/ComputeNodeStateChangedWatcher.java
mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/subscriber/ProcessListChangedSubscriberTest.java

Reverts apache/shardingsphere#25454

Revert "Remove KillProcessCompletedEvent"

---

kernel/data-pipeline/cdc/client/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/client/handler/CDCRequestHandler.java
kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/handler/CDCBackendHandler.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractInventoryIncrementalJobAPIImpl.java
proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/CDCChannelInboundHandler.java

- Improve cdc stop job when channel inactive, make sure stop job correctly
- Fix getJobItemInfos may lose error message
---

Improve cdc stop job when channel inactive

---

infra/expr/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParser.java

For #25509.
- Restrict Espresso API to only detect JAVA_HOME under Native Image.
---

Restrict Espresso API to only detect JAVA_HOME under Native Image

---

infra/util/pom.xml
kernel/sql-parser/api/pom.xml
parser/sql/statement/pom.xml

For #25509.
- Remove deleted module from the infra-util module POM.
---

Remove deleted module from the infra-util module POM

---

docs/blog/content/material/proxyIntroduce.cn.md
docs/document/content/quick-start/shardingsphere-proxy-quick-start.cn.md
docs/document/content/quick-start/shardingsphere-proxy-quick-start.en.md
docs/document/content/user-manual/shardingsphere-proxy/migration/build.cn.md
docs/document/content/user-manual/shardingsphere-proxy/migration/build.en.md
docs/document/content/user-manual/shardingsphere-proxy/startup/bin.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/bin.en.md
examples/pom.xml
pom.xml
test/e2e/agent/plugins/logging/file/src/test/resources/docker/proxy/Dockerfile
test/e2e/agent/plugins/metrics/prometheus/src/test/resources/docker/proxy/Dockerfile
test/e2e/agent/plugins/tracing/jaeger/src/test/resources/docker/proxy/Dockerfile
test/e2e/agent/plugins/tracing/zipkin/src/test/resources/docker/proxy/Dockerfile

Refer to https://bugs.mysql.com/bug.php?id=93590
Try eliminating warnings like
```
Tue May 09 11:34:28 UTC 2023 WARN: Caught while disconnecting...
EXCEPTION STACK TRACE:
** BEGIN NESTED EXCEPTION ** 
javax.net.ssl.SSLException
MESSAGE: closing inbound before receiving peer's close_notify
STACKTRACE:
javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
at sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:740)
at sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:719)
at com.mysql.jdbc.MysqlIO.quit(MysqlIO.java:2249)
at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4232)
at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1472)
at org.apache.shardingsphere.test.e2e.env.container.wait.JdbcConnectionWaitStrategy.lambd …
```

Bump MySQL Connector/J from 5.1.47 to 5.1.49

---

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
test/it/parser/src/main/resources/case/ddl/alter-table.xml
test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml

Fixes #25535.
- Support the precision of the column as a decimal.
---

Support the precision of the column as a decimal.

---

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/alter-encrypt-rule.cn.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/alter-encrypt-rule.en.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/create-encrypt-rule.cn.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/create-encrypt-rule.en.md
features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleStatementUpdater.java
features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdater.java
features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleStatementUpdaterTest.java
features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdaterTest.java
features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/Keyword.g4
features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/RDLStatement.g4
features/encrypt/distsql/parser/src/main/java/org/apache/shardingsphere/encrypt/distsql/parser/core/EncryptDistSQLStatementVisitor.java
features/encrypt/distsql/statement/src/main/java/org/apache/shardingsphere/encrypt/distsql/parser/segment/EncryptColumnSegment.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/loader/ExternalMySQLTestParameterLoader.java

- Simplify ASSISTED_QUERY_COLUMN to ASSISTED_QUERY, LIKE_QUERY_COLUMN to LIKE_QUERY in DistSQL.
- Remove useless dataType in DistSQL.
---

Simplify ASSISTED_QUERY_COLUMN to ASSISTED_QUERY, LIKE_QUERY_COLUMN to LIKE_QUERY in DistSQL.

---

parser/sql/dialect/mysql/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/mysql/external/ExternalMySQLParserIT.java
parser/sql/dialect/postgresql/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/postgresql/external/ExternalPostgreSQLParserIT.java
src/resources/checkstyle.xml

- Add LineLength ignorePattern to avoid checkstyle exception temporarily
---

Add LineLength ignorePattern to avoid checkstyle exception temporarily

---

features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFromXToYMaskAlgorithm.java
features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFromXToYMaskAlgorithm.java
features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFirstNLastMMaskAlgorithmTest.java
features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFromXToYMaskAlgorithmTest.java
features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFirstNLastMMaskAlgorithmTest.java
features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFromXToYMaskAlgorithmTest.java

Fixes #25616.
- Fix wrong mask result when config same value of from-x and to-y with KEEP_FROM_X_TO_Y
- add more unit test for mask algorithm
---

Fix wrong mask result when config same value of from-x and to-y with KEEP_FROM_X_TO_Y

---

infra/expr/core/src/main/java/org/apache/shardingsphere/infra/expr/core/InlineExpressionParserFactory.java
infra/expr/core/src/test/java/org/apache/shardingsphere/infra/expr/core/InlineExpressionParserFactoryTest.java
infra/expr/espresso/pom.xml
infra/expr/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParser.java
infra/expr/espresso/src/test/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParserTest.java
pom.xml

For #25509.
- Fix build-proxy-native-image job on Nightly Build. Refer to https://github.com/apache/shardingsphere/actions/runs/4957033387/jobs/8868215699 .
- Update GraalVM Native Build Tools to 0.9.22.
- Disable some unit tests when using GraalVM Native Build Tools. Because the copy execution of org.apache.shardingsphere:shardingsphere-infra-expr-espresso is later than the life cycle of executing unit tests.
---

Fix build-proxy-native-image job on Nightly Build

---

src/resources/checkstyle.xml
src/resources/spotless/java.xml

Synchronize the configuration of Checkstyle and Spotless regarding the line breaks in annotation parameters.
---

Synchronize the configuration of Checkstyle and Spotless

---

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/BinaryOperationExpressionConverter.java
test/it/optimizer/src/test/java/org/apache/shardingsphere/test/it/optimize/SQLNodeConverterEngineIT.java

support for EXPR with IS & Is not

---

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/DMLStatement.g4
parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java
parser/sql/dialect/postgresql/src/main/antlr4/imports/postgresql/DMLStatement.g4
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java

Fixes #25669.
- Optimize the definition and parsing of limit clause for PG/OG.
https://www.postgresql.org/docs/15/sql-select.html#SQL-LIMIT
https://docs.opengauss.org/zh/docs/5.0.0/docs/SQLReference/SELECT.html
---
- [-] I have made corresponding changes to the documentation.
- [-] I have added corresponding unit tests for my changes.

Optimize the definition and parsing of limit clause for PG/OG.

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/Literals.g4
test/it/parser/src/main/resources/case/dcl/drop-user.xml
test/it/parser/src/main/resources/sql/supported/dcl/drop-user.xml

Fixes #25535 .
- MySQL Oracle DROP USER statement for SQL parsing based on IP address deletion
---
- [✓] I have self-reviewed the commit code.
- [✓] I have added corresponding unit tests for my changes.

Support MySQL Oracle DROP USER statement for SQL parsing based on IP address deletion.

---

kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/check/datasource/MySQLDataSourceChecker.java
kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/check/datasource/MySQLDataSourceCheckerTest.java

- Query required variables in one SQL for MySQLDataSourceChecker
---

Query required variables in one SQL for MySQLDataSourceChecker

---

kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/connection/dialect/H2XAConnectionWrapper.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/connection/dialect/MariaDBXAConnectionWrapper.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/connection/dialect/MySQLXAConnectionWrapper.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/connection/dialect/OpenGaussXAConnectionWrapper.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/connection/dialect/OracleXAConnectionWrapper.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/connection/dialect/PostgreSQLXAConnectionWrapper.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/datasource/XATransactionDataSource.java

- Fix sonar volatile problem in `XAConnectionWrapper`
-  Initialize`XAConnectionWrapper` when `XATransactionDataSource` is created
The sonar issue links of `XAConnectionWrapper` are as follows:
https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=BUG&id=apache_shardingsphere&open=AYePEAKUmlEb3_PqvlbB
https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=BUG&id=apache_shardingsphere&open=AYePEAK3mlEb3_Pqvlbc
https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=BUG&id=apache_shardingsphere&open=AYePEAKumlEb3_PqvlbW
https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=BUG&id=apache_shardingsphere&open=AYePEAKmmlEb3_PqvlbR …

Fix sonar volatile issue in `XAConnectionWrapper`

---

agent/plugins/core/pom.xml
agent/plugins/core/src/test/java/org/apache/shardingsphere/agent/plugin/core/recorder/MethodTimeRecorderTest.java
agent/plugins/metrics/core/pom.xml
agent/plugins/metrics/core/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/jdbc/AbstractExecuteLatencyHistogramAdviceTest.java
agent/plugins/metrics/core/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/proxy/ExecuteLatencyHistogramAdviceTest.java

- fix sleep usage in UT for sonarcloud rule : https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEBwAmlEb3_PqvliE
---

Refactor Thread.sleep usage in UT for Sonar rules

---

kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/datasource/XATransactionDataSource.java
kernel/transaction/type/xa/provider/bitronix/src/main/java/org/apache/shardingsphere/transaction/xa/bitronix/manager/BitronixRecoveryResource.java

- Fix sonar issue of BitronixRecoveryResource, XATransactionDataSource
https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEAM8mlEb3_Pqvlbt
https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&types=BUG&id=apache_shardingsphere&open=AYePEAJcmlEb3_Pqvla8
---

Fix sonar issue of BitronixRecoveryResource, XATransactionDataSource

---

RELEASE-NOTES.md

Fixes spell error in release notes .
The word 'data souce' in release notes is spelled error.Change 'data souce' to 'data source'

Fix spell error in release notes: souce to source

---

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/_index.en.md

The current documentation mentions:
>Load JDBC URL of config.yaml profile in absolute path
>
>`jdbc:shardingsphere:/path/to/config.yaml`
However, the [code](https://github.com/apache/shardingsphere/blob/955ea40a41f083529ce2b98cd239a16d984ffe4a/jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/AbsolutePathDriverURLProvider.java#L38-L43) is clear) tells a different story. It needs to be prefixed with `jdbc:shardingsphere:absolutepath:`
Hence, the change is:
>Load JDBC URL of config.yaml profile in absolute path
>
>`jdbc:shardingsphere:absolutepath:/path/to/config.yaml`
---

doc: Fix the documentation for configuring ShardingSphere with an absolute path

---

mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoader.java

Fixes #25784.
- Fix the JDBCRepositorySQL fails to load when using a Fat Jar. 
---

Fix the JDBCRepositorySQL fails to load when using a Fat Jar. (#25784)

---

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/BinaryOperationExpressionConverter.java

Ref #24200 
This PR adds support for following case IDs
1.select_where_with_bit_expr_with_mod
2.select_where_with_bit_expr_with_vertical_bar
3.select_where_with_expr_with_not_sign
(Below case IDs from previous PRs)
4.select_where_with_predicate_with_in_subquery
5.select_where_with_expr_with_not

Support for MOD, Vertical Bar

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DDLStatement.g4
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/ddl/column/alter/RenameColumnSegment.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/ddl/AlterTableStatement.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ddl/impl/AlterTableStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/definition/ExpectedRenameColumnDefinition.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ddl/AlterTableStatementTestCase.java
test/it/parser/src/main/resources/case/ddl/alter-table.xml
test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml

Fixes #25852.
- Support Mysql ALTER TABLE RENAME COLUMN statement
- Add test sql
---

Support Mysql ALTER TABLE RENAME COLUMN statement

---

kernel/data-pipeline/core/pom.xml
kernel/data-pipeline/dialect/opengauss/pom.xml
parser/distsql/engine/src/main/antlr4/imports/RALStatement.g4
parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java
parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/parser/statement/ral/queryable/ShowDistVariablesStatement.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesExecutor.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesExecutorTest.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/QueryableRALStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/queryable/ShowDistVariablesStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ral/ShowDistVariablesStatementTestCase.java
test/it/parser/src/main/resources/case/ral/queryable.xml
test/it/parser/src/main/resources/sql/supported/ral/queryable.xml

Fixes https://github.com/apache/shardingsphere/issues/25493
- Add like support for `SHOW DIST VARIABLES`
---

Add like support for `SHOW DIST VARIABLES`

---

kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLIncrementalDumper.java

- Remove push FinishedRecord at MySQL increment dumper
---

Remove push FinishedRecord at MySQL increment dumper

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/metadata/dialect/OracleSchemaMetaDataLoader.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/metadata/dialect/OracleSchemaMetaDataLoaderTest.java

Fixes #25945.
- Modify PRIMARY_KEY_META_DATA_SQL in OracleSchemaMetaDataLoader to avoid ORA-01006 exception
---

Modify PRIMARY_KEY_META_DATA_SQL in OracleSchemaMetaDataLoader to avoid ORA-01006 exception

---

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/ClasspathDriverURLProvider.java

Fixes #25948.
- Unify the use of classloader in ClasspathDriverURLProvider
---

Optimize the use of classloader in ClasspathDriverURLProvider

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DDLStatement.g4
test/it/parser/src/main/resources/case/ddl/create-tablespace.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-tablespace.xml

Refer #25535.
- Change create tablespace syntax
- Add test sql
---

Change create tablespace syntax

---

test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/AbstractMigrationE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java

- Improve consistency job finished check at pipeline E2E
- Use Awaitility replace Thread sleep at create table rule
---

Improve consistency job finished check at pipeline E2E

---

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/circuit-breaker/enable-disable-compute-node.cn.md

The word ‘proy’ in ‘enable-disable-compute-node.cn.md’ is wrong.It is shoud be 'proxy'.so changed it .

Fix typo in enable-disable-compute-node.cn.md

---

mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/JDBCRepository.java

- Remove redundant code in JDBCRepository#persist
https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS4165&id=apache_shardingsphere&open=AYePEEOimlEb3_Pqvluq
The reproduction process has been verified without problems.
```java
@Override
public void persist(final String key, final String value) {
try {
if (isExisted(key)) {
update(key, value);
return;
}
String tempPrefix = "";
String parent = SEPARATOR;
// key = /a/b/c
// paths = ["a", "b", "c"]
String[] paths = Arrays.stream(key.split(SEPARATOR)).filter(each -> !Strings.isNullOrEmpty(each)).toArray(String[]::new);
// Create key level directory recursively.
for (int i = 0; i < paths.length - 1; i++) {
// i = 0, tempKey = "" + "/" + "a" = "/a"
// i = 1, tempKey = "/a" + "/" + "b" = "/a/b" …
```

Remove redundant code in JDBCRepository#persist

---

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/simple/ParameterMarkerExpressionSegment.java
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #26050.
- Fix oracle parse when projection contains parameter
---

Fix oracle parse when projection contains parameter

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml

Support oracle parser extract function
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/EXTRACT-datetime.html#GUID-36E52BF8-945D-437D-9A3C-6860CABD210E
-
---

Support oracle parser extract function

---

kernel/global-clock/type/tso/provider/redis/src/main/java/org/apache/shardingsphere/globalclock/type/tso/provider/RedisTSOPropertyKey.java

- Change redis default password is null at redis TSO, because empty string doesn't mean no password
---

Change redis default password is null at redis TSO

---

features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/metadata/converter/ReadwriteSplittingNodeConverter.java
features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/metadata/converter/ReadwriteSplittingNodeConverterTest.java
features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/NewYamlReadwriteSplittingRuleConfigurationSwapperTest.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/converter/ShardingNodeConverter.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapperTest.java

For #25485.
- Refactor metadata converter, remove redundant separator
- Update related test cases
---

Remove redundant separator in metadata converter

---

docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.en.md
features/encrypt/distsql/parser/src/main/java/org/apache/shardingsphere/encrypt/distsql/parser/core/EncryptDistSQLStatementVisitor.java
jdbc/core/pom.xml
proxy/backend/core/pom.xml
report/pom.xml
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/distsql/rdl/EncryptColumnAssert.java

- Remove useless shardingsphere-sql-federation-executor-original dependency
---

Remove useless shardingsphere-sql-federation-executor-original dependency

---

docs/document/content/user-manual/shardingsphere-proxy/migration/usage.cn.md
docs/document/content/user-manual/shardingsphere-proxy/migration/usage.en.md
kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/util/DataRecordResultConvertUtils.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/prepare/MigrationJobPreparer.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/RulesMigrationE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/MariaDBMigrationE2EIT.java

- Auto refresh table metadata at migration 
---

Auto refresh table metadata at migration 

---

.asf.yaml

- Add wbcfwbe to collaborators
---

Add wbcfwbe to collaborators

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptAlgorithmMetaData.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptAlgorithmMetaDataTest.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/SubqueryProjection.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementContextTest.java
infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/SubstitutableColumnNameTokenTest.java
test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-sub-query.xml

Fixes #26011.
- Support decrypt shorthand projection which expand from subquery column projection
- add encrypt integration test case
---

Support decrypt shorthand projection which expand from subquery column projection

---

kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/prepare/MigrationJobPreparer.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/RulesMigrationE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/MariaDBMigrationE2EIT.java

- Move refreshTableMetadata to migration job COMMIT
---

Move `refreshTableMetadata`to migration job COMMIT

---

kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/job/CDCJob.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/context/PipelineProcessContext.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/context/AbstractInventoryIncrementalProcessContext.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ExecuteEngine.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractSimplePipelineJob.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineLazyInitializer.java
kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/context/ConsistencyCheckJobItemContext.java
kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/context/ConsistencyCheckProcessContext.java
kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/task/ConsistencyCheckTasksRunner.java

Fixes #26195.
- Fix execute engine not closed after job stopping. Support migration job / consistency check job / CDC job / other sub-jobs of AbstractSimplePipelineJob.
Verified:
- Start a migration job, show threads; Stop job, show threads; And then start job again, show threads;
- On migration job completed, show threads;
- On migration job stopped or completed, related consistency check threads were reclaimed;
---

Fix execute engine not closed after job stopping

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/NotExpressionConverter.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/SQLExtensionOperatorTable.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
parser/sql/dialect/sql92/src/main/java/org/apache/shardingsphere/sql/parser/sql92/visitor/statement/SQL92StatementVisitor.java
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/NotExpression.java
test/it/optimizer/src/test/resources/converter/select-expression.xml

Enhancement of the PR #25865 .
Ref #24200 
---Test case addition for :
1.select_where_with_bit_expr_with_mod
2.select_where_with_bit_expr_with_vertical_bar
3.select_where_with_expr_with_not_sign
4.select_where_with_predicate_with_in_subquery
5.select_where_with_expr_with_not
---Enhanced NotConverter & visitor Files for Not Sign (!) 

test case addition & NotConverter enhancements

---

distribution/proxy-native/src/main/release-docs/LICENSE
distribution/proxy/src/main/release-docs/LICENSE
kernel/transaction/type/xa/provider/atomikos/pom.xml
test/e2e/operation/transaction/pom.xml

For #26041.
- Update Atomikos to 6.0.0 on javax classifier.
---

Update Atomikos to 6.0.0 on javax classifier

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/insert/values/InsertSelectContext.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDALStatementVisitor.java
parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java
parser/sql/dialect/sql92/src/main/java/org/apache/shardingsphere/sql/parser/sql92/visitor/statement/type/SQL92DMLStatementVisitor.java
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/AbstractSQLStatement.java

Ref #26210.
- Add uniqueParameterIndexes in AbstractSQLStatement to replace stream api
---

Add uniqueParameterIndexes in AbstractSQLStatement to replace stream api

---

features/encrypt/core/pom.xml
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/EncryptRuleConfigurationEventBuilder.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/config/AddEncryptConfigurationEvent.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/config/AlterEncryptConfigurationEvent.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/config/DeleteEncryptConfigurationEvent.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/encryptor/AddEncryptorEvent.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/encryptor/AlterEncryptorEvent.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/encryptor/DeleteEncryptorEvent.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptConfigurationSubscriber.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptorSubscriber.java
features/encrypt/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.rule.RuleConfigurationSubscribeCoordinator
features/encrypt/core/src/main/resources/META-INF/services/org.apache.shardingsphere.mode.event.config.RuleConfigurationEventBuilder

Add feature configuration changed event and subscribe at encrypt module

---

jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/adapter/PreparedStatementAdapterTest.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/adapter/StatementAdapterTest.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedOperationPreparedStatementTest.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedOperationStatementTest.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/SQLFederationExecutor.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/TranslatableTableScanExecutor.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/resultset/SQLFederationResultSet.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/resultset/SQLFederationResultSetMetaData.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLFederationCompiler.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/OptimizerContextFactory.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/planner/OptimizerPlannerContext.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/planner/OptimizerPlannerContextFactory.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/schema/SQLFederationDatabase.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/schema/SQLFederationSchema.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/schema/SQLFederationTable.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/rule/SQLFederationRule.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/rule/builder/SQLFederationRuleBuilder.java
kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/decider/engine/SQLFederationDecideEngineTest.java
kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/context/OptimizerContextTest.java
kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/it/SQLFederationCompilerIT.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/PreviewExecutor.java
test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/SQLRewriterIT.java

Ref #26011.
- Move optimizer context init logic to SQLFederationRule
---

Move optimizer context init logic to SQLFederationRule

---

infra/common/src/main/java/org/apache/shardingsphere/infra/rule/identifier/type/MetaDataHeldRule.java
infra/common/src/main/java/org/apache/shardingsphere/infra/rule/identifier/type/MutableDataNodeRule.java
kernel/single/core/src/main/java/org/apache/shardingsphere/single/decider/SingleSQLFederationDecider.java
kernel/single/core/src/main/java/org/apache/shardingsphere/single/route/engine/SingleStandardRouteEngine.java
kernel/single/core/src/main/java/org/apache/shardingsphere/single/rule/SingleRule.java
kernel/single/core/src/test/java/org/apache/shardingsphere/single/decider/SingleSQLFederationDeciderTest.java
kernel/single/core/src/test/java/org/apache/shardingsphere/single/route/engine/SingleStandardRouteEngineTest.java
kernel/single/core/src/test/java/org/apache/shardingsphere/single/rule/SingleRuleTest.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLFederationCompiler.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/OptimizerContext.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/rule/SQLFederationRule.java
mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
mode/core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java
mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneModeContextManager.java

Ref #26011.
- add MetaDataHeldRule for SQLFederationRule to refresh plannerContext when metadata change
---

Add MetaDataHeldRule for SQLFederationRule to refresh plannerContext when metadata change

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/BinaryOperationExpressionConverter.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/SQLExtensionOperatorTable.java
test/it/optimizer/src/test/resources/converter/select-expression.xml

Ref #24200
Support for Operators :- XOR, LOGICAL AND, SOUNDS LIKE, NOT REGEXP & NULL SAFE 
1.select_where_with_expr_with_xor 
2.select_where_with_predicate_with_regexp 
3.select_where_with_predicate_with_sounds_like 
4.select_where_with_expr_with_and_sign 
5.select_where_with_boolean_primary_with_null_safe

Support for MySQL operators

---

test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/RulesMigrationE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/MariaDBMigrationE2EIT.java

- Replace proxy data source to ShardingSphereDataSource to query, avoid "REFRESH TABLE METADATA" in process
---

Replace proxy data source to ShardingSphereDataSource to query, avoid "REFRESH TABLE METADATA" in process

---

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/AbstractExecutionPrepareEngine.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/ExecutionPrepareEngine.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/DatabaseConnectionManager.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/DriverExecutionPrepareEngine.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/raw/RawExecutionPrepareEngine.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManager.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManagerTest.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnectionTest.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/datasource/ShardingSphereDataSourceTest.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxyDatabaseConnectionManager.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/ProxyDatabaseConnectionManagerTest.java
proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandlerTest.java
proxy/frontend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/command/query/extended/bind/OpenGaussComBatchBindExecutorTest.java
proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutor.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLAggregatedBatchedStatementsCommandExecutorTest.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutorTest.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutorTest.java

Ref #26360.
- add connectionOffset in DatabaseConnectionManager interface for avoid stream api exception since use cache connection
- add unit test for DatabaseConnectionManager
---

Add connectionOffset in DatabaseConnectionManager interface for avoid stream api exception since use cache connection

---

infra/context/pom.xml
infra/context/src/main/java/org/apache/shardingsphere/infra/connection/refresher/type/table/CreateTableStatementSchemaRefresher.java
infra/context/src/main/java/org/apache/shardingsphere/infra/connection/refresher/type/table/DropTableStatementSchemaRefresher.java
infra/context/src/main/java/org/apache/shardingsphere/infra/connection/refresher/util/TableRefreshUtils.java
kernel/single/api/src/main/java/org/apache/shardingsphere/single/api/constant/SingleTableConstants.java
kernel/single/core/src/main/java/org/apache/shardingsphere/single/datanode/SingleTableDataNodeLoader.java
kernel/single/core/src/main/java/org/apache/shardingsphere/single/util/SingleTableLoadUtils.java
kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableStatementUpdater.java
kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/UnloadSingleTableStatementUpdater.java

For #26334
- Do not call `alterRuleConfiguration` when refresh is not required

Optimize performance of single table ddl refresher

---

kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/util/ColumnValueConvertUtils.java
kernel/data-pipeline/cdc/core/src/test/java/org/apache/shardingsphere/data/pipeline/cdc/util/ColumnValueConvertUtilsTest.java

- Fix java.sql.time convert failed when there are negative values
---

Fix java.sql.time convert failed when there are negative values

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select-combine.xml
test/it/parser/src/main/resources/sql/supported/dml/select-combine.xml

Fixes #26321.
- Support select except sql parse
- Add test sql
---
- [✓ ] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.

Enhance MySQL select statements

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/TableScanExecutorContext.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerablePushDownTableScanExecutor.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/row/SQLFederationRowEnumerator.java

Fixes #26360.
- Support sql federation stream query when not contains pipeline breaker
---

Support sql federation stream query when not contains pipeline breaker

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_am.yaml
infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_amop.yaml
infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_amproc.yaml
infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_attrdef.yaml
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_postgresql_pg_catalog_pg_am.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_postgresql_pg_catalog_pg_amop.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_postgresql_pg_catalog_pg_amproc.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_postgresql_pg_catalog_pg_attrdef.xml
test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema.xml

For #26143.
-add pg_am/pg_amop/pg_ampro/pg_attrdef table in pg_catalog for PostgreSQL
-add test cases
-pg_aggregate was finished in #25752 
---

Support PostgreSQL pg_catalog.pg_am/pg_amop/pg_ampro/pg_attrdef table empty query

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_range.yaml
infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_replication_origin.yaml
infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_rewrite.yaml
infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_seclabel.yaml
infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_sequence.yaml
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_postgresql_pg_catalog_pg_range.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_postgresql_pg_catalog_pg_replication_origin.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_postgresql_pg_catalog_pg_rewrite.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_postgresql_pg_catalog_pg_seclabel.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_postgresql_pg_catalog_pg_sequence.xml
test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema.xml

For #26150.
-add  pg_range, pg_replication_origin, pg_rewrite, pg_seclabel, pg_sequence table in pg_catalog for PostgreSQL
-add test cases
---

Support PostgreSQL pg_catalog.pg_range table empty query

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactory.java

Solve the error of java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "databaseName" is null
when executing sql like : SHOW VARIABLES LIKE 'lower_case_%'
-
---

fix proxy java.lang.NullPointerException

---

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/framework/param/array/E2ETestParameterGenerator.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/framework/param/array/JdbcStandaloneTestParameterGenerator.java
test/e2e/sql/src/test/resources/env/scenario/tbl/proxy/conf/mysql/config-tbl.yaml
test/e2e/sql/src/test/resources/env/scenario/tbl/rules.yaml

- Fix the issue where JdbcStandaloneTestParameterGenerator always uses H2 as the database type.
- Fix e2e failure caused by sqlCommentParseEnabled not being enabled.
- Fix the problem of getAssertionTestParameter not filtering by env adapter.
---

Fix the issue with e2e.

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java

- Replace globalRuleMetaData.getSingleRule(SQLFederationRule.class) with sqlFederationRule
---

Replace globalRuleMetaData.getSingleRule(SQLFederationRule.class) with sqlFederationRule

---

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDALStatementVisitor.java
test/it/parser/src/main/resources/case/dal/cache-index.xml
test/it/parser/src/main/resources/sql/supported/dal/cache-index.xml

Refer #25535.
- cache index t1,t2 in default;
- Add test sql
---

Support cache index default parse

---

proxy/bootstrap/src/main/java/org/apache/shardingsphere/proxy/arguments/BootstrapArguments.java

Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1075&id=apache_shardingsphere&open=AYePECdUmlEb3_Pqvlm5

Make Proxy default config path configurable

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ddl/ExecuteStatementTestCase.java
test/it/parser/src/main/resources/case/ddl/execute.xml
test/it/parser/src/main/resources/sql/supported/ddl/execute.xml

Refer #25535.
- EXECUTE ps1 USING @expected, @db, @table
- Add table rule in identifierKeywordsUnambiguous
---
- [  ✓] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [  ✓] I have self-reviewed the commit code.
- [  ✓] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [  ✓] I have added corresponding unit tests for my changes.

Add table rule in identifierKeywordsUnambiguous

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/metadata/schema/SQLFederationSchema.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerablePushDownTableScanExecutor.java

Fixes #26659.
- Table names in SQLFederationSchema are adjusted to lowercase
---

Table names in SQLFederationSchema are adjusted to lowercase

---

kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/rule/GlobalClockRule.java

- Fix creating transaction hook when global clock is not enabled
---

Fix creating transaction hook when global clock is not enabled

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/listener/ShardingSphereStatisticsScheduleCollector.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/context/parser/OptimizerParserContextFactory.java

- Remove useless timezone properties in OptimizerParserContextFactory
---

Remove useless timezone properties in OptimizerParserContextFactory

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/registrycenter/repository/GovernanceRepositoryAPI.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/registrycenter/repository/GovernanceRepositoryAPIImpl.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/persist/PipelineJobProgressPersistService.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/service/PipelineJobAPI.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/service/impl/AbstractInventoryIncrementalJobAPIImpl.java
kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/impl/CDCJobAPI.java
kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/impl/ConsistencyCheckJobAPI.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/job/service/GovernanceRepositoryAPIImplTest.java

- Use `PersistRepository.update` to update pipeline job item progress, but not `PersistRepository.persist`, to avoid node persistence when parent node doesn't exist in special case
- Clean code
---

Use PersistRepository.update to update pipeline job item progress

---

pom.xml

`maven-release-plugin` will modify pom.xml of projects. Spotless indentSchemaLocation sortPom will break the schema line.

Disable indentSchemaLocation of spotless

---

.github/workflows/required-check.yml

Spotless check can fail the PR with unformatted code.
```
The following files had format violations:
src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
@@ -83,7 +83,7 @@
·*/
@Getter
@Slf4j
-public·final·class·ContextManager·implements·AutoCloseable·{····
+public·final·class·ContextManager·implements·AutoCloseable·{
····
····private·final·AtomicReference<MetaDataContexts>·metaDataContexts;
····
Run 'mvn spotless:apply' to fix these violations.
```

Add spotless:check to avoid unformatted code in PR

---

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/nodepath/item/UniqueRuleItemNodePathTest.java

Fixes #26598.
Changes proposed in this pull request:Add test cases for UniqueRuleItemNodePath
-
Please add label "in:test" for this PR. I don't have access to add label.
---

Add test cases for UniqueRuleItemNodePath

---

features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/metadata/nodepath/BroadcastRuleNodePathProviderTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/metadata/nodepath/CompatibleEncryptRuleNodePathProviderTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/metadata/nodepath/EncryptRuleNodePathProviderTest.java
features/mask/core/src/test/java/org/apache/shardingsphere/mask/metadata/nodepath/MaskRuleNodePathProviderTest.java
features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/metadata/nodepath/ReadwriteSplittingRuleNodePathProviderTest.java
features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/metadata/nodepath/ShadowRuleNodePathProviderTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/metadata/nodepath/ShardingRuleNodePathProviderTest.java
kernel/single/core/src/test/java/org/apache/shardingsphere/single/metadata/nodepath/SingleRuleNodePathProviderTest.java

Fixes #26709.
Changes proposed in this pull request:Add unit test for RuleNodePathProvider 's implements
-
Please add label "in:test" for this PR. I don't have access to add label.
---

Add unit test for RuleNodePathProvider 's implements

---

mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/JDBCRepository.java

- Update `JDBCRepository.init`, replace `DROP TABLE` to `TRUNCATE TABLE`. To avoid possible `org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "repository" not found (this database is empty); SQL statement:
SELECT value FROM repository WHERE key = ? [42104-214]` error, if several `ShardingSphereDataSource` use default mode.
---

Improve Standalone mode JDBC type impl reset data on initialization

---

jdbc/core/src/main/java/org/apache/shardingsphere/driver/data/pipeline/datasource/creator/ShardingSpherePipelineDataSourceCreator.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/util/PipelineContextUtils.java

- Use Standalone mode JDBC type in ShardingSpherePipelineDataSourceCreator.createPipelineDataSource, and use different H2 database name in memory to isolate ShardingSphereDataSource Standalone repository
---

Isolate ShardingSphereDataSource Standalone repository in pipeline

---

jdbc/core/src/main/java/org/apache/shardingsphere/driver/data/pipeline/datasource/creator/ShardingSpherePipelineDataSourceCreator.java
test/it/pipeline/src/test/resources/config_sharding_sphere_jdbc_source.yaml
test/it/pipeline/src/test/resources/config_sharding_sphere_jdbc_target.yaml
test/it/pipeline/src/test/resources/migration_sharding_sphere_jdbc_target.yaml

- Disable system-schema-metadata-enabled in ShardingSpherePipelineDataSourceCreator. Else consistency check might be very slow.
- Disable system-schema-metadata-enabled in yaml config
---

Disable system-schema-metadata-enabled in pipeline

---

agent/plugins/tracing/core/src/main/java/org/apache/shardingsphere/agent/plugin/tracing/core/advice/TracingJDBCExecutorCallbackAdvice.java
agent/plugins/tracing/type/opentelemetry/src/test/java/org/apache/shardingsphere/agent/plugin/tracing/opentelemetry/advice/OpenTelemetryJDBCExecutorCallbackAdviceTest.java
agent/plugins/tracing/type/opentelemetry/src/test/java/org/apache/shardingsphere/agent/plugin/tracing/opentelemetry/fixture/JDBCExecutorCallbackFixture.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/resource/ShardingSphereResourceMetaData.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/driver/jdbc/JDBCExecutorCallback.java
infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/jdbc/JDBCExecutorCallbackTest.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/batch/BatchPreparedStatementExecutor.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/callback/ExecuteQueryCallback.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/callback/impl/PreparedStatementExecuteQueryCallback.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/callback/impl/StatementExecuteQueryCallback.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/StatementManager.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/executor/ProxyJDBCExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/executor/callback/ProxyJDBCExecutorCallback.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/executor/callback/ProxyJDBCExecutorCallbackFactory.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/executor/callback/impl/ProxyPreparedStatementExecutorCallback.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/executor/callback/impl/ProxyStatementExecutorCallback.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/PreviewExecutor.java
proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussSystemCatalogAdminQueryExecutor.java
proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java
proxy/frontend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/command/query/extended/bind/OpenGaussComBatchBindExecutorTest.java
proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutor.java

- Replace CACHED_DATASOURCE_METADATA in JDBCExecutorCallback with ShardingSphereResourceMetaData
---

Replace CACHED_DATASOURCE_METADATA in JDBCExecutorCallback with ShardingSphereResourceMetaData

---

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/metadata/JDBCQueryResultMetaData.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/executor/callback/ProxyJDBCExecutorCallback.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/executor/callback/impl/ProxyStatementExecutorCallback.java

- Handle SQLFeatureNotSupportedException when some db not implement jdbc interface
---

Handle SQLFeatureNotSupportedException when some db not implement jdbc interface

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

- Fix mysql groups and rank keywords
```sql
-- supported
select t1.groups,t1.rank from t1;
-- not supported
select groups,rank from t1;
-- supported
select `groups`,`rank` from t1;
```
---

Fix mysql groups and rank keywords

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
test/it/parser/src/main/resources/case/dml/insert.xml
test/it/parser/src/main/resources/sql/supported/dml/insert.xml

Fixes #26858.
- Fix Oracle CONNECT BY, PRIOR was not properly parsed
---

Fix Oracle CONNECT BY, PRIOR was not properly parsed(#26858)

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java
parser/sql/engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/ddl/DropContextStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleDropContextStatement.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ddl/DropContextStatementTestCase.java
test/it/parser/src/main/resources/case/ddl/drop-context.xml
test/it/parser/src/main/resources/sql/supported/ddl/drop-context.xml

Ref #27133.
- support parsing Oracle drop context.
---

Support parsing Oracle drop context.

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/sqlbuilder/PipelineImportSQLBuilder.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/common/sqlbuilder/PipelineImportSQLBuilderTest.java

- Fix pipeline buildUpdateSQL cache. Add unit test
---

Fix pipeline buildUpdateSQL cache

---

docs/community/content/involved/conduct/code.cn.md
docs/community/content/involved/conduct/code.en.md

- refactor the max parall to 20 in code of conduc
---

Refactor : refactor the max parall to 20 in code of conduct

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

- Support oracle format function parsing
Refer: https://docs.oracle.com/database/apex-5.1/AEAPI/FORMAT-Function.htm
---

Support oracle format function parsing

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

- Support oracle LAST_VALUE function parsing
Refer to: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/LAST_VALUE.html#GUID-A646AF95-C8E9-4A67-87BA-87B11AEE7B79
---

Support oracle LAST_VALUE function parsing

---

docs/community/content/involved/release/shardingsphere.cn.md
docs/community/content/involved/release/shardingsphere.en.md

- fix the mvn usage in release document
---

refactor the mvn usage in release document

---

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/AlterStorageUnitBackendHandler.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/RegisterStorageUnitBackendHandler.java

During the execution of `ModeContextManager#registerStorageUnits`, two exceptions are known to occur:
1. SQLWrapperException
2. ServiceProviderNotFoundServerException

Update exception type for register/alter storage unit.

---

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/_index.en.md

The English manual had Capitalized A-Z twice. I changed one to lowercase values a-z as I assume that was the intent.
I believe many of the following check list is not applicable, because this is a simple documentation change and not a code change.

[Documentation] Altered English Rules for Identifier

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DCLStatement.g4

Ref #27133.
- DropUser is already supported, but the grammar is not correct in g4. So this issue refactors the grammar.
---

Support drop user statement.

---

kernel/single/core/src/main/java/org/apache/shardingsphere/single/datanode/SingleTableDataNodeLoader.java

Fixes #27290, 
Support filter loading when there are single tables with the same name

Support filter loading when there are single tables with the same name

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/enums/AggregationType.java
test/it/parser/src/main/resources/case/dml/select-special-function.xml

- Support mysql GROUP_CONCAT function parsing
---

Support mysql GROUP_CONCAT function parsing

---

distribution/agent/pom.xml
distribution/jdbc/pom.xml
distribution/proxy/pom.xml
distribution/src/pom.xml
pom.xml

- set skip javadoc and checkstyle as default
---

Refactor : set skip javadoc and checkstyle as default

---

.github/workflows/nightly-check.yml

- leavel a message when set the issue/pr as stale
---

Refactor : leavel a message when set the issue/pr as stale

---

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/rule/BroadcastRule.java
features/mask/core/src/main/java/org/apache/shardingsphere/mask/rule/MaskRule.java
kernel/single/core/src/main/java/org/apache/shardingsphere/single/rule/SingleRule.java

- Adjust TableContainedRule implement in BroadcastRule and MaskRule to avoid invalid logic
---

Adjust TableContainedRule implement in BroadcastRule and MaskRule to avoid invalid logic

---

features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleStatementUpdater.java
features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdater.java
features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleStatementUpdaterTest.java
features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdaterTest.java

- Add check for conflict column name with logic column in encrypt rule definition
---

Add check for conflict column name with logic column in encrypt rule definition

---

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml

- Fix mysql extract from column parse error
---

Fix mysql extract from column parse error

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
test/it/parser/src/main/resources/case/dml/insert.xml

- Support oracle interval literals parsing
Refer to: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Literals.html#GUID-DC8D1DAD-7D04-45EA-9546-82810CD09A1B
---

Support oracle interval literals parsing

---

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/DockerStorageContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/EmbeddedStorageContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/StorageContainerFactory.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/config/StorageContainerConfiguration.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/config/impl/StorageContainerConfigurationFactory.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/config/impl/h2/H2ContainerConfigurationFactory.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/config/impl/mysql/MySQLContainerConfigurationFactory.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/config/impl/opengauss/OpenGaussContainerConfigurationFactory.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/config/impl/postgresql/PostgreSQLContainerConfigurationFactory.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/H2Container.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/MySQLContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/OpenGaussContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/PostgreSQLContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/runtime/scenario/database/DatabaseEnvironmentManager.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/createtable/CreateTableSQLGeneratorIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/container/compose/DockerContainerComposer.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/util/DockerImageVersion.java
test/e2e/operation/showprocesslist/src/test/java/org/apache/shardingsphere/test/e2e/showprocesslist/container/composer/ClusterShowProcessListContainerComposer.java
test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/framework/container/compose/DockerContainerComposer.java
test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/framework/container/config/StorageContainerConfigurationFactory.java
test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/framework/container/config/mysql/MySQLContainerConfigurationFactory.java
test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/framework/container/config/opengauss/OpenGaussContainerConfigurationFactory.java
test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/framework/container/config/postgresql/PostgreSQLContainerConfigurationFactory.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/container/compose/mode/ClusterContainerComposer.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/container/compose/mode/StandaloneContainerComposer.java

- Move the DB init SQL script from DockerStorageContainer to StorageContainerConfiguration. 
---

Move the DB init SQL script from DockerStorageContainer to StorageContainerConfiguration.

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4
test/it/parser/src/main/resources/case/dml/select-into.xml
test/it/parser/src/main/resources/sql/supported/dml/select-into.xml
test/it/parser/src/main/resources/sql/unsupported/unsupported.xml

- Support oracle select into clause parsing
Refer to: https://docs.oracle.com/en/database/oracle/oracle-database/21/lnpls/SELECT-INTO-statement.html#GUID-6E14E04D-4344-45F3-BE80-979DD26C7A90
---

Support oracle select into clause parsing

---

test/it/optimizer/src/test/resources/converter/select-expression.xml

Fixes #26871 .
- Finish task6: select_where_with_predicate_with_in_subquery
- dbtypes: PostgreSQL, openGauss
---

Enhance SQLNodeConverterEngine to support ''select_where_with_predicate_with_in_subquery

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/simple/ColumnWithJoinOperatorSegment.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/columnWithJoinOperator/ColumnWithJoinOperatorAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedColumnWithJoinOperatorSegment.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedExpression.java
test/it/parser/src/main/resources/case/dml/select-join.xml
test/it/parser/src/main/resources/sql/supported/dml/select-join.xml

- add Oracle Join Operator Parse
ref:  https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/Joins.html#GUID-29A4584C-0741-4E6A-A89B-DCFAA222994A
---

add Oracle Join Operator SQL Parse

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
test/it/parser/src/main/resources/case/ddl/create-table.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml

Fixes #27325.
- Support create table DEC parse
- Add test sql
---

Support create table DEC parse

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngine.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/item/AggregationDistinctProjectionSegment.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/projection/ProjectionAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/projection/impl/aggregation/ExpectedAggregationDistinctProjection.java
test/it/parser/src/main/resources/case/dml/select.xml

Ref #27287.
- Rename distinctExpression to distinctInnerExpression to keep same with AggregationDistinctProjection
- rename projection sql parse assert
---

Rename distinctExpression to distinctInnerExpression to keep same with AggregationDistinctProjection

---

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/ShardingDQLResultMergerTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByMemoryMergedResultTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByStreamMergedResultTest.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationDistinctProjection.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationProjection.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngineTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationProjectionTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementContextTest.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/projection/impl/AggregationProjectionConverter.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java
parser/sql/dialect/sql92/src/main/java/org/apache/shardingsphere/sql/parser/sql92/visitor/statement/SQL92StatementVisitor.java
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/item/AggregationDistinctProjectionSegment.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/item/AggregationProjectionSegment.java
parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractorTest.java
parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtilsTest.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/projection/ProjectionAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/projection/impl/aggregation/ExpectedAggregationProjection.java
test/it/parser/src/main/resources/case/dml/delete.xml
test/it/parser/src/main/resources/case/dml/select-aggregate.xml
test/it/parser/src/main/resources/case/dml/select-group-by.xml
test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/case/dml/select-sub-query.xml
test/it/parser/src/main/resources/case/dml/select-with.xml
test/it/parser/src/main/resources/case/dml/select.xml

Ref #27287.
- Modify innerExpression to expression in AggregationProjectionSegment to support MySQL column label
---

Modify innerExpression to expression in AggregationProjectionSegment to support MySQL column label

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

- Support oracle CONNECT_BY_ROOT clause parsing
---

Support oracle CONNECT_BY_ROOT clause parsing

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

- Support oracle keep clause parsing
Refer to: 
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/FIRST.html#GUID-85AB9246-0E0A-44A1-A7E6-4E57502E9238
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/LAST.html#GUID-4E16BC0E-D3B8-4BA4-8F97-3A08891A85CC
---

Support oracle keep clause parsing

---

.asf.yaml

- Add Mouqiuyu to collaborators and remove wbcfwbe
---

Add Mouqiuyu to collaborators and remove wbcfwbe

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

- Support oracle RATIO_TO_REPORT function parsing
Refer to:
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/RATIO_TO_REPORT.html#GUID-9D10C275-4341-435F-ACF4-767B9CCB7390
---

Support oracle RATIO_TO_REPORT function parsing

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

- Support oracle SYS_XMLAGG/SYS_XMLGEN functions parsing
Refer to:
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/SYS_XMLAGG.html#GUID-BEDD241D-360A-46A2-AEBF-C8B70E465D75
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6
---

Support oracle SYS_XMLAGG/SYS_XMLGEN functions parsing

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/IntervalDayToSecondExpression.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/IntervalYearToMonthExpression.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/item/IntervalExpressionProjection.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedExpression.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedIntervalDayToSecondExpression.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedIntervalExpression.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedIntervalYearToMonthExpression.java
test/it/parser/src/main/resources/case/dml/select-expression.xml
test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml

- Support Oracle Interval Expression
ref: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Interval-Expressions.html#GUID-EB9B5B5D-357B-494C-A237-153A2CF8425C
---

Support Oracle Interval Expression

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
test/it/parser/src/main/resources/case/ddl/alter-diskgroup.xml
test/it/parser/src/main/resources/case/ddl/alter-flashback-archive.xml
test/it/parser/src/main/resources/sql/supported/ddl/alter-diskgroup.xml
test/it/parser/src/main/resources/sql/supported/ddl/alter-flashback-archive.xml

Fixes #26962 #26963.
- Enhance Oracle qualifiedTemplateClause and alterFlashbackArchive syntax
- Add test sql
---

Enhance Oracle qualifiedTemplateClause and alterFlashbackArchive syntax

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/TableSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/ProjectionsSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ShorthandProjectionSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ShorthandProjectionSegmentBinderTest.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/table/JoinTableSegment.java

Ref #27287.
- Implement shorthand expand when contains join tables
- add more unit test for JoinTableSegmentBinder and ShorthandProjectionSegmentBinder
---

Implement shorthand expand when contains join tables

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4

- Revise oracle parse rule for pr 27451
---

Revise oracle parse rule for pr 27451

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/engine/ProjectionEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/engine/ProjectionsContextEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/engine/ProjectionEngineTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/engine/ProjectionsContextEngineTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinderTest.java
proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/NoResourceShowExecutor.java
test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-subquery.xml

Ref #27287.
- Remove useless projection logic in ProjectionContext and use bounded sql statement
- add unit test for JoinTableSegmentBinder
---

Remove useless projection logic in ProjectionContext and use bounded sql statement

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
test/it/parser/src/main/resources/case/ddl/create-table.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml

Fixes: #27268
- Support oracle negative data type parsing
Refer to:
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Data-Types.html#GUID-10D4D073-866D-4BD4-B3E9-ED153D505A6A
---

Support oracle negative data type parsing

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinderTest.java

Fixes #27287.
- Create new projection with subquery table alias when shorthand expand
---

Create new projection with subquery table alias when shorthand expand

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinderTest.java

Ref #27287.
- Fix shorthand expand wrong column name when subquery projection contains alias
---

Fix shorthand expand wrong column name when subquery projection contains alias

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/constant/EncryptColumnDataType.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptAlterTableTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptCreateTableTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptColumnToken.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptAlterTableTokenGeneratorTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptCreateTableTokenGeneratorTest.java
test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/ddl/alter/alter-table.xml
test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/ddl/create/create-table.xml
test/it/rewriter/src/test/resources/scenario/mix/case/query-with-cipher/ddl/create/create-table.xml

Fixes #27587
- Add default data type `VARCHAR(4000)` for encrypt columns.
- In MySQL, the maximum length of varchar is variable, determined by the character set (greater than 10000)
- https://dev.mysql.com/doc/refman/8.0/en/char.html 
- In PG, the maximum length of varchar is 10485760
- https://www.postgresql.org/docs/15/datatype-character.html
- In Oracle, varchar has a maximum length of 4000 (VARCHAR data type is currently synonymous with VARCHAR2)
- https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/Data-Types.html#GUID-7B72E154-677A-4342-A1EA-C74C1EA928E6
- MySQL
- PG
- Oracle
---

Add default data type `VARCHAR(4000)` for encrypt columns.

---

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select-sub-query.xml
test/it/parser/src/main/resources/sql/supported/dml/select-sub-query.xml

The following SQL can not be parsed because createCompareSegment deals with Subquery wrongly.
```SELECT * FROM employees WHERE salary = ANY (SELECT salary FROM employees WHERE department_id = 30) ORDER BY employee_id;```
I referred to the createCompareSegment method of MySQLStatementVisitor and fixed the createCompareSegment of OracleStatementVisitor.

[Oracle SQL] Support HR-7-1 of Oracle SQL

---

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/AdapterContainerFactory.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/impl/ShardingSphereJdbcContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/runtime/scenario/path/ScenarioCommonPath.java

Ref https://github.com/apache/shardingsphere/issues/27287.
- Refactor e2e jdbc rule config load logic to support database special config
---

Refactor e2e jdbc rule config load logic to support database special config

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptMergedResult.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/ProjectionsContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/engine/ProjectionEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/ColumnProjection.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/SQLBindEngine.java
proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java

Ref https://github.com/apache/shardingsphere/issues/27287.
- Fix e2e test when case contains dataSourceName sql hint
- rename originalOwner and originalName in ColumnProjection
---

Fix e2e test when case contains dataSourceName sql hint

---

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowTableMetaDataExecutor.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/QueryableRALBackendHandlerTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowTableMetaDataExecutorTest.java

Optimize ShowTableMetaDataExecutor, avoid databaseName being null

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/SQLBindEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/SubquerySegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/ddl/CursorStatementBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/InsertStatementBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/statement/SQLStatementContextFactoryTest.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/InsertStatementHandler.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutorTest.java

Ref https://github.com/apache/shardingsphere/issues/27287.
- Fix cursor e2e test exception caused by select statement context projection logic change
---

Fix cursor e2e test exception caused by select statement context projection logic change

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinderTest.java

Ref #27287.
- Fix wrong shorthand expand size when contains more than two tables join
---

Fix wrong shorthand expand size when contains more than two tables join

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/resource/ShardingSphereResourceMetaData.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/resource/ShardingSphereStorageNodeMetaData.java
mode/core/src/main/java/org/apache/shardingsphere/mode/manager/switcher/ResourceSwitchManager.java

Fixes #27888.
- Fix SwitchingResource in compatible cluster mode.
- Remove useless storageTypes in ShardingSphereStorageNodeMetaData
---
```sql
mysql> REGISTER STORAGE UNIT ds_0 (
->     HOST="127.0.0.1",
->     PORT=3306,
->     DB="demo_ds_0",
->     USER="root",
->     PASSWORD="123456",
->     PROPERTIES("maximumPoolSize"=10)
-> );
Query OK, 0 rows affected (0.48 sec)
mysql> EXPORT DATABASE CONFIGURATION;
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
| result                                                                                                                                                     | …
```

Fix SwitchingResource in compatible cluster mode.

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml

In this pr, I supported the parsing of set function for Oracle reffering to: https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/SET.html#GUID-533164AC-B4F0-4FCE-ADA4-85C925CB8D14
Now this SQL can be parsed:
``` SELECT customer_id, SET(cust_address_ntab) address FROM customers_demo ORDER BY customer_id; ```
Relate issue: https://github.com/apache/shardingsphere/issues/27569

[Oracle SQL] Support parsing set function for Oracle SQL

---

infra/datasource/core/src/main/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesCreator.java
infra/datasource/core/src/test/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesCreatorTest.java

Fixes #27927.
- handling correctly when parsing non-numeric values
---

Fix NumberFormatException when loadng persisted datasource pool config

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java

- Modify EncryptProjectionTokenGenerator projection logic when column set derived alias
---

Modify EncryptProjectionTokenGenerator projection logic when column set derived alias

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/ColumnProjection.java
test/e2e/sql/src/test/resources/env/scenario/encrypt/data/actual/init-sql/h2/01-actual-init.sql
test/e2e/sql/src/test/resources/env/scenario/encrypt/data/actual/init-sql/opengauss/01-actual-init.sql
test/e2e/sql/src/test/resources/env/scenario/encrypt/data/actual/init-sql/postgresql/01-actual-init.sql
test/e2e/sql/src/test/resources/env/scenario/encrypt/data/expected/init-sql/h2/01-expected-init.sql
test/e2e/sql/src/test/resources/env/scenario/encrypt/data/expected/init-sql/opengauss/01-expected-init.sql
test/e2e/sql/src/test/resources/env/scenario/encrypt/data/expected/init-sql/postgresql/01-expected-init.sql

Ref #27287.
- Fix encrypt e2e error and add init table for H2, PostgreSQL and openGauss
---

Fix encrypt e2e error and add init table for H2, PostgreSQL and openGauss

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select-expression.xml
test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml

- Support Oracle cursor function parse
ref: https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/CURSOR-Expressions.html#GUID-B28362BE-8831-4687-89CF-9F77DB3698D2
---

Support Oracle cursor function parse

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/condition/EncryptConditionEngine.java

- Revise code style for EncryptConditionEngine
---

Revise code style for EncryptConditionEngine

---

test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedExpression.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedMultisetExpression.java
test/it/parser/src/main/resources/case/dml/select-expression.xml

- Add oracle column parsing assertions of multiset expression
---

Add oracle column parsing assertions of multiset expression

---

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/definition/ColumnDefinitionAssert.java
test/it/parser/src/main/resources/case/ddl/alter-table.xml
test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml

Ref #26978.
- Fix oracle alter table column definition parse error
- Fix column definition assert NullPointerException
- The datatype of the Oracle alter table modify column statement column can be omitted
Refer to:
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/img/modify_col_properties.gif
Test statement execution results:
SQL> CREATE TABLE mytable (id NUMBER, name varchar(30), age NUMBER);
Table created.
SQL> ALTER TABLE mytable MODIFY (name);
Table altered.
---
- [ ✓] I …

Fix oracle alter table column definition parse error

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java
test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-sub-query.xml
test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-subquery.xml

Ref #28016.
- Fix exception caused by missing like query column in table subquery
- add integration test case and sql rewrite test case
---

Fix exception caused by missing like query column in table subquery

---

.github/workflows/e2e-sql.yml

- Refactor : remove openGauss from sql-e2e workflow
---

Refactor : remove openGauss from sql-e2e workflow

---

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select-expression.xml

- Fix wrong parse result with mysql great than operator
---

Fix wrong parse result with mysql great than operator

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/ExpressionSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/NotExpressionBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/util/ProjectionUtilsTest.java
parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtils.java

- Fix oracle parse wrong result when sql statement contains ANY subquery
---

Fix oracle parse wrong result when sql statement contains ANY subquery

---

test/e2e/sql/src/test/resources/env/scenario/encrypt/data/actual/dataset.xml
test/e2e/sql/src/test/resources/env/scenario/encrypt/data/expected/dataset.xml

- Add t_order and t_order_item init data sql for e2e encrypt scenario
---

Add t_order and t_order_item init data sql for e2e encrypt scenario

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/PipelineDataConsistencyChecker.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/TableDataConsistencyCheckerFactory.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/service/InventoryIncrementalJobAPI.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/service/impl/AbstractInventoryIncrementalJobAPIImpl.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/TableDataConsistencyCheckerFactoryTest.java
kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/impl/CDCJobAPI.java
kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/task/ConsistencyCheckTasksRunner.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/check/consistency/MigrationDataConsistencyChecker.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/migration/api/impl/MigrationJobAPITest.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/migration/check/consistency/MigrationDataConsistencyCheckerTest.java

Related to #27992 .
- Create new TableDataConsistencyChecker for every table data consistency check. Make sure new TableDataConsistencyChecker SPI impl could be isolated between tables' consistency check.
---

Create new TableDataConsistencyChecker for every table data consistency check

---

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/wait/JdbcConnectionWaitStrategy.java
test/e2e/operation/pipeline/src/test/resources/env/scenario/primary_key/text_primary_key/mysql.xml
test/e2e/operation/pipeline/src/test/resources/env/scenario/primary_key/text_primary_key/postgresql.xml

- Use Awaitility replace Unreliables
- Remove unused code
---

Use Awaitility replace Unreliables at E2E

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/dumper/ColumnValueReaderEngine.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/service/impl/AbstractInventoryIncrementalJobAPIImpl.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/consistencycheck/table/calculator/RecordSingleTableInventoryCalculatorTest.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/dump/ColumnValueReaderEngineTest.java

Refer https://www.logicbig.com/tutorials/core-java-tutorial/java-language/ternary-numeric-rules.html
- Fix number type implicit conversion at ColumnValueReaderEngine
---

Fix number type implicit conversion at ColumnValueReaderEngine

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java
test/it/parser/src/main/resources/case/ddl/alter-table.xml
test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml

Fixes #26980.
- Support oracle modifyTableDefaultAttrs and setSubpartitionTemplate syntax
- Add test sql
---

Support oracle modifyTableDefaultAttrs and setSubpartitionTemplate syntax

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/job/progress/ConsistencyCheckJobItemProgress.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/job/progress/yaml/YamlConsistencyCheckJobItemProgress.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/job/progress/yaml/YamlConsistencyCheckJobItemProgressSwapper.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/ConsistencyCheckJobItemProgressContext.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/MatchingTableDataConsistencyChecker.java
kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/impl/ConsistencyCheckJobAPI.java
kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/context/ConsistencyCheckJobItemContext.java
kernel/data-pipeline/scenario/consistencycheck/src/test/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/context/ConsistencyCheckJobItemContextTest.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobTest.java

- Isolate consistency check tableCheckPositions for source and target
---

Isolate consistency check tableCheckPositions for source and target

---

db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/protocol/MySQLDateBinaryProtocolValue.java
db-protocol/mysql/src/test/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/protocol/MySQLDateBinaryProtocolValueTest.java

- Fix MySQL 8.0.20 driver returns LocalDateTime type cast exception
---

Fix LocalDateTime type cast exception after MySQL 8.0.23 driver

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java

Ref https://github.com/apache/shardingsphere/issues/28016.
- adjust column segment binder logic
---

adjust column segment binder logic

---

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/Process.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/ProcessEngine.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/yaml/YamlProcess.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/yaml/swapper/YamlProcessSwapper.java
infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/process/yaml/swapper/YamlProcessListSwapperTest.java
infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/process/yaml/swapper/YamlProcessSwapperTest.java
mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/subscriber/ProcessListChangedSubscriberTest.java
proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowProcessListExecutorTest.java

Fixes #28069.
- Add heldByConnection to avoid MySQL JDBC memory leak
---

Add heldByConnection to avoid MySQL JDBC memory leak

---

distribution/proxy-native/pom.xml
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md

For #21347.
- Disable the implementation of Etcd during the build of ShardingSphere Proxy Native. Refer to https://github.com/apache/shardingsphere/issues/21347#issuecomment-1685514896.
- In #28099, the introduction of `io.grpc:grpc-netty-shaded:1.51.0` lacks the corresponding GraalVM Reachability Metadata, but GraalVM Team does not finish discussing whether GraalVM Reachability Metadata should be collected for shaded packages. As a temporary measure, related submodules are disabled during the build of Native Image. Refer to https://github.com/micronaut-projects/micronaut-gcp/issues/532 .
---

Disable the implementation of Etcd during the build of ShardingSphere Proxy Native

---

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/statistics/builder/PostgreSQLShardingSphereStatisticsBuilderTest.java

- Refactor PostgreSQLShardingSphereStatisticsBuilderTest logic
---

Refactor PostgreSQLShardingSphereStatisticsBuilderTest logic

---

distribution/proxy-native/pom.xml

For #21347.
- Fixes `OutOfMemoryError` unique to building GraalVM Native Image on Github Actions devices. Refer to https://github.com/apache/shardingsphere/actions/runs/5928664616/job/16074760055 .
- Discussions about this CI are located in https://github.com/oracle/graal/issues/7214 .
---

Fixes `OutOfMemoryError` unique to building GraalVM Native Image on Github Actions devices

---

db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/protocol/MySQLBinaryProtocolValueFactory.java
db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/protocol/MySQLByteLenencBinaryProtocolValue.java
db-protocol/mysql/src/test/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/protocol/MySQLBinaryProtocolValueFactoryTest.java
db-protocol/mysql/src/test/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/protocol/MySQLByteLenencBinaryProtocolValueTest.java

Fix raw bytes corrupted when decoding FIELD_TYPE_STRING in MySQL protocol

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinderTest.java

- Fix sql binder exception when tables join without owner
---

Fix sql binder exception when tables join without owner

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/enums/SegmentType.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/lock/LockSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementBinder.java

- Add sql binder logic for lock column segment
---

Add sql binder logic for lock column segment

---

test/e2e/agent/plugins/logging/file/pom.xml
test/e2e/agent/plugins/metrics/prometheus/pom.xml
test/e2e/agent/plugins/tracing/jaeger/pom.xml
test/e2e/agent/plugins/tracing/zipkin/pom.xml

Fixes #28254.
- Change group id to com.mysql of mysql 8.0.31 in agent
---

Change group id to com.mysql of mysql 8.0.31 in agent

---

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/DCLStatement.g4
test/it/parser/src/main/resources/case/dcl/drop-user.xml
test/it/parser/src/main/resources/sql/supported/dcl/drop-user.xml

Fixes #27640.
- Add support for parsing `DROP USER` with `CASCADE` and `RESTRICT`
- Add tests
---

Support parsing openGauss DROP USER sql

---

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4
parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/OpenGaussKeyword.g4
test/it/parser/src/main/resources/case/dml/select-expression.xml
test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml

Fixes #27739.
- Support OpenGauss number manipulation functions parse
ref: https://docs.opengauss.org/zh/docs/3.1.1-lite/docs/Developerguide/%E6%95%B0%E5%AD%97%E6%93%8D%E4%BD%9C%E5%87%BD%E6%95%B0%E5%92%8C%E6%93%8D%E4%BD%9C%E7%AC%A6.html
---

Support OpenGauss number manipulation functions parse

---

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4
parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/Symbol.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml
test/it/parser/src/main/resources/sql/unsupported/unsupported.xml

Fixes #27738.
- Support OpenGauss number numeric operators parse
ref: https://docs.opengauss.org/zh/docs/3.1.1-lite/docs/Developerguide/%E6%95%B0%E5%AD%97%E6%93%8D%E4%BD%9C%E5%87%BD%E6%95%B0%E5%92%8C%E6%93%8D%E4%BD%9C%E7%AC%A6.html
---

Support OpenGauss number numeric operators parse

---

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4
parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/OpenGaussKeyword.g4
test/it/parser/src/main/resources/case/dml/select-expression.xml
test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
test/it/parser/src/main/resources/sql/unsupported/unsupported.xml

Fixes #27779.
- Support OpenGauss elem_contained_by_range function parse
ref: https://docs.opengauss.org/en/docs/3.1.0/docs/Developerguide/range-functions-and-operators.html
---

Support OpenGauss elem_contained_by_range function parse

---

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select-expression.xml
test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
test/it/parser/src/main/resources/sql/unsupported/unsupported.xml

Fixes #27777.
- Support OpenGauss int8range function parse
---

Support OpenGauss int8range function parse

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/ddl/column/ColumnDefinitionSegment.java
test/it/parser/src/main/resources/case/ddl/create-table.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml

In this PR, I fixed the follwing SQL:
`CREATE TABLE location_table (location_number NUMBER, building REF warehouse_typ SCOPE IS warehouse_table);`
REF column is allowd in ColumnDefinitionClause of Oracle, the references are listed here:
https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/CREATE-TABLE.html#GUID-F9CE0CC3-13AE-4744-A43C-EAC7A71AAAB6
https://docs.oracle.com/en/database/oracle/oracle-database/21/adobj/design-considerations-for-REFs.html#GUID-078BD058-FE2C-4FC5-8418-CD95F085CBD6
The related issue: https://github.com/apache/shardingsphere/issues/27569

[Oracle SQL] Support REF column in create table clause

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/XmlElementFunctionSegment.java

The related issues is: https://github.com/apache/shardingsphere/issues/27569
In this pr, I supported the parsing of basic components of XMLElement and XMLCdata Function of Oracle.
Now, the HR-5-204 & HR-5-208 can be parsed correcly.
The Example SQL is :
`SELECT XMLELEMENT("PurchaseOrder", XMLAttributes(dummy as "pono"), XMLCdata('<!DOCTYPE po_dom_group [ <!ELEMENT po_dom_group(student_name)*> <!ELEMENT po_purch_name (#PCDATA)> <!ATTLIST po_name po_no ID #REQUIRED> <!ATTLIST po_name trust_1 IDREF #IMPLIED> <!ATTLIST po_name trust_2 IDREF #IMPLIED>]>')) "XMLCData" FROM DUAL;`
I refered to the offical doc of Oracle:
https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/XMLELEMENT.html#GUID-DEA75423-00EA-4034-A246-4A774ADC988E …

[Oracle SQL] Support parsing of XMLElement and XMLCdata Function

---

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select-expression.xml
test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
test/it/parser/src/main/resources/sql/unsupported/unsupported.xml

Fixes #27775.
- Support OpenGauss int4range function parse
---

Support OpenGauss int4range function parse

---

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4
parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/OpenGaussKeyword.g4
test/it/parser/src/main/resources/case/dml/select-expression.xml
test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
test/it/parser/src/main/resources/sql/unsupported/unsupported.xml

Fixes #27778.
- Support OpenGauss lower_inf upper_inf function parse
ref: https://docs.opengauss.org/en/docs/3.1.0/docs/Developerguide/range-functions-and-operators.html
---

Support OpenGauss lower_inf upper_inf function parse

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/EncryptTokenGenerateBuilder.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertDefaultColumnsTokenGenerator.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertDefaultColumnsTokenGeneratorTest.java

Ref #ISSUSE_ID.
- Rename EncryptForUseDefaultInsertColumnsTokenGenerator to EncryptInsertDefaultColumnsTokenGenerator and move package to insert
---

Rename EncryptForUseDefaultInsertColumnsTokenGenerator to EncryptInsertDefaultColumnsTokenGenerator and move package to insert

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/metadata/schema/SQLFederationTable.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSetMetaData.java

- Fix npe when execute mysql system table query with sql federation
---

Fix npe when execute mysql system table query with sql federation

---

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select-expression.xml
test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
test/it/parser/src/main/resources/sql/unsupported/unsupported.xml

Fixes #27670.
- Support OpenGauss tsquery type parse
---

Support OpenGauss tsquery type parse

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/execute/ExecuteEngine.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/AbstractSingleTableInventoryCalculator.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/PipelineJobProgressDetector.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/persist/PipelineJobProgressPersistService.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/runner/InventoryIncrementalTasksRunner.java
kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/CheckMigrationJobUpdater.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java
test/e2e/operation/pipeline/src/test/resources/env/common/migration-command.xml

If consistency check is started before inventory stage done, then consistency check should fail, it's not necessary to do it, so forbid it to avoid starting it by mistake.
- Verify inventory finished before starting consistency check
- Persist inventory progress after inventory done. Make sure when user find job status reaches EXECUTE_INCREMENTAL_TASK, consistency check could be started
---

Verify inventory finished before starting consistency check

---

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4
parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/OpenGaussKeyword.g4
test/it/parser/src/main/resources/case/dml/select-expression.xml
test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml

Fixes #27664.
- Support OpenGauss abbrev(inet) Function parse
- Support OpenGauss abbrev(cidr) Function parse
- Support OpenGauss set_masklen(cidr, int) Function parse
- Support OpenGauss text(inet) Function parse
- Support OpenGauss trunc(macaddr) Function parse
ref: https://docs.opengauss.org/en/docs/latest/docs/SQLReference/network-address-functions-and-operators.html
---

Support OpenGauss Network Address Functions parse

---

kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/prepare/CDCJobPreparer.java

- Fix CDC importer not start when first task is finished
---

Fix CDC importer not start when first inventory task is finished

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/SQLBindEngine.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactory.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/PreviewExecutor.java
proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java
proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutorTest.java
proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutor.java
proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutor.java
proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/parse/PostgreSQLComParseExecutor.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/parse/PostgreSQLComParseExecutorTest.java

- https://github.com/apache/shardingsphere/actions/runs/6170120809/job/16746047253
- fix e2e exception caused by sql binder when sql statement sql hint extract by sql util
---

fix e2e exception caused by sql binder when sql statement sql hint extract by sql util

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/pojo/DataConsistencyCheckAlgorithmInfo.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/service/impl/AbstractInventoryIncrementalJobAPIImpl.java
kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckAlgorithmsExecutor.java
kernel/data-pipeline/distsql/handler/src/test/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckAlgorithmsExecutorTest.java

- Add "type_aliases" column in "show migration check algorithms" DistSQL result
---

Improve "show migration check algorithms"

---

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java

- Format OracleStatementParser import class
---

Format OracleStatementParser import class

---

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/DDLStatement.g4
parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/OpenGaussKeyword.g4
test/it/parser/src/main/resources/case/dcl/grant.xml
test/it/parser/src/main/resources/case/dcl/revoke.xml
test/it/parser/src/main/resources/sql/supported/dcl/grant-user.xml
test/it/parser/src/main/resources/sql/supported/dcl/revoke-user.xml

Refs #27639.
- Add openGauss SQL support for `GRANT` and `REVOKE` for `COLUMN_ENCRYPTION_KEY`
- Add openGauss SQL support for `REVOKE` for `CLIENT_MASTER_KEY`
---

Add support for GRANT, REVOKE openGauss

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertDefaultColumnsTokenGenerator.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/insert/keygen/engine/GeneratedKeyContextEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/InsertStatementContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/InsertStatementBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/statement/dml/InsertStatementContextTest.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/context/SQLRewriteContext.java
infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/engine/RouteSQLRewriteEngineTest.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/BaseDMLE2EIT.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/InsertStatementAssert.java
test/it/parser/src/main/resources/case/dml/insert.xml
test/it/parser/src/main/resources/case/dml/replace.xml

- Refactor BaseDMLE2EIT and insert select statement parse logic
---

Refactor BaseDMLE2EIT and insert select statement parse logic

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertValuesTokenGenerator.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDALStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java
test/it/parser/src/main/resources/case/dml/insert.xml
test/it/parser/src/main/resources/case/dml/select-pagination.xml
test/it/parser/src/main/resources/case/dml/select-sub-query.xml

- Minimal refactor of oracle dml statement parameter parse
---

Minimal refactor of oracle dml statement parameter parse

---

features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleStatementUpdater.java
features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdater.java

In the process of reading the code, some optimizations were made for the isColumnNameNotConflicts method.
Use stream streaming to replace multiple ifs.

Made some optimizations for the isColumnNameNotConflicts method

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/execute/ExecuteEngine.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/runner/InventoryIncrementalTasksRunner.java

- Run completion callback in dedicated thread pool
- Skip incremental task on job stopping
---

Improve pipeline thread pool task submitting

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/registrycenter/repository/GovernanceRepositoryAPI.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/registrycenter/repository/GovernanceRepositoryAPIImpl.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/service/PipelineJobAPI.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/service/impl/AbstractPipelineJobAPIImpl.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/runner/InventoryIncrementalTasksRunner.java
kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/job/CDCJob.java
kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/task/ConsistencyCheckTasksRunner.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/task/InventoryTaskTest.java

- Use PersistRepository.update to update pipeline job item message. Make sure no error node will be created after job is dropped in special case
---

Improve pipeline job item error message persistance

---

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/data-source.en.md
docs/document/content/user-manual/shardingsphere-proxy/yaml-config/data-source.cn.md
docs/document/content/user-manual/shardingsphere-proxy/yaml-config/data-source.en.md

For #27608.
- Add document of data source for proxy

Add document of data source for proxy

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/MergeStatementBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/MergeStatementBinderTest.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/ExpressionWithParamsSegment.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/dml/MergeStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/UpdateStatementHandler.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/MergeStatementAssert.java
test/it/parser/src/main/resources/case/dml/merge.xml

Refactor merge statement.

---

.github/workflows/nightly-ci.yml
agent/core/pom.xml
agent/pom.xml
pom.xml

Fixes #28293 .
- Support for building with OpenJDK 21.
- Due to JEP 451, JDK21's CI has thousands more lines of warnings.  Reference https://github.com/mockito/mockito/issues/3037 .
- Since GraalVM Updater is deprecated in GraalVM CE 23.1.0 For JDK 21, the `shardingsphere-infra-expr-espresso` submodule will not be reusable, there are some temporary processing at https://github.com/apache/shardingsphere/pull/28340 .  Looking to the future, it is impossible for us to introduce the GPL LICENSE Espresso ontology into ShardingSphere. This module will be deleted or maintained by a third party in the foreseeable future.
- The javac in GraalVM CE 23.1.0 For JDK21 may has bugs. An error occurred when the ShardingSphere Proxy Native was migrated to GraalVM CE …

Support for building with OpenJDK 21

---

infra/data-source-pool/core/src/test/java/org/apache/shardingsphere/infra/datasource/pool/destroyer/DataSourcePoolDestroyerTest.java

Fixes #28550.
- remove DataSourcePoolDestroyerTest assertion
---
- [✓ ] I have self-reviewed the commit code.

Fix:DataSourcePoolDestroyerTest occasionally fails(#28550)

---

docs/community/content/involved/conduct/code.cn.md
docs/community/content/involved/conduct/code.en.md
docs/community/content/involved/contribute/contributor.cn.md
docs/community/content/involved/contribute/contributor.en.md
docs/document/content/user-manual/shardingsphere-proxy/startup/docker.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/docker.en.md
examples/README.md

- unify the mvn usage with ./mvnw in document
---

Document : unify the mvn usage with ./mvnw in document

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/with/WithConverter.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/statement/delete/DeleteStatementConverter.java
test/it/optimizer/src/test/java/org/apache/shardingsphere/test/it/optimizer/converter/SQLNodeConverterEngineIT.java
test/it/optimizer/src/test/resources/converter/delete.xml

Ref #28328 
- Support for SQLServer conversion
- Support for WithSegment and Test cases - 
-delete_with_with_clause
-delete_without_columns_with_with_clause

Support for WithSegment

---

docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.en.md

- Update wrong document link for shardingsphere plugin
---

Update wrong document link for shardingsphere plugin

---

distribution/proxy-native/pom.xml
docs/document/content/dev-manual/sharding.cn.md
docs/document/content/dev-manual/sharding.en.md
docs/document/content/user-manual/common-config/builtin-algorithm/expr.cn.md
docs/document/content/user-manual/common-config/builtin-algorithm/expr.en.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.en.md
docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.cn.md
docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.en.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
infra/expr/core/src/main/java/org/apache/shardingsphere/infra/expr/core/InlineExpressionParserFactory.java
infra/expr/type/espresso/pom.xml
infra/expr/type/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParser.java
infra/expr/type/espresso/src/test/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParserTest.java
pom.xml

Fixes #22899.
- Add documentation about the `infra-expr-espresso` module.
- This PR is detached from #28609. Related to https://github.com/oracle/graal/issues/7500 .
- Update the URL of the GraalVM documentation. Ref. https://github.com/quarkusio/quarkus/issues/34929 . 
- Rename `InlineExpressionParserFactory#removeTypeNameInExpr` to `InlineExpressionParserFactory#getExprWithoutTypeName`.
---

Add documentation about the `infra-expr-espresso` module

---

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaDataTest.java

Fixes #28564 .
Added Junit
---

 Junit for ShardingSphereMetaData (#28564)

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
test/it/parser/src/main/resources/case/ddl/alter-table.xml
test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml

Ref #26990.
- Add oracle alter table modifylobStorageClause parse rule
- Add test sql
---

Add oracle alter table modifylobStorageClause parse rule

---

features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/fixture/EncryptGeneratorFixtureBuilder.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/ShardingInsertStatementValidatorTest.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/SubquerySegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/engine/PaginationContextEngineTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/engine/ProjectionsContextEngineTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/statement/dml/InsertStatementContextTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContextTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ShorthandProjectionSegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/InsertStatementBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/MergeStatementBinderTest.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java
parser/sql/dialect/sql92/src/main/java/org/apache/shardingsphere/sql/parser/sql92/visitor/statement/SQL92StatementVisitor.java
parser/sql/dialect/sql92/src/main/java/org/apache/shardingsphere/sql/parser/sql92/visitor/statement/type/SQL92DMLStatementVisitor.java
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/subquery/SubquerySegment.java
parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtilsTest.java
parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/WhereExtractUtilsTest.java

add text for suquery segment

---

infra/common/src/main/java/org/apache/shardingsphere/infra/config/database/DatabaseConfiguration.java
infra/common/src/main/java/org/apache/shardingsphere/infra/config/database/impl/DataSourceGeneratedDatabaseConfiguration.java
infra/common/src/main/java/org/apache/shardingsphere/infra/config/database/impl/DataSourceProvidedDatabaseConfiguration.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/ShardingSphereDatabase.java
infra/common/src/test/java/org/apache/shardingsphere/infra/config/database/impl/DataSourceGeneratedDatabaseConfigurationTest.java
infra/common/src/test/java/org/apache/shardingsphere/infra/config/database/impl/DataSourceProvidedDatabaseConfigurationTest.java
kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/MetaDataPersistService.java
mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/MetaDataContextsFactory.java
mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/NewMetaDataContextsFactory.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/config/yaml/swapper/YamlProxyConfigurationSwapperTest.java

Use DatabaseConfiguration.getDataSources instead of getStorageResource

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/function/dialect/mysql/SQLExtensionOperatorTable.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/BinaryOperationExpressionConverter.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/CollateExpressionConverter.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/MatchExpressionConverter.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/NotExpressionConverter.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/UnaryOperationExpressionConverter.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/with/WithConverter.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/statement/delete/DeleteStatementConverter.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/statement/explain/ExplainStatementConverter.java

- Minor refactor for sql node convert logic
---

Minor refactor for sql node convert logic

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptTable.java
features/mask/core/src/main/java/org/apache/shardingsphere/mask/rule/MaskTable.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/ddl/ShardingDDLResultMerger.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/ShardingDQLResultMerger.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContext.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/datatype/DataTypeLoader.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSet.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/BinaryOperationExpressionConverter.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/UnaryOperationExpressionConverter.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/projection/impl/AggregationProjectionConverter.java
proxy/backend/type/hbase/src/main/java/org/apache/shardingsphere/proxy/backend/hbase/result/query/HBaseGetResultSet.java

replacing the TreeMap with CaseInsensitiveMap.(#28602)

---

.github/workflows/nightly-build.yml
README.md

Fixes #26521 
- Created a new Github Actions to automatically update the generated SVG based on Cronjob
---

Feature: add world map of contributors to shardingsphere project

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractSimplePipelineJob.java
kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/job/CDCJob.java

It is not enough to catch exceptions in the `doPrepare` method, other methods may also throw runtime exceptions
- Improve exception handle at AbstractPipelineJob
- Refactor processFailed
---

Improve exception handle at AbstractPipelineJob and refactor processFailed

---

kernel/data-pipeline/scenario/cdc/client/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/client/CDCClient.java

Avoiding changes in the order of CDC consumption
- Set CDC client nThreads of event loop group
---

Set CDC client nThreads of event loop group

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptTable.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/EncryptTableTest.java

- Fix encrypt e2e test case exception caused by EncryptRule#getLogicColumnByCipherColumn
---

Fix encrypt e2e test case exception caused by EncryptRule#getLogicColumnByCipherColumn

---

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/_index.en.md

Fixed spelling in three lines.
Changed "Confiugration" to "Configuration".
-
---

Fixed spelling for "Confiugration"

---

.github/workflows/ci.yml
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/operator/physical/EnumerableScan.java
kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/compiler/it/SQLStatementCompilerIT.java

Fix nightly e2e exception caused by line separator 

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/SQLNodeConverterEngine.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/statement/merge/MergeStatementConverter.java
test/it/optimizer/src/test/java/org/apache/shardingsphere/test/it/optimizer/converter/SQLNodeConverterEngineIT.java
test/it/optimizer/src/test/resources/converter/merge.xml

Ref #28754 
Added basic support. 

Basic support for MERGE queries

---

test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/job/service/GovernanceRepositoryAPIImplTest.java

Fixes #28544 .
- Adds unit test for persistJobOffsetInfo, getJobOffsetInfo methods
---

Add unit test in GovernanceRepositoryAPIImplTest
