- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/exception/UnsupportedDropCascadeTableException.java
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/route/validator/ddl/SingleTableDropTableValidator.java
> Add UnsupportedDropCascadeTableException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/exception/SchemaNotFoundException.java
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/route/validator/ddl/SingleTableDropSchemaMetadataValidator.java
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/test/java/org/apache/shardingsphere/singletable/route/validator/ddl/SingleTableDropSchemaMetadataValidatorTest.java
> Add SchemaNotFoundException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/exception/DropNotEmptySchemaException.java
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/route/validator/ddl/SingleTableDropSchemaMetadataValidator.java
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/test/java/org/apache/shardingsphere/singletable/route/validator/ddl/SingleTableDropSchemaMetadataValidatorTest.java
> Add DropNotEmptySchemaException

- shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-spring-infra/shardingsphere-jdbc-spring-boot-starter-infra/src/main/java/org/apache/shardingsphere/spring/boot/datasource/DataSourceMapSetter.java
- shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-spring-infra/shardingsphere-jdbc-spring-boot-starter-infra/src/main/java/org/apache/shardingsphere/spring/boot/exception/DataSourceJndiNotFoundException.java
- shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-spring-infra/shardingsphere-jdbc-spring-boot-starter-infra/src/main/java/org/apache/shardingsphere/spring/boot/exception/UnsupportedDataSourceTypeException.java
> Add DataSourceJndiNotFoundException and UnsupportedDataSourceTypeException

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-spring/shardingsphere-sharding-spring-namespace/src/main/java/org/apache/shardingsphere/sharding/spring/namespace/exception/UnsupportedShardingAlgorithmTypeException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-spring/shardingsphere-sharding-spring-namespace/src/main/java/org/apache/shardingsphere/sharding/spring/namespace/parser/strategy/ShardingStrategyBeanDefinitionParser.java
> Add UnsupportedShardingAlgorithmTypeException

- shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/database/DatabaseServerInfo.java
- shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/java/org/apache/shardingsphere/proxy/exception/DatabaseServerLoadingException.java
- shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/test/java/org/apache/shardingsphere/proxy/database/DatabaseServerInfoTest.java
> Add DatabaseServerLoadingException

- examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/spi-based-sharding-algorithm-example/spi-based-sharding-raw-jdbc-example/src/main/java/org/apache/shardingsphere/example/extension/spibased/sharding/raw/jdbc/SPIBasedShardingRawJavaConfigurationExample.java
- examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/spi-based-sharding-algorithm-example/spi-based-sharding-raw-jdbc-example/src/main/java/org/apache/shardingsphere/example/extension/spibased/sharding/raw/jdbc/SPIBasedShardingRawYamlConfigurationExample.java
- examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/spi-based-sharding-algorithm-example/spi-based-sharding-raw-jdbc-example/src/main/java/org/apache/shardingsphere/example/extension/spibased/sharding/raw/jdbc/config/SPIBasedShardingRawJavaConfiguration.java
- examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/spi-based-sharding-algorithm-example/spi-based-sharding-raw-jdbc-example/src/main/java/org/apache/shardingsphere/example/extension/spibased/sharding/raw/jdbc/factory/DataSourceFactory.java
Fixes #15717.
- Add raw java example for spi-based-sharding-algorithm-example
> Add raw java example for spi-based-sharding-algorithm-example

- shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/planner/QueryOptimizePlannerFactory.java
- shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/test/java/org/apache/shardingsphere/infra/federation/optimizer/ShardingSphereOptimizerTest.java
Ref #19937.
- modify filter rules
- modify the related unit test
> feat: modify filter optimization rules.

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdKeyGenerateAlgorithmTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdSnowflakeKeyGenerateAlgorithmTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/DateCosIdIntervalShardingAlgorithmTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/InstantCosIdIntervalShardingAlgorithmTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/LocalDateCosIdIntervalShardingAlgorithmTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/LocalDateTimeCosIdIntervalShardingAlgorithmTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/OffsetDateTimeCosIdIntervalShardingAlgorithmTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/SQLTimestampCosIdIntervalShardingAlgorithmTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/SqlDateCosIdIntervalShardingAlgorithmTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/StringCosIdIntervalShardingAlgorithmTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/TimestampCosIdIntervalShardingAlgorithmTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/YearMonthCosIdIntervalShardingAlgorithmTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/ZonedDateTimeCosIdIntervalShardingAlgorithmTest.java
> Revise code format for #20605

- docs/document/content/user-manual/error-code/_index.cn.md
- docs/document/content/user-manual/error-code/_index.en.md
- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
> Add draft description for error code document

- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/err/MySQLErrPacketFactory.java
> Refactor MySQLErrPacketFactory

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-dialect-exception/shardingsphere-dialect-exception-core/src/main/java/org/apache/shardingsphere/dialect/exception/connection/UnsupportedPreparedStatementException.java
- shardingsphere-dialect-exception/shardingsphere-mysql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/mysql/mapper/MySQLDialectExceptionMapper.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/sql/UnknownSQLException.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/exception/ExpectedExceptions.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/test/java/org/apache/shardingsphere/proxy/frontend/exception/ExpectedExceptionsTest.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/err/MySQLErrPacketFactory.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutorTest.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/err/MySQLErrPacketFactoryTest.java
> Refactor UnsupportedPreparedStatementException

- shardingsphere-dialect-exception/shardingsphere-dialect-exception-core/src/main/java/org/apache/shardingsphere/dialect/exception/connection/UnknownCharsetException.java
- shardingsphere-dialect-exception/shardingsphere-mysql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/mysql/mapper/MySQLDialectExceptionMapper.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/mysql/executor/MySQLSetCharsetExecutor.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/err/MySQLErrPacketFactory.java
> Add UnknownCharsetException

- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/DDLStatement.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/PostgreSQLStatementParser.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLDDLStatementSQLVisitor.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/postgresql/ddl/PostgreSQLAlterTypeStatement.java
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/alter-type.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml
Ref #17848 
- Proofread `ALTER TYPE` grammar
- Support Parsing `ALTER TYPE` in PostgreSQL
- Adds tests
> Support Parsing `ALTER TYPE` in PostgreSQL

- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/metadata/persist/service/config/database/DataSourcePersistService.java
- shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java
- shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/metadata/persist/service/config/database/DataSourcePersistServiceTest.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/DropResourceBackendHandler.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/AlterResourceBackendHandlerTest.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/DropResourceBackendHandlerTest.java
> Refactor ContextManager.dropResources()

- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/PostgreSQLStatementParser.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLDDLStatementSQLVisitor.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/postgresql/ddl/PostgreSQLCreatePublicationStatement.java
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/create-publication.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml
For #17844 
- Add [PostgreSQL Create Publication statement](https://www.postgresql.org/docs/current/sql-createpublication.html).
> Add PostgreSQL Create Publication Statement

- shardingsphere-dialect-exception/shardingsphere-dialect-exception-core/src/main/java/org/apache/shardingsphere/dialect/ExceptionTransformEngine.java
- shardingsphere-dialect-exception/shardingsphere-dialect-exception-core/src/main/java/org/apache/shardingsphere/dialect/SQLExceptionTransformEngine.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/err/MySQLErrPacketFactory.java
> Add SQLExceptionTransformEngine

- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/err/PostgreSQLErrPacketFactory.java
> Refactor PostgreSQLErrPacketFactory

- docs/document/content/dev-manual/mode.cn.md
- docs/document/content/user-manual/common-config/builtin-algorithm/metadata-repository.cn.md
- docs/document/content/user-manual/common-config/builtin-algorithm/metadata-repository.en.md
> Refactor metadata-repository document

- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/exception/InvalidAuthorizationSpecificationException.java
- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/mapper/PostgreSQLDialectExceptionMapper.java
- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/vendor/PostgreSQLServerErrorMessage.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/exception/ExpectedExceptions.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/test/java/org/apache/shardingsphere/proxy/frontend/exception/ExpectedExceptionsTest.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationEngine.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/err/OpenGaussErrorPacketFactory.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationEngineTest.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/PostgreSQLAuthenticationEngine.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/err/PostgreSQLErrPacketFactory.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/PostgreSQLAuthenticationEngineTest.java
> Refactor PostgreSQLDialectExceptionMapper

- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/sqlbuilder/OpenGaussPipelineSQLBuilder.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-opengauss/src/test/java/org/apache/shardingsphere/data/pipeline/opengauss/sqlbuilder/OpenGaussPipelineSQLBuilderTest.java
- Add openGauss ON DUPLICATE KEY UPDATE after insert sql
> Add openGauss conflict SQL builder

- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-standalone-mode/shardingsphere-standalone-mode-repository/shardingsphere-standalone-mode-repository-provider/shardingsphere-standalone-mode-repository-jdbc/shardingsphere-standalone-mode-repository-jdbc-h2/src/main/java/org/apache/shardingsphere/mode/repository/standalone/h2/H2JDBCRepositoryProvider.java
Fixes #20636.
- add  `IF NOT EXISTS `
> Improve H2JDBCRepositoryProvider.createTableSQL at high concurrency

- shardingsphere-dialect-exception/shardingsphere-dialect-exception-core/src/main/java/org/apache/shardingsphere/dialect/exception/SQLDialectException.java
- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/exception/InvalidAuthorizationSpecificationException.java
- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/exception/PostgreSQLProtocolViolationException.java
- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/mapper/PostgreSQLDialectExceptionMapper.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationEngine.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/err/OpenGaussErrorPacketFactory.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationEngineTest.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/PostgreSQLAuthenticationEngine.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/err/PostgreSQLErrPacketFactory.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/PostgreSQLAuthenticationEngineTest.java
> Refactor PostgreSQLProtocolViolationException

- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/exception/PostgreSQLAuthenticationException.java
- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/mapper/PostgreSQLDialectExceptionMapper.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationEngine.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/err/OpenGaussErrorPacketFactory.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationEngineTest.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/PostgreSQLAuthenticationEngine.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/err/PostgreSQLErrPacketFactory.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/PostgreSQLAuthenticationEngineTest.java
> Refactor PostgreSQLAuthenticationException

- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/test/java/org/apache/shardingsphere/dialect/postgresql/vendor/PostgreSQLServerErrorMessageTest.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-ha/src/test/java/org/apache/shardingsphere/test/integration/ha/framework/container/config/StorageContainerConfigurationFactory.java
> Add test case for PostgreSQLServerErrorMessageTest

- shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/util/ResultSetUtil.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSet.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSetTest.java
Fixes #20568.
- Fix bugs when variable type is OffsetDateTime
> offsetDateTime convert failed bug fix

- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/exception/InvalidAuthorizationSpecificationException.java
- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/mapper/PostgreSQLDialectExceptionMapper.java
> Add message to InvalidAuthorizationSpecificationException

- RELEASE-NOTES.md
> Update 5.2.0 release note

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting.cn.md
Modify sample parameter: change "read_weight"="2:1" into "write_ds=2,read_ds_0=2,read_ds_1=2,read_ds_2=1".
-
-
-
> Modify sample parameter

- shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/release-docs/LICENSE
> Update 5.2.0 license

- examples/pom.xml
> Update example version

- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/exception/InvalidPasswordException.java
- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/exception/PrivilegeNotGrantedException.java
- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/exception/UnknownUsernameException.java
- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/mapper/PostgreSQLDialectExceptionMapper.java
- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/vendor/PostgreSQLVendorError.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSetTest.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationEngine.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationHandler.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationEngineTest.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationHandlerTest.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/PostgreSQLAuthenticationEngine.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/PostgreSQLAuthenticationHandler.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/PostgreSQLAuthenticationEngineTest.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/PostgreSQLAuthenticationHandlerTest.java
> Use exception to instead of return logic in OpenGaussAuthenticationHandler and PostgreSQLAuthenticationHandler

- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/constant/DistSQLScriptConstants.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandler.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandlerTest.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/resources/conf/convert/config-readwrite-splitting.yaml
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/resources/expected/convert-readwrite-splitting.yaml
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/QueryableRALStatementAssert.java
Fixes #17939 
- Append generateDistSQL by feature SPI
- Add convert read-write-splitting distsql and test case
Need to do:
- Append Dynamic READ-WRITTING RULES by feature SPI
> Add convert read-write-splitting distsql and test case

- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
> Throws SQLException instead of wrapped exception in ShardingSphere-JDBC

- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSet.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSetUtil.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSetUtilTest.java
> Cache columnLabelAndIndexMap in ShardingSpherePreparedStatement

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/MigrateTableUpdater.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationDataConsistencyChecker.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/base/BaseExtraSQLITCase.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/base/BaseITCase.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/command/ExtraSQLCommand.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/command/MigrationDistSQLCommand.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/general/MySQLMigrationGeneralIT.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/general/PostgreSQLMigrationGeneralIT.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/primarykey/TextPrimaryKeyMigrationIT.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/task/MySQLIncrementTask.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/task/PostgreSQLIncrementTask.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/resources/env/common/command.xml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/resources/env/scenario/general/mysql.xml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/resources/env/scenario/general/postgresql.xml
- Support changing table name at migrating
- Remove unused DistSQL
> Support changing table name at migrating

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/checker/audit/ShardingAuditChecker.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/checker/ShardingAuditCheckerTest.java
> Reduce unused overhead in ShardingAuditChecker

- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/postgresql/exception/InvalidAuthorizationSpecificationException.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/constant/DistSQLScriptConstants.java
> Refactor InvalidAuthorizationSpecificationException

- shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/conf/config-sharding.yaml
- Remove useless scaling config
> Remove useless scaling config

- shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLCharacterSet.java
- shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/test/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLCharacterSetTest.java
- shardingsphere-dialect-exception/shardingsphere-mysql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/mysql/exception/UnknownCharsetException.java
- shardingsphere-dialect-exception/shardingsphere-mysql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/mysql/exception/UnknownCollationException.java
- shardingsphere-dialect-exception/shardingsphere-mysql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/mysql/exception/UnsupportedPreparedStatementException.java
- shardingsphere-dialect-exception/shardingsphere-mysql-dialect-exception/src/main/java/org/apache/shardingsphere/dialect/mysql/mapper/MySQLDialectExceptionMapper.java
- shardingsphere-dialect-exception/shardingsphere-mysql-dialect-exception/src/test/java/org/apache/shardingsphere/dialect/mysql/mapper/MySQLDialectExceptionMapperTest.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/mysql/executor/MySQLSetCharsetExecutor.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutorTest.java
> Refactor exception package of mysql-dialect-exception module

- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/engine/ddl/BaseDDLIT.java
- Optimize integration test of DDL in cluster mode
> Optimize integration test of DDL in cluster mode

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/sql/sqlstate/XOpenSQLState.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSetMetaData.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/ColumnIndexOutOfRangeException.java
> Add ColumnIndexOutOfRangeException

- docs/community/content/involved/release/shardingsphere.cn.md
- docs/community/content/involved/release/shardingsphere.en.md
- Update `svn add *` to `svn add * --parents` in release document
> Update `svn add *` to `svn add * --parents` in release document

- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/antlr4/imports/mysql/BaseRule.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/antlr4/imports/mysql/MySQLKeyword.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/dml/select-expression.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/dml/select-expression.xml
Fixes #20188.
- add json function support to mysql parser
- add json function visitor
-
> add json function support to mysql parser

- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-opengauss/src/main/antlr4/imports/opengauss/DDLStatement.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-opengauss/src/main/antlr4/imports/opengauss/Keyword.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-opengauss/src/main/antlr4/imports/opengauss/Literals.g4
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/create-tablespace.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/create-tablespace.xml
Fixes https://github.com/apache/shardingsphere/issues/20026
I am trying to add `max_size` option to `createtablespace` in openGause syntax. But I am not very familiar with antlr4. 
So this PR is still WIP. 
Is there any quick tutorial on antlr4 development in shardingsphere?  @RaigorJiang 
- try to add max_size to openGauss syntax
-
-
> add max_size to openGauss syntax

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/EmptySQLException.java
> Add EmptySQLException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/exception/InvalidMGRReplicationGroupMemberException.java
- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/type/MGRMySQLDatabaseDiscoveryProviderAlgorithm.java
> Add InvalidMGRReplicationGroupMemberException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/exception/EncryptAlgorithmInitializationException.java
- shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/exception/EncryptColumnAlterException.java
- shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/exception/EncryptLogicColumnNotFoundException.java
- shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/exception/UnsupportedEncryptInsertValueException.java
- shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/exception/UnsupportedEncryptSQLException.java
- shardingsphere-features/shardingsphere-shadow/shardingsphere-shadow-core/src/main/java/org/apache/shardingsphere/shadow/algorithm/shadow/UnsupportedShadowColumnTypeException.java
- shardingsphere-features/shardingsphere-shadow/shardingsphere-shadow-core/src/main/java/org/apache/shardingsphere/shadow/route/exception/UnsupportedShadowInsertValueException.java
> Update vendor code of encrypt and shadow

- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/SQLServerSchemaMetaDataLoader.java
- shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/SQLServerSchemaMetaDataLoaderTest.java
ref: #20681 .
- Support load SQLServer view metadata.
- add unit test.
> Support load SQLServer view metadata.

- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/commitrollback/BroadcastTableTransactionTestCase.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/base/BaseTransactionITCase.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/command/CommonSQLCommand.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/common/command.xml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/it-env.properties
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/jdbc/mysql/config-sharding-local.yaml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/jdbc/mysql/config-sharding-xa-atomikos.yaml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/jdbc/mysql/config-sharding-xa-bitronix.yaml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/jdbc/mysql/config-sharding-xa-narayana.yaml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/jdbc/opengauss/config-sharding-local.yaml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/jdbc/opengauss/config-sharding-xa-atomikos.yaml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/jdbc/opengauss/config-sharding-xa-bitronix.yaml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/jdbc/opengauss/config-sharding-xa-narayana.yaml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/jdbc/postgresql/config-sharding-local.yaml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/jdbc/postgresql/config-sharding-xa-atomikos.yaml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/jdbc/postgresql/config-sharding-xa-bitronix.yaml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/resources/env/jdbc/postgresql/config-sharding-xa-narayana.yaml
- Add broadcast table transaction test
> Add broadcast table transaction test

- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/constant/DistSQLScriptConstants.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandler.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandlerTest.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/resources/conf/convert/config-database-discovery.yaml
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/resources/expected/convert-database-discovery.yaml
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/QueryableRALStatementAssert.java
For #17939
- Add convert db-discovery yaml to distsql
- test case
> Add convert db-discovery distsql and test case

- .github/workflows/it.yml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/dml/dml-integration-test-cases.xml
- Fix shadow integration tests use PostgreSQL in cluster mode
> Fix shadow integration tests use PostgreSQL in cluster mode

- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/SQLServerSchemaMetaDataLoader.java
- shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/SQLServerSchemaMetaDataLoaderTest.java
- shardingsphere-kernel/shardingsphere-sql-federation/pom.xml
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-api/pom.xml
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-api/src/main/java/org/apache/shardingsphere/sqlfederation/api/config/SQLFederationRuleConfiguration.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-core/pom.xml
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-core/src/main/java/org/apache/shardingsphere/sqlfederation/constant/SQLFederationOrder.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-core/src/main/java/org/apache/shardingsphere/sqlfederation/rule/SQLFederationRule.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-core/src/main/java/org/apache/shardingsphere/sqlfederation/rule/builder/DefaultSQLFederationRuleConfigurationBuilder.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-core/src/main/java/org/apache/shardingsphere/sqlfederation/rule/builder/SQLFederationRuleBuilder.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.rule.builder.global.DefaultGlobalRuleConfigurationBuilder
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.rule.builder.global.GlobalRuleBuilder
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-provider/pom.xml
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-provider/shardingsphere-sql-federation-advanced-provider/pom.xml
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-provider/shardingsphere-sql-federation-original-provider/pom.xml
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/constant/DistSQLScriptConstants.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandler.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandlerTest.java
Ref #20710.
- add new shardingsphere-sql-federation moudle
- add SQLFederationRuleConfiguration related class
> Add shardingsphere-sql-federation moudle and SQLFederationRuleConfiguration related class

- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-standalone-mode/shardingsphere-standalone-mode-repository/shardingsphere-standalone-mode-repository-provider/shardingsphere-standalone-mode-repository-jdbc/shardingsphere-standalone-mode-repository-jdbc-core/src/test/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/JDBCRepositoryTest.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-standalone-mode/shardingsphere-standalone-mode-repository/shardingsphere-standalone-mode-repository-provider/shardingsphere-standalone-mode-repository-jdbc/shardingsphere-standalone-mode-repository-jdbc-core/src/test/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/fixture/JDBCRepositoryProviderFixture.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-standalone-mode/shardingsphere-standalone-mode-repository/shardingsphere-standalone-mode-repository-provider/shardingsphere-standalone-mode-repository-jdbc/shardingsphere-standalone-mode-repository-jdbc-core/src/test/resources/META-INF/services/org.apache.shardingsphere.mode.repository.standalone.jdbc.provider.JDBCRepositoryProvider
Fixes #19912.
- Added a fixture for JDBCRepositoryProvider
- Covered all positive and negative scenarios for all the methods of JDBCRepository using mocks
> [Issue #19912]-Added unit test for JDBCRepository

- docs/community/content/involved/release/shardingsphere.cn.md
- docs/community/content/involved/release/shardingsphere.en.md
- update release document for release vote email content
> Update release document for release vote email content

- shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/main/java/org/apache/shardingsphere/infra/federation/optimizer/planner/QueryOptimizePlannerFactory.java
- shardingsphere-infra/shardingsphere-infra-federation/shardingsphere-infra-federation-optimizer/src/test/java/org/apache/shardingsphere/infra/federation/optimizer/ShardingSphereOptimizerTest.java
Ref #19937 
- remove useless rules for push-down filters and projects. 
- remove useless subquery rules temporarily, and subquery optimization will be considered carefully in the next step.
> feat: remove useless rules for push-down filters and projects.

- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/SQLServerSchemaMetaDataLoader.java
For #20681 
- Optimize code, remove unused method param.
> Optimize code, remove unused method param.

- docs/document/content/overview/_index.cn.md
- docs/document/content/overview/_index.en.md
> Modify the level of the title

- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/lock/exception/TableLockedException.java
- Optimize error message of table lock exception
> Optimize error message of table lock exception

- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/metadata/MetaDataContextsFactory.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/metadata/persist/MetaDataPersistService.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/metadata/persist/service/DatabaseMetaDataPersistService.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/metadata/persist/service/schema/SchemaMetaDataPersistService.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/metadata/persist/service/schema/TableMetaDataPersistService.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/metadata/persist/service/schema/ViewMetaDataPersistService.java
- shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java
- shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/metadata/persist/service/DatabaseMetaDataPersistServiceTest.java
- shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/metadata/persist/service/config/schema/TableMetaDataPersistServiceTest.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/ClusterContextManagerBuilder.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/metadata/subscriber/SchemaMetaDataRegistrySubscriber.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/metadata/subscriber/SchemaMetaDataRegistrySubscriberTest.java
> Refactor DatabaseMetaDataPersistService and add TableMetaDataPersistService and ViewMetaDataPersistService

- shardingsphere-dialect-exception/shardingsphere-dialect-exception-core/src/main/java/org/apache/shardingsphere/dialect/exception/SQLDialectException.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/sql/ShardingSphereSQLException.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/exception/ExpectedExceptions.java
> Refactor ShardingSphereSQLException and SQLDialectException

- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/ShardingSphereInternalException.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/props/TypedPropertyValue.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/props/exception/TypedPropertyValueException.java
- shardingsphere-infra/shardingsphere-infra-util/src/test/java/org/apache/shardingsphere/infra/util/exception/ShardingSphereInternalExceptionTest.java
- shardingsphere-infra/shardingsphere-infra-util/src/test/java/org/apache/shardingsphere/infra/util/exception/fixture/ShardingSphereInternalExceptionFixture.java
- shardingsphere-infra/shardingsphere-infra-util/src/test/java/org/apache/shardingsphere/infra/util/props/TypedPropertyValueTest.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/command/CommandExecutorTask.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/exception/ExpectedExceptions.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/test/java/org/apache/shardingsphere/proxy/frontend/exception/ExpectedExceptionsTest.java
> Rename ShardingSphereInsideException to ShardingSphereInternalException

- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/type/MGRMySQLDatabaseDiscoveryProviderAlgorithm.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/ShardingSpherePreconditions.java
> Add ShardingSpherePreconditions

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/exception/InvalidMGRModeException.java
- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/type/MGRMySQLDatabaseDiscoveryProviderAlgorithm.java
> Add InvalidMGRModeException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/exception/InvalidMGRGroupNameConfigurationException.java
- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/type/MGRMySQLDatabaseDiscoveryProviderAlgorithm.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/ShardingSpherePreconditions.java
> Add InvalidMGRGroupNameConfigurationException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/unicast/ShardingUnicastRoutingEngineTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/checker/ShardingTableRuleStatementChecker.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/datanode/DataNode.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/exception/InvalidDataNodesFormatException.java
- shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/datanode/DataNodeTest.java
> Add InvalidDataNodesFormatException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/ActualDataNodesMissedWithShardingTableException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/rule/TableRule.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/unicast/ShardingUnicastRoutingEngineTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/rule/TableRuleTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/checker/ShardingTableRuleStatementChecker.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/datanode/DataNode.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/exception/InvalidDataNodesFormatException.java
- shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/datanode/DataNodeTest.java
> Add ActualDataNodesMissedWithShardingTableException

- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ApplyDistSQLHandler.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/DiscardDistSQLHandler.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/PrepareDistSQLHandler.java
Fix incorrect statement for DistSQL handler.
> Fix incorrect statement for DistSQL handler.

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/datanode/SingleTableDataNodeLoader.java
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/exception/SingleTablesLoadingException.java
> Add SingleTablesLoadingException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/ActualTableNotFoundException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/rule/BindingTableRule.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/rule/BindingTableRuleTest.java
> Add ActualTableNotFoundException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/DataSourceIntersectionNotFoundException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/unicast/ShardingUnicastRoutingEngine.java
> Add DataSourceIntersectionNotFoundException

- shardingsphere-infra/shardingsphere-infra-util/src/test/java/org/apache/shardingsphere/infra/util/exception/ShardingSpherePreconditionsTest.java
> [Issue #20749]-Added unit test for ShardingSpherePreconditions

- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-standalone-mode/shardingsphere-standalone-mode-repository/shardingsphere-standalone-mode-repository-provider/shardingsphere-standalone-mode-repository-jdbc/shardingsphere-standalone-mode-repository-jdbc-core/src/test/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/fixture/JDBCRepositoryProviderFixture.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-standalone-mode/shardingsphere-standalone-mode-repository/shardingsphere-standalone-mode-repository-provider/shardingsphere-standalone-mode-repository-jdbc/shardingsphere-standalone-mode-repository-jdbc-core/src/test/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/provider/JDBCRepositoryProviderFactoryTest.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-standalone-mode/shardingsphere-standalone-mode-repository/shardingsphere-standalone-mode-repository-provider/shardingsphere-standalone-mode-repository-jdbc/shardingsphere-standalone-mode-repository-jdbc-core/src/test/resources/META-INF/services/org.apache.shardingsphere.mode.repository.standalone.jdbc.provider.JDBCRepositoryProvider
> [#19911]-Added unit test for JDBCRepositoryProviderFactory

- shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/metadata/MetaDataContextsFactoryTest.java
> [Issue #19262]-Added unit test for MetaDataContextsFactory

- shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/metadata/MetaDataContextsFactoryTest.java
> Refactor MetaDataContextsFactoryTest

- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/test/java/org/apache/shardingsphere/dialect/postgresql/mapper/PostgreSQLDialectExceptionMapperTest.java
> [Issue #20692]-Use Parameterized test runner to refactor PostgreSQLDialectExceptionMapperTest

- shardingsphere-dialect-exception/shardingsphere-postgresql-dialect-exception/src/test/java/org/apache/shardingsphere/dialect/postgresql/mapper/PostgreSQLDialectExceptionMapperTest.java
> Refactor PostgreSQLDialectExceptionMapperTest

- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/DDLStatement.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/PostgreSQLKeyword.g4
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/alter-table.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/alter-view.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/alter-table.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/alter-view.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml
Ref #17848 
- `ALTER TABLE` was already partially supported, this
PR enhances that support.
- `ALTER VIEW` was already properly supported, this PR
adds additional test case.
Finishes GSOC Tasks
> Enhance support for `ALTER TABLE` and `ALTER VIEW` in PostgreSQL

- shardingsphere-kernel/shardingsphere-parser/shardingsphere-parser-core/src/test/java/org/apache/shardingsphere/parser/yaml/swapper/YamlSQLParserCacheOptionConfigurationSwapperTest.java
- shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/metadata/MetaDataContextsFactoryTest.java
Ref #20768.
- Refactor YamlSQLParserCacheOptionConfigurationSwapperTest
> Refactor YamlSQLParserCacheOptionConfigurationSwapperTest

- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/constant/DistSQLScriptConstants.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandler.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandlerTest.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/resources/conf/convert/config-encrypt.yaml
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/resources/conf/convert/config-resource.yaml
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/resources/conf/convert/config-sharding.yaml
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/resources/expected/convert-create-encrypt.yaml
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/resources/expected/convert-create-sharding.yaml
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/resources/expected/convert-database-discovery.yaml
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/QueryableRALStatementAssert.java
Fixes #17939 
- Add convert encrypt distsql
> Add convert encrypt distsql and test case

- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/switcher/ResourceSwitchManager.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/switcher/SwitchingResource.java
- shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java
- shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/switcher/ResourceSwitchManagerTest.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/ClusterContextManagerCoordinatorTest.java
> Fix add miss original data source when add new resource.

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/AlterIndexStatementHandlerTest.java
> [Issue #20377]-Improved coverage for AlterIndexStatementHandler

- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-env/src/test/java/org/apache/shardingsphere/test/integration/env/container/atomic/storage/DockerStorageContainer.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-env/src/test/java/org/apache/shardingsphere/test/integration/env/container/atomic/util/StorageContainerUtil.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-ha/src/test/java/org/apache/shardingsphere/test/integration/ha/cases/base/BaseITCase.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-ha/src/test/java/org/apache/shardingsphere/test/integration/ha/cases/mysql/MySQLHAGeneralIT.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-ha/src/test/java/org/apache/shardingsphere/test/integration/ha/framework/container/compose/BaseContainerComposer.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-ha/src/test/java/org/apache/shardingsphere/test/integration/ha/framework/container/compose/DockerContainerComposer.java
please add `test` and `refactor` label.
> Refactor : add mapped and exposed Datasource for HA testing. 

- shardingsphere-infra/shardingsphere-infra-rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/InsertValue.java
- shardingsphere-infra/shardingsphere-infra-rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/InsertValueTest.java
> Generate proper placeholder in InsertValue

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/AlterSchemaStatementHandlerTest.java
> [Issue #20383]-Improved coverage for AlterSchemaStatementHandler

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/algorithm/keygen/SnowflakeKeyGenerateAlgorithm.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/algorithm/keygen/SnowflakeKeyGenerateAlgorithmTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/main/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdSnowflakeKeyGenerateAlgorithm.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/instance/InstanceContextAware.java
- shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-namespace/src/test/java/org/apache/shardingsphere/spring/namespace/fixture/FixtureClusterPersistRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/ClusterContextManagerBuilder.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/fixture/ClusterPersistRepositoryFixture.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/ProcessListClusterPersistRepositoryFixture.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/ClusterPersistRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-etcd/src/main/java/org/apache/shardingsphere/mode/repository/cluster/etcd/EtcdRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/CuratorZookeeperRepository.java
- shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/test/java/org/apache/shardingsphere/proxy/fixture/ClusterPersistRepositoryFixture.java
- shardingsphere-test/shardingsphere-integration-driver-test/src/test/java/org/apache/shardingsphere/driver/fixture/TestClusterPersistRepository.java
- Refactor watchSessionConnection method via InstanceContextAware
> Refactor watchSessionConnection method via InstanceContextAware

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSet.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/ColumnLabelNotFoundException.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/AlterIndexStatementHandlerTest.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/AlterSchemaStatementHandlerTest.java
> Add ColumnLabelNotFoundException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/exception/UnsupportedDataTypeConversionException.java
- shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/exception/UnsupportedStreamCharsetConversionException.java
- shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/stream/JDBCStreamQueryResult.java
- shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/util/ResultSetUtil.java
- shardingsphere-infra/shardingsphere-infra-executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/util/ResultSetUtilTest.java
> Add UnsupportedStreamCharsetConversionException

- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/transaction/JDBCBackendTransactionManager.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/transaction/LocalTransactionManager.java
> Refactor JDBCBackendTransactionManager and LocalTransactionManager

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/DropTableStatementHandlerTest.java
Fixes #20376 .
- Rearranged existing test-cases to group by the database type
- Improved coverage
> [Issue #20376]-Improved coverage of DropTableStatementHandler

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/AlterIndexStatementHandlerTest.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/DropIndexStatementHandlerTest.java
Fixes #20375 .
- Added more unit-tests for DropIndexStatementHandler
- Formatting fixes for AlterIndexStatementHandlerTest
> [Issue #20375]-Improve coverage for DropIndexStatementHandler

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CreateIndexStatementHandlerTest.java
> [Issue #20384]-Added more unit tests in CreateIndexStatementHandlerTest

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/RenamedViewWithoutSameConfigException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/ddl/impl/ShardingAlterViewStatementValidator.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/ddl/ShardingAlterViewStatementValidatorTest.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandler.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandlerTest.java
Fixes #20780.
- add valid for alter rename view
> add valid for alter rename view

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CreateSchemaStatementHandlerTest.java
> [Issue #20386]-Added more scenarios to CreateSchemaStatementHandlerTest

- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesValidator.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/exception/MismatchedProtocolAndDataSourceException.java
> Add MismatchedProtocolAndDataSourceException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/util/ResultSetUtil.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/WrapperAdapter.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/ShardingSphereSavepoint.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ConnectionManager.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/OverallConnectionNotEnoughException.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/connection/ConnectionManagerTest.java
> Add OverallConnectionNotEnoughException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/ColumnIndexOutOfRangeException.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/ColumnLabelNotFoundException.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/ConnectionClosedException.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/EmptySQLException.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/ResultSetClosedException.java
> Add ConnectionClosedException

- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/database/type/dialect/OpenGaussDatabaseType.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/database/type/dialect/PostgreSQLDatabaseType.java
- shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/util/ResultSetUtil.java
- shardingsphere-infra/shardingsphere-infra-merge/src/main/java/org/apache/shardingsphere/infra/merge/result/impl/memory/MemoryMergedResult.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/ShardingSpherePreconditions.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/ShardingSphereSavepoint.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSet.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionBackendHandler.java
> Add ShardingSpherePreconditions.checkState with SQLException

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/algorithm/audit/DMLShardingConditionsShardingAuditAlgorithm.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/checker/audit/ShardingAuditChecker.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/algorithm/audit/DMLShardingConditionsShardingAuditAlgorithmTest.java
Ref #18430.
- refactor logic of DMLShardingConditionsShardingAuditAlgorithm
> Refactor logic of DMLShardingConditionsShardingAuditAlgorithm

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dal/FlushStatementHandlerTest.java
> [Issue #20370]-Added unit test for FlushStatementHandler

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CreateTableStatementHandlerTest.java
> [Issue #20385]-More unit-tests added for CreateTableStatementHandler

- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/PostgreSQLSchemaMetaDataLoader.java
- shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/PostgreSQLSchemaMetaDataLoaderTest.java
fix #16086
- add constraint info in PostgreSQLSchemaMetaDataLoader
-
-
> add constraint info in PostgreSQLSchemaMetaDataLoader

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dal/ExplainStatementHandlerTest.java
> [Issue #20371]-Improve coverage for ExplainStatementHandler

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/AlterViewStatementHandlerTest.java
> [Issue #20374]-Improving coverage of AlterViewStatementHandler

- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionBackendHandler.java
> Fix savepoint(#20820)

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/algorithm/audit/DMLShardingConditionsShardingAuditAlgorithmTest.java
Ref #20834.
- fix unit test exception when execute with JDK17
> Fix unit test exception when execute with JDK17

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingAuditorStatementUpdater.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.distsql.update.RuleDefinitionUpdater
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/DropShardingAuditorStatementUpdaterTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/antlr4/imports/sharding/RDLStatement.g4
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/antlr4/sharding/org/apache/shardingsphere/distsql/parser/autogen/ShardingDistSQLStatement.g4
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-statement/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/statement/DropShardingAuditorStatement.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/distsql/exception/rule/AuditorInUsedException.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/distsql/exception/rule/RequiredAuditorMissedException.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/rdl/drop/DropRuleStatementAssert.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/rdl/drop/impl/DropShardingAuditorStatementAssert.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/rdl/drop/DropShardingAuditorStatementTestCase.java
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/rdl/drop.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/rdl/drop.xml
> support DistSQL drop sharding auditor

- shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-core/src/main/java/org/apache/shardingsphere/readwritesplitting/checker/AbstractReadwriteSplittingRuleConfigurationChecker.java
- shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-core/src/test/java/org/apache/shardingsphere/readwritesplitting/checker/ReadwriteSplittingRuleConfigurationCheckerTest.java
Fixes #20846.
- fix config shadow and readwrite rule start failed.
> fix config shadow and readwrite rule.

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/UpdateStatementHandlerTest.java
> [Issue #20368]-Improving coverage for UpdateStatementHandler

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/exception/OverallConnectionNotEnoughException.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ConnectionManager.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/connection/ConnectionManagerTest.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/datasource/JDBCBackendDataSource.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/datasource/JDBCBackendDataSourceTest.java
> Reuse OverallConnectionNotEnoughException

- shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-namespace/src/test/java/org/apache/shardingsphere/spring/namespace/fixture/FixtureClusterPersistRepository.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/lock/LockKeyUtil.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/ClusterLockPersistService.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/fixture/ClusterPersistRepositoryFixture.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/ProcessListClusterPersistRepositoryFixture.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/ClusterPersistRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-etcd/src/main/java/org/apache/shardingsphere/mode/repository/cluster/etcd/EtcdRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/CuratorZookeeperRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/lock/ZookeeperInternalLockHolder.java
- shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/test/java/org/apache/shardingsphere/proxy/fixture/ClusterPersistRepositoryFixture.java
- shardingsphere-test/shardingsphere-integration-driver-test/src/test/java/org/apache/shardingsphere/driver/fixture/TestClusterPersistRepository.java
Related #20035.
- Optimize unLock of LockPersistService in cluster mode
> Optimize unLock of LockPersistService in cluster mode

- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/metadata/persist/service/schema/TableMetaDataPersistService.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/DropSchemaStatementHandlerTest.java
Ref #20758.
- refactor DropSchemaStatementHandlerTest
---
> Refactor DropSchemaStatementHandlerTest

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CreateFunctionStatementHandlerTest.java
> [Issue #20388]-Improving coverage of CreateFunctionStatementHandler

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CreateProcedureStatementHandlerTest.java
> [Issue #20389]-Improve coverage of CreateProcedureStatementHandler

- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/metadata/persist/service/schema/TableMetaDataPersistService.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionSetHandler.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/DropSchemaStatementHandlerTest.java
> Reuse SwitchTypeInTransactionException

- .github/workflows/it-transaction.yml
- Modify transaction integration test trigger conditions
> Modify transaction integration test trigger conditions

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-core/src/main/java/org/apache/shardingsphere/transaction/exception/StartNestedXATransactionException.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionXAHandler.java
> Add StartNestedXATransactionException

- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionXAHandler.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/tcl/XAStatement.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/tcl/MySQLXAStatement.java
> Refactor TransactionXAHandler

- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutor.java
> Clarify variables' name in PostgreSQLComDescribeExecutor

- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/ShardingSphereOptimizer.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/translatable/TranslatableProjectRule.java
Ref #20841.
- Revise PR 20841
---
> Revise PR 20841

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/SelectStatementHandlerTest.java
Fixes #20367 .
- Refactor existing unit tests in SelectStatementHandlerTest
- Improve coverage for SelectStatementHandler
> [Issue #20367]

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/CopyStatementHandlerTest.java
> [Issue #20363]-Add unit test for CopyStatementHandler

- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/AbstractMigrationITCase.java
- Extended time at migration IT case, avoid deadlock, wait the problem fixed.
---
> Extended time at migration IT case, avoid deadlock

- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/cases/dataset/metadata/DataSetColumn.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/engine/ral/BaseRALIT.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/ral/dataset/empty_rules/show_instance_list.xml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/ral/ral-integration-test-cases.xml
> Refactor DistSQL RAL assertion logic of integration test

- docs/community/content/involved/release/shardingsphere.cn.md
- docs/community/content/involved/release/shardingsphere.en.md
- Update xsd file list in release document
---
> Update xsd file list in release document

- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/context/PipelineProcessContext.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/context/AbstractInventoryIncrementalProcessContext.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/context/InventoryIncrementalProcessContext.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/InventoryTaskSplitter.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationProcessContext.java
Related to #19421
- Add InventoryIncrementalProcessContext
- Rename AbstractPipelineProcessContext to AbstractInventoryIncrementalProcessContext
- Refactor InventoryTaskSplitter and InventoryIncrementalJobItemContext
---
> Extract InventoryIncrementalProcessContext to simplify PipelineProcessContext

- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-env/src/test/java/org/apache/shardingsphere/test/integration/env/container/atomic/constants/AdapterContainerConstants.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-env/src/test/java/org/apache/shardingsphere/test/integration/env/container/atomic/constants/EnvironmentConstants.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-env/src/test/java/org/apache/shardingsphere/test/integration/env/container/atomic/constants/ProxyContainerConstants.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-env/src/test/java/org/apache/shardingsphere/test/integration/env/container/atomic/constants/StorageContainerConstants.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-ha/src/test/java/org/apache/shardingsphere/test/integration/ha/framework/container/compose/DockerContainerComposer.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/framework/container/compose/DockerContainerComposer.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/container/compose/ContainerComposerRegistry.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/engine/TotalSuitesCountCalculator.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/framework/param/array/ClusterParameterizedArrayGenerator.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/framework/param/array/JdbcStandaloneParameterizedArrayGenerator.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/framework/param/array/ParameterizedArrayFactory.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/framework/param/array/ProxyStandaloneParameterizedArrayGenerator.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/alterresource/AddResourceTestCase.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/alterresource/CloseResourceTestCase.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/truncate/MySQLXATruncateTestCase.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/base/BaseITCase.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/mysql/MySQLProxyTransactionIT.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/opengauss/OpenGaussProxyTransactionIT.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/postgresql/PostgreSQLProxyTransactionIT.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/java/org/apache/shardingsphere/integration/transaction/env/enums/TransactionTestCaseRegistry.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-transaction/src/test/java/org/apache/shardingsphere/integration/transaction/framework/container/compose/DockerContainerComposer.java
- Format the code
- replace magic variables with constants
- avoid memory leak
---
> Refactor : refactor the integration test with code conduct

- README.md
- README_ZH.md
- docs/community/content/involved/release/shardingsphere.cn.md
- docs/community/content/involved/release/shardingsphere.en.md
- examples/pom.xml
-  Update example pom version, readme.md and release document
---
> Update example pom version, readme.md and release document

- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/binlog/BinlogContext.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/ServerInfo.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/ServerVersion.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLCommandPacketDecoder.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiateHandler.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiatePackageDecoder.java
- Improve MySQL client thread safety
---
> Improve MySQL client thread safety

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/InsertStatementHandlerTest.java
Fixes #20366 .
- Refactor existing tests of InsertStatementHandler
- Improve coverage of InsertStatementHandler
> [Issue #20366]

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/UnusedShardingAuditorsQueryResultSet.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.distsql.query.DistSQLResultSet
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/UnusedShardingAuditorsQueryResultSetTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/antlr4/imports/sharding/RQLStatement.g4
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/antlr4/sharding/org/apache/shardingsphere/distsql/parser/autogen/ShardingDistSQLStatement.g4
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-statement/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/statement/ShowUnusedShardingAuditorsStatement.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/rql/impl/ShowRulesStatementAssert.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/rql/impl/rule/ShowUnusedShardingAuditorsStatementAssert.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/rql/ShowUnusedShardingAuditorsStatementTestCase.java
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/rql/show.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/rql/show.xml
> support distSQL show unused sharding auditors

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/DeleteStatementHandlerTest.java
> [Issue #20364]-Improve coverage for DeleteStatementHandler

- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/external/sql/type/feature/FeatureSQLException.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/external/sql/type/generic/GenericSQLException.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/external/sql/type/kernel/KernelSQLException.java
> Refactor FeatureSQLException and KernelSQLException

- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/type/MGRMySQLDatabaseDiscoveryProviderAlgorithm.java
- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/type/MySQLNormalReplicationDatabaseDiscoveryProviderAlgorithm.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/UpdatableRALBackendHandler.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationHandler.java
> Refactor ImportDatabaseConfigurationHandler

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-traffic/shardingsphere-traffic-core/src/main/java/org/apache/shardingsphere/traffic/exception/TrafficException.java
> Add TrafficException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/exception/UnsupportedCommandException.java
> Refactor UnsupportedCommandException

- pom.xml
- shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/release-docs/LICENSE
Fixes #20510.
- Update pom.xml and LICENSE.
- Also fixes https://github.com/apache/shardingsphere/issues/20511 . 
---
> Update slf4j, netty, vertx because of CVE

- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/database/metadata/dialect/OracleDataSourceMetaData.java
- shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/database/metadata/dialect/OracleDataSourceMetaDataTest.java
> [Issue #20529]-Fix connectDescriptorUrlPattern in OracleDataSourceMetaData class

- shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/database/metadata/dialect/OracleDataSourceMetaDataTest.java
> Code formant for OracleDataSourceMetaDataTest

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
> Add category for sql error code document

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-shadow/shardingsphere-shadow-core/src/main/java/org/apache/shardingsphere/shadow/exception/UnsupportedShadowColumnTypeException.java
- shardingsphere-features/shardingsphere-shadow/shardingsphere-shadow-core/src/main/java/org/apache/shardingsphere/shadow/exception/UnsupportedShadowInsertValueException.java
> Redefine ShadowSQLException's vendor codes

- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
- shardingsphere-kernel/shardingsphere-traffic/shardingsphere-traffic-core/src/main/java/org/apache/shardingsphere/traffic/exception/metadata/EmptyTrafficExecutionUnitException.java
> Redefine TrafficSQLException's vendor codes

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-sql-translator/shardingsphere-sql-translator-api/src/main/java/org/apache/shardingsphere/sqltranslator/exception/syntax/UnsupportedTranslatedDatabaseException.java
- shardingsphere-kernel/shardingsphere-sql-translator/shardingsphere-sql-translator-api/src/main/java/org/apache/shardingsphere/sqltranslator/exception/syntax/UnsupportedTranslatedSQLException.java
- shardingsphere-kernel/shardingsphere-sql-translator/shardingsphere-sql-translator-core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/SQLTranslatorRuleTest.java
- shardingsphere-kernel/shardingsphere-sql-translator/shardingsphere-sql-translator-core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/fixture/AlwaysFailedSQLTranslator.java
- shardingsphere-kernel/shardingsphere-sql-translator/shardingsphere-sql-translator-provider/shardingsphere-sql-translator-jooq-provider/src/main/java/org/apache/shardingsphere/sqltranslator/jooq/JooQDialectRegistry.java
- shardingsphere-kernel/shardingsphere-sql-translator/shardingsphere-sql-translator-provider/shardingsphere-sql-translator-jooq-provider/src/main/java/org/apache/shardingsphere/sqltranslator/jooq/JooQSQLTranslator.java
> Redefine SQLTranslationException's vendor codes

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/exception/mgr/InvalidMGRGroupNameConfigurationException.java
- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/exception/mgr/InvalidMGRModeException.java
- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/exception/mgr/InvalidMGRPluginException.java
- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/exception/mgr/InvalidMGRReplicationGroupMemberException.java
- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/type/MGRMySQLDatabaseDiscoveryProviderAlgorithm.java
> Redefine DBDiscoverySQLException's vendor codes

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/external/sql/type/feature/FeatureSQLException.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/external/sql/type/kernel/KernelSQLException.java
- shardingsphere-infra/shardingsphere-infra-util/src/test/java/org/apache/shardingsphere/infra/util/exception/external/sql/type/feature/FeatureSQLExceptionTest.java
- shardingsphere-infra/shardingsphere-infra-util/src/test/java/org/apache/shardingsphere/infra/util/exception/external/sql/type/kernel/KernelSQLExceptionTest.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/err/MySQLErrPacketFactoryTest.java
> Adjust category prefix of vendor codes for KernelSQLException and FeatureSQLException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/exception/syntax/UnsupportedEncryptInsertValueException.java
- shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/exception/syntax/UnsupportedEncryptSQLException.java
- shardingsphere-features/shardingsphere-shadow/shardingsphere-shadow-core/src/main/java/org/apache/shardingsphere/shadow/exception/data/UnsupportedShadowColumnTypeException.java
- shardingsphere-features/shardingsphere-shadow/shardingsphere-shadow-core/src/main/java/org/apache/shardingsphere/shadow/exception/syntax/UnsupportedShadowInsertValueException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/connection/CursorNameNotFoundException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/connection/EmptyShardingRouteResultException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/connection/ShardingDDLRouteException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/data/InvalidDatetimeFormatException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/data/NullShardingValueException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/data/ShardingValueDataTypeException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/syntax/DMLMultipleDataNodesWithLimitException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/syntax/DMLWithMultipleShardingTablesException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/syntax/DataSourceIntersectionNotFoundException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/syntax/InsertSelectTableViolationException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/syntax/MissingGenerateKeyColumnWithInsertSelectException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/syntax/RenamedViewWithoutSameConfigurationException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/syntax/UnsupportedCreateViewException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/syntax/UnsupportedPrepareRouteToSameDataSourceException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/syntax/UnsupportedShardingOperationException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/exception/syntax/UnsupportedUpdatingShardingValueException.java
- shardingsphere-kernel/shardingsphere-sql-translator/shardingsphere-sql-translator-api/src/main/java/org/apache/shardingsphere/sqltranslator/exception/syntax/UnsupportedTranslatedDatabaseException.java
- shardingsphere-kernel/shardingsphere-sql-translator/shardingsphere-sql-translator-api/src/main/java/org/apache/shardingsphere/sqltranslator/exception/syntax/UnsupportedTranslatedSQLException.java
> Adjust FeatureSQLException's vendor codes

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/exception/InvalidDataNodesFormatException.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/exception/OverallConnectionNotEnoughException.java
- shardingsphere-infra/shardingsphere-infra-datetime/shardingsphere-infra-datetime-type/shardingsphere-database-datetime/src/main/java/org/apache/shardingsphere/datetime/database/exception/DatetimeLoadingException.java
- shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/exception/UnsupportedDataTypeConversionException.java
- shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/exception/UnsupportedStreamCharsetConversionException.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/external/sql/type/kernel/KernelSQLException.java
- shardingsphere-infra/shardingsphere-infra-util/src/test/java/org/apache/shardingsphere/infra/util/exception/external/sql/type/kernel/KernelSQLExceptionTest.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/DriverRegisterException.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/connection/ConnectionClosedException.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/connection/ResultSetClosedException.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/syntax/ColumnIndexOutOfRangeException.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/syntax/ColumnLabelNotFoundException.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/transaction/JDBCTransactionAcrossDatabasesException.java
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/exception/DropNotEmptySchemaException.java
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/exception/SchemaNotFoundException.java
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/exception/SingleTableNotFoundException.java
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/exception/UnsupportedDropCascadeTableException.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/exception/OptimizationSQLNodeConvertException.java
- shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-type/shardingsphere-transaction-xa/shardingsphere-transaction-xa-core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/exception/XADataSourceInitializeException.java
- shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-type/shardingsphere-transaction-xa/shardingsphere-transaction-xa-core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/exception/XATransactionNestedBeginException.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/exception/InvalidValueException.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/exception/ResourceNotExistedException.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/exception/RuleNotExistedException.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/exception/CircuitBreakException.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/err/MySQLErrPacketFactoryTest.java
> Adjust KernelSQLException's vendor codes

- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/ShardingSpherePreconditions.java
- shardingsphere-infra/shardingsphere-infra-util/src/test/java/org/apache/shardingsphere/infra/util/exception/ShardingSpherePreconditionsTest.java
> Add ShardingSpherePreconditions.checkNotNull

- docs/blog/content/material/2022_04_13_A_Practical_Guide_to_Apache_ShardingSphere's_HINT.en.md
- shardingsphere-agent/shardingsphere-agent-plugins/shardingsphere-agent-plugin-tracing/shardingsphere-agent-tracing-zipkin/src/test/java/org/apache/shardingsphere/agent/plugin/tracing/zipkin/advice/JDBCExecutorCallbackAdviceTest.java
- shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java
- shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/PostgreSQLAggregatedCommandPacket.java
- shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLByteConverter.java
- shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/converter/ReadwriteSplittingRuleStatementConverterTest.java
- shardingsphere-features/shardingsphere-shadow/shardingsphere-shadow-core/src/main/java/org/apache/shardingsphere/shadow/algorithm/shadow/hint/ShadowHintExtractor.java
- shardingsphere-features/shardingsphere-shadow/shardingsphere-shadow-core/src/main/java/org/apache/shardingsphere/shadow/rule/ShadowRule.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/database/metadata/dialect/H2DataSourceMetaData.java
- shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/memory/loader/AbstractJDBCRowsLoader.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/metadata/IdentifierName.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/metadata/model/PipelineColumnMetaData.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/metadata/model/PipelineTableMetaData.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobPreparer.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLColumnValueReader.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/translatable/TranslatableTableScan.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/hint/HintManagerHolder.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/impl/SQLServerStatementSQLVisitor.java
> Rewrite `== null` to `null ==`

- shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/metadata/MetaDataContextsFactoryTest.java
> [Issue #19262]-Assertions added for metadata in MetaDataContextsFactory test

- shardingsphere-infra/shardingsphere-infra-binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/ddl/AlterViewStatementContext.java
- shardingsphere-infra/shardingsphere-infra-binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/ddl/AlterViewStatementContextTest.java
Fixes #20978 #20964.
- fix alter view rename bug.
> fix alter view rename bug.

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/datasource/AbstractDataSourceChecker.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/TargetTableNotEmptyWhenPrepareMigrationException.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleDDLStatementSQLVisitor.java
- shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/check/datasource/AbstractDataSourceCheckerTest.java
> Add TargetTableNotEmptyWhenPrepareMigrationException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLCharacterSet.java
- shardingsphere-infra/shardingsphere-infra-binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/InsertStatementContext.java
- shardingsphere-infra/shardingsphere-infra-binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementContext.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/database/metadata/url/StandardJdbcUrlParser.java
- shardingsphere-infra/shardingsphere-infra-merge/src/main/java/org/apache/shardingsphere/infra/merge/result/impl/stream/StreamMergedResult.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/ShardingSpherePreconditions.java
- shardingsphere-infra/shardingsphere-infra-util/src/test/java/org/apache/shardingsphere/infra/util/exception/ShardingSpherePreconditionsTest.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithoutEnoughPrivilegeException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineTableMetaDataUtil.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/check/datasource/MySQLDataSourceChecker.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/check/datasource/OpenGaussDataSourceChecker.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceChecker.java
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/route/validator/ddl/SingleTableDropSchemaMetadataValidator.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-executor/shardingsphere-sql-federation-executor-advanced/src/main/java/org/apache/shardingsphere/sqlfederation/advanced/resultset/FederationResultSet.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/DatabaseRequiredBackendHandler.java
> Reuse PrepareJobWithoutEnoughPrivilegeException

- shardingsphere-infra/shardingsphere-infra-util/src/test/java/org/apache/shardingsphere/infra/util/exception/ShardingSpherePreconditionsTest.java
> Refactor ShardingSpherePreconditionsTest

- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-standalone-mode/shardingsphere-standalone-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneContextManagerBuilder.java
For #20738.
- Support using disabled data source at startup in standalone mode
> Support using disabled data source at startup in standalone mode(#20738)

- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/datasource/state/DataSourceStateManager.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/ClusterContextManagerCoordinator.java
Fixes #20738.
- Refresh the data source state when modifying the read-write splitting data source state
> Add refresh data source states(#20738)

- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/database/CreateDatabaseBackendHandler.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/database/DropDatabaseBackendHandler.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationHandler.java
- Add method `addDatabaseAndPersist`
- Add method `dropDatabaseAndPersist`
---
> Add persist type methods for add and drop database in ContextManager

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithoutUserException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/check/datasource/OpenGaussDataSourceChecker.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceChecker.java
> Refactor PrepareJobWithoutUserException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/datasource/AbstractDataSourceChecker.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithCheckPrivilegeFailedException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithInvalidConnectionException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/check/datasource/MySQLDataSourceChecker.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/check/datasource/MySQLDataSourceCheckerTest.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/check/datasource/OpenGaussDataSourceChecker.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceChecker.java
- shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/check/datasource/AbstractDataSourceCheckerTest.java
> Add PrepareJobWithCheckPrivilegeFailedException

- shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/release-docs/LICENSE
- shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/release-docs/licenses/LICENSE-jts.txt
- shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/release-docs/licenses/LICENSE-opengauss-jdbc.txt
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SQLUtilTest.java
Ref #21028.
- Update master branch license
---
> Update master branch license

- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-executor/shardingsphere-sql-federation-executor-advanced/src/main/java/org/apache/shardingsphere/sqlfederation/advanced/AdvancedSQLFederationExecutor.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-executor/shardingsphere-sql-federation-executor-advanced/src/main/java/org/apache/shardingsphere/sqlfederation/advanced/resultset/SQLFederationResultSet.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-executor/shardingsphere-sql-federation-executor-advanced/src/test/java/org/apache/shardingsphere/sqlfederation/advanced/result/FederationResultSetTest.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-executor/shardingsphere-sql-federation-executor-core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/FilterableTableScanExecutor.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-executor/shardingsphere-sql-federation-executor-core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/TranslatableTableScanExecutor.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/parser/dialect/impl/H2OptimizerBuilder.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/parser/dialect/impl/MariaDBOptimizerBuilder.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/parser/dialect/impl/MySQLOptimizerBuilder.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/parser/dialect/impl/OpenGaussOptimizerBuilder.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/parser/dialect/impl/OracleOptimizerBuilder.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/parser/dialect/impl/PostgreSQLOptimizerBuilder.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/parser/dialect/impl/SQL92OptimizerBuilder.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/parser/dialect/impl/SQLServerOptimizerBuilder.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/planner/OptimizerPlannerContextFactory.java
- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/ShardingSphereOptimizerTest.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
Ref #19580.
- register database functions for ADVANCED federation executor
- add case sensitive props in OptimizerSQLDialectBuilder
- add integration test case for database function
---
> Register database functions for ADVANCED federation executor

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PipelineJobExecutionException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithGetBinlogPositionException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobPreparer.java
> Add PrepareJobWithGetBinlogPositionException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRulesUsedAuditorQueryResultSetTest.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PipelineImporterJobWriteException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithCheckPrivilegeFailedException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithGetBinlogPositionException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithInvalidConnectionException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithInvalidSourceDataSourceException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithTargetTableNotEmptyException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithoutEnoughPrivilegeException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithoutUserException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/SplitPipelineJobByRangeException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/SplitPipelineJobByUniqueKeyException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/InventoryTaskSplitter.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineTableMetaDataUtil.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/prepare/datasource/MySQLDataSourcePreparerTest.java
- shardingsphere-kernel/shardingsphere-sql-translator/shardingsphere-sql-translator-distsql/shardingsphere-sql-translator-distsql-handler/src/test/java/org/apache/shardingsphere/sqltranslator/distsql/handler/SQLTranslatorRuleQueryResultSetTest.java
- shardingsphere-mode/shardingsphere-mode-core/src/test/java/org/apache/shardingsphere/mode/metadata/MetaDataContextsFactoryTest.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SQLUtilTest.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/general/MySQLMigrationGeneralIT.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/primarykey/TextPrimaryKeyMigrationIT.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/rql/impl/rule/ShowShardingTableRulesUsedAuditorStatementAssert.java
- shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/prepare/InventoryTaskSplitterTest.java
> Refactor SplitPipelineJobByUniqueKeyException

- shardingsphere-kernel/shardingsphere-sql-federation/shardingsphere-sql-federation-optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/FunctionConverter.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
- shardingsphere-test/shardingsphere-optimize-test/src/test/java/org/apache/shardingsphere/infra/federation/converter/parameterized/engine/SQLNodeConvertEngineParameterizedTest.java
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/dml/select-special-function.xml
Ref #21052.
- optimize group_concat function sql paras and convert logic
- modify related test case
---
> Optimize group_concat function sql paras and convert logic

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/data/PipelineUnexpectedDataRecordOrderException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/DataRecordMerger.java
> Refactor PipelineUnexpectedDataRecordOrderException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/CRC32MatchDataConsistencyCalculateAlgorithm.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/data/PipelineTableDataConsistencyCheckLoadingFailedException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/DataRecordMerger.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/test/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/CRC32MatchDataConsistencyCalculateAlgorithmTest.java
> Add PipelineTableDataConsistencyCheckLoadingFailedException

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationJobStatusQueryResultSet.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/job/progress/InventoryIncrementalJobItemProgress.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/GovernanceRepositoryAPI.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/PipelineJobAPI.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/GovernanceRepositoryAPIImpl.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNode.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryIncrementalTasksRunner.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJob.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/base/BaseITCase.java
- Show migration status add error_msg column
- Add IT case
---
> Show migration status add error_msg column

- pom.xml
- shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/release-docs/LICENSE
Fixes #21043.
- Update pom.xml and LICENSE.
---
> Update snakeyaml to 1.32 to fix yaml deserialization problem

- docs/community/content/powered-by/_index.cn.md
- docs/community/content/powered-by/_index.en.md
> Add : add power by content

- docs/community/content/powered-by/_index.cn.md
- docs/community/content/powered-by/_index.en.md
> Fix : update the corresponding quantity of 'powered by' companies

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/CRC32MatchDataConsistencyCalculateAlgorithm.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/data/UnsupportedCRC32DataConsistencyCalculateAlgorithmException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationDataConsistencyChecker.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/sqlbuilder/MySQLPipelineSQLBuilderTest.java
> Add UnsupportedCRC32DataConsistencyCalculateAlgorithmException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/AddMigrationSourceResourceUpdater.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/connection/AddMigrationSourceResourceException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
> Refactor AddMigrationSourceResourceException

- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/job/JobType.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/GovernanceRepositoryAPI.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/GovernanceRepositoryAPIImpl.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/loader/PipelineTableMetaDataUtil.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNode.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobId.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/test/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNodeTest.java
- shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/api/impl/GovernanceRepositoryAPIImplTest.java
- shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/api/impl/MigrationJobAPIImplTest.java
- Add data consistency check related path and api in PipelineMetaDataNode
- Add CONSISTENCY_CHECK job type and id
---
> Prepare for CONSISTENCY_CHECK job

- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceChecker.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/base/BaseITCase.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/AbstractMigrationITCase.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralIT.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/primarykey/TextPrimaryKeyMigrationIT.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/task/PostgreSQLIncrementTask.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/env/IntegrationTestEnvironment.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/resources/env/scenario/primary_key/unique_key/mysql.xml
- Add clean up pipeline at native mode
- Fix codestyle
---
> Improve migration IT, add clean up pipeline at native mode

- shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-core/src/main/java/org/apache/shardingsphere/transaction/rule/TransactionRule.java
- shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-type/shardingsphere-transaction-xa/shardingsphere-transaction-xa-core/src/main/java/org/apache/shardingsphere/transaction/xa/XAShardingSphereTransactionManager.java
Fixes #21013.
- blocked until transaction management is created
---
> Fix NPE occurred when transaction management is not created(#21013)

- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/datasource/state/DataSourceState.java
- Remove unused code in DataSourceState
---
> Remove unused code in DataSourceState

- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/exception/BackendConnectionException.java
> Refactor BackendConnectionException

- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleDDLStatementSQLVisitor.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleDropJavaStatement.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/SQLParserTestCases.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/ddl/DropJavaStatementTestCase.java
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/drop-java.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/drop-java.xml
Ref https://github.com/apache/shardingsphere/issues/6480
- Add `DROP JAVA` grammar
- Support parsing `DROP JAVA`  in Oracle
- Add test
> Support parsing DROP JAVA in Oracle 

- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-opengauss/src/main/antlr4/imports/opengauss/DMLStatement.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/dml/update.xml
Fixes #21112.
- fix opengauss update set parse error.
> fix opengauss update set parse error.

- shardingsphere-test/shardingsphere-integration-test/pom.xml
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-showprocesslist/src/test/java/org/apache/shardingsphere/test/integration/showprocesslist/container/composer/ClusterShowProcessListContainerComposer.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-showprocesslist/src/test/java/org/apache/shardingsphere/test/integration/showprocesslist/engine/ShowProcessListIT.java
- import the new module `shardingsphere-integration-test-showprocesslist` which created by @tuichenchuxin 
- fix some checkstyle issues
---
> Refactor : import a new module and fix some checkstyle issues

- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/DropResourceBackendHandlerTest.java
> Fix checkstyle.

- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/pojo/PipelineJobInfo.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/InventoryTaskSplitter.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationChangedJobConfigurationProcessor.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
- Review and improve pipeline code
---
> Review and improve pipeline code

- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/JDBCBackendConnection.java
> resolve getConnection error

- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/InventoryIncrementalJobPublicAPI.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/MigrationJobPublicAPI.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/check/consistency/PipelineDataConsistencyChecker.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/InventoryIncrementalJobAPI.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractInventoryIncrementalJobAPIImpl.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/InventoryIncrementalJobPublicAPIImpl.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationChangedJobConfigurationProcessor.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationDataConsistencyChecker.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPI.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
- shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationDataConsistencyCheckerTest.java
Part of #19421.
- Extract more methods to InventoryIncrementalJobPublicAPI; Includes: job progress, data consistency check;
- Extract InventoryIncrementalJobAPI; Includes: job progress, job item progress, data consistency check;
- Add PipelineDataConsistencyChecker; Update MigrationDataConsistencyChecker constructor;
---
> Extract InventoryIncrementalJobAPI and extend InventoryIncrementalJobPublicAPI for common usage

- shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-namespace/src/test/java/org/apache/shardingsphere/spring/namespace/fixture/FixtureClusterPersistRepository.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/lock/ShardingSphereLockContext.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/ClusterLockPersistService.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/fixture/ClusterPersistRepositoryFixture.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/ProcessListClusterPersistRepositoryFixture.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/ClusterPersistRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/lock/InternalLockProvider.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-etcd/src/main/java/org/apache/shardingsphere/mode/repository/cluster/etcd/EtcdRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-etcd/src/main/java/org/apache/shardingsphere/mode/repository/cluster/etcd/lock/EtcdInternalLockProvider.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/CuratorZookeeperRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/lock/ZookeeperInternalLockProvider.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/test/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/CuratorZookeeperRepositoryTest.java
- shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/test/java/org/apache/shardingsphere/proxy/fixture/ClusterPersistRepositoryFixture.java
- shardingsphere-test/shardingsphere-integration-driver-test/src/test/java/org/apache/shardingsphere/driver/fixture/TestClusterPersistRepository.java
- Rename InternalLockHolder to InternalLockProvider
---
> Rename InternalLockHolder to InternalLockProvider

- docs/document/content/user-manual/error-code/server-error-code.cn.md
- docs/document/content/user-manual/error-code/server-error-code.en.md
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/props/exception/TypedPropertyValueException.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/spi/exception/ServiceProviderNotFoundServerException.java
- shardingsphere-infra/shardingsphere-infra-util/src/test/java/org/apache/shardingsphere/infra/util/props/exception/TypedPropertyValueExceptionTest.java
- shardingsphere-infra/shardingsphere-infra-util/src/test/java/org/apache/shardingsphere/infra/util/spi/exception/ServiceProviderNotFoundExceptionTest.java
> Update server error code doc

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/ShardingInsertValuesToken.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/ShardingInsertValuesTokenTest.java
> Fix SQL garbled after sharding rewrote

- shardingsphere-agent/shardingsphere-agent-core/src/main/java/org/apache/shardingsphere/agent/core/spi/AgentServiceLoader.java
- shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-distsql/shardingsphere-encrypt-distsql-handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleStatementUpdater.java
- shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/AlterReadwriteSplittingRuleStatementUpdater.java
- shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/DropReadwriteSplittingRuleStatementUpdater.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/CountShardingRuleQueryResultSet.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterShardingBindingTableRulesStatementUpdater.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterShardingBroadcastTableRuleStatementUpdater.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateShardingBindingTableRuleStatementUpdater.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleStatementUpdater.java
- shardingsphere-infra/shardingsphere-infra-binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementContext.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/metadata/SchemaTableName.java
> Use ShardingSpherePreconditions for throw exception

- examples/example-core/pom.xml
- examples/other-example/pom.xml
- examples/pom.xml
- examples/shardingsphere-example-generator/pom.xml
- examples/shardingsphere-jdbc-example/pom.xml
- examples/shardingsphere-proxy-example/pom.xml
> Rename shardingsphere-example's artifactId to shardingsphere-examples

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/checker/ShardingTableRuleStatementChecker.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterShardingBindingTableRulesStatementUpdater.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/AlterShardingBindingTableRulesStatementUpdaterTest.java
Fixes #21061 , enhanced validation of Alter Sharding Binding Table Rules.
---
> Enhanced validation of Alter Sharding Binding Table Rules.

- docs/document/content/reference/distsql/syntax/rdl/rule-definition/single-table/alter-default-single-table-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/single-table/alter-default-single-table-rule.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/single-table/drop-default-single-table-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/single-table/drop-default-single-table-rule.en.md
Fixes #20989 .
- add distsql rdl alter and drop default single table rule doc
-
-
---
> add distsql rdl alter and drop default single table rule doc.

- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/SchemaManager.java
- shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-nacos/pom.xml
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/NacosRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/entity/ServiceMetadata.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/listener/NamingEventListener.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/utils/NacosMetaDataUtil.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-nacos/src/test/java/org/apache/shardingsphere/mode/repository/cluster/nacos/NacosRepositoryTest.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-nacos/src/test/java/org/apache/shardingsphere/mode/repository/cluster/nacos/props/NacosPropertiesTest.java
- shardingsphere-proxy/shardingsphere-proxy-bootstrap/pom.xml
> Revise Nacos impl

- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/alter-sharding-table-rule.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/create-sharding-auditor.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/create-sharding-auditor.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/create-sharding-key-generator.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/create-sharding-key-generator.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/create-sharding-table-rule.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/spring-boot-starter/rules/ha.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/spring-boot-starter/rules/ha.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/spring-namespace/rules/ha.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/spring-namespace/rules/ha.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/ha.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/ha.en.md
- update wrong document reference
---
> Update wrong document reference

- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/persist/PipelineJobProgressPersistService.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/base/BaseITCase.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/AbstractMigrationITCase.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/general/MySQLMigrationGeneralIT.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralIT.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/primarykey/TextPrimaryKeyMigrationIT.java
- Simply wait finished method.
- Fix occasional ci error
---
> Simply migration IT method and fix occasional ci error.

- .github/workflows/check-license.yml
- .github/workflows/checkstyle-and-rat-check.yml
- .github/workflows/ci-daily.yml
- .github/workflows/ci.yml
- .github/workflows/docker-per-commit.yaml
- .github/workflows/docker.yml
- .github/workflows/it-scaling.yml
- .github/workflows/it-transaction.yml
- .github/workflows/nightlies-rsync.yml
for #21184 .
- format the order of metrix
- rename some workflow and drop the duplicated codecov job
- refactor maven OPS in  CI
---
---
> Refactor : refactor the github action workflow

- .github/workflows/checkstyle-and-rat-check.yml
- .github/workflows/ci-daily.yml
- .github/workflows/ci.yml
- .github/workflows/docker-per-commit.yaml
- .github/workflows/docker.yml
- .github/workflows/nightlies-rsync.yml
for #21184.
- refacor all maven cache usage in workflow
---
> Refactor : update all maven cache step in workflows(#21184)

- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/antlr4/imports/mysql/BaseRule.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/antlr4/imports/mysql/DDLStatement.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/BaseRule.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-sql92/src/main/antlr4/imports/sql92/BaseRule.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/dml/insert.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/dml/insert.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml
Fixes #21162.
- fix parse exception when execute insert statement with negative value
---
> Fix parse exception when execute insert statement with negative value

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/test/java/org/apache/shardingsphere/db/protocol/mysql/packet/binlog/row/column/value/time/MySQLTimestamp2BinlogProtocolValueTest.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/workerid/generator/ClusterWorkerIdGenerator.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/exception/ClusterPersistRepositoryException.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/NacosRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-nacos/src/test/java/org/apache/shardingsphere/mode/repository/cluster/nacos/NacosRepositoryTest.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/CuratorZookeeperRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/handler/CuratorZookeeperExceptionHandler.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/test/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/handler/CuratorZookeeperExceptionHandlerTest.java
> Refactor ClusterPersistRepositoryException

- shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-core/src/main/java/org/apache/shardingsphere/dbdiscovery/algorithm/DatabaseDiscoveryEngine.java
Fixes #18943 
- [bug]databaseDiscovery can not find master
> [bug]databaseDiscovery can not find master

- docs/document/content/user-manual/common-config/builtin-algorithm/metadata-repository.cn.md
- docs/document/content/user-manual/common-config/builtin-algorithm/metadata-repository.en.md
- Add metadata-repository-nacos doc
---
> Add metadata-repository-nacos doc

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/StartMigrationCheckUpdater.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/StopMigrationCheckUpdater.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-handler/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.distsql.update.RALUpdater
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/antlr4/imports/migration/RALStatement.g4
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/java/org/apache/shardingsphere/migration/distsql/parser/core/MigrationDistSQLStatementVisitor.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-statement/src/main/java/org/apache/shardingsphere/migration/distsql/statement/StartMigrationCheckStatement.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-statement/src/main/java/org/apache/shardingsphere/migration/distsql/statement/StopMigrationCheckStatement.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ConsistencyCheckJobPublicAPI.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/job/yaml/YamlConsistencyCheckJobConfigurationSwapper.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-api/src/main/java/org/apache/shardingsphere/data/pipeline/api/job/JobStatus.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/GovernanceRepositoryAPI.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/GovernanceRepositoryAPIImpl.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PipelineJobHasAlreadyFinishedException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJob.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobAPIImpl.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-env/src/test/java/org/apache/shardingsphere/test/integration/env/container/atomic/storage/impl/OpenGaussContainer.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/base/BaseITCase.java
- shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/api/impl/ConsistencyCheckJobAPIImplTest.java
- Add stop/start migration check DistSQL and implement
- Add some unit test
---
> Add stop/start migration check DistSQL and implement

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/test/java/org/apache/shardingsphere/db/protocol/mysql/packet/binlog/row/column/value/time/MySQLTimestamp2BinlogProtocolValueTest.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/workerid/generator/ClusterWorkerIdGenerator.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/exception/ClusterPersistRepositoryException.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/NacosRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-nacos/src/test/java/org/apache/shardingsphere/mode/repository/cluster/nacos/NacosRepositoryTest.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/CuratorZookeeperRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/handler/CuratorZookeeperExceptionHandler.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-zookeeper-curator/src/test/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/handler/CuratorZookeeperExceptionHandlerTest.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/exception/InvalidExecutorSuitableException.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/state/impl/JDBCOKProxyState.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/test/java/org/apache/shardingsphere/proxy/frontend/state/impl/JDBCOKProxyStateTest.java
> Add InvalidExecutorSuitableException

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/impl/InsertClauseShardingConditionEngine.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/impl/WhereClauseShardingConditionEngine.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/ConditionValue.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueBetweenOperatorGenerator.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueCompareOperatorGenerator.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueInOperatorGenerator.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/value/AlwaysFalseShardingConditionValue.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/value/ListShardingConditionValue.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/value/RangeShardingConditionValue.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/value/ShardingConditionValue.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/InsertClauseShardingConditionEngineTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/ConditionValueTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueBetweenOperatorGeneratorTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueCompareOperatorGeneratorTest.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueInOperatorGeneratorTest.java
> Support extracting sharding condition parameter marker indexes

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/syntax/ColumnIndexOutOfRangeException.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/syntax/ColumnLabelNotFoundException.java
- shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/syntax/EmptySQLException.java
- shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/main/java/org/apache/shardingsphere/singletable/exception/UnsupportedDropCascadeTableException.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/exception/UnsupportedVariableException.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/exception/SQLASTVisitorException.java
> Add SQLASTVisitorException

- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/ddl/impl/ShardingCreateViewStatementValidator.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/ddl/ShardingCreateViewStatementValidatorTest.java
- shardingsphere-infra/shardingsphere-infra-binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/ddl/CreateViewStatementContextTest.java
- shardingsphere-infra/shardingsphere-infra-context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/CreateViewStatementSchemaRefresher.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDDLStatementSQLVisitor.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussDDLStatementSQLVisitor.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLDDLStatementSQLVisitor.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/impl/SQLServerDDLStatementSQLVisitor.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java
- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/ddl/CreateViewStatement.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/ddl/DDLStatementAssert.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/ddl/impl/CreateViewStatementAssert.java
- shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/ddl/CreateViewStatementTestCase.java
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ddl/create-view.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ddl/create-view.xml
Ref #21230 #19580.
- refactor create view statement parse logic and add create view assert
---
> Refactor create view statement parse logic and add create view assert

- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLStatusFlag.java
- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/test/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLStatusFlagTest.java
> Refactor MySQLStatusFlag's exception

- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/protocol/MySQLDateBinaryProtocolValue.java
- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/protocol/MySQLTimeBinaryProtocolValue.java
- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/test/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/protocol/MySQLDateBinaryProtocolValueTest.java
- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/test/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/protocol/MySQLTimeBinaryProtocolValueTest.java
> Refactor MySQLDateBinaryProtocolValue and MySQLTimeBinaryProtocolValue

- shardingsphere-agent/shardingsphere-agent-plugins/pom.xml
Fixes #21238.
- agent plugin package excludes h2database
---
> Optimize agent plugin package dependencies,agent plugin package excludes h2database

- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ReactiveProxySQLExecutor.java
- shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutorTest.java
Fixes #21250.
- Fix openGauss cursor execution in xa transaction
---
> Fix openGauss cursor execution in xa transaction(#21250)

- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintExtractor.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintPropertiesKey.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintUtils.java
- shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/hint/SQLHintExtractorTest.java
- shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/hint/SQLHintUtilsTest.java
- shardingsphere-kernel/shardingsphere-traffic/shardingsphere-traffic-core/src/main/java/org/apache/shardingsphere/traffic/algorithm/traffic/hint/SQLHintTrafficAlgorithm.java
- shardingsphere-kernel/shardingsphere-traffic/shardingsphere-traffic-core/src/test/java/org/apache/shardingsphere/traffic/algorithm/traffic/hint/SQLHintTrafficAlgorithmTest.java
- shardingsphere-kernel/shardingsphere-traffic/shardingsphere-traffic-core/src/test/java/org/apache/shardingsphere/traffic/rule/TrafficRuleTest.java
- shardingsphere-test/shardingsphere-rewrite-test/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/update/update.xml
Fixes #20736 .
- Refactor read write split SQL hint.
- rename SQL hint key.
- fixes test case.
> Refactor read write split SQL hint

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PipelineJobHasAlreadyFinishedException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobAPIImpl.java
- shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralIT.java
For #20036.
- Change vendor code to `18095`, should not use engaged vendor code
- Use ShardingSpherePreconditions for first priority
- Update document for new error code
---
> Refactor PipelineJobHasAlreadyFinishedException

- docs/document/content/user-manual/error-code/server-error-code.cn.md
- docs/document/content/user-manual/error-code/server-error-code.en.md
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/datasource/state/DataSourceStateManager.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/datasource/state/exception/UnavailableDataSourceException.java
> Refactor DataSourceStateException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/UncompletedConsistencyCheckJobExistsException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobAPIImpl.java
> Refactor UncompletedConsistencyCheckJobExistsException

- docs/document/content/features/transaction/_index.en.md
Fixes #21296.
- Change `YM` to `TM`
- Change `XA Transanction` to `XA Transaction`
---
> Fix typos in XA Transaction section (#21296)

- shardingsphere-kernel/shardingsphere-parser/shardingsphere-parser-core/src/test/java/org/apache/shardingsphere/parser/rule/SQLParserRuleTest.java
> [Issue #20392]-Add unit test for SQLParserRule

- shardingsphere-kernel/shardingsphere-parser/shardingsphere-parser-core/src/test/java/org/apache/shardingsphere/parser/rule/builder/SQLParserRuleBuilderTest.java
> [Issue #20394]-Add unit test for SQLParserRuleBuilder

- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintExtractor.java
- shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintPropertiesKey.java
- shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/hint/SQLHintExtractorTest.java
For #20736 .
- add sharding SQL hint key.
- add test case.
---
> Add sharding SQL hint key.

- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLNewParametersBoundFlag.java
- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/main/java/org/apache/shardingsphere/db/protocol/mysql/exception/MySQLProtocolException.java
- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/test/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLNewParametersBoundFlagTest.java
> Add MySQLProtocolException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLNewParametersBoundFlag.java
- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/main/java/org/apache/shardingsphere/db/protocol/mysql/exception/MySQLProtocolException.java
- shardingsphere-db-protocol/shardingsphere-mysql-protocol/src/test/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLNewParametersBoundFlagTest.java
- shardingsphere-db-protocol/shardingsphere-postgresql-protocol/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/exception/PostgreSQLProtocolException.java
- shardingsphere-db-protocol/shardingsphere-postgresql-protocol/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/PostgreSQLCommandPacketType.java
- shardingsphere-db-protocol/shardingsphere-postgresql-protocol/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/PostgreSQLColumnType.java
- shardingsphere-db-protocol/shardingsphere-postgresql-protocol/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/close/PostgreSQLComClosePacket.java
- shardingsphere-db-protocol/shardingsphere-postgresql-protocol/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/identifier/PostgreSQLMessagePacketType.java
- shardingsphere-db-protocol/shardingsphere-postgresql-protocol/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/constant/PostgreSQLColumnTypeTest.java
- shardingsphere-db-protocol/shardingsphere-postgresql-protocol/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/PostgreSQLCommandPacketTypeLoaderTest.java
- shardingsphere-db-protocol/shardingsphere-postgresql-protocol/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/PostgreSQLCommandPacketTypeTest.java
- shardingsphere-db-protocol/shardingsphere-postgresql-protocol/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/close/PostgreSQLComClosePacketTest.java
- shardingsphere-db-protocol/shardingsphere-postgresql-protocol/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/identifier/PostgreSQLMessagePacketTypeTest.java
- shardingsphere-dialect-exception/shardingsphere-dialect-exception-core/src/main/java/org/apache/shardingsphere/dialect/SQLExceptionTransformEngine.java
- shardingsphere-dialect-exception/shardingsphere-dialect-exception-core/src/main/java/org/apache/shardingsphere/dialect/exception/protocol/DatabaseProtocolException.java
- shardingsphere-infra/shardingsphere-infra-util/src/main/java/org/apache/shardingsphere/infra/util/exception/external/sql/type/generic/DatabaseProtocolSQLException.java
- shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/exception/UnsupportedCommandException.java
> Add DatabaseProtocolException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-api/src/main/java/org/apache/shardingsphere/sharding/exception/ShardingPluginException.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/main/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/CosIdIntervalShardingAlgorithm.java
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-plugin/shardingsphere-sharding-cosid/src/main/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/CosIdSnowflakeIntervalShardingAlgorithm.java
> Add ShardingPluginException

- README.md
- Updated Hacktoberfest link.
- Before:
- After:
---
> Update Hacktoberfest link

- shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/SQLStatsTest.java
> [Issue #20353]-Add unit test for SQLStats

- docs/document/content/user-manual/common-config/builtin-algorithm/sharding.cn.md
- docs/document/content/user-manual/common-config/builtin-algorithm/sharding.en.md
> Correcting inline expression links

- shardingsphere-kernel/shardingsphere-parser/shardingsphere-parser-core/src/test/java/org/apache/shardingsphere/parser/yaml/swapper/YamlSQLParserRuleConfigurationSwapperTest.java
> [Issue #20400]-Add unit test for YamlSQLParserRuleConfigurationSwapper

- shardingsphere-kernel/shardingsphere-parser/shardingsphere-parser-core/src/test/java/org/apache/shardingsphere/parser/rule/builder/DefaultSQLParserRuleConfigurationBuilderTest.java
> [Issue #20396]-Add unit test for DefaultSQLParserRuleConfigurationBuilder

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/data/UnsupportedPipelineJobUniqueKeyDataTypeException.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/AbstractInventoryDumper.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/AbstractPipelineSQLBuilder.java
- shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/OraclePipelineSQLBuilder.java
> Add UnsupportedPipelineJobUniqueKeyDataTypeException

- shardingsphere-test/shardingsphere-pipeline-test/src/test/java/org/apache/shardingsphere/data/pipeline/core/fixture/FixtureInventoryDumper.java
> Fix test case AbstractInventoryDumper

- shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-type/shardingsphere-transaction-xa/shardingsphere-transaction-xa-provider/shardingsphere-transaction-xa-bitronix/src/test/java/org/apache/shardingsphere/transaction/xa/bitronix/manager/SingleXAResourceHolderTest.java
> [Issue #20382]-Add unit test for SingleXAResourceHolder

- shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-type/shardingsphere-transaction-xa/shardingsphere-transaction-xa-provider/shardingsphere-transaction-xa-bitronix/src/test/java/org/apache/shardingsphere/transaction/xa/bitronix/manager/BitronixRecoveryResourceTest.java
> [Issue #20381]-Improve coverage of BitronixRecoveryResource

- shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/test/java/org/apache/shardingsphere/proxy/arguments/BootstrapArgumentsTest.java
> [Issue #21016]-Improve coverage of BootstrapArguments

- shardingsphere-kernel/shardingsphere-parser/shardingsphere-parser-distsql/shardingsphere-parser-distsql-handler/src/test/java/org/apache/shardingsphere/parser/distsql/handler/query/SQLParserRuleQueryResultSetTest.java
> [Issue #21021]-Improve coverage of SQLParserRuleQueryResultSet

- shardingsphere-kernel/shardingsphere-parser/shardingsphere-parser-distsql/shardingsphere-parser-distsql-handler/src/test/java/org/apache/shardingsphere/parser/distsql/handler/query/SQLParserRuleQueryResultSetTest.java
> Remove test case for static impl

- shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-core/src/test/java/org/apache/shardingsphere/transaction/rule/builder/DefaultTransactionRuleConfigurationBuilderTest.java
> [Issue #20387]-Add unit test for DefaultTransactionRuleConfigurationBuilder

- shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-core/src/test/java/org/apache/shardingsphere/transaction/utils/AutoCommitUtilsTest.java
> [Issue #20360]-Add unit test for AutoCommitUtils

- shardingsphere-distribution/shardingsphere-proxy-native-distribution/pom.xml
- shardingsphere-mode/shardingsphere-mode-type/pom.xml
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/pom.xml
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/ConsulRepository.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/ShardingSphereConsulClient.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/ShardingSphereQueryParams.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/lock/ConsulInternalLockProvider.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/props/ConsulPropertyKey.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/test/java/org/apache/shardingsphere/mode/repository/cluster/consul/ConsulRepositoryTest.java
- shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository/shardingsphere-cluster-mode-repository-provider/shardingsphere-cluster-mode-repository-consul/src/test/java/org/apache/shardingsphere/mode/repository/cluster/consul/props/ConsulPropertiesTest.java
> Revise consul repository

- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/DCLStatement.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4
- shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/dcl/alter-role.xml
- shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/dcl/alter-role.xml
Fixes #20398
- Adds `ALTER ROLE` grammar
- Added tests
> Support Parsing `ALTER ROLE` in Oracle

- docs/community/content/team/_index.cn.md
- docs/community/content/team/_index.en.md
- update committer information
---
> Document : update the committer information

- .github/workflows/it.yml
- fix the test-suite trigger path
---
> Fix : fix the test-suite trigger path

- .github/workflows/docker-release.yml
- .github/workflows/issue-automation.yml
- refactor and fix some workflows
---
> Refactor : refactor and fix some workflows

- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/alterresource/AddResourceTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/base/BaseTransactionTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/base/BaseITCase.java
- Fix transaction test case code style
---
> Fix transaction test case code style

- jdbc/spring/core/shardingsphere-jdbc-core-spring-namespace/src/test/java/org/apache/shardingsphere/spring/namespace/fixture/FixtureClusterPersistRepository.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/persist/PersistRepository.java
- mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/fixture/ClusterPersistRepositoryFixture.java
- mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/ProcessListClusterPersistRepositoryFixture.java
- mode/type/cluster/repository/api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/ClusterPersistRepository.java
- mode/type/cluster/repository/api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/transaction/TransactionOperation.java
- mode/type/cluster/repository/provider/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/ConsulRepository.java
- mode/type/cluster/repository/provider/etcd/src/main/java/org/apache/shardingsphere/mode/repository/cluster/etcd/EtcdRepository.java
- mode/type/cluster/repository/provider/nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/NacosRepository.java
- mode/type/cluster/repository/provider/zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/CuratorZookeeperRepository.java
- mode/type/standalone/core/src/test/java/org/apache/shardingsphere/mode/manager/standalone/fixture/StandalonePersistRepositoryFixture.java
- mode/type/standalone/repository/provider/jdbc/core/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/JDBCRepository.java
- proxy/bootstrap/src/main/resources/conf/server.yaml
- proxy/bootstrap/src/test/java/org/apache/shardingsphere/proxy/fixture/ClusterPersistRepositoryFixture.java
- test/integration-driver-test/src/test/java/org/apache/shardingsphere/driver/fixture/TestClusterPersistRepository.java
> Migrate ElasticJob governance center interface to ShardingSphere governance center

- .github/workflows/ci.yml
- .github/workflows/docker-release.yml
- .github/workflows/it.yml
- .github/workflows/nightly-build.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/nightly-it-example-generator.yml
Fixes #21401 .
- upgrade all java set up in workflow
- rename some workflow
---
> Refactor : upgrade all java set up in workflow

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/ShardingSphereDatabase.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/MetaDataContextsFactory.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/ClusterContextManagerBuilder.java
- mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneContextManagerBuilder.java
- proxy/bootstrap/src/main/java/org/apache/shardingsphere/proxy/version/ShardingSphereProxyVersion.java
Fixes #21378.
- Fix check data source state
---
> Fix check data source state(#21378)

- docs/document/content/reference/encrypt/_index.en.md
> change 3 decryption algorithms into 5 decryption algorithms

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/resource/ShardingSphereResource.java
- Fix NPE when all data sources are unavailable
---
> Fix NPE when all data sources are unavailable

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/ShardingSphereDatabase.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/util/SQLFederationPlannerUtil.java
- kernel/sql-federation/optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLOptimizeEngineTest.java
- mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/ProcessListClusterPersistRepositoryFixture.java
- mode/type/cluster/repository/provider/zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/CuratorZookeeperRepository.java
- mode/type/standalone/core/src/test/java/org/apache/shardingsphere/mode/manager/standalone/fixture/StandalonePersistRepositoryFixture.java
- proxy/bootstrap/src/test/java/org/apache/shardingsphere/proxy/fixture/ClusterPersistRepositoryFixture.java
- test/integration-test/test-suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
Fixes #21388.
- add CoreRules.AGGREGATE_REDUCE_FUNCTIONS to rewrite AVG(x) to SUM(x) / COUNT(x)
- add unit test and integration test
---
> Add CoreRules.AGGREGATE_REDUCE_FUNCTIONS to rewrite AVG(x) to SUM(x) / COUNT(x)

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/resource/ShardingSphereResource.java
This reverts commit ada66afa030693f7d83a72ca3918a90c78f75e56.
-
-
-
---
> Revert "Fix NPE when all data sources are unavailable (#21412)"

- docs/blog/content/material/CNCF.cn.md
- docs/blog/content/material/CNCF.en.md
- docs/blog/content/material/committer.cn.md
- docs/blog/content/material/committer.en.md
- docs/blog/content/material/community.cn.md
- docs/blog/content/material/database.cn.md
> Refactor : refactor some docs with document conduct

- test/integration-test/test-suite/src/test/java/org/apache/shardingsphere/test/integration/engine/dql/BaseDQLIT.java
- test/integration-test/test-suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
Ref #19580.
-  Add more integration test for sql federation
---
> Add more integration test for sql federation

- infra/util/src/test/java/org/apache/shardingsphere/infra/util/yaml/YamlEngineTest.java
- mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/fixture/ClusterPersistRepositoryFixture.java
- mode/type/cluster/repository/provider/consul/src/test/java/org/apache/shardingsphere/mode/repository/cluster/consul/ConsulRepositoryTest.java
- mode/type/cluster/repository/provider/etcd/src/test/java/org/apache/shardingsphere/mode/repository/cluster/etcd/EtcdRepositoryTest.java
- mode/type/cluster/repository/provider/zookeeper-curator/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/CuratorZookeeperRepository.java
- proxy/bootstrap/src/test/java/org/apache/shardingsphere/proxy/fixture/ClusterPersistRepositoryFixture.java
- fix ci error on windows machine
---
> fix ci error on windows machine

- docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.en.md
Fixes #20049.
- Instructions for adding optional plugins to ShardingSphere Proxy documentation.
---
> Instructions for adding optional plugins to ShardingSphere Proxy documentation

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/data/ShardingStatisticsTableCollector.java
- features/sharding/core/src/main/resources/META-INF/services/org.apache.shardingsphere.data.pipeline.spi.data.collector.ShardingSphereDataCollector
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/spi/data/collector/ShardingSphereDataCollector.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/spi/data/collector/ShardingSphereDataCollectorFactory.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataJobWorker.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataScheduleCollector.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/listener/ShardingSphereDataContextManagerLifecycleListener.java
For #21268.
- collect sharding sphere data.
---
> collect sharding sphere data.

- .github/workflows/issue-automation.yml
for #21438.
- disable issue robot temporarily
---
> Refactor : disable issue robot temporarily

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/datasource/config/impl/StandardPipelineDataSourceConfiguration.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/datasource/config/yaml/YamlJdbcConfiguration.java
- kernel/data-pipeline/api/src/test/java/org/apache/shardingsphere/data/pipeline/api/datasource/config/impl/StandardPipelineDataSourceConfigurationTest.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLIncrementalDumper.java
- kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/OpenGaussLogicalReplication.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/LogicalReplication.java
- test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/api/datasource/config/yaml/YamlJdbcConfigurationTest.java
- test/pipeline/src/test/resources/config_sharding_sphere_jdbc_source.yaml
- test/pipeline/src/test/resources/config_sharding_sphere_jdbc_target.yaml
- test/pipeline/src/test/resources/config_standard_jdbc_target.yaml
- test/pipeline/src/test/resources/migration_sharding_sphere_jdbc_target.yaml
- test/pipeline/src/test/resources/migration_standard_jdbc_source.yaml
- Refactor jdbcUrl to url in data pipeline
---
> Refactor jdbcUrl to url in data pipeline YamlJdbcConfiguration

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckStatusQueryResultSet.java
- features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/migration/distsql/statement/ShowMigrationCheckStatusStatement.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ConsistencyCheckJobPublicAPI.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/InventoryIncrementalJobPublicAPI.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/job/progress/ConsistencyCheckJobProgress.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/job/progress/listener/PipelineJobProgressUpdatedParameter.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/pojo/ConsistencyCheckJobProgressInfo.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/GovernanceRepositoryAPI.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/InventoryIncrementalJobAPI.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractInventoryIncrementalJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/GovernanceRepositoryAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/SingleTableInventoryDataConsistencyChecker.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/DefaultImporter.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlConsistencyCheckJobProgress.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlConsistencyCheckJobProgressSwapper.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJob.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobItemContext.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckTasksRunner.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationDataConsistencyChecker.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobItemContext.java
- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/base/BaseITCase.java
- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/AbstractMigrationITCase.java
- test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/api/impl/MigrationJobAPIImplTest.java
- test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationDataConsistencyCheckerTest.java
- Refactor show migration check status DistSQL implementation
- Fix IT case
---
> Refactor show migration check status DistSQL implementation

- docs/document/content/dev-manual/proxy.cn.md
- docs/document/content/dev-manual/proxy.en.md
> Correct links in dev manual proxy

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/ddl/fetch/FetchStreamMergedResult.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/orderby/OrderByValue.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/context/cursor/CursorConnectionContext.java
Fixes #21421.
- Fix fetch forward all error in openGauss
---
> Fix fetch forward all error in openGauss(#21421)

- docs/document/content/quick-start/shardingsphere-proxy-quick-start.cn.md
- docs/document/content/quick-start/shardingsphere-proxy-quick-start.en.md
- Add data sources force start document
> Add data sources force start document

- docs/document/content/user-manual/shardingsphere-proxy/show-processlist/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/show-processlist/_index.en.md
- Add show processlist document
> Add show processlist document

- test/integration-test/test-suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/create_single_table_rules.xml
- test/integration-test/test-suite/src/test/resources/cases/rdl/rdl-integration-test-cases.xml
Fixes #21072.
- add test case for single table rule
-
-
---
> add test case for single table rule

- docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.en.md
- docs/document/content/user-manual/shardingsphere-proxy/session/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/session/_index.en.md
> add session management

- infra/common/src/main/resources/schema/mysql/information_schema/columns.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/engines.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/parameters.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/routines.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/schemata.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/tables.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/views.yaml
- infra/common/src/main/resources/schema/mysql/mysql/db.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/accounts.yaml
- infra/common/src/main/resources/schema/mysql/shardingsphere/sharding_statistics_table.yaml
- infra/common/src/main/resources/schema/mysql/sys/sys.yaml
- infra/common/src/main/resources/schema/opengauss/shardingsphere/sharding_statistics_table.yaml
- infra/common/src/main/resources/schema/postgresql/information_schema/columns.yaml
- infra/common/src/main/resources/schema/postgresql/information_schema/tables.yaml
- infra/common/src/main/resources/schema/postgresql/information_schema/views.yaml
- infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_class.yaml
- infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_database.yaml
- infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_inherits.yaml
- infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_tablespace.yaml
- infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_trigger.yaml
- infra/common/src/main/resources/schema/postgresql/shardingsphere/sharding_statistics_table.yaml
> Fix select * from information_schema.tables error.

- .github/PULL_REQUEST_TEMPLATE
- add new rule to github pull request template
---
> Refactor : add new rule for github pull request template

- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/constant/DatabaseDiscoveryOrder.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/constant/ReadwriteSplittingOrder.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/constant/ShadowOrder.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClient.java
Ref #21481.
- adjust order of DatabaseRuleConfiguration
---
> Adjust order of DatabaseRuleConfiguration

- docs/document/content/user-manual/shardingsphere-proxy/startup/dependencies-download/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/startup/dependencies-download/_index.en.md
- docs/document/content/user-manual/shardingsphere-proxy/startup/dependencies-download/add_Bitronix_dependency.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/startup/dependencies-download/add_Bitronix_dependency.en.md
- docs/document/content/user-manual/shardingsphere-proxy/startup/dependencies-download/add_Narayana_dependency.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/startup/dependencies-download/add_Narayana_dependency.en.md
> Add dependency download document

- docs/document/content/faq/_index.cn.md
- docs/document/content/faq/_index.en.md
- examples/shardingsphere-proxy-example/shardingsphere-proxy-boot-mybatis-example/src/main/java/org/apache/shardingsphere/example/proxy/spring/boot/mybatis/ProxySpringBootStarterExample.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/checker/AbstractReadwriteSplittingRuleConfigurationChecker.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/rule/ReadwriteSplittingRule.java
- proxy/bootstrap/src/main/resources/conf/config-readwrite-splitting.yaml
- Modify remaining replica query to readwrite-splitting
---
> Modify remaining replica query to readwrite-splitting

- docs/document/content/user-manual/shardingsphere-jdbc/special-api/readwrite-splitting/hint.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/special-api/readwrite-splitting/hint.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/special-api/sharding/hint.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/special-api/sharding/hint.en.md
ref #20736 .
- Fixes `read write` SQL hint document.
- Fixes `sharding` SQL hint document.
> Fixes SQL hint document.

- .github/workflows/it.yml
- remove the keystore for specific jobs.
---
> Refactor : remove the keystore for specific jobs.

- sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/ColumnExtractorTest.java
Fixes https://github.com/apache/shardingsphere/issues/20361.
Add unit test for ColumnExtractor
My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
> Add ColumnExtractorTest

- sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/ColumnExtractorTest.java
Ref #21532.
- Revise pr #21532
---
> Revise pr #21532

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/RefreshTableMetadataHandler.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/RefreshTableMetadataHandlerTest.java
> Fixes #19714, NPE when `REFRESH TABLE METADATA`

- docs/community/content/involved/release/shardingsphere-on-cloud.cn.md
- docs/community/content/involved/release/shardingsphere-on-cloud.en.md
- add close milestone step in shardingsphere on cloud release document
---
> Add close milestone step in shardingsphere on cloud release document

- docs/community/content/involved/release/shardingsphere-on-cloud.cn.md
- docs/community/content/involved/release/shardingsphere-on-cloud.en.md
- update document about updating charts version in release document
---
> Update document about updating charts version in release document

- docs/community/content/involved/release/shardingsphere.cn.md
- docs/community/content/involved/release/shardingsphere.en.md
- Update distribution package path after ShardingSphere module name simplify
---
> Update distribution package path after ShardingSphere module name simplify

- docs/community/content/involved/release/shardingsphere-on-cloud.cn.md
- docs/community/content/involved/release/shardingsphere-on-cloud.en.md
- Update ShardingSphere on Cloud release document
---
> Update ShardingSphere on Cloud release document

- docs/document/content/reference/distsql/syntax/rdl/rule-definition/encrypt/alter-encrypt-rule.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/encrypt/drop-encrypt-rule.en.md
Fixes #21190.
- Refactor `ALTER ENCRYPT RULE`
- Refactor `DROP ENCRYPT RULE`
---
> Refactored RDL-encrypt-related documentation

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java
Fixes #21589.
- Fix NPE when call findTableRule with subquery table
---
> Fix NPE when call findTableRule with subquery table

- docs/document/content/user-manual/shardingsphere-jdbc/special-api/readwrite-splitting/hint.cn.md
> Revise readwrite hint doc.

- .github/workflows/nightly-build.yml
Fixes #21623.
- add nightly image build
---
> Add : add nightly image build

- README.md
- README_ZH.md
- Update next version in README.md and README_ZH.md
---
> Update next version in README.md and README_ZH.md

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/single-table.en.md
> Change Chinese into English

- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/MySQLServerPreparedStatement.java
- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/execute/MySQLComStmtExecuteExecutor.java
- proxy/frontend/reactive-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/reactive/mysql/command/query/binary/execute/ReactiveMySQLComStmtExecuteExecutor.java
> Make field of MySQLServerPreparedStatement final

- .github/workflows/nightly-build.yml
> Fix path of Nightly Build

- docs/document/content/user-manual/shardingsphere-jdbc/special-api/sharding/hint.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/special-api/sharding/hint.en.md
- Update sql hint force sharding document
---
> Update sql hint force sharding document

- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/ShardingAutoTableAlgorithmUtilTest.java
Fixes #21569
- Add Test cases for the class ShardingAutoTableAlgorithmUtil.java
---
> [ISSUE #21569] Add Tests for ShardingAutoTableAlgorithmUtil Class

- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/ShardingAutoTableAlgorithmUtilTest.java
Ref #21603.
- Revise pr 21603
---
> Revise pr 21603

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/job/progress/InventoryIncrementalJobItemProgress.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/InventoryIncrementalJobItemAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/context/InventoryIncrementalJobItemContext.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlInventoryIncrementalJobItemProgress.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlInventoryIncrementalJobItemProgressSwapper.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/InventoryTaskSplitter.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/AbstractPipelineSQLBuilder.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobItemContext.java
- Add inventory records count at job item progress
---
> Add inventory records count at job item progress

- shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-core/src/test/java/org/apache/shardingsphere/transaction/rule/builder/TransactionRuleBuilderTest.java
Fixes #20356
- Adding test to TransactionRuleBuilder
---
> Adding test to TransactionRuleBuilder

- kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/rule/builder/TransactionRuleBuilderTest.java
> Revise TransactionRuleBuilderTest

- db-protocol/opengauss/pom.xml
- db-protocol/opengauss/src/main/java/org/apache/shardingsphere/db/protocol/opengauss/packet/command/generic/OpenGaussErrorResponsePacket.java
- db-protocol/opengauss/src/test/java/org/apache/shardingsphere/db/protocol/opengauss/packet/command/generic/OpenGaussErrorResponsePacketTest.java
- proxy/bootstrap/pom.xml
- proxy/frontend/opengauss/pom.xml
- proxy/frontend/opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/err/OpenGaussErrorPacketFactory.java
- proxy/frontend/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/err/OpenGaussErrorPacketFactoryTest.java
Related to #20036.
Replace reflection with direct coding for openGauss.
> Refactor OpenGaussErrorPacketFactory

- docs/document/content/user-manual/shardingsphere-proxy/startup/docker.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/startup/docker.en.md
> add note of environment variable cgroup

- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/base/BaseITCase.java
- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/general/MySQLMigrationGeneralIT.java
- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralIT.java
- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/primarykey/TextPrimaryKeyMigrationIT.java
- Improve check migration after stop
---
> Improve migration IT, remove comment

- kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/ConnectionSavepointManagerTest.java
- kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/yaml/swapper/ConnectionSavepointManagerTest.java
Fixes #20365
- Adding test to ConnectionSavepointManager
> Adding test to ConnectionSavepointManager

- kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/ConnectionSavepointManagerTest.java
> Revise ConnectionSavepointManagerTest

- .github/workflows/nightly-build.yml
> fix proxy-image Build failures

- mode/type/standalone/repository/provider/jdbc/core/src/test/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/JDBCRepositoryTest.java
Fixes #21609.
- Fix JDBCRepositoryTest error log printing
---
> Fix JDBCRepositoryTest error log printing

- infra/common/src/main/java/org/apache/shardingsphere/infra/database/type/DatabaseTypeEngine.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/ShardingSphereDatabasesFactory.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/resource/ShardingSphereResourceMetaData.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/database/type/DatabaseTypeEngineTest.java
- infra/datetime/type/database/src/main/java/org/apache/shardingsphere/datetime/database/DatabaseDatetimeService.java
- infra/datetime/type/database/src/main/java/org/apache/shardingsphere/datetime/database/config/DatabaseDatetimeServiceConfiguration.java
- infra/datetime/type/database/src/test/java/org/apache/shardingsphere/datetime/database/config/DatabaseDatetimeServiceConfigurationTest.java
- kernel/single-table/core/src/main/java/org/apache/shardingsphere/singletable/rule/SingleTableRule.java
- mode/core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java
Ref #21481.
- refactor DatabaseTypeEngine logic
---
> Refactor DatabaseTypeEngine logic and update unit test

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/job/PipelineJob.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/PipelineJobCenter.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckChangedJobConfigurationProcessor.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJob.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationChangedJobConfigurationProcessor.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJob.java
- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/framework/container/config/proxy/ScalingProxyClusterContainerConfigurationFactory.java
> Revise pr 21750

- docs/community/content/involved/release/shardingsphere-on-cloud.cn.md
- docs/community/content/involved/release/shardingsphere-on-cloud.en.md
> feat(release): release doc

- infra/common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintExtractor.java
> refactor code.

- docs/community/content/involved/release/shardingsphere-on-cloud.cn.md
- docs/community/content/involved/release/shardingsphere-on-cloud.en.md
- update release doc for on cloud
> feat(doc):  update release doc for on cloud

- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/datasource/MySQLJdbcQueryPropertiesExtension.java
> fix issue: refactor MySQLJdbcQueryPropertiesExtension.

- docs/community/content/involved/release/shardingsphere-on-cloud.cn.md
- docs/community/content/involved/release/shardingsphere-on-cloud.en.md
- Update vote template content in ShardingSphere on Cloud release document
---
> Update vote template content in ShardingSphere on Cloud release document

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/datatypeloader/MySQLDataTypeLoader.java
Fixes #21751.
- Add a MySQL data type, linestring. Map it to binary.
---
> fix issue: add MySQL data type, linestring.

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/common/SchemaTableNamesLoader.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/datatype/MySQLDataTypeLoader.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/datatype/OracleDataTypeLoader.java
- infra/common/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.metadata.database.schema.loader.spi.DataTypeLoader
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/common/SchemaTableNamesLoaderTest.java
- proxy/bootstrap/src/main/resources/conf/server.yaml
- Add ## conditional judgment to the isSystemTable method
- rename datatypeloader package to datatype
- format rule in server.yaml
---
> Add ## conditional judgment to the isSystemTable method

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariableHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableHandler.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactoryTest.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariableBackendHandlerTest.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesHandlerTest.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableBackendHandlerTest.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableExecutorTest.java
Fixes #21678.
- Rename DistSQL variable related classes
- Revise classes comments
---
> Rename DistSQL variable related classes

- docs/document/content/user-manual/shardingsphere-jdbc/spring-boot-starter/_index.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/spring-boot-starter/_index.en.md
> add springboot version

- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/parser/OptimizerParserContextFactory.java
- optimize OptimizerParserContextFactory#create getDatabaseType logic
---
> Optimize OptimizerParserContextFactory#create getDatabaseType logic

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/PipelineJobPreparerUtils.java
- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/AbstractMigrationITCase.java
- test/integration-test/scaling/src/test/resources/env/common/migration-command.xml
Fixes #21561.
- Support migration target database name case insensitive
---
> Support migration target database name case insensitive

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportDatabaseConfigurationHandler.java
Added check for empty rule configuration to export syntax.
before:
after:
---
> Added check for empty rule configuration to export syntax.

- docs/document/content/user-manual/shardingsphere-jdbc/spring-boot-starter/_index.en.md
> modify experiental to experimental

- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4
- sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
- test/parser/src/main/resources/case/dml/select.xml
- test/parser/src/main/resources/sql/supported/dml/select.xml
Ref #21804.
- support oracle analyticFunction parse
---
> Support oracle analyticFunction parse

- docs/document/content/reference/distsql/syntax/rdl/rule-definition/db-discovery/alter-db-discovery-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/db-discovery/alter-db-discovery-rule.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/db-discovery/drop-db-discovery-heartbeat.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/db-discovery/drop-db-discovery-heartbeat.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/db-discovery/drop-db-discovery-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/db-discovery/drop-db-discovery-rule.en.md
- Update distsql RDL create db discovery rule document
- Update distsql RDL alter db discovery rule document
- Update distsql RDL drop db discovery rule document
- Update distsql RDL drop db discovery heartbeat document
---
> Update DistSQL documents

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/db-discovery.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/db-discovery.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding.cn.md
- src/resources/spotless_shardingsphere_formatter.xml
> Revise documents.

- mode/core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java
> Fix unit test NPE

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/event/handler/PipelineChangedJobConfigurationProcessor.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/datasource/AbstractDataSourcePreparer.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationDataConsistencyChecker.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/GlobalTableMapEventMapping.java
- kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/OpenGaussIncrementalDumperCreator.java
- kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/OpenGaussPositionInitializer.java
- kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/OpenGaussWALDumper.java
- kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPlugin.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/PostgreSQLIncrementalDumperCreator.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLPositionInitializer.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLWALDumper.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/PostgreSQLLogicalReplication.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALEventConverter.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALPosition.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/DecodingPlugin.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPlugin.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/event/AbstractRowEvent.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/event/AbstractWALEvent.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/event/PlaceholderEvent.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLPositionInitializerTest.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLWALDumperTest.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/PostgreSQLLogicalReplicationTest.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALEventConverterTest.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALPositionTest.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPluginTest.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/sqlbuilder/PostgreSQLPipelineSQLBuilderTest.java
- test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/dumper/IncrementalDumperCreatorFactoryTest.java
- Rename Wal to WAL in class name
- Add PostgreSQL prefix for LogicalReplication; there's already OpenGaussLogicalReplication
- Improve code style
- Add TODO
---
> Refactor pipeline and improve code style part 1

- distsql/parser/src/main/antlr4/imports/BaseRule.g4
- distsql/parser/src/main/antlr4/imports/RALStatement.g4
- features/db-discovery/distsql/parser/src/main/antlr4/imports/db-discovery/BaseRule.g4
- features/db-discovery/distsql/parser/src/main/antlr4/imports/db-discovery/Keyword.g4
- features/db-discovery/distsql/parser/src/main/antlr4/imports/db-discovery/RDLStatement.g4
- features/db-discovery/distsql/parser/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/parser/core/DatabaseDiscoveryDistSQLStatementVisitor.java
- features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/BaseRule.g4
- features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/RDLStatement.g4
- features/encrypt/distsql/parser/src/main/java/org/apache/shardingsphere/encrypt/distsql/parser/core/EncryptDistSQLStatementVisitor.java
- features/readwrite-splitting/distsql/parser/src/main/antlr4/imports/readwrite-splitting/BaseRule.g4
- features/readwrite-splitting/distsql/parser/src/main/antlr4/imports/readwrite-splitting/RDLStatement.g4
- features/readwrite-splitting/distsql/parser/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/parser/core/ReadwriteSplittingDistSQLStatementVisitor.java
- features/shadow/distsql/parser/src/main/antlr4/imports/shadow/BaseRule.g4
- features/shadow/distsql/parser/src/main/antlr4/imports/shadow/Keyword.g4
- features/shadow/distsql/parser/src/main/antlr4/imports/shadow/RDLStatement.g4
- features/shadow/distsql/parser/src/main/java/org/apache/shardingsphere/shadow/distsql/parser/core/ShadowDistSQLStatementVisitor.java
- features/sharding/distsql/parser/src/main/antlr4/imports/migration/BaseRule.g4
- features/sharding/distsql/parser/src/main/antlr4/imports/migration/Keyword.g4
- features/sharding/distsql/parser/src/main/antlr4/imports/sharding/BaseRule.g4
- features/sharding/distsql/parser/src/main/antlr4/imports/sharding/RDLStatement.g4
- features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/migration/distsql/parser/core/MigrationDistSQLStatementVisitor.java
- features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java
- test/parser/src/main/resources/case/rdl/create.xml
- test/parser/src/main/resources/sql/supported/rdl/create.xml
For #21543.
- Make property value support `INT` and `BOOLEAN`, not only `STRING`
- Unify the definition of properties in all feature DistSQL
Due to the large number of affected files, the documents will be updated in the next PR.
---
> For #21543, improve properties definition in DistSQL.

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptInsertValueParameterRewriter.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptInsertValuesTokenGenerator.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptInsertValuesTokenGeneratorTest.java
- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/insert/values/InsertValueContext.java
- infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/insert/values/InsertValueContextTest.java
Fixes #21668.
- Fix NullPointerException when insert encrypt value is null
---
> [ISSUE #21668] Fix nullPointer when encrypt value is null

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow.en.md
For #21855. #21696
-  Update distsql syntax documents of readwrite splitting and shadow
> Update distsql syntax documents of readwrite splitting and shadow

- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptInsertValuesTokenGeneratorTest.java
- infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/insert/values/InsertValueContextTest.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintExtractor.java
- infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/InsertValue.java
- test/rewrite/src/test/java/org/apache/shardingsphere/sharding/rewrite/fixture/encrypt/RewriteNormalEncryptAlgorithmFixture.java
- test/rewrite/src/test/java/org/apache/shardingsphere/sharding/rewrite/fixture/encrypt/RewriteQueryAssistedEncryptAlgorithmFixture.java
- test/rewrite/src/test/java/org/apache/shardingsphere/sharding/rewrite/fixture/encrypt/RewriteSchemaMetaDataAwareEncryptAlgorithmFixture.java
- test/rewrite/src/test/java/org/apache/shardingsphere/sharding/rewrite/parameterized/engine/AbstractSQLRewriterParameterizedTest.java
- test/rewrite/src/test/java/org/apache/shardingsphere/sharding/rewrite/parameterized/engine/parameter/SQLRewriteEngineTestParameters.java
- test/rewrite/src/test/java/org/apache/shardingsphere/sharding/rewrite/parameterized/engine/parameter/SQLRewriteEngineTestParametersBuilder.java
- test/rewrite/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/insert/insert-column.xml
- test/rewrite/src/test/resources/scenario/encrypt/case/query-with-plain/dml/insert/insert-column.xml
Ref #21686.
- support query assist column rewrite when insert null value with encrypt column
- add rewrite test case
---
> Support query assist column rewrite when insert null value with encrypt column

- .github/workflows/it-scaling.yml
- pom.xml
- Upgrade the version of elasticjob
---
> Upgrade the version of elasticjob

- db-protocol/opengauss/src/main/java/org/apache/shardingsphere/db/protocol/opengauss/constant/OpenGaussProtocolVersion.java
- db-protocol/opengauss/src/main/java/org/apache/shardingsphere/db/protocol/opengauss/packet/authentication/OpenGaussAuthenticationSCRAMSha256Packet.java
- db-protocol/opengauss/src/test/java/org/apache/shardingsphere/db/protocol/opengauss/packet/authentication/OpenGaussAuthenticationSCRAMSha256PacketTest.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/handshake/PostgreSQLComStartupPacket.java
- proxy/frontend/opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationEngine.java
- proxy/frontend/opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationHandler.java
- proxy/frontend/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationEngineTest.java
> Fix gsql 3.0 may be stuck when connecting Proxy

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
> Fix issue 21867

- kernel/sql-federation/api/src/main/java/org/apache/shardingsphere/sqlfederation/spi/SQLFederationExecutor.java
- kernel/sql-federation/executor/advanced/src/main/java/org/apache/shardingsphere/sqlfederation/advanced/AdvancedSQLFederationExecutor.java
- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/FilterableTableScanExecutor.java
- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/TranslatableTableScanExecutor.java
- kernel/sql-federation/executor/original/src/main/java/org/apache/shardingsphere/sqlfederation/original/OriginalSQLFederationExecutor.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/translatable/TranslatableDatabase.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/translatable/TranslatableSchema.java
- kernel/sql-federation/optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLOptimizeEngineTest.java
Ref #20982.
- optimize AdvancedSQLFederationExecutor logic
---
> Optimize AdvancedSQLFederationExecutor logic

- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/HintRALStatementAssert.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/hint/AddShardingHintDatabaseValueStatementAssert.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/AddShardingHintDatabaseValueStatementTestCase.java
- test/parser/src/main/resources/case/ral/hint.xml
Fixes #[21467](https://github.com/apache/shardingsphere/issues/21467).
-
-
---
> Added SQL parser test case for AddShardingHintDatabaseValueStatement

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactory.java
- proxy/frontend/reactive-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/reactive/mysql/command/query/binary/execute/ReactiveMySQLComStmtExecuteExecutor.java
> Fix parameters are missed when checking SQL in Proxy backend

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/hint/HintRALStatementExecutorFactory.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/hint/executor/AddShardingHintDatabaseValueExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/hint/executor/AddShardingHintTableValueExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/hint/executor/ClearHintExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/hint/executor/ClearReadwriteSplittingHintExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/hint/executor/ClearShardingHintExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/hint/executor/SetReadwriteSplittingHintExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/hint/executor/SetShardingHintDatabaseValueExecutor.java
Revise #11838.
- Remove `EmptyStatement` from hint executor.
---
> Revise #11838, remove `EmptyStatement` from hint executor.

- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dal/show/DecoratedEncryptShowCreateTableMergedResultTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dal/show/MergedEncryptShowCreateTableMergedResultTest.java
For #21890
- [] I have made corresponding changes to the documentation.
> Fix ci error cause of fix show create table for encrypt table.

- .github/workflows/it-showprocesslist.yml
- test/integration-test/showprocesslist/src/test/java/org/apache/shardingsphere/test/integration/showprocesslist/container/composer/ClusterShowProcessListContainerComposer.java
- test/integration-test/showprocesslist/src/test/java/org/apache/shardingsphere/test/integration/showprocesslist/engine/ShowProcessListIT.java
- test/integration-test/showprocesslist/src/test/java/org/apache/shardingsphere/test/integration/showprocesslist/env/IntegrationTestEnvironment.java
- test/integration-test/showprocesslist/src/test/java/org/apache/shardingsphere/test/integration/showprocesslist/parameter/ShowProcessListParameterized.java
- test/integration-test/showprocesslist/src/test/resources/env/it-env.properties
For #19691.
- Add standalone mode for show processlist it.
-
-
---
- [] I have made corresponding changes to the documentation.
> Add standalone mode for show processlist it.

- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/ha.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/ha.en.md
> add discovery types of ha

- kernel/transaction/type/xa/provider/atomikos/src/test/java/org/apache/shardingsphere/transaction/xa/atomikos/manager/AtomikosTransactionManagerProviderTest.java
> [Issue #20380]-Improve coverage of AtomikosTransactionManagerProvider

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/SchemaMetaDataLoaderEngine.java
Fixes #21932.
- modify SQLException to Exception for more chance to load metadata
---
> Modify SQLException to Exception for more chance to load metadata

- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/DynamicLoadingSQLParserParameterizedTest.java
> Refactor DynamicLoadingSQLParserParameterizedTest

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateShardingTableReferenceRuleStatementUpdater.java
Fixes #21951.
- add check when create sharding table reference rule
---
> add check when create sharding table reference rule

- sql-parser/dialect/mysql/src/test/java/org/apache/shardingsphere/sql/parser/mysql/DynamicLoadingMySQLParserParameterizedTest.java
- sql-parser/dialect/postgresql/src/test/java/org/apache/shardingsphere/sql/parser/postgresql/DynamicLoadingPostgreSQLParserParameterizedTest.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/DynamicLoadingSQLParserParameterizedTest.java
> Refactor : disable the dynamic parser test temp temporarily

- test/integration-test/sql-parser/pom.xml
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/mysql/DynamicLoadingMySQLParserParameterizedTest.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/postgresql/DynamicLoadingPostgreSQLParserParameterizedTest.java
> Transfer parser test from UT to IT

- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/actual/init-sql/h2/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/actual/init-sql/h2/actual-db_0-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/actual/init-sql/h2/actual-db_1-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/actual/init-sql/h2/actual-logic_db-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/expected/init-sql/h2/01-expected-init.sql
- add cascade for drop h2 drop statement to avoid exception
---
> Add cascade for drop h2 drop statement to avoid exception

- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/metadata/EncryptSchemaMetaDataDecoratorTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/metadata/ShardingSchemaMetaDataDecoratorTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/common/DataTypeLoaderTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/H2SchemaMetaDataLoaderTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/OracleSchemaMetaDataLoaderTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/dialect/SQLServerSchemaMetaDataLoaderTest.java
- kernel/single-table/core/src/test/java/org/apache/shardingsphere/singletable/metadata/SingleTableSchemaMetaDataDecoratorTest.java
- test/rewrite/src/test/java/org/apache/shardingsphere/sharding/rewrite/parameterized/scenario/EncryptSQLRewriterParameterizedTest.java
- replace magic number to JDBC data type constant
---
> Replace magic number to JDBC data type constant

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckStatusQueryResultSet.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationJobStatusQueryResultSet.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ConsistencyCheckJobPublicAPI.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/InventoryIncrementalJobPublicAPI.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/datasource/config/impl/StandardPipelineDataSourceConfiguration.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/job/progress/ConsistencyCheckJobItemProgress.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/pojo/ConsistencyCheckJobItemInfo.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/pojo/InventoryIncrementalJobItemInfo.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/pojo/InventoryIncrementalJobItemProgressInfo.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractInventoryIncrementalJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlConsistencyCheckJobItemProgress.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlConsistencyCheckJobItemProgressSwapper.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobAPIImpl.java
- Revise pr 21929 and other related code style improvement
---
> Revise 21929

- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/classictransfer/ClassicTransferTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/commitrollback/MultiOperationsCommitAndRollbackTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/readonly/MySQLSetReadOnlyTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/readonly/PostgreSQLSetReadOnlyTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/readonly/SetReadOnlyTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/savepoint/BaseSavePointTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/base/BaseITCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/base/BaseTransactionITCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/mysql/MySQLJdbcTransactionIT.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/mysql/MySQLProxyTransactionIT.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/opengauss/OpenGaussJdbcTransactionIT.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/opengauss/OpenGaussProxyTransactionIT.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/postgresql/PostgreSQLJdbcTransactionIT.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/postgresql/PostgreSQLProxyTransactionIT.java
- Clean up transaction test code
---
> Clean up transaction test code

- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/nested/NestedTransactionTestCase.java
- test/integration-test/transaction/src/test/resources/env/it-env.properties
- Add nested transaction test case
---
> Add nested transaction test case

- docs/community/content/security/_index.cn.md
- docs/community/content/security/_index.en.md
Add ElasticJob-UI CVE-2022-31764
> Update security pages

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptPredicateColumnTokenGenerator.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/EncryptRuleTest.java
- features/encrypt/spring/spring-boot-starter/src/test/resources/application-encrypt.properties
- features/encrypt/spring/spring-namespace/src/main/resources/META-INF/namespace/encrypt.xsd
- features/encrypt/spring/spring-namespace/src/test/java/org/apache/shardingsphere/encrypt/spring/namespace/EncryptSpringNamespaceTest.java
- features/encrypt/spring/spring-namespace/src/test/resources/META-INF/spring/encrypt-application-context.xml
Fixes #21940.
- Revise pr 21940
---
> Revise pr 21940

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/spi/ingest/dumper/ColumnValueReader.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/AbstractColumnValueReader.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/ColumnValueReaderFactory.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/DefaultColumnValueReader.java
- kernel/data-pipeline/core/src/main/resources/META-INF/services/org.apache.shardingsphere.data.pipeline.spi.ingest.dumper.ColumnValueReader
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLColumnValueReader.java
- test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/ColumnValueReaderFactoryTest.java
- Refactor ColumnValueReader impl
---
> Refactor ColumnValueReader impl

- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/base/DynamicLoadingSQLParserParameterizedTest.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/mysql/DynamicLoadingMySQLParserParameterizedIT.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/postgresql/DynamicLoadingPostgreSQLParserParameterizedIT.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/result/CSVResultGenerator.java
- test/integration-test/sql-parser/src/test/resources/env/it-env.properties
> Revise #22011

- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/base/BaseITCase.java
- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/AbstractMigrationITCase.java
- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/general/MySQLMigrationGeneralIT.java
- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralIT.java
- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/framework/helper/ScalingCaseHelper.java
- Improve migration IT
- Fix codestyle
-
---
> Improve migration IT, use a separate key generate and add wait job prepare success check method

- infra/common/src/main/java/org/apache/shardingsphere/infra/instance/InstanceContext.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/event/WorkerIdEvent.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/service/ComputeNodeStatusService.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/watcher/ComputeNodeStateChangedWatcher.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/StateChangedSubscriber.java
- mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/StateChangedSubscriberTest.java
- test/integration-test/test-suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/show_compute_nodes.xml
Fixes https://github.com/apache/shardingsphere/pull/18951.
> Revise pr 18951

- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/base/DynamicLoadingSQLParserParameterizedTest.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/mysql/DynamicLoadingMySQLParserParameterizedIT.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/postgresql/DynamicLoadingPostgreSQLParserParameterizedIT.java
Fixes #22006.
- Remove databaseType of getTestParameters
- Correct call of getTestParameters
- Correct comment of Parameters
---
> Remove databaseType to simplify code style

- .github/workflows/nightly-sql-parser.yml
Fixes #21999
- add github action to generate the SQL parser report
---
> Add : add github action to generate the SQL parser report

- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/base/DynamicLoadingSQLParserParameterizedTest.java
- Filter ERROR result while loading SQL case.
---
> feat: Filter ERROR result while loading SQL case

- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/base/DynamicLoadingSQLParserParameterizedTest.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/env/IntegrationTestEnvironment.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/loader/DynamicSQLCaseGitHubLoader.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/loader/DynamicSQLCaseGiteeLoader.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/loader/DynamicSQLCaseLocalLoader.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/mysql/DynamicLoadingMySQLParserParameterizedIT.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/postgresql/DynamicLoadingPostgreSQLParserParameterizedIT.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/result/SQLParserCSVResultProcessor.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/result/SQLParserLogResultProcessor.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/result/SQLParserResultProcessor.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/result/SQLParserResultProcessorManager.java
- test/integration-test/sql-parser/src/test/resources/env/it-env.properties
Fixes #21999.
- refactor the SQL parser result processor with strategy pattern
---
> Refactor : refactor the SQL parser result processor with strategy pattern

- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/result/SQLParserResultProcessorManager.java
Fixes #21999.
- add back the missing class name
---
> Fix : add back the missing class name

- .github/workflows/nightly-sql-parser.yml
Fixes #21999.
- add workflow dispatch for SQL parser action
---
> Add : add workflow dispatch for SQL parser action

- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/base/DynamicLoadingSQLParserParameterizedTest.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/mysql/DynamicLoadingMySQLParserParameterizedIT.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/postgresql/DynamicLoadingPostgreSQLParserParameterizedIT.java
- Replace cases with results while dynamic loading SQL cases
- Fix: check case with type
---
> Replace cases with results while dynamic loading SQL cases

- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4
- sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
- test/parser/src/main/resources/case/dml/select.xml
- test/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #22041
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/PERCENT_RANK.html#GUID-66A868F5-9EBA-482A-BF8C-09300B9EE165
---
> Update Oracle DML SLELECT PERCENT_RANK statement parse

- infra/util/src/main/java/org/apache/shardingsphere/infra/util/exception/external/sql/type/generic/GenericSQLException.java
- infra/util/src/main/java/org/apache/shardingsphere/infra/util/exception/external/sql/type/generic/UnknownSQLException.java
- infra/util/src/main/java/org/apache/shardingsphere/infra/util/exception/external/sql/type/wrapper/SQLWrapperException.java
- Enable cause for UnknownSQLException and SQLWrapperException
---
> Enable cause for UnknownSQLException and SQLWrapperException

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/rule/ReadwriteSplittingRule.java
> Remove load banlance map to avoid multi groups readwirte-splitting rule refer to one load banlancer name be overwrite

- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java
- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/fieldlist/MySQLComFieldListPacketExecutor.java
- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java
- proxy/frontend/reactive-mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/reactive/mysql/command/query/text/fieldlist/ReactiveMySQLComFieldListPacketExecutor.java
> repair prepareStatement connection.getDatabase null

- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
- test/parser/src/main/resources/case/dml/select.xml
- test/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #22069
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/PERCENTILE_DISC.html#GUID-7C34FDDA-C241-474F-8C5C-50CC0182E005
---
> Update Oracle DML SLELECT PERCENTILE_DISC statement parse

- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
- test/parser/src/main/resources/case/dml/select.xml
- test/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #22074
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/CUME_DIST.html#GUID-B12C577C-A63C-4D19-8E18-FCCBBFBF8278
---
> Update Oracle DML SLELECT CUME_DIST statement parse

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataScheduleCollector.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataCollectorFixture.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataCollectorTest.java
- kernel/data-pipeline/core/src/test/resources/META-INF/services/org.apache.shardingsphere.data.pipeline.spi.data.collector.ShardingSphereDataCollector
For #22052.
- Refactor ShardingSphereDataScheduleCollector.
---
> Refactor ShardingSphereDataScheduleCollector.

- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
- test/parser/src/main/resources/case/dml/select.xml
- test/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #22079
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/RANK.html#GUID-0950BD34-C994-41DA-A8F9-34B3FE53BBBA
---
> Update Oracle DML SLELECT RANK statement parse

- .github/PULL_REQUEST_TEMPLATE
- .github/workflows/ci.yml
- .github/workflows/it-scaling.yml
- .github/workflows/it-showprocesslist.yml
- .github/workflows/it-transaction.yml
- .github/workflows/it.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/nightly-it-example-generator.yml
- .github/workflows/nightly-sql-parser.yml
- pom.xml
- Add : add RAT plugin to enable local check
---
> Add : add RAT plugin to enable local check

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/rule/ReadwriteSplittingRule.java
- kernel/traffic/core/src/main/java/org/apache/shardingsphere/traffic/rule/TrafficRule.java
Fixes #22050, https://github.com/apache/shardingsphere/pull/22059.
> Refactor ReadwriteSplittingRule and TrafficRule trafficAlgorithm map and loadBalancers map

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/constant/DistSQLScriptConstants.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandler.java
- proxy/backend/src/test/resources/expected/convert-mix.yaml
- proxy/backend/src/test/resources/expected/convert-sharding.yaml
Remove invalid syntax in ConvertYamlConfigurationHandler.
---
> Remove invalid syntax in ConvertYamlConfigurationHandler.

- docs/community/content/involved/conduct/code.cn.md
- docs/community/content/involved/conduct/code.en.md
After some discussion between developers, we'll improve some of them.
- Update code of conduct
---
> Update code of conduct

- docs/document/content/user-manual/common-config/builtin-algorithm/encrypt.cn.md
- docs/document/content/user-manual/common-config/builtin-algorithm/encrypt.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/encrypt.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/encrypt.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/mix.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/mix.en.md
-Update builtin-algorithm and java-api on encrypt document
---
> Update builtin-algorithm and java-api on encrypt document

- infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/driver/jdbc/JDBCExecutor.java
- infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/raw/RawExecutor.java
- infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/jdbc/JDBCExecutorTest.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/DriverExecutor.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/executor/batch/BatchPreparedStatementExecutorTest.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/ProxySQLExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/JDBCDatabaseCommunicationEngine.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/PreviewHandler.java
- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java
- proxy/frontend/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/command/query/extended/bind/OpenGaussComBatchBindExecutorTest.java
- proxy/frontend/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutor.java
- proxy/frontend/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLAggregatedBatchedStatementsCommandExecutorTest.java
- proxy/frontend/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutorTest.java
Fix serial flag judgment error within the transaction(#12052)
Fixes #12052.
- Fix serial flag judgment error within the transaction
---
> Fix serial flag judgment error within the transaction(#12052)

- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/alterresource/AddResourceTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/alterresource/CloseResourceTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/autocommit/MySQLAutoCommitTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/autocommit/PostgresSQLAutoCommitTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/base/BaseTransactionTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/commitrollback/BroadcastTableTransactionTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/commitrollback/ExceptionInTransactionTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/commitrollback/MultiOperationsCommitAndRollbackTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/commitrollback/MultiTableCommitAndRollbackTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/commitrollback/SingleTableCommitAndRollbackTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/cursor/OpenGaussCursorTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/nested/NestedTransactionTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/readonly/MySQLSetReadOnlyTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/readonly/PostgreSQLSetReadOnlyTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/readonly/SetReadOnlyTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/savepoint/OpenGaussSavePointTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/savepoint/PostgreSQLSavePointTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/truncate/MySQLLocalTruncateTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/truncate/MySQLXATruncateTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/truncate/PostgresSQLAndOpenGaussTruncateTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/constants/TransactionTestConstants.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/mysql/MysqlJdbcTransactionIT.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/mysql/MysqlProxyTransactionIT.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/postgresql/PostgresqlJdbcTransactionIT.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/postgresql/PostgresqlProxyTransactionIT.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/env/enums/TransactionTestCaseRegistry.java
- Rename transaction test variable names
---
> Rename transaction test variable names

- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/base/DynamicLoadingSQLParserParameterizedTest.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/loader/DynamicSQLCaseGitHubLoader.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/loader/DynamicSQLCaseGiteeLoader.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/loader/DynamicSQLCaseLoaderStrategy.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/loader/DynamicSQLCaseLocalLoader.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/mysql/DynamicLoadingMySQLParserParameterizedIT.java
- test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/postgresql/DynamicLoadingPostgreSQLParserParameterizedIT.java
- Add 3rd param sqlCaseResultURI & update sqlFilter
- Update calls of getTestParameters
-
---
> Restructure SQL filter of loading cases

- docs/document/content/reference/distsql/syntax/ral/import-database-configuration.cn.md
- docs/document/content/reference/distsql/syntax/ral/import-database-configuration.en.md
- Correct DistSQL RAL import database configuration from file document
---
> Correct DistSQL RAL document

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobPreparer.java
- Avoid possible exception in pipeline
---
> Avoid possible exception in pipeline

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/like/CharDigestLikeEncryptAlgorithm.java
Fixes #22098.
- refactor CharDigestLikeEncryptAlgorithm logic and code style
---
> Refactor CharDigestLikeEncryptAlgorithm logic and code style

- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Number.g4
- test/parser/src/main/resources/case/dml/select.xml
- test/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #22116
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/REGR_-Linear-Regression-Functions.html#GUID-A675B68F-2A88-4843-BE2C-FCDE9C65F9A9
---
> Update Oracle DML SLELECT regression functions statement parse

- .github/workflows/nightly-sql-parser.yml
- sql-parser/dialect/pom.xml
- add workflow support for SQL parser IT
---
> Add : add workflow support for SQL parser IT

- kernel/sql-federation/executor/advanced/src/main/java/org/apache/shardingsphere/sqlfederation/advanced/AdvancedSQLFederationExecutor.java
- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/FilterableTableScanExecutor.java
- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/TranslatableTableScanExecutor.java
- kernel/sql-federation/executor/original/src/main/java/org/apache/shardingsphere/sqlfederation/original/OriginalSQLFederationExecutor.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/OptimizerContext.java
- kernel/sql-federation/optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/context/OptimizerContextTest.java
- add public method for OptimizerContext map to access
---
> Add public method for OptimizerContext map to access

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/mysql/executor/ShowDatabasesExecutor.java
- test/integration-test/test-suite/src/test/resources/cases/dal/dataset/db/mysql/show_databases.xml
- test/integration-test/test-suite/src/test/resources/cases/dal/dataset/dbtbl_with_readwrite_splitting/mysql/show_databases.xml
- test/integration-test/test-suite/src/test/resources/cases/dal/dataset/dbtbl_with_readwrite_splitting_and_encrypt/mysql/show_databases.xml
- test/integration-test/test-suite/src/test/resources/cases/dal/dataset/encrypt/mysql/show_databases.xml
- test/integration-test/test-suite/src/test/resources/cases/dal/dataset/encrypt_and_readwrite_splitting/mysql/show_databases.xml
- test/integration-test/test-suite/src/test/resources/cases/dal/dataset/readwrite_splitting/mysql/show_databases.xml
- test/integration-test/test-suite/src/test/resources/cases/dal/dataset/sharding_and_encrypt/mysql/show_databases.xml
- test/integration-test/test-suite/src/test/resources/cases/dal/dataset/sharding_governance/mysql/show_databases.xml
- test/integration-test/test-suite/src/test/resources/cases/dal/dataset/tbl/mysql/show_databases.xml
- add order for show database result and modify integration test case
---
> Add order for show database result and modify integration test case

- kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/rule/TransactionRule.java
- kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/rule/TransactionRuleTest.java
- Fix alter transaction rule error
---
> Fix alter transaction rule error

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/tables/PgClassTableCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/tables/PgNamespaceTableCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/data/swapper/YamlShardingSphereTableDataSwapper.java
- infra/common/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.metadata.data.collector.ShardingSphereDataCollector
For #22052.
- Add pg_class and pg_namespace data collector.
---
> Add pg_class and pg_namespace data collector.

- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/distsql/ral/impl/HintRALStatementAssert.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/distsql/ral/impl/hint/SetShardingHintDatabaseValueStatementAssert.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/jaxb/cases/domain/statement/distsql/ral/SetShardingHintDatabaseValueStatementTestCase.java
- test/parser/src/main/resources/case/ral/hint.xml
For #21465 .
- Add test unit for SetShardingHintDatabaseValueStatement.
---
> test(issue-21465): set-sharding-hint-database-value-statement

- docs/document/content/user-manual/shardingsphere-jdbc/spring-boot-starter/rules/encrypt.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/spring-boot-starter/rules/encrypt.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/spring-boot-starter/rules/mix.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/spring-boot-starter/rules/mix.en.md
-Update builtin-algorithm and java-api on encrypt document 
---
> Update spring-boot-starter rules on encrypt document

- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/ProcessListChangedSubscriber.java
- mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/ProcessListChangedSubscriberTest.java
> fix issue 20802

- .github/workflows/check.yml
- .github/workflows/ci.yml
- .github/workflows/it-scaling.yml
- .github/workflows/it-showprocesslist.yml
- .github/workflows/it-transaction.yml
- .github/workflows/it.yml
- .github/workflows/nightly-build.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/nightly-it-example-generator.yml
for #21934.
- add mannully trigger for workflows
---
> Add : add manully trigger for all workflows(#21934)

- .github/workflows/nightly-build.yml
for #21934.
- build the docker test image through a specific commit id
---
> Build the docker test image through a specific commit id

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandler.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandlerTest.java
Add parsing verification for generated sql.
---
> Enhance the test case of ConvertYamlConfigurationHandler.

- docs/document/content/user-manual/shardingsphere-proxy/logging/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/logging/_index.en.md
- Add logging configuration document for Proxy
---
> Add logging configuration document for Proxy

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/util/SystemSchemaUtil.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/util/SystemSchemaUtilTest.java
For #22052.
- Fix using federation to select from system schema.
---
> Fix using federation to select from system schema.

- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/BinaryOperationExpressionConverter.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/util/SQLFederationPlannerUtil.java
For #22052.
- Support registry user defined function and add operator for federation.
---
> Support registry user defined function and add operator for federation.

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/RegisterMigrationSourceStorageUnitUpdater.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesValidator.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesValidatorTest.java
- mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/ProcessListChangedSubscriberTest.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/AlterStorageUnitBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/RegisterStorageUnitBackendHandler.java
Fixes #22177, support heterogeneous databases for DistSQL.
- Remove databaseType from DataSourcePropertiesValidator.
---
> Support heterogeneous databases for DistSQL

- docs/blog/content/material/2022_03_18_Executor_Engine_Performance_Optimization_Showcase_with_Apache_ShardingSphere_5.1.0.en.md
Fixes #22188.
- convert multi lines into one line.
---
> Fix unmarshal failed

- distsql/statement/src/main/java/org/apache/shardingsphere/distsql/parser/statement/rdl/StorageUnitDefinitionStatement.java
- distsql/statement/src/main/java/org/apache/shardingsphere/distsql/parser/statement/rdl/create/RegisterStorageUnitStatement.java
- distsql/statement/src/main/java/org/apache/shardingsphere/distsql/parser/statement/rdl/drop/UnregisterStorageUnitStatement.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/RDLBackendHandlerFactory.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/AlterStorageUnitBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/RegisterStorageUnitBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/StorageUnitBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/UnregisterStorageUnitBackendHandler.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/resource/UnregisterStorageUnitBackendHandlerTest.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/distsql/rdl/alter/AlterStorageUnitStatementAssert.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/distsql/rdl/create/RegisterStorageUnitStatementAssert.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/distsql/rdl/drop/UnregisterStorageUnitStatementAssert.java
Refactor StorageUnitBackendHandler.
- Add interface method `checkSQLStatement`
- Optimize method names and param names
- Optimize the order of private methods
---
> Refactor StorageUnitBackendHandler.

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/data/ShardingStatisticsTableCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/ShardingSphereDataCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/tables/PgClassTableCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/tables/PgNamespaceTableCollector.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataScheduleCollector.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataCollectorFixture.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataCollectorTest.java
- Add all databases param in shardingsphere table collector
---
> Add all databases param in shardingsphere table collector

- .github/workflows/nightly-build.yml
- mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/ProcessListChangedSubscriberTest.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/external/engine/SQLParserParameterizedIT.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/external/env/SQLParserExternalITEnvironment.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/external/loader/SQLCaseLoader.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/external/loader/strategy/impl/GitHubSQLCaseLoadStrategy.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/external/loader/strategy/impl/LocalFileSQLCaseLoadStrategy.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/external/loader/summary/FileSummary.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/external/result/type/csv/CsvSQLParseResultReporter.java
- test/parser/src/main/resources/META-INF/services/org.apache.shardingsphere.test.sql.parser.external.result.SQLParseResultReporterCreator
- Add fileloader support and reafctor the parser code
---
> Refactor : add fileloader support and reafctor the parser code

- docs/document/content/features/transaction/limitations.cn.md
> Update typo in limitations.cn.md

- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/cursor/OpenGaussCursorTestCase.java
- test/integration-test/transaction/src/test/resources/env/jdbc/mysql/config-sharding-local.yaml
- test/integration-test/transaction/src/test/resources/env/jdbc/mysql/config-sharding-xa-atomikos.yaml
- test/integration-test/transaction/src/test/resources/env/jdbc/mysql/config-sharding-xa-bitronix.yaml
- test/integration-test/transaction/src/test/resources/env/jdbc/opengauss/config-sharding-local.yaml
- test/integration-test/transaction/src/test/resources/env/jdbc/opengauss/config-sharding-xa-atomikos.yaml
- test/integration-test/transaction/src/test/resources/env/jdbc/opengauss/config-sharding-xa-bitronix.yaml
- test/integration-test/transaction/src/test/resources/env/jdbc/opengauss/config-sharding-xa-narayana.yaml
- test/integration-test/transaction/src/test/resources/env/jdbc/postgresql/config-sharding-local.yaml
- test/integration-test/transaction/src/test/resources/env/jdbc/postgresql/config-sharding-xa-atomikos.yaml
- test/integration-test/transaction/src/test/resources/env/jdbc/postgresql/config-sharding-xa-bitronix.yaml
- test/integration-test/transaction/src/test/resources/env/jdbc/postgresql/config-sharding-xa-narayana.yaml
- test/integration-test/transaction/src/test/resources/env/opengauss/server.yaml
- test/integration-test/transaction/src/test/resources/env/postgresql/server.yaml
- test/integration-test/transaction/src/test/resources/env/scenario/cursor/data/actual/init-sql/opengauss/01-actual-init.sql
- Enable federation config in transaction IT
---
> Enable federation config in transaction IT

- docs/document/themes/hugo-theme-learn/layouts/partials/language.html
Fixes #22126.
- Adding a version switch button
---
> Add a version switch button in the upper right corner of the document page

- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
- sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
- test/parser/src/main/resources/case/dml/insert.xml
- test/parser/src/main/resources/sql/supported/dml/insert.xml
Fixes #22226.
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/Literals.html#GUID-8F4B3F82-8821-4071-84D6-FBBA21C05AC1
---
> Update Oracle DML INSERT Datetime Literals statement parse

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/data/ShardingStatisticsTableCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/tables/PgClassTableCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/tables/PgNamespaceTableCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/data/swapper/YamlShardingSphereTableDataSwapper.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataScheduleCollector.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataCollectorFixture.java
- test/integration-test/discovery/pom.xml
For #22052.
- Optimize pg_class, pg_namespace collect logic, add decorate logic.
---
> Optimize pg_class, pg_namespace collect logic, add decorate logic.

- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/cases/base/BaseITCase.java
- test/integration-test/scaling/src/test/java/org/apache/shardingsphere/integration/data/pipeline/command/ExtraSQLCommand.java
- test/integration-test/scaling/src/test/resources/env/common/migration-command.xml
- Update table sharding rule at migration IT
---
> Update table sharding rule at migration IT

- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
- sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
- test/parser/src/main/resources/case/dml/select.xml
- test/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #22254.
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/XMLCOLATTVAL.html#GUID-AE3B6441-74D8-4033-900B-A578A79E5F0A
---
> Update Oracle SQL XMLCOLATTVAL function parse

- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/ExpressionConverter.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/CaseWhenConverter.java
- sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
- sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/CaseWhenSegment.java
- test/optimize/src/test/java/org/apache/shardingsphere/infra/federation/converter/parameterized/engine/SQLNodeConverterEngineParameterizedTest.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/jaxb/cases/domain/segment/impl/expr/ExpectedCaseWhenExpression.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/jaxb/cases/domain/segment/impl/expr/ExpectedExpression.java
- test/parser/src/main/resources/case/dml/select-expression.xml
- test/parser/src/main/resources/sql/supported/dml/select-expression.xml
Fixes #21392.
For #22052
- Add case when segment, support sql node convert.
---
> Add case when segment, support sql node convert.

- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/FilterableTableScanExecutor.java
- kernel/sql-federation/executor/core/src/test/java/org/apache/shardingsphere/sqlfederation/executor/FilterableTableScanExecutorTest.java
For #22052.
- Fix no resource, select contains system schema NPE.
---
> Fix no resource, select contains system schema NPE.

- test/integration-test/fixture/Dockerfile
> Reduce integration test image size

- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
- sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
- test/parser/src/main/resources/case/dml/select.xml
- test/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #22282.
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/XMLFOREST.html#GUID-68E5C67E-CE97-4BF8-B7FF-2365E062C363
---
> Update Oracle SQL XMLFOREST function parse

- docs/document/content/reference/management/_index.cn.md
- docs/document/content/reference/management/_index.en.md
> change dataSources to data_sources

- test/integration-test/scaling/src/test/resources/env/opengauss/01-initdb.sql
- Fix opengauss ci permission
---
> Fix opengauss ci permission

- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
- sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
- test/parser/src/main/resources/case/dml/select.xml
- test/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #22308.
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/XMLPARSE.html#GUID-39A93E58-F06E-4633-A7BF-6CF27A53D9B6
---
> Update Oracle SQL XMLPARSE function parse

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/ShardingSphereTableDataCollectorUtil.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/tables/PgClassTableCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/tables/PgNamespaceTableCollector.java
- infra/common/src/main/resources/schema/opengauss/pg_catalog/pg_class.yaml
- infra/common/src/main/resources/schema/opengauss/pg_catalog/pg_namespace.yaml
For #22052.
- Support og \d and optimize table collect code.
---
> Support og \d and optimize table collect code.

- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropShadowRuleStatementUpdater.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/DropShadowRuleStatementUpdaterTest.java
Fixes #22300.
- Fix update logic in `DropShadowRuleStatementUpdater`
- Optimize `DropShadowRuleStatementUpdaterTest`
---
> Fix DropShadowRuleStatementUpdater

- infra/util/src/main/java/org/apache/shardingsphere/infra/util/retry/RetryExecutor.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/RegistryCenter.java
- mode/type/cluster/repository/api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/lock/impl/DefaultDistributedLock.java
- mode/type/cluster/repository/api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/lock/impl/DefaultDistributedLockCreator.java
- mode/type/cluster/repository/api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/lock/impl/props/DefaultLockPropertyKey.java
- mode/type/cluster/repository/api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/lock/impl/props/DefaultLockTypedProperties.java
- mode/type/cluster/repository/api/src/main/resources/META-INF/services/org.apache.shardingsphere.mode.repository.cluster.lock.creator.DistributedLockCreator
- mode/type/cluster/repository/api/src/test/java/org/apache/shardingsphere/mode/repository/cluster/lock/holder/DistributedLockHolderTest.java
- mode/type/cluster/repository/api/src/test/java/org/apache/shardingsphere/mode/repository/cluster/lock/impl/props/DefaultLockTypedPropertiesTest.java
- mode/type/cluster/repository/provider/nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/NacosRepository.java
- Add default implementation of distributed lock
---
> Add default implementation of distributed lock

- test/integration-test/test-suite/src/test/java/org/apache/shardingsphere/test/integration/cases/value/SQLValue.java
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/db/batch_insert_for_order.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/db/delete_with_sharding_value.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/db/insert_for_order_1.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/db/insert_for_order_2.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/db/insert_multiple_values_for_order_1_2.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/db/insert_on_duplicate_key_update.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/db/update.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/db/update_with_column_equal_column.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/db/update_without_condition.xml
- test/integration-test/test-suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/actual/dataset.xml
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/actual/init-sql/h2/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/actual/init-sql/mysql/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/actual/init-sql/opengauss/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/actual/init-sql/oracle/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/actual/init-sql/postgresql/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/actual/init-sql/sqlserver/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/expected/dataset.xml
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/expected/init-sql/h2/01-expected-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/expected/init-sql/mysql/01-expected-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/expected/init-sql/opengauss/01-expected-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/expected/init-sql/oracle/01-expected-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/expected/init-sql/postgresql/01-expected-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/db/data/expected/init-sql/sqlserver/01-expected-init.sql
Fixes #22170.
- add integration test case for select group by statement contains null value record
---
> Add integration test case for select group by statement contains null value record

- test/integration-test/test-suite/src/test/java/org/apache/shardingsphere/test/integration/cases/dataset/DataSetLoader.java
- test/integration-test/test-suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/opengauss/select_sys_data_for_og.xml
- test/integration-test/test-suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/postgresql/select_sys_data_for_pg.xml
- test/integration-test/test-suite/src/test/resources/cases/ral/dataset/empty_rules/standalone/opengauss/select_sys_data_for_og.xml
- test/integration-test/test-suite/src/test/resources/cases/ral/dataset/empty_rules/standalone/postgresql/select_sys_data_for_pg.xml
- test/integration-test/test-suite/src/test/resources/cases/ral/ral-integration-test-cases.xml
- test/integration-test/test-suite/src/test/resources/env/common/cluster/proxy/conf/server.yaml
Fixes #22052.
- Add pg/og \d it.
-
-
---
> Add pg/og \d it.

- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/sharding-cache.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/sharding-cache.en.md
> Add documents for sharding cache

- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/builder/ResponsePacketBuilder.java
- proxy/frontend/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/execute/MySQLComStmtExecuteExecutorTest.java
- proxy/frontend/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/builder/ResponsePacketBuilderTest.java
- proxy/frontend/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLComQueryPacketExecutorTest.java
> Set binary flag for MySQL column definition packet

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow.en.md
> delete shadow status

- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
- sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
- test/parser/src/main/resources/case/dml/select.xml
- test/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #22323.
Ref: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/XMLROOT.html#GUID-5BD300E2-7138-436D-87AF-21658840CF9D
---
> Update Oracle SQL XMLROOT function parse

- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/tbl/insert_max_values_into_single_table_integer.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/tbl/insert_min_values_into_single_table_integer.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/tbl/insert_negative_values_into_single_table_integer.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/tbl/mysql/insert_min_values_into_single_table_integer.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/tbl/mysql/insert_negative_smallint_into_single_table_integer.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dml-integration-test-cases.xml
- test/integration-test/test-suite/src/test/resources/env/scenario/tbl/data/actual/dataset.xml
- test/integration-test/test-suite/src/test/resources/env/scenario/tbl/data/actual/init-sql/h2/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/tbl/data/actual/init-sql/mysql/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/tbl/data/actual/init-sql/opengauss/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/tbl/data/actual/init-sql/postgresql/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/tbl/data/expected/dataset.xml
- test/integration-test/test-suite/src/test/resources/env/scenario/tbl/data/expected/init-sql/h2/01-expected-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/tbl/data/expected/init-sql/mysql/01-expected-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/tbl/data/expected/init-sql/opengauss/01-expected-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/tbl/data/expected/init-sql/postgresql/01-expected-init.sql
> Add IT cases to cover PostgreSQL/openGauss integer types

- docs/document/content/user-manual/shardingsphere-jdbc/spring-namespace/rules/encrypt.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/spring-namespace/rules/encrypt.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/spring-namespace/rules/mix.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/spring-namespace/rules/mix.en.md
- features/encrypt/spring/spring-namespace/src/test/java/org/apache/shardingsphere/encrypt/spring/namespace/EncryptSpringNamespaceTest.java
- features/encrypt/spring/spring-namespace/src/test/resources/META-INF/spring/encrypt-application-context.xml
-Update spring-namespace rules on encrypt document and spring-namespace test
---
> Update spring-namespace rules on encrypt document and spring-namespace test

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLInt2BinaryProtocolValue.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLInt2BinaryProtocolValueTest.java
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/tbl/insert_min_values_into_single_table_integer.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/tbl/insert_negative_values_into_single_table_integer.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dml-integration-test-cases.xml
> Fix PostgreSQL int2 negative value decoding incorrect

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java
- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/ProjectionsContext.java
- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngine.java
- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionsContextEngine.java
- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/ShorthandProjection.java
- infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngineTest.java
Ref #21768.
- Revise pr 21768
---
> Revise pr 21768

- sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussDMLStatementSQLVisitor.java
- sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
- sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLDMLStatementSQLVisitor.java
- sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/ReturningSegment.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/InsertStatementHandler.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/opengauss/dml/OpenGaussInsertStatement.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/postgresql/dml/PostgreSQLInsertStatement.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/segment/returning/ReturningClauseAssert.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/dml/impl/InsertStatementAssert.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/cases/parser/domain/segment/impl/insert/ExpectedReturningClause.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/cases/parser/domain/statement/dml/InsertStatementTestCase.java
- test/parser/src/main/resources/case/dml/insert.xml
- test/parser/src/main/resources/sql/supported/dml/insert.xml
> Parse RETURNING clause of PostgreSQL/openGauss Insert

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding.en.md
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleStatementUpdater.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/DropShardingTableRuleStatementUpdaterTest.java
- features/sharding/distsql/parser/src/main/antlr4/imports/sharding/RDLStatement.g4
- features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java
- features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/statement/DropShardingTableRuleStatement.java
For #22358.
- Remove unused algorithms while removing the sharding table rule
- Update document
---
> Improve DistSQL DROP SHARDING TABLE RULE

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/ddl/fetch/FetchStreamMergedResult.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/cursor/OpenGaussCursorTestCase.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/engine/command/CursorSQLCommand.java
- test/integration-test/transaction/src/test/resources/env/common/cursor-command.xml
- test/integration-test/transaction/src/test/resources/env/scenario/cursor/data/actual/init-sql/opengauss/01-actual-init.sql
Fixes #21421.
- Fix cursor wasNull usage and add test cases
-
-
---
> Fix cursor wasNull usage and add test cases(#21421)

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLRowDescriptionPacket.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLRowDescriptionPacketTest.java
- proxy/frontend/opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/command/query/simple/OpenGaussComQueryExecutor.java
- proxy/frontend/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/JDBCPortal.java
- proxy/frontend/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutor.java
- proxy/frontend/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/simple/PostgreSQLComQueryExecutor.java
> Remove unnecessary field in PostgreSQLRowDescriptionPacket

- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngine.java
- infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngineTest.java
- test/integration-test/test-suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
Ref #22355.
- support PostgreSQL, openGauss join statement with using condition
- add unit test for ProjectionEngine
- add integration test case for PostgreSQL, openGauss
---
> Support PostgreSQL, openGauss join statement with using condition

- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropEncryptRuleStatementUpdater.java
- features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropEncryptRuleStatementUpdaterTest.java
For #22358 .
- Improve DROP ENCRYPT RULE, remove unused algorithms while dropping rule
- Supplementary related test cases
---
> Improve DistSQL DROP ENCRYPT RULE

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow.en.md
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropShadowRuleStatementUpdater.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/DropShadowRuleStatementUpdaterTest.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleStatementUpdater.java
For #22358.
- Remove unused algorithms while dropping a shadow rule
- Update document
---
> Improve DistSQL DROP SHADOW RULE

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/ddl/fetch/FetchStreamMergedResult.java
- infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/type/memory/AbstractMemoryQueryResult.java
- test/integration-test/transaction/src/test/java/org/apache/shardingsphere/integration/transaction/cases/cursor/OpenGaussCursorTestCase.java
- test/integration-test/transaction/src/test/resources/env/common/cursor-command.xml
- test/integration-test/transaction/src/test/resources/env/scenario/cursor/data/actual/init-sql/opengauss/01-actual-init.sql
Fixes #21421.
- Fix cursor wasNull usage and test cases
---
> Fix cursor wasNull usage and test cases(#21421)

- test/integration-test/showprocesslist/src/test/java/org/apache/shardingsphere/test/integration/showprocesslist/engine/ShowProcessListIT.java
- Use more precise assert
-
-
---
> Use more precise assert.

- sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
- sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
- sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/table/JoinTableSegment.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/segment/table/TableAssert.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/cases/parser/domain/segment/impl/table/ExpectedJoinTable.java
- test/parser/src/main/resources/case/dml/select-join.xml
- test/parser/src/main/resources/sql/supported/dml/select-join.xml
Ref #22359.
- optimize MySQL, PostgreSQL and openGauss natural join sql parse
---
> Optimize MySQL, PostgreSQL and openGauss natural join sql parse

- docs/community/content/involved/conduct/code.cn.md
- docs/community/content/involved/conduct/code.en.md
- Update unit test specification documentation
---
> Update unit test specification documentation

- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/encrypt.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/encrypt.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/mix.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/mix.en.md
-Update spring-namespace rules on encrypt document
---
> Update yaml-config rules on encrypt document

- test/integration-test/test-suite/src/test/java/org/apache/shardingsphere/test/integration/cases/value/SQLValue.java
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/passthrough/insert_max_floating_point_values.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/passthrough/insert_min_floating_point_values.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/passthrough/insert_negative_infinity_floating_point_values.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dataset/passthrough/insert_positive_infinity_floating_point_values.xml
- test/integration-test/test-suite/src/test/resources/cases/dml/dml-integration-test-cases.xml
- test/integration-test/test-suite/src/test/resources/env/scenario/passthrough/data/actual/dataset.xml
- test/integration-test/test-suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/mysql/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/opengauss/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/postgresql/01-actual-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/mysql/01-expected-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/opengauss/01-expected-init.sql
- test/integration-test/test-suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/postgresql/01-expected-init.sql
Related to #14899.
Some test cases require fixing #22407.
> Add floating point data type cases for PostgreSQL/openGauss

- kernel/sql-federation/optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLOptimizeEngineTest.java
- kernel/sql-federation/optimizer/src/test/resources/cases/federation-query-sql-cases.xml
Ref  #19937.
- modify case code style
- add schema information in optimization test cases.
---
> 19937 federation optimization 20221121

- sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
- sql-parser/dialect/postgresql/src/main/antlr4/imports/postgresql/DMLStatement.g4
- sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
- test/parser/src/main/resources/case/dml/select.xml
- test/parser/src/main/resources/sql/supported/dml/select.xml
> Update openGauss SQL statement visitor

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt.en.md
- test/integration-test/discovery/src/test/java/org/apache/shardingsphere/test/integration/discovery/cases/base/BaseITCase.java
- test/integration-test/discovery/src/test/java/org/apache/shardingsphere/test/integration/discovery/cases/mysql/MySQLMGRPrimaryDataSourceChangedIT.java
-Update distsql-rdl rules on encrypt document 
-Format code
---
> Update distsql-rdl rules on encrypt document and Format code

- infra/common/src/main/java/org/apache/shardingsphere/infra/config/props/ConfigurationPropertyKey.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/event/ShardingSphereSchemaDataAlteredEvent.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/data/swapper/YamlShardingSphereTableDataSwapper.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataScheduleCollector.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataCollectorFixture.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataCollectorTest.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/persist/data/ShardingSphereDataPersistService.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/ClusterContextManagerBuilder.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/metadata/subscriber/ShardingSphereSchemaDataRegistrySubscriber.java
For #22052.
- Make proxy collected data rows partition configurable.
---
> Make proxy collected data rows partition configurable.

- mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/persist/data/ShardingSphereDataPersistService.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/RegistryCenter.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/metadata/subscriber/ShardingSphereSchemaDataRegistrySubscriber.java
For #22052.
- Use distribution lock to persist sys_data table.
---
> Use distribution lock to persist sys_data table.

- kernel/sql-federation/optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLOptimizeEngineTest.java
- kernel/sql-federation/optimizer/src/test/resources/cases/federation-query-sql-cases.xml
Ref #19937.
- add optimization test
> 19937 federation optimization test 20221128

- kernel/traffic/distsql/parser/src/main/antlr4/imports/traffic/Keyword.g4
- kernel/traffic/distsql/parser/src/main/antlr4/imports/traffic/RALStatement.g4
- kernel/transaction/distsql/parser/src/main/antlr4/imports/transaction/Keyword.g4
- kernel/transaction/distsql/parser/src/main/antlr4/imports/transaction/RALStatement.g4
- test/parser/src/main/resources/case/ral/updatable.xml
- test/parser/src/main/resources/sql/supported/ral/updatable.xml
The seventh task of #22456 
---
> Optimize global-rule-DistSQL

- infra/common/src/main/java/org/apache/shardingsphere/infra/config/props/ConfigurationPropertyKey.java
- test/integration-test/test-suite/src/test/resources/env/common/cluster/proxy/conf/server.yaml
For #22052.
- Default open sys_data collector.
---
> Default open sys_data collector.

- docs/document/content/user-manual/shardingsphere-jdbc/spring-boot-starter/mode.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/spring-boot-starter/mode.en.md
> update the mode of boot starter

- kernel/data-pipeline/cdc/client/pom.xml
- kernel/data-pipeline/cdc/core/pom.xml
- kernel/data-pipeline/cdc/protocol/pom.xml
Part of #22500.
- Add pipeline cdc sub-modules
---
> Add pipeline cdc sub-modules

- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-boot-example/pom.xml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-boot-example/src/main/java/org/apache/shardingsphere/example/transaction/xa/spring/boot/XAOrderService.java
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-boot-example/src/main/resources/application-sharding-databases-tables.properties
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-boot-example/src/main/resources/application-sharding-databases.properties
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-boot-example/src/main/resources/application-sharding-tables.properties
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-boot-example/src/main/resources/sharding-databases-tables.yaml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-boot-example/src/main/resources/sharding-databases.yaml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-boot-example/src/main/resources/sharding-tables.yaml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-namespace-example/pom.xml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-namespace-example/src/main/java/org/apache/shardingsphere/example/transaction/xa/spring/namspace/XAOrderService.java
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-namespace-example/src/main/resources/META-INF/application-sharding-databases-tables.xml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-namespace-example/src/main/resources/META-INF/application-sharding-databases.xml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-namespace-example/src/main/resources/META-INF/application-sharding-tables.xml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-namespace-example/src/main/resources/META-INF/sharding-databases-tables.yaml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-namespace-example/src/main/resources/META-INF/sharding-databases.yaml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-2pc-xa-spring-namespace-example/src/main/resources/META-INF/sharding-tables.yaml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-base-seata-spring-boot-example/pom.xml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-base-seata-spring-boot-example/src/main/java/org/apache/shardingsphere/example/transaction/base/seata/spring/boot/SeataATOrderService.java
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-base-seata-spring-boot-example/src/main/resources/application-sharding-databases-tables.properties
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-base-seata-spring-boot-example/src/main/resources/application-sharding-databases.properties
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-base-seata-spring-boot-example/src/main/resources/application-sharding-tables.properties
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-base-seata-spring-boot-example/src/main/resources/sharding-databases-tables.yaml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-base-seata-spring-boot-example/src/main/resources/sharding-databases.yaml
- examples/shardingsphere-jdbc-example/single-feature-example/transaction-example/transaction-base-seata-spring-boot-example/src/main/resources/sharding-tables.yaml
For #22469.
- Remove `shardingsphere-jdbc-core-spring-boot-starter` from transaction-example
- Remove `shardingsphere-jdbc-core-spring-namespace` from transaction-example
---
> Update transaction-example to use ShardingSphereDriver

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/_index.en.md
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ConsistencyCheckJobPublicAPI.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/GovernanceRepositoryAPI.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/GovernanceRepositoryAPIImpl.java
- kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/DropMigrationCheckUpdater.java
- kernel/data-pipeline/distsql/parser/src/main/antlr4/imports/migration/RALStatement.g4
- kernel/data-pipeline/distsql/parser/src/main/java/org/apache/shardingsphere/migration/distsql/parser/core/MigrationDistSQLStatementVisitor.java
- kernel/data-pipeline/distsql/statement/src/main/java/org/apache/shardingsphere/migration/distsql/statement/DropMigrationCheckStatement.java
- kernel/data-pipeline/scenario/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobAPIImpl.java
- kernel/data-pipeline/scenario/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobId.java
- kernel/data-pipeline/scenario/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckSequence.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/statement/ral/impl/migration/update/DropMigrationCheckStatementAssert.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/cases/parser/jaxb/statement/ral/migration/DropMigrationCheckStatementTestCase.java
- test/parser/src/main/resources/case/ral/migration.xml
- test/parser/src/main/resources/sql/supported/ral/migration.xml
- test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/api/impl/ConsistencyCheckJobAPIImplTest.java
- test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineContextUtil.java
- test/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckSequenceTest.java
- Add DROP MIGRATION CHECK jobId DistSQL and impl
- Refactor consistency check sequence
- Add unit test
---
> Support drop migration consitency check job

- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/ExpressionConverter.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/CaseWhenExpressionConverter.java
- sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
- sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/CaseWhenExpression.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedCaseWhenExpression.java
- test/parser/src/main/resources/case/dml/select-expression.xml
Ref #22528.
- refactor CaseWhenExpression parse logic
---
> Refactor CaseWhenExpression parse logic

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/_index.en.md
> Update syntax document

- sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
- test/optimize/src/test/java/org/apache/shardingsphere/infra/federation/converter/parameterized/engine/SQLNodeConverterEngineParameterizedTest.java
- test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java
- test/parser/src/main/resources/case/dml/select-expression.xml
- test/parser/src/main/resources/sql/supported/dml/select-expression.xml
Ref #22528.
- Support mysql case when then statement parse
---
> Support mysql case when then statement parse

- kernel/sql-federation/optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLOptimizeEngineTest.java
- kernel/sql-federation/optimizer/src/test/resources/cases/federation-query-sql-cases.xml
Fixes #19937.
- Add test case for federation optimization test.
---
> Add test case for federation optimization test.

- db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/admin/MySQLComResetConnectionPacket.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/session/ServerPreparedStatementRegistry.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/session/ServerServerPreparedStatementRegistryTest.java
- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/MySQLCommandExecutorFactory.java
- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/MySQLCommandPacketFactory.java
- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/admin/MySQLComResetConnectionExecutor.java
- proxy/frontend/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/MySQLCommandExecutorFactoryTest.java
- proxy/frontend/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/MySQLCommandPacketFactoryTest.java
- proxy/frontend/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/admin/MySQLComResetConnectionExecutorTest.java
> Proxy support MySQL COM_RESET_CONNECTION

- docs/document/content/user-manual/common-config/builtin-algorithm/encrypt.cn.md
- docs/document/content/user-manual/common-config/builtin-algorithm/encrypt.en.md
- Update encrypt like algorithm document
---
> Update encrypt like algorithm document

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt.en.md
Ref #22494.
-Update distsql-rdl rules on encrypt document
---
> Update distsql-rdl rules on encrypt document

- kernel/transaction/api/src/main/java/org/apache/shardingsphere/transaction/factory/ShardingSphereTransactionManagerFactory.java
- kernel/transaction/api/src/main/java/org/apache/shardingsphere/transaction/spi/ShardingSphereTransactionManager.java
- kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/ShardingSphereTransactionManagerEngine.java
- kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/core/fixture/OtherShardingSphereTransactionManagerFixture.java
- kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/core/fixture/ShardingSphereTransactionManagerFixture.java
- kernel/transaction/type/base/seata-at/src/main/java/org/apache/shardingsphere/transaction/base/seata/at/SeataATShardingSphereTransactionManager.java
- kernel/transaction/type/base/seata-at/src/test/java/org/apache/shardingsphere/transaction/base/seata/at/SeataATShardingSphereTransactionManagerTest.java
- kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/XAShardingSphereTransactionManager.java
- kernel/transaction/type/xa/core/src/test/java/org/apache/shardingsphere/transaction/xa/XAShardingSphereTransactionManagerTest.java
Fixes #22567.
- Move ShardingSphereTransactionManager to api module
---
> Move ShardingSphereTransactionManager to api module(#22567)

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/data/ShardingStatisticsTableCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/builder/dialect/MySQLShardingSphereDataBuilder.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/builder/dialect/PostgreSQLShardingSphereDataBuilder.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/tables/PgClassTableCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/tables/PgNamespaceTableCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/event/ShardingSphereSchemaDataAlteredEvent.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/data/pojo/YamlShardingSphereTableData.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/data/swapper/YamlShardingSphereTableDataSwapper.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataScheduleCollector.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataCollectorFixture.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataCollectorTest.java
- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/row/MemoryEnumerator.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/MetaDataContexts.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/persist/data/ShardingSphereDataPersistService.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/persist/node/ShardingSphereDataNode.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/ClusterContextManagerBuilder.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/data/ShardingSphereDataChangedWatcher.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/data/event/ShardingSphereRowDataChangedEvent.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/data/event/ShardingSphereRowDataDeletedEvent.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/data/event/TableDataChangedEvent.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/metadata/subscriber/ShardingSphereSchemaDataRegistrySubscriber.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/DatabaseChangedSubscriber.java
For #22052.
- Optimize sys_data watch event & remove ShardingSphereTableData#columns.
---
> Optimize sys_data watch event & remove ShardingSphereTableData#columns.

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURL.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/ShardingSphereDriverTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURLTest.java
- jdbc/core/src/test/resources/config/driver/foo-driver-fixture.yaml
Related to #22557.
- Fix ShardingSphereDriverURL.toConfigurationBytes ignore newline
- Improve ShardingSphereDriverTest. Do real test, make sure driver works
---
> Revise 22557

- docs/document/content/user-manual/shardingsphere-proxy/migration/usage.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/migration/usage.en.md
- Refining the documentation for migration permissions
---
> Refining the documentation for migration permissions

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/standard/ShardingStandardRoutingEngine.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintUtils.java
- Code little optimized.
-
-
---
> Code little optimized.

- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/alter-sharding-table-reference-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/alter-sharding-table-reference-rule.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/create-sharding-table-reference-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/create-sharding-table-reference-rule.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/drop-sharding-table-reference-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/drop-sharding-table-reference-rule.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding.en.md
Fixes #22371.
Update documents for sharding table reference rule.
> Update documents for sharding table reference rule.

- docs/document/content/user-manual/shardingsphere-proxy/migration/usage.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/migration/usage.en.md
Relation #22585
- Add refer link at migration document
---
> Add refer link at migration document

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/data/ShardingStatisticsTableCollector.java
- test/integration-test/test-suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/mysql/select_sharding_table_statistics.xml
- test/integration-test/test-suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/opengauss/select_sharding_table_statistics.xml
- test/integration-test/test-suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/postgresql/select_sharding_table_statistics.xml
- test/integration-test/test-suite/src/test/resources/cases/ral/dataset/empty_rules/standalone/select_sharding_table_statistics.xml
- test/integration-test/test-suite/src/test/resources/cases/ral/ral-integration-test-cases.xml
- Optimize ShardingStatisticsTableCollector & add it.
---
> Optimize ShardingStatisticsTableCollector & add it.

- features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/DropDatabaseDiscoveryRuleStatementUpdater.java
- features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/DropDatabaseDiscoveryRuleStatementUpdaterTest.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropShadowRuleStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropBroadcastTableRuleStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropDefaultStrategyStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleStatementUpdater.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/DropBroadcastTableRuleStatementUpdaterTest.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/DropDefaultShardingStrategyStatementUpdaterTest.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/DropShardingTableRuleStatementUpdaterTest.java
Remove empty rule configuration after drop rule.
> Remove empty rule configuration after drop rule.

- infra/common/src/main/java/org/apache/shardingsphere/infra/config/props/ConfigurationPropertyKey.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/config/props/internal/InternalConfigurationProperties.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/config/props/internal/InternalConfigurationPropertyKey.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaData.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataJobWorker.java
> Add InternalConfigurationProperties for inner use.

- test/e2e/agent/plugins/metrics/src/test/assembly/shardingsphere-proxy-agent-metrics-assembly.xml
- test/e2e/agent/plugins/opentelemetry/src/test/assembly/shardingsphere-proxy-agent-opentelemetry-assembly.xml
for #22630 
- fix the issue caused by e2e refactor
---
> Fix : fix the issue caused by e2e refactor

- docs/document/content/reference/distsql/syntax/rql/rule-query/sharding/show-sharding-table-reference-rules.cn.md
- docs/document/content/reference/distsql/syntax/rql/rule-query/sharding/show-sharding-table-reference-rules.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/sharding.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/sharding.en.md
- Update docs for Show Sharding Table reference rule
-
-
---
> Update docs for Show Sharding Table reference rule

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/AbstractStreamingDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractSimplePipelineJob.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/datasource/AbstractDataSourcePreparer.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/prepare/datasource/AbstractDataSourcePreparerTest.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJob.java
- Recover methods from public to protected
- Move class from IT to UT module
---
> Recover methods from public to protected; Move class from IT to UT module

- examples/shardingsphere-jdbc-example/single-feature-example/cluster-mode-example/cluster-mode-spring-boot-mybatis-example/src/main/resources/local-zookeeper-readwrite-splitting.yaml
- examples/shardingsphere-jdbc-example/single-feature-example/cluster-mode-example/cluster-mode-spring-boot-mybatis-example/src/main/resources/local-zookeeper-sharding-databases-tables.yaml
- examples/shardingsphere-jdbc-example/single-feature-example/cluster-mode-example/cluster-mode-spring-namespace-mybatis-example/src/main/resources/META-INF/zookeeper/cloud/application-readwrite-splitting.xml
- examples/shardingsphere-jdbc-example/single-feature-example/cluster-mode-example/cluster-mode-spring-namespace-mybatis-example/src/main/resources/META-INF/zookeeper/cloud/application-shadow.xml
- examples/shardingsphere-jdbc-example/single-feature-example/cluster-mode-example/cluster-mode-spring-namespace-mybatis-example/src/main/resources/META-INF/zookeeper/cloud/application-sharding-databases-tables.xml
For #22469.
- Fix cluster-mode-example configuration
---
> Fix cluster-mode-example

- mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/MetaDataContexts.java
For #22052.
- Optimize init ShardingSphereData logic.
---
> Optimize init ShardingSphereData logic.

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/single-table.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/single-table.en.md
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/rule/SingleTableQueryResultSet.java
- test/e2e/suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/alter_single_table_rules.xml
- test/e2e/suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/cluster/alter_single_table_rules.xml
- test/e2e/suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/cluster/create_single_table_rules.xml
- test/e2e/suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/cluster/drop_single_table_rules.xml
- test/e2e/suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/create_single_table_rules.xml
- test/e2e/suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/drop_single_table_rules.xml
- test/e2e/suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/standalone/alter_single_table_rules.xml
- test/e2e/suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/standalone/create_single_table_rules.xml
- test/e2e/suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/standalone/drop_single_table_rules.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/db/show_single_table.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/db/show_single_tables.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting/show_single_table.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting/show_single_tables.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting_and_encrypt/show_single_table.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting_and_encrypt/show_single_tables.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/encrypt/show_single_table.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/encrypt/show_single_tables.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/encrypt_and_readwrite_splitting/show_single_table.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/encrypt_and_readwrite_splitting/show_single_tables.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/sharding_and_encrypt/show_single_table.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/sharding_and_encrypt/show_single_tables.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/sharding_governance/mysql/show_single_table.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/sharding_governance/mysql/show_single_tables.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/tbl/show_single_table.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/tbl/show_single_tables.xml
For #21659.
Change `resource_name` to `storage_unit_name` for single table.
> Change `resource_name` to `storage_unit_name` for single table.

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding.en.md
> Fix document reference

- agent/bootstrap/src/main/java/org/apache/shardingsphere/agent/bootstrap/ShardingSphereAgent.java
- agent/core/src/main/java/org/apache/shardingsphere/agent/core/plugin/AgentPluginLoader.java
Fixes #22689.
-  fix agent loading plugin definition error
---
> fix agent loading plugin definition error

- docs/community/content/involved/release/shardingsphere.cn.md
- docs/community/content/involved/release/shardingsphere.en.md
> Update release guide for ShardingSphere about Spring

- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/alter-sharding-table-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/alter-sharding-table-rule.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/create-sharding-table-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/sharding/create-sharding-table-rule.en.md
- Update DistSQL audit related document
---
> Update DistSQL audit related document

- docs/community/content/involved/release/shardingsphere-on-cloud.cn.md
- docs/community/content/involved/release/shardingsphere-on-cloud.en.md
- release doc update for generate index.yaml and upload tgz file
-
-
> feat(release): release doc update

- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdater.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/distsql/exception/resource/EmptyResourceException.java
Fixes #22699.
- fix create encrypt rule error when no storage nodes
---
> fix create encrypt rule error when no storage nodes

- .github/workflows/e2e.yml
- .github/workflows/nightly-e2e.yml
for #22695.
- remove a variable in github action
---
> Refactor : remove a variable in github action

- docs/document/content/user-manual/shardingsphere-proxy/migration/usage.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/migration/usage.en.md
- Add heterogeneous migration example for openGauss
- Rename resources to storage units
---
> Add heterogeneous migration example for openGauss

- infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/state/DataSourceStateManager.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/state/exception/UnavailableDataSourceException.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/MetadataContextsFactory.java
- Fix exception info missing when data source is unavailable
---
> Fix exception info missing when data source is unavailable

- test/e2e/suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
Fixes #22576.
- add more integration test for PostgreSQL and openGauss combine statement
---
> Add more integration test for PostgreSQL and openGauss combine statement

- examples/README.md
- examples/README_ZH.md
For #12366.
- update the example module docs
---
> update the example module docs

- mode/type/cluster/repository/provider/zookeeper/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/ZookeeperRepository.java
- mode/type/cluster/repository/provider/zookeeper/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/props/ZookeeperPropertyKey.java
- proxy/bootstrap/src/main/resources/conf/server.yaml
> Remove ensembleTracker configuration

- .github/workflows/nightly-build-example.yml
Fixes #22757.
- disable the example upload action temporarily
---
> Refactor : disable the example upload action temporarily (#22757)

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataScheduleCollector.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataCollectorTest.java
- Fix occasional test exceptions for ShardingSphereDataCollectorTest.
> Fix occasional test exceptions for ShardingSphereDataCollectorTest.

- distsql/parser/src/main/antlr4/imports/Keyword.g4
- distsql/parser/src/main/antlr4/imports/RQLStatement.g4
- distsql/parser/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java
- distsql/statement/src/main/java/org/apache/shardingsphere/distsql/parser/statement/rql/show/ShowSingleTableStatement.java
- docs/document/content/reference/distsql/syntax/rql/rule-query/single-table/show-single-table.cn.md
- docs/document/content/reference/distsql/syntax/rql/rule-query/single-table/show-single-table.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/single-table.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/single-table.en.md
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/rule/SingleTableQueryResultSet.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/SingleTableQueryResultSetTest.java
> Add like literal for show single table statement

- examples/shardingsphere-example-generator/src/main/resources/template/jdbc/resources/yaml/feature/sharding.ftl
- Fix JDBC sharding config template
---
> Fix example generator

- .github/workflows/nightly-build-example.yml
Fixes #22757.
- add back the example upload 
---
> Add : add back the example upload since the permission has been granted by apache infra team

- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/ha.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/ha.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/mix.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/mix.en.md
Update indentation of ruleConfigs.
---
> Update document format.

- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFirstNLastMMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFromXToYMaskAlgorithm.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/KeepFirstNLastMMaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/KeepFromXToYMaskAlgorithmTest.java
Ref #22776.
- Revise pr 22776 for code style
---
> Revise pr 22776 for code style

- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFirstNLastMMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFromXToYMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFirstNLastMMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFromXToYMaskAlgorithm.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFirstNLastMMaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFromXToYMaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFirstNLastMMaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFromXToYMaskAlgorithmTest.java
Ref #22808.
- revise pr 22808 for code style
---
> Revise pr 22808 for code style

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- infra/common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintDataSourceNotExistsException.java
- infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/impl/PartialSQLRouteExecutor.java
- Add SQL Hint data source not exists exception
---
> Add SQL Hint data source not exists exception(#22849)

- infra/util/src/test/java/org/apache/shardingsphere/infra/util/retry/RetryExecutorTest.java
- infra/util/src/test/java/org/apache/shardingsphere/infra/util/retry/fixture/RetryFunctionFixture.java
Signed-off-by: Junfeng <i@jacob953.com>
Fixes #22709.
- Add test cases of RetryExecutor
---
> Add test cases of RetryExecutor

- docs/document/content/reference/distsql/syntax/rdl/rule-definition/shadow/create-default-shadow-algorithm.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/shadow/create-default-shadow-algorithm.en.md
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/CreateDefaultShadowAlgorithmStatementUpdater.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropDefaultShadowAlgorithmStatementUpdater.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/DropDefaultShadowAlgorithmStatementUpdaterTest.java
Fix DROP DEFAULT SHADOW ALGORITHM.
before:
after:
---
> Fix DROP DEFAULT SHADOW ALGORITHM.

- docs/document/content/reference/distsql/syntax/rdl/rule-definition/encrypt/alter-encrypt-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/encrypt/alter-encrypt-rule.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/encrypt/create-encrypt-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/encrypt/create-encrypt-rule.en.md
- docs/document/content/reference/distsql/syntax/rdl/storage-unit-definition/alter-storage-unit.cn.md
- docs/document/content/reference/distsql/syntax/rdl/storage-unit-definition/alter-storage-unit.en.md
- docs/document/content/reference/distsql/syntax/rdl/storage-unit-definition/register-storage-unit.cn.md
- docs/document/content/reference/distsql/syntax/rdl/storage-unit-definition/register-storage-unit.en.md
For #22135.
Update documents of encrypt DistSQL.
> Update documents of encrypt DistSQL.

- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/task/InventoryTaskTest.java
link ci error: https://github.com/apache/shardingsphere/actions/runs/3709680170
- Fix occasional ci error at InventoryTaskTest
---
> Fix occasional ci error at InventoryTaskTest

- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/constant/DatabaseDiscoveryOrder.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/constant/ReadwriteSplittingOrder.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/constant/ShadowOrder.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/task/MySQLIncrementTask.java
Ref #22759.
- modify datasource rule order for mask feature
---
> Modify datasource rule order for mask feature

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
For #20736 .
- optimize JDBC SQL hint.
> Optimize JDBC SQL hint.

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/checker/ShardingTableRuleStatementChecker.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/enums/ShardingStrategyType.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/checker/ShardingRuleStatementCheckerTest.java
Fixes #22925.
- Correct error message for sharding strategy type
---
> Correct error message for sharding strategy type

- agent/bootstrap/pom.xml
- agent/distribution/src/main/assembly/shardingsphere-agent-binary-distribution.xml
- agent/plugins/pom.xml
- docs/document/content/user-manual/shardingsphere-proxy/observability/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/observability/_index.en.md
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/ClusterContextManagerBuilder.java
- pom.xml
Fixes #22966.
- refactor shade package `org.apache.shardingsphere.dependencies` to `org.apache.shardingsphere.shade`
- remove useless `dependency-reduced-pom.xml` file which generated by shade plugin
- add release version for agent artifact
---
> Refactor agent

- distribution/proxy-native/src/main/release-docs/LICENSE
- distribution/proxy/src/main/release-docs/LICENSE
> Update LICENSE for Netty dependencies

- docs/community/content/team/_index.cn.md
- docs/community/content/team/_index.en.md
- Add Everly under the committer section.
> Document: Update Teams Page

- docs/document/content/reference/distsql/syntax/rdl/rule-definition/readwrite-splitting/alter-readwrite-splitting-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/readwrite-splitting/alter-readwrite-splitting-rule.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/readwrite-splitting/create-readwrite-splitting-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/readwrite-splitting/create-readwrite-splitting-rule.en.md
Fixes #22984.
- update DistSQL Create readwrite_splitting rule document
- update DistSQL Alter readwrite_splitting rule document
---
> Update document for DistSql readwrite_splitting

- distsql/parser/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java
- features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java
- kernel/data-pipeline/distsql/parser/src/main/java/org/apache/shardingsphere/migration/distsql/parser/core/MigrationDistSQLStatementVisitor.java
- kernel/traffic/distsql/parser/src/main/java/org/apache/shardingsphere/traffic/distsql/parser/core/TrafficDistSQLStatementVisitor.java
- kernel/transaction/distsql/parser/src/main/java/org/apache/shardingsphere/transaction/distsql/parser/core/TransactionDistSQLStatementVisitor.java
- Change `if` to Conditional Operator `? :`
---
> Refactor DistSQL visitors

- distsql/statement/src/main/java/org/apache/shardingsphere/distsql/parser/statement/rdl/create/CreateRuleStatement.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/CreateDefaultShadowAlgorithmStatementUpdater.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/CreateDefaultShadowAlgorithmStatementUpdaterTest.java
- features/shadow/distsql/parser/src/main/antlr4/imports/shadow/Keyword.g4
- features/shadow/distsql/parser/src/main/antlr4/imports/shadow/RDLStatement.g4
- features/shadow/distsql/parser/src/main/java/org/apache/shardingsphere/shadow/distsql/parser/core/ShadowDistSQLStatementVisitor.java
- features/shadow/distsql/statement/src/main/java/org/apache/shardingsphere/shadow/distsql/parser/statement/CreateDefaultShadowAlgorithmStatement.java
For #22844 , add IF NOT EXISTS to CREATE DEFAULT SHADOW ALGORITHM.
---
> Add IF NOT EXISTS to CREATE DEFAULT SHADOW ALGORITHM.

- sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
- sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
- sql-parser/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/impl/OracleStatementSQLVisitor.java
- sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
- sql-parser/dialect/sql92/src/main/java/org/apache/shardingsphere/sql/parser/sql92/visitor/statement/impl/SQL92StatementSQLVisitor.java
- sql-parser/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/impl/SQLServerStatementSQLVisitor.java
- test/it/parser/src/main/resources/case/dml/call.xml
- test/it/parser/src/main/resources/case/dml/select-expression.xml
- test/it/parser/src/main/resources/case/dml/select-with.xml
- test/it/parser/src/main/resources/case/dml/select.xml
- test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/update/update.xml
- Fix update where cipher column is null not rewrite.
---
> Fix update where cipher column is null not rewrite.

- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClient.java
Fixes #23055.
- Fix nioEventLoop leakage at pipeline
---
> Fix nioEventLoop leakage at pipeline

- mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
> Fix create table throws npe

- db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLCharacterSet.java
- distsql/parser/src/main/java/org/apache/shardingsphere/distsql/parser/engine/api/DistSQLStatementParserEngine.java
- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/algorithm/DatabaseDiscoveryEngine.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/like/CharDigestLikeEncryptAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/impl/InsertClauseShardingConditionEngine.java
- infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/util/ResultSetUtil.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/DriverDataSourceCache.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataScheduleCollector.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/util/PostgreSQLPipelineFreemarkerManager.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- mode/type/standalone/repository/provider/jdbc/core/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/JDBCRepository.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/mysql/executor/MySQLSetCharsetExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/postgresql/PostgreSQLCharacterSets.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/enums/VariableEnum.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableHandler.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/BackendConnectionTest.java
- test/e2e/showprocesslist/src/test/java/org/apache/shardingsphere/test/e2e/showprocesslist/engine/ShowProcessListE2EIT.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/engine/dql/BaseDQLE2EIT.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/classictransfer/ClassicTransferTestCase.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/readonly/MySQLSetReadOnlyTestCase.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/readonly/PostgreSQLSetReadOnlyTestCase.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/savepoint/PostgreSQLSavePointTestCase.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/truncate/MySQLXATruncateTestCase.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/execute/ExecuteEngineTest.java
> Add final to exception.

- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/MetaDataRefreshEngine.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/MetaDataRefresher.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/AlterIndexStatementSchemaRefresher.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/AlterSchemaStatementSchemaRefresher.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/AlterTableStatementSchemaRefresher.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/AlterViewStatementSchemaRefresher.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/CreateIndexStatementSchemaRefresher.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/CreateSchemaStatementSchemaRefresher.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/CreateTableStatementSchemaRefresher.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/CreateViewStatementSchemaRefresher.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/DropIndexStatementSchemaRefresher.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/DropSchemaStatementSchemaRefresher.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/DropTableStatementSchemaRefresher.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/DropViewStatementSchemaRefresher.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/refresher/type/RenameTableStatementSchemaRefresher.java
- infra/context/src/test/java/org/apache/shardingsphere/infra/context/refresher/MetaDataRefreshEngineTest.java
- infra/context/src/test/java/org/apache/shardingsphere/infra/context/refresher/fixture/MetaDataRefresherFixture.java
- infra/context/src/test/java/org/apache/shardingsphere/infra/context/refresher/type/RenameTableStatementSchemaRefresherTest.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/DriverJDBCExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/DatabaseCommunicationEngine.java
> MetaDataRefreshEngine add modeContextManager field

- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/CreateShadowRuleStatementUpdater.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/CreateShadowRuleStatementUpdaterTest.java
- features/shadow/distsql/parser/src/main/antlr4/imports/shadow/RDLStatement.g4
- features/shadow/distsql/parser/src/main/java/org/apache/shardingsphere/shadow/distsql/parser/core/ShadowDistSQLStatementVisitor.java
- features/shadow/distsql/statement/src/main/java/org/apache/shardingsphere/shadow/distsql/parser/statement/CreateShadowRuleStatement.java
For #22844 , add IF NOT EXISTS to CREATE SHADOW RULE.
---
> Add IF NOT EXISTS to CREATE SHADOW RULE.

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/checker/ShardingTableRuleStatementChecker.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateShardingTableRuleStatementUpdater.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/checker/ShardingRuleStatementCheckerTest.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/CreateShardingTableRuleStatementUpdaterTest.java
- features/sharding/distsql/parser/src/main/antlr4/imports/sharding/Keyword.g4
- features/sharding/distsql/parser/src/main/antlr4/imports/sharding/RDLStatement.g4
- features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java
- features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/statement/CreateShardingTableRuleStatement.java
The second task of #22844.
- Add IF NOT EXISTS for create sharding table rule
---
> Add `IF NOT EXISTS` for `create sharding table rule`

- features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/checker/ReadwriteSplittingRuleStatementChecker.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/checker/ShadowRuleStatementChecker.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/converter/ShadowRuleStatementConverter.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/supporter/ShadowRuleStatementSupporter.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/AlterDefaultShadowAlgorithmStatementUpdater.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/AlterShadowRuleStatementUpdater.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/CreateShadowRuleStatementUpdater.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropDefaultShadowAlgorithmStatementUpdater.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropShadowAlgorithmStatementUpdater.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropShadowRuleStatementUpdater.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/AlterShadowRuleStatementUpdaterTest.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/DatabaseDiscoveryRuleConfigurationImportChecker.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/ReadwriteSplittingRuleConfigurationImportChecker.java
Revise #23086,
optimize some parameters and method naming.
---
> Revise #23086, optimize some parameters and method naming.

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ExecuteEngine.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryIncrementalTasksRunner.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/execute/ExecuteEngineTest.java
- Add ExecuteEngine.trigger
---
> Add ExecuteEngine.trigger

- infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/dml/InsertStatementContextTest.java
- infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementContextTest.java
> Correct unit test package in shardingsphere-infra-binder

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/event/handler/PipelineChangedJobConfigurationProcessor.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/event/handler/impl/ChangedJobConfigurationDispatcher.java
- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/metadata/processor/ConsistencyCheckChangedJobConfigurationProcessor.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/metadata/processor/MigrationChangedJobConfigurationProcessor.java
- Replace `DataChangedEvent.Type` to `Type`
- Replace `JobConfigurationPOJO` to `JobConfiguration`
---
> Refactor PipelineChangedJobConfigurationProcessor.process parameter

- infra/util/src/main/java/org/apache/shardingsphere/infra/util/spi/type/ordered/cache/OrderedServicesCache.java
- infra/util/src/test/java/org/apache/shardingsphere/infra/util/spi/type/ordered/cache/OrderedServicesCacheTest.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/CacheEvictedSubscriber.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/ContextManagerSubscriberFacade.java
- mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/CacheEvictedSubscriberTest.java
- mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneModeContextManager.java
> Clear service cache when any configuration changed

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateShardingTableReferenceRuleStatementUpdater.java
- proxy/bootstrap/src/main/resources/conf/config-mask.yaml
Ref #22759.
- Add mask default configuration in Proxy Adapter
---
> Add mask default configuration in Proxy Adapter

- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/impl/CDCJobAPIImpl.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/job/CDCJob.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/prepare/CDCJobPreparer.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/GovernanceRepositoryAPI.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/InventoryIncrementalJobAPI.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/PipelineJobAPI.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractInventoryIncrementalJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/GovernanceRepositoryAPIImpl.java
- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJob.java
- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/impl/ConsistencyCheckJobAPI.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJob.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/prepare/MigrationJobPreparer.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/cdc/fixture/FixtureCDCJobAPI.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/api/impl/GovernanceRepositoryAPIImplTest.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/api/impl/MigrationJobAPITest.java
- Refactor GovernanceRepositoryAPI.getJobItemProgress return Optional
- Refactor PipelineJobAPI.getJobItemProgress return Optional
---
> Refactor pipeline getJobItemProgress return Optional

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateDefaultShardingStrategyStatementUpdater.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/CreateDefaultShardingStrategyStatementUpdaterTest.java
- features/sharding/distsql/parser/src/main/antlr4/imports/sharding/RDLStatement.g4
- features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java
- features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/statement/CreateDefaultShardingStrategyStatement.java
The fifth task of #22844.
- Add `IF NOT EXISTS` to `create default sharding strategy`
---
> Add `IF NOT EXISTS` to `create default sharding strategy`

- mode/type/standalone/core/src/test/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneContextManagerBuilderTest.java
- mode/type/standalone/core/src/test/java/org/apache/shardingsphere/mode/manager/standalone/subscriber/ProcessStandaloneSubscriberTest.java
> Correct tests name and package in standalone-mode-core

- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleStatementUpdater.java
- features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleStatementUpdaterTest.java
- Fix DistSQL ALTER ENCRYPT RULE
- Add related unit test
---
> Fix DistSQL ALTER ENCRYPT RULE

- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdater.java
- features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdaterTest.java
- features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/Keyword.g4
- features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/RDLStatement.g4
- features/encrypt/distsql/parser/src/main/java/org/apache/shardingsphere/encrypt/distsql/parser/core/EncryptDistSQLStatementVisitor.java
- features/encrypt/distsql/statement/src/main/java/org/apache/shardingsphere/encrypt/distsql/parser/statement/CreateEncryptRuleStatement.java
The sixth task of #22844.
- Add `IF NOT EXISTS` to `create encrypt rule`
---
> Add `IF NOT EXISTS` to `create encrypt rule`

- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/MaskAlgorithmUtil.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFirstNLastMMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFromXToYMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskAfterSpecialCharsAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskBeforeSpecialCharsAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFirstNLastMMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFromXToYMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/exception/MaskSQLException.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/exception/algorithm/MaskAlgorithmInitializationException.java
- features/mask/core/src/main/resources/META-INF/services/org.apache.shardingsphere.mask.spi.MaskAlgorithm
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFirstNLastMMaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFromXToYMaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskAfterSpecialCharsAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskBeforeSpecialCharsAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFirstNLastMMaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFromXToYMaskAlgorithmTest.java
Ref #22759.
- Optimize mask algorithm logic and add MaskAlgorithmInitializationException
---
> Optimize mask algorithm logic and add MaskAlgorithmInitializationException

- features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/checker/ReadwriteSplittingRuleStatementChecker.java
- features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/CreateReadwriteSplittingRuleStatementUpdater.java
- features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/CreateReadwriteSplittingRuleStatementUpdaterTest.java
- features/readwrite-splitting/distsql/parser/src/main/antlr4/imports/readwrite-splitting/Keyword.g4
- features/readwrite-splitting/distsql/parser/src/main/antlr4/imports/readwrite-splitting/RDLStatement.g4
- features/readwrite-splitting/distsql/parser/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/parser/core/ReadwriteSplittingDistSQLStatementVisitor.java
- features/readwrite-splitting/distsql/statement/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/parser/statement/CreateReadwriteSplittingRuleStatement.java
For #22844 , add IF NOT EXISTS to CREATE READWRITE_SPLITTING RULE.
---
> Add IF NOT EXISTS to CREATE READWRITE_SPLITTING RULE.

- db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/MySQLColumnDefinitionFlag.java
- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java
- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/builder/ResponsePacketBuilder.java
- proxy/frontend/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutorTest.java
> Set proper column definition flag for MySQL COM_STMT_PREPARE

- features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleStatementUpdaterTest.java
- Revise unit test method name
---
> Revise unit test method name

- features/mask/core/src/main/java/org/apache/shardingsphere/mask/merge/MaskResultDecoratorEngine.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/merge/dql/MaskAlgorithmMetaData.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/yaml/swapper/YamlMaskRuleConfigurationSwapper.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/yaml/swapper/rule/YamlMaskTableRuleConfigurationSwapper.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/merge/dql/MaskAlgorithmMetaDataTest.java
- proxy/bootstrap/src/main/resources/conf/config-mask.yaml
Ref #22759.
- optimize data mask result decorator logic and code style
---
> Optimize data mask result decorator logic and code style

- features/mask/distsql/handler/pom.xml
- features/mask/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
- features/mask/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.update.RuleDefinitionUpdater
- features/mask/distsql/parser/pom.xml
- features/mask/distsql/parser/src/main/antlr4/imports/mask/Alphabet.g4
- features/mask/distsql/parser/src/main/antlr4/imports/mask/BaseRule.g4
- features/mask/distsql/parser/src/main/antlr4/imports/mask/Keyword.g4
- features/mask/distsql/parser/src/main/antlr4/imports/mask/Literals.g4
- features/mask/distsql/parser/src/main/antlr4/imports/mask/RDLStatement.g4
- features/mask/distsql/parser/src/main/antlr4/imports/mask/RQLStatement.g4
- features/mask/distsql/parser/src/main/antlr4/imports/mask/Symbol.g4
- features/mask/distsql/parser/src/main/antlr4/org/apache/shardingsphere/distsql/parser/autogen/MaskDistSQLStatement.g4
- features/mask/distsql/parser/src/main/java/org/apache/shardingsphere/mask/distsql/parser/core/MaskDistSQLLexer.java
- features/mask/distsql/parser/src/main/java/org/apache/shardingsphere/mask/distsql/parser/core/MaskDistSQLParser.java
- features/mask/distsql/parser/src/main/java/org/apache/shardingsphere/mask/distsql/parser/core/MaskDistSQLStatementVisitor.java
- features/mask/distsql/parser/src/main/java/org/apache/shardingsphere/mask/distsql/parser/facade/MaskDistSQLStatementParserFacade.java
- features/mask/distsql/parser/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.parser.engine.spi.FeaturedDistSQLStatementParserFacade
- features/mask/distsql/pom.xml
- features/mask/distsql/statement/pom.xml
Add g4 file for #23138.
- Add DistSQL syntax to `mask rule`
---
> Add DistSQL syntax to `mask rule`

- test/e2e/agent/plugins/opentelemetry/src/test/assembly/shardingsphere-proxy-agent-opentelemetry-assembly.xml
- test/e2e/agent/plugins/zipkin/src/test/assembly/shardingsphere-proxy-agent-zipkin-assembly.xml
- test/e2e/agent/plugins/zipkin/src/test/resources/docker/docker-compose.yml
- test/e2e/agent/plugins/zipkin/src/test/resources/docker/proxy/conf/agent.yaml
- test/e2e/agent/plugins/zipkin/src/test/resources/docker/proxy/conf/config-db.yaml
- test/e2e/agent/plugins/zipkin/src/test/resources/docker/proxy/conf/logback.xml
- test/e2e/agent/plugins/zipkin/src/test/resources/docker/proxy/conf/server.yaml
for #23135.
- add the Dockerfile and related config for zipkin E2E test.
---
> Add : add docker resource for zipkin docker packaging (#23135)

- docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/mask.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/mask.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/mask.en.md
Ref #22759.
- update some wrong content in data masking document
---
> Update some wrong content in data masking document

- infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/schema/swapper/YamlTableSwapper.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/yaml/schema/swapper/YamlSchemaSwapperTest.java
- infra/common/src/test/resources/yaml/schema/schema.yaml
> Fix unsigned flag of column metadata was not serialized

- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/cases/value/SQLValue.java
> Fix mistake in E2E suite SQLValue.java

- test/e2e/suite/src/test/resources/cases/dml/dataset/passthrough/mysql/insert_max_values_into_single_table_integer_unsigned.xml
- test/e2e/suite/src/test/resources/cases/dml/dataset/passthrough/mysql/insert_min_values_into_single_table_integer_unsigned.xml
- test/e2e/suite/src/test/resources/cases/dml/dml-integration-test-cases.xml
- test/e2e/suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/dataset.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/mysql/01-actual-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/opengauss/01-actual-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/postgresql/01-actual-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/dataset.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/mysql/01-expected-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/opengauss/01-expected-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/postgresql/01-expected-init.sql
> Add DML/DQL cases cover MySQL unsigned integer types

- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/util/TestCaseClassScanner.java
- Fix transaction test case load package name
---
> Fix transaction test case load package name

- test/e2e/agent/plugins/jaeger/src/test/assembly/bin/start.sh
- test/e2e/agent/plugins/jaeger/src/test/assembly/shardingsphere-proxy-agent-jaeger-assembly.xml
for #23135 
- refactor the assembly file for jaeger
---
> Refactor : refactor the assembly and startup file for jaeger  (#23135)

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/PostgreSQLColumnType.java
- proxy/frontend/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutor.java
- proxy/frontend/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutorTest.java
> Fix NPE when describing PostgreSQL composite type

- features/mask/api/src/main/java/org/apache/shardingsphere/mask/factory/MaskAlgorithmFactory.java
- features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/converter/MaskRuleStatementConverter.java
- features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/update/CreateMaskRuleStatementUpdater.java
- features/mask/distsql/parser/src/main/java/org/apache/shardingsphere/mask/distsql/parser/core/MaskDistSQLStatementVisitor.java
- features/mask/distsql/statement/src/main/java/org/apache/shardingsphere/mask/distsql/parser/segment/MaskColumnSegment.java
- features/mask/distsql/statement/src/main/java/org/apache/shardingsphere/mask/distsql/parser/segment/MaskRuleSegment.java
- features/mask/distsql/statement/src/main/java/org/apache/shardingsphere/mask/distsql/parser/statement/CreateMaskRuleStatement.java
The first task of #23138.
- Add DistSQL `create mask rule` updater
---
> Add DistSQL `create mask rule` updater

- test/e2e/suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/dataset.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/mysql/01-actual-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/opengauss/01-actual-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/postgresql/01-actual-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/dataset.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/mysql/01-expected-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/opengauss/01-expected-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/postgresql/01-expected-init.sql
Relates to:
* https://github.com/apache/shardingsphere/issues/22345
* https://github.com/apache/shardingsphere/issues/22522
* https://github.com/apache/shardingsphere/issues/23102
> Add tests for ShardingSphere-Proxy PostgreSQL/openGauss insert returning

- proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/executor/ConnectionThreadExecutorGroup.java
- proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/ServerHandlerInitializer.java
- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/MySQLFrontendEngine.java
- proxy/frontend/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/authentication/MySQLAuthenticationEngine.java
- proxy/frontend/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/MySQLFrontendEngineTest.java
- proxy/frontend/spi/src/main/java/org/apache/shardingsphere/proxy/frontend/spi/DatabaseProtocolFrontendEngine.java
> Init MySQL sequence ID when channel initializing

- features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/update/DropMaskRuleStatementUpdater.java
- features/mask/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.update.RuleDefinitionUpdater
- features/mask/distsql/parser/src/main/java/org/apache/shardingsphere/mask/distsql/parser/core/MaskDistSQLStatementVisitor.java
- features/mask/distsql/statement/src/main/java/org/apache/shardingsphere/mask/distsql/parser/statement/DropMaskRuleStatement.java
- proxy/bootstrap/src/main/resources/conf/server.yaml
Ref:  #23138.
- Add `drop mask rule` DistSQL updater
---
> Add `drop mask rule` DistSQL updater

- features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/query/MaskRuleResultSet.java
- features/mask/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
- features/mask/distsql/parser/src/main/java/org/apache/shardingsphere/mask/distsql/parser/core/MaskDistSQLStatementVisitor.java
- features/mask/distsql/statement/src/main/java/org/apache/shardingsphere/mask/distsql/parser/statement/ShowMaskRulesStatement.java
Ref:  #23138.
- add `show mask rule` DistSQL resultSet
---
> add `show mask rule` DistSQL resultSet

- features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/query/CountMaskRuleResultSet.java
- features/mask/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
- features/mask/distsql/parser/src/main/java/org/apache/shardingsphere/mask/distsql/parser/core/MaskDistSQLStatementVisitor.java
- features/mask/distsql/statement/src/main/java/org/apache/shardingsphere/mask/distsql/parser/statement/CountMaskRuleStatement.java
Ref: #23138.
- add `count mask rule` DistSQL resultSet
---
> add `count mask rule` DistSQL resultSet

- docs/document/content/reference/distsql/syntax/rdl/rule-definition/encrypt/create-encrypt-rule.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/mask/alter-mask-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/mask/alter-mask-rule.en.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/mask/create-mask-rule.cn.md
Ref: #23138.
add doc for #23185.
- Update `alter mask rule` DistSQL document
---
> Update `alter mask rule` DistSQL document

- docs/document/content/reference/distsql/syntax/rdl/rule-definition/mask/drop-mask-rule.cn.md
- docs/document/content/reference/distsql/syntax/rdl/rule-definition/mask/drop-mask-rule.en.md
Ref: #23138.
add doc for #23197.
- Update `drop mask rule` DistSQL document
---
> Update `drop mask rule` DistSQL document

- docs/document/content/reference/distsql/syntax/rql/rule-query/mask/count-mask-rule.cn.md
- docs/document/content/reference/distsql/syntax/rql/rule-query/mask/count-mask-rule.en.md
Ref: #23138.
add doc for #23207 
- Update the` count mask rule` DistSQL document
---
> Update `count mask rule` DistSQL document

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/datasource/config/impl/ShardingSpherePipelineDataSourceConfiguration.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/datasource/config/impl/StandardPipelineDataSourceConfiguration.java
- kernel/data-pipeline/api/src/test/java/org/apache/shardingsphere/data/pipeline/api/datasource/config/impl/ShardingSpherePipelineDataSourceConfigurationTest.java
- kernel/data-pipeline/api/src/test/java/org/apache/shardingsphere/data/pipeline/api/datasource/config/impl/StandardPipelineDataSourceConfigurationTest.java
- Fix PipelineDataSourceConfiguration side effect
---
> Fix PipelineDataSourceConfiguration side effect

- docs/document/content/user-manual/common-config/builtin-algorithm/metadata-repository.cn.md
- docs/document/content/user-manual/common-config/builtin-algorithm/metadata-repository.en.md
- mode/type/standalone/repository/provider/jdbc/mysql/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/mysql/MySQLJDBCRepositoryProvider.java
- mode/type/standalone/repository/provider/jdbc/mysql/src/test/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/mysql/MySQLJDBCRepositoryProviderTest.java
> Revise #23176

- docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.en.md
- mode/type/standalone/repository/provider/jdbc/mysql/pom.xml
For https://github.com/apache/shardingsphere/issues/19766.
- Update documentation for MySQL's JDBCRepositoryProvider implementation
---
> Update documentation for MySQL's JDBCRepositoryProvider implementation

- mode/type/standalone/repository/provider/jdbc/core/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/JDBCRepository.java
Fixes #23218.
- Reconstruct the JDBCRepository#delete function.
---
> Reconstruct the JDBCRepository#delete function

- features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/update/CreateMaskRuleStatementUpdater.java
- features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/update/CreateMaskRuleStatementUpdaterTest.java
Ref: #23138.
add unit test for #23167.
- Add `create mask rule` DistSQL unit test
---
> Add `create mask rule` DistSQL unit test

- features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/update/AlterMaskRuleStatementUpdater.java
- features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/update/AlterMaskRuleStatementUpdaterTest.java
Ref: #23138.
add unit test for #23186.
- Add `alter mask rule` DistSQL unit test
---
> Add `alter mask rule` DistSQL unit test

- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/CreateDefaultShadowAlgorithmStatementUpdater.java
For #22844 , refactor ifNotExists of CREATE DEFAULT SHADOW ALGORITHM.
---
> Refactor ifNotExists of CREATE DEFAULT SHADOW ALGORITHM.

- features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/update/DropMaskRuleStatementUpdaterTest.java
Ref: #23138.
add unit test for #23197.
- Add `drop mask rule` DistSQL unit test
---
> Add `drop mask rule` DistSQL unit test

- features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/query/MaskRuleResultSetTest.java
Ref: #23138.
add unit test for #23199.
- Add `show mask rule` DistSQL unit test
---
> Add `show mask rule` DistSQL unit test

- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/CreateDefaultShadowAlgorithmStatementUpdater.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/CreateShadowRuleStatementUpdater.java
For #22844 , refactor ifNotExists of CREATE SHADOW RULE.
---
> Refactor ifNotExists of CREATE SHADOW RULE.

- test/e2e/agent/plugins/metrics/src/test/java/org/apache/shardingsphere/test/e2e/agent/metrics/result/JsonConfiguration.java
- test/e2e/agent/plugins/metrics/src/test/java/org/apache/shardingsphere/test/e2e/agent/metrics/result/MetricsQueryResult.java
Fixes #23260.
- refactor the metrics class to implement json configuration
---
> Refactor the metrics class to implement json configuration (#23260)

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportDatabaseConfigurationHandler.java
Ref: #23138.
-  Update ExportDatabaseConfigurationHandler
---
>  Update ExportDatabaseConfigurationHandler

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/constant/DistSQLScriptConstants.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandler.java
Ref: #23138.
-  Update ConvertYamlConfigurationHandler
---
>  Update ConvertYamlConfigurationHandler

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationHandler.java
Ref: #23138.
-  Update ImportDatabaseConfigurationHandler
---
>  Update ImportDatabaseConfigurationHandler

- docs/document/content/user-manual/shardingsphere-jdbc/special-api/readwrite-splitting/hint.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/special-api/readwrite-splitting/hint.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/special-api/sharding/hint.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/special-api/sharding/hint.en.md
For #20736 .
- update SQL hint document.
---
> update SQL hint document

- test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/show_compute_node_info.xml
- test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/cluster/show_compute_node_mode.xml
- test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/standalone/show_compute_node_info.xml
- test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/standalone/show_compute_node_mode.xml
- test/e2e/suite/src/test/resources/cases/ral/ral-integration-test-cases.xml
Ref: #20867.
- add ral test case `SHOW COMPUTE NODE INFO`
- add ral test case `SHOW COMPUTE NODE MODE`
---
> Add some integration test case for DistSQL RAL

- features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/checker/ReadwriteSplittingRuleStatementChecker.java
- features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/CreateReadwriteSplittingRuleStatementUpdater.java
For #22844 , refactor ifNotExists of CREATE READWRITE_SPLITTING RULE.
---
> Refactor ifNotExists of CREATE READWRITE_SPLITTING RULE.

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/nightly-build-example.yml
- .github/workflows/nightly-e2e.yml
Fixes #23273.
- remove the maven settings for spring 
---
> Remove : remove the maven settings for spring (#23273)

- docs/document/content/dev-manual/sharding.cn.md
- docs/document/content/dev-manual/sharding.en.md
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/audit/DMLShardingConditionsShardingAuditAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/decider/ShardingSQLFederationDecider.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/ShardingSQLRouter.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/ShardingConditionEngine.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/ShardingConditionEngineFactory.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/impl/DefaultShardingConditionEngine.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/decider/ShardingSQLFederationDeciderTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/ShardingConditionEngineFactoryTest.java
Ref #22857.
- Revise ShardingConditionEngine logic
---
> Revise ShardingConditionEngine logic

- kernel/data-pipeline/cdc/core/src/test/java/org/apache/shardingsphere/data/pipeline/cdc/util/ColumnValueConvertUtilTest.java
- Fix ColumnValueConvertUtilTest unit test error
---
> Fix ColumnValueConvertUtilTest unit test error

- examples/shardingsphere-example-generator/src/main/resources/template/jdbc/java/config/mask.ftl
For #22759.
- fix the mask example error
---
> fix the mask example error

- features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/AlterDatabaseDiscoveryRuleStatementUpdater.java
- features/db-discovery/distsql/handler/src/main/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/CreateDatabaseDiscoveryRuleStatementUpdater.java
- Remove unused check in DistSQL DB_DISCOVERY RULE
---
> Remove unused check

- agent/pom.xml
Fixes #23287.
- remove the H2 data.zip from shaded artifact 
---
> Remove : remove the H2 data.zip from shaded artifact (#23287)

- agent/README.md
Fixes #23254.
- Add README.md for agent
---
> Add README.md for agent

- agent/plugins/logging/type/file/pom.xml
- agent/plugins/logging/type/file/src/main/resources/META-INF/conf/file-advisors.yaml
- agent/plugins/pom.xml
Fixes #23305.
- agent plugin excludes slf4j dependency
---
> Plugin excludes slf4j dependency

- test/e2e/fixture/pom.xml
Fixes #23296.
- Remove use of shardingsphere-agent-bootstrap
- Maybe related to https://github.com/apache/shardingsphere/issues/22354.
---
> Remove use of shardingsphere-agent-bootstrap

- agent/pom.xml
Fixes #23290.
- remove mozilla suffix file
---
> Remove mozilla suffix file

- docs/document/content/user-manual/shardingsphere-proxy/observability/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/observability/_index.en.md
For #23259
- update agent doc
---
> update agent doc

- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/MaskAlgorithmUtilTest.java
Fixes #23292 .
-Add unit test for MaskAlgorithmUtil
> Add unit test for MaskAlgorithmUtil

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/ShadowRuleConfigurationImportChecker.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationHandler.java
- Add `ShadowRuleConfigurationImportChecker` for `ImportDatabaseConfigurationHandler`
---
> Add `ShadowRuleConfigurationImportChecker`

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/EncryptRuleConfigurationImportChecker.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/MaskRuleConfigurationImportChecker.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationHandler.java
- Add `MaskRuleConfigurationImportChecker` for `ImportDatabaseConfigurationHandler`
---
> Add `MaskRuleConfigurationImportChecker`

- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/ShardingRuleConfigurationImportCheckerTest.java
- add `ShardingRuleConfigurationImportCheckerTest`
---
> Add unit test for `ShardingRuleConfigurationImportChecker`

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/checker/EncryptRuleConfigurationChecker.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/exception/metadata/EncryptAssistedQueryColumnNotFoundException.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/exception/metadata/EncryptAssistedQueryEncryptorNotFoundException.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/exception/metadata/EncryptCipherColumnNotFoundException.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/exception/metadata/EncryptEncryptorNotFoundException.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/exception/metadata/EncryptLikeQueryColumnNotFoundException.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/exception/metadata/EncryptLikeQueryEncryptorNotFoundException.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/exception/metadata/EncryptTableNotFoundException.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dal/show/EncryptShowColumnsMergedResult.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dal/show/EncryptShowCreateTableMergedResult.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptInsertValueParameterRewriter.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptForUseDefaultInsertColumnsTokenGenerator.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptRule.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/checker/EncryptRuleConfigurationCheckerTest.java
For #20036.
- Optimize error code for encrypt.
---
> Optimize error code for encrypt.

- features/encrypt/core/pom.xml
- features/encrypt/distsql/handler/pom.xml
- jdbc/core/pom.xml
-  Remove the dependency of encrypt-plugin from encrypt-core.
---
> Remove the dependency of encrypt-plugin from encrypt-core.

- docs/community/content/involved/release/shardingsphere-on-cloud.cn.md
- docs/community/content/involved/release/shardingsphere-on-cloud.en.md
- update helm carts release doc
> feat(helm): update helm carts release doc

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/exception/algorithm/MaskAlgorithmInitializationException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/classbased/ClassBasedShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/classbased/ClassBasedShardingAlgorithmFactory.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/complex/ComplexInlineShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/datetime/AutoIntervalShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/datetime/IntervalShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/hint/HintInlineShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/InlineShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/mod/HashModShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/mod/ModShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/range/BoundaryBasedRangeShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/range/VolumeBasedRangeShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/algorithm/keygen/GenerateKeyStrategyNotFoundException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/algorithm/sharding/MismatchedInlineShardingAlgorithmExpressionAndColumnException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/algorithm/sharding/ShardingAlgorithmClassImplementationException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/algorithm/sharding/ShardingAlgorithmInitializationException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/algorithm/sharding/ShardingRouteAlgorithmException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/strategy/type/standard/StandardShardingStrategy.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/classbased/ClassBasedShardingAlgorithmFactoryTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/classbased/ClassBasedShardingAlgorithmTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/InlineShardingAlgorithmTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/mod/ModShardingAlgorithmTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/standard/ShardingStandardRoutingEngineTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java
Ref #20036.
- Add new ShardingAlgorithmInitializationException to handle related exceptions
---
> Add new ShardingAlgorithmInitializationException to handle related exceptions

- .github/workflows/e2e.yml
- test/e2e/agent/plugins/common/src/test/java/org/apache/shardingsphere/test/e2e/agent/common/result/JsonConfiguration.java
- test/e2e/agent/plugins/metrics/src/test/java/org/apache/shardingsphere/test/e2e/agent/metrics/result/MetricsMetaDataResult.java
- test/e2e/agent/plugins/metrics/src/test/java/org/apache/shardingsphere/test/e2e/agent/metrics/result/MetricsQueryResult.java
- test/e2e/agent/plugins/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/ZipkinPluginE2EIT.java
- test/e2e/agent/plugins/zipkin/src/test/resources/env/engine-env.properties
for #23135
- add assertion for zipkin E2E
---
> Add : add assertion for zipkin E2E (#23135)

- features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/update/DropMaskRuleStatementUpdater.java
- features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/update/DropMaskRuleStatementUpdaterTest.java
- Add `ifExist` for `drop mask rule`
---
> Add `ifExist` for `drop mask rule`

- examples/shardingsphere-example-generator/src/main/java/org/apache/shardingsphere/example/generator/ExampleGeneratorMain.java
- examples/shardingsphere-example-generator/src/main/java/org/apache/shardingsphere/example/generator/core/ExampleGenerator.java
- examples/shardingsphere-example-generator/src/main/java/org/apache/shardingsphere/example/generator/core/ExampleGeneratorFactory.java
- examples/shardingsphere-example-generator/src/main/java/org/apache/shardingsphere/example/generator/core/impl/JDBCExampleGenerator.java
- examples/shardingsphere-example-generator/src/main/java/org/apache/shardingsphere/example/generator/core/impl/ProxyExampleGenerator.java
- examples/shardingsphere-example-generator/src/main/java/org/apache/shardingsphere/example/generator/core/yaml/config/YamlExampleConfiguration.java
- examples/shardingsphere-example-generator/src/main/resources/config.yaml
For #12366.
- Supports specifying the directory for example output
---
> Supports specifying the directory for example output

- .github/workflows/nightly-build-example.yml
- examples/shardingsphere-example-generator/src/main/resources/template/jdbc/java/config/Configuration.ftl
- examples/shardingsphere-example-generator/src/main/resources/template/jdbc/pom.ftl
For #12366.
- Add cluster zookeeper for example genterator
---
> Add cluster zookeeper for example genterator

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/keygen/KeyGenerateStrategyConfiguration.java
- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/sharding/ComplexShardingStrategyConfiguration.java
- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/sharding/HintShardingStrategyConfiguration.java
- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/sharding/StandardShardingStrategyConfiguration.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/keygen/SnowflakeKeyGenerateAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/complex/ComplexInlineShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/mod/ModShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/range/BoundaryBasedRangeShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/checker/ShardingRuleConfigurationChecker.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/algorithm/keygen/SnowflakeClockMoveBackException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/algorithm/sharding/MismatchedComplexInlineShardingAlgorithmColumnAndValueSizeException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/data/ShardingValueOffsetException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/metadata/MissingRequiredAlgorithmException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/metadata/MissingRequiredConfigurationException.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/keygen/SnowflakeKeyGenerateAlgorithmTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/checker/ShardingRuleConfigurationCheckerTest.java
- features/sharding/plugin/cosid/src/main/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdSnowflakeKeyGenerateAlgorithm.java
- features/sharding/plugin/cosid/src/main/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/AbstractCosIdIntervalShardingAlgorithm.java
- features/sharding/plugin/cosid/src/main/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/mod/CosIdModShardingAlgorithm.java
- features/sharding/plugin/cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdSnowflakeKeyGenerateAlgorithmTest.java
Ref #20036.
- optimize algorithm error code and message for sharding algorithm
---
> Optimize algorithm error code and message for sharding algorithm

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/data/NotImplementComparableShardingValueException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/data/NotImplementComparableValueException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/metadata/InvalidBindingTablesException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByMemoryMergedResult.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByRowComparator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByStreamMergedResult.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/orderby/OrderByValue.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/parameter/impl/ShardingGeneratedKeyInsertValueParameterRewriter.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/CursorTokenGenerator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/FetchDirectionTokenGenerator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/impl/InsertClauseShardingConditionEngine.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/ConditionValue.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/checker/ShardingTableRuleStatementChecker.java
Ref #23047.
- Add NotImplementComparableShardingValueException, InvalidBindingTablesException to handle related exceptions
- remove useless Preconditions check
---
> Add NotImplementComparableValueException, InvalidBindingTablesException to handle related exceptions

- sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
- sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
- test/e2e/suite/src/test/resources/cases/dml/dml-integration-test-cases.xml
- test/it/parser/src/main/resources/case/dml/insert.xml
- test/it/parser/src/main/resources/case/dml/select.xml
- test/it/parser/src/main/resources/sql/supported/dml/insert.xml
> Fix PostgreSQL/openGauss parameter lost if placeholder contains type cast

- .github/workflows/e2e-discovery.yml
- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/algorithm/DatabaseDiscoveryEngine.java
- features/db-discovery/provider/mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/type/MySQLNormalReplicationDatabaseDiscoveryProviderAlgorithm.java
> Avoid throw NFE when use `MySQL.NORMAL_REPLICATION` not set delay-milliseconds-threshold

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/ShardingSphereTransactionManagerEngine.java
- kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/exception/TransactionManagerNotExistedException.java
- kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/exception/TransactionTimeoutException.java
- kernel/transaction/type/base/seata-at/src/main/java/org/apache/shardingsphere/transaction/base/seata/at/SeataATShardingSphereTransactionManager.java
- kernel/transaction/type/base/seata-at/src/main/java/org/apache/shardingsphere/transaction/base/seata/at/exception/SeataATConfigurationException.java
- kernel/transaction/type/base/seata-at/src/main/java/org/apache/shardingsphere/transaction/base/seata/at/exception/SeataATDisabledException.java
- kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/XAShardingSphereTransactionManager.java
For #20036.
- Add transaction exception codes
---
> Add transaction exception codes

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- Update `error message` for `sql error code document`
---
> Update `error message` for `sql error code document`

- .github/workflows/e2e.yml
- test/e2e/agent/plugins/jaeger/pom.xml
- test/e2e/agent/plugins/jaeger/src/test/assembly/shardingsphere-proxy-agent-jaeger-assembly.xml
- test/e2e/agent/plugins/jaeger/src/test/java/org/apache/shardingsphere/test/e2e/agent/jaeger/JaegerPluginE2EIT.java
- test/e2e/agent/plugins/jaeger/src/test/java/org/apache/shardingsphere/test/e2e/agent/jaeger/result/JaegerTraceResult.java
- test/e2e/agent/plugins/jaeger/src/test/resources/docker/agent/conf/agent.yaml
- test/e2e/agent/plugins/jaeger/src/test/resources/docker/docker-compose.yml
- test/e2e/agent/plugins/jaeger/src/test/resources/env/engine-env.properties
- test/e2e/agent/plugins/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/ZipkinPluginE2EIT.java
- test/e2e/agent/plugins/zipkin/src/test/resources/env/engine-env.properties
Fixes #23135
- add E2E for jaeger
---
> Add : add E2E for jaeger (#23135)

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/algorithm/shadow/column/AbstractColumnMatchedShadowAlgorithm.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/algorithm/shadow/column/ColumnRegexMatchedShadowAlgorithm.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/algorithm/shadow/column/ColumnValueMatchedShadowAlgorithm.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/algorithm/shadow/hint/SimpleHintShadowAlgorithm.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/checker/ShadowRuleConfigurationChecker.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/exception/algorithm/NotImplementHintShadowAlgorithmException.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/exception/algorithm/ShadowAlgorithmInitializationException.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/exception/metadata/InvalidShadowAlgorithmOperationException.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/exception/metadata/MissingRequiredShadowAlgorithmException.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/exception/metadata/MissingRequiredShadowConfigurationException.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/exception/metadata/ShadowDataSourceMappingNotFoundException.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/rule/ShadowTableRule.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/checker/ShardingRuleConfigurationChecker.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/metadata/MissingRequiredShardingAlgorithmException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/metadata/MissingRequiredShardingConfigurationException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/strategy/type/complex/ComplexShardingStrategy.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/strategy/type/hint/HintShardingStrategy.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/strategy/type/standard/StandardShardingStrategy.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/builder/ShardingRuleBuilder.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/swapper/rule/YamlShardingAutoTableRuleConfigurationSwapper.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/swapper/rule/YamlShardingTableRuleConfigurationSwapper.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/checker/ShardingRuleConfigurationCheckerTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/builder/ShardingRuleBuilderTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/rule/YamlShardingAutoTableRuleConfigurationSwapperTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/rule/YamlShardingTableRuleConfigurationSwapperTest.java
Ref #20036.
- Optimize shadow exception error code and message
---
> Optimize shadow exception error code and message

- .licenserc.yaml
- .mvn/wrapper/maven-wrapper.properties
- examples/shardingsphere-example-generator/src/main/resources/template/jdbc/resources/file.ftl
- examples/shardingsphere-example-generator/src/main/resources/template/jdbc/resources/registry.ftl
- examples/shardingsphere-example-generator/src/main/resources/template/jdbc/resources/seata.ftl
- examples/shardingsphere-example-generator/src/main/resources/template/jdbc/resources/yaml/config.ftl
- kernel/transaction/type/base/seata-at/src/test/resources/file.conf
- kernel/transaction/type/base/seata-at/src/test/resources/registry.conf
- kernel/transaction/type/base/seata-at/src/test/resources/seata.conf
- mvnw
- mvnw.cmd
- proxy/backend/src/test/resources/conf/convert/config-encrypt.yaml
- proxy/backend/src/test/resources/conf/empty/server.yaml
- test/e2e/agent/plugins/jaeger/pom.xml
- test/e2e/agent/plugins/zipkin/pom.xml
- test/e2e/fixture/src/test/assembly/conf/jbossts-properties.xml
- test/e2e/transaction/src/test/resources/env/common/cursor-command.xml
- test/e2e/transaction/src/test/resources/env/scenario/cursor/data/actual/databases.xml
- test/e2e/transaction/src/test/resources/env/scenario/cursor/data/actual/dataset.xml
- test/e2e/transaction/src/test/resources/env/scenario/cursor/data/expected/databases.xml
- test/e2e/transaction/src/test/resources/env/scenario/cursor/data/expected/dataset.xml
- test/e2e/transaction/src/test/resources/jbossts-properties.xml
Fixes #23385.
- Unify Copyright format
---
> Unify Copyright format

- pom.xml
For #22469.
- Remove version management for spring-jdbc.
- Related to https://github.com/apache/shardingsphere/issues/22354.
---
> Remove version management for spring-jdbc

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
Ref #20036.
- Update error code in shadow document
---
> Update error code in shadow document

- features/db-discovery/api/src/main/java/org/apache/shardingsphere/dbdiscovery/exception/DBDiscoveryProviderException.java
- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/checker/DatabaseDiscoveryRuleConfigurationChecker.java
- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/exception/DBDiscoveryDataSourceRuleNotFoundException.java
- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/exception/DBDiscoverySQLException.java
- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/exception/MissingRequiredDBDiscoveryConfigurationException.java
- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/exception/MissingRequiredDataSourceNamesConfigurationException.java
- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/exception/MissingRequiredGroupNameConfigurationException.java
- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryDataSourceRule.java
- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryRule.java
- features/db-discovery/core/src/test/java/org/apache/shardingsphere/dbdiscovery/checker/DatabaseDiscoveryRuleConfigurationCheckerTest.java
- features/db-discovery/core/src/test/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryDataSourceRuleTest.java
- features/db-discovery/provider/mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/exception/mgr/InvalidMGRGroupNameConfigurationException.java
- features/db-discovery/provider/mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/exception/mgr/InvalidMGRModeException.java
- features/db-discovery/provider/mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/exception/mgr/InvalidMGRReplicationGroupMemberException.java
- features/db-discovery/provider/mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/exception/replica/DuplicatePrimaryDataSourceException.java
- features/db-discovery/provider/mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/type/MySQLNormalReplicationDatabaseDiscoveryProviderAlgorithm.java
Ref https://github.com/apache/shardingsphere/issues/20036.
> Add DBDiscoveryProviderException and DBDiscoverySQLException

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/exception/DBDiscoveryDataSourceRuleNotFoundException.java
- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/exception/MissingRequiredDBDiscoveryConfigurationException.java
- features/db-discovery/core/src/main/java/org/apache/shardingsphere/dbdiscovery/exception/MissingRequiredGroupNameConfigurationException.java
- features/db-discovery/provider/mysql/src/main/java/org/apache/shardingsphere/dbdiscovery/mysql/exception/replica/DuplicatePrimaryDataSourceException.java
Ref https://github.com/apache/shardingsphere/issues/20036.
> Update sql-error-code for db-discovery

- .github/workflows/e2e.yml
> Refactor : make agent test to matrics

- agent/core/src/main/java/org/apache/shardingsphere/agent/core/plugin/jar/PluginJarLoader.java
- agent/distribution/src/main/assembly/shardingsphere-agent-binary-distribution.xml
Fixes #23392
- refactor the agent packging structure
---
> Refactor : refactor the agent packging structure (#23392)

- infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/memory/loader/dialect/OpenGaussQueryResultDataRowLoader.java
- infra/executor/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.executor.sql.execute.result.query.impl.driver.jdbc.type.memory.loader.DialectQueryResultDataRowLoader
> Correct openGauss spelling mistakes.

- docs/document/content/user-manual/shardingsphere-proxy/yaml-config/rules.en.md
- Correct the `Distributed Operations` to `Distributed Transaction` (screen shot shown below)
---
> Correct a translate issue for document
