- .github/workflows/e2e.yml
> Add MySQL Connector/J 8.0.30 client case to E2E actions

- features/shadow/distsql/parser/src/main/java/org/apache/shardingsphere/shadow/distsql/parser/core/ShadowDistSQLStatementVisitor.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/RDLStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/drop/DropRuleStatementAssert.java
- Optimise RDLStatementAssert
---
> Optimise DistSQL RDL parser test

- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdater.java
For #22844 , refactor ifNotExists of CREATE ENCRYPT RULE.
---
> Refactor ifNotExists of CREATE ENCRYPT RULE.

- sql-parser/dialect/opengauss/src/main/antlr4/imports/opengauss/DALStatement.g4
- sql-parser/dialect/opengauss/src/main/antlr4/imports/opengauss/OpenGaussKeyword.g4
- test/it/parser/src/main/resources/case/dal/explain.xml
- test/it/parser/src/main/resources/sql/supported/dal/explain.xml
> Support openGauss EXPLAIN PERFORMANCE

- test/e2e/pipeline/src/test/resources/env/mysql/server-5.yaml
- test/e2e/pipeline/src/test/resources/env/mysql/server-8.yaml
- test/e2e/pipeline/src/test/resources/env/opengauss/server.yaml
- test/e2e/pipeline/src/test/resources/env/postgresql/server.yaml
- Disable sql-show at pipeline E2E test
---
> Disable sql-show at pipeline E2E test

- test/it/parser/pom.xml
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/distsql/rdl/MaskColumnAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/distsql/rdl/MaskRuleAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/create/CreateRuleStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/create/impl/CreateMaskRuleStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/distsql/rdl/ExpectedMaskColumn.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/distsql/rdl/ExpectedMaskRule.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rdl/rule/mask/CreateMaskRuleStatementTestCase.java
- test/it/parser/src/main/resources/case/rdl/create.xml
- test/it/parser/src/main/resources/sql/supported/rdl/create.xml
- Add parser test for `create mask rule`
---
> Add parser test for `create mask rule`

- agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/constant/MetricIds.java
- agent/plugins/metrics/type/prometheus/src/main/resources/META-INF/conf/prometheus-metrics.yaml
- agent/plugins/metrics/type/prometheus/src/test/resources/META-INF/conf/prometheus-metrics.yaml
- docs/document/content/user-manual/shardingsphere-proxy/observability/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/observability/_index.en.md
- test/e2e/agent/plugins/metrics/src/test/java/org/apache/shardingsphere/test/e2e/agent/metrics/MetricsPluginE2EIT.java
Fixes #23458.
- metric total_proxy_requests changed to proxy_request_total
---
> Agent: metric total_proxy_requests changed to proxy_request_total

- agent/core/src/main/java/org/apache/shardingsphere/agent/core/plugin/jar/PluginJarLoader.java
Fixes #23392.
- Refactor agent packaging and class loader
---
> Refactor agent packaging and class loader

- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/drop/DropRuleStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/drop/impl/DropMaskRuleStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rdl/rule/mask/DropMaskRuleStatementTestCase.java
- test/it/parser/src/main/resources/case/rdl/drop.xml
- test/it/parser/src/main/resources/sql/supported/rdl/drop.xml
- Add parser test for `drop mask rule`
---
> Add parser test for `drop mask rule`

- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rql/rule/mask/CountMaskRuleStatementTestCase.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rql/rule/mask/ShowMaskRulesStatementTestCase.java
- test/it/parser/src/main/resources/case/rql/show.xml
- test/it/parser/src/main/resources/sql/supported/rql/show.xml
- add `show mask rules` case
- add `count mask rule` case
---
> Add RQL parser test case for `mask rule`

- .github/workflows/nightly-build-example.yml
- examples/shardingsphere-example-generator/src/main/resources/config.yaml
- examples/shardingsphere-example-generator/src/main/resources/template/jdbc/java/repository/jdbc/OrderRepository.ftl
Fixes #12366.
- Add xa transaction support
---
> Add xa transaction support  for example generator

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/checker/ReadwriteSplittingRuleConfigurationChecker.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/rule/ReadwriteSplittingRule.java
Ref https://github.com/apache/shardingsphere/issues/20036.
> Add readwrite-splitting error code doc

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/IncrementalTask.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryTask.java
- Add throwable log at pipeline inventory and incremental task.
---
> Add throwable log at pipeline inventory and incremental task.

- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/autocommit/MySQLAutoCommitTestCase.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/autocommit/PostgresSQLAutoCommitTestCase.java
- test/e2e/transaction/src/test/resources/env/it-env.properties
- Fix auto commit transaction test cases
---
> Fix auto commit transaction test cases

- agent/plugins/metrics/core/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/proxy/ExecuteLatencyHistogramAdviceTest.java
> Fix ExecuteLatencyHistogramAdviceTest occasionally failed

- sql-parser/dialect/opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4
- sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
- sql-parser/dialect/postgresql/src/main/antlr4/imports/postgresql/BaseRule.g4
- sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
- test/it/parser/src/main/resources/case/dml/select.xml
- test/it/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #23473.
https://www.postgresql.org/docs/current/sql-expressions.html#SQL-EXPRESSIONS-PARAMETERS-POSITIONAL
> Fix PostgreSQL/openGauss positional parameter rule

- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/cases/value/SQLValue.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/engine/SingleE2EIT.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/env/DataSetEnvironmentManager.java
- test/e2e/suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/dataset.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/mysql/01-actual-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/opengauss/01-actual-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/postgresql/01-actual-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/dataset.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/mysql/01-expected-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/opengauss/01-expected-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/postgresql/01-expected-init.sql
Relates to #14899.
Covers #23468, #23494
> Add DQL test cases for PostgreSQL/openGauss money type

- agent/core/src/test/java/org/apache/shardingsphere/agent/core/plugin/PluginContextTest.java
Add test case for PluginContextTest
Fixes #23419 .
-Add test case for PluginContextTest
---
> Add test case for PluginContextTest

- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/engine/BatchE2EIT.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/engine/dml/BaseDMLE2EIT.java
- test/e2e/suite/src/test/resources/cases/dml/dataset/passthrough/insert_max_money_values.xml
- test/e2e/suite/src/test/resources/cases/dml/dataset/passthrough/insert_min_money_values.xml
- test/e2e/suite/src/test/resources/cases/dml/dataset/passthrough/insert_rounding_money_values.xml
- test/e2e/suite/src/test/resources/cases/dml/dataset/passthrough/update_money_add_value.xml
- test/e2e/suite/src/test/resources/cases/dml/dataset/passthrough/update_money_subtract_value.xml
- test/e2e/suite/src/test/resources/cases/dml/dml-integration-test-cases.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/dataset.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/dataset.xml
> Add DML cases for PostgreSQL/openGauss money type

- docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/sharding.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/sharding.en.md
Fixes #23519.
- Fix configuration example
> Fix configuration example

- agent/core/src/test/java/org/apache/shardingsphere/agent/core/plugin/PluginContextTest.java
> Revise #23514

- sql-parser/dialect/opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4
- sql-parser/dialect/postgresql/src/main/antlr4/imports/postgresql/BaseRule.g4
- test/it/parser/src/main/resources/case/dml/select.xml
- test/it/parser/src/main/resources/sql/supported/dml/select.xml
- test/it/parser/src/main/resources/sql/unsupported/unsupported.xml
> Fix PostgreSQL/openGauss failed to parse const with type cast

- agent/core/src/test/java/org/apache/shardingsphere/agent/core/plugin/PluginContextTest.java
- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/FilterableTableScanExecutor.java
- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/TranslatableTableScanExecutor.java
- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/row/EmptyRowScalarEnumerator.java
- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/row/MemoryEnumerator.java
- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/row/MemoryScalarEnumerator.java
- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/row/SQLFederationRowScalarEnumerator.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/translatable/StringToRexNodeUtil.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/translatable/TranslatableFilterRule.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/translatable/TranslatableProjectFilterRule.java
Ref #23040.
- Revise PR#23040
---
> Revise PR#23040

- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/helper/PipelineCaseHelper.java
- test/e2e/pipeline/src/test/resources/env/scenario/general/postgresql.xml
- Add emoji text at pipeline E2E test
- Add more column type at PostgreSQL E2E test
---
> Add emoji text at pipeline E2E test

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/MissRequireTargetDatabaseException.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/MissingRequiredTargetDatabaseException.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/ModeConfigNotFoundException.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/UnsupportedModeTypeException.java
- kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/MigrateTableUpdater.java
Ref #20036.
- Add  `ModeConfigNotFoundException, UnsupportedModeTypeException, MissRequireTargetDatabaseException`
---
> Add new pipeline exceptions to handle related exceptions #23341

- infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/ExecuteProcessEngine.java
Fixes #23546.
- Fix show processlist does not collect the execution info of sub threads
---
> Fix show processlist does not collect the execution info of async threads(#23546)

- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/commitrollback/MultiOperationsCommitAndRollbackTestCase.java
- test/e2e/transaction/src/test/resources/env/it-env.properties
- Fix multi operations in transaction test case
---
> Fix multi operations in transaction test case

- docs/document/content/reference/sharding/rewrite.cn.md
> Fix rewrite document

- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/SQLUtil.java
- sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SQLUtilTest.java
> Remove unused method SQLUtil.isReadOnly

- sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
- sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/TypeCastExpression.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/ExpressionExtractUtil.java
- sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/ExpressionExtractUtilTest.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedExpression.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedTypeCastExpression.java
- test/it/parser/src/main/resources/case/dml/select-special-function.xml
- test/it/parser/src/main/resources/case/dml/select.xml
- test/it/parser/src/main/resources/sql/supported/dml/select.xml
> Add TypeCastExpression for PostgreSQL/openGauss

- distribution/proxy/src/main/resources/bin/start.sh
Fixes #23605
- fix the agent script in start.sh
---
> Fix : fix the agent script in start.sh

- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/replace/TelephoneRandomReplaceAlgorithm.java
- features/mask/core/src/main/resources/algorithm/replace/chinese_network_number.dict
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/replace/TelephoneRandomReplaceAlgorithmTest.java
Ref #22759 .
-Refactor TelephoneRandomReplaceAlgorithm
> Refactor TelephoneRandomReplaceAlgorithm

- agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/SQLParseCountAdvice.java
- agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/SQLRouteCountAdvice.java
- agent/plugins/metrics/core/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/SQLParseCountAdviceTest.java
- agent/plugins/metrics/core/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/SQLRouteCountAdviceTest.java
- agent/plugins/metrics/type/prometheus/src/main/resources/META-INF/conf/prometheus-metrics.yaml
- docs/document/content/user-manual/shardingsphere-proxy/observability/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/observability/_index.en.md
- test/e2e/agent/plugins/metrics/src/test/java/org/apache/shardingsphere/test/e2e/agent/metrics/MetricsPluginE2EIT.java
Fixes #23629.
- Add `parsed_sql_total metric`
- Add `routed_sql_total metric`
- Remove `routed_insert_sql_total, routed_update_sql_total, routed_delete_sql_total, routed_select_sql_total`
- Remove `parsed_insert_sql_total, parsed_update_sql_total, parsed_delete_sql_total, parsed_select_sql_total, parsed_ddl_total, parsed_dcl_total, parsed_dal_total, parsed_tcl_total, parsed_rql_total, parsed_rdl_total, parsed_ral_total, parsed_rul_total`
---
> optimize parsed sql and routed sql metrics

- docs/document/content/features/sharding/appendix.cn.md
- docs/document/content/features/sharding/appendix.en.md
Fixes #23047.
- update document for getGeneratedKeys in sharding feature
---
> Update document for getGeneratedKeys in sharding feature

- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/settype/SetTransactionTypeTestCase.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/settype/TransactionTypeHolderTestCase.java
- test/e2e/transaction/src/test/resources/env/it-env.properties
- Add set transaction type test case
---
> Add set transaction type test case

- test/e2e/transaction/src/test/resources/env/it-env.properties
- Fix transaction it error case
---
> Fix transaction it error case

- features/db-discovery/distsql/handler/src/test/resources/META-INF/services/org.apache.shardingsphere.dbdiscovery.spi.DatabaseDiscoveryProviderAlgorithm
- features/db-discovery/provider/mysql/src/main/resources/META-INF/services/org.apache.shardingsphere.dbdiscovery.spi.DatabaseDiscoveryProviderAlgorithm
- features/db-discovery/provider/opengauss/src/main/resources/META-INF/services/org.apache.shardingsphere.dbdiscovery.spi.DatabaseDiscoveryProviderAlgorithm
- proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.proxy.backend.response.header.query.QueryHeaderBuilder
> Correct copyright

- test/e2e/suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/alter_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/create_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/drop_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rdl/rdl-integration-test-cases.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/db/count_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/db/show_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting/count_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting/show_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting_and_encrypt/count_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting_and_encrypt/show_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/mask/count_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/mask/show_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/mask_encrypt/count_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/mask_encrypt/show_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/mask_encrypt_sharding/count_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/mask_encrypt_sharding/show_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/mask_sharding/count_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/mask_sharding/show_mask_rule.xml
- test/e2e/suite/src/test/resources/cases/rql/rql-integration-test-cases.xml
- Add integration test cases for DistSQL `mask rule`
---
> Add integration test cases for DistSQL `mask rule`

- infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/engine/GenericSQLRewriteEngine.java
- infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/engine/GenericSQLRewriteEngineTest.java
> Fix NoSuchElementException when use system database

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/DistSQLBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/QueryableGlobalRuleRALBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/UpdatableGlobalRuleRALBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/migration/query/QueryableScalingRALBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/migration/update/UpdatableScalingRALBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/RDLBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/RDLBackendHandlerFactory.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/rule/RuleDefinitionBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/AlterStorageUnitBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/RegisterStorageUnitBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/StorageUnitDefinitionBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/UnregisterStorageUnitBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/storage/unit/StorageUnitResultSet.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/RULBackendHandler.java
- proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/RDLBackendHandlerFactoryTest.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/AlterStorageUnitBackendHandlerTest.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/RegisterStorageUnitBackendHandlerTest.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/UnregisterStorageUnitBackendHandlerTest.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/StorageUnitResultSetTest.java
For #23725.
- Add DistSQLBackendHandler.
Note: `DatabaseRequiredBackendHandler` and `RQLBackendHandler` do not conform to the current design and will be adjusted in the next PR.
---
> Add DistSQLBackendHandler to optimize the inheritance structure of ProxyBackendHandler

- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/context/CDCConnectionContext.java
- kernel/data-pipeline/cdc/protocol/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/common/CDCResponseErrorCode.java
- proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/CDCChannelInboundHandler.java
- proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/netty/CDCChannelInboundHandlerTest.java
Related: #22500
- Add privileges check at CDC
---
> Add privileges check at CDC

- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/ShowSingleTableExecutorTest.java
The first task of #23737.
- Add `ShowSingleTableExecutorTest`
---
> Add `ShowSingleTableExecutorTest`

- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/ShowStorageUnitExecutorTest.java
The second task of #23737.
- ShowStorageUnitExecutorTest
---
> Add `ShowStorageUnitExecutorTest`

- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/row/MemoryEnumerator.java
- kernel/sql-federation/executor/core/src/test/java/org/apache/shardingsphere/sqlfederation/executor/FilterableTableScanExecutorTest.java
- test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/select_cluster_information.xml
- test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/standalone/select_cluster_information.xml
- test/e2e/suite/src/test/resources/cases/ral/ral-integration-test-cases.xml
> Fix query system table and add IT case

- infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/InsertValueTest.java
- sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussStatementSQLVisitor.java
- sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/TypeCastExpression.java
- sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/ExpressionExtractUtilTest.java
- test/e2e/suite/src/test/resources/cases/dml/dml-integration-test-cases.xml
> Make TypeCastExpression implement ComplexExpression

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptPredicateRightValueTokenGenerator.java
- test/e2e/suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
> Fix lower case like query error in PG.

- docs/community/content/team/_index.cn.md
- docs/community/content/team/_index.en.md
- Move Hongsheng Zhong from Committers list to PMC list
- Adjust Committers list for aligning
---
> Update ShardingSphere Team page

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLBinaryProtocolValueFactory.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLByteaBinaryProtocolValue.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLByteaBinaryProtocolValueTest.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/cases/value/SQLValue.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/engine/BatchE2EIT.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/engine/dml/BaseDMLE2EIT.java
- test/e2e/suite/src/test/resources/cases/dml/dataset/passthrough/insert_bytea_values.xml
- test/e2e/suite/src/test/resources/cases/dml/dml-integration-test-cases.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/dataset.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/mysql/01-actual-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/opengauss/01-actual-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/actual/init-sql/postgresql/01-actual-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/dataset.xml
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/mysql/01-expected-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/opengauss/01-expected-init.sql
- test/e2e/suite/src/test/resources/env/scenario/passthrough/data/expected/init-sql/postgresql/01-expected-init.sql
> PostgreSQL protocol support bytea binary data format

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/data/ShardingStatisticsTableCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/ShardingSphereTableDataCollectorUtil.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/tables/PgClassTableCollector.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/tables/PgNamespaceTableCollector.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
Fixes #23624.
- Fix collect data error with different storage type and protocol type.
---
> Fix collect data error with different storage type and protocol type.

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/spi/datasource/creator/PipelineDataSourceCreator.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/datasource/PipelineDataSourceFactory.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/datasource/creator/StandardPipelineDataSourceCreator.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/datasource/creator/FixturePipelineDataSourceCreator.java
- Rename pipeline data source creator variables
---
> Rename pipeline data source creator variables

- features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/query/ShowMaskRuleExecutor.java
- features/mask/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
- features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/query/ShowMaskRuleExecutorTest.java
For #23772.
- Replace `MaskRuleResultSet` with `ShowMaskRuleExecutor`
---
> Replace `MaskRuleResultSet` with `ShowMaskRuleExecutor`

- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/query/ShowShadowRuleExecutor.java
- features/shadow/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowRuleExecutorTest.java
For #23772.
- Replace `ShadowRuleResultSet` with `ShowShadowRuleExecutor`
---
> Replace `ShadowRuleResultSet` with `ShowShadowRuleExecutor`

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaData.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaDataTest.java
- Compatible with null databaseName on create database
---
> Compatible with null databaseName on create database

- db-protocol/opengauss/src/main/java/org/apache/shardingsphere/db/protocol/opengauss/packet/command/query/extended/bind/OpenGaussComBatchBindPacket.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/PostgreSQLComBindPacket.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextTimeUtils.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextTimeUtilsTest.java
> Support parsing more PostgreSQL time format

- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/query/ShowShadowAlgorithmExecutor.java
- features/shadow/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
- features/shadow/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowAlgorithmExecutorTest.java
For #23772.
- Replace `ShadowAlgorithmResultSet` with `ShowShadowAlgorithmExecutor`
---
> Replace `ShadowAlgorithmResultSet` with `ShowShadowAlgorithmExecutor`

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow/count-shadow-rule.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow/count-shadow-rule.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow/show-default-shadow-algorithm.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow/show-default-shadow-algorithm.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow/show-shadow-algorithm.en.md
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/query/ShowDefaultShadowAlgorithmExecutor.java
- features/shadow/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
- features/shadow/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowDefaultShadowAlgorithmExecutorTest.java
For #23772.
- Replace `DefaultShadowAlgorithmResultSet` with `ShowDefaultShadowAlgorithmExecutor`
---
> Refactor `DefaultShadowAlgorithmResultSet`

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLDateBinaryProtocolValue.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLDateBinaryProtocolValueTest.java
> Fix PostgreSQL protocol codec for date type in binary format

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingTableRuleExecutor.java
- features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
- features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRuleExecutorTest.java
For #23772.
- Replace `ShardingTableRuleResultSet` with `ShowShardingTableRuleExecutor`
---
> Refactor `ShardingTableRuleResultSet`

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingAlgorithmExecutor.java
- features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
- features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingAlgorithmExecutorTest.java
For #23772.
- Replace `ShardingAlgorithmResultSet` with `ShowShardingAlgorithmExecutor`
---
> Refactor`ShardingAlgorithmResultSet`

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingKeyGeneratorExecutor.java
- features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
- features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingKeyGeneratorExecutorTest.java
For #23772.
- Replace `ShardingKeyGeneratorResultSet` with `ShowShardingKeyGeneratorExecutor`
---
> Refactor `ShardingKeyGeneratorResultSet`

- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/api/config/rule/ShardingAutoTableRuleConfiguration.java
- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/api/config/rule/ShardingTableRuleConfiguration.java
- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/audit/ShardingAuditStrategyConfiguration.java
- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/keygen/KeyGenerateStrategyConfiguration.java
- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/sharding/ComplexShardingStrategyConfiguration.java
- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/sharding/HintShardingStrategyConfiguration.java
- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/api/config/strategy/sharding/StandardShardingStrategyConfiguration.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/checker/ShardingRuleConfigurationCheckerTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/TableRuleTest.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShardingTableReferenceRuleResultSetTest.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/AlterShardingTableReferenceRuleStatementUpdaterTest.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/DropShardingAlgorithmStatementUpdaterTest.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/DropShardingTableReferenceRuleStatementUpdaterTest.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/DropShardingTableRuleStatementUpdaterTest.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/common/checker/ShardingRuleConfigurationImportCheckerTest.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/ShowRulesUsedStorageUnitExecutorTest.java
Replace standard constructors with `@RequiredArgsConstructor`
---
> Optimize the construction method of ShardingTableRuleConfiguration.

- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/base/PipelineBaseE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/AbstractMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/NoUniqueKeyMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/TextPrimaryKeyMigrationE2EIT.java
- Pipeline E2E add clean up job method for native mode
---
> Pipeline E2E add clean up job method for native mode

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/sharding/show-sharding-table-nodes.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/sharding/show-sharding-table-nodes.en.md
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingTableNodesExecutor.java
- features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
- features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.resultset.DistSQLResultSet
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShardingTableNodesResultSetTest.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableNodesExecutorTest.java
For #23772.
- Replace `ShardingTableNodesResultSet` with `ShowShardingTableNodesExecutor`
---
> Refactor `ShardingTableNodesResultSet`

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLInt8BinaryProtocolValue.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLInt8BinaryProtocolValueTest.java
> Fix possible CCE when PostgreSQL protocol encoding binary format int8

- distsql/handler/src/main/java/org/apache/shardingsphere/distsql/handler/ral/query/DatabaseRequiredQueryableRALExecutor.java
- distsql/handler/src/main/java/org/apache/shardingsphere/distsql/handler/ral/query/InstanceContextRequiredQueryableRALExecutor.java
- distsql/handler/src/main/java/org/apache/shardingsphere/distsql/handler/ral/query/MetaDataRequiredQueryableRALExecutor.java
- distsql/handler/src/main/java/org/apache/shardingsphere/distsql/handler/ral/query/QueryableRALExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/AbstractQueryableRALBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/QueryableRALBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/UpdatableRALBackendHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportDatabaseConfigurationHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodeInfoHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodeModeHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodesExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariableHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowStatusFromReadwriteSplittingRulesHandler.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowTableMetaDataHandler.java
- proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.QueryableRALExecutor
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactoryTest.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodesExecutorTest.java
For #23854.
- Add QueryableRALExecutor
- Refactor QueryableRALBackendHandler
---
> Add QueryableRALExecutor and refactor QueryableRALBackendHandler.

- agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/collector/type/GaugeMetricFamilyMetricsCollector.java
- agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/exporter/impl/BuildInfoExporter.java
- agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/exporter/impl/proxy/ProxyMetaDataInfoExporter.java
- agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/exporter/impl/proxy/ProxyStateExporter.java
- agent/plugins/metrics/type/prometheus/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/prometheus/collector/type/PrometheusMetricsGaugeMetricFamilyCollector.java
Fixes #23863.
- fix agent duplicate export metrics
---
> fix agent duplicate export metrics

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodeInfoExecutor.java
- proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.QueryableRALExecutor
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodeInfoExecutorTest.java
For #23854.
- Replace `ShowComputeNodeInfoHandler` with `ShowComputeNodeInfoExecutor`
---
> Refactor ShowComputeNodeInfoHandler

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodeModeExecutor.java
- proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.QueryableRALExecutor
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodeModeExecutorTest.java
For #23854.
- Replace `ShowComputeNodeModeHandler` with `ShowComputeNodeModeExecutor`
---
> Replace `ShowComputeNodeModeHandler` with `ShowComputeNodeModeExecutor`

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLInt2BinaryProtocolValue.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLInt2BinaryProtocolValueTest.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/engine/dql/AdditionalDQLE2EIT.java
> Fix possible CCE PostgreSQLInt2BinaryProtocolValue

- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/base/PipelineBaseE2EIT.java
Related to #23838
- Fix proxyDataSource NPE in pipeline NATIVE mode
- Add missing appendExtraParam
---
> Improve PipelineBaseE2EIT.initEnvironment

- docs/document/content/user-manual/common-config/builtin-algorithm/mask.cn.md
- docs/document/content/user-manual/common-config/builtin-algorithm/mask.en.md
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/MaskAlgorithmPropsChecker.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFirstNLastMMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFromXToYMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskAfterSpecialCharsAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskBeforeSpecialCharsAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFirstNLastMMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFromXToYMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/replace/GenericTableRandomReplaceAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/replace/LandlineNumberRandomAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/replace/MilitaryIdentityNumberRandomReplaceAlgorithm.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/MaskAlgorithmPropsCheckerTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/replace/GenericTableRandomReplaceAlgorithmTest.java
Ref #23685.
- rename MaskAlgorithmUtil to MaskAlgorithmPropsChecker
- revise GenericTableRandomReplaceAlgorithm logic
- update document
---
> Revise pr#23685

- sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
- test/it/parser/src/main/resources/case/dml/select-expression.xml
- test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
Fixes #23875.
- Fix parameters in the json function are not recognized
---
> Fix parameters in the json function are not recognized(#23875)

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AbstractDropShardingRuleUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleStatementUpdater.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/DropShardingTableRuleStatementUpdaterTest.java
Fixes #23919 .
- Improve excute checks while removing unused sharding algorithms, key generators and auditors
- Improve related test case
---
> Fix DROP SHARDING TABLE RULE

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNodeWatcher.java
- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/metadata/processor/ConsistencyCheckChangedJobConfigurationProcessor.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/metadata/processor/MigrationChangedJobConfigurationProcessor.java
- Dispatch pipeline data node event asynchronously
---
> Dispatch pipeline data node event asynchronously

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/TableRule.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/TableRuleTest.java
Ref #19423.
- logic table can has some number suffix
---
> Revert Data node suffix pattern.

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/global-rule/alter-transaction-rule.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/global-rule/alter-transaction-rule.en.md
- Fix typo of transaction rule demo
---
> Fix typo of transaction rule demo

- distribution/proxy-native/src/main/release-docs/LICENSE
- distribution/proxy/src/main/release-docs/LICENSE
> Update LICENSE for antlr 4.10.1

- docs/document/content/reference/management/_index.cn.md
- docs/document/content/reference/management/_index.en.md
- Update sys_data description in management document
---
> Update sys_data description in management document

- test/e2e/suite/src/test/resources/cases/dml/dml-integration-delete.xml
- test/e2e/suite/src/test/resources/cases/dml/dml-integration-insert.xml
- test/e2e/suite/src/test/resources/cases/dml/dml-integration-update.xml
Ref #23645.
-splitting dml-integration-test-cases.xml file
> Refactor: splitting dml-integration-test-cases.xml file

- .gitignore
- distsql/parser/pom.xml
- features/db-discovery/distsql/parser/pom.xml
- features/encrypt/distsql/parser/pom.xml
- features/mask/distsql/parser/pom.xml
- features/readwrite-splitting/distsql/parser/pom.xml
- features/shadow/distsql/parser/pom.xml
- features/sharding/distsql/parser/pom.xml
- kernel/authority/distsql/parser/pom.xml
- kernel/data-pipeline/distsql/parser/pom.xml
- kernel/parser/distsql/parser/pom.xml
- kernel/sql-federation/optimizer/pom.xml
- kernel/sql-translator/distsql/parser/pom.xml
- kernel/traffic/distsql/parser/pom.xml
- kernel/transaction/distsql/parser/pom.xml
- pom.xml
- sql-parser/dialect/pom.xml
> Restore antlr output directory for generated codes

- distribution/agent/src/main/assembly/shardingsphere-agent-binary-distribution.xml
- distribution/agent/src/main/release-docs/README.txt
- Add README.txt for agent
---
> Add README.txt for agent

- infra/util/src/main/java/org/apache/shardingsphere/infra/util/props/TypedPropertyValue.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableExecutorTest.java
Fixes #24015.
- Fix get Enum from props value
---
> Fix SET DIST VARIABLE system-log-level

- docs/document/content/quick-start/shardingsphere-jdbc-quick-start.en.md
Fixes #23939.
- Fixes document error. 
---
> fixes document error in quick start doc

- test/e2e/suite/src/test/resources/cases/ral/ral-integration-hint.xml
- test/e2e/suite/src/test/resources/cases/ral/ral-integration-preview.xml
- test/e2e/suite/src/test/resources/cases/ral/ral-integration-queryable.xml
- test/e2e/suite/src/test/resources/cases/ral/ral-integration-refresh.xml
- test/e2e/suite/src/test/resources/cases/ral/ral-integration-set.xml
- test/e2e/suite/src/test/resources/cases/ral/ral-integration-show.xml
- test/e2e/suite/src/test/resources/cases/ral/ral-integration-updatable.xml
Ref #23645.
-splitting ral-integration-test-cases.xml file
> Refactor: splitting ral-integration-test-cases.xml file

- infra/common/src/test/java/org/apache/shardingsphere/infra/hint/SQLHintExtractorTest.java
> add sql hint extractor test case.

- docs/document/content/dev-manual/transaction.cn.md
- docs/document/content/dev-manual/transaction.en.md
- docs/document/content/reference/transaction/2pc-xa-transaction.en.md
- docs/document/content/reference/transaction/base-transaction-seata.en.md
- Update transaction link document
---
> Update transaction link document

- docs/document/content/dev-manual/shadow.cn.md
- docs/document/content/dev-manual/shadow.en.md
- docs/document/content/user-manual/common-config/builtin-algorithm/shadow.cn.md
- docs/document/content/user-manual/common-config/builtin-algorithm/shadow.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/shadow.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/shadow.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow/alter-default-shadow-algorithm.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow/alter-default-shadow-algorithm.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow/alter-shadow-rule.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow/alter-shadow-rule.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow/create-default-shadow-algorithm.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow/create-default-shadow-algorithm.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow/create-shadow-rule.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow/create-shadow-rule.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow/drop-shadow-algorithm.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow/drop-shadow-algorithm.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow/show-shadow-table-rule.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow/show-shadow-table-rule.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/usage/shadow-rule.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/usage/shadow-rule.en.md
> Replace shadow SIMPLE HINT to SQL HINT for doc.

- docs/document/content/user-manual/common-config/builtin-algorithm/load-balance.cn.md
- docs/document/content/user-manual/common-config/builtin-algorithm/load-balance.en.md
- features/readwrite-splitting/api/src/main/java/org/apache/shardingsphere/readwritesplitting/api/transaction/TransactionReadQueryStrategyAware.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/transaction/TransactionReadQueryStrategyUtil.java
Fixes #23974.
- Rename transaction-read-query-strategy properties name
---
> Rename transaction-read-query-strategy properties name(#23974)

- docs/community/content/team/_index.cn.md
- docs/community/content/team/_index.en.md
Signed-off-by: mlycore <maxwell92@126.com>
- Add Liyao Miao Committers list
---
> update team doc

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/swapper/rule/YamlShardingAutoTableRuleConfigurationSwapper.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/rule/YamlShardingAutoTableRuleConfigurationSwapperTest.java
Fixes #24068 .
- Fix CREATE SHARDING TABLE RULE with audit strategy
- Add related test case
---
> Fix CREATE SHARDING TABLE RULE with audit strategy

- test/e2e/suite/src/test/resources/cases/rql/rql-integration-count.xml
- test/e2e/suite/src/test/resources/cases/rql/rql-integration-show.xml
Ref #23645.
-splitting rql-integration-test-cases.xml file
> Refactor: splitting rql-integration-test-cases.xml file

- agent/plugins/metrics/type/prometheus/src/main/resources/META-INF/conf/prometheus-proxy-advisors.yaml
- proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/command/CommandExecutorTask.java
Fixes #24082.
- Split the `executeCommand` method in `CommandExecutorTask`
- Update pointcut method for metric
---
> Optimize execute latency millis metric

- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPlugin.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPluginTest.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/task/PostgreSQLIncrementTask.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/helper/PipelineCaseHelper.java
- Fix unicode cannot be decoded correctly at TestDecodingPlugin
- E2E add unicode case
---
> Fix unicode char and special char decoding in TestDecodingPlugin for PostgreSQL

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/data/NotImplementComparableValueException.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByMemoryMergedResult.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByRowComparator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByStreamMergedResult.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/orderby/OrderByValue.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/InsertClauseShardingConditionEngine.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/ConditionValue.java
- Update NotImplementComparableValueException message for wrong value
---
> Update NotImplementComparableValueException message for wrong value

- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/commitrollback/MultiTransactionInConnectionTestCase.java
- Fix multiple transactions within a connection integration test 
---
> Fix multiple transactions within a connection integration test

- kernel/logging/core/src/main/java/org/apache/shardingsphere/logging/utils/LoggingUtils.java
- kernel/logging/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.rule.builder.global.DefaultGlobalRuleConfigurationBuilder
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableHandler.java
For #24101.
- Disable logging rule default builder
- Disable synchronize `sql-show` & logging rule props
---
> Disable logging rule default builder

- docs/community/content/involved/contribute/dev-env.cn.md
- docs/community/content/involved/contribute/dev-env.en.md
> Update Java requirement in dev guide

- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/impl/CDCJobAPI.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/context/job/CDCJobItemContext.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/prepare/CDCJobPreparer.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractInventoryIncrementalJobAPIImpl.java
Related to #22500 
- Improve CDC pure incremental mode
- Fix mismatch comment
- Improve CDC prepare stage 
---
> Improve CDC pure incremental mode

- agent/core/src/test/java/org/apache/shardingsphere/agent/core/advisor/config/yaml/swapper/YamlPluginsConfigurationSwapperTest.java
Add TestCase for YamlPluginsConfigurationSwapper
Fixes #23358 .
Created test for YamlPluginsConfigurationSwapper.java
> Add TestCase for YamlPluginsConfigurationSwapper

- kernel/sql-federation/executor/core/src/main/resources/saffron.properties
- test/e2e/suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
- test/e2e/suite/src/test/resources/env/scenario/db/data/actual/dataset.xml
- test/e2e/suite/src/test/resources/env/scenario/db/data/expected/dataset.xml
Fixes #23461.
- Fix chines character encode exception when execute select with sql federation engine
---
> Fix chines character encode exception when execute select with sql federation engine

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
- test/e2e/discovery/src/test/java/org/apache/shardingsphere/test/e2e/discovery/cases/base/BaseDiscoveryE2EIT.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/cases/SQLCommandType.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/cases/assertion/IntegrationTestCase.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/engine/dal/GeneralDALE2EIT.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/framework/param/array/E2ETestParameterGenerator.java
- test/e2e/suite/src/test/resources/cases/dal/dal-integration-set.xml
- test/e2e/suite/src/test/resources/cases/dal/dataset/select_session_variables.xml
Fixes #23325.
- fix IndexOutOfBoundsException when execute set variable statement int jdbc adapter
---
> Fix IndexOutOfBoundsException when execute set variable statement int jdbc adapter

- infra/common/src/main/java/org/apache/shardingsphere/infra/config/props/internal/InternalConfigurationPropertyKey.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariableExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableHandler.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariableExecutorTest.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesExecutorTest.java
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableExecutorTest.java
- test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/show_dist_variables.xml
- DIST VARIABLE support internal property key
- add related test cases
---
> [DistSQL] DIST VARIABLE support internal property key

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/data/pipeline/datasource/creator/ShardingSpherePipelineDataSourceCreator.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/InventoryDumper.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/JDBCStreamQueryUtil.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithmTest.java
- Using streaming query at pipeline inventory dump and data consistency check
---
> Using streaming query at pipeline inventory dump and data consistency check

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSet.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/unsupported/AbstractUnsupportedDatabaseMetaDataResultSet.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnSupportedDatabaseMetaDataResultSetTest.java
Fixes [#23973](https://github.com/apache/shardingsphere/issues/23973)
-
---
> fix get Statement fail

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/db-discovery/show-db-discovery-rule.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/db-discovery/show-db-discovery-rule.en.md
Update document for #24162.
- Update DistSQL `SHOW DB_DISCOVERY RULE` document
---
> Update DistSQL `SHOW DB_DISCOVERY RULE` document

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/db-discovery/show-db-discovery-rule.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/readwrite-splitting/show-readwrite-splitting-rule.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/readwrite-splitting/show-readwrite-splitting-rule.en.md
Update document for #24165.
- Update DistSQL `SHOW READWRITE_SPLITTING RULE` document
---
> Update DistSQL `SHOW READWRITE_SPLITTING RULE` document

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowDefaultShardingStrategyExecutor.java
- test/e2e/suite/src/test/resources/cases/rql/dataset/db/show_default_sharding_strategy.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting/show_default_sharding_strategy.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting_and_encrypt/show_default_sharding_strategy.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/readwrite_splitting/show_default_sharding_strategy.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/sharding_and_encrypt/show_default_sharding_strategy.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/sharding_governance/mysql/show_default_sharding_strategy.xml
- test/e2e/suite/src/test/resources/cases/rql/dataset/tbl/show_default_sharding_strategy.xml
- Refactor `ShowDefaultShardingStrategyExecutor`
---
> Refactor `ShowDefaultShardingStrategyExecutor`

- agent/core/src/test/java/org/apache/shardingsphere/agent/core/plugin/PluginLifecycleServiceManagerTest.java
Fixes #23425 
Created test for PluginLifecycleServiceManager.java
- [✔️ ] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [✔️ ] I have self-reviewed the commit code.
- [✔️ ] I have (or in comment I request) added corresponding labels for the pull request.
- [✔️ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [✔️ ] I have added corresponding unit tests for my changes.
> Add test case for PluginLifecycleServiceManager

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/enums/ShardingStrategyType.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/checker/ShardingRuleStatementCheckerTest.java
> Fix #21055

- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java
- sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractorTest.java
- Fix union extract table error.
---
> Fix union extract table error.

- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
- sql-parser/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
- test/it/parser/src/main/resources/case/dml/select.xml
- test/it/parser/src/main/resources/sql/supported/dml/select.xml
According to the syntax documentation, fix "**INDENT**" and "**DEFAULTS**".
> Fix grammar for oracle xmlSerializeFunction

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/DriverDataSourceCache.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURLManager.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingsphereDriverURLProvider.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/AbsolutePathDriverURLProvider.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/ClasspathDriverURLProvider.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/exception/syntax/DriverURLProviderNotFoundException.java
- jdbc/core/src/main/resources/META-INF/services/org.apache.shardingsphere.driver.jdbc.core.driver.ShardingsphereDriverURLProvider
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURLManagerTest.java
For #23388.
- Abstract the spi of shardingsphere driver url
---
> Abstract the spi of shardingsphere driver url

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereSchema.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/schema/pojo/YamlShardingSphereColumn.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/schema/pojo/YamlShardingSphereConstraint.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/schema/pojo/YamlShardingSphereSchema.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/schema/pojo/YamlShardingSphereTable.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/schema/pojo/YamlShardingSphereView.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/executor/AbstractDatabaseMetaDataExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/postgresql/executor/SelectDatabaseExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/postgresql/executor/SelectTableExecutor.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowTableMetaDataExecutor.java
Correct `meta data` in comments.
---
> Correct meta data in comments.

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/LabelComputeNodeUpdater.java
- proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.update.RALUpdater
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/LabelComputeNodeUpdaterTest.java
For #24181.
Refactor LabelComputeNodeHandler
---
> Refactor LabelComputeNodeHandler

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/UnlabelComputeNodeUpdater.java
- proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.update.RALUpdater
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/UnlabelComputeNodeUpdaterTest.java
For  #24181.
- Refactor `UnlabelComputeNodeHandler`
---
> Refactor `UnlabelComputeNodeHandler`

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetInstanceStatusUpdater.java
- proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.update.RALUpdater
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetInstanceStatusUpdaterTest.java
For #24181.
- Refactor `SetInstanceStatusHandler`
---
> Refactor `SetInstanceStatusHandler`

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationUpdater.java
- proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.update.RALUpdater
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationUpdaterTest.java
For #24181.
- Refactor `ImportDatabaseConfigurationHandler`
---
> Refactor `ImportDatabaseConfigurationHandler`

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/DriverExecutor.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ConnectionManager.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/executor/batch/BatchPreparedStatementExecutorTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnectionTest.java
- kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/ConnectionTransaction.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/commitrollback/MultiJDBCConnectionsTestCase.java
- test/e2e/transaction/src/test/resources/env/it-env.properties
- Fix connection close exception in transaction
---
> Fix connection close exception in transaction

- test/e2e/suite/src/test/resources/cases/rdl/dataset/rdl_empty_rules/drop_single_table_rules.xml
- test/e2e/suite/src/test/resources/cases/rdl/rdl-integration-alter.xml
- test/e2e/suite/src/test/resources/cases/rdl/rdl-integration-create.xml
> Ignore unreasonable case for RDL

- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
- proxy/backend/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/RefreshDatabaseMetaDataUpdater.java
- proxy/backend/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.update.RALUpdater
- proxy/backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/RefreshDatabaseMetaDataUpdaterTest.java
For #24181.
- Refactor `RefreshDatabaseMetaDataHandler`
---
> Refactor `RefreshDatabaseMetaDataHandler`

- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/base/PipelineBaseE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/MariaDBMigrationE2EIT.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/consistencycheck/api/impl/ConsistencyCheckJobAPITest.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/migration/api/impl/MigrationJobAPITest.java
- Add faked MariaDBMigrationE2EIT
- Improve IndexesMigrationE2EIT
- Improve part of pipeline job api unit test
---
> Add faked MariaDBMigrationE2EIT

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/rule/ReadwriteSplittingRule.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/rule/builder/ReadwriteSplittingRuleBuilder.java
- features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/route/ReadwriteSplittingSQLRouterTest.java
- features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/rule/ReadwriteSplittingRuleTest.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/storage/watcher/StorageNodeStateChangedWatcher.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationUpdater.java
> Fix #24275

- infra/common/src/main/java/org/apache/shardingsphere/infra/rule/identifier/type/StaticDataSourceContainedRule.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/ConfigurationChangedSubscriber.java
> Refactor disableDataSources logic when configuration changed.

- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationUpdaterTest.java
- proxy/backend/core/src/test/resources/conf/import/config-encrypt.yaml
- proxy/backend/core/src/test/resources/conf/import/config-mask.yaml
- proxy/backend/core/src/test/resources/conf/import/config-shadow.yaml
Fixes #24279.
- add unit test for `encrypt`
- add unit test for `shadow`
- add unit test for `mask`
---
> Add unit test for `ImportDatabaseConfigurationUpdater`

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/spi/sqlbuilder/PipelineSQLBuilder.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/InventoryTaskSplitter.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/AbstractPipelineSQLBuilder.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/fixture/FixturePipelineSQLBuilder.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/sqlbuilder/MySQLPipelineSQLBuilder.java
- kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/sqlbuilder/MySQLPipelineSQLBuilderTest.java
- kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/sqlbuilder/OpenGaussPipelineSQLBuilder.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/sqlbuilder/PostgreSQLPipelineSQLBuilder.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/fixture/FixturePipelineSQLBuilder.java
Fixes #24291.
- Improve table records count calculation in pipeline job
---
> Improve table records count calculation in pipeline job for MySQL

- .github/workflows/e2e-agent.yml
- test/e2e/agent/plugins/tracing/jaeger/src/test/java/org/apache/shardingsphere/test/e2e/agent/jaeger/JaegerPluginE2EIT.java
- test/e2e/agent/plugins/tracing/opentelemetry/src/test/java/org/apache/shardingsphere/test/e2e/agent/opentelemetry/OpenTelemetryPluginE2EIT.java
- test/e2e/agent/plugins/tracing/zipkin/pom.xml
- test/e2e/agent/plugins/tracing/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/ZipkinPluginE2EIT.java
- test/e2e/agent/plugins/tracing/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/asserts/SpanAssert.java
- test/e2e/agent/plugins/tracing/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/cases/IntegrationTestCases.java
- test/e2e/agent/plugins/tracing/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/cases/IntegrationTestCasesLoader.java
- test/e2e/agent/plugins/tracing/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/cases/SpanTestCase.java
- test/e2e/agent/plugins/tracing/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/cases/TagAssertion.java
- test/e2e/agent/plugins/tracing/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/result/LocalEndpoint.java
- test/e2e/agent/plugins/tracing/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/result/SpanResult.java
- test/e2e/agent/plugins/tracing/zipkin/src/test/resources/cases/execute_sql.xml
- test/e2e/agent/plugins/tracing/zipkin/src/test/resources/cases/parse_sql.xml
- test/e2e/agent/plugins/tracing/zipkin/src/test/resources/cases/root_invoke.xml
- test/e2e/agent/plugins/tracing/zipkin/src/test/resources/env/engine-env.properties
Fixes #24179.
- Optimize zipkin e2e test
---
> Optimize zipkin e2e test

- docs/document/content/reference/gateway/_index.cn.md
> Fixed a typo

- proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/authentication/authenticator/MySQLAuthenticatorTypeTest.java
- proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/authentication/authenticator/impl/MySQLClearPasswordAuthenticatorTest.java
- proxy/frontend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationEngine.java
- proxy/frontend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/authenticator/OpenGaussAuthenticatorType.java
- proxy/frontend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/authenticator/impl/OpenGaussMD5PasswordAuthenticator.java
- proxy/frontend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/authenticator/OpenGaussAuthenticatorTypeTest.java
- proxy/frontend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/authenticator/impl/OpenGaussMD5PasswordAuthenticatorTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/authenticator/PostgreSQLAuthenticatorTypeTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/authenticator/impl/PostgreSQLPasswordAuthenticatorTest.java
Fixes #20619.
Related to #20620.
Now, when Proxy works with openGauss protocol, users can connect using `psql`.
The following two configurations are equivalent:
- No need to specify the `defaultAuthenticator`, because the default is SCRAM_SHA256
```yaml
authority:
users:
- user: root@%
password: root
authenticationMethodName: md5
- user: sharding
password: sharding
authenticators:
md5:
type: MD5
props:
proxy-frontend-database-protocol-type: openGauss
```
- Explicitly specify the `defaultAuthenticator`
```yaml
authority:
users:
- user: root@%
password: root
authenticationMethodName: md5
- user: sharding
password: sharding
authenticators:
md5:
type: MD5
scram_sha256:
type: SCRAM_SHA256
defaultAuthenticator: scram_sha256
props:
proxy-frontend-database-protocol-type: openGauss
```
---
Before …
> Add MD5 password authenticator for openGauss.

- agent/core/src/test/java/org/apache/shardingsphere/agent/core/plugin/config/yaml/swapper/YamlPluginsConfigurationSwapperTest.java
Refactor YamlPluginsConfigurationSwapperTest.
---
> Refactor YamlPluginsConfigurationSwapperTest

- distsql/parser/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java
- distsql/parser/src/test/java/org/apache/shardingsphere/distsql/parser/rdl/RegisterStorageUnitTest.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/value/literal/impl/StringLiteralValue.java
> password support special characters for DistSql

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractInventoryIncrementalJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/InventoryTaskSplitter.java
- kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/sqlbuilder/OpenGaussPipelineSQLBuilder.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/sqlbuilder/PostgreSQLPipelineSQLBuilder.java
- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/impl/ConsistencyCheckJobAPI.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
Fixes #24291
During the testing process, some problems were found and fixed together
- Add PostgreSQL and openGauss estimated count sql
- Fix build insert sql without unique keys of PostgresSQL
- Improve show consistency check remaining_seconds
- Add E2E test case
---
> Add PostgreSQL and openGauss estimated count SQL 

- infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/state/DataSourceStateManager.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/state/exception/UnavailableDataSourceException.java
> Add information when throws UnavailableDataSourceException

- docs/blog/content/material/2022_08_02_Book_Release_“A_Definitive_Guide_to_Apache_ShardingSphere”_is_Published_Internationally.en.md
- docs/blog/content/material/2022_09_02_First_Look_at_ShardingSphere_5.2.0_&_In-Person_Meetup_on_Massive_Data_Management_Practices.en.md
- docs/blog/content/material/2022_09_06_Apache_ShardingSphere_Enterprise_User_Case_-_Energy_Monster.en.md
- docs/blog/content/material/2022_09_08_Apache_ShardingSphere_5.2.0_is_Released,_Bringing_New_Cloud_Native_Possibilities.en.md
- docs/blog/content/material/2022_09_22_How_does_ShardingSphere’s_Show_processlist_&_Kill_Work.en.md
> Article Fixes

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/ConstraintToken.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/ConstraintTokenTest.java
> Fix uppercase table constraint not rewrite exception.

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/UpdatableRALBackendHandler.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactoryTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/RefreshTableMetaDataUpdaterTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableUpdatableRALBackendHandlerTest.java
For #24181.
- Refactor `UpdatableRALBackendHandler`
---
> Refactor `UpdatableRALBackendHandler`

- agent/plugins/tracing/test/pom.xml
- kernel/data-pipeline/cdc/core/pom.xml
- pom.xml
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/MySQLSetVariableAdminExecutorTest.java
- proxy/backend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/PostgreSQLDefaultSessionVariableHandlerTest.java
- src/resources/checkstyle.xml
- src/resources/checkstyle_ci.xml
- test/fixture/infra/pom.xml
- test/fixture/jdbc/pom.xml
- test/it/parser/pom.xml
> Add junit 5' dependencies

- pom.xml
> Adjust junit-jupiter-params's scope

- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaDataTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/GenericSchemaBuilderTest.java
- infra/executor/pom.xml
- infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/process/ExecuteProcessReporterTest.java
> Use MockResourceAutoReleaseExtension on infra modules

- agent/plugins/metrics/core/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/core/exporter/impl/proxy/ProxyMetaDataInfoExporterTest.java
- agent/plugins/metrics/core/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/core/exporter/impl/proxy/ProxyStateExporterTest.java
- agent/plugins/metrics/type/prometheus/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/prometheus/PrometheusPluginLifecycleServiceTest.java
- agent/plugins/tracing/type/opentelemetry/src/test/java/org/apache/shardingsphere/agent/plugin/tracing/opentelemetry/advice/OpenTelemetryCommandExecutorTaskAdviceTest.java
- agent/plugins/tracing/type/opentracing/src/test/java/org/apache/shardingsphere/agent/plugin/tracing/opentracing/advice/OpenTracingCommandExecutorTaskAdviceTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptAssignmentTokenGeneratorTest.java
- features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/CreateReadwriteSplittingRuleStatementUpdaterTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaDataTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/GenericSchemaBuilderTest.java
- infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/process/ExecuteProcessReporterTest.java
- kernel/transaction/type/base/seata-at/pom.xml
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/context/BackendExecutorContextTest.java
- test/it/pipeline/pom.xml
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/migration/api/impl/MigrationJobAPITest.java
- test/util/src/main/java/org/apache/shardingsphere/test/mock/AutoMockExtension.java
> Use AutoMockExtension on test modules

- jdbc/core/pom.xml
- mode/core/src/test/java/org/apache/shardingsphere/mode/metadata/MetaDataContextsFactoryTest.java
- mode/type/standalone/core/src/test/java/org/apache/shardingsphere/mode/manager/standalone/subscriber/ProcessStandaloneSubscriberTest.java
- test/it/pipeline/pom.xml
> Use AutoMockExtension on mode modules

- proxy/bootstrap/pom.xml
- proxy/bootstrap/src/test/java/org/apache/shardingsphere/proxy/version/ShardingSphereProxyVersionTest.java
> Use AutoMockExtension on proxy bootstrap module

- proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/command/CommandExecutorTaskTest.java
- proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/connection/ConnectionLimitContextTest.java
- proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/netty/CDCChannelInboundHandlerTest.java
- proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/netty/FrontendChannelInboundHandlerTest.java
- proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/protocol/FrontDatabaseProtocolTypeFactoryTest.java
- proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/state/impl/OKProxyStateTest.java
- proxy/frontend/type/mysql/pom.xml
- proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/MySQLFrontendEngineTest.java
- proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/authentication/MySQLAuthenticationEngineTest.java
- proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/execute/MySQLComStmtExecuteExecutorTest.java
- proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutorTest.java
- proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLComQueryPacketExecutorTest.java
- proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandlerTest.java
- proxy/frontend/type/opengauss/pom.xml
- proxy/frontend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationEngineTest.java
- proxy/frontend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/command/query/extended/bind/OpenGaussComBatchBindExecutorTest.java
- proxy/frontend/type/postgresql/pom.xml
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/PostgreSQLAuthenticationEngineTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/PostgreSQLCommandExecuteEngineTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PortalTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLAggregatedBatchedStatementsCommandExecutorTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutorTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/bind/PostgreSQLComBindExecutorTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutorTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/parse/PostgreSQLComParseExecutorTest.java
> Use AutoMockExtension on frontend proxy modules

- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/algorithm.en.md
Fixes #24191.
-
- In the document of YAML algorithm configuration, the shadow algorithm configuration item changes `loadBalancers` to `shadowAlgorithms`.
---
> Correct Shadow Algorithm document

- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnectorFactoryTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/ProxySQLExecutorTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/DatabaseConnectorTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/connection/BackendConnectionTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/datasource/JDBCBackendDataSourceTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactoryTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/admin/DatabaseAdminQueryBackendHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/admin/executor/DefaultDatabaseMetaDataExecutorTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/cdc/CDCBackendHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/data/DatabaseBackendHandlerFactoryTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/database/CreateDatabaseBackendHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/database/DatabaseOperateBackendHandlerFactoryTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/advance/ParseDistSQLHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportMetaDataExecutorTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowStatusFromReadwriteSplittingRulesExecutorTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowTableMetaDataExecutorTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/AlterReadwriteSplittingStorageUnitStatusStatementUpdaterTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationUpdaterTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/LabelComputeNodeUpdaterTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/RefreshDatabaseMetaDataUpdaterTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableUpdaterTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetInstanceStatusUpdaterTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/UnlabelComputeNodeUpdaterTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/AlterStorageUnitBackendHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/RegisterStorageUnitBackendHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/UnregisterStorageUnitBackendHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/RuleDefinitionBackendHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionBackendHandlerFactoryTest.java
> Use AutoMockExtension on frontend proxy modules part1

- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManagerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/data/impl/UnicastDatabaseBackendHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/database/DropDatabaseBackendHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/DistSQLBackendHandlerFactoryTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/QueryableRALBackendHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportMetaDataUpdaterTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/RefreshTableMetaDataUpdaterTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionBackendHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/session/ConnectionSessionTest.java
> Use AutoMockExtension on frontend proxy modules part2

- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/connector/jdbc/statement/MySQLStatementMemoryStrictlyFetchSizeSetterTest.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/MySQLAdminExecutorCreatorTest.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/MySQLSetVariableAdminExecutorTest.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowCreateDatabaseExecutorTest.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowCurrentUserExecutorTest.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowDatabasesExecutorTest.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowFunctionStatusExecutorTest.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowProcedureStatusExecutorTest.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowProcessListExecutorTest.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowTablesExecutorTest.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/UseDatabaseExecutorTest.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/information/SelectInformationSchemataExecutorTest.java
- proxy/backend/type/opengauss/pom.xml
- proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/connector/jdbc/statement/OpenGaussStatementMemoryStrictlyFetchSizeSetterTest.java
- proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussSystemCatalogAdminQueryExecutorTest.java
- proxy/backend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/backend/postgresql/connector/jdbc/statement/PostgreSQLStatementMemoryStrictlyFetchSizeSetterTest.java
- proxy/backend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/PostgreSQLDefaultSessionVariableHandlerTest.java
- proxy/backend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/PostgreSQLResetVariableAdminExecutorTest.java
- proxy/backend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/PostgreSQLSetVariableAdminExecutorTest.java
- proxy/backend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/executor/SelectDatabaseExecutorTest.java
- proxy/backend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/executor/SelectTableExecutorTest.java
- proxy/frontend/type/opengauss/pom.xml
> Use AutoMockExtension on backend proxy modules

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactory.java
For #23806.
Remove unused method `getRules`.
> Remove unused method `getRules`.

- kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLBinlogEventPacketDecoderTest.java
- mode/core/src/test/java/org/apache/shardingsphere/mode/manager/switcher/ResourceSwitchManagerTest.java
- mode/core/src/test/java/org/apache/shardingsphere/mode/metadata/persist/service/DatabaseMetaDataPersistServiceTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowStatusFromReadwriteSplittingRulesExecutorTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/RegisterStorageUnitBackendHandlerTest.java
- sql-parser/dialect/mysql/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/mysql/internal/InternalMySQLParserIT.java
- sql-parser/dialect/opengauss/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/opengauss/internal/InternalOpenGaussParserIT.java
- sql-parser/dialect/oracle/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/oracle/internal/InternalOracleParserIT.java
- sql-parser/dialect/postgresql/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/postgresql/internal/InternalPostgreSQLParserIT.java
- sql-parser/dialect/sql92/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/sql92/internal/InternalSQL92ParserIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/MariaDBMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/TextPrimaryKeyMigrationE2EIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalSQLParserIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalSQLParserITSettings.java
- test/it/parser/src/test/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalDistSQLParserIT.java
> Use junit 5.x's API to refactor InternalSQLParserIT

- sql-parser/dialect/mysql/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/mysql/internal/InternalUnsupportedMySQLParserIT.java
- sql-parser/dialect/opengauss/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/opengauss/internal/InternalUnsupportedOpenGaussParserIT.java
- sql-parser/dialect/oracle/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/oracle/internal/InternalUnsupportedOracleParserIT.java
- sql-parser/dialect/postgresql/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/postgresql/internal/InternalUnsupportedPostgreSQLParserIT.java
- sql-parser/dialect/sql92/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/sql92/internal/InternalUnsupportedSQL92ParserIT.java
- sql-parser/dialect/sqlserver/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/sqlserver/internal/InternalUnsupportedSQLServerParserIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalUnsupportedSQLParserIT.java
> Use junit 5.x's API to refactor InternalUnsupportedSQLParserIT

- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/RulesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/MariaDBMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/TextPrimaryKeyMigrationE2EIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalSQLParserIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalUnsupportedSQLParserIT.java
> Upgrade AbstractMigrationE2EIT to junit 5

- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/RulesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/MariaDBMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/TextPrimaryKeyMigrationE2EIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalSQLParserIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalUnsupportedSQLParserIT.java
Reverts apache/shardingsphere#24427
> Revert "Upgrade AbstractMigrationE2EIT to junit 5"

- sql-parser/dialect/mysql/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/mysql/external/ExternalMySQLParserIT.java
- sql-parser/dialect/postgresql/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/postgresql/external/ExternalPostgreSQLParserIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/ExternalSQLParserIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/ExternalSQLParserITSettings.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/loader/ExternalSQLParserTestParameterLoader.java
> Upgrade ExternalSQLParserIT to Junit 5

- kernel/transaction/api/src/main/java/org/apache/shardingsphere/transaction/config/TransactionRuleConfiguration.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/result/type/csv/CsvSQLParseResultReporter.java
> Fix comment

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/pojo/ConsistencyCheckJobItemInfo.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/pojo/InventoryIncrementalJobItemInfo.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/pojo/TableBasedPipelineJobInfo.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/impl/CDCJobAPI.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractInventoryIncrementalJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
- kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckStatusExecutor.java
- kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationJobStatusExecutor.java
- kernel/data-pipeline/distsql/handler/src/test/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckStatusExecutorTest.java
- kernel/data-pipeline/distsql/handler/src/test/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationJobStatusExecutorTest.java
- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/impl/ConsistencyCheckJobAPI.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/migration/api/impl/MigrationJobAPITest.java
- Check dataSourceName exists before migrating table; Add some unit tests
- Add tables column in SHOW MIGRATION STATUS; Refactor getJobProgress and getJobInfo
- Add check_failed_tables column in SHOW MIGRATION CHECK STATUS
---
> Improve migrate table param check; Add column in show migration DistSQLs

- dialect-exception/mysql/src/test/java/org/apache/shardingsphere/dialect/mysql/mapper/MySQLDialectExceptionMapperTest.java
- dialect-exception/mysql/src/test/java/org/apache/shardingsphere/dialect/mysql/vendor/MySQLVendorErrorTest.java
- dialect-exception/postgresql/src/test/java/org/apache/shardingsphere/dialect/postgresql/mapper/PostgreSQLDialectExceptionMapperTest.java
- dialect-exception/postgresql/src/test/java/org/apache/shardingsphere/dialect/postgresql/message/ServerErrorMessageBuilderTest.java
- test/e2e/pipeline/pom.xml
> Upgrade junit 5 on dialect-exception modules

- distsql/parser/src/test/java/org/apache/shardingsphere/distsql/parser/rdl/RegisterStorageUnitTest.java
- distsql/statement/src/test/java/org/apache/shardingsphere/distsql/parser/segment/converter/DataSourceSegmentsConverterTest.java
> Upgrade junit 5 on distsql modules

- features/db-discovery/core/src/test/java/org/apache/shardingsphere/dbdiscovery/checker/DatabaseDiscoveryRuleConfigurationCheckerTest.java
- features/db-discovery/core/src/test/java/org/apache/shardingsphere/dbdiscovery/route/DatabaseDiscoverySQLRouterTest.java
- features/db-discovery/core/src/test/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryDataSourceRuleTest.java
- features/db-discovery/core/src/test/java/org/apache/shardingsphere/dbdiscovery/rule/DatabaseDiscoveryRuleTest.java
- features/db-discovery/core/src/test/java/org/apache/shardingsphere/dbdiscovery/rule/builder/DatabaseDiscoveryRuleBuilderTest.java
- features/db-discovery/core/src/test/java/org/apache/shardingsphere/dbdiscovery/yaml/swapper/YamlDatabaseDiscoveryRuleConfigurationSwapperTest.java
- features/db-discovery/core/src/test/java/org/apache/shardingsphere/dbdiscovery/yaml/swapper/YamlRootRuleConfigurationsForYamlDatabaseDiscoveryRuleConfigurationTest.java
- features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/converter/DatabaseDiscoveryRuleStatementConverterTest.java
- features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/CountDatabaseDiscoveryRuleExecutorTest.java
- features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/ShowDatabaseDiscoveryHeartbeatExecutorTest.java
- features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/ShowDatabaseDiscoveryRuleExecutorTest.java
- features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/query/ShowDatabaseDiscoveryTypeExecutorTest.java
- features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/AlterDatabaseDiscoveryRuleStatementUpdaterTest.java
- features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/CreateDatabaseDiscoveryRuleStatementUpdaterTest.java
- features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/DropDatabaseDiscoveryHeartbeatStatementUpdaterTest.java
- features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/DropDatabaseDiscoveryProviderStatementUpdaterTest.java
- features/db-discovery/distsql/handler/src/test/java/org/apache/shardingsphere/dbdiscovery/distsql/handler/update/DropDatabaseDiscoveryRuleStatementUpdaterTest.java
- features/db-discovery/provider/mysql/src/test/java/org/apache/shardingsphere/dbdiscovery/mysql/type/MGRDatabaseDiscoveryProviderTest.java
- features/db-discovery/provider/mysql/src/test/java/org/apache/shardingsphere/dbdiscovery/mysql/type/MySQLNormalReplicationDatabaseDiscoveryProviderTest.java
- features/db-discovery/provider/opengauss/src/test/java/org/apache/shardingsphere/dbdiscovery/opengauss/OpenGaussNormalReplicationDatabaseDiscoveryProviderTest.java
> Upgrade junit 5 on db-discovery modules

- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/algorithm/encrypt/AESEncryptAlgorithmTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/algorithm/encrypt/RC4EncryptAlgorithmTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/checker/EncryptRuleConfigurationCheckerTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dal/show/DecoratedEncryptShowColumnsMergedResultTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dal/show/MergedEncryptShowColumnsMergedResultTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/EncryptRuleTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/EncryptTableTest.java
- features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleStatementUpdaterTest.java
- features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdaterTest.java
- features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropEncryptRuleStatementUpdaterTest.java
- features/encrypt/plugin/sm/src/test/java/org/apache/shardingsphere/encrypt/sm/algorithm/SM4EncryptAlgorithmTest.java
> Refactor @Test(expected) to assert assertThrows on encrypt modules

- features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/checker/ReadwriteSplittingRuleConfigurationCheckerTest.java
- features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/AlterReadwriteSplittingRuleStatementUpdaterTest.java
- features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/DropReadwriteSplittingRuleStatementUpdaterTest.java
> Refactor @Test(expected) to assert assertThrows on readwrite-splitting modules

- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/algorithm/shadow/column/ColumnRegexMatchShadowAlgorithmTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/algorithm/shadow/column/ColumnValueMatchShadowAlgorithmTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/algorithm/shadow/validator/ShadowValueValidatorTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/AlterDefaultShadowAlgorithmStatementUpdaterTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/AlterShadowRuleStatementUpdaterTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/CreateDefaultShadowAlgorithmStatementUpdaterTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/CreateShadowRuleStatementUpdaterTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/DropDefaultShadowAlgorithmStatementUpdaterTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/DropShadowAlgorithmStatementUpdaterTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/DropShadowRuleStatementUpdaterTest.java
> Refactor @Test(expected) to assertThrows on shadow modules

- mode/type/cluster/repository/provider/nacos/src/test/java/org/apache/shardingsphere/mode/repository/cluster/nacos/NacosRepositoryTest.java
- mode/type/standalone/core/src/test/java/org/apache/shardingsphere/mode/manager/standalone/workerid/generator/StandaloneWorkerIdGeneratorTest.java
> Refactor @Test(expected) to assert assertThrows on mode modules

- sql-parser/engine/src/test/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRuleTest.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/check/datasource/AbstractDataSourceCheckerTest.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/importer/DataRecordMergerTest.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/ingest/channel/memory/ManualBitSetTest.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/metadata/loader/StandardPipelineTableMetaDataLoaderTest.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/metadata/model/PipelineTableMetaDataTest.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/task/InventoryTaskTest.java
> Refactor @Test(expected) to assert assertThrows on test modules

- kernel/data-pipeline/api/src/test/java/org/apache/shardingsphere/data/pipeline/api/datasource/PipelineDataSourceWrapperTest.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/CRC32MatchDataConsistencyCalculateAlgorithmTest.java
- kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/check/datasource/MySQLDataSourceCheckerTest.java
- kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClientTest.java
- kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLBinlogEventPacketDecoderTest.java
- kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiateHandlerTest.java
- kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiatePackageDecoderTest.java
- kernel/data-pipeline/dialect/opengauss/src/test/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPluginTest.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceCheckerTest.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLPositionInitializerTest.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/PostgreSQLLogicalReplicationTest.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALEventConverterTest.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPluginTest.java
- kernel/single/core/src/test/java/org/apache/shardingsphere/single/route/engine/SingleStandardRouteEngineTest.java
- kernel/single/core/src/test/java/org/apache/shardingsphere/single/route/validator/ddl/SingleDropSchemaMetaDataValidatorTest.java
- kernel/sql-federation/executor/advanced/src/test/java/org/apache/shardingsphere/sqlfederation/advanced/result/SQLFederationResultSetTest.java
- kernel/sql-translator/core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/SQLTranslatorRuleTest.java
- kernel/traffic/distsql/handler/src/test/java/org/apache/shardingsphere/traffic/distsql/handler/update/AlterTrafficRuleStatementUpdaterTest.java
- kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/core/ResourceDataSourceTest.java
- kernel/transaction/type/base/seata-at/src/test/java/org/apache/shardingsphere/transaction/base/seata/at/SeataATShardingSphereTransactionManagerTest.java
- kernel/transaction/type/xa/provider/bitronix/src/test/java/org/apache/shardingsphere/transaction/xa/bitronix/manager/BitronixRecoveryResourceTest.java
> Refactor @Test(expected) to assert assertThrows on kernel modules

- jdbc/core/src/test/java/org/apache/shardingsphere/driver/ShardingSphereDriverTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/executor/batch/BatchPreparedStatementExecutorTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/adapter/WrapperAdapterTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSetTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/resultset/GeneratedKeysResultSetMetaDataTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/resultset/GeneratedKeysResultSetTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/EncryptPreparedStatementTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/EncryptStatementTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingPreparedStatementTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ReadwriteSplittingStatementTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatementTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatementTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnSupportedDatabaseMetaDataResultSetTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedGeneratedKeysResultSetTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedOperationConnectionTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedOperationParameterMetaTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedOperationPreparedStatementTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedOperationResultSetTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedOperationStatementTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedUpdateOperationResultSetTest.java
> Refactor @Test(expected) to assert assertThrows on jdbc modules

- test/it/parser/src/main/resources/case/dml/select-expression.xml
Ref #24470.
- Revise pr#24470 xml code style
---
> Revise pr#24470 xml code style

- distsql/parser/src/main/antlr4/imports/Keyword.g4
- distsql/parser/src/main/antlr4/imports/RALStatement.g4
- distsql/parser/src/main/antlr4/org/apache/shardingsphere/distsql/parser/autogen/KernelDistSQLStatement.g4
- distsql/parser/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java
- distsql/statement/src/main/java/org/apache/shardingsphere/distsql/parser/statement/ral/updatable/UnlockClusterStatement.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/state/ClusterStateContextTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/datasource/ShardingSphereDataSourceTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/state/DriverStateContextTest.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/UnlockClusterUpdater.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/lock/impl/ClusterWriteLockStrategy.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/state/impl/ReadOnlyProxyState.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/state/impl/UnavailableProxyState.java
- proxy/backend/core/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.update.RALUpdater
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/context/ProxyContextTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/UnlockClusterUpdaterTest.java
For #24338.
- Add DistSQL UNLOCK CLUSTER
---
> Add DistSQL UNLOCK CLUSTER

- .github/ISSUE_TEMPLATE/feature-request.md
> super tiny grammar change

- docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.en.md
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaDataTest.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ddlgenerator/AbstractPostgreSQLDDLAdapter.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ddlgenerator/PostgreSQLColumnPropertiesAppender.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ddlgenerator/PostgreSQLConstraintsPropertiesAppender.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ddlgenerator/PostgreSQLCreateTableSQLGenerator.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ddlgenerator/PostgreSQLIndexSQLGenerator.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ddlgenerator/PostgreSQLTablePropertiesLoader.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/prepare/datasource/PostgreSQLDataSourcePreparer.java
- sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CreateIndexStatementHandlerTest.java
- sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/DropIndexStatementHandlerTest.java
- sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/DropTableStatementHandlerTest.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/createtable/CreateTableSQLGeneratorIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/env/PipelineE2EEnvironment.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/autocommit/PostgreSQLAutoCommitTestCase.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/truncate/PostgreSQLAndOpenGaussTruncateTestCase.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/engine/base/BaseE2EIT.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/env/TransactionE2EEnvironment.java
- test/e2e/transaction/src/test/resources/env/it-env.properties
- Rename Postgres to PostgreSQL
- Rename PostgresSQL to PostgreSQL
---
> Rename Postgres to PostgreSQL

- docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.en.md
- docs/document/content/user-manual/shardingsphere-proxy/observability/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/observability/_index.en.md
For #24492.
- add agent doc about JDBC
- update agent doc of Proxy
---
> add agent doc about JDBC

- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/state/impl/ReadOnlyProxyStateTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/state/impl/UnavailableProxyStateTest.java
For #24338.
- Add unit test for cluster state
---
> Add test for cluster state

- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/MaskAlgorithmPropsCheckerTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFirstNLastMMaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFromXToYMaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskAfterSpecialCharsAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskBeforeSpecialCharsAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFirstNLastMMaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFromXToYMaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/hash/MD5MaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/replace/GenericTableRandomReplaceAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/replace/LandlineNumberRandomAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/replace/MilitaryIdentityNumberRandomReplaceAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/replace/PersonalIdentityNumberRandomReplaceAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/replace/TelephoneRandomReplaceAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/merge/dql/MaskDQLResultDecoratorTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/rule/builder/MaskRuleBuilderTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/yaml/swapper/YamlMaskRuleConfigurationSwapperTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/yaml/swapper/rule/YamlMaskColumnRuleConfigurationSwapperTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/yaml/swapper/rule/YamlMaskTableRuleConfigurationSwapperTest.java
- features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/converter/MaskRuleStatementConverterTest.java
- features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/query/CountMaskRuleExecutorTest.java
- features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/query/ShowMaskRuleExecutorTest.java
> Use jupiter.api.Test on mask module

- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/algorithm/shadow/column/ColumnRegexMatchShadowAlgorithmTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/algorithm/shadow/column/ColumnValueMatchShadowAlgorithmTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/algorithm/shadow/hint/SQLHintShadowAlgorithmTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/algorithm/shadow/validator/ShadowValueValidatorTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/checker/ShadowRuleConfigurationCheckerTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/route/ShadowSQLRouterTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/route/engine/ShadowRouteEngineFactoryTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/route/engine/determiner/ColumnShadowAlgorithmDeterminerTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/route/engine/determiner/HintShadowAlgorithmDeterminerTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/route/engine/dml/ShadowDeleteStatementRoutingEngineTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/route/engine/dml/ShadowInsertStatementRoutingEngineTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/route/engine/dml/ShadowSelectStatementRoutingEngineTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/route/engine/dml/ShadowUpdateStatementRoutingEngineTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/route/engine/impl/ShadowNonDMLStatementRoutingEngineTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/route/engine/util/ShadowExtractorTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/rule/ShadowRuleTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/rule/builder/ShadowRuleBuilderTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/yaml/swapper/YamlRootRuleConfigurationsForYamlShadowRuleConfigurationTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/yaml/swapper/table/YamlShadowTableConfigurationSwapperTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/converter/ShadowRuleStatementConverterTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/CountShadowRuleExecutorTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowDefaultShadowAlgorithmExecutorTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowAlgorithmExecutorTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowRuleExecutorTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowTableRuleExecutorTest.java
> Use jupiter.api.Test on shadow module

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/InventoryDumper.java
- Update rate limit in inventory dumper streaming query
---
> Update rate limit in inventory dumper streaming query

- kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/converter/YamlUsersConfigurationConverter.java
- kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/yaml/config/YamlAuthorityRuleConfiguration.java
- kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/yaml/config/YamlUserConfiguration.java
- kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/yaml/swapper/YamlAuthorityRuleConfigurationSwapper.java
- kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/yaml/swapper/YamlUserSwapper.java
- kernel/authority/core/src/test/java/org/apache/shardingsphere/authority/yaml/swapper/YamlAuthorityRuleConfigurationSwapperTest.java
- kernel/authority/core/src/test/java/org/apache/shardingsphere/authority/yaml/swapper/YamlEngineUserConfigurationTest.java
- kernel/authority/core/src/test/java/org/apache/shardingsphere/authority/yaml/swapper/YamlUserSwapperTest.java
For #24499.
Move YamlUserConfiguration to authority module.
> Move YamlUserConfiguration to authority module.

- hbase/pom.xml
- hbase/src/main/java/org/apache/shardingsphere/hbase/backend/bean/HBaseCluster.java
- hbase/src/main/java/org/apache/shardingsphere/hbase/backend/config/YamlHBaseConfiguration.java
- hbase/src/main/java/org/apache/shardingsphere/hbase/backend/connector/HBaseAdminCallback.java
- hbase/src/main/java/org/apache/shardingsphere/hbase/backend/connector/HBaseBackgroundExecutorManager.java
- hbase/src/main/java/org/apache/shardingsphere/hbase/backend/connector/HBaseConnectionFactory.java
- hbase/src/main/java/org/apache/shardingsphere/hbase/backend/connector/HBaseExecutor.java
- hbase/src/main/java/org/apache/shardingsphere/hbase/backend/connector/HBaseQueryCallback.java
- hbase/src/main/java/org/apache/shardingsphere/hbase/backend/connector/HBaseTaskExecutorManager.java
- hbase/src/main/java/org/apache/shardingsphere/hbase/backend/connector/HBaseUpdateCallback.java
- hbase/src/main/java/org/apache/shardingsphere/hbase/backend/context/HBaseContext.java
- hbase/src/main/java/org/apache/shardingsphere/hbase/backend/context/HBaseMetaDataRefresher.java
- hbase/src/main/java/org/apache/shardingsphere/hbase/backend/context/HBaseRegionWarmUpContext.java
- hbase/src/main/java/org/apache/shardingsphere/hbase/backend/exception/HBaseOperationException.java
- infra/common/pom.xml
- pom.xml
- proxy/backend/core/pom.xml
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/config/ProxyConfigurationLoader.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/config/YamlProxyConfiguration.java
- proxy/bootstrap/src/main/java/org/apache/shardingsphere/proxy/initializer/BootstrapInitializer.java
> Revise #24401

- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationUpdaterTest.java
Refactor ImportDatabaseConfigurationUpdaterTest.
---
> Refactor ImportDatabaseConfigurationUpdaterTest

- kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/rule/constant/GlobalClockOrder.java
For #24519.
- Modify global clock order
---
> Modify global clock order(#24519)

- features/sharding/plugin/cache/src/test/java/org/apache/shardingsphere/sharding/cache/checker/ShardingRouteCacheableCheckerTest.java
> Upgrade junit 5 for ShardingRouteCacheableCheckerTest

- features/sharding/plugin/cache/src/test/java/org/apache/shardingsphere/sharding/cache/checker/ShardingRouteCacheableCheckerTest.java
- sql-parser/dialect/mysql/src/test/java/org/apache/shardingsphere/sql/parser/mysql/MySQLFormatTest.java
- sql-parser/dialect/mysql/src/test/java/org/apache/shardingsphere/sql/parser/mysql/MySQLParameterizedTest.java
- sql-parser/dialect/mysql/src/test/java/org/apache/shardingsphere/sql/parser/mysql/MySQLTableVisitorTest.java
- sql-parser/dialect/mysql/src/test/java/org/apache/shardingsphere/sql/parser/mysql/MySQLXAVisitorTest.java
- sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/ColumnExtractorParameterizedTest.java
> Upgrade junit 5 ParameterizedTest for parser modules

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/AbstractPipelineSQLBuilder.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/sqlbuilder/MySQLPipelineSQLBuilder.java
- kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/sqlbuilder/OpenGaussPipelineSQLBuilder.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/sqlbuilder/PostgreSQLPipelineSQLBuilder.java
- Quote query column
- Replace List to Set for RESERVED_KEYWORDS in PipelineSQLBuilder impls
---
> Refactor PipelineSQLBuilder column quote and RESERVED_KEYWORDS

- docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/mode.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/mode.en.md
- docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.en.md
> Update documents for optional plugins and mode config

- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/engine/base/TransactionBaseE2EIT.java
> Refactor TransactionBaseE2EIT

- test/e2e/showprocesslist/src/test/java/org/apache/shardingsphere/test/e2e/showprocesslist/container/composer/ClusterShowProcessListContainerComposer.java
- test/e2e/showprocesslist/src/test/java/org/apache/shardingsphere/test/e2e/showprocesslist/engine/ShowProcessListE2EIT.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/engine/base/TransactionBaseE2EIT.java
> Upgrade junit 5 on ShowProcessListE2EIT

- test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/AbstractYamlDataSourceE2EIT.java
- test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/mix/YamlShardingWithReadwriteSplittingE2EIT.java
- test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/readwrite/YamlReadwriteSplittingE2EIT.java
- test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/sharding/YamlShardingE2EIT.java
> Upgrade junit 5 on Yaml DataSource E2E

- agent/plugins/tracing/test/src/main/java/org/apache/shardingsphere/agent/plugin/tracing/TracingAgentExtension.java
- agent/plugins/tracing/test/src/main/java/org/apache/shardingsphere/agent/plugin/tracing/advice/AbstractJDBCExecutorCallbackAdviceTest.java
- agent/plugins/tracing/test/src/main/java/org/apache/shardingsphere/agent/plugin/tracing/advice/AbstractSQLParserEngineAdviceTest.java
- agent/plugins/tracing/type/opentelemetry/src/test/java/org/apache/shardingsphere/agent/plugin/tracing/opentelemetry/advice/OpenTelemetryRootSpanAdviceTest.java
- agent/plugins/tracing/type/opentracing/src/test/java/org/apache/shardingsphere/agent/plugin/tracing/opentracing/advice/OpenTracingRootSpanAdviceTest.java
- test/e2e/agent/plugins/common/src/test/java/org/apache/shardingsphere/test/e2e/agent/common/AgentTestActionExtension.java
- test/e2e/agent/plugins/logging/file/src/test/java/org/apache/shardingsphere/test/e2e/agent/file/FilePluginE2EIT.java
- test/e2e/agent/plugins/metrics/prometheus/src/test/java/org/apache/shardingsphere/test/e2e/agent/metrics/MetricsPluginE2EIT.java
- test/e2e/agent/plugins/tracing/jaeger/src/test/java/org/apache/shardingsphere/test/e2e/agent/jaeger/JaegerPluginE2EIT.java
- test/e2e/agent/plugins/tracing/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/ZipkinPluginE2EIT.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/readonly/SetReadOnlyTestCase.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/engine/base/TransactionBaseE2EIT.java
> Upgrade junit 5 on Agent E2E

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/QueryableRALBackendHandler.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandler.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/UpdatableGlobalRuleRALBackendHandler.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/UpdatableRALBackendHandler.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/readonly/SetReadOnlyTestCase.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/engine/base/TransactionBaseE2EIT.java
Fixes #24181.
Fix TODO in RALBackendHandlerFactory and QueryableRALBackendHandler.
---
> Fix TODO in RALBackendHandlerFactory and QueryableRALBackendHandler.

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/MetaDataReviseEngine.java
- Fix revise engine data source NPE.
---
> Fix revise engine data source NPE.

- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/AbstractMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/RulesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/MariaDBMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/TextPrimaryKeyMigrationE2EIT.java
> Add PipelineContainerComposer

- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/AbstractMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/RulesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/MariaDBMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/TextPrimaryKeyMigrationE2EIT.java
> Refactor PipelineContainerComposer.init()

- docs/README.md
- docs/build-with-docker.sh
for #23762.
- add hudo docker support
---
> Document : add document for hugo docker (#23762)

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxySQLExecutor.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
- Refactor DatabaseConnector and ProxySQLExecutor for multi logic sql transaction control
---
> Refactor DatabaseConnector and ProxySQLExecutor for multi logic sql transaction control

- distsql/parser/src/main/antlr4/imports/RALStatement.g4
- distsql/parser/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java
- distsql/statement/src/main/java/org/apache/shardingsphere/distsql/parser/statement/ral/queryable/ExportStorageNodesStatement.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/distsql/export/ExportedStorageNodes.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportStorageNodesExecutor.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportStorageNodesExecutorTest.java
- proxy/backend/core/src/test/resources/expected/export-storage-nodes.json
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/QueryableRALStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/queryable/ExportStorageNodesStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ral/ExportStorageNodesStatementTestCase.java
- test/it/parser/src/main/resources/case/ral/queryable.xml
- test/it/parser/src/main/resources/sql/supported/ral/queryable.xml
For #24338.
- Refactor export storage nodes, add param databaseName
- Update related test cases
---
> Refactor export storage nodes, add param databaseName

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/set-dist-vairable.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/set-dist-vairable.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-dist-variable.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-dist-variable.en.md
> Update dist variable related document

- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/AbstractMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/RulesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/MariaDBMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/TextPrimaryKeyMigrationE2EIT.java
> Remove PipelineContainerComposer.getTargetTableOrderName()

- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/AbstractMigrationE2EIT.java
> Upgrade junit 5 on CDCE2EIT

- test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/preview_sql.xml
- test/e2e/suite/src/test/resources/cases/ral/dataset/empty_rules/preview_sql_hint.xml
Ref #24403.
- add integration test case for sql hint
---
> Add integration test case for sql hint

- infra/common/src/main/java/org/apache/shardingsphere/infra/context/transaction/TransactionConnectionContext.java
- kernel/global-clock/core/pom.xml
- kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/executor/GlobalClockTransactionExecutor.java
- kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/executor/GlobalClockTransactionHook.java
- kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/executor/OpenGaussGlobalClockTransactionExecutor.java
- kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/rule/GlobalClockRule.java
- kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/rule/builder/GlobalClockRuleBuilder.java
- kernel/global-clock/core/src/main/resources/META-INF/services/org.apache.shardingsphere.globalclock.core.executor.GlobalClockTransactionExecutor
- kernel/global-clock/core/src/main/resources/META-INF/services/org.apache.shardingsphere.transaction.spi.TransactionHook
- kernel/transaction/api/src/main/java/org/apache/shardingsphere/transaction/spi/TransactionHook.java
- kernel/transaction/api/src/main/java/org/apache/shardingsphere/transaction/spi/TransactionHookAdapter.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/config/ProxyConfigurationLoader.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/BackendConnection.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxySQLExecutor.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManager.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManagerTest.java
- proxy/bootstrap/src/main/resources/conf/config-sharding.yaml
- proxy/bootstrap/src/main/resources/conf/server.yaml
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/readonly/SetReadOnlyTestCase.java
- test/e2e/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/engine/base/TransactionBaseE2EIT.java
For #24519 .
- Add transaction hook for global clock
---
> Add transaction hook for global clock(#24519)

- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineE2ECondition.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/createtable/CreateTableSQLGeneratorIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/RulesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/MariaDBMigrationE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/TextPrimaryKeyMigrationE2EIT.java
> Add PipelineE2ECondition

- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/decider/engine/SQLFederationDeciderEngine.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/ShardingSphereDatabase.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/common/SchemaMetaDataLoader.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/common/SchemaMetaDataLoaderTest.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/context/kernel/KernelProcessor.java
- kernel/single/core/src/test/java/org/apache/shardingsphere/single/datanode/SingleTableDataNodeLoaderTest.java
- kernel/single/core/src/test/java/org/apache/shardingsphere/single/rule/SingleRuleTest.java
- proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLAdminExecutorCreator.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/MySQLAdminExecutorCreatorTest.java
Fixes #24642.
- Transparently pass SQL to database when configure data source in system database
- add unit test for change logic
---
> Transparently pass SQL to database when configure data source in system database

- kernel/data-pipeline/cdc/client/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/client/util/ProtobufAnyValueConverter.java
- kernel/data-pipeline/cdc/client/src/test/java/org/apache/shardingsphere/data/pipeline/cdc/client/util/ProtobufAnyValueConverterTest.java
- kernel/data-pipeline/cdc/core/src/test/java/org/apache/shardingsphere/data/pipeline/cdc/util/DataRecordResultConvertUtilTest.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/DataSourceRecordConsumer.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/task/E2EIncrementalTask.java
- test/e2e/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/util/SQLBuilderUtil.java
- Enable CDC E2E IT
- Add struct convert and unit test
---
> Enable CDC E2E IT

- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/engine/BatchE2EITContainerComposer.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/engine/SingleE2EIT.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/engine/dml/BatchDMLE2EIT.java
- test/e2e/suite/src/test/java/org/apache/shardingsphere/test/e2e/framework/param/array/E2ETestParameterFactory.java
> Use BatchE2EITContainerComposer to instead of BatchE2EIT

- agent/core/src/main/java/org/apache/shardingsphere/agent/core/yaml/AgentYamlEngine.java
Fixes #24596..
- Remove non-existing `IOException` comments in javadoc of AgentYamlEngine
---
> fix javadoc error

- features/mask/api/src/main/java/org/apache/shardingsphere/mask/spi/MaskAlgorithm.java
- features/readwrite-splitting/api/src/main/java/org/apache/shardingsphere/readwritesplitting/spi/ReadQueryLoadBalanceAlgorithm.java
- features/shadow/api/src/main/java/org/apache/shardingsphere/shadow/spi/ShadowAlgorithm.java
- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/spi/KeyGenerateAlgorithm.java
- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/spi/ShardingAlgorithm.java
- features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/spi/ShardingAuditAlgorithm.java
- infra/util/src/main/java/org/apache/shardingsphere/infra/util/spi/type/typed/algorithm/ShardingSphereAlgorithm.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/spi/ratelimit/JobRateLimitAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/spi/check/consistency/DataConsistencyCalculateAlgorithm.java
- kernel/traffic/api/src/main/java/org/apache/shardingsphere/traffic/spi/TrafficAlgorithm.java
- kernel/traffic/api/src/main/java/org/apache/shardingsphere/traffic/spi/TrafficLoadBalanceAlgorithm.java
For #24624.
- Refactor algorithm spi
---
> Refactor algorithm spi

- features/shadow/distsql/parser/src/main/antlr4/imports/shadow/Literals.g4
- kernel/data-pipeline/distsql/parser/src/main/antlr4/imports/cdc/RALStatement.g4
- kernel/data-pipeline/distsql/parser/src/main/antlr4/imports/migration/RALStatement.g4
- Make the `IDENTIFIER_`definition in shadow module consistent with others.
- Optimize `jobId` definition
---
> Optimize g4 definition for DistSQL.

- docs/document/content/dev-manual/proxy.cn.md
- docs/document/content/dev-manual/proxy.en.md
Fixes #24672.
- fix an err in https://shardingsphere.apache.org/document/current/en/dev-manual/proxy/
---
> fix:  an error in the proxy document included in the dev-manual package.

- agent/plugins/metrics/type/prometheus/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/prometheus/PrometheusPluginLifecycleServiceTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/database/CreateDatabaseBackendHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/database/DropDatabaseBackendHandlerTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/AlterReadwriteSplittingStorageUnitStatusStatementUpdaterTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionBackendHandlerFactoryTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionBackendHandlerTest.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/connector/jdbc/statement/MySQLStatementMemoryStrictlyFetchSizeSetterTest.java
- proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/connector/jdbc/statement/OpenGaussStatementMemoryStrictlyFetchSizeSetterTest.java
- proxy/backend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/backend/postgresql/connector/jdbc/statement/PostgreSQLStatementMemoryStrictlyFetchSizeSetterTest.java
- proxy/backend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/executor/SelectDatabaseExecutorTest.java
- proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/command/CommandExecutorTaskTest.java
- proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/connection/ConnectionLimitContextTest.java
- proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/protocol/FrontDatabaseProtocolTypeFactoryTest.java
- proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandlerTest.java
- Remove useless static from test classes
- Optime setup for CommandExecutorTaskTest.
---
> Remove useless static from test classes.

- sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
- test/it/parser/src/main/resources/case/dml/select-special-function.xml
> Fix mysql cast function parsing error (#24637)

- docs/community/content/team/_index.cn.md
- docs/community/content/team/_index.en.md
> Update committer list

- proxy/backend/type/hbase/src/test/java/org/apache/shardingsphere/proxy/backend/hbase/checker/CommonHeterogeneousSQLStatementCheckerTest.java
- proxy/backend/type/hbase/src/test/java/org/apache/shardingsphere/proxy/backend/hbase/checker/HBaseDatabaseCheckerFactoryTest.java
- proxy/backend/type/hbase/src/test/java/org/apache/shardingsphere/proxy/backend/hbase/checker/HeterogeneousDeleteStatementCheckerTest.java
- proxy/backend/type/hbase/src/test/java/org/apache/shardingsphere/proxy/backend/hbase/checker/HeterogeneousInsertStatementCheckerTest.java
- proxy/backend/type/hbase/src/test/java/org/apache/shardingsphere/proxy/backend/hbase/checker/HeterogeneousSelectStatementCheckerTest.java
- proxy/backend/type/hbase/src/test/java/org/apache/shardingsphere/proxy/backend/hbase/checker/HeterogeneousUpdateStatementCheckerTest.java
> Upgrade junit 5 on HBase checker test

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
- infra/common/src/main/resources/schema/mysql/information_schema/character_sets.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/collation_character_set_applicability.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/collations.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/column_privileges.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/columns.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/engines.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/events.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/files.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/global_status.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/global_variables.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/tables.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/views.yaml
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
For #24662.
- Add mysql information_schema tables
---
> Add mysql information_schema tables(#24662)

- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/BackendConnectionTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/MockConnectionUtil.java
> Fix failure cases in BackendConnectionTest

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/data/ShardingStatisticsTableCollector.java
> Fix e2e dql it error.

- kernel/logging/core/src/main/java/org/apache/shardingsphere/logging/utils/LogbackUtils.java
- kernel/logging/core/src/main/java/org/apache/shardingsphere/logging/utils/LoggingUtils.java
> Refactor LoggingUtils to move out codes related to logback

- features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/converter/MaskRuleStatementConverter.java
- features/shadow/distsql/parser/src/main/java/org/apache/shardingsphere/shadow/distsql/parser/core/ShadowDistSQLStatementVisitor.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/converter/ShardingTableRuleStatementConverter.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterDefaultShardingStrategyStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateDefaultShardingStrategyStatementUpdater.java
Optimize toLowerCase() in DistSQL.
> Optimize toLowerCase() in DistSQL.

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/condition/impl/EncryptBinaryCondition.java
- test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-aggregate.xml
Ref #24337.
- fix rewrite exception when execute encrypt like concat with prepared statement
- add e2e test case
---
> Fix rewrite exception when execute encrypt like concat with prepared statement

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java
- Fix get data node empty for broadcast.
---
> Fix get data node empty for broadcast.

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
- Refactor DatabaseConnector for sql statement optimize
---
> Refactor DatabaseConnector for sql statement optimize

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/mod/HashModShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/mod/ModShardingAlgorithm.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/mod/HashModShardingAlgorithmTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/mod/ModShardingAlgorithmTest.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/fixture/sharding/CoreAutoShardingAlgorithmFixture.java
- Improve init check of ShardingAutoTableAlgorithm
---
> Improve init check of ShardingAutoTableAlgorithm

- test/e2e/agent/plugins/metrics/prometheus/pom.xml
- test/e2e/agent/plugins/tracing/jaeger/pom.xml
- test/e2e/agent/plugins/tracing/zipkin/pom.xml
For #24758.
- update profile id in pom.xml of prometheus, jager, zipkin
---
> update profile id in pom.xml of prometheus, jager, zipkin

- pom.xml
> Add io.smallrye:jandex-maven-plugin

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/metadata/dialect/H2SchemaMetaDataLoader.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/metadata/dialect/H2SchemaMetaDataLoaderTest.java
> Fix case sensitive issue when loading schema meta data with H2 database

- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/translatable/ParseRexNodeVisitorImpl.java
Ref #23703.
- Revise pr 23703
---
> Revise pr 23703

- infra/common/src/main/java/org/apache/shardingsphere/infra/rule/identifier/type/ColumnContainedRule.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AbstractResultSetAdapter.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSet.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSetMetaData.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/adapter/ResultSetAdapterTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/adapter/ResultSetGetterAdapterTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSetTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedOperationResultSetTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedUpdateOperationResultSetTest.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
> Avoid repeat call findRules method

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
> Refactor DatabaseConnector avoid repeat call findRules method

- features/db-discovery/distsql/parser/src/main/antlr4/imports/db-discovery/BaseRule.g4
- features/db-discovery/distsql/parser/src/main/antlr4/imports/db-discovery/Keyword.g4
- features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/BaseRule.g4
- features/mask/distsql/parser/src/main/antlr4/imports/mask/BaseRule.g4
- features/mask/distsql/parser/src/main/antlr4/imports/mask/Keyword.g4
- features/readwrite-splitting/distsql/parser/src/main/antlr4/imports/readwrite-splitting/BaseRule.g4
- features/readwrite-splitting/distsql/parser/src/main/antlr4/imports/readwrite-splitting/Keyword.g4
- features/shadow/distsql/parser/src/main/antlr4/imports/shadow/BaseRule.g4
- features/sharding/distsql/parser/src/main/antlr4/imports/sharding/BaseRule.g4
> Update build-in algorithm type in DistSQL

- test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/base/BaseTransactionTestCase.java
- test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/nested/NestedTransactionTestCase.java
- test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/readwritesplitting/ReadwriteSplittingInTransactionTestCase.java
- test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/settype/SetTransactionTypeTestCase.java
- test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/env/TransactionE2EEnvironment.java
- test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/framework/container/compose/DockerContainerComposer.java
- test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/util/TestCaseClassScanner.java
- test/e2e/operation/transaction/src/test/resources/env/it-env.properties
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/data/actual/databases.xml
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/data/actual/dataset.xml
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/data/actual/init-sql/mysql/01-actual-init.sql
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/data/actual/init-sql/opengauss/01-actual-init.sql
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/data/actual/init-sql/postgresql/01-actual-init.sql
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/data/expected/databases.xml
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/data/expected/dataset.xml
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/data/expected/init-sql/mysql/01-expected-init.sql
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/data/expected/init-sql/opengauss/01-expected-init.sql
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/data/expected/init-sql/postgresql/01-expected-init.sql
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/jdbc/conf/mysql/config-readwrite-splitting-local.yaml
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/jdbc/conf/mysql/config-readwrite-splitting-xa-atomikos.yaml
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/jdbc/conf/mysql/config-readwrite-splitting-xa-narayana.yaml
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/proxy/conf/mysql/config-readwrite-splitting.yaml
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/proxy/conf/opengauss/config-readwrite-splitting.yaml
- test/e2e/operation/transaction/src/test/resources/env/scenario/readwrite-splitting/proxy/conf/postgresql/config-readwrite-splitting.yaml
- Add readwrite splitting e2e in transaction
---
> Add readwrite splitting e2e in transaction

- examples/example-core/example-api/src/main/java/org/apache/shardingsphere/example/core/api/DataSourceUtils.java
- examples/shardingsphere-example-generator/src/main/java/org/apache/shardingsphere/example/generator/core/ExampleGenerator.java
- examples/shardingsphere-example-generator/src/main/java/org/apache/shardingsphere/example/generator/core/GenerateUtils.java
- examples/shardingsphere-example-generator/src/main/java/org/apache/shardingsphere/example/generator/core/impl/JDBCExampleGenerator.java
- examples/shardingsphere-example-generator/src/main/java/org/apache/shardingsphere/example/generator/core/impl/ProxyExampleGenerator.java
- examples/shardingsphere-proxy-example/shardingsphere-proxy-distsql-example/src/main/java/org/apache/shardingsphere/example/proxy/distsql/DistSQLFeatureExample.java
- examples/shardingsphere-proxy-example/shardingsphere-proxy-distsql-example/src/main/java/org/apache/shardingsphere/example/proxy/distsql/util/FileUtils.java
For #24622 .
- The modules involved are: `examples`
---
> Rename xxUtil to xxUtils

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
- infra/common/src/main/resources/schema/mysql/information_schema/innodb_sys_fields.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/innodb_sys_foreign.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/innodb_sys_foreign_cols.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/innodb_sys_indexes.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/innodb_sys_tables.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/innodb_sys_tablespaces.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/innodb_sys_tablestats.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/innodb_sys_virtual.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/innodb_temp_table_info.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/innodb_trx.yaml
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_sys_fields.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_sys_foreign.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_sys_foreign_cols.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_sys_indexes.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_sys_tables.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_sys_tablespaces.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_sys_tablestats.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_sys_virtual.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_temp_table_info.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_innodb_trx.xml
- test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema.xml
For #24662 .
- Add more MySQL information_schema tables
---
> Add more MySQL information_schema tables

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/LockClusterUpdater.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/UnlockClusterUpdater.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/lock/impl/ClusterReadWriteLockStrategy.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/lock/impl/ClusterWriteLockStrategy.java
For #24338.
- Refactor cluster lock
---
> Refactor cluster lock

- docs/community/content/team/_index.cn.md
- docs/community/content/team/_index.en.md
> Add a new committer

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/PipelineAPIFactory.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingSphereDataJobWorker.java
- src/resources/spotbugs.xml
> Fix spot bugs JLM

- features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/route/standard/StandardReadwriteSplittingDataSourceRouterTest.java
> Add test cases for StandardReadwriteSplittingDataSourceRouter

- pom.xml
> Fix : avoid the error when report by javadoc plugin

- test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/arg/E2ETestCaseArgumentsProvider.java
- test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/framework/param/array/E2ETestParameterGenerator.java
- test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/framework/param/model/AssertionTestParameter.java
- test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/framework/param/model/CaseTestParameter.java
- test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/framework/param/model/E2ETestParameter.java
> Split test case docker container to fix ci error.

- infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesValidator.java
> Fix #24882

- pom.xml
Fixes #24996.
- remove some useless cofiguration for reporting plugins
---
> Refactor : remove some useless cofiguration for reporting plugins

- sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLTCLStatementSQLVisitor.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/tcl/MySQLReleaseSavepointStatement.java
- test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/savepoint/BaseSavePointTestCase.java
- Fix release savepoint in MySQL
---
> Fix release savepoint in MySQL

- kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/ConnectionSavepointManager.java
- kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/ConnectionSavepointManagerTest.java
- test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/savepoint/MySQLSavePointTestCase.java
- test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/settype/TransactionTypeHolderTestCase.java
- test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/engine/base/TransactionBaseE2EIT.java
- Support release savepoint in MySQL
---
> Support release savepoint in MySQL

- docs/community/content/powered-by/_index.cn.md
> Update user cases

- docs/community/content/involved/contribute/dev-env.cn.md
- docs/community/content/involved/contribute/dev-env.en.md
Ref #24877.
- After maven-checkstyle-plugin upgrade to 3.2.1, we need update document for checkStyle settings
---
> Update document for checkStyle settings

- .mvn/wrapper/maven-wrapper.properties
> Bump Maven to 3.8.7 to fix occasional multi-thread building failure

- distribution/proxy-native/src/main/release-docs/LICENSE
- distribution/proxy/src/main/release-docs/LICENSE
- pom.xml
> Fix the dependency of jackson-dataformat-yaml and upgrade jackson to 2.14.0

- proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussSystemCatalogAdminQueryExecutor.java
- src/resources/spotbugs.xml
> Fix spotbugs issues in openGauss backend module

- docs/community/content/involved/release/shardingsphere.cn.md
- docs/community/content/involved/release/shardingsphere.en.md
https://lists.apache.org/thread/w4d7jozl5x2l1x37o6f7okycx5s3syco
> Integrate community suggestion into release guide

- pom.xml
Fixes #25029.
- remove report duplicated plugin and fix OOM issue
---
> Refactor : remove report duplicated plugin and fix OOM issue

- distribution/proxy/src/main/assembly/shardingsphere-proxy-binary-distribution.xml
Fixes #24005.
- Remove meaningless assembly configuration.
---
> Remove meaningless assembly configuration

- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rql/RQLStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rql/impl/ShowStorageUnitsStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rql/impl/ShowTablesStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rql/impl/table/ShowSingleTablesStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rql/storage/unit/ShowRulesUsedStorageUnitStatementTestCase.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rql/storage/unit/ShowStorageUnitsStatementTestCase.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rql/table/ShowLogicalTableStatementTestCase.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rql/table/ShowSingleTableStatementTestCase.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rql/table/ShowTableStatementTestCase.java
- test/it/parser/src/main/resources/case/rql/show.xml
- test/it/parser/src/main/resources/sql/supported/rql/show.xml
Add parse test for:
- SHOW SINGLE TABLES
- SHOW LOGICAL TABLES
- SHOW STORAGE UNITS
> Add parse test for some RQL.

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
- infra/common/src/main/resources/schema/mysql/information_schema/session_status.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/session_variables.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/statistics.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/table_constraints.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/table_privileges.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/tablespaces.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/triggers.yaml
- infra/common/src/main/resources/schema/mysql/information_schema/user_privileges.yaml
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_schemata.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_session_status.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_session_variables.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_statistics.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_table_constraints.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_table_privileges.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_tables.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_tablespaces.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_triggers.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_user_privileges.xml
- test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema.xml
For #24662 .
- Add more information_schema tables
---
> Add more information_schema tables

- pom.xml
- add config for checkstyle report
- add output path for spotbugs report
- refactor the project name to `Apache ShardingSphere`
- add distribution management for mvn site:stage
---
> Refactor : add configuration for report plugins

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/ingest/InventoryDumperConfiguration.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/InventoryDumper.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryIncrementalTasksRunner.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/prepare/MigrationJobPreparer.java
Improve inventory task dumper to support more scenarios
- Improve inventory task dumper at pipeline
---
> Improve inventory task dumper at pipeline

- kernel/traffic/core/src/main/java/org/apache/shardingsphere/traffic/algorithm/traffic/segment/SQLMatchTrafficAlgorithm.java
- kernel/traffic/core/src/main/java/org/apache/shardingsphere/traffic/algorithm/traffic/segment/SQLRegexTrafficAlgorithm.java
- kernel/traffic/core/src/main/java/org/apache/shardingsphere/traffic/exception/segment/SegmentTrafficAlgorithmInitializationException.java
- kernel/traffic/core/src/test/java/org/apache/shardingsphere/traffic/algorithm/traffic/segment/SQLMatchTrafficAlgorithmTest.java
- kernel/traffic/core/src/test/java/org/apache/shardingsphere/traffic/algorithm/traffic/segment/SQLRegexTrafficAlgorithmTest.java
> Improve properties verification of TrafficAlgorithm #24754

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
- infra/common/src/main/resources/schema/mysql/mysql/columns_priv.yaml
- infra/common/src/main/resources/schema/mysql/mysql/engine_cost.yaml
- infra/common/src/main/resources/schema/mysql/mysql/event.yaml
- infra/common/src/main/resources/schema/mysql/mysql/func.yaml
- infra/common/src/main/resources/schema/mysql/mysql/general_log.yaml
- infra/common/src/main/resources/schema/mysql/mysql/gtid_executed.yaml
- infra/common/src/main/resources/schema/mysql/mysql/help_category.yaml
- infra/common/src/main/resources/schema/mysql/mysql/help_keyword.yaml
- infra/common/src/main/resources/schema/mysql/mysql/help_relation.yaml
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_columns_priv.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_db.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_engine_cost.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_event.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_func.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_general_log.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_gtid_executed.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_help_category.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_help_keyword.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_help_relation.xml
- test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema.xml
For #24662 .
- Add mysql schema tables
---
> Add mysql schema tables

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
- infra/common/src/main/resources/schema/mysql/mysql/help_topic.yaml
- infra/common/src/main/resources/schema/mysql/mysql/innodb_index_stats.yaml
- infra/common/src/main/resources/schema/mysql/mysql/innodb_table_stats.yaml
- infra/common/src/main/resources/schema/mysql/mysql/ndb_binlog_index.yaml
- infra/common/src/main/resources/schema/mysql/mysql/plugin.yaml
- infra/common/src/main/resources/schema/mysql/mysql/proc.yaml
- infra/common/src/main/resources/schema/mysql/mysql/procs_priv.yaml
- infra/common/src/main/resources/schema/mysql/mysql/proxies_priv.yaml
- infra/common/src/main/resources/schema/mysql/mysql/server_cost.yaml
- infra/common/src/main/resources/schema/mysql/mysql/servers.yaml
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_help_topic.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_innodb_index_stats.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_innodb_table_stats.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_ndb_binlog_index.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_plugin.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_proc.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_procs_priv.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_proxies_priv.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_server_cost.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_mysql_servers.xml
- test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema.xml
For #24662 .
- Add more mysql schema tables
---
> Add more mysql schema tables

- proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/state/impl/OKProxyState.java
> Code cleanup for OKProxyState

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/data/ShardingStatisticsTableCollector.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/ProjectionsTokenGenerator.java
- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationProjection.java
- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/table/TablesContext.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilder.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/common/SchemaMetaDataLoader.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/util/SystemSchemaUtils.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AbstractStatementAdapter.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/JDBCStreamQueryUtils.java
- kernel/sql-federation/executor/advanced/src/main/java/org/apache/shardingsphere/sqlfederation/advanced/resultset/SQLFederationResultSet.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/MetaDataContexts.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionBackendHandler.java
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/task/E2EIncrementalTask.java
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/helper/PipelineCaseHelper.java
Fixes #25113.
- Replace `databaseType instanceof PostgreSQLDatabaseType || databaseType instanceof OpenGaussDatabaseType` with `databaseType instanceof SchemaSupportedDatabaseType`
> Fixes #25113. Optimize usage of PostgreSQLDatabaseType and OpenGaussDatabaseType

- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/MetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/DataSourcePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/DatabaseRuleBasedPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/DatabaseRulePersistService.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/ClusterModeContextManager.java
- mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneModeContextManager.java
> Add DatabaseRuleBasedPersistService to prepare load single table #22887

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
- infra/common/src/main/resources/schema/mysql/performance_schema/accounts.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/cond_instances.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/events_stages_current.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/events_stages_history.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/events_stages_history_long.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/events_stages_summary_by_account_by_event_name.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/events_stages_summary_by_host_by_event_name.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/events_stages_summary_by_thread_by_event_name.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/events_stages_summary_by_user_by_event_name.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/events_stages_summary_global_by_event_name.yaml
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_accounts.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_cond_instances.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_stages_current.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_stages_history.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_stages_history_long.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_stages_summary_by_account_by_event_name.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_stages_summary_by_host_by_event_name.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_stages_summary_by_thread_by_event_name.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_stages_summary_by_user_by_event_name.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_events_stages_summary_global_by_event_name.xml
- test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema.xml
For #24662 .
- Add mysql performance_schema tables
---
> Add mysql performance_schema tables

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/util/SchemaMetaDataUtils.java
> bug fixed: NoSuchElementException occurred when create mask rule. 

- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/checker/ShadowRuleStatementChecker.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/AlterShadowRuleStatementUpdater.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/CreateShadowRuleStatementUpdater.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/AlterShadowRuleStatementUpdaterTest.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/update/CreateShadowRuleStatementUpdaterTest.java
- features/shadow/distsql/statement/src/main/java/org/apache/shardingsphere/shadow/distsql/parser/segment/ShadowAlgorithmSegment.java
Fixes #25099.
- Remove redundant check in shadow rule
---
> Remove redundant check in shadow rule

- dialect-exception/postgresql/src/main/java/org/apache/shardingsphere/dialect/postgresql/exception/PostgreSQLException.java
> Revise code style in PostgreSQLException

- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/algorithm/shadow/column/ColumnRegexMatchShadowAlgorithmTest.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/algorithm/shadow/column/ColumnValueMatchShadowAlgorithmTest.java
Fixes #24749.
-Improve properties verification of ShadowAlgorithm
---
> Improve properties verification of ShadowAlgorithms #24749

- src/resources/checkstyle.xml
- src/resources/pmd.xml
For #25135.
- fix the pmd config since pmd upgrade
---
> Fix : fix the pmd config since pmd upgrade

- pom.xml
For #25135.
- remove class in test package from xref
---
> Remove : remove class in test package from xref (#25135)

- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/readwrite-splitting.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/readwrite-splitting.en.md
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/group/ReadwriteSplittingGroup.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/group/type/StaticReadwriteSplittingGroup.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/route/standard/StandardReadwriteSplittingDataSourceRouter.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/rule/ReadwriteSplittingDataSourceRule.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/rule/ReadwriteSplittingRule.java
- features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/rule/ReadwriteSplittingRuleTest.java
> Rename ReadwriteSplittingStrategy to ReadwriteSplittingGroup

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/PipelineJobIdUtils.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/util/InstanceTypeUtils.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/job/util/InstanceTypeUtilsTest.java
- Rename InstanceTypeUtil to InstanceTypeUtils
- Rename InstanceTypeUtilTest to InstanceTypeUtilsTest
---
> Rename InstanceTypeUtil to InstanceTypeUtils

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/keygen/SnowflakeKeyGenerateAlgorithm.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/keygen/SnowflakeKeyGenerateAlgorithmTest.java
- features/sharding/plugin/cosid/src/main/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdSnowflakeKeyGenerateAlgorithm.java
- features/sharding/plugin/cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdSnowflakeKeyGenerateAlgorithmTest.java
Fixes #24750 .
- Improve initial checks of CosIdSnowflakeKeyGenerateAlgorithm.
- Improve initial checks of SnowflakeKeyGenerateAlgorithm.
---
> improve properties verification of key generate algorithms

- pom.xml
For #25135.
- aggregate javadoc into maven report
---
> Aggregate javadoc

- distsql/parser/src/main/antlr4/imports/Keyword.g4
For #24187.
- remove DISCARD from DistSQL keyword.
> Revise-24187, remove DISCARD from DistSQL keyword.

- docs/blog/content/material/2023_03_21_Streamlining_Database_Configuration_with_DistSQL's_Export,_Import,_and_YAML_Conversion.en.md
- docs/blog/resources/_gen/assets/scss/scss/tale.scss_5ad6f408b0e3e473c748aac88af0ea18.content
- docs/blog/themes/tale4zh/assets/scss/tale/_code.scss
fix code style  && modify en 2023-03-21 content
> feat:modify blog en content

- jdbc/core/pom.xml
- proxy/bootstrap/pom.xml
- Add runtime scope for h2 in jdbc-core & bootstrap
---
> Add runtime scope for h2 in jdbc-core & bootstrap

- docs/document/content/features/transaction/appendix.cn.md
- docs/document/content/features/transaction/appendix.en.md
- Add xa transaction required privilege document
---
> Add xa transaction required privilege document

- infra/common/src/test/java/org/apache/shardingsphere/infra/database/metadata/dialect/OpenGaussDataSourceMetaDataTest.java
> Unify the format of jdbc:opengauss

- db-protocol/core/src/main/java/org/apache/shardingsphere/db/protocol/event/WriteCompleteEvent.java
- db-protocol/core/src/main/java/org/apache/shardingsphere/db/protocol/netty/ProxyFlowControlHandler.java
- db-protocol/core/src/test/java/org/apache/shardingsphere/db/protocol/netty/ProxyFlowControlHandlerTest.java
- db-protocol/mysql/src/test/java/org/apache/shardingsphere/db/protocol/mysql/netty/MySQLSequenceIDInboundHandlerTest.java
- proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/command/CommandExecutorTask.java
> Refactor WriteCompleteEvent

- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesExecutorTest.java
- Fix unit test in SHOW DIST VARIABLES
---
> Fix unit test in SHOW DIST VARIABLES

- kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/rule/AuthorityRule.java
- kernel/authority/core/src/test/java/org/apache/shardingsphere/authority/rule/AuthorityRuleTest.java
> Remove useless method refresh from AuthorityRule.

- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/LiteralExpressionConverter.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/TrimFunctionConverter.java
- sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
- test/it/optimizer/src/test/java/org/apache/shardingsphere/test/it/optimize/SQLNodeConverterEngineIT.java
- test/it/parser/src/main/resources/case/dml/select-special-function.xml
- test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml
Ref #25189.
- Revise pr 25189 for code style
---
> Revise pr 25189 for code style

- proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLSetVariableAdminExecutor.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/MySQLSetVariableAdminExecutorTest.java
- proxy/backend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/PostgreSQLSetVariableAdminExecutorTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PortalTest.java
- sql-parser/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
- sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/format/impl/MySQLFormatSQLVisitor.java
- sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDALStatementSQLVisitor.java
- sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
- sql-parser/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/impl/OpenGaussDALStatementSQLVisitor.java
- sql-parser/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLDALStatementSQLVisitor.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dal/VariableSegment.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dal/impl/SetParameterStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedExpression.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedVariableSegment.java
- test/it/parser/src/main/resources/case/dml/select-expression.xml
- test/it/parser/src/main/resources/case/dml/select.xml
- test/it/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #25138.
https://github.com/mysql/mysql-server/blob/mysql-8.0.32/sql/sql_yacc.yy#L11529-L11539
https://github.com/mysql/mysql-server/blob/mysql-8.0.32/sql/sql_yacc.yy#L16001-L16015
> Fix variable was not parsed into VariableSegment

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescription.java
- docs/document/content/features/transaction/appendix.cn.md
- docs/document/content/features/transaction/appendix.en.md
- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- infra/common/src/main/java/org/apache/shardingsphere/infra/exception/UnsupportedStorageTypeException.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/factory/ExternalMetaDataFactory.java
- kernel/transaction/type/xa/core/src/test/java/org/apache/shardingsphere/transaction/xa/jta/datasource/checker/MySQLDataSourcePrivilegeCheckerTest.java
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLTimeTypesMigrationE2EIT.java
- Add unsupported storage type check
---
> Add unsupported storage type check

- db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/codec/MySQLPacketCodecEngine.java
- db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/binlog/row/column/value/integer/MySQLBitBinlogProtocolValue.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/InsertCipherNameTokenGenerator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/ShardingInsertValuesTokenGenerator.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/datatype/DataTypeLoader.java
- infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/context/SQLRewriteContext.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/util/ColumnValueConvertUtils.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/DataRecordMerger.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/DataSourceImporter.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiateHandler.java
- kernel/sql-federation/executor/advanced/src/main/java/org/apache/shardingsphere/sqlfederation/advanced/resultset/SQLFederationResultSet.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/metadata/watcher/MetaDataChangedWatcher.java
- sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
> Fix pmd check for UselessParentheses

- src/resources/pmd.xml
> Exclude PreserveStackTrace rule for pmd

- docs/document/content/faq/_index.cn.md
- docs/document/content/faq/_index.en.md
- Add unwrap mysql connection exception doc
---
> Add unwrap mysql connection exception FAQ doc

- src/resources/pmd.xml
> Refactor rule checks for pmd

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/condition/impl/EncryptBinaryCondition.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/job/CDCJob.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractInventoryIncrementalJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/datasource/DefaultPipelineDataSourceManager.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/config/MigrationJobConfiguration.java
- kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/provider/GlobalClockProvider.java
- kernel/single/core/src/main/java/org/apache/shardingsphere/single/route/engine/SingleStandardRouteEngine.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/translatable/TranslatableTableScan.java
- kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/datasource/checker/dialect/MySQLDataSourcePrivilegeChecker.java
> Fix MissingOverride rule for pmd

- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/BinaryOperationExpressionConverter.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/LiteralExpressionConverter.java
- sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
- test/it/optimizer/src/test/java/org/apache/shardingsphere/test/it/optimize/SQLNodeConverterEngineIT.java
- test/it/parser/src/main/resources/case/dml/select-special-function.xml
Fixes #24200 .
Support for Extract function
Support for BitExpr Mod
> Support for Extract, BitExpr Mod

- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiatePackageDecoder.java
- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/TranslatableTableScanExecutor.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/config/yaml/swapper/YamlProxyConfigurationSwapper.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/executor/callback/ProxyJDBCExecutorCallback.java
- proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/connector/sane/MySQLSaneQueryResultEngine.java
> Fix UnusedFormalParameter rule for pmd

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptPredicateColumnTokenGenerator.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/checker/ShardingTableRuleStatementChecker.java
- infra/util/src/main/java/org/apache/shardingsphere/infra/util/expr/InlineExpressionParser.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/LiteralExpressionConverter.java
- mode/type/cluster/repository/provider/nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/util/NacosMetaDataUtils.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionXAHandler.java
- proxy/backend/type/hbase/src/main/java/org/apache/shardingsphere/proxy/backend/hbase/checker/CommonHeterogeneousSQLStatementChecker.java
- proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowTransactionExecutor.java
> Fix LiteralsFirstInComparisons rule for pmd

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/GenericSchemaBuilder.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/model/TableMetaData.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/table/TableMetaDataReviseEngine.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/metadata/dialect/PostgreSQLSchemaMetaDataLoaderTest.java
- Rename constrains to constraints in TableMetaData
---
> Rename constrains to constraints in TableMetaData

- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/query/CountEncryptRuleExecutor.java
- features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/query/CountEncryptRuleExecutorTest.java
- features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/query/CountMaskRuleExecutor.java
- features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/query/CountMaskRuleExecutorTest.java
- features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/CountReadwriteSplittingRuleExecutor.java
- features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/CountReadwriteSplittingRuleExecutorTest.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/query/CountShadowRuleExecutor.java
- features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/CountShadowRuleExecutorTest.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/CountShardingRuleExecutor.java
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/CountShardingRuleExecutorTest.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/rule/CountSingleTableExecutor.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/rule/CountSingleTableExecutorTest.java
Refactor count rule executor, simplify code.
> Refactor count rule executor.

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/algorithm/loadbalance/WeightReadQueryLoadBalanceAlgorithm.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/engine/dml/AbstractWhereSegmentShadowColumnConditionIterator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/datetime/IntervalShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/mod/ModShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/aggregation/AccumulationAggregationUnit.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/aggregation/AverageAggregationUnit.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/aggregation/DistinctAverageAggregationUnit.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/aggregation/DistinctSumAggregationUnit.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/util/SystemSchemaUtils.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/ingest/InventoryDumperConfiguration.java
- kernel/data-pipeline/cdc/client/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/client/handler/LoginRequestHandler.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/util/ColumnValueConvertUtils.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractInventoryIncrementalJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/AbstractDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/loader/PipelineTableMetaDataUtils.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLCommandPacketDecoder.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiateHandler.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- mode/type/cluster/repository/provider/zookeeper/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/ZookeeperRepository.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationExecutor.java
- proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/CDCChannelInboundHandler.java
- src/resources/pmd.xml
> Fix rules for pmd

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowStatusFromReadwriteSplittingRulesExecutor.java
> Fix rule LooseCoupling for pmd

- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/ShardingLoadDataStatementValidatorTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/ShardingLoadXMLStatementValidatorTest.java
> Add unit test for ShardingLoadDataStatementValidator and ShardingLoadXMLStatementValidator

- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/ShardingLoadDataStatementValidatorTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/ShardingLoadXMLStatementValidatorTest.java
Ref #25245.
- Revise pr 25245 for code style
---
> Revise pr 25245 for code style

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
- infra/common/src/main/resources/schema/mysql/performance_schema/global_status.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/global_variables.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/host_cache.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/hosts.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/memory_summary_by_account_by_event_name.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/memory_summary_by_host_by_event_name.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/memory_summary_by_thread_by_event_name.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/memory_summary_by_user_by_event_name.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/memory_summary_global_by_event_name.yaml
- infra/common/src/main/resources/schema/mysql/performance_schema/metadata_locks.yaml
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_global_status.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_global_variables.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_host_cache.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_hosts.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_memory_summary_by_account_by_event_name.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_memory_summary_by_host_by_event_name.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_memory_summary_by_thread_by_event_name.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_memory_summary_by_user_by_event_name.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_memory_summary_global_by_event_name.xml
- test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_performance_schema_metadata_locks.xml
- test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema.xml
For #24662 .
- Add more mysql performance schema tables
---
> Add more mysql performance schema tables

- db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/MySQLComStmtExecutePacket.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptForUseDefaultInsertColumnsTokenGenerator.java
- features/sharding/plugin/cache/src/main/java/org/apache/shardingsphere/sharding/cache/checker/algorithm/CacheableShardingAlgorithmChecker.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/pool/creator/DataSourceReflection.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/TableNameSchemaNameMapping.java
- kernel/sql-federation/executor/core/src/main/java/org/apache/shardingsphere/sqlfederation/row/EmptyRowEnumerator.java
- src/resources/pmd.xml
> Add more best practices rules for pmd

- proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/ShardingSphereProxy.java
> Refactor code style for ShardingSphereProxy

- proxy/frontend/core/src/test/resources/logback-test.xml
> Revert partial changes in #25120 to hide logging in tests

- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/query/CountEncryptRuleExecutor.java
- features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/query/CountMaskRuleExecutor.java
- features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/CountReadwriteSplittingRuleExecutor.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/query/CountShadowRuleExecutor.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/CountShardingRuleExecutor.java
- kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/provider/database/builder/DatabasePrivilegeBuilder.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/RegularUtils.java
- test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/env/DataSetEnvironmentManager.java
> Optimize code style.

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/algorithm/loadbalance/WeightReadQueryLoadBalanceAlgorithm.java
For #24752.
- Remove unused code
--
> Remove duplicated check in WeightReadQueryLoadBalanceAlgorithm

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/data/pipeline/datasource/creator/ShardingSpherePipelineDataSourceCreator.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/datasource/config/impl/ShardingSpherePipelineDataSourceConfiguration.java
- Add databaseName at pipeline data source configuration
---
> Set databaseName at pipeline data source configuration

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithmTest.java
Fixes #24748.
- Improve properties check of DataMatchDataConsistencyCalculateAlgorithm
- Add related test case
---
> Improve properties check of DataMatchDataConsistencyCalculateAlgorithm

- distsql/parser/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLStatementParserEngine.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptAlterTableTokenGenerator.java
- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleStatementUpdater.java
- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdater.java
- features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/update/AlterMaskRuleStatementUpdater.java
- features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/DropReadwriteSplittingRuleStatementUpdater.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/ddl/impl/ShardingAlterViewStatementValidator.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterShardingTableReferenceRuleStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingAlgorithmStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableReferenceRuleStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleStatementUpdater.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/pool/metadata/type/hikari/HikariDataSourcePoolPropertiesValidator.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/PipelineJobAPI.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLBinlogEventPacketDecoder.java
- kernel/global-clock/type/tso/provider/redis/src/main/java/org/apache/shardingsphere/globalclock/type/tso/provider/RedisTSOProvider.java
- kernel/sql-translator/api/src/main/java/org/apache/shardingsphere/sqltranslator/spi/SQLTranslator.java
- kernel/sql-translator/core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/fixture/AlwaysFailedSQLTranslator.java
- kernel/sql-translator/provider/jooq/src/main/java/org/apache/shardingsphere/sqltranslator/jooq/JooQDialectRegistry.java
- kernel/sql-translator/provider/jooq/src/main/java/org/apache/shardingsphere/sqltranslator/jooq/JooQSQLTranslator.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/cluster/watcher/ClusterStateChangedWatcher.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableUpdater.java
- sql-parser/engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/parser/SQLParserErrorListener.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java
- src/resources/pmd.xml
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/ExternalSQLParserIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/result/SQLParseResultReporter.java
> Add more design rules for pmd

- proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/information/SelectInformationSchemataExecutor.java
Fixes #25309.
- Fix npe in mysql query system with lowercase table column names
---
> Fix npe in mysql query system with lowercase table column names

- infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/generator/SQLTokenGenerators.java
- infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/token/generator/SQLTokenGeneratorsTest.java
- src/resources/pmd.xml
> Add more error prone rules for pmd

- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/RALStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/JobIdAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/QueryablePipelineRALStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/UpdatablePipelineRALStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/cdc/ShowStreamingStatusStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/migration/query/ShowMigrationCheckStatusStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/migration/query/ShowMigrationStatusStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/migration/update/CheckMigrationStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/migration/update/CommitMigrationStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/migration/update/MigrateTableStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/migration/update/RegisterMigrationSourceStorageUnitStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/migration/update/RollbackMigrationStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/migration/update/StartMigrationCheckStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/migration/update/StartMigrationStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/migration/update/StopMigrationCheckStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/migration/update/StopMigrationStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/pipeline/migration/update/UnregisterMigrationSourceStorageUnitStatementAssert.java
For #23955.
- Refactor pipeline package structure in parser IT
---
> Refactor pipeline package structure in parser IT

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/executor/AbstractDatabaseMetaDataExecutor.java
- proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/information/SelectInformationSchemataExecutor.java
- proxy/backend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/executor/SelectDatabaseExecutor.java
- proxy/backend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/executor/SelectTableExecutor.java
Refactor method names in AbstractDatabaseMetaDataExecutor
> Refactor method names in AbstractDatabaseMetaDataExecutor

- src/resources/pmd.xml
> Add more security rules for pmd

- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/importer/SocketSinkImporter.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/util/ColumnValueConvertUtils.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/process/yaml/YamlPipelineProcessConfiguration.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/process/yaml/YamlPipelineReadConfiguration.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/process/yaml/YamlPipelineWriteConfiguration.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/AbstractDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/CRC32MatchDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/PipelineInternalException.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ExecuteEngine.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/MultiplexMemoryPipelineChannel.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/SimpleMemoryPipelineChannel.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/loader/StandardPipelineTableMetaDataLoader.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNodeWatcher.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClient.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLBinlogEventPacketDecoder.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiateHandler.java
- kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPlugin.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLPositionInitializer.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java
- Refactor part of pipeline code by pmd results
---
> Refactor part of pipeline code by pmd results

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/reviser/ShardingMetaDataReviseEntry.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/config/props/ConfigurationPropertyKey.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/GenericSchemaBuilder.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/config/props/ConfigurationPropertiesTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/config/props/ConfigurationPropertyKeyTest.java
Fixes #25332.
- Rename CHECK_TABLE_META_DATA_ENABLED to CHECK_TABLE_METADATA_ENABLED for SHOW DIST VARIABLE
---
> Rename CHECK_TABLE_META_DATA_ENABLED to CHECK_TABLE_METADATA_ENABLED for SHOW DIST VARIABLE

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ExecuteEngine.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/FunctionConverter.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/LiteralExpressionConverter.java
Ref #25318.
- Revise pr 25318 for code style
---
> Revise pr 25318 for code style

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/executor/DefaultSessionVariableHandler.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/session/RequiredSessionVariableRecorder.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/session/RequiredSessionVariableRecorderTest.java
- proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLDefaultSessionVariableHandler.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/DefaultMySQLSessionVariableHandlerTest.java
> support MySQL SET session variable (#24124)

- test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/runtime/DataSourceEnvironment.java
- test/e2e/operation/pipeline/src/test/resources/env/mysql/server-5.yaml
- test/e2e/operation/pipeline/src/test/resources/env/mysql/server-8.yaml
- test/e2e/operation/pipeline/src/test/resources/env/opengauss/server.yaml
- test/e2e/operation/pipeline/src/test/resources/env/postgresql/server.yaml
- test/e2e/operation/showprocesslist/src/test/resources/env/common/cluster/proxy/zookeeper/conf/server.yaml
- test/e2e/operation/showprocesslist/src/test/resources/env/common/standalone/proxy/conf/server.yaml
- test/e2e/operation/transaction/src/test/resources/env/mysql/server.yaml
- test/e2e/operation/transaction/src/test/resources/env/opengauss/server.yaml
- test/e2e/operation/transaction/src/test/resources/env/postgresql/server.yaml
- test/e2e/sql/src/test/resources/env/common/cluster/proxy/conf/server.yaml
- test/e2e/sql/src/test/resources/env/common/standalone/proxy/conf/server.yaml
> Enable Proxy frontend SSL in E2E

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- kernel/global-clock/type/tso/core/src/main/java/org/apache/shardingsphere/globalclock/type/tso/provider/LocalTSOProvider.java
- kernel/transaction/api/src/main/java/org/apache/shardingsphere/transaction/spi/ShardingSphereTransactionManager.java
- kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/ShardingSphereTransactionManagerEngine.java
- kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/exception/CloseTransactionManagerFailedException.java
- kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/XAShardingSphereTransactionManager.java
- kernel/transaction/type/xa/core/src/test/java/org/apache/shardingsphere/transaction/xa/XAShardingSphereTransactionManagerTest.java
- kernel/transaction/type/xa/provider/narayana/src/main/java/org/apache/shardingsphere/transaction/xa/narayana/manager/NarayanaXATransactionManagerProvider.java
- kernel/transaction/type/xa/spi/src/main/java/org/apache/shardingsphere/transaction/xa/spi/XATransactionManagerProvider.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/BackendConnection.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/connection/ConnectionPostProcessor.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManager.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/LocalTransactionManager.java
For #25174
- Fix transaction pmd check
---
> Fix transaction pmd check

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/position/IngestPosition.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/position/FinishedPosition.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/position/IntegerPrimaryKeyPosition.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/position/NoUniqueKeyPosition.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/position/PlaceholderPosition.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/position/StringPrimaryKeyPosition.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/position/UnsupportedKeyPosition.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/MultiplexMemoryPipelineChannelTest.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/position/IntegerPrimaryKeyPositionTest.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/position/PlaceholderPositionTest.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/position/StringPrimaryKeyPositionTest.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/binlog/BinlogPosition.java
- kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/binlog/BinlogPositionTest.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALPosition.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALPositionTest.java
- Remove Comparable from IngestPosition
---
> Remove Comparable from IngestPosition

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/record/Column.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/DataSourceImporter.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/record/RecordUtils.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/AbstractPipelineSQLBuilder.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/PipelineSQLBuilderTest.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/check/consistency/MigrationDataConsistencyChecker.java
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/task/E2EIncrementalTask.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/importer/DataSourceImporterTest.java
- Fix table without unique key increment task write failed
---
> Fix table without unique key increment task write failed

- .asf.yaml
Fixes #25390.
- add mandatory check before pull request
---
> Add : add status check for protect branch

- sql-parser/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
- test/it/parser/src/main/resources/case/dml/select-expression.xml
- test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
Fixes #25294.
- Support BetweenExpression in Projection
---
> Support BetweenExpression in Projection (#25294)

- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTableTest.java
> Add unit tests for ShardingSphereTable

- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/subscriber/ProcessListChangedSubscriber.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/event/KillProcessInstanceCompleteEvent.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/event/ShowProcessInstanceCompleteEvent.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/event/ShowProcessListTriggerEvent.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/watcher/ComputeNodeStateChangedWatcher.java
- mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/subscriber/ProcessListChangedSubscriberTest.java
> Rename process unit to process instance.

- features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java
> Fix NPE of ALTER DEFAULT SHARDING TABLE STRATEGY

- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java
- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/WhereExtractUtils.java
- sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractorTest.java
- sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/WhereExtractUtilsTest.java
> Support extract join table and get where segments from sub table join.

- sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java
- sql-parser/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractorTest.java
> Rename joinTableSegments to joinTables.

- agent/plugins/metrics/core/pom.xml
- agent/plugins/metrics/type/prometheus/pom.xml
- agent/plugins/tracing/core/pom.xml
- agent/plugins/tracing/type/pom.xml
- distribution/proxy/pom.xml
Fixes #25481.
- add h2 for distribution/proxy/pom.xml
- remove useless h2 from agent
---
> Fix Proxy standalone mode startup failure

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/record/GroupedDataRecord.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/metadata/IdentifierName.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/metadata/SchemaTableName.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/metadata/model/PipelineColumnMetaData.java
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/metadata/model/PipelineTableMetaData.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/check/consistency/DataConsistencyCalculateParameter.java
- kernel/data-pipeline/distsql/statement/src/main/java/org/apache/shardingsphere/migration/distsql/statement/pojo/SourceTargetEntry.java
- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobId.java
- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobType.java
- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/impl/ConsistencyCheckJobAPI.java
- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/metadata/processor/ChangedConsistencyCheckJobConfigurationProcessor.java
- kernel/data-pipeline/scenario/consistencycheck/src/main/resources/META-INF/services/org.apache.shardingsphere.data.pipeline.spi.job.JobType
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/yaml/job/YamlMigrationJobConfiguration.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/spi/job/JobTypeFactoryTest.java
- Remove unused ToString annotation
- Simplify equals and hashCode with EqualsAndHashCode
- Move ConsistencyCheckJobType to scenario module
---
> Clean pipeline code

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-dist-variable.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-dist-variable.en.md
> Update SHOW DIST VARIABLES document

- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/MetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/NewMetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/data/ShardingSphereDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/DataSourcePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/global/GlobalRulePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/database/DatabaseMetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/schema/ShardingSphereTableRowDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/version/MetaDataVersionPersistService.java
For #25485.
- Add annotatin
---
> Add @Override for implement method

- infra/expr/core/pom.xml
- infra/expr/espresso/pom.xml
- infra/expr/hotsopt/pom.xml
- infra/expr/spi/pom.xml
- infra/pom.xml
> Revise pom format

- docs/community/content/involved/conduct/code.cn.md
- docs/community/content/involved/conduct/code.en.md
- add Chinse and English version code of conduct for GitHub Action
---
> Add action doc

- infra/expr/core/src/main/java/org/apache/shardingsphere/infra/expr/core/InlineExpressionParser.java
- infra/expr/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParser.java
- infra/expr/hotsopt/src/main/java/org/apache/shardingsphere/infra/expr/hotsopt/HotspotInlineExpressionParser.java
- infra/expr/spi/src/main/java/org/apache/shardingsphere/infra/expr/spi/JVMInlineExpressionParser.java
> Revise InlineExpressionParser

- agent/core/src/main/java/org/apache/shardingsphere/agent/core/plugin/PluginContext.java
Fix issue for https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYfGhP9y7mYWfw_Hi7Xx&tab=code
> Fix sonar could issue of PluginContext

- db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLServerInfo.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/constant/PostgreSQLServerInfo.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/constant/PostgreSQLServerInfoTest.java
- proxy/frontend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/OpenGaussFrontendEngine.java
- proxy/frontend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/OpenGaussAuthenticationEngine.java
- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/PostgreSQLFrontendEngine.java
- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/PostgreSQLAuthenticationEngine.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePEDksmlEb3_PqvlqA
> Fix sonar could issue of PostgreSQLServerInfo

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/circuit-breaker/show-status-from-readwrite-splitting-rule.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/circuit-breaker/show-status-from-readwrite-splitting-rule.en.md
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowStatusFromReadwriteSplittingRulesExecutor.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowStatusFromReadwriteSplittingRulesExecutorTest.java
- test/e2e/sql/src/test/resources/cases/ral/dataset/empty_rules/show_status_from_readwrite_splitting_rules.xml
- Remove deprecated row delay_time
---
> Remove deprecated row delay_time

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/constant/PostgreSQLServerInfo.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/constant/PostgreSQLServerInfoTest.java
> Remove unnecessary null-check in PostgreSQLServerInfo

- kernel/data-pipeline/cdc/client/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/client/CDCClient.java
- kernel/data-pipeline/core/pom.xml
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/JsonUtils.java
- kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPlugin.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowMigrationRuleExecutor.java
- Use jackson replace gson 
- Improve cdc client connect
---
> Use jackson replace gson when generate pipeline id

- docs/document/content/test-manual/pipeline-e2e-test/_index.cn.md
- docs/document/content/test-manual/pipeline-e2e-test/_index.en.md
> Update pipeline E2E doc

- distsql/parser/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD_ZJmlEb3_PqvlVo
> Fix sonar issue of KernelDistSQLStatementVisitor

- db-protocol/core/src/main/java/org/apache/shardingsphere/db/protocol/constant/DatabaseProtocolServerInfo.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYgCLiMqOBztts9np3Kr
> Fix sonar issue of DatabaseProtocolServerInfo

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/PostgreSQLCommandPacketFactory.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/flush/PostgreSQLComFlushPacket.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/PostgreSQLCommandPacketFactoryTest.java
- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/PostgreSQLCommandExecutorFactory.java
- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/flush/PostgreSQLComFlushExecutor.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/PostgreSQLCommandExecutorFactoryTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/flush/PostgreSQLComFlushExecutorTest.java
> deal pg flush command in proxy, support node typeorm case

- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/YamlEncryptRuleConfigurationSwapperTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/rule/YamlEncryptColumnRuleConfigurationSwapperTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/rule/YamlEncryptTableRuleConfigurationSwapperTest.java
Ref #25521.
- Add unit test for new encrypt yaml api swapper
---
> Add unit test for new encrypt yaml api swapper

- db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/text/MySQLTextResultSetRowPacket.java
- db-protocol/mysql/src/test/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/text/MySQLTextResultSetRowPacketTest.java
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYfGEswNmZnFUjRt1U7v
> Use primitive boolean in MySQLTextResultSetRowPacket

- docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/encrypt.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/encrypt.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/mix.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/mix.en.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/encrypt.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/encrypt.en.md
Ref #25521.
- Update encrypt document for new api and compatible api
---
> Update encrypt document for new api and compatible api

- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/BinaryOperationExpressionConverter.java
- test/it/optimizer/src/test/java/org/apache/shardingsphere/test/it/optimize/SQLNodeConverterEngineIT.java
> support for boolean primary SQL

- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/BinaryOperationExpressionConverter.java
Ref #25564.
- Revise pr 25564 code style
---
> Revise pr 25564 code style

- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/PostgreSQLCommandPacketFactoryTest.java
- parser/sql/dialect/mysql/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/mysql/external/ExternalMySQLParserIT.java
- parser/sql/dialect/postgresql/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/postgresql/external/ExternalPostgreSQLParserIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/ExternalSQLParserIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/loader/ExternalMySQLTestParameterLoader.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/loader/ExternalPostgreSQLTestParameterLoader.java
- test/util/src/main/java/org/apache/shardingsphere/test/loader/AbstractTestParameterLoader.java
- test/util/src/main/java/org/apache/shardingsphere/test/loader/strategy/impl/GitHubTestParameterLoadStrategy.java
- Adjusted some parsing rules for MySQL Test Suite .test files.
---
> Optimize the code for testing sqlParser using MySQL Test Suite.

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DDLStatement.g4
- test/it/parser/src/main/resources/case/dcl/alter-user.xml
- test/it/parser/src/main/resources/case/ddl/alter-table.xml
- test/it/parser/src/main/resources/sql/supported/dcl/alter-user.xml
- test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
Issue [25535](https://github.com/apache/shardingsphere/issues/25535).
- Optimize DDLStatement.g4 alterOrderList.
- Optimize BaseRule.g4 pluginName.
---
> Optimized sqlParser to support examples from MySQL Test Suite.

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/standard/RC4EncryptAlgorithm.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD-01mlEb3_PqvlSa
> Fix sonar issue for RC4EncryptAlgorithm

- kernel/data-pipeline/cdc/client/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/client/CDCClient.java
- Fix sonar checkstyle at CDCClient
---
> Fix sonar checkstyle at CDCClient

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DALStatement.g4
- test/it/parser/src/main/resources/case/dal/check-table.xml
- test/it/parser/src/main/resources/case/ddl/analyze.xml
- test/it/parser/src/main/resources/sql/supported/dal/check-table.xml
- test/it/parser/src/main/resources/sql/supported/ddl/analyze.xml
Issue [25535](https://github.com/apache/shardingsphere/issues/25535).
- Optimize DALStatement.g4 histogram checkTable.
---
> Optimized sqlParser to support examples from MySQL Test Suite. 

- docs/document/content/user-manual/error-code/sql-error-code.cn.md
- docs/document/content/user-manual/error-code/sql-error-code.en.md
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/checker/EncryptRuleConfigurationChecker.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/exception/algorithm/MismatchedEncryptAlgorithmTypeException.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptRule.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/EncryptRuleTest.java
Ref #25521.
- Add checkEncryptAlgorithmType to avoid wrong config of encrypt algorithm
---
> Add checkEncryptAlgorithmType to avoid wrong config of encrypt algorithm

- features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/api/config/CompatibleEncryptRuleConfiguration.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/checker/CompatibleEncryptRuleConfigurationChecker.java
- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/query/ShowEncryptRuleExecutor.java
- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterCompatibleEncryptRuleStatementUpdater.java
- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateCompatibleEncryptRuleStatementUpdater.java
- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropCompatibleEncryptRuleStatementUpdater.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationExecutor.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/rule/ShowRulesUsedStorageUnitExecutor.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/ExportUtils.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/YamlDatabaseConfigurationImportExecutor.java
Ref #25521.
- Refactor CompatibleEncryptRuleConfiguration convert to EncryptRuleConfiguration logic
---
> Refactor CompatibleEncryptRuleConfiguration convert to EncryptRuleConfiguration logic

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/keygen/SnowflakeKeyGenerateAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/algorithm/keygen/SnowflakeClockMoveBackException.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/keygen/SnowflakeKeyGenerateAlgorithmTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD-f4mlEb3_PqvlQC
> Fix sonar issue for SnowflakeKeyGenerateAlgorithm

- parser/sql/dialect/postgresql/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/postgresql/external/ExternalPostgreSQLParserIT.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/loader/DefaultExternalTestParameterLoader.java
> Rename ExternalPostgreSQLTestParameterLoader to DefaultExternalTestParameterLoader.

- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/NewMetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/NewDatabaseMetaDataNode.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/metadata/DataSourceNode.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/DataSourcePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/DatabaseBasedPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/DatabaseRulePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/NewDataSourcePersistService.java
- kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/persist/service/config/database/DatabaseRulePersistServiceTest.java
> Add NewMetaDataPersistService to write new data source metadata structure

- features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/route/qualified/type/QualifiedReadwriteSplittingTransactionalDataSourceRouterTest.java
> Revise #25486

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dal/show/LogicTablesMergedResult.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYfA18iWtGAAaUtvu0eL
> Fix sonar issue for LogicTablesMergedResult

- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/InsertClauseShardingConditionEngineTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/ShardingLoadDataStatementValidatorTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYfA18aatGAAaUtvu0eI
> Fix sonar issue for InsertClauseShardingConditionEngineTest

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptPredicateColumnTokenGenerator.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYgKyrsmfQ6SxjWUO723
> Fix sonar issue for EncryptPredicateColumnTokenGenerator

- kernel/data-pipeline/cdc/client/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/client/CDCClient.java
- Fix sonar issue CDCClient
---
>  Fix sonar issue CDCClient

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/ShardingRouteEngineFactory.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/enums/ShardingStrategyType.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD-m2mlEb3_PqvlQn&tab=code
> Fix sonar issue for ShardingStrategyType

- infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/SQLExecutorExceptionHandler.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePEBZrmlEb3_Pqvlg_&tab=code
> Fix sonar issue for SQLExecutorExceptionHandler

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AbstractStatementAdapter.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePED2hmlEb3_Pqvlrt&tab=why
> Fix sonar issue for AbstractStatementAdapter

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/context/JDBCContext.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePED4-mlEb3_Pqvlr-
> Fix sonar issue for JDBCContext

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/check/consistency/DataConsistencyCalculateParameter.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD_akmlEb3_PqvlVt
> Fix sonar issue of DataConsistencyCalculateParameter

- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/impl/CDCJobAPI.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/api/task/progress/IncrementalTaskProgress.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/YamlJobItemIncrementalTasksProgressSwapper.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/IncrementalTask.java
- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/PostgreSQLCommand.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD_b6mlEb3_PqvlVw
> Fix sonar issue of IncrementalTaskProgress

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/AbstractDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD_pNmlEb3_PqvlXY
> Fix sonar issue of AbstractDataConsistencyCalculateAlgorithm

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/AbstractStreamingDataConsistencyCalculateAlgorithm.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD_pXmlEb3_PqvlXb
> Fix sonar issue of ResultIterator

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD_pgmlEb3_PqvlXg
> Fix sonar issue of CalculationContext

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/executor/AbstractLifecycleExecutor.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/DataSourceImporter.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD_oymlEb3_PqvlXQ
> Fix sonar issue of DataSourceImporter

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryTask.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClient.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/ServerInfo.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/ServerVersion.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLCommandPacketDecoder.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiateHandler.java
- kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClientTest.java
- kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiateHandlerTest.java
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD_0nmlEb3_PqvlYu
> Fix sonar issue of MySQLBinlogEventHandler

- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/PostgreSQLCommand.java
Fixes https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePECTimlEb3_PqvlmD&tab=code
> Avoid using Optional and null-check together in PostgreSQLCommand

- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/impl/CDCJobAPI.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/job/CDCJob.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractSimplePipelineJob.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/config/processor/impl/AbstractChangedJobConfigurationProcessor.java
- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJob.java
- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/metadata/processor/ChangedConsistencyCheckJobConfigurationProcessor.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJob.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/metadata/processor/ChangedMigrationJobConfigurationProcessor.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobTest.java
- Refactor AbstractPipelineJob.jobId as final
---
> Refactor AbstractPipelineJob.jobId as final

- docs/document/content/reference/sharding/parse.cn.md
- docs/document/content/reference/sharding/parse.en.md
> Fix Parse Engine doc

- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiateHandler.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD_05mlEb3_PqvlYy
> Fix sonar issue of MySQLNegotiateHandler

- infra/expr/espresso/src/test/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParserTest.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiateHandler.java
- proxy/backend/type/hbase/src/main/java/org/apache/shardingsphere/proxy/backend/hbase/result/query/HBaseGetResultSet.java
https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYgRoCjDuZeJ-BPpX1cc&tab=code
> Fix sonar issue of HBaseGetResultSet

- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/task/ConsistencyCheckTasksRunner.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=BUG&id=apache_shardingsphere&open=AYePEAGhmlEb3_Pqvlay
> Fix sonar issue of ConsistencyCheckTasksRunner

- kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/task/ConsistencyCheckTasksRunner.java
- kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/rule/TransactionRule.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=BUG&id=apache_shardingsphere&open=AYePEAPNmlEb3_Pqvlb5
> Fix sonar issue of TransactionRule

- mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=BUG&id=apache_shardingsphere&open=AYePEEQfmlEb3_Pqvlut
> Fix sonar issue of ContextManager

- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/impl/CDCJobAPI.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/config/job/CDCJobConfiguration.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER&types=CODE_SMELL&id=apache_shardingsphere&open=AYePD_xWmlEb3_PqvlYT&tab=code
> Fix sonar issue of CDCJobAPI

- agent/plugins/metrics/type/prometheus/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/prometheus/collector/type/PrometheusMetricsHistogramCollector.java
- test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/statement/ShardingPreparedStatementTest.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/prepare/InventoryTaskSplitterTest.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/task/IncrementalTaskTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEBrdmlEb3_Pqvlh5
> Fix sonar issue of PrometheusMetricsHistogramCollector

- dialect-exception/postgresql/src/main/java/org/apache/shardingsphere/dialect/postgresql/exception/PostgreSQLException.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEEDdmlEb3_Pqvltv
> Fix sonar issue of PostgreSQLException

- dialect-exception/postgresql/src/main/java/org/apache/shardingsphere/dialect/postgresql/mapper/PostgreSQLDialectExceptionMapper.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEEDvmlEb3_Pqvltw
> Fix sonar issue of PostgreSQLDialectExceptionMapper

- agent/plugins/core/src/main/java/org/apache/shardingsphere/agent/plugin/core/recorder/MethodTimeRecorder.java
- agent/plugins/core/src/test/java/org/apache/shardingsphere/agent/plugin/core/recorder/MethodTimeRecorderTest.java
- agent/plugins/logging/type/file/src/main/java/org/apache/shardingsphere/agent/plugin/logging/file/advice/MetaDataContextsFactoryAdvice.java
- agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/jdbc/AbstractExecuteLatencyHistogramAdvice.java
- agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/proxy/ExecuteLatencyHistogramAdvice.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEBvxmlEb3_PqvliD&tab=why
> Fix sonar issue of MethodTimeRecorder

- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/SQLUtils.java
- parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SQLUtilsTest.java
- sonar link: https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&types=BUG&id=apache_shardingsphere&open=AYePECwKmlEb3_PqvlnL&tab=code
- sonar line: https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&types=BUG&id=apache_shardingsphere&open=AYePECwKmlEb3_PqvlnM
---
> Fix sql regex sonar issue in SQLUtils

- mode/type/cluster/repository/provider/etcd/src/main/java/org/apache/shardingsphere/mode/repository/cluster/etcd/lock/EtcdDistributedLock.java
Sonar links: : 
- https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&types=BUG&id=apache_shardingsphere&open=AYePEELgmlEb3_Pqvluk
- https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&types=BUG&id=apache_shardingsphere&open=AYePEELgmlEb3_Pqvlul
> Fix sonar issue of EtcdDistributedLock

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/ConstraintToken.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/CursorToken.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/IndexToken.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/TableToken.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/TokenUtils.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/TokenUtilsTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER&types=CODE_SMELL&id=apache_shardingsphere&open=AYePD-ILmlEb3_PqvlNk
> Fix sonar issue of TokenUtilsTest

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/ConstraintToken.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/CursorToken.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/IndexToken.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/TableToken.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/TokenUtils.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/TokenUtilsTest.java
- infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/table/TablesContextTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEBLdmlEb3_Pqvlfz
> Fix sonar issue of TablesContextTest

- mode/type/cluster/repository/provider/consul/src/test/java/org/apache/shardingsphere/mode/repository/cluster/consul/ConsulRepositoryTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEEKpmlEb3_Pqvlue
> Fix sonar issue of ConsulRepositoryTest

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/Literals.g4
Ref #25620.
- Revise pr 25620 for code style
---
> Revise pr 25620 for code style

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/metadata/dialect/SQLServerSchemaMetaDataLoader.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEAxumlEb3_PqvleJ&tab=code
> Fix sonar issue of SQLServerSchemaMetaDataLoader

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/MySQLKeyword.g4
- test/it/parser/src/main/resources/case/ddl/create-table.xml
- test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
> Optimize BaseRule.g4 support CREATE TABLE with GEOMCOLLECTION.

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/export-database-configuration.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/export-database-configuration.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/import-database-configuration.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/import-database-configuration.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-database-metadata.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-database-metadata.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-table-metadata.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-table-metadata.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/set-dist-vairable.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/set-dist-vairable.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-compute-node-info.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-compute-node-info.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-compute-node-mode.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-compute-node-mode.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-dist-variable.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-dist-variable.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-rules-used-storage-unit.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-rules-used-storage-unit.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-table-metadata.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-table-metadata.en.md
> Fix RAL docs order

- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/ExpressionConverter.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/NotExpressionConverter.java
- test/it/optimizer/src/test/java/org/apache/shardingsphere/test/it/optimize/SQLNodeConverterEngineIT.java
> support for NotSegment & NotConverter

- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/CommonSQLStatementContext.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYggUUN_W4yr8z3Zp1Pq
> Fix sonar issues of CommonSQLStatementContext

- kernel/logging/core/src/main/java/org/apache/shardingsphere/logging/rule/builder/DefaultLoggingRuleConfigurationBuilder.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEAlBmlEb3_Pqvldh
> Fix sonar issues of DefaultLoggingRuleConfigurationBuilder

- db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/binlog/row/column/value/MySQLBinlogProtocolValueFactory.java
- kernel/logging/core/src/main/java/org/apache/shardingsphere/logging/rule/builder/DefaultLoggingRuleConfigurationBuilder.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&id=apache_shardingsphere&open=AYePEDvLmlEb3_Pqvlqn
> Fix sonar issues of MySQLBinlogProtocolValueFactory

- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/check/datasource/MySQLDataSourceChecker.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&id=apache_shardingsphere&open=AYePEDvLmlEb3_Pqvlqn
> Fix sonar issues of MySQLDataSourceChecker

- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnectionTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedOperationConnectionTest.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/database/DropDatabaseBackendHandler.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/database/DropDatabaseBackendHandlerTest.java
Fixes #25700.
- Add supported drop current database check
- Add related test case
---
> Add supported drop current database check

- test/e2e/agent/jdbc-project/src/main/java/org/apache/shardingsphere/test/e2e/agent/jdbc/project/controller/AbstractRestController.java
- test/e2e/agent/jdbc-project/src/main/java/org/apache/shardingsphere/test/e2e/agent/jdbc/project/vo/response/HttpResult.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&types=CODE_SMELL&id=apache_shardingsphere&open=AYePD9wTmlEb3_PqvlK5
> Fix sonar issues of ResultCode

- docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/java-api.cn.md
- docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/java-api.en.md
- examples/shardingsphere-example-generator/src/main/resources/template/jdbc/java/repository/jdbc/OrderRepository.ftl
Fixes #25674.
- Remove `TransactionTypeHolder` document
---
> Remove `TransactionTypeHolder` document(#25674)

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/MySQLKeyword.g4
- parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
- test/it/parser/src/main/resources/case/ddl/create-table.xml
- test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
#25535 
https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast
---
> Optimize BaseRule.g4 support CREATE TABLE with cast function.

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DALStatement.g4
- parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDALStatementVisitor.java
- test/it/parser/src/main/resources/case/dal/explain.xml
- test/it/parser/src/main/resources/sql/supported/dal/explain.xml
Refer #25535.
- Support for MySQL explain delete statements
---
> Support for MySQL explain delete statements

- dialect-exception/postgresql/src/main/java/org/apache/shardingsphere/dialect/postgresql/mapper/PostgreSQLDialectExceptionMapper.java
- dialect-exception/postgresql/src/main/java/org/apache/shardingsphere/dialect/postgresql/sqlstate/PostgreSQLState.java
- dialect-exception/postgresql/src/main/java/org/apache/shardingsphere/dialect/postgresql/vendor/PostgreSQLVendorError.java
- Add TableExistsException mapper for PostgreSQL
---
> Add TableExistsException mapper for PostgreSQL

- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLTimeTypesMigrationE2EIT.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=INFO&types=CODE_SMELL&id=apache_shardingsphere&open=AYePD94wmlEb3_PqvlLs
> Refactor MySQLTimeTypesMigrationE2EIT

- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/query/ShowShadowAlgorithmExecutor.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingTableRuleExecutor.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&id=apache_shardingsphere&open=AYePD_N-mlEb3_PqvlU3&tab=code
> Refactor ShowShadowAlgorithmExecutor

- .gitignore
- distribution/src/src/main/assembly/source-distribution.xml
- pom.xml
Fixes #25721.
- remove remove coveralls and cobertura plugin
---
> Refactor : remove coveralls and cobertura plugin (#25721)

- infra/expr/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParser.java
https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=CODE_SMELL&id=apache_shardingsphere&open=AYgVU1-g6KptV5L325kL&tab=code
> Fix sonar issues on EspressoInlineExpressionParser

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/PostgreSQLAggregatedCommandPacket.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/cache/checker/ShardingRouteCacheableChecker.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
Fixes:
* https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&types=CODE_SMELL&id=apache_shardingsphere&open=AYePD-jLmlEb3_PqvlQV
* https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&types=CODE_SMELL&id=apache_shardingsphere&open=AYePED0smlEb3_PqvlrH
* https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEDhimlEb3_Pqvlpq
> Extract assignments out of expression

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/MySQLKeyword.g4
- test/it/parser/src/main/resources/case/ddl/create-table.xml
- test/it/parser/src/main/resources/case/dml/select.xml
- test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
> Optimize BaseRule.g4 label castTypeName lexer.

- .github/workflows/nightly-sql-parser.yml
> Fix workflow nightly-sql-parser.yml.

- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/handler/CDCBackendHandler.java
- proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/CDCChannelInboundHandler.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=CODE_SMELL&id=apache_shardingsphere&open=AYfA19J-tGAAaUtvu0ej
> Fix sonar issue of CDCBackendHandler

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DALStatement.g4
- test/it/parser/src/main/resources/case/dal/flush.xml
- test/it/parser/src/main/resources/sql/supported/dal/flush.xml
Refer #25535.
- Support mysql flush table statement
---
> Support mysql flush table statement

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/persist/PipelineJobProgressPersistService.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=CODE_SMELL&id=apache_shardingsphere&open=AYePD_kNmlEb3_PqvlWr&tab=why
> Fix sonar issue of PipelineJobProgressPersistService

- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/assignment/AssignmentSegment.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/assignment/ColumnAssignmentSegment.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=CODE_SMELL&id=apache_shardingsphere
> Fix sonar issue of AssignmentSegment

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/UnlabelComputeNodeUpdater.java
Fix https://sonarcloud.io/summary/new_code?id=apache_shardingsphere
> Fix sonar issue of UnlabelComputeNodeUpdater

- proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLInformationSchemaExecutorFactory.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEB5KmlEb3_Pqvljk
> Fix sonar issue of MySQLInformationSchemaExecutorFactory

- proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowVersionExecutor.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEB4LmlEb3_Pqvlje
> Fix sonar issue of ShowVersionExecutor

- proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowVersionExecutor.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dcl/impl/sqlserver/SQLServerGrantStatementAssert.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=CODE_SMELL&id=apache_shardingsphere&open=AYePD9bdmlEb3_PqvlIk
> Fix sonar issue of SQLServerGrantStatementAssert

- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dcl/impl/sqlserver/SQLServerRevokeStatementAssert.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=CODE_SMELL&id=apache_shardingsphere&open=AYePD9bomlEb3_PqvlIm
> Fix sonar issue of SQLServerRevokeStatementAssert

- infra/common/src/main/java/org/apache/shardingsphere/infra/instance/InstanceContext.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/datanode/DataNodeTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesTest.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/api/job/progress/yaml/YamlInventoryIncrementalJobItemProgressSwapperTest.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/value/collection/CollectionValue.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/session/ConnectionSession.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactoryTest.java
- proxy/backend/type/hbase/src/main/java/org/apache/shardingsphere/proxy/backend/hbase/util/HBaseHeterogeneousUtils.java
- test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/AdditionalDMLE2EIT.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/migration/api/impl/MigrationJobAPITest.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&types=CODE_SMELL&id=apache_shardingsphere&open=AYePEA7ImlEb3_Pqvle7
> Fix sonar issue of UnlockClusterUpdater

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/executor/AbstractLifecycleExecutor.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&id=apache_shardingsphere&open=AYePEACnmlEb3_Pqvlaa
> Fix sonar issue of AbstractLifecycleExecutor

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/ShardingRouteEngineFactory.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD-P0mlEb3_PqvlOW&tab=code
> Fix sonar issue of ShardingRouteEngineFactory

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/InlineShardingAlgorithm.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&types=BUG&id=apache_shardingsphere&open=AYePD-fNmlEb3_PqvlP8
> Fix sonar issue of InlineShardingAlgorithm

- .github/workflows/nightly-check.yml
- pom.xml
- report/pom.xml
> Refactor : refactor the jacoco usage

- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/BinaryOperationExpressionConverter.java
- parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
- test/it/optimizer/src/test/java/org/apache/shardingsphere/test/it/optimize/SQLNodeConverterEngineIT.java
- test/it/parser/src/main/resources/case/dml/select-expression.xml
> Support for OR sign

- .github/workflows/nightly-check.yml
- add checkstyle report to sonarcloud
---
> Add : add checkstyle report to sonarcloud

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java
- Replace volatile to AtomicXxx in AbstractPipelineJob, to fix sonar issue
---
> Replace volatile to AtomicXxx in AbstractPipelineJob

- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/updatable/AlterSQLParserRuleStatementAssert.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD9Q_mlEb3_PqvlHS
> Refactor AlterSQLParserRuleStatementAssert

- kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/datasource/swapper/DataSourceSwapper.java
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePEAKLmlEb3_Pqvla_
> Refactor DataSourceSwapper

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaData.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaDataTest.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManager.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- mode/core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java
- mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneModeContextManager.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/YamlDatabaseConfigurationImportExecutor.java
Sonar Link : https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePEA2GmlEb3_Pqvlep
> Fix sonar problem of ShardingSphereMetaData

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DALStatement.g4
- parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDALStatementVisitor.java
- test/it/parser/src/main/resources/case/dal/explain.xml
- test/it/parser/src/main/resources/sql/supported/dal/explain.xml
Refer #25535.
- Add EXPLAIN ANALYZE DELETE t1 FROM t t1, t t2 WHERE t1.x = t2.x + 1 SQL test.
- Add EXPLAIN INSERT UPDATE SQL parsing and testing.
---
> Support for update insert explain MySQL statements

- agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/proxy/ExecuteLatencyHistogramAdvice.java
- agent/plugins/metrics/core/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/proxy/ExecuteLatencyHistogramAdviceTest.java
Fixes #25779.
- Add proxy execute latency millis metric collection condition
---
> Add proxy execute latency millis metric collection condition

- kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/core/ResourceDataSource.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&id=apache_shardingsphere&open=AYePEAO9mlEb3_Pqvlb4&tab=code
> Fix sonar issue of ResourceDataSource

- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueBetweenOperatorGeneratorTest.java
- proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/ssl/SSLUtils.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=apache_shardingsphere&open=AYg1p_lzH2u19tyN-xAw
> Fix sonar issue on SSLUtils

- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLRowDescriptionPacketTest.java
- dialect-exception/postgresql/src/test/java/org/apache/shardingsphere/dialect/postgresql/mapper/PostgreSQLDialectExceptionMapperTest.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/keygen/SnowflakeKeyGenerateAlgorithm.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/orderby/CompareUtilsTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/ShardingConditionsTest.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/checker/ShardingTableRuleStatementChecker.java
- features/sharding/plugin/cosid/src/main/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdSnowflakeKeyGenerateAlgorithm.java
- infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/pagination/PaginationContextTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/instance/util/IpUtilsTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/yaml/config/swapper/mode/YamlModeConfigurationSwapperTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedGeneratedKeysResultSetTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/state/circuit/connection/CircuitBreakerConnectionTest.java
- kernel/data-pipeline/cdc/core/src/test/java/org/apache/shardingsphere/data/pipeline/cdc/core/job/CDCJobIdTest.java
- kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/PasswordEncryptionTest.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceCheckerTest.java
- kernel/logging/core/src/test/java/org/apache/shardingsphere/logging/yaml/YamlLoggingRuleConfigurationSwapperTest.java
- kernel/traffic/core/src/test/java/org/apache/shardingsphere/traffic/yaml/swapper/YamlTrafficStrategyConfigurationSwapperTest.java
- parser/sql/engine/src/test/java/org/apache/shardingsphere/sql/parser/core/SQLParserFactoryTest.java
- parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/table/SimpleTableSegmentTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/state/impl/ReadOnlyProxyStateTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/state/impl/UnavailableProxyStateTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/PostgreSQLCommandExecutorFactoryTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS3578&types=CODE_SMELL&id=apache_shardingsphere&open=AYg4kjEOjaR3HNxhP8_J
> Fix sonar issue on Rename this method name to match the regular expression: '^assert[A-Z][a-zA-Z0-9]*$'

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/orderby/CompareUtils.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/ProjectionsTokenGenerator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/FetchDirectionToken.java
- features/sharding/plugin/cosid/src/main/java/org/apache/shardingsphere/sharding/cosid/algorithm/sharding/interval/AbstractCosIdIntervalShardingAlgorithm.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/state/instance/InstanceStateContext.java
- kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/executor/GlobalClockTransactionHook.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/orderby/item/ColumnOrderByItemConverter.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/orderby/item/ExpressionOrderByItemConverter.java
- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/orderby/item/IndexOrderByItemConverter.java
- kernel/transaction/distsql/handler/src/main/java/org/apache/shardingsphere/transaction/distsql/handler/update/AlterTransactionRuleStatementUpdater.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/order/item/OrderByItemSegment.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/value/identifier/IdentifierValue.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS4551&id=apache_shardingsphere&open=AYg4khrgjaR3HNxhP87p
> Fix sonar issues on Use "==" to perform this enum comparison instead of using "equals"

- infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionsContextEngineTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/resultset/GeneratedKeysResultSetMetaDataTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedGeneratedKeysResultSetTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedOperationResultSetTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS3578&id=apache_shardingsphere
> Fix sonar issues on Rename this method name to match the regular expression: '^assert[A-Z][a-zA-Z0-9]*$'

- db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/binlog/row/column/value/string/MySQLJsonValueDecoder.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLBinlogEventPacketDecoder.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1151&id=apache_shardingsphere&open=AYgzI2sMXDiqwzmzK-MM
> Fix sonar issue on MySQLBinlogEventPacketDecoder

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionXAHandler.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1151&id=apache_shardingsphere&open=AYgzI4W7XDiqwzmzK-NW
> Fix sonar issue on TransactionXAHandler

- .github/workflows/ci.yml
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/handler/CDCBackendHandler.java
- parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/model/ModelClauseAssert.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS4144&id=apache_shardingsphere&open=AYgvbKZiiPWjHBOaqaug
> Update this method so that its implementation is not identical 

- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/execute/ExecuteEngineTest.java
- proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/ssl/SSLUtilsTest.java
- test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/readonly/PostgreSQLSetReadOnlyTestCase.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS3658&id=apache_shardingsphere&open=AYg4kfl9jaR3HNxhP83r
> Fix sonar issue of Remove this failure assertion and simply add the exception type to the method signature

- infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/process/ProcessEngineTest.java
- mode/type/standalone/core/src/test/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneContextManagerBuilderTest.java
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/task/E2EIncrementalTask.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS5977&id=apache_shardingsphere&open=AYg4kfo-jaR3HNxhP83t&tab=code
> Fix sonar issue of Replace randomly generated values with fixed ones

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/PostgreSQLCommandPacketType.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/enums/DirectionType.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1641&id=apache_shardingsphere&open=AYg4kf60jaR3HNxhP831
> Fix sonar issues of Convert this Set to an EnumSet

- .github/workflows/nightly-check.yml
- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/DeleteStatementContext.java
- mode/type/standalone/core/src/test/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneContextManagerBuilderTest.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxyDatabaseConnectionManager.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/orderby/OrderByItemAssert.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS3047&id=apache_shardingsphere&open=AYg4kiXTjaR3HNxhP89t
> Fix sonar issues on Combine this loop with the one that starts

- infra/common/src/main/java/org/apache/shardingsphere/infra/database/metadata/dialect/H2DataSourceMetaData.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/database/metadata/dialect/OracleDataSourceMetaData.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/database/metadata/dialect/SQL92DataSourceMetaData.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/database/metadata/dialect/SQLServerDataSourceMetaData.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java
- kernel/sql-federation/executor/original/src/main/java/org/apache/shardingsphere/sqlfederation/original/OriginalSQLFederationExecutor.java
- parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java
- parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java
- parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
- test/fixture/jdbc/src/main/java/org/apache/shardingsphere/test/fixture/jdbc/MockedDriver.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS112&id=apache_shardingsphere
> Fix sonar issue of Define and throw a dedicated exception instead of using a generic one

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/OrderByToken.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/ManualBitSet.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS2250&id=apache_shardingsphere
> Fix sonar issues on Collection methods with O(n) performance should be used carefully

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
Fix sonar links : 
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePECFXmlEb3_Pqvlkl
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePECFXmlEb3_Pqvlkm
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePED0smlEb3_PqvlrK
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePED0imlEb3_PqvlrD
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePED0imlEb3_PqvlrE
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePECFXmlEb3_Pqvlkl
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePECFXmlE …
> Fix sonar issue of ShardingSpherePreparedStatement & ShardingSphereStatement & DatabaseConnector

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/AbstractStreamingDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
> small fixes added for sonar

- proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/MySQLSystemVariableQueryExecutor.java
- proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/MySQLSystemVariableQueryExecutorTest.java
https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1121&id=apache_shardingsphere&open=AYfA1-AZtGAAaUtvu0f-
> Extract assignment out of expr in MySQLSystemVariableQueryExecutor

- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ddlgenerator/AbstractPostgreSQLDDLAdapter.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ddlgenerator/PostgreSQLConstraintsPropertiesAppender.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ddlgenerator/PostgreSQLTablePropertiesLoader.java
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD_6mmlEb3_PqvlZu
---
> Fix sonar issue.

- kernel/data-pipeline/distsql/parser/src/main/java/org/apache/shardingsphere/migration/distsql/parser/core/MigrationDistSQLStatementVisitor.java
- Fix sonar issue: Add getRequiredIdentifierValue for MigrationDistSQLStatementVisitor
---
> Fix sonar issue: Add getRequiredIdentifierValue for MigrationDistSQLStatementVisitor

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/AbstractStreamingDataConsistencyCalculateAlgorithm.java
- Fix sonar issue: Remove Optional null check in ResultIterator
---
> Fix sonar issue: Remove Optional null check in ResultIterator

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/DataConsistencyCheckUtils.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/DataMatchCalculatedResult.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/CRC32MatchDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchDataConsistencyCalculateAlgorithm.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/DataMatchCalculatedResultTest.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/algorithm/DataMatchCalculatedResultTest.java
- Refactor DataMatchCalculatedResult
---
> Refactor DataMatchCalculatedResult

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/PostgreSQLComBindPacket.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextJsonUtils.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextJsonUtilsTest.java
> proxy support parse pg json parameter in bind phase

- parser/sql/engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
- test/it/parser/src/main/resources/case/dcl/grant.xml
- test/it/parser/src/main/resources/sql/supported/dcl/grant-user.xml
Refer #25535.
- Change GRANT_PROXY enum value Spelling
- Add test sql
---
> Change GRANT_PROXY enum value Spelling

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4
- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/Literals.g4
- test/it/parser/src/main/resources/case/dml/insert.xml
- test/it/parser/src/main/resources/sql/supported/dml/insert.xml
Refer #25535.
- Improve MySQL insert syntax rules
- Add test sql
---
> Improve MySQL insert syntax rules

- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/MaskAlgorithmPropsChecker.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFirstNLastMMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFromXToYMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFirstNLastMMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFromXToYMaskAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/replace/GenericTableRandomReplaceAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/replace/PersonalIdentityNumberRandomReplaceAlgorithm.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/replace/TelephoneRandomReplaceAlgorithm.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/MaskAlgorithmPropsCheckerTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/KeepFromXToYMaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskAfterSpecialCharsAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskFromXToYMaskAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/replace/LandlineNumberRandomAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/replace/MilitaryIdentityNumberRandomReplaceAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/replace/PersonalIdentityNumberRandomReplaceAlgorithmTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/replace/UnifiedCreditCodeRandomReplaceAlgorithmTest.java
Fixes #24755 .
- SubTask: 
---
> [#24755] Improve property verification of MaskAlgorithm

- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/UnusedAlgorithmFinderTest.java
Refs [#25730](https://github.com/apache/shardingsphere/issues/25730)
-  Add JUnit test for UnusedAlgorithmFinder.find(..)
---
> Add junit test for UnusedAlgorithmFinder

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DALStatement.g4
- parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDALStatementVisitor.java
- test/it/parser/src/main/resources/case/dal/kill.xml
- test/it/parser/src/main/resources/sql/supported/dal/kill.xml
Refer #25535.
- Improve MySQL kill statement
---
> Improve MySQL kill statement

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/AbstractSQLRULBackendHandler.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/RULBackendHandlerFactory.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/executor/RULExecutor.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/FormatSQLExecutor.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/ParseDistSQLHandler.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/PreviewHandler.java
- proxy/backend/core/src/main/resources/META-INF/services/org.apache.shardingsphere.proxy.backend.handler.distsql.rul.executor.RULExecutor
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactoryTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/FormatSQLExecutorTest.java
For #25868 .
- Add RULExecutor
- Refactor RULBackendHandlerFactory
- Refactor FormatSQLExecutor and adding unit tests
---
> Add RULExecutor and refactor RULBackendHandlerFactory

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/api/yaml/YamlJDBCConfiguration.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/api/yaml/YamlShardingSphereDataSourceFactory.java
For #25883.
- Refactor JDBC global rule config format specification, keep consistent with Proxy style
---
> Refactor JDBC global rule config format specification

- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/cover/MaskAfterSpecialCharsAlgorithmTest.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClient.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER&types=CODE_SMELL&id=apache_shardingsphere&open=AYhPbBbalhODbqBwcFc1
> Fix sonar issue of MaskAfterSpecialCharsAlgorithmTest

- agent/core/src/main/java/org/apache/shardingsphere/agent/core/advisor/executor/type/ConstructorAdviceExecutor.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS134&id=apache_shardingsphere&open=AYg4kiosjaR3HNxhP8-h
> Fix sonar issue of ConstructorAdviceExecutor

- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/engine/ShadowRouteEngine.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/engine/dml/AbstractShadowDMLStatementRouteEngine.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/engine/impl/ShadowNonDMLStatementRoutingEngine.java
- proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/MySQLCommandExecutorFactory.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS134&id=apache_shardingsphere&open=AYg4khFqjaR3HNxhP85u
> Fix sonar issue of AbstractShadowDMLStatementRouteEngine

- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLIncrementalDumper.java
- kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPlugin.java
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/helper/PipelineCaseHelper.java
- Fix openGauss mpp decoding plugin decode single quote at increment task
- Fix sonar issue
---
> Fix openGauss mpp decoding plugin decode single quote at increment task

- test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema.xml
- Fix system table query e2e
---
> Fix system table query e2e

- infra/common/src/test/java/org/apache/shardingsphere/infra/datasource/pool/destroyer/fixture/MockedDataSourcePoolActiveDetector.java
- infra/common/src/test/resources/META-INF/services/org.apache.shardingsphere.infra.datasource.pool.destroyer.detector.DataSourcePoolActiveDetector
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/storage/unit/ShowStorageUnitExecutorTest.java
- test/fixture/jdbc/src/main/java/org/apache/shardingsphere/test/fixture/jdbc/MockedDataSource.java
> Fix occasional failure of DataSourcePoolDestroyerTest

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-dist-variable.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-dist-variable.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting/alter-readwrite-splitting-rule.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting/alter-readwrite-splitting-rule.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting/create-readwrite-splitting-rule.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting/create-readwrite-splitting-rule.en.md
For #25870 , Update docs for `SHOW DIST VARIABLES`
For #25871 , Update docs for `CREATE/ALTER READWRITE_SPLITTING RULE`
> For #25870 & 25871, Update docs for DistSQL.

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/loader/metadata/SchemaMetaDataLoaderEngine.java
- https://sonarcloud.io/project/issues?resolved=false&rules=java:S2221&id=apache_shardingsphere&open=AYgzI3abXDiqwzmzK-Mw
---
> Fix sonar issue in SchemaMetaDataLoaderEngine

- distsql/handler/src/main/java/org/apache/shardingsphere/distsql/handler/rul/RULExecutor.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/RULBackendHandlerFactory.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/SQLRULBackendHandler.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/executor/ConnectionSessionRequiredRULExecutor.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/FormatSQLExecutor.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/ParseDistSQLExecutor.java
- proxy/backend/core/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.rul.RULExecutor
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/FormatSQLExecutorTest.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/ParseDistSQLExecutorTest.java
For #25868 .
- Add ConnectionSessionRequiredRULExecutor
- Refactor ParseDistSQLHandler
---
> Refactor ParseDistSQLHandler

- db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/constant/MySQLAuthenticationPlugin.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/PasswordEncryption.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLNegotiateHandler.java
Update MySQL protocol javadoc.
> For #25856, update MySQL protocol javadoc.

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DDLStatement.g4
- test/it/parser/src/main/resources/case/ddl/rename-table.xml
- test/it/parser/src/main/resources/sql/supported/ddl/rename-table.xml
Refer #25535.
- Change rename table syntax suooprt tables sql statement
---
> Change rename table syntax

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/ComplexInlineShardingAlgorithm.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/data/NullShardingValueException.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/ComplexInlineShardingAlgorithmTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS134&id=apache_shardingsphere&open=AYg4kgqNjaR3HNxhP84z
> Refactor ComplexInlineShardingAlgorithm on Sonar issue

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/TCLStatement.g4
- test/it/parser/src/main/resources/case/tcl/lock.xml
- test/it/parser/src/main/resources/sql/supported/tcl/lock.xml
Refer #25535.
- Change lock syntax support single table sql statement
---
> Change lock syntax (#25535)

- infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/lock/ProcessOperationLock.java
- infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/lock/ProcessOperationLockRegistry.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/connector/SocketSinkImporterConnector.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/connection/ResourceLock.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/connection/ResourceLockTest.java
- proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/MySQLCommandExecuteEngine.java
- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/PostgreSQLCommandExecuteEngine.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/PostgreSQLCommandExecuteEngineTest.java
Sonar link : https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS2274&id=apache_shardingsphere&open=AYePEBbymlEb3_PqvlhD
> Fix sonar issue of ReentrantLock await

- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/connector/SocketSinkImporterConnector.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/connection/ResourceLockTest.java
> Revise #25827

- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterContextManagerBuilder.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterModeContextManager.java
> Add NewClusterModeContextManager for refactor metadata

- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterModeContextManager.java
> Fix compilation error

- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/check/datasource/MySQLDataSourceChecker.java
- kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/check/datasource/MySQLDataSourceCheckerTest.java
> Fix logic error in MySQLDataSourceChecker

- kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/from/impl/SubqueryTableConverter.java
Ref #25921.
- Revise pr 25921 for code style
---
> Revise pr 25921 for code style

- mode/type/cluster/repository/api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/lock/impl/DefaultDistributedLock.java
- mode/type/cluster/repository/provider/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/lock/ConsulDistributedLock.java
- mode/type/cluster/repository/provider/zookeeper/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/ZookeeperRepository.java
Sonar issue link : https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS2221&id=apache_shardingsphere&open=AYgzI5XEXDiqwzmzK-PL
> Fix sonar issue of lock and ZooKeeperRepository

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/PipelineJobProgressDetector.java
> Remove unnecessary cast in PipelineJobProgressDetector

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/NewYamlReadwriteSplittingRuleConfigurationSwapper.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapper.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapperTest.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/metadata/config/sharding/ShardingNodeConverter.java
For #25485.
- Add new sharding rule configuration swapper
---
> Add new sharding rule configuration swapper

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DDLStatement.g4
- parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CreateIndexStatementHandler.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/ddl/MySQLCreateIndexStatement.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ddl/impl/CreateIndexStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/algorithm/ExpectedAlgorithmClause.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/lock/ExpectedLockTypeClause.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ddl/CreateIndexStatementTestCase.java
- test/it/parser/src/main/resources/case/ddl/create-index.xml
- test/it/parser/src/main/resources/sql/supported/ddl/create-index.xml
Refer #25862.
- Support create index ALGORITHM and LOCK options parse
---
> Support create index ALGORITHM and LOCK options parse

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescription.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/PostgreSQLColumnType.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/PostgreSQLComBindPacket.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextBitUtils.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextBoolUtils.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/PostgreSQLColumnDescriptionTest.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/PostgreSQLColumnTypeTest.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextBitUtilsTest.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextBoolUtilsTest.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/response/data/QueryResponseCell.java
- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/Portal.java
- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutor.java
Fixes #25933.
- parse pg bit parameter
- set correct typeOid for PG bit and bool type  for proxy
> support pg bit and bool type parsed from/to java&jdbc

- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/DataConsistencyCheckUtils.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ddlgenerator/PostgreSQLColumnPropertiesAppender.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ddlgenerator/PostgreSQLColumnType.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ddlgenerator/PostgreSQLColumnTypeTest.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/watcher/ComputeNodeStateChangedWatcher.java
- parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
- parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java
- parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java
- parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/type/OpenGaussDDLStatementVisitor.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS3776&id=apache_shardingsphere&open=AYePEDT4mlEb3_PqvloI
> Fix sonar issue on OpenGaussDDLStatementVisitor

- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/context/JDBCContextTest.java
Fixes #25631 .
Test added 
---
> test added for JDBCContext

- db-protocol/opengauss/src/main/java/org/apache/shardingsphere/db/protocol/opengauss/packet/command/query/extended/bind/OpenGaussComBatchBindPacket.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/PostgreSQLComBindPacket.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTimeBinaryProtocolValue.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLBinaryTimestampUtils.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLTextBitUtils.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLTextBoolUtils.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLTextJsonUtils.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLTextTimeUtils.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLTextTimestampUtils.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTimeBinaryProtocolValueTest.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLBinaryTimestampUtilsTest.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLTextBitUtilsTest.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLTextBoolUtilsTest.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLTextJsonUtilsTest.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLTextTimeUtilsTest.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLTextTimestampUtilsTest.java
- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/Portal.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYhyUlsO2YQaQ_1mQGK0&tab=code
> Fix sonar issue on PostgreSQLTextBitUtils

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLTextBoolUtils.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYhyUlrt2YQaQ_1mQGKz
> Fix sonar issue on PostgreSQLTextBoolUtils

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingConfigurationSubscriber.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingLoadBalanceSubscriber.java
- features/readwrite-splitting/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.rule.RuleConfigurationSubscribeCoordinator
- infra/common/src/main/java/org/apache/shardingsphere/infra/rule/RuleConfigurationSubscribeCoordinator.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/metadata/config/readwritesplitting/ReadwriteSplittingNodeConverter.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/rule/FeatureEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/rule/readwritesplitting/configuration/AddReadwriteSplittingConfigurationEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/rule/readwritesplitting/configuration/AlterReadwriteSplittingConfigurationEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/rule/readwritesplitting/configuration/DeleteReadwriteSplittingConfigurationEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/rule/readwritesplitting/loadbalance/AddLoadBalanceEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/rule/readwritesplitting/loadbalance/AlterLoadBalanceEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/rule/readwritesplitting/loadbalance/DeleteLoadBalanceEvent.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterContextManagerBuilder.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/NewGovernanceWatcher.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/metadata/watcher/NewMetaDataChangedWatcher.java
- mode/type/cluster/core/src/main/resources/META-INF/services/org.apache.shardingsphere.mode.manager.cluster.coordinator.registry.NewGovernanceWatcher
> Add subscribe to refresh readwrite-splitting configuration at  readwrite-splitting module

- .github/workflows/e2e-pipeline.yml
- Increase pipeline timeout-minutes of E2E
---
> Increase pipeline timeout-minutes of E2E

- kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/OpenGaussPositionInitializer.java
- kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/OpenGaussWALDumper.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLWALDumper.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/pojo/ReplicationSlotInfo.java
- kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java
- Fix replication slot not remove when drop database at openGauss
- Reduced data replay after reconnect
- Make sure stop job before drop, reduce error log
---
> Fix replication slot not remove when drop database at openGauss

- features/shadow/core/pom.xml
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/yaml/swapper/NewYamlShadowRuleConfigurationSwapper.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/yaml/swapper/NewYamlShadowRuleConfigurationSwapperTest.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/metadata/config/shadow/ShadowNodeConverter.java
For #25485.
- Add new shadow rule configuration swapper
---
> Add new shadow rule configuration swapper

- features/mask/core/pom.xml
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/yaml/swapper/NewYamlMaskRuleConfigurationSwapper.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/yaml/swapper/NewYamlMaskRuleConfigurationSwapperTest.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/metadata/config/mask/MaskNodeConverter.java
For #25485.
- Add new mask rule configuration swapper
---
> Add new mask rule configuration swapper

- features/encrypt/core/pom.xml
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlEncryptRuleConfigurationSwapper.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlEncryptRuleConfigurationSwapperTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/context/JDBCContextTest.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/metadata/config/encrypt/EncryptNodeConverter.java
For #35485.
- Add new encrypt rule configuration swapper
---
> Add new encrypt rule configuration swapper

- db-protocol/mysql/src/test/java/org/apache/shardingsphere/db/protocol/mysql/packet/binlog/row/column/value/integer/MySQLBitBinlogProtocolValueTest.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/generic/PostgreSQLCommandCompletePacketTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/EncryptRuleTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/common/IteratorStreamMergedResultTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/ddl/fetch/FetchStreamMergedResultTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/standard/SQLRouteTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/standard/SubqueryRouteTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/database/metadata/dialect/H2DataSourceMetaDataTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS5976&id=apache_shardingsphere
> Fix sonar issue on Replace tests with a single Parameterized one

- parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CreateTableStatementHandler.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/ddl/MySQLCreateTableStatement.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ddl/impl/CreateTableStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ddl/CreateTableStatementTestCase.java
- test/it/parser/src/main/resources/case/ddl/create-table.xml
- test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
Refer #25926.
- Support create table like syntax parsed
- Add test
---
> Support create table like syntax parsed

- features/encrypt/core/pom.xml
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/metadata/converter/EncryptNodeConverter.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlEncryptRuleConfigurationSwapper.java
- features/mask/core/pom.xml
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/metadata/converter/MaskNodeConverter.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/yaml/swapper/NewYamlMaskRuleConfigurationSwapper.java
- features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/NewYamlReadwriteSplittingRuleConfigurationSwapperTest.java
- features/shadow/core/pom.xml
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/metadata/converter/ShadowNodeConverter.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/yaml/swapper/NewYamlShadowRuleConfigurationSwapper.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/converter/ShardingNodeConverter.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapper.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/metadata/config/readwritesplitting/ReadwriteSplittingNodeConverter.java
For #25485.
- Move rule node converters to feature module
---
> Move rule node converters to feature module

- .github/workflows/nightly-check.yml
- refactor the job name in nightly check
---
> Refactor : refactor the job name in nightly check

- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTimeBinaryProtocolValue.java
- db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLBinaryTimestampUtils.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTimeBinaryProtocolValueTest.java
- db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/util/PostgreSQLBinaryTimestampUtilsTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/algorithm/replace/MilitaryIdentityNumberRandomReplaceAlgorithmTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/context/JDBCContextTest.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/importer/CDCImporter.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/importer/CDCImporterManager.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/prepare/CDCJobPreparer.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/util/CDCSchemaTableUtils.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/SingleTableInventoryDataConsistencyChecker.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/sink/PipelineDataSourceSink.java
- parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java
- parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/type/OpenGaussDDLStatementVisitor.java
- parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/type/PostgreSQLDDLStatementVisitor.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/OwnerAvailable.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleAlterSynonymStatement.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleDropDirectoryStatement.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/sqlserver/ddl/SQLServerAlterTriggerStatement.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/sqlserver/ddl/SQLServerCreateTriggerStatement.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/sqlserver/ddl/SQLServerDropTriggerStatement.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS3776&sinceLeakPeriod=true&id=apache_shardingsphere&open=AYh0imMyGX7CbipLA4aC
> Fix sonar issue on MySQLDDLStatementVisitor

- .github/workflows/nightly-check.yml
- .github/workflows/resources/linkcheck/markdown-link-check-config.json
- refactor the dead link check pattern
---
> Refactor : refactor the dead link check pattern

- .github/workflows/nightly-check.yml
- switch on all action in nightly check workflows
---
> Refactor : switch all action in nightly workflows on

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/EncryptResultDecoratorEngine.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/EncryptResultDecoratorEngineTest.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/merge/MaskResultDecoratorEngine.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/merge/MaskResultDecoratorEngineTest.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/reviser/ShardingMetaDataReviseEntry.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/MetaDataReviseEntry.java
- infra/merge/src/main/java/org/apache/shardingsphere/infra/merge/MergeEngine.java
- infra/merge/src/main/java/org/apache/shardingsphere/infra/merge/engine/decorator/ResultDecoratorEngine.java
- infra/merge/src/test/java/org/apache/shardingsphere/infra/merge/fixture/decorator/ResultDecoratorEngineFixture.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/PipelineJobAPI.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractInventoryIncrementalJobAPIImpl.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/api/impl/AbstractPipelineJobAPIImpl.java
- proxy/backend/type/hbase/src/main/java/org/apache/shardingsphere/proxy/backend/hbase/checker/CommonHeterogeneousSQLStatementChecker.java
- proxy/backend/type/hbase/src/main/java/org/apache/shardingsphere/proxy/backend/hbase/checker/HBaseCheckerFactory.java
- proxy/backend/type/hbase/src/main/java/org/apache/shardingsphere/proxy/backend/hbase/checker/HeterogeneousDeleteStatementChecker.java
- proxy/backend/type/hbase/src/main/java/org/apache/shardingsphere/proxy/backend/hbase/checker/HeterogeneousInsertStatementChecker.java
- proxy/backend/type/hbase/src/main/java/org/apache/shardingsphere/proxy/backend/hbase/checker/HeterogeneousSQLStatementChecker.java
- proxy/backend/type/hbase/src/main/java/org/apache/shardingsphere/proxy/backend/hbase/checker/HeterogeneousSelectStatementChecker.java
- proxy/backend/type/hbase/src/main/java/org/apache/shardingsphere/proxy/backend/hbase/checker/HeterogeneousUpdateStatementChecker.java
- proxy/backend/type/hbase/src/test/java/org/apache/shardingsphere/proxy/backend/hbase/checker/CommonHeterogeneousSQLStatementCheckerTest.java
- proxy/backend/type/hbase/src/test/java/org/apache/shardingsphere/proxy/backend/hbase/checker/HBaseCheckerFactoryTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1452&types=CODE_SMELL&id=apache_shardingsphere
> Fix sonar issues on Fix sonar issue on Remove usage of generic wildcard type

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/datasource/ShardingSphereDataSource.java
- kernel/data-pipeline/cdc/client/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/client/handler/CDCRequestHandler.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/impl/CDCJobAPI.java
- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/importer/sink/CDCSocketSink.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLIncrementalDumper.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClient.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLBinlogEventPacketDecoder.java
- Fix sonar issues in pipeline
---
> Fix sonar issues in pipeline

- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLServerPreparedStatement.java
- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/bind/PostgreSQLComBindExecutor.java
- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/parse/PostgreSQLComParseExecutor.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/bind/PostgreSQLComBindExecutorTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/parse/PostgreSQLComParseExecutorTest.java
Fixes #25960.
-  convert pg parameters index to jdbc style  for proxy
> re-order pg parameters in jdbc style

- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/importer/CDCImporter.java
Related to #22500 
It's not completed in #25994 
It still need openGauss CSN could increase for every transaction, then more improvement could be done.
- Improve CDC XA records output
---
> Improve CDC XA records output

- proxy/frontend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/command/query/extended/bind/OpenGaussComBatchBindExecutorTest.java
- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLServerPreparedStatement.java
- proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/parse/PostgreSQLComParseExecutor.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PortalTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLAggregatedBatchedStatementsCommandExecutorTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutorTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/bind/PostgreSQLComBindExecutorTest.java
- proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutorTest.java
Revise #25988.
* Remove method only used in test code.
* Avoid using stream in high frequency code.
* Simplify code by lombok.
> Remove unused constructor and revise code style for #25988

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptColumnItem.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/impl/EncryptAlterTableTokenGeneratorTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/impl/EncryptCreateTableTokenGeneratorTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/impl/EncryptProjectionTokenGeneratorTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/EncryptColumnTest.java
- Remove useless constructor and modify related unit test
---
> Remove useless constructor and modify related unit test

- docs/blog/content/material/2023_02_17_Dynamic_Data_Masking_ShardingSphere_5.3.1_Deep_Dive.en.md
- infra/util/src/main/java/org/apache/shardingsphere/infra/util/props/PropertiesConverter.java
- test/e2e/sql/src/test/resources/cases/rdl/dataset/rdl_empty_rules/alter_mask_rule.xml
- test/e2e/sql/src/test/resources/cases/rql/dataset/mask/cluster/show_mask_rule.xml
- test/e2e/sql/src/test/resources/cases/rql/dataset/mask/standalone/show_mask_rule.xml
- test/e2e/sql/src/test/resources/cases/rql/dataset/mask_encrypt/cluster/show_mask_rule.xml
- test/e2e/sql/src/test/resources/cases/rql/dataset/mask_encrypt/show_mask_rule.xml
- test/e2e/sql/src/test/resources/cases/rql/dataset/mask_encrypt/standalone/show_mask_rule.xml
- test/e2e/sql/src/test/resources/cases/rql/dataset/mask_encrypt_sharding/cluster/show_mask_rule.xml
- test/e2e/sql/src/test/resources/cases/rql/dataset/mask_encrypt_sharding/standalone/show_mask_rule.xml
- test/e2e/sql/src/test/resources/cases/rql/dataset/mask_sharding/cluster/show_mask_rule.xml
- test/e2e/sql/src/test/resources/cases/rql/dataset/mask_sharding/standalone/show_mask_rule.xml
Fixes #26036
Ref https://github.com/apache/shardingsphere/actions/runs/5158222228/jobs/9292091516?pr=26021
- Fix mask e2e integration test error since props can not guarantee order
---
> Fix mask e2e integration test error since props can not guarantee order

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/ShardingRouteEngineFactory.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/ShardingRouteEngineFactoryTest.java
- https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS107&id=apache_shardingsphere&open=AYePD-P0mlEb3_PqvlOS
---
> Fix sonar issue in ShardingRouteEngineFactory

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/metadata/converter/ReadwriteSplittingNodeConverter.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/converter/ShardingNodeConverter.java
- mode/type/cluster/repository/provider/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/lock/ConsulDistributedLock.java
Sonar links : https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYiNOMtaONYr_5YLXsHs
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYiNONC2ONYr_5YLXsHw
> Fix sonar issue

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlEncryptRuleConfigurationSwapper.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/yaml/swapper/NewYamlMaskRuleConfigurationSwapper.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/NewYamlReadwriteSplittingRuleConfigurationSwapper.java
- features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/NewYamlReadwriteSplittingRuleConfigurationSwapperTest.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/yaml/swapper/NewYamlShadowRuleConfigurationSwapper.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/yaml/swapper/table/YamlShadowTableConfigurationSwapper.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapper.java
For #25485.
- Improve swap DatabaseRule to YamlDataNode
---
> Improve swap DatabaseRule to YamlDataNode

- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/converter/EncryptRuleStatementConverter.java
- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleStatementUpdater.java
- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdater.java
- features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/converter/EncryptRuleStatementConverterTest.java
- features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleStatementUpdaterTest.java
- features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdaterTest.java
- features/encrypt/distsql/parser/src/main/java/org/apache/shardingsphere/encrypt/distsql/parser/core/EncryptDistSQLStatementVisitor.java
- features/encrypt/distsql/statement/src/main/java/org/apache/shardingsphere/encrypt/distsql/parser/segment/EncryptColumnItemSegment.java
- features/encrypt/distsql/statement/src/main/java/org/apache/shardingsphere/encrypt/distsql/parser/segment/EncryptColumnSegment.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/distsql/rdl/EncryptColumnAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/distsql/rdl/ExpectedEncryptColumn.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/distsql/rdl/ExpectedEncryptColumnItem.java
- test/it/parser/src/main/resources/case/rdl/alter.xml
- test/it/parser/src/main/resources/case/rdl/create.xml
- Refactor EncryptColumnSegment using EncryptColumnItemSegment
- Update related test cases
---
> Refactor EncryptColumnSegment using EncryptColumnItemSegment

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByMemoryMergedResult.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/ShardingSQLRouter.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/InsertClauseShardingConditionEngine.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/ShardingStatementValidatorFactory.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/impl/ShardingInsertStatementValidator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/impl/ShardingSelectStatementValidator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/impl/ShardingUpdateStatementValidator.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByMemoryMergedResultTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/InsertClauseShardingConditionEngineTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/standard/assertion/ShardingRouteAssert.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/ShardingDeleteStatementValidatorTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/ShardingInsertStatementValidatorTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/ShardingUpdateStatementValidatorTest.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/connection/validator/ShardingSphereMetaDataValidateUtils.java
- kernel/single/core/pom.xml
- kernel/single/core/src/main/java/org/apache/shardingsphere/single/route/SingleSQLRouter.java
- kernel/single/core/src/main/java/org/apache/shardingsphere/single/route/validator/SingleMetaDataValidatorFactory.java
- kernel/single/core/src/test/java/org/apache/shardingsphere/single/route/SingleSQLRouterTest.java
- test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/scenario/EncryptSQLRewriterIT.java
- test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/scenario/MixSQLRewriterIT.java
- test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/scenario/ShardingSQLRewriterIT.java
- test/it/rewriter/src/test/resources/scenario/mix/case/query-with-cipher/ddl/create/create-table.xml
- test/it/rewriter/src/test/resources/scenario/mix/config/query-with-cipher.yaml
- test/it/rewriter/src/test/resources/scenario/sharding/case/ddl/create-table.xml
- test/it/rewriter/src/test/resources/scenario/sharding/config/sharding-rule.yaml
Fixes #26062.
- Validate table exist when execute insert, delete, update and select statement
---
> Validate table exist when execute insert, delete, update and select statement

- .github/workflows/e2e-pipeline.yml
- jdbc/core/pom.xml
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/InventoryRecordsCountCalculator.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/prepare/InventoryTaskSplitter.java
- proxy/backend/core/pom.xml
- report/pom.xml
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/MariaDBMigrationE2EIT.java
- Refactor InventoryTaskSplitter
---
> Refactor InventoryTaskSplitter

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlCompatibleEncryptRuleConfigurationSwapper.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlCompatibleEncryptRuleConfigurationSwapperTest.java
For #25485.
- Add compatible encrypt configuration swapper
---
> Add compatible encrypt configuration swapper

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
- infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_roles.yaml
- infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_tables.yaml
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
- proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussAdminExecutorCreator.java
- proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussSystemCatalogAdminQueryExecutor.java
- proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/schema/OpenGaussRoles.java
- proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/schema/OpenGaussTables.java
- proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussAdminExecutorCreatorTest.java
- proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussSystemCatalogAdminQueryExecutorTest.java
- proxy/backend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/PostgreSQLAdminExecutorCreator.java
- proxy/bootstrap/src/main/resources/conf/server.yaml
Enhance https://github.com/apache/shardingsphere/pull/25741
Liked to issue #25468 #24662. maybe.
Features:
---
> Support metadata table pg_tables,pg_roles in og scenario.

- features/mask/core/src/main/java/org/apache/shardingsphere/mask/metadata/converter/MaskNodeConverter.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/yaml/swapper/NewYamlMaskRuleConfigurationSwapper.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/metadata/converter/MaskNodeConverterTest.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/yaml/swapper/NewYamlMaskRuleConfigurationSwapperTest.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/NewYamlReadwriteSplittingRuleConfigurationSwapper.java
> Improve swap yaml data to rule configuration in mask

- infra/context/src/main/java/org/apache/shardingsphere/infra/connection/validator/ShardingSphereMetaDataValidateUtils.java
- test/e2e/sql/src/test/resources/cases/dql/dql-integration-select.xml
Fixes #26091.
-  Exclude dual when validate if a table exist. 
---
>  Exclude dual when validate if a table exist. (#26091)

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptCreateTableTokenGenerator.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptIndexColumnTokenGenerator.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptOrderByItemTokenGenerator.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptPredicateColumnTokenGenerator.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/InsertCipherNameTokenGenerator.java
- infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/SubstitutableColumnNameToken.java
- infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/SubstitutableColumnNameTokenTest.java
- test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-projection.xml
- test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-subquery.xml
- test/it/rewriter/src/test/resources/scenario/mix/case/query-with-cipher/dml/select/select-projection.xml
Ref #26028.
- fix column index out of range exception when execute subquery with encrypt
- modify encrypt rewrite test
---
> Fix column index out of range exception when execute subquery with encrypt

- kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/metadata/converter/AuthorityNodeConverter.java
- kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/yaml/swapper/NewYamlAuthorityRuleConfigurationSwapper.java
- kernel/authority/core/src/test/java/org/apache/shardingsphere/authority/metadata/AuthorityNodeConverterTest.java
- kernel/authority/core/src/test/java/org/apache/shardingsphere/authority/yaml/swapper/NewYamlAuthorityRuleConfigurationSwapperTest.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/NewDatabaseRulePersistService.java
> Add NewYamlAuthorityRuleConfigurationSwapper of global rule.

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dal/show/EncryptShowColumnsMergedResult.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dal/show/EncryptShowCreateTableMergedResult.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptMergedResult.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptMergedResultTest.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/merge/dql/MaskMergedResult.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/merge/dql/MaskMergedResultTest.java
- infra/context/src/main/java/org/apache/shardingsphere/infra/connection/validator/ShardingSphereMetaDataValidateUtils.java
- infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/QueryResult.java
- infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/stream/JDBCStreamQueryResult.java
- infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/type/memory/AbstractMemoryQueryResult.java
- infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/stream/JDBCStreamQueryResultTest.java
- infra/merge/src/main/java/org/apache/shardingsphere/infra/merge/result/MergedResult.java
- infra/merge/src/main/java/org/apache/shardingsphere/infra/merge/result/impl/decorator/DecoratorMergedResult.java
- infra/merge/src/main/java/org/apache/shardingsphere/infra/merge/result/impl/local/LocalDataMergedResult.java
- infra/merge/src/main/java/org/apache/shardingsphere/infra/merge/result/impl/memory/MemoryMergedResult.java
- infra/merge/src/main/java/org/apache/shardingsphere/infra/merge/result/impl/stream/StreamMergedResult.java
- infra/merge/src/main/java/org/apache/shardingsphere/infra/merge/result/impl/transparent/TransparentMergedResult.java
- infra/merge/src/test/java/org/apache/shardingsphere/infra/merge/result/impl/local/LocalDataMergedResultTest.java
- infra/merge/src/test/java/org/apache/shardingsphere/infra/merge/result/impl/transparent/TransparentMergedResultTest.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSet.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/adapter/ResultSetGetterAdapterTest.java
- jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSetTest.java
> Fix the exception thrown when invoking ShardingSphereResultSet#getCharacterStream with CLOB type while using Oracle database. (#26093)

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptAlgorithmMetaData.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java
- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/subquery/SubqueryTableContext.java
- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/subquery/engine/SubqueryTableContextEngine.java
- infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/table/TablesContext.java
- test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-sub-query.xml
- test/e2e/sql/src/test/resources/env/it-env.properties
Fixes #26166.
- Fix unknown column exception when execute subquery contains join statement with multi encrypt table columns
---
> Fix unknown column exception when execute subquery contains join statement with multi encrypt table columns

- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/record/DataRecord.java
- kernel/data-pipeline/cdc/core/src/test/java/org/apache/shardingsphere/data/pipeline/cdc/util/DataRecordResultConvertUtilsTest.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/InventoryDumper.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/importer/DataRecordMergerTest.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/MultiplexMemoryPipelineChannelTest.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/DataRecordTest.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/record/RecordUtilsTest.java
- kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/PipelineSQLBuilderTest.java
- kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLIncrementalDumper.java
- kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/sqlbuilder/MySQLPipelineSQLBuilderTest.java
- kernel/data-pipeline/dialect/opengauss/src/test/java/org/apache/shardingsphere/data/pipeline/opengauss/sqlbuilder/OpenGaussPipelineSQLBuilderTest.java
- kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALEventConverter.java
- kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/sqlbuilder/PostgreSQLPipelineSQLBuilderTest.java
- test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/importer/PipelineDataSourceSinkTest.java
- Refactor DataRecord type and tableName fields as final
---
> Refactor DataRecord type and tableName fields as final

- infra/context/src/main/java/org/apache/shardingsphere/infra/connection/validator/ShardingSphereMetaDataValidateUtils.java
> Fix code smell.

- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/yaml/swapper/NewYamlShadowRuleConfigurationSwapper.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/converter/ShardingNodeConverter.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapper.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/swapper/strategy/YamlShardingAuditStrategyConfigurationSwapper.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/metadata/converter/ShardingNodeConverterTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapperTest.java
> Improve swap yaml data to rule configuration in sharding

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/Literals.g4
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/SQLUtils.java
- parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SQLUtilsTest.java
- test/it/parser/src/main/resources/case/ddl/create-table.xml
- test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
Fixes #26035.
- Support table name backquote parse
- Add test sql
---
> Support table name backquote parse

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/metadata/converter/EncryptNodeConverter.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlCompatibleEncryptRuleConfigurationSwapper.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlEncryptRuleConfigurationSwapper.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/metadata/converter/EncryptNodeConverterTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlCompatibleEncryptRuleConfigurationSwapperTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlEncryptRuleConfigurationSwapperTest.java
> Improve swap yaml data to rule configuration in encrypt

- kernel/authority/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.yaml.config.swapper.rule.NewYamlRuleConfigurationSwapper
- kernel/global-clock/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.yaml.config.swapper.rule.NewYamlRuleConfigurationSwapper
- kernel/logging/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.yaml.config.swapper.rule.NewYamlRuleConfigurationSwapper
- kernel/single/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.yaml.config.swapper.rule.NewYamlRuleConfigurationSwapper
- kernel/sql-federation/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.yaml.config.swapper.rule.NewYamlRuleConfigurationSwapper
- kernel/sql-parser/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.yaml.config.swapper.rule.NewYamlRuleConfigurationSwapper
- kernel/sql-translator/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.yaml.config.swapper.rule.NewYamlRuleConfigurationSwapper
- kernel/traffic/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.yaml.config.swapper.rule.NewYamlRuleConfigurationSwapper
For https://github.com/apache/shardingsphere/issues/25485 , https://github.com/apache/shardingsphere/issues/26165 .
> Add NewYamlRuleConfigurationSwapper SPI

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/ReadwriteSplittingRuleConfigurationEventBuilder.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/config/AddReadwriteSplittingConfigurationEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/config/AlterReadwriteSplittingConfigurationEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/config/DeleteReadwriteSplittingConfigurationEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/loadbalance/AddLoadBalanceEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/loadbalance/AlterLoadBalanceEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/loadbalance/DeleteLoadBalanceEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingLoadBalanceSubscriber.java
- features/readwrite-splitting/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.rule.RuleConfigurationSubscribeCoordinator
Reverts apache/shardingsphere#26252
> Revert Refactor database rule config refresh logic for new metadata structure

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/ReadwriteSplittingRuleConfigurationEventBuilder.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/converter/GlobalRuleNodeConverter.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/converter/GlobalRuleNodeConverterTest.java
> The watch event parameter is adjusted to Object

- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/alter/AlterStorageUnitStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/alter/impl/AlterEncryptRuleStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/alter/impl/AlterReadwriteSplittingRuleStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/alter/impl/AlterShadowRuleStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/alter/impl/AlterShardingTableReferenceRulesStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/alter/impl/AlterShardingTableRuleStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/create/RegisterStorageUnitStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/create/impl/CreateEncryptRuleStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/create/impl/CreateReadwriteSplittingRuleStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/create/impl/CreateShadowRuleStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/create/impl/CreateShardingTableReferenceRuleStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rdl/create/impl/CreateShardingTableRuleStatementAssert.java
> Adjust code format

- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/SQLFederationExecutor.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/TranslatableTableScanExecutor.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/resultset/SQLFederationResultSet.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/resultset/SQLFederationResultSetMetaData.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/rexnode/SQLOptimizerRexNodeVisitor.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/rexnode/StringToRexNodeUtils.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLFederationCompiler.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLFederationExecutionPlan.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/planner/OptimizerPlannerContextFactory.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/schema/SQLFederationSchema.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/schema/SQLFederationTable.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/util/SQLFederationDataTypeUtils.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/planner/util/SQLFederationPlannerUtils.java
- kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/it/SQLFederationCompilerIT.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
Ref #26011.
- Refactor sql federation package and class name for better understanding
---
> Refactor sql federation package and class name for better understanding

- features/mask/core/pom.xml
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/MaskRuleConfigurationEventBuilder.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/algorithm/AddMaskAlgorithmEvent.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/algorithm/AlterMaskAlgorithmEvent.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/algorithm/DeleteMaskAlgorithmEvent.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/config/AddMaskConfigurationEvent.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/config/AlterMaskConfigurationEvent.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/config/DeleteMaskConfigurationEvent.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/subscriber/MaskAlgorithmSubscriber.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/subscriber/MaskConfigurationSubscriber.java
- features/mask/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.rule.RuleConfigurationSubscribeCoordinator
- features/mask/core/src/main/resources/META-INF/services/org.apache.shardingsphere.mode.event.config.RuleConfigurationEventBuilder
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/ReadwriteSplittingRuleConfigurationEventBuilder.java
> Add feature configuration changed event and subscribe at mask module

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingConfigurationSubscriber.java
- features/shadow/core/pom.xml
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/ShadowRuleConfigurationEventBuilder.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/algorithm/AddShadowAlgorithmEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/algorithm/AlterShadowAlgorithmEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/algorithm/DeleteShadowAlgorithmEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/config/AddShadowConfigurationEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/config/AlterShadowConfigurationEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/config/DeleteShadowConfigurationEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/table/AddShadowTableEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/table/AlterShadowTableEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/table/DeleteShadowTableEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowAlgorithmSubscriber.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowConfigurationSubscriber.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowTableSubscriber.java
- features/shadow/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.rule.RuleConfigurationSubscribeCoordinator
- features/shadow/core/src/main/resources/META-INF/services/org.apache.shardingsphere.mode.event.config.RuleConfigurationEventBuilder
> Add feature configuration changed event and subscribe at shadow module

- distribution/proxy-native/src/main/release-docs/LICENSE
- distribution/proxy/src/main/release-docs/LICENSE
- kernel/transaction/type/xa/provider/atomikos/pom.xml
- test/e2e/operation/transaction/pom.xml
Reverts apache/shardingsphere#26074
> Revert "Update Atomikos to 6.0.0 on javax classifier"

- infra/common/src/main/java/org/apache/shardingsphere/infra/database/type/checker/DatabaseTypeChecker.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesValidator.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/exception/UnsupportedStorageTypeException.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/factory/ExternalMetaDataFactory.java
- test/fixture/jdbc/src/main/java/org/apache/shardingsphere/test/fixture/jdbc/MockedDriver.java
- Add unsupported storage node type
---
> Add unsupported storage node type

- kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/event/AuthorityRuleConfigurationEventBuilder.java
- kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/event/GlobalClockRuleConfigurationEventBuilder.java
- kernel/logging/core/src/main/java/org/apache/shardingsphere/logging/event/LoggingRuleConfigurationEventBuilder.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/NewGlobalNode.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/AbstractPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/NewDatabaseRulePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/global/NewGlobalRulePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/global/NewPropertiesPersistService.java
- kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/persist/node/NewGlobalNodeTest.java
- kernel/single/core/src/main/java/org/apache/shardingsphere/single/event/SingleRuleConfigurationEventBuilder.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/event/SQLFederationRuleConfigurationEventBuilder.java
- kernel/sql-parser/core/src/main/java/org/apache/shardingsphere/parser/event/SQLParserRuleConfigurationEventBuilder.java
- kernel/sql-translator/core/src/main/java/org/apache/shardingsphere/sqltranslator/event/SQLTranslatorConfigurationEventBuilder.java
- kernel/traffic/core/src/main/java/org/apache/shardingsphere/traffic/event/TrafficRuleConfigurationEventBuilder.java
- kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/event/TransactionRuleConfigurationEventBuilder.java
> Extract abstract AbstractPersistService class

- infra/common/src/main/java/org/apache/shardingsphere/infra/database/type/checker/DatabaseTypeChecker.java
- kernel/sql-federation/distsql/handler/pom.xml
- kernel/sql-federation/distsql/handler/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/handler/query/ShowSQLFederationRuleExecutor.java
- kernel/sql-federation/distsql/handler/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/handler/update/AlterSQLFederationRuleStatementUpdater.java
- kernel/sql-federation/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.QueryableRALExecutor
- kernel/sql-federation/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.update.GlobalRuleRALUpdater
- kernel/sql-federation/distsql/handler/src/test/java/org/apache/shardingsphere/sqlfederation/distsql/handler/query/ShowSQLFederationRuleExecutorTest.java
- kernel/sql-federation/distsql/handler/src/test/java/org/apache/shardingsphere/sqlfederation/distsql/handler/update/AlterSQLFederationRuleStatementUpdaterTest.java
- kernel/sql-federation/distsql/parser/pom.xml
- kernel/sql-federation/distsql/parser/src/main/antlr4/imports/sql-federation/Alphabet.g4
- kernel/sql-federation/distsql/parser/src/main/antlr4/imports/sql-federation/Keyword.g4
- kernel/sql-federation/distsql/parser/src/main/antlr4/imports/sql-federation/Literals.g4
- kernel/sql-federation/distsql/parser/src/main/antlr4/imports/sql-federation/RALStatement.g4
- kernel/sql-federation/distsql/parser/src/main/antlr4/imports/sql-federation/Symbol.g4
- kernel/sql-federation/distsql/parser/src/main/antlr4/org/apache/shardingsphere/distsql/parser/autogen/SQLFederationDistSQLStatement.g4
- kernel/sql-federation/distsql/parser/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/parser/core/SQLFederationDistSQLLexer.java
- kernel/sql-federation/distsql/parser/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/parser/core/SQLFederationDistSQLParser.java
- kernel/sql-federation/distsql/parser/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/parser/core/SQLFederationDistSQLStatementVisitor.java
- kernel/sql-federation/distsql/parser/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/parser/facade/SQLFederationDistSQLStatementParserFacade.java
- kernel/sql-federation/distsql/parser/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.parser.engine.spi.FeaturedDistSQLStatementParserFacade
- kernel/sql-federation/distsql/pom.xml
- kernel/sql-federation/distsql/statement/pom.xml
- kernel/sql-federation/distsql/statement/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/segment/CacheOptionSegment.java
- kernel/sql-federation/distsql/statement/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/statement/queryable/ShowSQLFederationRuleStatement.java
- kernel/sql-federation/distsql/statement/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/statement/updatable/AlterSQLFederationRuleStatement.java
- kernel/sql-parser/distsql/handler/src/main/java/org/apache/shardingsphere/parser/distsql/handler/update/AlterSQLParserRuleStatementUpdater.java
- proxy/backend/core/pom.xml
For #26011.
- New DistSQL `SHOW SQL_FEDERATION RULE`
- New DistSQL `ALTER SQL_FEDERATION RULE`
---
> Add DistSQL for sql federation.

- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLFederationCompilerEngine.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/compiler/SQLStatementCompiler.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/compiler/SQLStatementCompilerEngine.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/compiler/SQLStatementCompilerEngineFactory.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/planner/OptimizerPlannerContext.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/planner/cache/ExecutionPlanCacheBuilder.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/planner/cache/ExecutionPlanCacheKey.java
- kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/engine/fixture/decider/SQLFederationDeciderNotMatchFixture.java
- kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/it/SQLFederationCompilerEngineIT.java
Ref #26011.
- Add execution plan cache for sql federation and use useCache flag
---
> Add execution plan cache for sql federation and use useCache flag

- kernel/data-pipeline/api/pom.xml
- kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/executor/AbstractLifecycleExecutor.java
- kernel/data-pipeline/api/src/test/java/org/apache/shardingsphere/data/pipeline/api/executor/AbstractLifecycleExecutorTest.java
- Fix stop job before task starting
---
> Fix stop job before task starting

- kernel/single/core/src/main/java/org/apache/shardingsphere/single/yaml/config/swapper/NewYamlSingleRuleConfigurationSwapper.java
> Fix single rule persist by new metadata

- kernel/single/core/src/test/java/org/apache/shardingsphere/single/yaml/config/swapper/NewYamlSingleRuleConfigurationSwapperTest.java
> Fix single rule UT

- features/readwrite-splitting/distsql/handler/pom.xml
- features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/AlterReadwriteSplittingRuleStatementUpdater.java
- features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/DropReadwriteSplittingRuleStatementUpdater.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/instance/mode/ModeContextManager.java
- infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/update/RuleDefinitionAlterUpdater.java
- infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/update/RuleDefinitionCreateUpdater.java
- infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/update/RuleDefinitionDropUpdater.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/NewDatabaseMetaDataNode.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/DatabaseBasedPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/NewDatabaseRulePersistService.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterModeContextManager.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/RDLBackendHandlerFactory.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/rule/NewRuleDefinitionBackendHandler.java
- proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/RDLBackendHandlerFactoryTest.java
> Add NewRuleDefinitionBackendHandler for new RDL refresh mechanism

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/ReadwriteSplittingRuleConfigurationEventBuilder.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/ShadowRuleConfigurationEventBuilder.java
> Fix feature rule configuration event builder

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptConfigurationSubscriber.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptorSubscriber.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/subscriber/MaskAlgorithmSubscriber.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/subscriber/MaskConfigurationSubscriber.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingConfigurationSubscriber.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingLoadBalanceSubscriber.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowAlgorithmSubscriber.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowConfigurationSubscriber.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowTableSubscriber.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingAlgorithmSubscriber.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingCacheConfigurationSubscriber.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingStrategyConfigurationSubscriber.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingTableConfigurationSubscriber.java
> Fix new configuration subscriber

- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropDefaultShadowAlgorithmStatementUpdater.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropShadowAlgorithmStatementUpdater.java
- features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropShadowRuleStatementUpdater.java
- infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/update/RuleDefinitionDropUpdater.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/rule/NewRuleDefinitionBackendHandler.java
> Refactor shadow RDL updater

- features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/AlterReadwriteSplittingRuleStatementUpdater.java
- features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/DropReadwriteSplittingRuleStatementUpdater.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/rule/NewRuleDefinitionBackendHandler.java
> Fix ReadwriteSplittingRule statement updater

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptConfigurationSubscriber.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/NewConfigurationChangedSubscriber.java
> Fix new database rule subscriber

- features/broadcast/distsql/handler/pom.xml
- jdbc/core/src/main/java/org/apache/shardingsphere/driver/data/pipeline/datasource/creator/ShardingSpherePipelineDataSourceCreator.java
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
- test/e2e/operation/pipeline/src/test/resources/env/common/migration-command.xml
- Pipeline job compatible with sharding rule audit strategy
---
> Pipeline job compatible with sharding rule audit strategy

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterShardingTableRuleStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropDefaultStrategyStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingAlgorithmStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingAuditorStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingKeyGeneratorStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableReferenceRuleStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleStatementUpdater.java
> Refactor ShardingRule RDL statement updater

- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/engine/BroadcastRouteEngineFactory.java
- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/rule/BroadcastRule.java
- features/broadcast/distsql/handler/pom.xml
- features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/query/CountBroadcastRuleExecutor.java
- features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/update/DropBroadcastTableRuleStatementUpdater.java
- features/broadcast/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.query.RQLExecutor
- features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/query/CountBroadcastRuleExecutorTest.java
- features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/query/ShowBroadcastTableRuleExecutorTest.java
- features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/update/CreateBroadcastTableRuleStatementUpdaterTest.java
- features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/update/DropBroadcastTableRuleStatementUpdaterTest.java
- features/broadcast/distsql/parser/src/main/antlr4/imports/broadcast/RQLStatement.g4
- features/broadcast/distsql/parser/src/main/java/org/apache/shardingsphere/broadcast/distsql/parser/core/BroadcastDistSQLStatementVisitor.java
- features/broadcast/distsql/statement/src/main/java/org/apache/shardingsphere/broadcast/distsql/parser/statement/CountBroadcastRuleStatement.java
- test/e2e/sql/src/test/resources/env/scenario/db/proxy/conf/mysql/config-db.yaml
- test/e2e/sql/src/test/resources/env/scenario/db/proxy/conf/opengauss/config-db.yaml
- test/e2e/sql/src/test/resources/env/scenario/db/proxy/conf/postgresql/config-db.yaml
- test/e2e/sql/src/test/resources/env/scenario/db/rules.yaml
- test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/proxy/conf/mysql/config-dbtbl-with-readwrite-splitting.yaml
- test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/proxy/conf/opengauss/config-dbtbl-with-readwrite-splitting.yaml
- test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/proxy/conf/postgresql/config-dbtbl-with-readwrite-splitting.yaml
- test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/rules.yaml
- test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting_and_encrypt/proxy/conf/mysql/config-dbtbl-with-readwrite-splitting-and-encrypt.yaml
- test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting_and_encrypt/proxy/conf/opengauss/config-dbtbl-with-readwrite-splitting-and-encrypt.yaml
- test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting_and_encrypt/proxy/conf/postgresql/config-dbtbl-with-readwrite-splitting-and-encrypt.yaml
- test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting_and_encrypt/rules.yaml
- test/e2e/sql/src/test/resources/env/scenario/sharding_and_encrypt/proxy/conf/mysql/config-sharding-and-encrypt.yaml
- test/e2e/sql/src/test/resources/env/scenario/sharding_and_encrypt/proxy/conf/opengauss/config-sharding-and-encrypt.yaml
- test/e2e/sql/src/test/resources/env/scenario/sharding_and_encrypt/proxy/conf/postgresql/config-sharding-and-encrypt.yaml
- test/e2e/sql/src/test/resources/env/scenario/sharding_and_encrypt/rules.yaml
Fixes #26299.
- add `count broadcast rule` DistSQL
- add test for broadcast statement handler
---
> Add `count broadcast rule` DistSQL

- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterContextManagerBuilder.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/NewRegistryCenter.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/NewGovernanceWatcherFactory.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/subscriber/NewProcessListChangedSubscriber.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/compute/subscriber/NewComputeNodeStatusSubscriber.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/workerid/generator/NewClusterWorkerIdGenerator.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/NewContextManagerSubscriberFacade.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/NewStateChangedSubscriber.java
> Add new subscriber for new metadata structure

- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropCompatibleEncryptRuleStatementUpdater.java
- features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropEncryptRuleStatementUpdater.java
> Refactor EncryptRule RDL statement updater

- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/yaml/swapper/YamlBroadcastRuleConfigurationSwapper.java
- features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/BroadcastRouteEngineFactoryTest.java
- features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/engine/type/broadcast/BroadcastDatabaseBroadcastRoutingEngineTest.java
- features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/engine/type/broadcast/BroadcastInstanceBroadcastRoutingEngineTest.java
- features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/engine/type/broadcast/BroadcastTableBroadcastRoutingEngineTest.java
- features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/engine/type/ignore/BroadcastIgnoreRoutingEngineTest.java
- features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/engine/type/unicast/BroadcastUnicastRoutingEngineTest.java
- features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/rule/builder/BroadcastRuleBuilderTest.java
- features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/yaml/BroadcastRuleConfigurationYamlIT.java
- features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/yaml/swapper/YamlBroadcastRuleConfigurationSwapperTest.java
- features/broadcast/core/src/test/resources/yaml/broadcast-rule.yaml
- features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/update/CreateBroadcastTableRuleStatementUpdater.java
- features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/update/CreateBroadcastTableRuleStatementUpdaterTest.java
- features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/update/DropBroadcastTableRuleStatementUpdaterTest.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rql/rule/broadcast/CountBroadcastRuleStatementTestCase.java
- test/it/parser/src/main/resources/case/rql/show.xml
- test/it/parser/src/main/resources/sql/supported/rql/show.xml
Fixes #26299.
- add test for broadcast core
- add `count broadcast rule` parse test 
---
> Add test for broadcast rule

- features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/update/CreateBroadcastTableRuleStatementUpdaterTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&types=BUG&id=apache_shardingsphere&open=AYjF4F-aVAvaDMbCZkqp
> Fix sonar issue on CreateBroadcastTableRuleStatementUpdaterTest

- features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/update/CreateBroadcastTableRuleStatementUpdaterTest.java
- kernel/sql-translator/core/src/main/java/org/apache/shardingsphere/sqltranslator/yaml/swapper/NewYamlSQLTranslatorRuleConfigurationSwapper.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1941&types=CODE_SMELL&id=apache_shardingsphere&open=AYim9MC9QC8nCOc3cC8w
> Fix sonar issue on NewYamlSQLTranslatorRuleConfigurationSwapper

- kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/persist/node/NewDatabaseMetaDataNodeTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS3578&types=CODE_SMELL&id=apache_shardingsphere&open=AYjAt63Xs3ixWYtaTBKS
> Fix sonar issue on NewDatabaseMetaDataNodeTest

- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/BroadcastSQLRouter.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/statement/SQLStatementCompilerEngine.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1066&types=CODE_SMELL&id=apache_shardingsphere&open=AYjAt6R7s3ixWYtaTBKN
> Fix sonar issue on BroadcastSQLRouter

- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropDefaultShardingStrategyStatementUpdater.java
- features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleStatementUpdater.java
- features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.update.RuleDefinitionUpdater
- features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/DropDefaultShardingStrategyStatementUpdaterTest.java
- infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/exception/rule/RuleInUsedException.java
Revise #23934
- rename DropDefaultStrategyStatementUpdater to DropDefaultShardingStrategyStatementUpdater
- optimize DropShardingTableRuleStatementUpdater
---
> Optimize DropShardingTableRuleStatementUpdater

- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/NewDataSourcePersistService.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/datasource/AlterStorageUnitEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/datasource/RegisterStorageUnitEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/datasource/UnregisterStorageUnitEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/manager/switcher/NewResourceSwitchManager.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/metadata/watcher/NewMetaDataChangedWatcher.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/NewDataSourceChangedSubscriber.java
> Refactor load data source properties for NewDataSourcePersistService

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/ReadwriteSplittingRuleConfigurationEventBuilder.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/config/AddReadwriteSplittingConfigurationEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/config/AlterReadwriteSplittingConfigurationEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/config/DeleteReadwriteSplittingConfigurationEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/loadbalance/AlterLoadBalanceEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/loadbalance/DeleteLoadBalanceEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/metadata/converter/ReadwriteSplittingNodeConverter.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingConfigurationSubscriber.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingLoadBalanceSubscriber.java
- features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/metadata/converter/ReadwriteSplittingNodeConverterTest.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/NewDatabaseMetaDataNode.java
- kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/persist/node/NewDatabaseMetaDataNodeTest.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/datasource/AlterStorageUnitEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/datasource/RegisterStorageUnitEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/datasource/UnregisterStorageUnitEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/schema/table/AlterTableEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/schema/table/DropTableEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/schema/view/AlterViewEvent.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/event/schema/view/DropViewEvent.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterModeContextManager.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/metadata/watcher/NewMetaDataChangedWatcher.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/NewContextManagerSubscriberFacade.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/NewDataSourceChangedSubscriber.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/NewResourceMetaDataChangedSubscriber.java
> Add NewResourceMetaDataChangedSubscriber to refresh schema meta data

- agent/core/src/main/java/org/apache/shardingsphere/agent/core/plugin/config/PluginConfigurationLoader.java
Fix sonar issue:
+ https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1075&id=apache_shardingsphere&open=AYePEBoUmlEb3_Pqvlhq
> Fix sonar issue of PluginConfigurationLoader

- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/broadcast-table/_index.cn.md
- fix a quotation error in document
---
> Fix : fix document issue

- kernel/data-pipeline/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/handler/CDCBackendHandler.java
- kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/check/consistency/SingleTableInventoryDataConsistencyChecker.java
- test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
- CDC E2E add single table test.
---
> CDC E2E add single table test.

- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/global/NewGlobalRulePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/global/NewPropertiesPersistService.java
> Fix global active version bug

- infra/common/src/main/java/org/apache/shardingsphere/infra/config/rule/global/event/AlterGlobalRuleConfigurationEvent.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/config/rule/global/event/DeleteGlobalRuleConfigurationEvent.java
- kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/event/AuthorityRuleConfigurationEventBuilder.java
- kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/event/GlobalClockRuleConfigurationEventBuilder.java
- kernel/logging/core/src/main/java/org/apache/shardingsphere/logging/event/LoggingRuleConfigurationEventBuilder.java
- kernel/single/core/src/main/java/org/apache/shardingsphere/single/event/SingleRuleConfigurationEventBuilder.java
- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/event/SQLFederationRuleConfigurationEventBuilder.java
- kernel/sql-parser/core/src/main/java/org/apache/shardingsphere/parser/event/SQLParserRuleConfigurationEventBuilder.java
- kernel/sql-translator/core/src/main/java/org/apache/shardingsphere/sqltranslator/event/SQLTranslatorConfigurationEventBuilder.java
- kernel/traffic/core/src/main/java/org/apache/shardingsphere/traffic/event/TrafficRuleConfigurationEventBuilder.java
- kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/event/TransactionRuleConfigurationEventBuilder.java
- Add version to global rule event
---
> Add version to global rule event

- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/BroadcastSQLRouter.java
- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/engine/BroadcastRouteEngineFactory.java
- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/rule/BroadcastRule.java
- features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/BroadcastRouteEngineFactoryTest.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/ShardingRouteEngineFactory.java
For #26299.
Fixes sonar issue
+ https://sonarcloud.io/project/issues?resolved=false&id=apache_shardingsphere&open=AYjAt6Rzs3ixWYtaTBKK
+ https://sonarcloud.io/project/issues?resolved=false&id=apache_shardingsphere&open=AYjAt6SDs3ixWYtaTBKP
+ https://sonarcloud.io/project/issues?resolved=false&id=apache_shardingsphere&open=AYjAt5l1s3ixWYtaTBKB
- Remove unused parameters from BroadcastRouteEngineFactory
---
> Remove unused parameters from BroadcastRouteEngineFactory

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/NewUpdatableGlobalRuleRALBackendHandler.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java
> Add new global rule RAL backend handler for new metadata structure

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/version/MetaDataVersion.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/schema/NewTableMetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/schema/NewViewMetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/schema/SchemaMetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/schema/TableMetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/schema/ViewMetaDataPersistService.java
- mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/NewConfigurationChangedSubscriber.java
> Move refresh global rule and database rule to ContextManager

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DDLStatement.g4
- parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java
- parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/ddl/tablespace/TablespaceSegment.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ddl/DDLStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ddl/impl/AlterTablespaceStatementAssert.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/tablespace/ExpectedTablespace.java
- test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ddl/AlterTablespaceStatementTestCase.java
- test/it/parser/src/main/resources/case/ddl/alter-tablespace.xml
- test/it/parser/src/main/resources/sql/supported/ddl/alter-tablespace.xml
Refer #25535.
- Modify alter tablespace syntax
- Add alter tablespace rename parse
- Add test sql
---
> Support alter tablespace rename parse

- src/resources/spotbugs.xml
> Remove from spotbugs.xml cause fixed.

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
- test/it/parser/src/main/resources/case/dml/select.xml
- test/it/parser/src/main/resources/sql/supported/dml/select.xml
> fix: add keyword SYSTEM

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/EncryptRuleConfigurationEventBuilder.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/event/ShardingRuleConfigurationEventBuilder.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/NewDatabaseMetaDataNode.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/DatabaseBasedPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/NewDataSourcePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/NewDatabaseRulePersistService.java
- kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/persist/node/NewDatabaseMetaDataNodeTest.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterModeContextManager.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/NewUpdatableGlobalRuleRALBackendHandler.java
> Refactor StorageUnit RDL statement handler

- .github/workflows/resources/linkcheck/markdown-link-check.json
- deadlink-checker.sh
- docs/document/content/faq/_index.cn.md
- docs/document/content/faq/_index.en.md
- docs/document/content/features/sharding/limitation.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/create-sharding-table-rule.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/create-sharding-table-rule.en.md
- docs/document/content/user-manual/shardingsphere-proxy/startup/bin.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/startup/bin.en.md
- docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
for #26456
- fix the incorrect link in ShardingSphere document
---
> Fix deadlink

- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/ReadwriteSplittingRuleConfigurationEventBuilder.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/config/AddReadwriteSplittingConfigurationEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/config/AlterReadwriteSplittingConfigurationEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/config/DeleteReadwriteSplittingConfigurationEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/loadbalance/AlterLoadBalanceEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/metadata/converter/ReadwriteSplittingNodeConverter.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingConfigurationSubscriber.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingLoadBalanceSubscriber.java
- features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/metadata/converter/ReadwriteSplittingNodeConverterTest.java
- infra/common/src/main/java/org/apache/shardingsphere/infra/instance/mode/ModeContextManager.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterModeContextManager.java
> Refactor readwrite-splitting event build

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
- infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_available_extension_versions.yaml
- infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_available_extensions.yaml
- infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_backend_memory_contexts.yaml
- infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_cast.yaml
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java
- infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
For #24662.
- add `pg_available_extension_versions`
- add `pg_available_extensions`
- add `pg_backend_memory_contexts`
- add `pg_cast`
---
> add pg_catalog tables

- .github/workflows/nightly-check.yml
- add codeql action in nightly check
---
> Add : add codeql action in nightly check

- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/metadata/converter/BroadcastNodeConverter.java
- kernel/single/core/src/main/java/org/apache/shardingsphere/single/metadata/converter/SingleNodeConverter.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS6353&id=apache_shardingsphere&open=AYjadfbAE5e5wkXa0spG
> Fix sonar issues on BroadcastNodeConverter and SingleNodeConverter

- features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/YamlReadwriteSplittingRuleConfigurationSwapperTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=INFO&types=CODE_SMELL&id=apache_shardingsphere&open=AYjVTpHfi_iR0Chb5csT
> Fix sonar issue on YamlReadwriteSplittingRuleConfigurationSwapperTest

- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/NewMetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/database/NewDatabaseMetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/version/MetaDataVersionBasedPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/version/MetaDataVersionPersistService.java
- kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/persist/service/MetaDataVersionPersistServiceTest.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterModeContextManager.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/ConfigurationChangedSubscriber.java
- mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/ConfigurationChangedSubscriberTest.java
> Refactor MetaDataVersionBasedPersistService

- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/ShadowRuleConfigurationEventBuilder.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/algorithm/AlterShadowAlgorithmEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/algorithm/DeleteShadowAlgorithmEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/datasource/AddShadowDataSourceEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/datasource/AlterShadowDataSourceEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/datasource/DeleteShadowDataSourceEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/table/AddShadowTableEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/table/AlterShadowTableEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/table/DeleteShadowTableEvent.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/metadata/converter/ShadowNodeConverter.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowAlgorithmSubscriber.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowDataSourceSubscriber.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowTableSubscriber.java
- features/shadow/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.rule.RuleConfigurationSubscribeCoordinator
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/metadata/converter/ShadowNodeConverterTest.java
> Refactor shadow event & subscriber

- features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/MaskRuleConfigurationEventBuilder.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/algorithm/AlterMaskAlgorithmEvent.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/algorithm/DeleteMaskAlgorithmEvent.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/table/AddMaskTableEvent.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/table/AlterMaskTableEvent.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/table/DeleteMaskTableEvent.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/metadata/converter/MaskNodeConverter.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/subscriber/MaskAlgorithmSubscriber.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/subscriber/MaskTableSubscriber.java
- features/mask/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.rule.RuleConfigurationSubscribeCoordinator
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/metadata/converter/MaskNodeConverterTest.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/ReadwriteSplittingRuleConfigurationEventBuilder.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/loadbalance/DeleteLoadBalanceEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingLoadBalanceSubscriber.java
> Refactor mask event & subscriber

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/EncryptRuleConfigurationEventBuilder.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/encryptor/AlterEncryptorEvent.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/table/AddEncryptTableEvent.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/table/AlterEncryptTableEvent.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/metadata/converter/EncryptNodeConverter.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptTableSubscriber.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptorSubscriber.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/metadata/converter/EncryptNodeConverterTest.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/metadata/converter/ReadwriteSplittingNodeConverter.java
> Refactor encrypt event & subscriber

- kernel/single/core/src/main/java/org/apache/shardingsphere/single/event/SingleRuleConfigurationEventBuilder.java
- kernel/single/core/src/main/java/org/apache/shardingsphere/single/event/config/AddSingleTableEvent.java
- kernel/single/core/src/main/java/org/apache/shardingsphere/single/event/config/AlterSingleTableEvent.java
- kernel/single/core/src/main/java/org/apache/shardingsphere/single/metadata/converter/SingleNodeConverter.java
- kernel/single/core/src/main/java/org/apache/shardingsphere/single/subscriber/SingleConfigurationSubscriber.java
> Refactor single event & subscriber

- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/event/BroadcastRuleConfigurationEventBuilder.java
- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/event/config/AddBroadcastTableEvent.java
- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/event/config/AlterBroadcastTableEvent.java
- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/event/config/DeleteBroadcastTableEvent.java
- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/metadata/converter/BroadcastNodeConverter.java
- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/subscriber/BroadcastConfigurationSubscriber.java
- features/broadcast/core/src/main/test/org/apache/shardingsphere/broadcast/metadata/convert/BroadcastNodeConverterTest.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/ReadwriteSplittingRuleConfigurationEventBuilder.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/datasource/AddReadwriteSplittingDataSourceEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/datasource/AlterReadwriteSplittingDataSourceEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/datasource/DeleteReadwriteSplittingDataSourceEvent.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingDataSourceSubscriber.java
- features/readwrite-splitting/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.rule.RuleConfigurationSubscribeCoordinator
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/NewDatabaseMetaDataNode.java
> Refactor broadcast event & subscriber

- kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java
> Fix sql federation NPE

- parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
- parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
- test/it/parser/src/main/resources/case/ddl/create-view.xml
- test/it/parser/src/main/resources/sql/supported/ddl/create-view.xml
Refer #25535.
- Support udf function parse for mysql
- Add test sql
---
> Support udf function parse for mysql

- infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/version/MetaDataVersion.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/NewDataSourcePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/NewDatabaseRulePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/schema/NewTableMetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/schema/NewViewMetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/version/MetaDataVersionPersistService.java
- kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/persist/service/MetaDataVersionPersistServiceTest.java
> Remove active_version suffix for MetaDataVersion key

- docs/document/content/dev-manual/sharding.cn.md
- docs/document/content/dev-manual/sharding.en.md
for #26456
- fix the incorrect link in sharding doc
---
> Fix : fix the incorrect link in sharding doc (#26456)

- docs/community/content/team/_index.cn.md
for #26456
- fix the incorrect link in team doc
---
> Fix : fix the incorrect link in team doc (#26456)

- infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/state/DataSourceStateManager.java
- Initialize dataSource state only once
---
> Initialize dataSource state only once

- docs/community/content/powered-by/_index.cn.md
- docs/community/content/powered-by/_index.en.md
for #26456.
- remove the link does not exist
---
> Fix : remove the link does not exist (#26456)

- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
Fixes 
https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS2250&id=apache_shardingsphere&open=AYg4ki7rjaR3HNxhP8-6 https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS2250&id=apache_shardingsphere&open=AYg4ki7rjaR3HNxhP8-7
> Avoid using CopyOnWriteArrayList in DatabaseConnector

- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/event/BroadcastRuleConfigurationEventBuilder.java
- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/event/config/DeleteBroadcastTableEvent.java
- features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/subscriber/BroadcastConfigurationSubscriber.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/ShadowRuleConfigurationEventBuilder.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/event/ShardingRuleConfigurationEventBuilder.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/converter/ShardingNodeConverter.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/metadata/converter/ShardingNodeConverterTest.java
> Refactor features event & subscriber

- infra/common/src/main/java/org/apache/shardingsphere/infra/instance/mode/ModeContextManager.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/version/MetaDataVersionPersistService.java
- mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterModeContextManager.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/NewUpdatableGlobalRuleRALBackendHandler.java
- proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/rule/NewRuleDefinitionBackendHandler.java
> Switch active version after configuration altered

- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlCompatibleEncryptRuleConfigurationSwapper.java
- features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlEncryptRuleConfigurationSwapper.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlCompatibleEncryptRuleConfigurationSwapperTest.java
- features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlEncryptRuleConfigurationSwapperTest.java
- features/mask/core/src/main/java/org/apache/shardingsphere/mask/yaml/swapper/NewYamlMaskRuleConfigurationSwapper.java
- features/mask/core/src/test/java/org/apache/shardingsphere/mask/yaml/swapper/NewYamlMaskRuleConfigurationSwapperTest.java
- features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/NewYamlReadwriteSplittingRuleConfigurationSwapper.java
- features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/NewYamlReadwriteSplittingRuleConfigurationSwapperTest.java
- features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/yaml/swapper/NewYamlShadowRuleConfigurationSwapper.java
- features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/yaml/swapper/NewYamlShadowRuleConfigurationSwapperTest.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapper.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapperTest.java
- kernel/single/core/src/main/java/org/apache/shardingsphere/single/yaml/config/swapper/NewYamlSingleRuleConfigurationSwapper.java
> Refactor rule swap in new swapper

- .github/workflows/nightly-check.yml
- increase the timeout for nightly action
---
> Refactor : increase the timeout for nightly action

- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/ddl/impl/ShardingAlterTableStatementValidator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/ddl/impl/ShardingRenameTableStatementValidator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/ShardingDMLStatementValidator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/impl/ShardingInsertStatementValidator.java
- features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/ddl/ShardingAlterTableStatementValidatorTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/ddl/ShardingRenameTableStatementValidatorTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/ShardingDeleteStatementValidatorTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/ShardingInsertStatementValidatorTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/ShardingUpdateStatementValidatorTest.java
- features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java
- Replace stream api usage in ShardingRule#isNeedAccumulate method
---
> Replace stream api usage in ShardingRule#isNeedAccumulate method

- test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/ITContainers.java
> Fix Docker network leakage in E2E

- features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/route/qualified/type/QualifiedReadwriteSplittingTransactionalDataSourceRouterTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=apache_shardingsphere&open=AYjxeUG8bgpyf8X-apGS
> Fix sonar issue on QualifiedReadwriteSplittingTransactionalDataSourceRouterTest

- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/NewDataSourcePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/NewDatabaseRulePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/global/NewGlobalRulePersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/schema/NewTableMetaDataPersistService.java
- kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/schema/NewViewMetaDataPersistService.java
> Refactor meta data persist default active version
