apache/shardingsphere

kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/yaml/swapper/NewYamlTransactionRuleConfigurationSwapper.java, mode/type/cluster/repository/provider/zookeeper/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/ZookeeperRepository.java, mode/type/cluster/repository/provider/zookeeper/src/test/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/ZookeeperRepositoryTest.java
=> Fix set default transaction when new cluster startup

proxy/bootstrap/src/main/resources/conf/config-sharding.yaml, proxy/bootstrap/src/main/resources/conf/server.yaml
=> Revert default config

mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/ClusterContextManagerBuilder.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/ConfigurationChangedSubscriber.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/ContextManagerSubscriberFacade.java, mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/ConfigurationChangedSubscriberTest.java
Sonar link : https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYjvDh-JggyGjxkFIX-C
=> Fix sonar issue for ConfigurationChangedSubscriber

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/framework/param/array/E2ETestParameterGenerator.java, test/e2e/sql/src/test/resources/cases/dql/dql-integration-select.xml, test/e2e/sql/src/test/resources/env/scenario/rdl_empty_rules/data/actual/databases.xml
=> Fix the issue of some e2e test cases not working properly.

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/context/OptimizerContext.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/rule/SQLFederationRule.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/RDLE2EIT.java
Fixes #26563.
- Fix npe when create database with postgres database
---
=> Fix npe when create database with postgres database

.github/workflows/nightly-check.yml
=> Add : add stale action

.github/workflows/nightly-check.yml
- refactor the stale time in stale action
---
=> Refactor : refactor the stale time in stale action

kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/version/MetaDataVersionPersistService.java, mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
=> Fix new metadata persist and renew

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/InlineShardingAlgorithm.java
- https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1696&id=apache_shardingsphere&open=AYgzI1y5XDiqwzmzK-K_
---
=> Fix sonar issue in InlineShardingAlgorithm

features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlCompatibleEncryptRuleConfigurationSwapperTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlEncryptRuleConfigurationSwapperTest.java, features/mask/core/src/test/java/org/apache/shardingsphere/mask/yaml/swapper/NewYamlMaskRuleConfigurationSwapperTest.java, features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/NewYamlReadwriteSplittingRuleConfigurationSwapperTest.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/ShadowRuleConfigurationEventBuilder.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/algorithm/AlterDefaultShadowAlgorithmNameEvent.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/algorithm/DeleteDefaultShadowAlgorithmNameEvent.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/metadata/converter/ShadowNodeConverter.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/DefaultShadowAlgorithmNameSubscriber.java, features/shadow/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.rule.RuleChangedSubscriber, features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/yaml/swapper/NewYamlShadowRuleConfigurationSwapperTest.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/converter/ShardingNodeConverter.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapperTest.java, infra/common/src/main/java/org/apache/shardingsphere/infra/config/converter/GlobalNodeConverter.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/converter/RuleItemNodeConverter.java, infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/converter/RuleItemNodeConverterTest.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/metadata/converter/SingleNodeConverter.java
=> Refactor pattern for metadata node

docs/document/content/features/sharding/concept.cn.md, docs/document/content/features/sharding/concept.en.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/single.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/single.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/single-table/load-single-table.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/single-table/load-single-table.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/single-table/set-default-single-table-storage-unit.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/single-table/set-default-single-table-storage-unit.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/single-table/unload-single-table.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/single-table/unload-single-table.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/single-table/show-single-table.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/single-table/show-single-table.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/single-table/show-unloaded-single-tables.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/single-table/show-unloaded-single-tables.en.md
Fixes #22887.
Add docs for single tables:
- single table YAML configuration
- DistSQL doc: `LOAD SINGLE TABLE`
- DistSQL doc: `UNLOAD SINGLE TABLE`
- DistSQL doc: `SHOW UNLOADED SINGLE TABLES`
=> Fixes #22887, add docs for single tables.

infra/common/src/test/java/org/apache/shardingsphere/infra/database/impl/DataSourceGeneratedDatabaseConfigurationTest.java, proxy/backend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/PostgreSQLAdminExecutorCreator.java
Fix sonar issue:
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYiXgb3HgFPhSO7-ARh6
=> Fix sonar issue, remove unused field PG_ROLES

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dal/show/ShowCreateTableMergedResult.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByMemoryMergedResultTest.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/insert/keygen/engine/GeneratedKeyContextEngine.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/data/collector/ShardingSphereTableDataCollectorUtils.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTable.java, infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/schema/swapper/YamlTableSwapper.java, infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/GenericSchemaBuilderTest.java, infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTableTest.java, infra/common/src/test/java/org/apache/shardingsphere/infra/yaml/schema/swapper/YamlSchemaSwapperTest.java, infra/context/src/main/java/org/apache/shardingsphere/infra/connection/refresher/type/index/AlterIndexStatementSchemaRefresher.java, infra/context/src/main/java/org/apache/shardingsphere/infra/connection/refresher/type/index/CreateIndexStatementSchemaRefresher.java, infra/context/src/main/java/org/apache/shardingsphere/infra/connection/refresher/type/index/DropIndexStatementSchemaRefresher.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/listener/ShardingSphereDataScheduleCollector.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/listener/ShardingSphereDataCollectorTest.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/data/ShardingSphereDataPersistService.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/schema/ShardingSphereTableRowDataPersistService.java, kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/persist/service/DatabaseMetaDataPersistServiceTest.java, kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/persist/service/schema/TableMetaDataPersistServiceTest.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/metadata/util/SQLFederationDataTypeUtils.java, mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java, mode/core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowTableMetaDataExecutor.java, proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutor.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/RALE2EIT.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/RDLE2EIT.java, test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/scenario/MixSQLRewriterIT.java, test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/scenario/ShardingSQLRewriterIT.java
Fixes #26600
- Fix sharding sphere table equals
---
=> Fix sharding sphere table equals

features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingDataSourceSubscriber.java, features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingLoadBalanceSubscriber.java
=> Refactor readwrite-splitting subscriber

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/single.en.md
=> Fix : fix a dead link

features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/DefaultShadowAlgorithmNameSubscriber.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowAlgorithmSubscriber.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowDataSourceSubscriber.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowTableSubscriber.java
For https://github.com/apache/shardingsphere/issues/25485.
=> Refactor shadow subscriber

infra/common/src/main/java/org/apache/shardingsphere/infra/instance/mode/ModeContextManager.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/node/NewGlobalNode.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/global/NewPropertiesPersistService.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/ClusterModeContextManager.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterModeContextManager.java, mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneModeContextManager.java
=> Alter props switch to active_version

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingAlgorithmSubscriber.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingCacheConfigurationSubscriber.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingStrategyConfigurationSubscriber.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingTableConfigurationSubscriber.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapper.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapperTest.java
=> Refactor sharding rule changed subscriber

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/yaml/swapper/NewYamlBroadcastRuleConfigurationSwapper.java, features/broadcast/core/src/main/test/org/apache/shardingsphere/broadcast/yaml/swapper/NewYamlBroadcastRuleConfigurationSwapperTest.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptTableSubscriber.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptorSubscriber.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/compatible/CompatibleEncryptTableSubscriber.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/compatible/CompatibleEncryptorSubscriber.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlCompatibleEncryptRuleConfigurationSwapper.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlEncryptRuleConfigurationSwapper.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlCompatibleEncryptRuleConfigurationSwapperTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlEncryptRuleConfigurationSwapperTest.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/subscriber/MaskAlgorithmSubscriber.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/subscriber/MaskTableSubscriber.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/yaml/swapper/NewYamlMaskRuleConfigurationSwapper.java, features/mask/core/src/test/java/org/apache/shardingsphere/mask/yaml/swapper/NewYamlMaskRuleConfigurationSwapperTest.java, features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/NewYamlReadwriteSplittingRuleConfigurationSwapper.java, features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/NewYamlReadwriteSplittingRuleConfigurationSwapperTest.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/yaml/swapper/NewYamlShadowRuleConfigurationSwapper.java, features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/yaml/swapper/NewYamlShadowRuleConfigurationSwapperTest.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapper.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapperTest.java, infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/NewYamlRuleConfigurationSwapperEngine.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/yaml/config/swapper/NewYamlSingleRuleConfigurationSwapper.java, test/e2e/agent/plugins/logging/file/src/test/java/org/apache/shardingsphere/test/e2e/agent/file/FilePluginE2EIT.java
=> Refactor encrypt & mask rule changed subscriber

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/MySQLKeyword.g4, parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/RLStatement.g4, parser/sql/dialect/mysql/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/MySQLStatement.g4, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLRLStatementVisitor.java, parser/sql/engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/rl/MySQLChangeReplicationSourceToStatement.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rl/ChangeReplicationSourceToStatementTestCase.java, test/it/parser/src/main/resources/case/rl/change-replication-source-to.xml, test/it/parser/src/main/resources/sql/supported/rl/change-replication-source-to.xml
Ref #25535.
- Support Change replication source statement for mysql
- Add test parse sql
---
=> Support Change replication source statement for mysql

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/framework/E2EExtension.java, test/e2e/sql/src/test/resources/env/scenario/db/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting_and_encrypt/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/empty_rules/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/encrypt/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/encrypt_and_readwrite_splitting/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/encrypt_shadow/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/mask/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/mask_encrypt/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/mask_encrypt_sharding/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/mask_sharding/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/passthrough/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/rdl_empty_rules/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/readwrite_splitting/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/readwrite_splitting_and_shadow/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/shadow/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/sharding_and_encrypt/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/sharding_and_shadow/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/sharding_encrypt_shadow/rules.yaml, test/e2e/sql/src/test/resources/env/scenario/tbl/rules.yaml, test/e2e/sql/src/test/resources/logback-test.xml
=> Optimizing E2E logs.

docs/document/content/user-manual/shardingsphere-proxy/migration/usage.cn.md, docs/document/content/user-manual/shardingsphere-proxy/migration/usage.en.md
- Remove REFRESH TABLE METADATA in usage doc
---
=> Update pipeline doc

kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/yaml/swapper/NewYamlTransactionRuleConfigurationSwapper.java
- Fix alter transaction rule in new cluster mode
---
=> Fix alter transaction rule in new cluster mode

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptTableSubscriber.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/compatible/CompatibleEncryptTableSubscriber.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/subscriber/MaskTableSubscriber.java, features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingDataSourceSubscriber.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowDataSourceSubscriber.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingTableConfigurationSubscriber.java
=> Refactor features rule changed subscriber

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/enums/ShardingStrategyType.java
- https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=apache_shardingsphere&open=AYePD-m2mlEb3_PqvlQm
---
=> Fix sonar issue in ShardingStrategyType

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/event/BroadcastRuleConfigurationEventBuilder.java
=> Fix broadcast event builder

kernel/single/core/src/main/java/org/apache/shardingsphere/single/event/SingleRuleConfigurationEventBuilder.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/rule/NewRuleDefinitionBackendHandler.java
=> Fix single event builder

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/subscriber/BroadcastConfigurationSubscriber.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/CompatibleEncryptRuleConfigurationEventBuilder.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/EncryptRuleConfigurationEventBuilder.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/compatible/encryptor/DeleteCompatibleEncryptorEvent.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/compatible/table/DeleteCompatibleEncryptTableEvent.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/encryptor/DeleteEncryptorEvent.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/table/DeleteEncryptTableEvent.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptTableSubscriber.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptorSubscriber.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/compatible/CompatibleEncryptTableSubscriber.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/compatible/CompatibleEncryptorSubscriber.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/subscriber/MaskAlgorithmSubscriber.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/subscriber/MaskTableSubscriber.java, features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingDataSourceSubscriber.java, features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingLoadBalanceSubscriber.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/DefaultShadowAlgorithmNameSubscriber.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowAlgorithmSubscriber.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowDataSourceSubscriber.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowTableSubscriber.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingAlgorithmSubscriber.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingCacheConfigurationSubscriber.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingStrategyConfigurationSubscriber.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingTableConfigurationSubscriber.java, mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/NewDataSourceChangedSubscriber.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/NewResourceMetaDataChangedSubscriber.java, mode/type/cluster/repository/provider/zookeeper/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/ZookeeperRepository.java, proxy/bootstrap/src/main/resources/conf/server.yaml
=> Enhanced delete metadata refresh

mode/type/cluster/repository/provider/zookeeper/src/main/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/ZookeeperRepository.java, proxy/bootstrap/src/main/resources/conf/server.yaml
=> Revert #26630

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/metadata/nodepath/BroadcastNodePath.java
=> Fix BroadcastNodePath

test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/cursor/OpenGaussCursorTestCase.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/engine/command/CursorSQL.java, test/e2e/operation/transaction/src/test/resources/env/common/cursor-command.xml
Fixes #26633.
- optimize OpenGaussCursorTestCase, add cursor-name for case
---
=> add cursor-name for cursor-command

test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/util/PipelineContextUtils.java
- Pipeline IT compatible with New_Cluster mode
---
=> Pipeline IT compatible with New_Cluster mode

features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/checker/ReadwriteSplittingRuleConfigurationChecker.java, features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingDataSourceSubscriber.java, features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingLoadBalanceSubscriber.java
=> Fix read-write splitting rule changed subscriber

mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterModeContextManager.java
=> Refactor NewClusterModeContextManager.alterRuleConfiguration

test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/AbstractMigrationE2EIT.java
- Use Awaitility replace sleep at CDC E2E
---
=> Use Awaitility replace sleep at CDC E2E

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/rule/NewRuleDefinitionBackendHandler.java
=> Fix new RDL handler for single table

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/statistics/builder/PostgreSQLShardingSphereStatisticsBuilderTest.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/DriverExecutor.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/listener/ShardingSphereStatisticsScheduleCollector.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/listener/ShardingSphereDataCollectorTest.java, kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerablePushDownTableScanExecutorTest.java, mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/MetaDataContexts.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/MetaDataContextsFactory.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/NewMetaDataContextsFactory.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxySQLExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/PreviewExecutor.java, proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussSystemCatalogAdminQueryExecutor.java
- Rename shardingSphereData field name to statistics
---
=> Rename shardingSphereData field name to statistics

features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/AlterDefaultShadowAlgorithmStatementUpdater.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/CreateDefaultShadowAlgorithmStatementUpdater.java
- Fix algorithm check of shadow rule updater
=> Fix shadow algorithm updater

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java
- https://sonarcloud.io/project/issues?fileUuids=AYePD8WHmlEb3_PqvjGS&resolved=false&id=apache_shardingsphere&open=AYjAt5zzs3ixWYtaTBKC
---
=> Remove repetitive join condition judgement logic for sonar issue

docs/document/content/features/sharding/concept.cn.md, docs/document/content/features/sharding/concept.en.md
- Update sharding binding table document
---
=> Update sharding binding table document

kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/yaml/swapper/NewYamlAuthorityRuleConfigurationSwapper.java, kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/yaml/swapper/NewYamlGlobalClockRuleConfigurationSwapper.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/yaml/swapper/NewYamlSQLFederationRuleConfigurationSwapper.java, kernel/sql-parser/core/src/main/java/org/apache/shardingsphere/parser/yaml/swapper/NewYamlSQLParserRuleConfigurationSwapper.java, kernel/sql-translator/core/src/main/java/org/apache/shardingsphere/sqltranslator/yaml/swapper/NewYamlSQLTranslatorRuleConfigurationSwapper.java, kernel/traffic/core/src/main/java/org/apache/shardingsphere/traffic/yaml/swapper/NewYamlTrafficRuleConfigurationSwapper.java, kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/yaml/swapper/NewYamlTransactionRuleConfigurationSwapper.java
=> Fix global rule swapper

test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/AbstractMigrationE2EIT.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/util/AwaitTimeoutUtil.java
- Add record exist check at no unique key migration E2E 
---
=> Add record exist check at no unique key migration E2E 

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/yaml/swapper/NewYamlBroadcastRuleConfigurationSwapper.java, features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/yaml/swapper/NewYamlBroadcastRuleConfigurationSwapperTest.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlCompatibleEncryptRuleConfigurationSwapper.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlEncryptRuleConfigurationSwapper.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlCompatibleEncryptRuleConfigurationSwapperTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/swapper/NewYamlEncryptRuleConfigurationSwapperTest.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/yaml/swapper/NewYamlMaskRuleConfigurationSwapper.java, features/mask/core/src/test/java/org/apache/shardingsphere/mask/yaml/swapper/NewYamlMaskRuleConfigurationSwapperTest.java, features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/NewYamlReadwriteSplittingRuleConfigurationSwapper.java, features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/NewYamlReadwriteSplittingRuleConfigurationSwapperTest.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/yaml/swapper/NewYamlShadowRuleConfigurationSwapper.java, features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/yaml/swapper/NewYamlShadowRuleConfigurationSwapperTest.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapper.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/NewYamlShardingRuleConfigurationSwapperTest.java, infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/NewYamlGlobalRuleConfigurationSwapperEngine.java, infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/config/swapper/rule/NewYamlRuleConfigurationSwapperEngine.java, infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/swapper/NewYamlConfigurationSwapper.java, kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/yaml/swapper/NewYamlAuthorityRuleConfigurationSwapper.java, kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/core/yaml/swapper/NewYamlGlobalClockRuleConfigurationSwapper.java, kernel/logging/core/src/main/java/org/apache/shardingsphere/logging/yaml/swapper/NewYamlLoggingRuleConfigurationSwapper.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/yaml/config/swapper/NewYamlSingleRuleConfigurationSwapper.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/yaml/swapper/NewYamlSQLFederationRuleConfigurationSwapper.java, kernel/sql-parser/core/src/main/java/org/apache/shardingsphere/parser/yaml/swapper/NewYamlSQLParserRuleConfigurationSwapper.java, kernel/sql-translator/core/src/main/java/org/apache/shardingsphere/sqltranslator/yaml/swapper/NewYamlSQLTranslatorRuleConfigurationSwapper.java, kernel/traffic/core/src/main/java/org/apache/shardingsphere/traffic/yaml/swapper/NewYamlTrafficRuleConfigurationSwapper.java, kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/yaml/swapper/NewYamlTransactionRuleConfigurationSwapper.java
=> Refactor new YAML configuration swapper

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/rule/NewRuleDefinitionBackendHandler.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1941&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYj-gZpmrJmnVRfbd76G
=> Fix sonar issue on NewRuleDefinitionBackendHandler

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportMetaDataUpdater.java
=> Refactor import metadata support new metadata

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/subscriber/BroadcastConfigurationSubscriber.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptTableSubscriber.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/EncryptorSubscriber.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/compatible/CompatibleEncryptTableSubscriber.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/subscriber/compatible/CompatibleEncryptorSubscriber.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/subscriber/MaskAlgorithmSubscriber.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/subscriber/MaskTableSubscriber.java, features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingDataSourceSubscriber.java, features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/subscriber/ReadwriteSplittingLoadBalanceSubscriber.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/DefaultShadowAlgorithmNameSubscriber.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowAlgorithmSubscriber.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowDataSourceSubscriber.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/subscriber/ShadowTableSubscriber.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingAlgorithmSubscriber.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingCacheConfigurationSubscriber.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingStrategyConfigurationSubscriber.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/subscriber/ShardingTableConfigurationSubscriber.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/subscriber/SingleConfigurationSubscriber.java, mode/core/src/main/java/org/apache/shardingsphere/mode/subsciber/RuleChangedSubscriber.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterContextManagerBuilder.java
=> Refactor rule changed subscribers

kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java
- Improve migration commit, make sure stop job before drop
---
=> Improve migration commit, make sure stop job before drop

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/event/BroadcastRuleChangedEventCreator.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/ShadowRuleChangedEventCreator.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/event/SingleRuleChangedEventCreator.java
Fix https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1301&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere
=> Fix sonar issues of Replace this "switch" statement by "if" statements to increase readability.

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptAlterTableTokenGenerator.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java
- https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1871&types=CODE_SMELL&id=apache_shardingsphere&open=AYjadetzE5e5wkXa0so1
---
=> Fix sonar issue in MySQLDDLStatementVisitor

kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableStatementUpdater.java, kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableStatementUpdaterTest.java
=> For #26717, fix load single table and add test

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/DoStatementAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/dostatement/ExpectedDoParameter.java, test/it/parser/src/main/resources/case/dml/do.xml, test/it/parser/src/main/resources/sql/supported/dml/do.xml
Ref #25535.
- Enhance MySQL do syntax rules
- Modify previous test cases
- Add test sql
---
=> Enhance MySQL do syntax rules

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java
Ref #25535.
- Optimize alter tablespace parse implement
---
=> Optimize alter tablespace parse implement

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
Fixes #25535 #26687 
- Support RLIKE parse for MySQL
- Add test sql
---
=> Support RLIKE parse for MySQL

features/broadcast/api/src/main/java/org/apache/shardingsphere/broadcast/api/config/BroadcastRuleConfiguration.java, features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/api/config/CompatibleEncryptRuleConfiguration.java, features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/api/config/EncryptRuleConfiguration.java, features/mask/api/src/main/java/org/apache/shardingsphere/mask/api/config/MaskRuleConfiguration.java, features/readwrite-splitting/api/src/main/java/org/apache/shardingsphere/readwritesplitting/api/ReadwriteSplittingRuleConfiguration.java, features/shadow/api/src/main/java/org/apache/shardingsphere/shadow/api/config/ShadowRuleConfiguration.java, features/sharding/api/src/main/java/org/apache/shardingsphere/sharding/api/config/ShardingRuleConfiguration.java, infra/common/src/main/java/org/apache/shardingsphere/infra/config/rule/scope/DatabaseRuleConfiguration.java, infra/common/src/main/java/org/apache/shardingsphere/infra/rule/builder/database/DatabaseRulesBuilder.java, infra/common/src/test/java/org/apache/shardingsphere/infra/rule/builder/fixture/FixtureDatabaseRuleConfiguration.java, kernel/single/api/src/main/java/org/apache/shardingsphere/single/api/config/SingleRuleConfiguration.java
=> Add method isEmpty() to DatabaseRuleConfiguration

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/condition/EncryptConditionEngine.java
- Refactor createBinaryEncryptCondition code style according to code review
---
=> Refactor createBinaryEncryptCondition code style according to code review

kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/job/CDCJob.java
- Persist job progress when start incremental task of CDC
---
=> Persist job progress when start incremental task of CDC

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/parser/src/main/resources/case/dml/select-sub-query.xml, test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml, test/it/parser/src/main/resources/sql/supported/dml/select-sub-query.xml
Ref #25535.
- Support MySQL LATERAL query parse
- Add test sql
---
=> Support MySQL LATERAL query parse

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/operator/physical/EnumerableScan.java
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=apache_shardingsphere&open=AYkijWwdT-5DCSEVooth
---
=> Fix sonar issue in EnumerableScan

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/collector/opengauss/pgcatalog/OpenGaussPgClassTableCollector.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/collector/opengauss/pgcatalog/OpenGaussPgNamespaceTableCollector.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/collector/postgresql/pgcatalog/PostgreSQLPgClassTableCollector.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/collector/postgresql/pgcatalog/PostgreSQLPgNamespaceTableCollector.java, infra/common/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.metadata.statistics.collector.ShardingSphereStatisticsCollector, infra/common/src/main/resources/schema/opengauss/pg_catalog/pg_class.yaml, infra/common/src/main/resources/schema/opengauss/pg_catalog/pg_rules.yaml, infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_class.yaml, infra/common/src/main/resources/schema/postgresql/pg_catalog/pg_roles.yaml, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/listener/ShardingSphereStatisticsScheduleCollector.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/listener/ShardingSphereDataCollectorFixture.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/listener/ShardingSphereDataCollectorTest.java
Fixes #26773.
- Optimize the type return value of the ShardingSphereStatisticsCollector implementation class
- Add oid for pg_roles table
---
=> Optimize the type return value of the ShardingSphereStatisticsCollector implementation class

features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/event/ShadowRuleChangedEventCreatorTest.java
Fixes #26706.
-
---
- [✅] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [✅] I have self-reviewed the commit code.
- [✅] I have (or in comment I request) added corresponding labels for the pull request.
- [✅] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [✅] I have made corresponding changes to the documentation.
- [✅] I have added corresponding unit tests for my changes.
=> [26706] Add test cases for ShadowRuleChangedEventCreator

features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/event/ReadwriteSplittingRuleChangedEventCreatorTest.java
Fixes #26705
-
---
- [✅] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [ ✅] I have self-reviewed the commit code.
- [ ✅] I have (or in comment I request) added corresponding labels for the pull request.
- [✅ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [✅ ] I have made corresponding changes to the documentation.
- [ ✅] I have added corresponding unit tests for my changes.
=> [26705] Unit test cases for ReadwriteSplittingRuleChangedEventCreator

jdbc/core/src/main/java/org/apache/shardingsphere/driver/ShardingSphereDriver.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/DriverDataSourceCache.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURLManager.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURLProvider.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/AbsolutePathDriverURLProvider.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/ApolloDriverURLProvider.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/ClasspathDriverURLProvider.java, jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/driver/DriverDataSourceCacheTest.java, jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereDriverURLManagerTest.java
=> shardingsphere driver supports url prefix

kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/factory/ExternalMetaDataFactory.java
=> Fix force startup

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/CompatibleEncryptRuleChangedEventCreator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/event/EncryptRuleChangedEventCreator.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/event/MaskRuleChangedEventCreator.java, features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/event/ReadwriteSplittingRuleChangedEventCreator.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/event/ShadowRuleChangedEventCreator.java
- Fix itemName parameter passing in event creator
---
=> Fix event creator

agent/plugins/core/pom.xml, agent/plugins/core/src/main/java/org/apache/shardingsphere/agent/plugin/core/enums/SQLStatementType.java, agent/plugins/core/src/main/java/org/apache/shardingsphere/agent/plugin/core/util/SQLStatementUtil.java, agent/plugins/core/src/main/java/org/apache/shardingsphere/agent/plugin/core/util/ShardingSphereDriverUtil.java, agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/SQLParseCountAdvice.java, agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/SQLRouteCountAdvice.java, agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/exporter/impl/jdbc/JDBCMetaDataInfoExporter.java, agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/exporter/impl/jdbc/JDBCStateExporter.java
Fixes #26807.
- Optimize SQLType in routed_sql_total and routed_sql_total metrics 
- Add ShardingSphereDriverUtil to get ShardingSphereDriver
---
=> Optimize SQLType in routed_sql_total and routed_sql_total metrics 

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterShardingTableRuleStatementUpdater.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropDefaultShardingStrategyStatementUpdater.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleStatementUpdater.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/update/RuleDefinitionDropUpdater.java
=> Remove useless algorithm after drop sharing config item

features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropCompatibleEncryptRuleStatementUpdater.java, features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropEncryptRuleStatementUpdater.java, features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/update/DropMaskRuleStatementUpdater.java, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/DropReadwriteSplittingRuleStatementUpdater.java, features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/DropReadwriteSplittingRuleStatementUpdaterTest.java, features/shadow/api/src/main/java/org/apache/shardingsphere/shadow/api/config/ShadowRuleConfiguration.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropShadowRuleStatementUpdater.java
=> Remove useless config item after drop rule item

infra/common/src/main/java/org/apache/shardingsphere/infra/database/metadata/url/StandardJdbcUrlParser.java, kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/datasource/config/impl/ShardingSpherePipelineDataSourceConfiguration.java, kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/datasource/config/impl/StandardPipelineDataSourceConfiguration.java, kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/spi/datasource/JdbcQueryPropertiesExtension.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/datasource/H2JdbcQueryPropertiesExtension.java, kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/datasource/MySQLJdbcQueryPropertiesExtension.java, kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/datasource/MySQLJdbcQueryPropertiesExtensionTest.java, kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/datasource/OpenGaussJdbcQueryPropertiesExtension.java, kernel/data-pipeline/dialect/opengauss/src/test/java/org/apache/shardingsphere/data/pipeline/opengauss/datasource/OpenGaussJdbcQueryPropertiesExtensionTest.java, kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/datasource/PostgreSQLJdbcQueryPropertiesExtension.java, kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/datasource/PostgreSQLJdbcQueryPropertiesExtensionTest.java
- Refactor JdbcQueryPropertiesExtension, some parameters should not be overridden
---
=> Refactor JdbcQueryPropertiesExtension

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/InsertValue.java, infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/InsertValueTest.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dal/VariableSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/column/ColumnSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/BetweenExpression.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/CaseWhenExpression.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/CollateExpression.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/ExistsSubqueryExpression.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/ExpressionSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/InExpression.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/ListExpression.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/NotExpression.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/ValuesExpression.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/complex/CommonTableExpressionSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/simple/LiteralExpressionSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/simple/ParameterMarkerExpressionSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/subquery/SubqueryExpressionSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/subquery/SubquerySegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/item/AggregationProjectionSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/DataTypeSegment.java
- Fix sysdate class cast exception
---
=> Fix sysdate class cast exception

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManager.java
Fixes #26726.
- fix missing clearup savepoints when commits or rollbacks.
---
=> fix: missing clearup savepoints when commits or rollbacks.

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/StoreProcedure.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/Symbol.g4, test/it/parser/src/main/resources/sql/supported/ddl/create-procedure.xml
=> Correct Oracle parser assignment operator

test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/ExternalSQLParserIT.java, test/it/parser/src/main/resources/junit-platform.properties
https://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-parallel-execution
=> Enable parallel execution to speed up ExternalSQLParserIT

infra/context/src/main/java/org/apache/shardingsphere/infra/connection/refresher/type/table/DropTableStatementSchemaRefresher.java, infra/context/src/main/java/org/apache/shardingsphere/infra/connection/refresher/util/TableRefreshUtils.java
=> Update single table judgment in DropTableStatementSchemaRefresher

docs/community/content/involved/release/shardingsphere.cn.md, docs/community/content/involved/release/shardingsphere.en.md
- Update the step which requires help of PMC in release document
---
=> Update the step which requires help of PMC in release document

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractPipelineJob.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractSimplePipelineJob.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/job/CDCJob.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java
- Improve cleaning on pipeline job stopping
---
=> Improve cleaning on pipeline job stopping

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptMergedResult.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYkyBPWPQJB0Vve5rrnM
=> Fix sonar issue on EncryptMergedResult

mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
Fixes https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYks3SS3r-c7m0oXUTz7
=> Fix sonar issue on ContextManager

infra/common/src/main/java/org/apache/shardingsphere/infra/instance/mode/ModeContextManager.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/version/MetaDataVersionBasedPersistService.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/version/MetaDataVersionPersistService.java, mode/core/src/main/java/org/apache/shardingsphere/mode/subsciber/RuleItemChangedSubscriber.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterModeContextManager.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/NewConfigurationChangedSubscriber.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/NewResourceMetaDataChangedSubscriber.java
=> Switch active version when execute Create/Drop table

infra/util/src/main/java/org/apache/shardingsphere/infra/util/spi/type/typed/TypedSPILoader.java, kernel/data-pipeline/dialect/h2/pom.xml
=> Refactor TypedSPILoader

kernel/data-pipeline/dialect/h2/pom.xml
- Upgrade ShardingSphere dependency to 5.4.1-SNAPSHOT
---
=> Upgrade ShardingSphere dependency to 5.4.1-SNAPSHOT

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/provider/ShardingConvertRuleConfigurationProvider.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/ral/constant/DistSQLScriptConstants.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/ral/query/ConvertRuleConfigurationProvider.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationExecutor.java, proxy/backend/core/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.ConvertRuleConfigurationProvider
For #26732, convert ShardingRuleConfiguration to DistSQL via SPI.
---
=> Convert ShardingRuleConfiguration to DistSQL via SPI

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/nodepath/RuleNodePathTest.java
Fixes #26599.
Changes proposed in this pull request: Add test cases for RuleNodePath
-
---
=> Add test cases for RuleNodePath

.github/workflows/e2e-showprocesslist.yml, .github/workflows/e2e-transaction.yml, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/MySQLContainer.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/engine/base/TransactionBaseE2EIT.java
Fixes #26910.
- unique the mysql image in E2E test
---
=> Refactor : unique the mysql image in E2E test (#26910)

.github/workflows/nightly-check.yml
- add more parameters for stale action
---
=> Update : add more parameters for stale action

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
Ref #25535.
- Enhanced hex function for mysql
- Add test sql
---
=> Enhanced HEX function for mysql

.github/workflows/ci.yml, .github/workflows/e2e-agent.yml, .github/workflows/e2e-showprocesslist.yml, test/e2e/operation/showprocesslist/src/test/java/org/apache/shardingsphere/test/e2e/showprocesslist/env/ShowProcessListEnvironment.java
for #26935.
- refactor the steps by code of conduct 
---
=> Refactor : refactor the ci by code of conduct (#26935)

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/ExpressionConverter.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/ExtractArgExpressionConverter.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/TypeCastExpressionConverter.java, parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/ExtractArgExpression.java, test/it/optimizer/src/test/resources/converter/select-special-function.xml, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedExpression.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedExtractArgExpression.java, test/it/parser/src/main/resources/case/dml/select-special-function.xml
Fixes #26871 
- Finish task1: select_extract_function
- dbtype: openGauss, postgresql
---
=> Enhance SQLNodeConverterEngine to support 'select_extract_function'

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/ExtractArgExpressionConverter.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/TypeCastExpressionConverter.java, parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedExtractArgExpression.java
Ref #26901.
- Revise pr #26901
---
=> Revise pr #26901

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/dumper/ColumnValueReaderEngine.java, kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLColumnValueReader.java, kernel/data-pipeline/dialect/mysql/src/main/resources/META-INF/services/org.apache.shardingsphere.data.pipeline.spi.ingest.dumper.DialectColumnValueReader, kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/OpenGaussColumnValueReader.java, kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLColumnValueReader.java, test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/dump/ColumnValueReaderEngineTest.java
- Call `resultSet.wasNull()` after read value.
- There still need MySQLColumnValueReader
---
=> Revise #26930

docs/community/content/involved/release/shardingsphere-on-cloud.cn.md, docs/community/content/involved/release/shardingsphere-on-cloud.en.md
- Update ShardingSphere on cloud releases link. Fix typo
---
=> Update ShardingSphere on cloud releases link

docs/community/content/involved/conduct/code.cn.md, docs/community/content/involved/conduct/code.en.md
- update the code of conduct doc
---
=> Document : update the code of conduct doc

.github/workflows/schedule-check.yml
- add schedule check  for sonar
---
=> Add : add schedule check  for sonar

.github/workflows/e2e-sql.yml, .github/workflows/nightly-build-artifact.yml, .github/workflows/nightly-build-example.yml, .github/workflows/nightly-check.yml, .github/workflows/nightly-ci.yml, .github/workflows/nightly-e2e.yml, .github/workflows/nightly-sql-parser.yml
- refactor the naming of workflows by code of conduct
---
=> Refactor : refactor the naming of workflows by code of conduct

.github/workflows/schedule-check.yml
=> Fix : fix a spelling error

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/broadcast.cn.md
- update the code of rules doc
---
=> Document : update the code of rules doc

test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/definition/CreateTableOptionDefinitionAssert.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYlQ5yOWhHFT_BabsjLm
=> Fix sonar issue on CreateTableOptionDefinitionAssert

.github/workflows/required-check.yml
=> Remove temporary step check-checkstyle

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDMLStatementVisitor.java, parser/sql/engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/dml/MySQLImportStatement.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/dml/ImportStatementTestCase.java, test/it/parser/src/main/resources/case/dml/import.xml, test/it/parser/src/main/resources/sql/supported/dml/import.xml
Ref #25535.
- Support import statement for mysql
- Add test sql
---
=> Support import statement for mysql

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, parser/sql/engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleDropClusterStatement.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ddl/DropClusterStatementTestCase.java, test/it/parser/src/main/resources/case/ddl/drop-cluster.xml, test/it/parser/src/main/resources/sql/supported/ddl/drop-cluster.xml
Ref #27133.
- support drop cluster.
---
=> Support Oracle drop cluster statement.

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleDropFunctionStatement.java, test/it/parser/src/main/resources/case/ddl/drop-function.xml, test/it/parser/src/main/resources/sql/supported/ddl/drop-function.xml
Ref #27134.
- support drop function in oracle SQL.
---
=> Support Oracle drop function statement.

.github/workflows/e2e-agent.yml, .github/workflows/e2e-operation.yml, .github/workflows/e2e-sql.yml, .github/workflows/nightly-build-example.yml, .github/workflows/nightly-e2e.yml, .github/workflows/nightly-sql-parser.yml
- refactor the matrix max parallel to 20
---
=> Refactor the matrix max parallel to 20

.github/workflows/nightly-e2e-operation.yml
for #26910.
- add nightly e2e operation
---
=> Add : add nightly e2e operation (#26910)

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-database.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-database.xml
Fixes #26941 #26942 #26943.
- Enhanced Oracle alter database RECOVER syntax
- Add test sql
---
=> Enhanced Oracle alter database RECOVER syntax

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-database.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-database.xml
Fixes #26944 #26945.
- Change Oracle supplementalIdKeyClause syntax
- Add test sql
---
=> Change Oracle supplementalIdKeyClause syntax

features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/provider/EncryptConvertRuleConfigurationProvider.java, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/provider/ReadwriteSplittingConvertRuleConfigurationProvider.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/provider/ShardingConvertRuleConfigurationProvider.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationExecutor.java, proxy/backend/core/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.ConvertRuleConfigurationProvider
For #26732, convert EncryptRuleConfiguration to DistSQL via SPI.
---
=> Convert EncryptRuleConfiguration to DistSQL via SPI

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/planner/rule/transformation/PushFilterIntoScanRule.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/planner/rule/transformation/PushProjectIntoScanRule.java
- Fix wrong result when query system table with projection and predicate
---
=> Fix wrong result when query system table with projection and predicate

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/UnregisterStorageUnitBackendHandler.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/storage/unit/ShowStorageUnitExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/StorageUnitUtils.java
Remove usage of `com.google.common.collect.Multimap`
=> Remove multimap from StorageUnitDefinitionBackendHandler

features/encrypt/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.ConvertRuleConfigurationProvider, features/readwrite-splitting/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.ConvertRuleConfigurationProvider, features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.ConvertRuleConfigurationProvider, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationExecutor.java
For #26732
Simplify ConvertYamlConfigurationExecutor via SPI
=> Simplify ConvertYamlConfigurationExecutor via SPI

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, parser/sql/engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleDropTableSpaceStatement.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ddl/DropTableSpaceStatementTestCase.java, test/it/parser/src/main/resources/case/ddl/drop-tablespace.xml, test/it/parser/src/main/resources/sql/supported/ddl/drop-tablespace.xml
Ref #27137.
- Support Oracle drop tablespace statement.
---
=> Support Oracle drop tablespace statement.

docs/document/content/dev-manual/data-source.cn.md, docs/document/content/dev-manual/data-source.en.md
- fix the deadlink checked by nightly-check workflow
---
=> Fix : fix the deadlink checked by nightly-check workflow

kernel/data-pipeline/core/pom.xml, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/sqlbuilder/PipelineImportSQLBuilder.java
Related to #27251.
- Improve PR 27251
---
=> Improve PR 27251

parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, parser/sql/engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleSystemActionStatement.java, test/it/parser/src/main/resources/case/ddl/drop-database.xml, test/it/parser/src/main/resources/sql/supported/ddl/drop-database.xml
Fixes #27134.
- add tests for drop database.
---
=> Add tests for drop database.

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYlXccqv_NKBn8zVgEvZ
---
=> Fix sonar issue in MySQLStatementVisitor

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/_index.en.md
- Add apollo shardingsphere driver url configuration document
---
=> Add apollo shardingsphere driver url configuration document

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/Projection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngine.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationDistinctProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/ColumnProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/DerivedProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/ExpressionProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/ParameterMarkerProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/ShorthandProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/SubqueryProjection.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngineTest.java, proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutorTest.java, test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-sub-query.xml, test/e2e/sql/src/test/resources/cases/dql/dql-integration-select.xml, test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-subquery.xml, test/it/rewriter/src/test/resources/scenario/sharding/case/dml/select.xml
Ref #27287.
- Remove useless transformSubqueryProjection in Projection
---
=> Remove useless transformSubqueryProjection in Projection

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/classbased/ClassBasedShardingAlgorithm.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/datetime/IntervalShardingAlgorithm.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/ComplexInlineShardingAlgorithm.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/InlineShardingAlgorithm.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/classbased/ClassBasedShardingAlgorithmTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/ComplexInlineShardingAlgorithmTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/InlineShardingAlgorithmTest.java
Fixes #24756.
- Improve properties verification of ShardingAlgorithm
---
=> Improve properties verification of ShardingAlgorithm

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/context/EncryptSQLRewriteContextDecorator.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/context/ShardingSQLRewriteContextDecorator.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/context/ShardingSQLRewriteContextDecoratorTest.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/SQLRewriteEntry.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/context/SQLRewriteContext.java, infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/context/SQLRewriteContextTest.java, infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/engine/GenericSQLRewriteEngineTest.java, infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/engine/RouteSQLRewriteEngineTest.java
- Refactor SQLRewriteContext global filed for obtain more database metadata
---
=> Refactor SQLRewriteContext global filed for obtain more database metadata

.gitignore, .mvn/extensions.xml
=> Add : add maven profiler

features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/provider/EncryptConvertRuleConfigurationProvider.java, features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/provider/MaskConvertRuleConfigurationProvider.java, features/mask/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.ConvertRuleConfigurationProvider, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/provider/ReadwriteSplittingConvertRuleConfigurationProvider.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationExecutor.java
For #26732, convert MaskRuleConfiguration to DistSQL via SPI.
---
=> Convert MaskRuleConfiguration to DistSQL via SPI

.github/workflows/e2e-sql.yml
- refactor all e2e-sql job to matrix
---
=> Refactor : refactor all e2e-sql job to matrix

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/create-tablespace.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-tablespace.xml
Ref #27113.
- Add rules for create tablespace.
---
=> Add rules for create tablespace.

kernel/single/core/src/main/java/org/apache/shardingsphere/single/decider/SingleSQLFederationDecider.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/route/SingleSQLRouter.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/route/engine/SingleRouteEngineFactory.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/route/engine/SingleStandardRouteEngine.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/rule/SingleRule.java, kernel/single/core/src/test/java/org/apache/shardingsphere/single/decider/SingleSQLFederationDeciderTest.java, kernel/single/core/src/test/java/org/apache/shardingsphere/single/route/engine/SingleRouteEngineFactoryTest.java, kernel/single/core/src/test/java/org/apache/shardingsphere/single/rule/SingleRuleTest.java, kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/query/ShowUnloadedSingleTableExecutor.java
- refactor SingleSQLRouter code style and logic for schema rewrite
---
=> Refactor SingleSQLRouter code style and logic for schema rewrite

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
- Support oracle LEAD and LAG function parsing
Refer to : https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/LEAD.html#GUID-0A0481F1-E98F-4535-A739-FCCA8D1B5B77
---
=> Support oracle LEAD and LAG function parsing

kernel/single/core/src/main/java/org/apache/shardingsphere/single/rule/SingleRule.java, kernel/single/core/src/test/java/org/apache/shardingsphere/single/decider/SingleSQLFederationDeciderTest.java, test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/SQLRewriterIT.java
- Refactor SingleRule and SQLRewriterIT code style
---
=> Refactor SingleRule and SQLRewriterIT code style

kernel/single/core/src/main/java/org/apache/shardingsphere/single/route/engine/SingleStandardRouteEngine.java
- Refactor SingleStandardRouteEngine code style
---
=> Refactor SingleStandardRouteEngine code style

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/parser/src/main/resources/case/dml/select-sub-query.xml, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml, test/it/parser/src/main/resources/sql/supported/dml/select-sub-query.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #25535.
- Enhance select query statements
- Fix position function parse ClassCastException
- Support LATERAL query parse
- Add test sql
---
=> Enhance select query statements

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/create-tablespace.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-tablespace.xml
Ref #27116.
- Add rules for create tablespace.
---
=> feat: add rules for create tablespace.

agent/plugins/metrics/core/src/test/resources/config/driver/foo-driver-fixture.yaml, jdbc/core/src/test/resources/config/driver/foo-driver-fixture.yaml, jdbc/core/src/test/resources/config/factory/config-for-factory-test.yaml, proxy/backend/core/src/test/resources/conf/convert/config-sharding-auto-tables.yaml, proxy/backend/core/src/test/resources/conf/import/config-duplicated-logic-table.yaml, test/e2e/agent/jdbc-project/src/main/resources/config.yaml
Fixes #27330.
- Optimize algorithm name in yaml
---
=> Optimize algorithm name in yaml

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/executor/variable/session/SessionVariableRecordExecutor.java, proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/MySQLSetVariableAdminExecutor.java, proxy/backend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/executor/PostgreSQLResetVariableAdminExecutor.java, proxy/backend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/executor/PostgreSQLSetVariableAdminExecutor.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/column/ColumnWithJoinOperatorAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYl7B6mqekkzf3wiC2rc
=> Fix sonar issue on ColumnWithJoinOperatorAssert

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleAlterTypeStatement.java, test/it/parser/src/main/resources/case/ddl/alter-type.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-type.xml
Ref #27004.
- Add alter type SQL.
---
=> Add alter type SQL.

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DCLStatement.g4, test/it/parser/src/main/resources/case/dcl/drop-role.xml, test/it/parser/src/main/resources/sql/supported/dcl/drop-role.xml
Ref #27133.
- Refactor drop role statement.
---
=> Refactor drop role statement.

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DALStatement.g4
- fix import in Oracle dal g4
---
=> fix import in Oracle dal g4

.github/workflows/ci.yml, .github/workflows/nightly-ci.yml, .github/workflows/required-check.yml, distribution/agent/pom.xml, distribution/jdbc/pom.xml, distribution/proxy/pom.xml, distribution/src/pom.xml, docs/community/content/team/_index.cn.md, docs/community/content/team/_index.en.md, pom.xml
- Refactor mvn install to mvn test
---
=> Refactor mvn install to mvn test

.github/workflows/e2e-sql.yml, .github/workflows/required-check.yml
- Refactor e2e sql and required check
---
=> Refactor e2e sql

.asf.yaml
=> Refactor required check

.github/workflows/required-check.yml
- remove the duplicated required check
---
=> Refactor : remove the duplicated required check

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueCompareOperatorGenerator.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/ConditionValueGeneratorFactoryTest.java
Fixes #27411.
- Condition value support is null
---
=> Condition value support is null

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
- Support oracle NTILE,PERCENTILE_CONT,PERCENTILE_DISC functions parsing
Refer to: 
[oracle ntile function](https://docs.oracle.com/cd/B13789_01/server.101/b10759/functions091.htm)
[oracle PERCENTILE_CONT function](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/PERCENTILE_CONT.html#GUID-CA259452-A565-41B3-A4F4-DD74B66CEDE0)
[oracle PERCENTILE_DISC function](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/PERCENTILE_DISC.html)
---
=> Support oracle NTILE,PERCENTILE_CONT,PERCENTILE_DISC functions parsing

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptMergedResult.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/aware/DatabaseTypeAware.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/EncryptParameterRewriterBuilder.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptCreateTableTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptIndexColumnTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptOrderByItemTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptPredicateColumnTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertCipherNameTokenGenerator.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGeneratorTest.java, features/mask/core/src/test/java/org/apache/shardingsphere/mask/merge/dql/MaskAlgorithmMetaDataTest.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngine.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/ColumnProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/util/ProjectionUtils.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/pagination/engine/RowNumberPaginationContextEngineTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/ProjectionsContextTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/engine/ProjectionEngineTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationProjectionTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/table/TablesContextTest.java, infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/SubstitutableColumnNameTokenTest.java, jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSetUtilsTest.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSetMetaData.java, kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSetTest.java
Ref #27287.
- Modify getColumnName and getColumnLabel logic for ColumnProjection
---
=> Modify getColumnName and getColumnLabel logic for ColumnProjection

docs/document/content/dev-manual/data-source.cn.md, docs/document/content/dev-manual/data-source.en.md
- fix the document where caused by refactor
---
=> Fix : fix the document where caused by refactor

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
- Support Oracle SQL function owner Parse
---
=> Support Oracle function owner Parse

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/ProjectionsContext.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/ColumnProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/ExpressionProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/SubqueryProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementContext.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/impl/AggregationProjectionTest.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSetMetaData.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSet.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSetMetaData.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/response/header/query/QueryHeaderBuilderEngine.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dql/BaseDQLE2EIT.java, test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-combine.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-type.xml
Ref #27287.
- refactor proxy and jdbc getColumnName, getColumnLabel call logic
- add e2e test for column label and column name
---
=> Refactor proxy and jdbc getColumnName, getColumnLabel call logic and add e2e test

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/preparer/InventoryRecordsCountCalculator.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/preparer/InventoryTaskSplitter.java
- Add insert columns copy at InventoryTaskSplitter of pipeline
---
=> Add insert columns copy at InventoryTaskSplitter of pipeline

jdbc/core/src/main/java/org/apache/shardingsphere/driver/data/pipeline/datasource/creator/ShardingSpherePipelineDataSourceCreator.java
- Remove authority rule when building data source for pipeline
---
=> Remove authority rule when building data source for pipeline

.github/workflows/required-check.yml, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/util/ProjectionUtils.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/SQLBindEngine.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/route/SingleSQLRouter.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/from/impl/SimpleTableConverter.java, src/resources/rat.txt
- fix the failed check in required check action
---
=> Fix : fix the failed check in required check action

.github/workflows/ci.yml, .github/workflows/e2e-agent.yml, .github/workflows/e2e-operation.yml, .github/workflows/e2e-sql.yml, .github/workflows/required-check.yml
- remove the master push trigger from workflows
---
=> Remove : remove the master push trigger from workflows

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/response/header/query/QueryHeaderBuilderEngine.java
- https://sonarcloud.io/project/issues?resolved=false&id=apache_shardingsphere&open=AYmMV9i4wYEKabf22x5H
---
=> Fix sonar issue in QueryHeaderBuilderEngine

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/SQLBindEngine.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/combine/CombineSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/ColumnSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/TableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/ProjectionsSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ColumnProjectionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/SQLStatementBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementBinder.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/column/ColumnSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/item/ColumnProjectionSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/table/SubqueryTableSegment.java
Ref #27287.
- add SelectStatementBinder and table segment bind logic
---
=> Add SelectStatementBinder and table segment bind logic

test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/ExternalSQLParserIT.java
=> Fixing ExternalSQLParserIT not reporting correctly.

.github/workflows/ci.yml, .github/workflows/e2e-agent.yml, .github/workflows/e2e-operation.yml, .github/workflows/e2e-sql.yml, .github/workflows/nightly-build.yml, .github/workflows/nightly-check.yml, .github/workflows/nightly-ci.yml, .github/workflows/nightly-e2e-operation.yml, .github/workflows/nightly-sql-parser.yml, .github/workflows/required-check.yml, .github/workflows/required-reusable.yml, .github/workflows/resources/variables/env-variables.properties, .github/workflows/schedule-report.yml
for #27463.
- refactor workflow variables
---
=> Refactor workflow variables

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/global-rule/show-transaction-rule.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow/drop-shadow-rule.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow/drop-shadow-rule.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow/show-default-shadow-algorithm.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow/show-default-shadow-algorithm.en.md
- Fix shadow's DistSQL document
- Fix transaction's DistSQL document
---
=> Fix DistSQL document

.github/workflows/ci.yml
- fix the command to include more tests
---
=> Fix : fix the command to include more tests

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-diskgroup.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-diskgroup.xml
Fixes #26961.
- Change Oracle attributeNameAndValue and setOwnerClause syntax
- Add test sql
---
=> Change Oracle attributeNameAndValue and setOwnerClause syntax

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/runner/InventoryIncrementalTasksRunner.java
- Extract InventoryIncrementalTasksRunner.inventoryFailureCallback
- Replace some methods from `protected` to `private`
---
=> Extract InventoryIncrementalTasksRunner.inventoryFailureCallback

.github/workflows/ci.yml, .github/workflows/e2e-agent.yml, .github/workflows/e2e-operation.yml, .github/workflows/e2e-sql.yml, .github/workflows/required-check.yml, .github/workflows/required-reusable.yml, .github/workflows/resources/variables/env-variables.properties
for #27463.
- add job runnable check
---
=> Add : add job runnable check

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/data/dialect/type/MySQLShardingStatisticsTableCollector.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/data/dialect/type/OpenGaussShardingStatisticsTableCollector.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/data/dialect/type/PostgreSQLShardingStatisticsTableCollector.java
=> Use prepared statement to replace statement.

test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-order-by.xml
Fixes #20096.
- Bugfix encryption distinct select bug
---
=> Bugfix encryption distinct select bug

.github/workflows/e2e-sql.yml, .github/workflows/nightly-ci.yml
- refactor the E2E SQL job name
---
=> Refactor : refactor the E2E SQL job name

docs/document/content/dev-manual/data-source.cn.md
=> Fix : fix the dead link

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-diskgroup.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-diskgroup.xml
Ref #26962.
- Enhance Oracle resizeDiskClause syntax
- Add test sql
---
=> Enhance Oracle resizeDiskClause syntax

infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/OracleConnectionPropertiesParser.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYmMJfTDyKY_eK4sPAdK
=> Fix sonar issue on OracleConnectionPropertiesParser

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/InsertStatementHandler.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/dml/OracleInsertStatement.java, parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/InsertStatementHandlerTest.java, test/e2e/sql/src/test/resources/cases/dml/dataset/tbl/batch_insert_into_order_with_select.xml, test/e2e/sql/src/test/resources/cases/dml/dataset/tbl/insert_into_order_table_with_select.xml, test/e2e/sql/src/test/resources/cases/dml/dml-integration-insert.xml, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/InsertStatementAssert.java, test/it/parser/src/main/resources/case/dml/insert.xml
- Fix oracle insert select
---
=> Fix oracle insert select

.github/workflows/ci.yml, .github/workflows/e2e-agent.yml, .github/workflows/e2e-operation.yml, .github/workflows/nightly-build.yml, .github/workflows/nightly-e2e-operation.yml, .github/workflows/nightly-sql-parser.yml, .github/workflows/required-check.yml, .github/workflows/required-reusable.yml, .github/workflows/resources/variables/env-variables.properties
- refactor the runs on of workflow
---
=> Refactor : refactor the runs on of workflow

docs/document/content/dev-manual/data-source.cn.md
=> Fix : fix the deadlink

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/ColumnSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/TableSegmentBinderContext.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ShorthandProjectionSegmentBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinderTest.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/column/ColumnSegment.java
Ref #27287.
- Add unit test for SimpleTableSegmentBinder
---
=> Add unit test for SimpleTableSegmentBinder

.github/workflows/e2e-operation.yml, .github/workflows/nightly-build.yml, .github/workflows/nightly-check.yml, .github/workflows/nightly-e2e-operation.yml, .github/workflows/nightly-sql-parser.yml, .github/workflows/required-reusable.yml, .github/workflows/schedule-report.yml, .gitignore
- refactor workflow content
---
=> Refactor : refactor workflow content

docs/document/content/dev-manual/data-source.cn.md, docs/document/content/dev-manual/data-source.en.md
=> Refactor : fix deadlink

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
- Support Oracle Feature Functions
ref: https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/FEATURE_COMPARE.html#GUID-3D4E179F-F5D2-4FCF-AB42-4D0C8CC7D514
https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/FEATURE_DETAILS.html#GUID-A42F313B-22C1-4CAC-BA3F-C418178D743F
https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/FEATURE_ID.html#GUID-BA187F80-5F51-49F6-BB69-64422FB9FD90
https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/FEATURE_SET.html#GUID-55582346-F1D6-447E-851A-D4912982EB28
https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/FEATURE_VALUE.html#GUID-EC0E44D0-BE01-49F8-9E5A-72B500119877
---
Before committing this PR, I'm sure that I have checked the following …
=> Support Oracle Feature Functions

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/ProjectionsSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ShorthandProjectionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ShorthandProjectionSegmentBinderTest.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/item/ColumnProjectionSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/item/ProjectionSegment.java, test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/scenario/EncryptSQLRewriterIT.java, test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/scenario/MixSQLRewriterIT.java, test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/scenario/ShardingSQLRewriterIT.java, test/it/rewriter/src/test/resources/scenario/mix/case/query-with-cipher/dml/select/select-projection.xml
Ref #27287.
- filter invisible column in shorthand expand
- add more unit test for JoinTableSegmentBinder, SubqueryTableSegmentBinder and ShorthandProjectionSegmentBinder
---
=> Filter invisible column in shorthand expand and add more unit test

.github/workflows/ci.yml, .github/workflows/e2e-agent.yml, .github/workflows/e2e-operation.yml, .github/workflows/e2e-sql.yml, .github/workflows/nightly-build.yml, .github/workflows/nightly-check.yml, .github/workflows/nightly-ci.yml, .github/workflows/nightly-e2e-operation.yml, .github/workflows/nightly-sql-parser.yml, .github/workflows/required-check.yml, .github/workflows/required-reusable.yml, .github/workflows/schedule-report.yml
- refacotor the reusable related workflow job name
---
=> Refactor : refacotor the reusable related workflow job name

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java, test/it/parser/src/main/resources/sql/supported/dml/insert.xml
=> Fix parsing Oracle INSERT with multiple values

.github/workflows/ci.yml, .github/workflows/e2e-agent.yml, .github/workflows/e2e-operation.yml, .github/workflows/e2e-sql.yml, .github/workflows/nightly-build.yml, .github/workflows/nightly-check.yml, .github/workflows/nightly-ci.yml, .github/workflows/nightly-e2e-operation.yml, .github/workflows/nightly-sql-parser.yml, .github/workflows/required-check.yml, .github/workflows/required-reusable.yml, .github/workflows/resources/variables/env-variables.properties, .github/workflows/schedule-report.yml
- Refactor some output name in workflows
---
=> Refactor some output name in workflows

docs/document/content/dev-manual/data-source.cn.md, docs/document/content/dev-manual/data-source.en.md
=> Fix : fix deadlink

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-index.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-index.xml
Ref #26964.
- Format g4 file
- Support Oracle alter index PARAMETERS parse
- Add test sql
---
=> Support Oracle alter index PARAMETERS parse

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java, test/it/parser/src/main/resources/sql/supported/dml/insert.xml
Reverts apache/shardingsphere#27534
=> Revert "Fix parsing Oracle INSERT with multiple values"

.github/workflows/e2e-agent.yml, .github/workflows/e2e-operation.yml, .github/workflows/e2e-sql.yml, .github/workflows/nightly-build.yml, .github/workflows/nightly-check.yml, .github/workflows/nightly-e2e-operation.yml, .github/workflows/nightly-sql-parser.yml, .github/workflows/required-reusable.yml, .github/workflows/resources/variables/env-variables.properties, .github/workflows/schedule-report.yml
=> Refactor : change the cache prefix

test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/env/PipelineE2EEnvironment.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/container/compose/DockerContainerComposer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/container/compose/NativeContainerComposer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/util/DockerImageVersion.java
- Add more database type support
- Remove duplicate code.
---
=> Improve the code in the pipeline E2E

.github/workflows/e2e-operation.yml, .github/workflows/required-reusable.yml, .github/workflows/resources/variables/env-variables.properties
- reusable workflow to make label control workflow possible
---
=> Refactor reusable workflow

.github/workflows/e2e-sql.yml
- refactor the retention from 1 to 10
---
=> Refactor : refactor the retention from 1 to 10

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4, test/it/parser/src/main/resources/case/ddl/alter-flashback-archive.xml, test/it/parser/src/main/resources/case/ddl/alter-index.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-flashback-archive.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-index.xml
Fixes #26964 #26963.
- Improve Oracle alter index syntax
- Add test sql
---
=> Improve Oracle alter index syntax

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/case/dml/select.xml
- Extract expressions from special functions
---
=> Extract expressions from special functions

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/ProjectionsSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementBinder.java
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYmcBAcXUdhK_fzPr5gt
---
=> Fix sonar issue in ProjectionsSegmentBinder class

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4, test/it/parser/src/main/resources/case/dml/update.xml, test/it/parser/src/main/resources/sql/supported/dml/update.xml
Fixes #27170.
Changes proposed in this pull request: Support parsing Oracle UPDATE queries
-
---
=> Support parsing Oracle UPDATE queries

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/case/dml/select.xml
- Extract expressions from analytic functions
---
=> Extract expressions from analytic functions

infra/exception/core/src/main/java/org/apache/shardingsphere/infra/exception/core/external/sql/type/kernel/category/AuditSQLException.java
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYmmjP87l16czXS1qXHQ
=> Fix sonar issue on AuditSQLException

parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/type/OpenGaussDDLStatementVisitor.java, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/type/PostgreSQLDDLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/create-index.xml
- Extract columns from create index
Refer to:
---
=> Extract columns from create index

features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/update/DropBroadcastTableRuleStatementUpdater.java, features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropEncryptRuleStatementUpdater.java, features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/update/DropMaskRuleStatementUpdater.java, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/DropReadwriteSplittingRuleStatementUpdater.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropDefaultShadowAlgorithmStatementUpdater.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropShadowRuleStatementUpdater.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropDefaultShardingStrategyStatementUpdater.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleStatementUpdater.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/ExportUtils.java
- Refactor check DatabaseRule is empty
---
=> Refactor check DatabaseRule is empty

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-index.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-index.xml
Fixes #26966 #26967.
- Enhance Oracle alter index syntax
- Add test sql
---
=> Enhance Oracle alter index syntax

examples/shardingsphere-parser-example/src/main/java/org/apache/shardingsphere/example/parser/oracle/statement/OracleParserStatementExample.java, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml
In this pr, I added CHR in the definition of charFunction.
You can find more details in this official doc: https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/CHR.html#GUID-35FEE007-D49C-4562-A904-041186AC8928
=> [Oracle SQL] Support HR-5-19 of Oracle SQL

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ColumnProjectionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ShorthandProjectionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/SelectStatementBinderTest.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/item/ShorthandProjectionSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/table/SimpleTableSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/SelectStatementHandler.java
Ref #27287.
- create new bounded sql statement and segment to avoid affecting SQLStatement cache
---
=> Create new bounded sql statement and segment to avoid affecting SQLStatement cache

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinder.java
- Fix og query pg_settings table NPE
---
=> Fix og query pg_settings table NPE

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-database.xml, test/it/parser/src/main/resources/case/ddl/alter-diskgroup.xml, test/it/parser/src/main/resources/case/ddl/alter-java.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-database.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-diskgroup.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-java.xml
Fixes #26969.
- Enhance Alter Java syntax and add other SQL test statements
- Add alter java test sql
- Add alter database test sql
- Add alter diskgroup test sql
---
=> Enhance Alter Java syntax and add other SQL test statements

parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/SelectStatementHandler.java
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=apache_shardingsphere&open=AYmwLpxrj1-xV5SWbquB
=> Fix sonar issue on SelectStatementHandler

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/from/impl/DeleteMultiTableConverter.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/statement/delete/DeleteStatementConverter.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/statement/select/SelectStatementConverter.java
=> Revise pr#27599

mode/core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java
=> Fix ServiceProviderNotFoundException exception when run ContextManagerTest unit test

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodeInfoExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowTableMetaDataExecutor.java, proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLAdminExecutorCreator.java
Fix sonar issue: https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYmGjOBcUgeQcdzwegdN
=> Refactor MySQLAdminExecutorCreator to reduce its cognitive complexity

infra/session/src/main/java/org/apache/shardingsphere/infra/session/query/QueryContext.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/DriverJDBCExecutor.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java
- Support jdbc adapter to get databaseName from sql
---
=> Support jdbc adapter to get databaseName from sql

kernel/data-pipeline/scenario/cdc/client/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/client/CDCClient.java, kernel/data-pipeline/scenario/cdc/client/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/client/handler/CDCRequestHandler.java, kernel/data-pipeline/scenario/cdc/client/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/client/util/ResponseFuture.java, kernel/data-pipeline/scenario/cdc/client/src/test/java/org/apache/shardingsphere/data/pipeline/cdc/client/example/Bootstrap.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/generator/CDCResponseUtils.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
Relate #22500 
- Add connect method of channel for CDC client
---
=> Add connect method of channel for CDC client

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4, parser/sql/dialect/postgresql/src/main/antlr4/imports/postgresql/BaseRule.g4, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
=> Fix BYTEA type cast (#27593)

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/enums/AggregationType.java, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
- Support Oracle collect function sql parse
ref: https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/COLLECT.html#GUID-A0A74602-2A97-449B-A3EC-847D38D3DA90
---
=> Support Oracle collect function sql parse

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java, test/it/parser/src/main/resources/sql/supported/dml/select-join.xml
- Support oracle natural join visit and add parser test case
---
=> Support oracle natural join visit and add parser test case

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/Symbol.g4, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
- Support Oracle Arrow Symbol parse
---
=> Support Oracle Arrow Symbol parse

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
Ref #27021.
- fix create cluster oracle in antlr bugs.
---
=> fix: fix oracle antlr bugs.

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleAlterTablespaceStatement.java
Ref #27874.
- Revise pr 27874 for code style
---
=> Revise pr 27874 for code style

test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema-mysql.xml, test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema-opengauss.xml, test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema-postgresql.xml
- Move system tables e2e to tbl
---
=> Move system tables e2e to tbl

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/PLSQL.g4, parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4
Procedure and function have same body.
https://docs.oracle.com/cd/E11882_01/appdev.112/e25519/function.htm#LNPLS01322
https://docs.oracle.com/cd/E11882_01/appdev.112/e25519/procedure.htm#LNPLS01336
=> Rename Oracle StoreProcedure to PL/SQL and move function to PL/SQL

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/PLSQL.g4
https://docs.oracle.com/cd/E11882_01/appdev.112/e25519/block.htm#CJADJGJE
https://docs.oracle.com/cd/E11882_01/appdev.112/e25519/autotransaction_pragma.htm#LNPLS01302
=> Support Oracle autonomous_trans_pragma

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/engine/ProjectionEngine.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/ExpressionProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/SubqueryProjection.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/util/ProjectionUtils.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/ProjectionsContextTest.java, infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/SubstitutableColumnNameTokenTest.java
Ref #27287.
- Enhance ExpressionProjection and SubqueryProjection getColumnName and getColumnLabel logic
---
=> Enhance ExpressionProjection and SubqueryProjection getColumnName and getColumnLabel logic

test/it/parser/src/main/resources/case/dml/select.xml
- Add oracle parsing column assertion
---
=> Add oracle parsing column assertion

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/ExportUtils.java
Optimize export when rules is empty.
---
=> EXPORT DATABASE CONFIGURATION optimization

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/SubqueryProjection.java
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=apache_shardingsphere&open=AYnAEjvK5X6axl7480hd
---
=> Remove useless logic for sonar check

test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema-mysql.xml, test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema-opengauss.xml
=> Remove failed system table query e2e

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
- Fix oracle antlr bugs in DDLStatement.
---
=> Fix oracle antlr bugs in DDLStatement.

features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/BaseRule.g4, features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/RDLStatement.g4, features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/RQLStatement.g4, features/encrypt/distsql/parser/src/main/java/org/apache/shardingsphere/encrypt/distsql/parser/core/EncryptDistSQLStatementVisitor.java
Split `buildInEncryptAlgorithmType` to `standardEncryptAlgorithm`, `assistedEncryptAlgorithm` and `likeEncryptAlgorithm`
=> Optimize encrypt g4 definition

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
- Enhance parse oracle SQL efficiency.
---
=> Enhance parse oracle efficiency

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
Fixes #26976.
- Add oracle alter table supplementalTableLogging rule
- Add test sql
- https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-TABLE.html#GUID-552E7373-BF93-477D-9DA3-B2C9386F2877__CJAGFCDI
---
=> Add oracle alter table supplementalTableLogging rule

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-system.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-system.xml
Ref #26976.
- Change oracle alterSystemSetClause syntax
- Add test sql
---
=> Change oracle alterSystemSetClause syntax

test/util/src/main/java/org/apache/shardingsphere/test/env/env/TestUtilEnvironment.java, test/util/src/main/java/org/apache/shardingsphere/test/loader/strategy/impl/GitHubTestParameterLoadStrategy.java, test/util/src/main/resources/env/test-util-env.properties
=> GitHubTestParameterLoadStrategy support GitHub token.

test/e2e/sql/src/test/resources/cases/rql/dataset/encrypt/count_single_table.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/encrypt/show_single_tables.xml, test/e2e/sql/src/test/resources/env/scenario/encrypt/data/actual/init-sql/mysql/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/encrypt/data/expected/init-sql/mysql/01-expected-init.sql
- Fix e2e error in master branch
---
=> Fix e2e error in master branch

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/enums/AggregationType.java, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/case/dml/update.xml
- Add oracle column parsing assertions
---
=> Add oracle column parsing assertions

infra/datasource/type/c3p0/src/test/java/org/apache/shardingsphere/infra/datasource/c3p0/creator/C3P0DataSourcePoolCreatorTest.java, infra/datasource/type/druid/src/test/java/org/apache/shardingsphere/infra/datasource/druid/creator/DruidDataSourcePoolCreatorTest.java
=> Revise #27991

mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/NewStandaloneContextManagerBuilder.java, mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/NewStandaloneModeContextManager.java, mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneContextManagerBuilder.java, mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneModeContextManager.java, mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/yaml/NewStandaloneYamlPersistRepositoryConfigurationSwapper.java, mode/type/standalone/core/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.yaml.config.swapper.mode.YamlPersistRepositoryConfigurationSwapper, mode/type/standalone/core/src/main/resources/META-INF/services/org.apache.shardingsphere.mode.manager.ContextManagerBuilder, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/RALBackendHandlerFactory.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/RDLBackendHandlerFactory.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/rule/NewRuleDefinitionBackendHandler.java
=> New metadata structure for Standalone mode

infra/context/src/main/java/org/apache/shardingsphere/infra/connection/refresher/util/TableRefreshUtils.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYne-PvsTTCOyeVz1dpG
=> Fix sonar issue on TableRefreshUtils

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ddl/impl/AnalyzeStatementAssert.java, test/it/parser/src/main/resources/case/ddl/analyze.xml, test/it/parser/src/main/resources/sql/supported/ddl/analyze.xml
Ref #27007.
- Improve Oracle analyze syntax
- Change test check
---
=> Improve Oracle analyze syntax

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DCLStatement.g4, test/it/parser/src/main/resources/case/dcl/alter-user.xml, test/it/parser/src/main/resources/case/dcl/grant.xml, test/it/parser/src/main/resources/sql/supported/dcl/alter-user.xml, test/it/parser/src/main/resources/sql/supported/dcl/grant-user.xml
Fixes #27149.
Changes proposed in this pull request: Support parsing Oracle GRANT CREATE sql 
-
---
- [X ] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [ X] I have self-reviewed the commit code.
- [ X] I have (or in comment I request) added corresponding labels for the pull request.
- [ X] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ X] I have made corresponding changes to the documentation.
- [ X] I have added corresponding unit tests for my changes.
=> Support parsing Oracle GRANT CREATE sql

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
Fixes #26979.
- Improve oracle alter table syntax
- Add test sql
---
=> Improve oracle alter table syntax

test/it/optimizer/src/test/resources/converter/delete.xml
=> Delete test case addition

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/DataConsistencyCheckUtils.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/result/RecordSingleTableInventoryCalculatedResult.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/result/TableDataConsistencyCheckResult.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/result/TableDataConsistencyCountCheckResult.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/result/yaml/YamlTableDataConsistencyCheckResult.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/result/yaml/YamlTableDataConsistencyCheckResultSwapper.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/MatchingTableDataConsistencyChecker.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/RecordSingleTableInventoryCalculator.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/ConsistencyCheckDataBuilder.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/result/RecordSingleTableInventoryCalculatedResultTest.java, kernel/data-pipeline/dialect/h2/src/main/java/org/apache/shardingsphere/data/pipeline/h2/sqlbuilder/H2PipelineSQLBuilder.java, kernel/data-pipeline/dialect/h2/src/main/resources/META-INF/services/org.apache.shardingsphere.data.pipeline.spi.sqlbuilder.DialectPipelineSQLBuilder, test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/consistencycheck/table/calculator/RecordSingleTableInventoryCalculatorTest.java
- Review and refactor data consistency check
---
=> Review and refactor data consistency check

infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLMetaDataLoader.java, infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLMetaDataLoaderTest.java
For #28035 .
- support save unique key in metadata for postgres
---
=> support save unique key in metadata for postgres

infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/data/loader/OracleMetaDataLoader.java, infra/database/type/oracle/src/test/java/org/apache/shardingsphere/infra/database/oracle/metadata/data/loader/OracleMetaDataLoaderTest.java
For #28035 .
- support save unique key in metadata for oracle
---
=> support save unique key in metadata for Oracle

docs/document/content/faq/_index.cn.md, docs/document/content/faq/_index.en.md
=> Add Standalone 、Compatible_Standalone faq document.

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/generator/SQLTokenGenerators.java
use collection to replace useless map.
-
---
=> refactor SQLTokenGenerators

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/resource/storage/StorageUnit.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/impl/CDCJobAPI.java, kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java, mode/core/src/main/java/org/apache/shardingsphere/mode/manager/context/ConfigurationContextManager.java, mode/core/src/main/java/org/apache/shardingsphere/mode/manager/switcher/NewResourceSwitchManager.java, mode/core/src/main/java/org/apache/shardingsphere/mode/manager/switcher/ResourceSwitchManager.java, mode/core/src/main/java/org/apache/shardingsphere/mode/manager/switcher/SwitchingResource.java, mode/core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java, mode/core/src/test/java/org/apache/shardingsphere/mode/manager/switcher/SwitchingResourceTest.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/storage/unit/ShowStorageUnitExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/ExportUtils.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportDatabaseConfigurationExecutorTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportMetaDataExecutorTest.java, test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/migration/api/impl/MigrationJobAPITest.java
Remove the logic in modifying ResourceMetaData
=> Refactor usage of StorageUnitMetaData.dataSourcePoolPropertiesMap

test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
Fixes #26981.
- Add alter table column DECRYPT ENCRYPT sql test
---
=> Add alter table column DECRYPT ENCRYPT sql test

proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/parse/PostgreSQLComParseExecutor.java, proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/parse/PostgreSQLComParseExecutorTest.java
=> escape pg ? operator in proxy

mode/type/cluster/repository/provider/etcd/pom.xml, pom.xml
- Use grpc-all in dependency
---
=> Use grpc-all in dependency

mode/type/standalone/repository/provider/jdbc/src/main/resources/sql/H2.xml, mode/type/standalone/repository/provider/jdbc/src/main/resources/sql/MySQL.xml
=> Fix restart proxy throws IllegalStateException when use H2 or MySQL persistence type in Standalone

infra/database/type/sqlserver/src/main/java/org/apache/shardingsphere/infra/database/sqlserver/metadata/data/loader/SQLServerMetaDataLoader.java, infra/database/type/sqlserver/src/test/java/org/apache/shardingsphere/infra/database/sqlserver/metadata/data/loader/SQLServerMetaDataLoaderTest.java
For #28035.
- support save unique key in metadata for sqlserver
---
=> support save unique key in metadata for sqlserver

kernel/authority/api/src/main/java/org/apache/shardingsphere/authority/spi/AuthorityRegistryProvider.java, kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/provider/database/DatabasePermittedAuthorityRegistryProvider.java, kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/provider/simple/AllPermittedAuthorityRegistryProvider.java, kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/rule/AuthorityRule.java, kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/rule/builder/AuthorityRuleBuilder.java, kernel/authority/core/src/test/java/org/apache/shardingsphere/authority/checker/AuthorityCheckerTest.java, kernel/authority/core/src/test/java/org/apache/shardingsphere/authority/provider/database/DatabasePermittedAuthorityRegistryProviderTest.java, kernel/authority/core/src/test/java/org/apache/shardingsphere/authority/rule/AuthorityRuleTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactoryTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportMetaDataExecutorTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportStorageNodesExecutorTest.java, test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/migration/api/impl/MigrationJobAPITest.java
Remove useless param databases in AuthorityRegistryProvider.
=> Remove useless param databases in AuthorityRegistryProvider.

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
- Optimize oracle parsing speed
---
=> Optimize oracle parsing speed

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/AlterViewStatementHandler.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleAlterViewStatement.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ddl/impl/AlterViewStatementAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ddl/AlterViewStatementTestCase.java, test/it/parser/src/main/resources/case/ddl/alter-view.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-view.xml
Ref #27007.
- Refactor the constraintState syntax definition
- Add constraintDefinition parse
- Add test sql
---
=> Refactor the constraintState syntax definition

kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/TableNameSchemaNameMapping.java, kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/metadata/model/PipelineTableMetaData.java
- Clean code in pipeline api module
---
=> Clean code in pipeline api module

infra/exception/dialect/core/src/test/java/org/apache/shardingsphere/infra/exception/dialect/SQLExceptionTransformEngineTest.java, infra/exception/dialect/core/src/test/java/org/apache/shardingsphere/infra/exception/dialect/fixture/DatabaseProtocolExceptionExceptionFixture.java, infra/exception/dialect/core/src/test/java/org/apache/shardingsphere/infra/exception/dialect/fixture/SQLDialectExceptionMapperFixture.java, infra/exception/dialect/core/src/test/resources/META-INF/services/org.apache.shardingsphere.infra.exception.dialect.mapper.SQLDialectExceptionMapper
=> Add test case for SQLExceptionTransformEngine

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/combine/CombineSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/ExpressionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/BinaryOperationExpressionBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ExistsSubqueryExpressionBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/InExpressionBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/NotExpressionBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/SubqueryExpressionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/SubquerySegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/TableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/TableSegmentBinderContext.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/ProjectionsSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ColumnProjectionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/SubqueryProjectionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/where/WhereSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/SQLStatementBinderContext.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/InsertStatementBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinderTest.java
Ref #28016.
- Enhance join statement column and correlation subquery binder logic
---
=> Enhance join statement column and correlation subquery binder logic

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/SQLNodeConverterEngine.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/statement/explain/ExplainStatementConverter.java, test/it/optimizer/src/test/java/org/apache/shardingsphere/test/it/optimizer/converter/SQLNodeConverterEngineIT.java, test/it/optimizer/src/test/resources/converter/explain.xml
Ref #27379.
- Support explain sqlNodeConverter
- Add select and delete test sql
---
=> Support explain sqlNodeConverter

test/it/parser/src/main/resources/case/rdl/alter.xml
- Fix : fix the incorrect format
---
=> Fix : fix the incorrect format

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
Fixes #26982.
- Change alter table addConstraintSpecification syntax
- Add test sql
---
=> Change alter table addConstraintSpecification syntax

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/BroadcastSQLRouter.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/complex/ShardingCartesianRoutingEngine.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/route/SingleSQLRouter.java, kernel/single/core/src/test/java/org/apache/shardingsphere/single/route/SingleSQLRouterTest.java, test/it/rewriter/src/test/resources/scenario/sharding/case/ddl/alter-table.xml, test/it/rewriter/src/test/resources/scenario/sharding/case/ddl/create-table.xml
- Fix wrong index and constraints rewrite caused by single table and broadcast table lost in RouteContext
---
=> Fix wrong index and constraints rewrite caused by single table and broadcast table lost in RouteContext

mode/core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java, test/e2e/sql/src/test/resources/cases/dml/dataset/encrypt/batch_insert_into_user_table.xml, test/e2e/sql/src/test/resources/cases/dml/dataset/encrypt/delete_user_table.xml, test/e2e/sql/src/test/resources/cases/dml/dataset/encrypt/update_user_table.xml, test/e2e/sql/src/test/resources/cases/dml/dataset/encrypt/update_user_table_by_pwd.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/encrypt/show_encrypt_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/encrypt/show_encrypt_rules.xml, test/e2e/sql/src/test/resources/env/scenario/encrypt/data/actual/dataset.xml, test/e2e/sql/src/test/resources/env/scenario/encrypt/data/actual/init-sql/h2/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/encrypt/data/actual/init-sql/mysql/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/encrypt/data/actual/init-sql/opengauss/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/encrypt/data/actual/init-sql/postgresql/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/encrypt/proxy/conf/mysql/config-encrypt.yaml, test/e2e/sql/src/test/resources/env/scenario/encrypt/proxy/conf/opengauss/config-encrypt.yaml, test/e2e/sql/src/test/resources/env/scenario/encrypt/proxy/conf/postgresql/config-encrypt.yaml, test/e2e/sql/src/test/resources/env/scenario/encrypt/rules.yaml
Ref #28016.
- Modify e2e encrypt column to add table name prefix
---
=> Modify e2e encrypt column to add table name prefix

infra/database/type/mysql/src/test/java/org/apache/shardingsphere/infra/database/mysql/resultset/MySQLResultSetMapperTest.java
=> Add test case for MySQLResultSetMapper

infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/resultset/MySQLResultSetMapper.java, infra/database/type/mysql/src/test/java/org/apache/shardingsphere/infra/database/mysql/resultset/MySQLResultSetMapperTest.java
=> Refactor MySQLResultSetMapperTest

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/SQLNodeConverterEngine.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/statement/update/UpdateStatementConverter.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/dml/UpdateStatement.java, test/it/optimizer/src/test/java/org/apache/shardingsphere/test/it/optimizer/converter/SQLNodeConverterEngineIT.java, test/it/optimizer/src/test/resources/converter/update.xml
Ref #27378
- Support sql federation update
- Add test sql
---
=> Support sql federation update

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptPredicateColumnTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGeneratorTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/fixture/EncryptGeneratorFixtureBuilder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/engine/ProjectionEngine.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinderTest.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/column/ColumnSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/bounded/ColumnSegmentBoundedInfo.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/bounded/TableSegmentBoundedInfo.java
Ref #28016.
- Refactor bounded column and bounded table info in ColumnSegment and TableNameSegment
---
=> Refactor bounded column and bounded table info in ColumnSegment and TableNameSegment

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/DMLStatement.g4, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #27674.
- Fix OpenGauss Group BY and Having parse
---
=> Fix OpenGauss Group BY and Having parse

test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
Fixes #27007.
- Add alter table test sql
---
=> Add alter table test sql

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/statement/explain/ExplainStatementConverter.java, test/it/optimizer/src/test/resources/converter/explain.xml
Ref #27379.
- Support sql federation explain update
- Add test convert
---
=> Support sql federation explain update

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/EncryptTokenGenerateBuilder.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptPredicateColumnTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/util/EncryptTokenGeneratorUtils.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContext.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ShorthandProjectionSegmentBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ShorthandProjectionSegmentBinderTest.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/column/ColumnSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/table/JoinTableSegment.java
Ref #28016.
- Add unsupported check for join using and natural join statement
---
=> Add unsupported check for join using and natural join statement

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/standard/SQLRouteTest.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/enums/SegmentType.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/ExpressionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/BinaryOperationExpressionBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/FunctionExpressionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/InExpressionBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/NotExpressionBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ColumnProjectionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/where/WhereSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/SQLStatementBinderContext.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinderTest.java
- [Enhance sql binder logic to support join using statement](https://github.com/apache/shardingsphere/commit/9cc0ec1140a913a1dc53c0319d09eadea8962d70)
---
=> Enhance sql binder logic to support join using statement

docs/document/content/user-manual/error-code/sql-error-code.cn.md, docs/document/content/user-manual/error-code/sql-error-code.en.md, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/enums/SegmentType.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinder.java, infra/common/src/main/java/org/apache/shardingsphere/infra/exception/AmbiguousColumnException.java, infra/common/src/main/java/org/apache/shardingsphere/infra/exception/UnknownColumnException.java
- Optimize AmbiguousColumnException and UnknownColumnException message
---
=> Optimize AmbiguousColumnException and UnknownColumnException message

test/it/rewriter/src/test/resources/scenario/sharding/case/dml/select.xml
- Add more sharding sql rewrite test case for mysql
---
=> Add more sharding sql rewrite test case for mysql

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/runtime/IntegrationTestEnvironment.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/cases/value/SQLValue.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dql/BaseDQLE2EIT.java, test/e2e/sql/src/test/resources/cases/dml/dataset/passthrough/insert_date_values.xml, test/e2e/sql/src/test/resources/cases/dml/dataset/passthrough/update_date_values.xml, test/e2e/sql/src/test/resources/cases/dml/dml-integration-insert.xml, test/e2e/sql/src/test/resources/cases/dml/dml-integration-update.xml, test/e2e/sql/src/test/resources/cases/dql/dql-integration-select.xml, test/e2e/sql/src/test/resources/env/scenario/passthrough/data/actual/dataset.xml, test/e2e/sql/src/test/resources/env/scenario/passthrough/data/actual/init-sql/mysql/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/passthrough/data/actual/init-sql/opengauss/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/passthrough/data/actual/init-sql/postgresql/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/passthrough/data/expected/dataset.xml, test/e2e/sql/src/test/resources/env/scenario/passthrough/data/expected/init-sql/mysql/01-expected-init.sql, test/e2e/sql/src/test/resources/env/scenario/passthrough/data/expected/init-sql/opengauss/01-expected-init.sql, test/e2e/sql/src/test/resources/env/scenario/passthrough/data/expected/init-sql/postgresql/01-expected-init.sql
=> Add datetime type e2e

docs/community/content/team/_index.cn.md, docs/community/content/team/_index.en.md
Update document for  PMC list.
---
=> Update document for  PMC list.

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml, test/it/parser/src/main/resources/sql/unsupported/unsupported.xml
Fixes #27661.
- Support OpenGauss INET function
---
=> Support OpenGauss INET function

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
Fixes #26983.
- Fix oracle drop column ClassCastException
- Add test sql
---
=> Fix oracle drop column ClassCastException

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
Fixes #26984.
- Add oracle alter table modifyTableSubpartition parse
- Add test sql
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-TABLE.html#GUID-552E7373-BF93-477D-9DA3-B2C9386F2877__I2131024
---
=> Add oracle alter table modifyTableSubpartition parse

examples/shardingsphere-proxy-example/shardingsphere-proxy-distsql-example/src/main/java/org/apache/shardingsphere/example/proxy/distsql/feature/encrypt/EncryptExecutor.java, examples/shardingsphere-proxy-example/shardingsphere-proxy-distsql-example/src/main/java/org/apache/shardingsphere/example/proxy/distsql/feature/readwritesplitting/ReadWriteSplittingExecutor.java, examples/shardingsphere-proxy-example/shardingsphere-proxy-distsql-example/src/main/java/org/apache/shardingsphere/example/proxy/distsql/feature/resource/ResourceExecutor.java, examples/shardingsphere-proxy-example/shardingsphere-proxy-distsql-example/src/main/java/org/apache/shardingsphere/example/proxy/distsql/feature/shadow/ShadowExecutor.java, examples/shardingsphere-proxy-example/shardingsphere-proxy-distsql-example/src/main/java/org/apache/shardingsphere/example/proxy/distsql/feature/sharding/ShardingExecutor.java
For #28259.
Remove Gson from DistSQL example.
=> Remove Gson from DistSQL example.

infra/util/src/main/java/org/apache/shardingsphere/infra/util/json/JsonUtils.java, kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppTableData.java, kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPlugin.java, kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java, mode/type/cluster/repository/provider/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/lock/ConsulDistributedLock.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodeModeExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportMetaDataUpdater.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/ParseDistSQLExecutor.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/sql/ParseDistSQLExecutorTest.java, test/e2e/agent/plugins/common/pom.xml, test/e2e/agent/plugins/common/src/test/java/org/apache/shardingsphere/test/e2e/agent/common/util/OkHttpUtils.java, test/e2e/agent/plugins/tracing/jaeger/src/test/java/org/apache/shardingsphere/test/e2e/agent/jaeger/asserts/SpanAssert.java, test/e2e/agent/plugins/tracing/jaeger/src/test/java/org/apache/shardingsphere/test/e2e/agent/jaeger/result/JaegerTraceResult.java, test/e2e/agent/plugins/tracing/jaeger/src/test/java/org/apache/shardingsphere/test/e2e/agent/jaeger/result/SpanResult.java, test/e2e/agent/plugins/tracing/jaeger/src/test/java/org/apache/shardingsphere/test/e2e/agent/jaeger/result/TraceResult.java, test/e2e/agent/plugins/tracing/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/asserts/SpanAssert.java
For #28259.
Replace the use of Gson with Jackson
=> Replace the use of Gson with Jackson

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4, test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
Fixes #26985.
- Add oracle TO_DATE function parse
- Add test sql
- https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/TO_DATE.html#GUID-D226FA7C-F7AD-41A0-BB1D-BD8EF9440118
---
=> Add oracle TO_DATE function parse

parser/sql/dialect/postgresql/src/main/antlr4/imports/postgresql/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-type.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-type.xml
For #26801.
This PR is for supporting more Alter Type  statements in PostgreSQL, and also for my OSPP2023 project
=> Support more Alter Type statements

kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/ingest/record/DataRecord.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/datanode/JobDataNodeLineConvertUtils.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/CRC32MatchTableDataConsistencyChecker.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/DataMatchTableDataConsistencyChecker.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/MatchingTableDataConsistencyChecker.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/TableDataConsistencyChecker.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/TableInventoryCheckParameter.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/DataMatchTableDataConsistencyCheckerTest.java, kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLIncrementalDumper.java, kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPlugin.java, kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALEventConverter.java, kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPlugin.java, kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/event/AbstractRowEvent.java, kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALEventConverterTest.java, kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/update/CheckMigrationJobUpdater.java, kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/impl/ConsistencyCheckJobAPI.java, kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/pojo/CreateConsistencyCheckJobParameter.java, kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/impl/MigrationJobAPI.java, kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/check/consistency/MigrationDataConsistencyChecker.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java, test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/fixture/TableDataConsistencyCheckerFixture.java, test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/consistencycheck/api/impl/ConsistencyCheckJobAPITest.java
- Review and refactor pipeline
---
=> Review and refactor pipeline

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/SQLBindEngine.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/enums/SegmentType.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/MergeStatementBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/MergeStatementBinderTest.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/InsertStatementHandler.java
=> Support bind merge statement.

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
=> Fix oracle TO_DATE function parsing

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/impl/ShardingSphereProxyClusterContainer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/container/compose/DockerContainerComposer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/container/compose/NativeContainerComposer.java, test/it/pipeline/src/test/resources/config_sharding_sphere_jdbc_source.yaml, test/it/pipeline/src/test/resources/config_sharding_sphere_jdbc_target.yaml
- Improve pipeline to be compatible with Oracle
- Revise config of Pipeline IT
---
=> Improve E2E container to be compatible with Oracle

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
Fixes #26986.
- Fix nestedTableColProperties and physicalProperties definition
- Add test sql
---
=> Fix nestedTableColProperties and physicalProperties definition

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dml/delete.xml, test/it/parser/src/main/resources/case/dml/select-group-by.xml, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
=> Support extracting column information from oracle projections

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/assignment/AssignmentValueAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/assignment/ExpectedAssignmentValue.java, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/case/dml/update.xml, test/it/parser/src/main/resources/sql/supported/dml/update.xml
- Support extracting columns from oracle case when expressions
---
=> Support extracting columns from oracle case when expressions

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/impl/ShardingSphereJdbcContainer.java
=> Fix actual data sources were closed unexpectedly in Cluster mode JDBC E2E

kernel/single/core/src/main/java/org/apache/shardingsphere/single/datanode/SingleTableDataNodeLoader.java
=> Fix load single table is invalid when the table name is case-sensitive

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/ConditionValue.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueInOperatorGenerator.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/value/ListShardingConditionValue.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueInOperatorGeneratorTest.java
=> Support null routing

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
Fixes #26987.
- Change partitionKeyValue rule define
- Add test sql
---
=> Change partitionKeyValue rule define

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
Fixes #26988.
- Add oracle renamePartitionSubpart and alterIntervalPartitioning rule
- Add test sql
---
=> Add oracle renamePartitionSubpart and alterIntervalPartitioning rule

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/runtime/DataSourceEnvironment.java
=> Clean useless test code.

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/CaseWhenExpression.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/assignment/AssignmentValueAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/assignment/ExpectedAssignmentValue.java, test/it/parser/src/main/resources/case/dml/insert.xml, test/it/parser/src/main/resources/case/dml/merge.xml, test/it/parser/src/main/resources/case/dml/update.xml
- Add more Oracle column assertions and parsing
---
=> Add more Oracle column assertions and parsing

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/BaseRule.g4, parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/DMLStatement.g4, parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/OpenGaussKeyword.g4, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/parser/src/main/resources/sql/supported/dml/select-expression.xml
Fixes #27740.
- Support OpenGauss ts_rewrite function parse
ref: https://docs.opengauss.org/zh/docs/1.0.0/docs/Developerguide/%E6%9F%A5%E8%AF%A2%E9%87%8D%E5%86%99.html
---
=> Support OpenGauss ts_rewrite function parse

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/SQLNodeConverterEngine.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/statement/insert/InsertStatementConverter.java, test/it/optimizer/src/test/java/org/apache/shardingsphere/test/it/optimizer/converter/SQLNodeConverterEngineIT.java, test/it/optimizer/src/test/resources/converter/insert.xml, test/it/parser/src/main/resources/sql/supported/dml/insert.xml
Ref #27376.
- add insert statement converter.
---
=> Add insert statement converter.

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, test/it/optimizer/src/test/resources/converter/select-expression.xml, test/it/parser/src/main/resources/case/dml/select-expression.xml
Fixes #26871 .
support odbc escape syntax
---
=> support odbc escape syntax

docs/document/content/user-manual/error-code/sql-error-code.cn.md, docs/document/content/user-manual/error-code/sql-error-code.en.md, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/DeleteStatementBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/MergeStatementBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/SelectStatementBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/UpdateStatementBinderTest.java, infra/common/src/main/java/org/apache/shardingsphere/infra/exception/TableNotExistsException.java, proxy/backend/type/hbase/src/test/java/org/apache/shardingsphere/proxy/backend/hbase/converter/type/HBaseDeleteOperationConverterTest.java, proxy/backend/type/hbase/src/test/java/org/apache/shardingsphere/proxy/backend/hbase/converter/type/HBaseUpdateOperationConverterTest.java, proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutorTest.java, proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLComQueryPacketExecutorTest.java, proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandlerTest.java, proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutorTest.java, proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/parse/PostgreSQLComParseExecutorTest.java
=> Add table not exists exception.

.github/workflows/nightly-check.yml
- increase the codeql check timeout
---
=> Refactor : increase the codeql check timeout

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/alter-encrypt-rule.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/alter-encrypt-rule.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/create-encrypt-rule.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/create-encrypt-rule.en.md
=> Fix algorithm type in ENCRYPT DDL document

test/util/src/main/java/org/apache/shardingsphere/test/loader/TestParameterLoader.java
=> TestParameterLoader support GitHub token.

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/UnaryOperationExpressionConverter.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java
Ref #28320.
- Revise pr #28320
---
=> Revise pr #28320

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/WindowFunctionConverter.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, test/it/optimizer/src/test/resources/converter/select-special-function.xml, test/it/parser/src/main/resources/case/dml/select-special-function.xml
=> support for WindowFunction

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/FunctionConverter.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/WindowFunctionConverter.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
Ref #28319.
- Revise pr#28319
---
=> Revise pr#28319

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/expression/impl/VariableSegmentConverter.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/type/DataTypeConverter.java, test/it/optimizer/src/test/resources/converter/select-table.xml, test/it/optimizer/src/test/resources/converter/update.xml
Ref #27461.
- Revise pr#27461
---
=> Revise pr#27461

test/it/parser/src/main/resources/case/ddl/audit.xml, test/it/parser/src/main/resources/sql/supported/ddl/audit.xml
Fixes #27008.
- Add oracle audit all sql test
---
=> Add oracle audit all sql test

parser/sql/dialect/postgresql/src/main/antlr4/imports/postgresql/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/execute.xml, test/it/parser/src/main/resources/sql/supported/ddl/execute.xml
For #26801.
This PR is for supporting more EXECUTE statements in PostgreSQL, and also for my OSPP2023 project
=> support EXECUTE statement

kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/config/ingest/InventoryDumperConfiguration.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/job/progress/JobItemInventoryTasksProgress.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/PipelineTaskUtils.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/common/job/progress/InventoryIncrementalJobItemProgressTest.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/common/job/progress/yaml/YamlInventoryIncrementalJobItemProgressSwapperTest.java, kernel/data-pipeline/core/src/test/resources/job-progress.yaml
- Fix get inventory position not correctly at Pipeline
---
=> Fix get inventory position not correctly at Pipeline

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4, test/it/parser/src/main/resources/case/ddl/create-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
- Optimize Oracle support create table as select.
---
=> Optimize Oracle support create table as select.

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java
Ref #26989.
- Optimized alter definition parse code
---
=> Optimized alter definition parse code

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java
=> add more exclude bind columns

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/MergeStatementBinderTest.java
=> Fix suquery expression projection in merge bind ex

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
- Support Oracle SQL parsing custom functions with DISTINCT
---
=> Support Oracle SQL parsing custom functions with DISTINCT

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4
=> Fix Oracle BaseRule.g4 error.

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/pojo/ConsistencyCheckJobItemInfo.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/PipelineTaskUtils.java, kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckStatusExecutor.java, kernel/data-pipeline/distsql/handler/src/test/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckStatusExecutorTest.java, kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/impl/ConsistencyCheckJobAPI.java, kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/config/ConsistencyCheckJobConfiguration.java, kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/config/yaml/YamlConsistencyCheckJobConfiguration.java, kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/config/yaml/YamlConsistencyCheckJobConfigurationSwapper.java, kernel/data-pipeline/scenario/consistencycheck/src/test/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/context/ConsistencyCheckJobItemContextTest.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java, test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/consistencycheck/api/impl/ConsistencyCheckJobAPITest.java
- Add algorithm columns in "show migration check status" DistSQL result
- Improve migration general E2E to shorten waiting time in waitIncrementTaskFinished
- Impl getSourceDatabaseType() for ConsistencyCheckJobConfiguration
---
=> Add algorithm columns in "show migration check status" DistSQL result

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/type/SQLServerDDLStatementVisitor.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ddl/DDLStatementAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ddl/impl/CreateSequenceStatementAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/sequence/ExpectedSequenceNameClause.java, test/it/parser/src/main/resources/case/ddl/create-sequence.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-sequence.xml
Ref #28387.
- Fix create sequence parse
- Add test sql
---
=> Fix create sequence parse

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/ExpressionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/TableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/DeleteMultiTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/ProjectionsSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ShorthandProjectionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/DeleteStatementBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/MergeStatementBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/SelectStatementBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/UpdateStatementBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/JoinTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ShorthandProjectionSegmentBinderTest.java
=> Fix multi subquery bind

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/BaseDMLE2EIT.java, test/e2e/sql/src/test/resources/cases/dml/dml-integration-insert.xml
- Fix insert statement assert exception with encrypt feature
---
=> Fix insert statement assert exception with encrypt feature

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/ExpressionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/ProjectionsSegmentBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinderTest.java
=> Fix same alias subquery bind

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManager.java
=> Refactor DriverDatabaseConnectionManager#getRandomConnection

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/FunctionTableSegmentBinderContext.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/SimpleTableSegmentBinderContext.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/TableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinderTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ShorthandProjectionSegmentBinderTest.java
=> Fix function table bind ex

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/value/literal/impl/DateTimeLiteralValue.java, test/it/parser/src/main/resources/case/dml/insert.xml, test/it/parser/src/main/resources/case/dml/select-special-function.xml
- Enhance oracle datetime sql parse logic
---
=> Enhance oracle datetime sql parse logic

parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/simple/ColumnWithJoinOperatorSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/ColumnExtractor.java
=> Support Left and Right Joins Using the Plus (+) Sign in Oracle.

infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLMetaDataLoader.java, infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLMetaDataLoaderTest.java
=> Support save index columns in metadata for postgres

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/InsertStatementContext.java
- Support encrypt insert select sql rewrite
---
=> Support encrypt insert select sql rewrite

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/_index.en.md
Fixes #21476.
- Add a description of the Jakarta EE namespace in the documentation for Spring Boot.
- For https://github.com/apache/shardingsphere/issues/26041 .
---
=> Add a description of the Jakarta EE namespace in the documentation for Spring Boot

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/ColumnProjection.java
- Add null check to avoid NPE
---
=> Add null check to avoid NPE

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertDefaultColumnsTokenGenerator.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/fixture/EncryptGeneratorFixtureBuilder.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertCipherNameTokenGeneratorTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertDefaultColumnsTokenGeneratorTest.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/InsertStatementBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/InsertStatementBinderTest.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/dml/InsertStatement.java
Ref #28016.
- Add encryptor check for insert select statement without columns
---
=> Add encryptor check for insert select statement without columns

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/reviser/index/ShardingIndexReviser.java
=> Fix sharding index reviser not return default indexname

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/SQLStatementBinderContext.java, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/PivotSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/table/SimpleTableSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/table/SubqueryTableSegment.java
- Parse pivot segment and extract column in sql binder
---
=> Parse pivot segment and extract column in sql binder

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/statement/insert/InsertStatementConverter.java
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYpJ1wWbIDLzMnRvyJ6F
---
=> Fis sonar issue in InsertStatementConverter

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/PivotSegment.java
- Parse unpivot segment and extract column in sql binder
---
=> Parse unpivot segment and extract column in sql binder

features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleStatementUpdater.java
=> Check algorithm type in encrypt DistSQL

features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/api/encrypt/assisted/AssistedEncryptAlgorithm.java, features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/api/encrypt/like/LikeEncryptAlgorithm.java, features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/api/encrypt/standard/StandardEncryptAlgorithm.java, features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/spi/EncryptAlgorithm.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/assisted/MD5AssistedEncryptAlgorithm.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/like/CharDigestLikeEncryptAlgorithm.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/standard/AESEncryptAlgorithm.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/standard/RC4EncryptAlgorithm.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptAlterTableTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/util/EncryptTokenGeneratorUtils.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptRule.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptTable.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/column/item/AssistedQueryColumnItem.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/column/item/CipherColumnItem.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/column/item/LikeQueryColumnItem.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/algorithm/assisted/MD5AssistedEncryptAlgorithmTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/algorithm/like/CharDigestLikeEncryptAlgorithmTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/algorithm/standard/AESEncryptAlgorithmTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/algorithm/standard/RC4EncryptAlgorithmTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/fixture/CoreEncryptAlgorithmFixture.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/fixture/CoreQueryAssistedEncryptAlgorithmFixture.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/fixture/CoreQueryLikeEncryptAlgorithmFixture.java, test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/fixture/encrypt/JDBCEncryptAlgorithmFixture.java, test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/fixture/encrypt/JDBCQueryAssistedEncryptAlgorithmFixture.java, test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/fixture/encrypt/RewriteNormalEncryptAlgorithmFixture.java, test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/fixture/encrypt/RewriteQueryAssistedEncryptAlgorithmFixture.java, test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/fixture/encrypt/RewriteQueryLikeEncryptAlgorithmFixture.java
=> Rmove <I, O> from encrypt algorithm

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4, parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleCreateViewStatement.java, test/it/parser/src/main/resources/case/ddl/create-view.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-view.xml
Ref #28387.
- Support oracle create view parse
- Add test sql
- https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CREATE-VIEW.html#GUID-61D2D2B4-DACC-4C7C-89EB-7E50D9594D30
---
=> Support oracle create view parse

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
Fixes #26989.
- Enhance Oracle alter table syntax rules
- Add test sql
---
=> Enhance Oracle alter table syntax rules

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/DDLStatement.g4, parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/OpenGaussKeyword.g4, test/it/parser/src/main/resources/case/dcl/grant.xml, test/it/parser/src/main/resources/sql/supported/dcl/grant-user.xml
Support GRANT USAGE ON CLIENT_MASTER_KEY
Refs #27639.
-
---
=> Support parsing openGauss GRANT sql

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/common/pojo/ConsistencyCheckJobItemInfo.java, kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckStatusExecutor.java, kernel/data-pipeline/distsql/handler/src/test/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationCheckStatusExecutorTest.java, kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/impl/ConsistencyCheckJobAPI.java
- Add "active" column in "show migration check status" DistSQL result
---
=> Improve "show migration check status"

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/DALStatement.g4, test/it/parser/src/main/resources/case/dal/set.xml, test/it/parser/src/main/resources/sql/supported/dal/set.xml
Fixes #27639.
- Add support for SET SESSION AUTHORIZATION for openGauss
---
=> Add support for SET SESSION openGauss

infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussMetaDataLoader.java, infra/database/type/opengauss/src/test/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussMetaDataLoaderTest.java
=> Support get unique key for og

infra/database/type/opengauss/src/test/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussMetaDataLoaderTest.java
=> Fix ci failed

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-aggregate.xml, test/it/parser/src/main/resources/sql/supported/dml/select-aggregate.xml
=> Oracle sql parser support approx rank.

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/sink/PipelineDataSourceSink.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/service/impl/AbstractPipelineJobAPIImpl.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/runner/InventoryIncrementalTasksRunner.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/job/CDCJob.java, kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/task/ConsistencyCheckTasksRunner.java, test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/migration/check/consistency/MigrationDataConsistencyCheckerTest.java
- Break success process if job is stopping
- Add run_count in job props
---
=> Break success process if job is stopping

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/planner/util/SQLFederationFunctionUtils.java, proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussAdminExecutorCreator.java
Fixes #28482.
- Fix the problem that gsql cannot connect in version 3.1.0
---
=> Fix the problem that gsql cannot connect in version 3.1.0

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/item/IntervalExpressionProjection.java, test/it/parser/src/main/resources/case/dml/insert.xml, test/it/parser/src/main/resources/sql/supported/dml/insert.xml
- Fix oracle interval sql visit npe
---
=> Fix oracle interval sql visit npe

infra/database/type/opengauss/src/test/java/org/apache/shardingsphere/infra/database/opengauss/resultset/OpenGaussResultSetMapperTest.java
For #27932 OpenGaussResultSetMapperTest
-
---
=> Add test case for OpenGaussResultSetMapperTest

infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/resultset/PostgreSQLResultSetMapperTest.java
For #27932   PostgreSQLResultSetMapperTest
-
---
=> Add test case for  PostgreSQLResultSetMapper

.github/workflows/nightly-check.yml
- refactor the stale action to avoid stale PR
---
=> Refactor: refactor the stale action to avoid stale PR

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/reviser/index/ShardingIndexReviser.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java
Fix
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=apache_shardingsphere&open=AYqTbPZem7oxF2xZRTCx&tab=how_to_fix
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=apache_shardingsphere&open=AYonuDl-d4qzGKisbOkx
=> Fix sonar issues

parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/type/OpenGaussDDLStatementVisitor.java, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/type/PostgreSQLDDLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/alter-table.xml
Fixes https://github.com/apache/shardingsphere/issues/27957
-
---
=> PostgreSQL And OpenGauss Support Get Rename Column

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dml/insert.xml, test/it/parser/src/main/resources/case/dml/select.xml
- Extract parameters from oracle TO_DATE function
---
=> Extract parameters from oracle TO_DATE function

docs/document/content/reference/management/_index.cn.md, docs/document/content/reference/management/_index.en.md, docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/alter-encrypt-rule.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/alter-encrypt-rule.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/create-encrypt-rule.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/create-encrypt-rule.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/usage/encrypt-rule.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/usage/encrypt-rule.en.md, docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.cn.md, docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.en.md, docs/document/content/user-manual/shardingsphere-proxy/yaml-config/data-source.cn.md, docs/document/content/user-manual/shardingsphere-proxy/yaml-config/data-source.en.md, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/config/ProxyConfigurationLoaderTest.java, proxy/backend/core/src/test/resources/conf/config_loader/config-encrypt.yaml, proxy/backend/core/src/test/resources/conf/convert/config-encrypt.yaml, proxy/backend/core/src/test/resources/conf/convert/config-mix.yaml, proxy/backend/core/src/test/resources/expected/convert-encrypt.yaml, proxy/backend/core/src/test/resources/expected/convert-mix.yaml, proxy/bootstrap/src/main/resources/conf/config-encrypt.yaml
- Remove useless rc4 config and update document for shardingsphere plugin
---
=> Remove useless rc4 config and update document for shardingsphere plugin

mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoader.java
Rename return parameter to result.
---
=> Rename return parameter to result

docs/document/content/test-manual/integration-test/_index.cn.md, docs/document/content/test-manual/integration-test/_index.en.md
=> Ehance remote debug docs

mode/core/src/test/java/org/apache/shardingsphere/mode/metadata/MetaDataContextsFactoryTest.java
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYsJOFopBx6PFK230VpC
=> Fix sonar cloud issue

db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLArrayParameterDecoder.java
Adjust foreach variable name.
---
=> Adjust foreach variable name

docs/document/content/test-manual/integration-test/_index.cn.md, docs/document/content/test-manual/integration-test/_index.en.md
- Add content in remote debug doc
---
=> Add content in remote debug doc

.github/workflows/e2e-operation.yml
- rename the operation workflow name
---
=> Refactor : rename the operation workflow name

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/statement/explain/ExplainStatementConverter.java, test/it/optimizer/src/test/resources/converter/explain.xml
Ref #27379.
- Add explain insert convert
- Add convert test
---
=> Add explain insert convert

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/segment/from/impl/JoinTableConverter.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java, test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-pagination-group-by-order-by.xml
Fixes #28678.
- Support mysql cross join statement for sql federation
- add e2e test case
---
=> Support mysql cross join statement for sql federation

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java
Fix https://sonarcloud.io/project/issues?impactSeverities=HIGH&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYpERCSACGFczfQYpFTX
=> Fix sonar issue on OracleDMLStatementVisitor

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/cache/checker/ShardingRouteCacheableCheckerTest.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/assign/AssignmentSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/projection/ProjectionsSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/UpdateStatementBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/assign/AssignmentSegmentBinderTest.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/item/ExpressionProjectionSegment.java, proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/parse/PostgreSQLComParseExecutorTest.java, test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/statement/ShardingPreparedStatementTest.java
=> support bind update set assignment

kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/schema/NewViewMetaDataPersistService.java
Fixes #28696.
- Fix wrong view zk path with new metadata structure
---
=> Fix wrong view zk path with new metadata structure

.github/workflows/nightly-check.yml
- refactor the jvm for maven to pass the sonar report test
---
=> Refactor : refactor the jvm for maven to pass the sonar report test

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/storage/unit/ShowStorageUnitExecutor.java
Refactor ShowStorageUnitExecutor
result set unchanged
=> Refactor ShowStorageUnitExecutor

docs/document/content/user-manual/common-config/builtin-algorithm/expr.cn.md, docs/document/content/user-manual/common-config/builtin-algorithm/expr.en.md, infra/expr/type/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParser.java, infra/expr/type/groovy/src/main/java/org/apache/shardingsphere/infra/expr/groovy/GroovyInlineExpressionParser.java, infra/util/src/main/java/org/apache/shardingsphere/infra/util/groovy/GroovyUtils.java, infra/util/src/test/java/org/apache/shardingsphere/infra/util/groovy/GroovyUtilsTest.java
Fixes https://sonarcloud.io/project/issues?resolved=false&id=apache_shardingsphere&open=AYnqVrW36RCP65Ho1B18 .
- Fix the SonarCloud issue in EspressoInlineExpressionParser.
- Refer to https://sonarcloud.io/project/issues?resolved=false&id=apache_shardingsphere&open=AYnqVrW36RCP65Ho1B18 .
---
=> Fix the SonarCloud issue in EspressoInlineExpressionParser

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptTable.java, proxy/backend/type/hbase/src/main/java/org/apache/shardingsphere/proxy/backend/hbase/result/query/HBaseGetResultSet.java
=> Fix the case sensitivity issue caused by using CaseInsensitiveMap keys.

test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/case/dml/select-group-by.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/dml/select-group-by.xml
Fixes #26991 #26992 #26993
- Add oracle alter table and select sql parse test
---
=> Add oracle alter table and select sql parse test

mode/core/src/main/java/org/apache/shardingsphere/mode/manager/switcher/ResourceSwitchManager.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/AlterStorageUnitBackendHandler.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/AlterStorageUnitBackendHandlerTest.java
=> Fixes #28726, optimize AlterStorageUnitBackendHandler

docs/community/content/involved/release/shardingsphere.cn.md, docs/community/content/involved/release/shardingsphere.en.md
- refactor the release document
---
=> Document : refactor the release document

mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/status/cluster/subscriber/ClusterStatusSubscriberTest.java
Fixes #28488
-added test for ClusterStatusSubscriberTest
---
=> added test for ClusterStatusSubscriberTest

test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/job/service/GovernanceRepositoryAPIImplTest.java
Fixes #28543 
- Added unit test for GovernanceRepositoryAPIImpl.isExisted
---
=> #28543 Add unit test for GovernanceRepositoryAPIImpl.isExisted

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/SQLRewriteEntry.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/engine/GenericSQLRewriteEngine.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/engine/RouteSQLRewriteEngine.java, infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/engine/GenericSQLRewriteEngineTest.java, infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/engine/RouteSQLRewriteEngineTest.java, kernel/sql-translator/api/src/main/java/org/apache/shardingsphere/sqltranslator/spi/SQLTranslator.java, kernel/sql-translator/core/src/main/java/org/apache/shardingsphere/sqltranslator/rule/SQLTranslatorRule.java, kernel/sql-translator/core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/SQLTranslatorRuleTest.java, kernel/sql-translator/core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/fixture/AlwaysFailedSQLTranslator.java, kernel/sql-translator/core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/fixture/ConvertToUpperCaseSQLTranslator.java, kernel/sql-translator/provider/jooq/src/main/java/org/apache/shardingsphere/sqltranslator/jooq/JooQSQLTranslator.java, kernel/sql-translator/provider/native/src/main/java/org/apache/shardingsphere/sqltranslator/natived/NativeSQLTranslator.java
Ref #28750.
- Add RuleMetaData for SQLTranslator interface
---
=> Add RuleMetaData for SQLTranslator interface

.github/workflows/nightly-check.yml, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/operator/physical/EnumerableScan.java, kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/compiler/it/SQLStatementCompilerIT.java, mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/subscriber/ProcessListChangedSubscriberTest.java
=> Fix : fix nightly ci

examples/pom.xml
- change example version to 5.4.1 for release
---
=> change example version to 5.4.1 for release

RELEASE-NOTES.md
- update release note for 5.4.1
---
=> update release note for 5.4.1

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/SQLRewriteEntry.java
Ref #28750.
- Minor refactor in SQLRewriteEntry
---
=> Minor refactor in SQLRewriteEntry

distribution/proxy-native/src/main/release-docs/LICENSE, distribution/proxy/src/main/release-docs/LICENSE
- Update license for some upgrade jar
---
=> Update license for some upgrade jar

test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ddl/impl/AlterTablespaceStatementAssert.java, test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/case/ddl/alter-tablespace.xml, test/it/parser/src/main/resources/case/dml/select-group-by.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-tablespace.xml, test/it/parser/src/main/resources/sql/supported/dml/select-group-by.xml
Fixes #26994.
- Add alter table sql parse test
- Add select sum group by sql parse test
- Fix alter tablespace assert define
- Change alter tablespace sql cast
---
=> Fix alter tablespace assert and add other sql parse test

kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/persist/node/NewDatabaseMetaDataNodeTest.java
Fixes #28496.
- Added Unit Test for NewDatabaseMetaDataNode#getDataSourceNodeVersionsNode, asserts expecte value
---
=> Adding Unit Test for NewDatabaseMetaDataNode#getDataSourceNodeVersionsNode

kernel/single/core/src/test/java/org/apache/shardingsphere/single/metadata/reviser/SingleMetaDataReviseEntryTest.java
Fixes #28533 
-
Added unit tests for SingleMetaDataReviseEntry.java
---
=> Singlemetadatareviseentry unit tests

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/audit.xml, test/it/parser/src/main/resources/sql/supported/ddl/audit.xml
Fixes #27009.
- Fix oracle audit auditOperationClause rule
- Add test sql
---
=> Fix oracle audit auditOperationClause rule

docs/document/content/user-manual/shardingsphere-proxy/migration/build.cn.md, docs/document/content/user-manual/shardingsphere-proxy/migration/build.en.md
- fix the connector-j 404 issue
---
=> Fix : fix the connector-j 404 issue

distribution/proxy-native/pom.xml, infra/expr/type/espresso/pom.xml, kernel/single/core/src/test/java/org/apache/shardingsphere/single/metadata/reviser/SingleMetaDataReviseEntryTest.java, pom.xml, test/e2e/agent/jdbc-project/pom.xml
Fix: https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=apache_shardingsphere&open=AYtg-m9Mgl3BJwMzBHrH
=> Fix sonar issues on SingleMetaDataReviseEntryTest

test/it/parser/src/main/resources/case/ddl/create-diskgroup.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-diskgroup.xml
Fixes #27023 and ref #26878
- Add create-diskgroup related test SQL
---
=> SQL parsing Enhancement: add create-diskgroup test SQL

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/PipelineJobProgressDetector.java
- Add  all inventory task is empty check.
---
=> Improve PipelineJobProgressDetector.isAllInventoryTasksCompleted when all inventory task is empty

kernel/sql-translator/api/src/main/java/org/apache/shardingsphere/sqltranslator/api/config/SQLTranslatorRuleConfiguration.java, kernel/sql-translator/core/src/main/java/org/apache/shardingsphere/sqltranslator/rule/SQLTranslatorRule.java, kernel/sql-translator/core/src/main/java/org/apache/shardingsphere/sqltranslator/yaml/config/YamlSQLTranslatorRuleConfiguration.java, kernel/sql-translator/core/src/main/java/org/apache/shardingsphere/sqltranslator/yaml/swapper/NewYamlSQLTranslatorRuleConfigurationSwapper.java, kernel/sql-translator/core/src/main/java/org/apache/shardingsphere/sqltranslator/yaml/swapper/YamlSQLTranslatorRuleConfigurationSwapper.java, kernel/sql-translator/core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/SQLTranslatorRuleTest.java, kernel/sql-translator/distsql/handler/src/test/java/org/apache/shardingsphere/sqltranslator/distsql/handler/ShowSQLTranslatorRuleExecutorTest.java
- Add props config in SQLTranslatorRuleConfiguration
---
=> Add props config in SQLTranslatorRuleConfiguration

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariableExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesExecutor.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariableExecutorTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesExecutorTest.java
=> For #28968, fix query for proxy_frontend_database_protocol_type

kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPlugin.java, kernel/data-pipeline/dialect/opengauss/src/test/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPluginTest.java, kernel/data-pipeline/scenario/cdc/client/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/client/handler/RetryStreamingExceptionHandler.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/AbstractMigrationE2EIT.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/task/E2EIncrementalTask.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/helper/PipelineCaseHelper.java, test/e2e/operation/pipeline/src/test/resources/env/scenario/general/opengauss.xml
Related: #22500
Fixes #28958.
- Improve MppdbDecodingPlugin,compatible with more types
- Add unit test and IT
---
=> Improve MppdbDecodingPlugin,compatible with more types

kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/cdc/distsql/handler/update/DropStreamingUpdater.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/impl/CDCJobAPI.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/handler/CDCBackendHandler.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
Relate #22500.
Fixes: #28979
- Improve drop streaming, not allow drop active job
---
=> Improve drop streaming, not allow drop active job

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/from/impl/SimpleTableConverter.java, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/table/SimpleTableSegment.java, test/it/optimizer/src/test/resources/converter/delete.xml, test/it/parser/src/main/resources/case/dml/delete.xml
=> Increase Support for dmlTableClause for Oracle

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableUpdater.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableUpdaterTest.java
=> Fix set dist variable for proxy_frontend_database_protocol_type

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-combine.xml, test/it/parser/src/main/resources/sql/supported/dml/select-combine.xml
- Add complex select union query statement parsing test
- Add multiple union statement parsing test
- Add multiple union priority test
- Priority Description Reference [link](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/The-UNION-ALL-INTERSECT-MINUS-Operators.html#GUID-B64FE747-586E-4513-945F-80CB197125EE)
---
- [  ✓] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [  ✓] I have self-reviewed the commit code.
- [  ✓] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [  ✓] I have added …
=> Add oracle select union statement parse test

kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/context/CDCJobItemContext.java
Fixes #29035.
- Fix CDC processedRecordCount statistics
---
=> Fix CDC processedRecordCount statistics

docs/community/content/involved/release/shardingsphere.cn.md, docs/community/content/involved/release/shardingsphere.en.md
- add steps for document navigation in mobile
=> Document : add steps for document navigation in mobile

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/create-view.xml, test/it/parser/src/main/resources/case/dml/insert.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-view.xml, test/it/parser/src/main/resources/sql/supported/dml/insert.xml
Fixes #27122.
- Fix oracle attribute parse rule
- Add oracle  create view parse sql test
- Add oracle  insert parse sql test
---
- [✓] I have self-reviewed the commit code.
- [✓] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [✓] I have added corresponding unit tests for my changes.
=> Fix oracle create view attribute parse rule

test/it/parser/src/main/resources/case/ddl/create-materialized-view.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-materialized-view.xml
Fixes #27049.
- Add more test case.
---
=> SQL parsing Enhancement: add more SQL test case for create-materialized-view

test/it/parser/src/main/resources/case/ddl/create-materialized-view-log.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-materialized-view-log.xml
Fixes #27034.
- Add test case SQL
---
=> SQL parsing Enhancement:add test case for create materialized view log

test/it/parser/src/main/resources/case/dal/explain.xml, test/it/parser/src/main/resources/sql/supported/dal/explain.xml
Fixes #27142.
- Format explain case xml
- Add oracle explain parse test
---
- [✓] I have self-reviewed the commit code.
- [✓] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [✓] I have added corresponding unit tests for my changes.
=> Add oracle explain parse test

kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/impl/CDCJobAPI.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/importer/sink/CDCSocketSink.java
Related #22500.
- Improve CDC job stop_time display
- Notify client when job close
---
=> Improve stop_time display at show streaming list of CDC

test/e2e/sql/src/test/resources/cases/ral/dataset/empty_rules/show_dist_variables.xml, test/e2e/sql/src/test/resources/cases/ral/dataset/empty_rules/show_sharding_table_rule.xml, test/e2e/sql/src/test/resources/cases/rdl/dataset/rdl_empty_rules/alter_encrypt_rule.xml, test/e2e/sql/src/test/resources/cases/rdl/dataset/rdl_empty_rules/alter_mask_rule.xml, test/e2e/sql/src/test/resources/cases/rdl/dataset/rdl_empty_rules/alter_sharding_rules.xml, test/e2e/sql/src/test/resources/cases/rdl/dataset/rdl_empty_rules/create_encrypt_rule.xml, test/e2e/sql/src/test/resources/cases/rdl/dataset/rdl_empty_rules/create_sharding_rules.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting_and_encrypt/show_encrypt_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting_and_encrypt/show_encrypt_rules.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/encrypt/show_encrypt_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/encrypt/show_encrypt_rules.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/encrypt_and_readwrite_splitting/show_encrypt_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/encrypt_and_readwrite_splitting/show_encrypt_rules.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/mask/cluster/show_mask_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/mask/standalone/show_mask_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/mask_encrypt/cluster/show_mask_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/mask_encrypt/show_mask_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/mask_encrypt/standalone/show_mask_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/mask_encrypt_sharding/cluster/show_mask_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/mask_encrypt_sharding/standalone/show_mask_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/mask_sharding/cluster/show_mask_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/mask_sharding/standalone/show_mask_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/sharding_and_encrypt/show_encrypt_rule.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/sharding_and_encrypt/show_encrypt_rules.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/tbl/show_sharding_algorithms.xml, test/e2e/sql/src/test/resources/cases/rql/dataset/tbl/show_sharding_table_rules.xml
Fixes #29039.
- Fix e2e sql test error
---
=> Fix e2e sql test error

test/it/parser/src/main/resources/case/ddl/create-materialized-view.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-materialized-view.xml
Fixes #27048.
- Add test case SQL 
---
=> SQL parsing Enhancement: add test case for create materialized view

test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/deadlock/TransactionDeadlockTestCase.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/readwritesplitting/ReadwriteSplittingInTransactionTestCase.java
Fix https://github.com/apache/shardingsphere/actions/runs/6942546061/job/18885733347?pr=29107
=> Fix transaction E2E on MySQL.

docs/document/content/dev-manual/sharding.cn.md, docs/document/content/dev-manual/sharding.en.md
- https://github.com/apache/shardingsphere/actions/runs/6948982174/job/18906133558
---
=> Update key generate doc to solve dead link

test/e2e/sql/src/test/resources/env/scenario/encrypt_shadow/proxy/conf/mysql/config-encrypt-shadow.yaml, test/e2e/sql/src/test/resources/env/scenario/readwrite_splitting_and_shadow/proxy/conf/mysql/config-shadow.yaml, test/e2e/sql/src/test/resources/env/scenario/shadow/proxy/conf/mysql/config-shadow.yaml
Fix https://github.com/apache/shardingsphere/actions/runs/6953119678/job/18917919112?pr=29119
=> Fix shadow E2E on MySQL.

kernel/sql-translator/distsql/parser/src/main/java/org/apache/shardingsphere/sqltranslator/distsql/parser/core/SQLTranslatorDistSQLStatementVisitor.java
For #29108.
- Fix statement visitor of DistSQL ALTER SQL_TRANSLATOR RULE
---
=> Fix statement visitor of DistSQL ALTER SQL_TRANSLATOR RULE

infra/common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintUtils.java
- Refactor SQLHintUtils logic for method reuse
---
=> Refactor SQLHintUtils logic for method reuse

docs/document/content/faq/_index.cn.md, docs/document/content/faq/_index.en.md
- Update single table use way in FAQ doc
---
=> Update single table use way in FAQ doc

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/no-audit.xml, test/it/parser/src/main/resources/sql/supported/ddl/no-audit.xml
Fixes #27155.
- Add g4 syntax for NOAUDIT ALL
- Add test case SQL
---
=> Support parsing Oracle NOAUDIT ALL sql

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/create-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
Ref #27083.
- Refactor the syntax of the Oracle create table section
- Add parse test
---
=> Refactor the syntax of the Oracle create table section

test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/job/service/PipelineGovernanceFacadeTest.java
- Clean zk node,avoid effect other case
---
=> Recover PipelineGovernanceFacadeTest; Clean new created node in unit test

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/create-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
Fixes #27083.
- Fix create table listPartitionDesc and subpartitionTemplate syntax
- Add test sql
---
=> Fix create table listPartitionDesc and subpartitionTemplate syntax

kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/query/ShowUnloadedSingleTableExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowTableMetaDataExecutor.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowTableMetaDataExecutorTest.java
=> Enhance the output information of SHOW TABLE METADATA

infra/common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintUtils.java
- Minor refactor of SQLHintUtils
---
=> Minor refactor of SQLHintUtils

test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/statement/EncryptPreparedStatementTest.java
- Fix assert insert with batch execute test
---
=> Fix assert insert with batch execute test

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/create-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
Ref #27084.
- Fix create table hashSubpartitionQuantity rule
- Add test sql
---
=> Fix create table hashSubpartitionQuantity rule

docs/community/content/involved/release/shardingsphere.cn.md, docs/community/content/involved/release/shardingsphere.en.md
Fix : fix the incorrect link
---
=> Fix : fix the incorrect link

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/create-cluster.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-cluster.xml
Fixes #27020.
- Fix oracle create cluster syntax
- Add test sql
---
=> Fix oracle create cluster syntax

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/builder/ShardingRuleBuilder.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/cache/checker/ShardingRouteCacheableCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dal/show/ShowCreateTableMergedResultTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dal/show/ShowTableStatusMergedResultTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dal/show/ShowTablesMergedResultTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/fixture/ShardingRoutingEngineFixtureBuilder.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/broadcast/ShardingDatabaseBroadcastRoutingEngineTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/broadcast/ShardingTableBroadcastRoutingEngineTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/unicast/ShardingUnicastRoutingEngineTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableNodesExecutorTest.java, jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/datasource/metadata/ShardingSphereDatabaseMetaDataTest.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/YamlDatabaseConfigurationImportExecutor.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationUpdaterTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rql/storage/unit/ShowStorageUnitExecutorTest.java, test/it/pipeline/src/test/resources/config_sharding_sphere_jdbc_target.yaml
- Minor refactor for create new ShardingRule
---
=> Minor refactor for create new ShardingRule

features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/query/ShowShadowTableRulesExecutor.java, features/shadow/distsql/parser/src/main/antlr4/imports/shadow/BaseRule.g4, features/shadow/distsql/parser/src/main/antlr4/imports/shadow/RQLStatement.g4, features/shadow/distsql/parser/src/main/java/org/apache/shardingsphere/shadow/distsql/parser/core/ShadowDistSQLStatementVisitor.java, features/shadow/distsql/statement/src/main/java/org/apache/shardingsphere/shadow/distsql/statement/ShowShadowTableRulesStatement.java, test/it/parser/src/main/resources/case/rql/show.xml
Fixes #25925 .
-
Added support for specifying table name to the feature Show Shadow Table Rules. 
---
=> Add support for specifying table name in show shadow table rule for shadow table feature

infra/context/src/test/java/org/apache/shardingsphere/infra/connection/kernel/KernelProcessorTest.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/engine/GenericSQLRewriteEngine.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/engine/RouteSQLRewriteEngine.java, infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/SQLRewriteEntryTest.java, kernel/sql-translator/api/src/main/java/org/apache/shardingsphere/sqltranslator/context/SQLTranslatorContext.java, kernel/sql-translator/api/src/main/java/org/apache/shardingsphere/sqltranslator/spi/SQLTranslator.java, kernel/sql-translator/core/src/main/java/org/apache/shardingsphere/sqltranslator/rule/SQLTranslatorRule.java, kernel/sql-translator/core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/SQLTranslatorRuleTest.java, kernel/sql-translator/core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/fixture/AlwaysFailedSQLTranslator.java, kernel/sql-translator/core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/fixture/ConvertToUpperCaseSQLTranslator.java, kernel/sql-translator/provider/jooq/pom.xml, kernel/sql-translator/provider/jooq/src/main/java/org/apache/shardingsphere/sqltranslator/jooq/JooQSQLTranslator.java, kernel/sql-translator/provider/native/src/main/java/org/apache/shardingsphere/sqltranslator/natived/NativeSQLTranslator.java
- Minor refactor SQLTranslator interface and implement logic
---
=> Minor refactor SQLTranslator interface and implement logic

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/version/MetaDataVersion.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/DatabaseBasedPersistService.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/datasource/NewDataSourceNodePersistService.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/datasource/NewDataSourceUnitPersistService.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/config/database/rule/NewDatabaseRulePersistService.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/schema/NewTableMetaDataPersistService.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/builder/RuleConfigurationEventBuilder.java, mode/core/src/main/java/org/apache/shardingsphere/mode/subsciber/NewConfigurationChangedSubscriber.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterModeContextManager.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/metadata/watcher/NewMetaDataChangedWatcher.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/NewContextManagerSubscriberFacade.java, mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/NewStandaloneContextManagerBuilder.java, mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/NewStandaloneModeContextManager.java
=> Fix miss sharding rule problem when use Standalone mode

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/id/PipelineJobId.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/id/PipelineJobIdUtils.java, kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobId.java
- Refactor PipelineJobId.marshalSuffix to reduce consistency check job id length
---
=> Refactor PipelineJobId.marshalSuffix to reduce consistency check job id length

README.md
=> Update README.md, remove content related to Hacktoberfest 2022

test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema-postgresql.xml
Refer to https://github.com/apache/shardingsphere/actions/runs/7162669707/job/19500061278?pr=29339
=> Fix PostgreSQL DQL E2E failed.

parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java, parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractorTest.java
=> support extract table from function segment

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/enums/QuoteCharacter.java
=> Optimizing the performance of QuoteCharacter lookup.

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/MemoryPipelineChannelCreator.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/MultiplexMemoryPipelineChannel.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractSeparablePipelineJob.java
- Fix sonar issue of MemoryPipelineChannelCreator and AbstractSeparablePipelineJob
---
=> Fix sonar issue of pipeline

kernel/sql-translator/distsql/handler/src/main/java/org/apache/shardingsphere/sqltranslator/distsql/handler/update/AlterSQLTranslatorRuleStatementUpdater.java, kernel/sql-translator/distsql/handler/src/test/java/org/apache/shardingsphere/sqltranslator/distsql/handler/update/AlterSQLTranslatorRuleStatementUpdaterTest.java, kernel/sql-translator/distsql/parser/src/main/antlr4/imports/sqltranslator/BaseRule.g4, kernel/sql-translator/distsql/parser/src/main/antlr4/imports/sqltranslator/RALStatement.g4, kernel/sql-translator/distsql/parser/src/main/java/org/apache/shardingsphere/sqltranslator/distsql/parser/core/SQLTranslatorDistSQLStatementVisitor.java, kernel/sql-translator/distsql/statement/src/main/java/org/apache/shardingsphere/sqltranslator/distsql/statement/updateable/AlterSQLTranslatorRuleStatement.java, kernel/transaction/distsql/handler/src/main/java/org/apache/shardingsphere/transaction/distsql/handler/update/AlterTransactionRuleStatementUpdater.java
=> Refactor DistSQL implementation for SQL translator

features/sharding/distsql/parser/src/main/antlr4/imports/sharding/Keyword.g4, features/sharding/distsql/parser/src/main/antlr4/sharding/org/apache/shardingsphere/distsql/parser/autogen/ShardingDistSQLStatement.g4, features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java, parser/distsql/engine/src/main/antlr4/imports/Keyword.g4, parser/distsql/engine/src/main/antlr4/imports/RALStatement.g4, parser/distsql/engine/src/main/antlr4/org/apache/shardingsphere/distsql/parser/autogen/KernelDistSQLStatement.g4, parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java, parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/statement/ral/queryable/ShowKeyGenerateAlgorithmImplementationsStatement.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowKeyGenerateAlgorithmImplementationsExecutor.java, proxy/backend/core/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.ral.query.QueryableRALExecutor, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/fixture/DistSQLKeyGenerateAlgorithmImplementationsFixture.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowKeyGenerateAlgorithmImplementationsExecutorTest.java, proxy/backend/core/src/test/resources/META-INF/services/org.apache.shardingsphere.keygen.core.algorithm.KeyGenerateAlgorithm
For #28984 .
- refactor "SHOW KEY GENERATE ALGORITHM IMPLEMENTATIONS" module
---
=> refactor "SHOW KEY GENERATE ALGORITHM IMPLEMENTATIONS" module

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4, test/it/parser/src/main/resources/case/dal/explain.xml, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dal/explain.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #29311.
- Fix mysql comment sql
- Add test sql
---
=> Fix mysql comment sql

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #29415.
- Fix mysql notExpression ClassCastException
- Add test sql
---
=> Fix mysql notExpression ClassCastException

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/registrycenter/repository/item/PipelineJobItemErrorMessageGovernanceRepository.java, test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/registrycenter/repository/PipelineGovernanceFacadeTest.java
- Fix job item error message clean: node not created in repository
---
=> Fix job item error message clean: node not created in repository

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/InventoryDumper.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/preparer/inventory/InventoryRecordsCountCalculator.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/importer/CDCImporter.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/importer/sink/CDCSocketSink.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/prepare/CDCJobPreparer.java, proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/CDCChannelInboundHandler.java
Ref #22500
Fixes #29274.
- Fix drop streaming failed
- Adjust CDC thread wait intervals
- Fixes needSort flag may not equals
---
=> Fix drop streaming failed and improve CDC inventory task thread wait intervals

agent/pom.xml, distribution/proxy/src/main/release-docs/LICENSE, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java, infra/common/src/main/java/org/apache/shardingsphere/infra/rule/identifier/type/TableNamesMapper.java, pom.xml
Ref #29432 
- Remove the dependency on commons-collections4.
---
=> Remove the dependency on commons-collections4.

kernel/schedule/core/pom.xml, kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/StatisticsContextManagerLifecycleListener.java, kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/StatisticsJobWorker.java, kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/StatisticsScheduleCollector.java, kernel/schedule/core/src/main/resources/META-INF/services/org.apache.shardingsphere.mode.manager.listener.ContextManagerLifecycleListener, kernel/schedule/core/src/test/java/org/apache/shardingsphere/schedule/core/job/statistics/ShardingSphereStatisticsCollectorFixture.java, kernel/schedule/core/src/test/java/org/apache/shardingsphere/schedule/core/job/statistics/StatisticsScheduleCollectorTest.java, kernel/schedule/core/src/test/resources/META-INF/services/org.apache.shardingsphere.infra.metadata.statistics.collector.ShardingSphereStatisticsCollector, kernel/schedule/pom.xml, proxy/backend/core/pom.xml
- Move ShardingSphere statistics to kernel schedule module
---
=> Move ShardingSphere statistics to kernel schedule module

kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/StatisticsCollectContextManagerLifecycleListener.java, kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/StatisticsCollectJobWorker.java, kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/StatisticsCollectScheduler.java, kernel/schedule/core/src/main/resources/META-INF/services/org.apache.shardingsphere.mode.manager.listener.ContextManagerLifecycleListener, kernel/schedule/core/src/test/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/StatisticsCollectSchedulerTest.java, kernel/schedule/core/src/test/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/StatisticsCollectorFixture.java, kernel/schedule/core/src/test/resources/META-INF/services/org.apache.shardingsphere.infra.metadata.statistics.collector.ShardingSphereStatisticsCollector
- Minor refactor for statistics collect job
---
=> Minor refactor for statistics collect job

kernel/sql-federation/api/src/main/java/org/apache/shardingsphere/sqlfederation/api/config/SQLFederationRuleConfiguration.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/rule/builder/DefaultSQLFederationRuleConfigurationBuilder.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/yaml/config/YamlSQLFederationRuleConfiguration.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/yaml/swapper/NewYamlSQLFederationRuleConfigurationSwapper.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/yaml/swapper/YamlSQLFederationRuleConfigurationSwapper.java, kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngineTest.java, kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/engine/fixture/rule/SQLFederationDeciderRuleMatchFixture.java, kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/engine/fixture/rule/SQLFederationDeciderRuleNotMatchFixture.java, kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/yaml/swapper/NewYamlSQLFederationRuleConfigurationSwapperTest.java, kernel/sql-federation/distsql/handler/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/handler/query/ShowSQLFederationRuleExecutor.java, kernel/sql-federation/distsql/handler/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/handler/update/AlterSQLFederationRuleStatementUpdater.java, kernel/sql-federation/distsql/handler/src/test/java/org/apache/shardingsphere/sqlfederation/distsql/handler/query/ShowSQLFederationRuleExecutorTest.java, kernel/sql-federation/distsql/handler/src/test/java/org/apache/shardingsphere/sqlfederation/distsql/handler/update/AlterSQLFederationRuleStatementUpdaterTest.java, kernel/sql-federation/distsql/parser/src/main/antlr4/imports/sql-federation/Keyword.g4, kernel/sql-federation/distsql/parser/src/main/antlr4/imports/sql-federation/RALStatement.g4, kernel/sql-federation/distsql/parser/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/parser/core/SQLFederationDistSQLStatementVisitor.java, kernel/sql-federation/distsql/statement/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/statement/updatable/AlterSQLFederationRuleStatement.java, proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussSystemCatalogAdminQueryExecutorTest.java, test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/SQLRewriterIT.java
Ref #29464.
- Add sql federation allQueryUseSQLFederation conf
- Add sql federation distsql
- Support all query sql use sql federation
- Improve sql federation test
---
=> Support all query sql use sql federation

kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/MigrationJobAPI.java, mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java, mode/core/src/main/java/org/apache/shardingsphere/mode/manager/context/ConfigurationContextManager.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/RefreshDatabaseMetaDataUpdater.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/RefreshTableMetaDataUpdater.java
=> Splitting refresh table metadata and database metadata

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-database-metadata.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-database-metadata.en.md, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/util/SystemSchemaUtils.java, parser/distsql/engine/src/main/antlr4/imports/Keyword.g4, parser/distsql/engine/src/main/antlr4/imports/RALStatement.g4, parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java, parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/statement/ral/updatable/RefreshDatabaseMetaDataStatement.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/RefreshDatabaseMetaDataUpdater.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/RefreshDatabaseMetaDataUpdaterTest.java, test/e2e/sql/src/test/resources/cases/ral/ral-integration-refresh.xml
Fixes #29467.
- Enhance REFRESH DATABASE METADATA implements
- Update related test cases
- Update documents
---
=> Enhance REFRESH DATABASE METADATA implements

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/insert/keygen/engine/GeneratedKeyContextEngine.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/insert/keygen/engine/GeneratedKeyContextEngineTest.java
=> Fix generated key with upper case column name

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/data/DatabaseBackendHandlerFactory.java
=> Exclude database required DAL statements from unicast scenario

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/create-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
=> Add some keywords in the "CREATE TABLE" in ORACLE.

infra/common/src/test/java/org/apache/shardingsphere/infra/rule/identifier/type/TableNamesMapperTest.java
Fixes #26217.
- Add tests for:
---
=> add tests for TableNamesMapper (#26217)

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/export-database-configuration.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/export-database-configuration.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/import-database-configuration.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/import-database-configuration.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-database-metadata.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-database-metadata.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-table-metadata.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-table-metadata.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/set-dist-vairable.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/set-dist-vairable.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-compute-node-info.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-compute-node-info.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-compute-node-mode.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-compute-node-mode.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-dist-variable.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-dist-variable.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-rules-used-storage-unit.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-rules-used-storage-unit.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-table-metadata.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-table-metadata.en.md
=> fixes doc sort

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/parameter/builder/impl/StandardParameterBuilder.java
- Optimize StandardParameterBuilder logic
---
=> Optimize StandardParameterBuilder logic

kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/handler/CDCBackendHandler.java
- Recover DialectDatabaseMetaData.isSupportGlobalCSN in CDC
---
=> Recover DialectDatabaseMetaData.isSupportGlobalCSN in CDC

features/broadcast/distsql/parser/src/main/antlr4/imports/broadcast/Keyword.g4, features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/segment/strategy/KeyGenerateStrategySegment.java
=> Fix missing boolean literal in broadcast distsql

kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/job/progress/PipelineJobProgressDetectorTest.java
Fixes #28541.
Add tests for:
---
=> add tests for PipelineJobProgressDetectorTest #28541

examples/shardingsphere-parser-example/src/main/java/org/apache/shardingsphere/example/parser/mysql/statement/MySQLParserStatementExample.java, examples/shardingsphere-parser-example/src/main/java/org/apache/shardingsphere/example/parser/opengauss/statement/OpenGaussParserStatementExample.java, examples/shardingsphere-parser-example/src/main/java/org/apache/shardingsphere/example/parser/oracle/statement/OracleParserStatementExample.java, examples/shardingsphere-parser-example/src/main/java/org/apache/shardingsphere/example/parser/postgresql/statement/PostgreSQLParserStatementExample.java, examples/shardingsphere-parser-example/src/main/java/org/apache/shardingsphere/example/parser/sql92/statement/SQL92ParserStatementExample.java, examples/shardingsphere-parser-example/src/main/java/org/apache/shardingsphere/example/parser/sqlserver/statement/SQLServerParserStatementExample.java
Fixes https://github.com/apache/shardingsphere/actions/runs/7353096418/job/20018979383.
- fix example CI job error
---
=> fix parser example CI error

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/user/Grantee.java, infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/user/GranteeTest.java, kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/rule/AuthorityRule.java, kernel/authority/provider/database/src/main/java/org/apache/shardingsphere/authority/provider/database/privilege/DatabasePermittedAuthorityRegistry.java, kernel/authority/provider/simple/src/main/java/org/apache/shardingsphere/authority/provider/simple/privilege/AllPermittedAuthorityRegistry.java
=> Add accept method to Grantee

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/PLSQL.g4, test/it/parser/src/main/resources/case/ddl/create-trigger.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-trigger.xml
Ref #27119.
- Support Create Trigger with System Trigger
---
=> Support Create Trigger with System Trigger in Oracle

infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/YamlEngine.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/importer/CDCImporter.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportMetaDataExecutorTest.java
For #29590, fix nightly ci on windows https://github.com/apache/shardingsphere/actions/runs/7388988344
Revert LineBreak to getPlatformLineBreak() for YAMLEngine.
=> Revert YAML line break

.github/workflows/nightly-check.yml, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/show-implementations-of-spi.en.md
- fix dead link
- increase the memory of codeql
---
=> Fix : fix dead link

kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/channel/memory/MemoryPipelineChannelTest.java
- Remove SimpleMemoryPipelineChannelTest.assertFetchRecordsTimeoutCorrectly. It's not stable in nightly CI
---
=> Remove SimpleMemoryPipelineChannelTest.assertFetchRecordsTimeoutCorrectly

.github/workflows/nightly-check.yml
=> Refactor : update  the codeQL install command

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/PLSQL.g4, test/it/parser/src/main/resources/case/ddl/create-trigger.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-trigger.xml
add new line
Fixes #27119.
- Enhance Create Trigger Statement in Oracle
---
=> Enhance Create Trigger Statement in Oracle

kernel/authority/core/src/test/java/org/apache/shardingsphere/authority/rule/builder/DefaultAuthorityRuleConfigurationBuilderTest.java, kernel/authority/core/src/test/java/org/apache/shardingsphere/authority/yaml/swapper/NewYamlAuthorityRuleConfigurationSwapperTest.java, kernel/authority/core/src/test/java/org/apache/shardingsphere/authority/yaml/swapper/YamlAuthorityRuleConfigurationSwapperTest.java
=> Add test cases for authenticators & defaultAuthenticator

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/channel/memory/MemoryPipelineChannel.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/channel/memory/MemoryPipelineChannelTest.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/prepare/CDCJobPreparer.java, kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/preparer/MigrationJobPreparer.java
- Improve MemoryPipelineChannel.fetch
---
=> Improve MemoryPipelineChannel.fetch

infra/common/src/main/java/org/apache/shardingsphere/infra/config/database/impl/DataSourceProvidedDatabaseConfiguration.java
Fixes #29451.
- Fix NPE in DataSourceProvidedDatabaseConfiguration when `isInstanceConnectionAvailable` is true.
=> Fixes #29451, optimize DataSourceProvidedDatabaseConfiguration

kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/channel/memory/MemoryPipelineChannelTest.java
- Improve MemoryPipelineChannelTest for nightly CI
---
=> Improve MemoryPipelineChannelTest for nightly CI

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/ConditionValue.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueCompareOperatorGenerator.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/ConditionValueTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueCompareOperatorGeneratorTest.java
- Support null condition value routing
---
=> Support null condition value routing

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, test/it/parser/src/main/resources/case/dal/explain.xml, test/it/parser/src/main/resources/case/ddl/flashback-database.xml, test/it/parser/src/main/resources/sql/supported/dal/explain.xml, test/it/parser/src/main/resources/sql/supported/ddl/flashback-database.xml
Closes #27147 
All mentioned test cases added
=> Support parsing Oracle EXPLAIN PLAN sql(27147)

docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/broadcast.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/broadcast.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/encrypt.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/encrypt.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/mask.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/mask.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/mix.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/mix.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/readwrite-splitting.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/readwrite-splitting.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/shadow.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/shadow.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/sharding-cache.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/sharding-cache.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/single.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/single.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/sql-parser.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/sql-parser.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/sql-translator.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/sql-translator.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/transaction.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/transaction.en.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/sql-translator.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/sql-translator.en.md
- Add broadcast, sharding-cache and single java api doc
---
=> Add broadcast, sharding-cache and single java api doc

features/encrypt/distsql/statement/src/main/java/org/apache/shardingsphere/encrypt/distsql/segment/EncryptColumnItemSegment.java, features/encrypt/distsql/statement/src/main/java/org/apache/shardingsphere/encrypt/distsql/segment/EncryptColumnSegment.java, features/encrypt/distsql/statement/src/main/java/org/apache/shardingsphere/encrypt/distsql/segment/EncryptRuleSegment.java, features/mask/distsql/statement/src/main/java/org/apache/shardingsphere/mask/distsql/segment/MaskColumnSegment.java, features/mask/distsql/statement/src/main/java/org/apache/shardingsphere/mask/distsql/segment/MaskRuleSegment.java, features/readwrite-splitting/distsql/statement/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/segment/ReadwriteSplittingRuleSegment.java, features/shadow/distsql/statement/src/main/java/org/apache/shardingsphere/shadow/distsql/segment/ShadowAlgorithmSegment.java, features/shadow/distsql/statement/src/main/java/org/apache/shardingsphere/shadow/distsql/segment/ShadowRuleSegment.java, features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/segment/strategy/AuditStrategySegment.java, features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/segment/strategy/KeyGenerateStrategySegment.java, features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/segment/strategy/ShardingAuditorSegment.java, features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/segment/strategy/ShardingStrategySegment.java, features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/segment/table/AbstractTableRuleSegment.java, features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/segment/table/TableReferenceRuleSegment.java, kernel/single/distsql/statement/src/main/java/org/apache/shardingsphere/single/distsql/segment/SingleTableSegment.java, kernel/sql-federation/distsql/statement/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/segment/CacheOptionSegment.java, kernel/sql-parser/distsql/statement/src/main/java/org/apache/shardingsphere/parser/distsql/segment/CacheOptionSegment.java, kernel/transaction/distsql/statement/src/main/java/org/apache/shardingsphere/transaction/distsql/segment/TransactionProviderSegment.java, parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/segment/AlgorithmSegment.java, parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/segment/DataSourceSegment.java, parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/segment/DistSQLSegment.java, parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/segment/ReadOrWriteSegment.java, parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/segment/TransmissionRuleSegment.java
=> Add DistSQLSegment

test/e2e/sql/src/test/resources/cases/ddl/ddl-integration-alter-table.xml, test/e2e/sql/src/test/resources/cases/ddl/ddl-integration-create-index.xml, test/e2e/sql/src/test/resources/cases/ddl/ddl-integration-create-table.xml, test/e2e/sql/src/test/resources/cases/ddl/ddl-integration-drop-index.xml, test/e2e/sql/src/test/resources/cases/ddl/ddl-integration-drop-table.xml, test/e2e/sql/src/test/resources/cases/ddl/ddl-integration-truncate.xml
- Minor refactor for ddl e2e test case
---
=> Minor refactor for ddl e2e test case

parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtils.java, parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtilsTest.java
=> fix miss extracting projection function segment

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/ConstraintToken.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/TableToken.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/TokenUtils.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/BindingTableRule.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
- Remove toLowerCase and use CaseInsensitiveMap to replace LinkedHashMap
---
=> Remove toLowerCase and use CaseInsensitiveMap to replace LinkedHashMap

kernel/data-pipeline/scenario/cdc/core/src/test/java/org/apache/shardingsphere/data/pipeline/cdc/generator/CDCResponseUtilsTest.java
Fixes #28530 .
- add tests for CDCResponseUtils
---
=> add tests for CDCResponseUtils

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/Literals.g4, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
=> support chinese whitespace for oracle

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractSeparablePipelineJob.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/IncrementalTask.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/InventoryTask.java, kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJob.java, kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/metadata/processor/ConsistencyCheckJobConfigurationChangedProcessor.java, kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJob.java, kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/metadata/processor/MigrationJobConfigurationChangedProcessor.java, test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobTest.java
- Adjust thread pools scope from job item level to job level
---
=> Adjust thread pools scope from job item level to job level

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/config/processor/JobConfigurationChangedProcessEngine.java
Revoke code aca91c8d0fbe8dfc3e1baffbed6134437c55574c, it's need get sharding item before stop job.
- Get sharding items before stop job, because sharding items will be cleared after stop job.
---
=> Revoke JobConfigurationChangedProcessEngine code

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/SingleChannelConsumerImporter.java, kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLBinlogEventPacketDecoder.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/importer/CDCImporter.java
- Support for immediate update of other events, PlaceholderRecord need be ack too .
---
=> Improve pipeline incremental task persist position

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AbstractStatementAdapter.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java, jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/adapter/StatementAdapterTest.java, kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/implicit/ImplicitTransactionCallback.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
- Refactor proxy and jdbc adapter and add ImplicitTransactionCallback
---
=> Refactor proxy and jdbc adapter and add ImplicitTransactionCallback

features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/query/ShowEncryptAlgorithmImplementationsExecutor.java, features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/query/ShowMaskAlgorithmImplementationsExecutor.java, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ShowReadQueryLoadBalanceAlgorithmImplementationsExecutor.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/query/ShowShadowAlgorithmImplementationsExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowComputeNodesExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowKeyGenerateAlgorithmImplementationsExecutor.java
=> Refactor DistSQL getRows

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/ddl/impl/ShardingDropTableStatementValidator.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContext.java
- Fix drop sharding table exception when table name is uppercase
---
=> Fix drop sharding table exception when table name is uppercase

agent/core/src/main/java/org/apache/shardingsphere/agent/core/advisor/config/AdvisorConfigurationLoader.java, agent/core/src/main/java/org/apache/shardingsphere/agent/core/advisor/executor/type/ConstructorAdviceExecutor.java, agent/core/src/main/java/org/apache/shardingsphere/agent/core/advisor/executor/type/InstanceMethodAdviceExecutor.java, agent/core/src/main/java/org/apache/shardingsphere/agent/core/advisor/executor/type/StaticMethodAdviceExecutor.java, agent/core/src/main/java/org/apache/shardingsphere/agent/core/builder/AgentTransformer.java, agent/core/src/main/java/org/apache/shardingsphere/agent/core/builder/interceptor/impl/MethodAdvisorBuilderInterceptor.java, agent/core/src/main/java/org/apache/shardingsphere/agent/core/plugin/PluginLifecycleServiceManager.java, agent/core/src/main/java/org/apache/shardingsphere/agent/core/plugin/jar/PluginJarLoader.java, agent/core/src/main/java/org/apache/shardingsphere/agent/core/spi/AgentServiceLoader.java, agent/core/src/main/java/org/apache/shardingsphere/agent/core/util/AgentPreconditions.java, agent/plugins/core/src/main/java/org/apache/shardingsphere/agent/plugin/core/spi/PluginServiceLoader.java, agent/plugins/core/src/main/java/org/apache/shardingsphere/agent/plugin/core/util/PluginPreconditions.java
Fixes #29743.
-  https://sonarcloud.io/project/issues?resolved=false&id=apache_shardingsphere&open=AY0fjDjbEG2C8jSk5gaB
-  https://sonarcloud.io/project/issues?resolved=false&id=apache_shardingsphere&open=AY0fjDkxEG2C8jSk5gaF
-  https://sonarcloud.io/project/issues?resolved=false&id=apache_shardingsphere&open=AY0fjDkVEG2C8jSk5gaE
---
=> Fix sonar error

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/MySQLContainer.java, test/it/parser/src/main/resources/case/dml/select-window.xml, test/it/parser/src/main/resources/sql/supported/dml/select-window.xml
Fixes #29809.
- Fix npe cause by parse MySQL select window statement
- add sql parser test
---
=> Fix npe cause by parse MySQL select window statement

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/runtime/DataSourceEnvironment.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/composer/BatchE2EContainerComposer.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/BaseDMLE2EIT.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/BatchDMLE2EIT.java
- Refactor BatchDMLE2EIT logic and add MySQL rewriteBatchedStatements param
---
=> Refactor BatchDMLE2EIT logic and add MySQL rewriteBatchedStatements param

docs/document/content/user-manual/shardingsphere-proxy/yaml-config/rules.en.md
- Fix document SQL Translator link
---
=> Fix document SQL Translator link

kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/type/ShardingSpherePipelineDataSourceConfiguration.java
=> fix missing props for pipeline

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/BaseDMLE2EIT.java
- Refactor BaseDMLE2EIT to support order by in batch api test
---
=> Refactor BaseDMLE2EIT to support order by in batch api test

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
=> Fix local transaction auto commit in jdbc adapter.

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/group/DataRecordGroupEngine.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/group/DataRecordGroupEngineTest.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/task/E2EIncrementalTask.java
Related to #29776 
- Fix DataRecordGroupEngine mergeUpdate and mergeDelete
- Improve unit test of DataRecordGroupEngine
- Improve E2EIncrementalTask to generate more types of changes
---
=> Fix DataRecordGroupEngine mergeUpdate and mergeDelete

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/_index.en.md
Fixes #29850
fix the bad link
-
---
=> fix bug #29850

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/runtime/DataSourceEnvironment.java
- Add rewriteBatchedStatements param in DataSourceEnvironment to enable MySQL batch rewrite
---
=> Add rewriteBatchedStatements param in DataSourceEnvironment to enable MySQL batch rewrite

test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/DataSourceRecordConsumer.java
=> Improve CDCE2EIT

kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/CDCJob.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/importer/CDCImporter.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/prepare/CDCJobPreparer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/DataSourceRecordConsumer.java
- Improve consumption timeout in CDC E2E of PostgreSQL
- Refactor CDCImporter
---
=> Improve consumption timeout in CDC E2E of PostgreSQL

proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java
- Minor refactor for MySQLMultiStatementsHandler
---
=> Minor refactor for MySQLMultiStatementsHandler

agent/core/src/main/java/org/apache/shardingsphere/agent/core/plugin/jar/PluginJarLoader.java
- Refactor : extact variable to reduce the file transfer
---
=> Refactor : extact variable to reduce the file transfer

proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java
- Refactor MySQLMultiStatementsHandler logic
---
=> Refactor MySQLMultiStatementsHandler logic

features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/update/CreateBroadcastTableRuleExecutor.java, infra/common/src/main/java/org/apache/shardingsphere/infra/instance/mode/ModeContextManager.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/type/rdl/rule/engine/database/type/DropDatabaseRuleOperator.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/NewClusterModeContextManager.java, mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/NewStandaloneModeContextManager.java
Fix CI:
https://github.com/apache/shardingsphere/actions/runs/7715328335/job/21029893786
=> Fixes #29932, revert ModeContextManager.removeRuleConfiguration

features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleExecutor.java, features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropEncryptRuleExecutor.java, features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/UnusedAlgorithmFinder.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/AlterDefaultShadowAlgorithmExecutor.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/AlterShadowRuleExecutor.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropShadowRuleExecutor.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/UnusedAlgorithmFinder.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterDefaultShardingStrategyExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterShardingTableReferenceRuleExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterShardingTableRuleExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropDefaultShardingStrategyExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/UnusedAlgorithmFinder.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/UnusedAlgorithmFinderTest.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/type/rdl/rule/spi/database/DatabaseRuleAlterExecutor.java, kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/UnloadSingleTableExecutor.java
- Improve clear unused algorithms when alter database rule
---
=> Improve clear unused algorithms when alter database rule

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AbstractStatementAdapter.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
- Refactor isNeedImplicitCommitTransaction param for code reuse
---
=> Refactor isNeedImplicitCommitTransaction param for code reuse

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
=> Refactor the execution of batches in jdbc adapter

README.md
- remove the table detail part since it doesn't work
---
=> Remove : remove the table detail part since it doesn't work

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/column/ColumnValueReaderEngine.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/task/E2EIncrementalTask.java
- Read underlying value of BLOB and CLOB
---
=> Read underlying value of BLOB and CLOB

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AbstractStatementAdapter.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/commitrollback/ImplicitCommitTransactionTestCase.java
=> Fix jdbc auto commit in implicit commit transaction

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
=> Fix xa auto commit in executeQuery

.github/workflows/ci.yml, .github/workflows/e2e-agent.yml, .github/workflows/e2e-operation.yml, .github/workflows/e2e-sql.yml, .github/workflows/graalvm.yml, .github/workflows/nightly-build.yml, .github/workflows/nightly-check.yml, .github/workflows/nightly-ci.yml, .github/workflows/nightly-e2e-operation.yml, .github/workflows/nightly-sql-parser.yml, .github/workflows/required-check.yml, .github/workflows/required-reusable.yml, .github/workflows/schedule-report.yml
Fixes #29941.
- fix the workflow plugins warning
---
=> Fix : fix the workflow plugins warning

mode/core/src/main/java/org/apache/shardingsphere/mode/manager/context/ConfigurationContextManager.java
- Add filter DatabaseRule in alterRuleConfiguration method to avoid clear datasources in TransactionRule
---
=> Add filter DatabaseRule in alterRuleConfiguration method to avoid clear datasources in TransactionRule

infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/metadata/data/loader/MySQLMetaDataLoader.java
For #29816.
- Fix get view name SQL
---
=> Fix load table type from MySQL

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/datetime/IntervalShardingAlgorithmTest.java
For #29353.
- Refactor unit tests for IntervalShardingAlgorithm. The original test structure is too bloated and lacks unit testing for the time component of `java.sql.Date`. 
- Also for #28909 . Add verification for `java.lang.StringIndexOutOfBoundsException` phenomenon.
---
=> Refactor unit tests for IntervalShardingAlgorithm

infra/distsql-handler/pom.xml, infra/distsql-handler/src/test/java/org/apache/shardingsphere/distsql/handler/util/DatabaseNameUtilsTest.java
Fixes #29768 .
-
Added unit tests for DatabaseNameUtils
---
=> Added unit tests for DatabaseNameUtils

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4, parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/DMLStatement.g4, parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/OutputSegment.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/output/OutputClauseAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/output/ExpectedOutputClause.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/output/ExpectedOutputColumn.java, test/it/parser/src/main/resources/case/dml/delete.xml, test/it/parser/src/main/resources/case/dml/insert.xml, test/it/parser/src/main/resources/case/dml/update.xml, test/it/parser/src/main/resources/sql/supported/dml/delete.xml, test/it/parser/src/main/resources/sql/supported/dml/insert.xml
Fixes #29187.
- support output scalar_expression feature
- fix tableName get owner or databaseName issue
- support sql
```
1. INSERT INTO #temp (id, job_name, job_id, dynamic_filter_login,
dynamic_filter_hostname, dynamic_snapshot_location,
frequency_type,	frequency_interval, frequency_subday_type,
frequency_subday_interval, frequency_relative_interval, 
frequency_recurrence_factor, active_start_date,	active_end_date, 
active_start_time,active_end_time)
EXEC sp_helpdynamicsnapshot_job
2.  INSERT INTO cci_target WITH (TABLOCK)
SELECT TOP 300000 * FROM staging  // same with  insert_with_table_hint case
3.  INSERT INTO player (
name,
surname,
info
)
VALUES (
N'Ovidiu',
N'Cracium',
COMPRESS(N'{"sport":"Tennis","age": 28,"rank":1,"points":15258, …
```
=> Support parsing SQL Server INSERT INTO sql #29187

test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema-mysql.xml
=> Fix system schema query test

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilder.java, infra/expr/type/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParser.java, mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoader.java
=> Fix the issue where the current thread's class loader may fail to load resources.

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/window/WindowConverter.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDMLStatementVisitor.java, parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/WindowItemSegment.java
=> refactor window segment

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDMLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/FunctionSegment.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/window/WindowClauseAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/SelectStatementAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/window/ExpectedWindowClause.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/window/ExpectedWindowItem.java, test/it/parser/src/main/resources/case/dml/select-group-by.xml, test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/case/dml/select-window.xml
=> enhance window segment parser

infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/data/loader/OracleMetaDataLoader.java
For #29816.
- Implement load table type for Oracle
---
=> Implement load table type for Oracle

infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/metadata/data/loader/MySQLMetaDataLoader.java, infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/data/loader/OracleMetaDataLoader.java
=> Refactor variable name

kernel/transaction/type/xa/spi/src/main/java/org/apache/shardingsphere/transaction/xa/spi/SingleXAResource.java
=> Add map xa exception in SingleXAResource

infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/type/query/rql/ShowSPIImplementationsExecutor.java
=> Refactor ShowSPIImplementationsExecutor

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/ShardingConditions.java
- https://sonarcloud.io/project/issues?resolved=false&id=apache_shardingsphere&open=AYiNOMhnONYr_5YLXsHr&tab=how_to_fix
---
=> Fix sonar in ShardingConditions

test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/savepoint/MySQLSavePointTestCase.java, test/e2e/operation/transaction/src/test/resources/env/it-env.properties
=> Ignore failed save point test cases

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/Process.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/yaml/YamlProcess.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/yaml/swapper/YamlProcessSwapper.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/subscriber/NewProcessListChangedSubscriber.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/subscriber/ProcessListChangedSubscriber.java, mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/subscriber/ProcessListChangedSubscriberTest.java, proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowProcessListExecutorTest.java
- Refactor show processlist and kill logic
---
=> Refactor show processlist and kill logic

mode/core/src/main/java/org/apache/shardingsphere/mode/subsciber/RuleItemChangedSubscriber.java, mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/NewStandaloneContextManagerBuilder.java
=> Fix #30046

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/sharding/show-sharding-algorithm-implementations.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/sharding/show-sharding-algorithm-implementations.en.md, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingAlgorithmImplementationsResultRowBuilder.java, features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.engine.query.rql.spi.ShowSPIImplementationsResultRowBuilder, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingAlgorithmImplementationsResultRowBuilderTest.java, features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/query/rql/spi/ShowSPIImplementationsExecutor.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/query/rql/spi/ShowSPIImplementationsResultRowBuilder.java, infra/distsql-handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.engine.query.DistSQLQueryExecutor
=> Refactor SHOW SHARDING ALGORITHM IMPLEMENTATIONS

features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ShowReadQueryLoadBalanceAlgorithmPluginsResultRowBuilder.java, features/readwrite-splitting/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.executor.ral.plugin.ShowPluginsResultRowBuilder, features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ShowReadQueryLoadBalanceAlgorithmPluginsResultRowBuilderTest.java, features/readwrite-splitting/distsql/parser/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/parser/core/ReadwriteSplittingDistSQLStatementVisitor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingAlgorithmPluginsResultRowBuilder.java, features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.executor.ral.plugin.ShowPluginsResultRowBuilder, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingAlgorithmPluginsResultRowBuilderTest.java, features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/ral/plugin/ShowPluginsExecutor.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/ral/plugin/ShowPluginsResultRowBuilder.java, infra/distsql-handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.engine.query.DistSQLQueryExecutor, parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/statement/ral/queryable/show/ShowPluginsStatement.java
Move ShowPluginExecutor from RQL to RAL
=> Rename ShowPluginsExecutor and move from RQL to RAL

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/kernel/model/ExecutionGroupReportContext.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/Process.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/ProcessEngine.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/yaml/YamlProcess.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/yaml/swapper/YamlProcessSwapper.java, infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/process/yaml/swapper/YamlProcessListSwapperTest.java, infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/process/yaml/swapper/YamlProcessSwapperTest.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/executor/batch/BatchPreparedStatementExecutor.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java, jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java, jdbc/core/src/test/java/org/apache/shardingsphere/driver/executor/batch/BatchPreparedStatementExecutorTest.java, kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java, mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/subscriber/ProcessListChangedSubscriberTest.java, proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowProcessListExecutorTest.java
- Remove heldByConnection flag and call connect and disconnect in ShardingSphereConnection
---
=> Remove heldByConnection flag and call connect and disconnect in ShardingSphereConnection

test/it/parser/src/main/resources/case/dml/insert.xml, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/case/dml/update.xml, test/it/parser/src/main/resources/sql/supported/dml/insert.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/update.xml
Fixes #29193.
- support sql
```
1.  INSERT INTO [HR].[Employees]
(
[SSN]
, [FirstName]
, [LastName]
, [Salary]
)
VALUES
(
'990-00-6818'
, N'Kim'
, N'Abercrombie'
, $55415
)
2.  UPDATE HumanResources.Employee   
SET JobTitle = N'Executive'  
WHERE NationalIDNumber = 123456789  
IF @@ROWCOUNT = 0  
PRINT 'Warning: No rows were updated'  // remark  " IF @@ROWCOUNT = 0   PRINT 'Warning: No rows were updated' " do not parser , because it do not affect rows 
3. INSERT [SourceDatabase].[dbo].[SourceTable]
VALUES (1, N'Bob'),
(2, N'Susan')
4.  INSERT [DestinationDatabase].[dbo].[DestTable_InMem]
SELECT * FROM [SourceDatabase].[dbo].[SourceTable]
5.  SELECT
[req].[session_id],
[req].[start_time],
[req].[cpu_time] AS [cpu_time_ms],
OBJECT_NAME([ST].[objectid], …
```
=> Support parsing SQL Server INSERT INTO sql #29193

features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/Keyword.g4, features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/RALStatement.g4, features/encrypt/distsql/parser/src/main/antlr4/org/apache/shardingsphere/distsql/parser/autogen/EncryptDistSQLStatement.g4, features/encrypt/distsql/parser/src/main/java/org/apache/shardingsphere/encrypt/distsql/parser/core/EncryptDistSQLStatementVisitor.java, features/mask/distsql/parser/src/main/antlr4/imports/mask/Keyword.g4, features/mask/distsql/parser/src/main/antlr4/imports/mask/RALStatement.g4, features/mask/distsql/parser/src/main/antlr4/org/apache/shardingsphere/distsql/parser/autogen/MaskDistSQLStatement.g4, features/mask/distsql/parser/src/main/java/org/apache/shardingsphere/mask/distsql/parser/core/MaskDistSQLStatementVisitor.java, features/readwrite-splitting/distsql/parser/src/main/antlr4/imports/readwrite-splitting/Keyword.g4, features/readwrite-splitting/distsql/parser/src/main/antlr4/imports/readwrite-splitting/RALStatement.g4, features/readwrite-splitting/distsql/parser/src/main/antlr4/org/apache/shardingsphere/distsql/parser/autogen/ReadwriteSplittingDistSQLStatement.g4, features/readwrite-splitting/distsql/parser/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/parser/core/ReadwriteSplittingDistSQLStatementVisitor.java, features/shadow/distsql/parser/src/main/antlr4/imports/shadow/Keyword.g4, features/shadow/distsql/parser/src/main/antlr4/imports/shadow/RALStatement.g4, features/shadow/distsql/parser/src/main/antlr4/org/apache/shardingsphere/distsql/parser/autogen/ShadowDistSQLStatement.g4, features/shadow/distsql/parser/src/main/java/org/apache/shardingsphere/shadow/distsql/parser/core/ShadowDistSQLStatementVisitor.java, features/sharding/distsql/parser/src/main/antlr4/imports/sharding/Keyword.g4, features/sharding/distsql/parser/src/main/antlr4/imports/sharding/RALStatement.g4, features/sharding/distsql/parser/src/main/antlr4/sharding/org/apache/shardingsphere/distsql/parser/autogen/ShardingDistSQLStatement.g4, features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java, parser/distsql/engine/src/main/antlr4/imports/Keyword.g4, parser/distsql/engine/src/main/antlr4/imports/RALStatement.g4, parser/distsql/engine/src/main/antlr4/org/apache/shardingsphere/distsql/parser/autogen/KernelDistSQLStatement.g4, parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java
=> Refactor DistSQL syntax show xxx implementations to show xxx plugins

test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/deadlock/TransactionDeadlockTestCase.java
=> Fix transaction deadlock test case

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.en.md
For #30120 .
- Updates Known Implementation documentation for ShardingSphere JDBC Driver. The current documentation requires more information.
---
=> Updates Known Implementation documentation for ShardingSphere JDBC Driver

proxy/bootstrap/pom.xml
- Remove useless jdbc-core dependency in Proxy bootstrap module
---
=> Remove useless jdbc-core dependency in Proxy bootstrap module

docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/narayana.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/narayana.en.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.en.md
For #30102.
- Updates Narayana Implementation documentation for CoreEnvironmentBean.nodeIdentifier .
- Also fixes #25543 . Documentation needs to document what happened with #25543 .
---
=> Updates Narayana Implementation documentation for CoreEnvironmentBean.nodeIdentifier

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/provider/ShardingConvertRuleConfigurationProvider.java, proxy/backend/core/src/test/resources/conf/convert/config-sharding.yaml, proxy/backend/core/src/test/resources/expected/convert-sharding.yaml
=> Fix unexpected line separators in ConvertYamlConfiguration

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4
Fixes #27145.
- Support parsing Oracle EXPLAIN PLAN sql #27145
---
=> Support parsing Oracle EXPLAIN PLAN sql #27145

features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/update/DropBroadcastTableRuleExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/checker/ShardingTableRuleStatementChecker.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterShardingTableReferenceRuleExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateShardingTableReferenceRuleExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableReferenceExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleExecutor.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/util/CollectionUtils.java
Add CollectionUtils for DistSQL.
=> Extract public method `containsIgnoreCase`

features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/rule/ReadwriteSplittingRule.java, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ShowStatusFromReadwriteSplittingRulesExecutor.java, features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ShowStatusFromReadwriteSplittingRulesExecutorTest.java, features/readwrite-splitting/distsql/statement/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/statement/ShowStatusFromReadwriteSplittingRulesStatement.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/enums/ShardingStrategyType.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterDefaultShardingStrategyExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateDefaultShardingStrategyExecutor.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/util/CollectionUtils.java
=> Refactor ShowStatusFromReadwriteSplittingRulesExecutor

docs/document/content/user-manual/shardingsphere-jdbc/java-api/_index.en.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.en.md
=> Fix document issue

features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/checker/ReadwriteSplittingRuleStatementChecker.java, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/exception/InvalidStorageUnitStatusException.java, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/exception/MissingRequiredReadStorageUnitException.java, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/AlterReadwriteSplittingStorageUnitStatusExecutor.java, features/readwrite-splitting/distsql/parser/src/main/antlr4/imports/readwrite-splitting/RALStatement.g4, features/readwrite-splitting/distsql/parser/src/main/antlr4/imports/readwrite-splitting/RDLStatement.g4, features/readwrite-splitting/distsql/parser/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/parser/core/ReadwriteSplittingDistSQLStatementVisitor.java, features/readwrite-splitting/distsql/statement/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/statement/AlterReadwriteSplittingStorageUnitStatusStatement.java, mode/core/src/main/java/org/apache/shardingsphere/mode/storage/service/StorageNodeStatusService.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/UpdatableRALStatementAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/updatable/AlterReadwriteSplittingStorageUnitStatusStatementAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ral/AlterReadwriteSplittingStorageUnitStatusStatementTestCase.java, test/it/parser/src/main/resources/case/ral/updatable.xml
- remove dependency of `mode.event`
- simplify the code
=> Refactor AlterReadwriteSplittingStorageUnitStatusExecutor

kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/datasource/checker/dialect/MySQLXATransactionPrivilegeChecker.java, kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/exception/XATransactionCheckPrivilegeFailedException.java
=> Add advice message in XATransactionCheckPrivilegeFailedException

features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/EncryptRuleConfigurationYamlIT.java, test/it/optimizer/src/test/resources/converter/select-special-function.xml
- Fix unit test in test it module
---
=> Fix unit test in test it module

infra/url/type/absolutepath/src/test/java/org/apache/shardingsphere/infra/url/absolutepath/AbsolutePathURLLoaderTest.java, infra/url/type/classpath/src/test/java/org/apache/shardingsphere/infra/url/classpath/ClassPathURLLoaderTest.java
Fixes #30234.
- org/apache/shardingsphere/infra/url/absolutepath/AbsolutePathURLLoaderTest.java
- org/apache/shardingsphere/infra/url/classpath/ClassPathURLLoaderTest.java
---
=> Improve shardingsphere.infra.url test cases

docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.en.md, docs/document/content/user-manual/shardingsphere-proxy/observability/_index.cn.md, docs/document/content/user-manual/shardingsphere-proxy/observability/_index.en.md
For #30225.
- Update observability doc
---
=> Update observability doc

jdbc/src/test/java/org/apache/shardingsphere/driver/api/yaml/YamlJDBCConfigurationTest.java
Fixes #30158.
- https://github.com/apache/shardingsphere/issues/30158
---
=> Add test case on YamlJDBCConfiguration.rebuild()

features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/query/ShowBroadcastTableRuleExecutorTest.java, features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/query/ShowEncryptRuleExecutorTest.java, features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/query/ShowMaskRuleExecutorTest.java, features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ShowReadwriteSplittingRuleExecutorTest.java, features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ShowStatusFromReadwriteSplittingRulesExecutorTest.java, features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowDefaultShadowAlgorithmExecutorTest.java, features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowAlgorithmsExecutorTest.java, features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowRuleExecutorTest.java, features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowTableRulesExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowDefaultShardingStrategyExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingAlgorithmExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingAuditorsExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingKeyGeneratorExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableNodesExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableReferenceRuleExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRuleExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRulesUsedAlgorithmExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRulesUsedAuditorExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRulesUsedKeyGeneratorExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowUnusedShardingAlgorithmsExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowUnusedShardingAuditorsExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowUnusedShardingKeyGeneratorExecutorTest.java, kernel/global-clock/distsql/handler/src/test/java/org/apache/shardingsphere/globalclock/distsql/handler/query/ShowGlobalClockRuleExecutorTest.java, kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/query/ShowDefaultSingleTableStorageUnitExecutorTest.java, kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/query/ShowSingleTableExecutorTest.java, kernel/sql-federation/distsql/handler/src/test/java/org/apache/shardingsphere/sqlfederation/distsql/handler/query/ShowSQLFederationRuleExecutorTest.java, kernel/sql-parser/distsql/handler/src/test/java/org/apache/shardingsphere/parser/distsql/handler/query/ShowSQLParserRuleExecutorTest.java, kernel/sql-translator/distsql/handler/src/test/java/org/apache/shardingsphere/sqltranslator/distsql/handler/query/ShowSQLTranslatorRuleExecutorTest.java, kernel/traffic/distsql/handler/src/test/java/org/apache/shardingsphere/traffic/distsql/handler/query/ShowTrafficRuleExecutorTest.java, kernel/transaction/distsql/handler/src/test/java/org/apache/shardingsphere/transaction/distsql/handler/query/ShowTransactionRuleExecutorTest.java
Fixes #30083.
-
Refactor test cases that can use the Dist SQL Query Execute Engine
---
=> Refactor DistSQLExecutor's test cases

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/DockerStorageContainer.java
- Modify maximumPoolSize to avoid can not get connection exception
---
=> Modify maximumPoolSize to avoid can not get connection exception

agent/plugins/core/src/main/java/org/apache/shardingsphere/agent/plugin/core/context/PluginContext.java, agent/plugins/core/src/main/java/org/apache/shardingsphere/agent/plugin/core/util/ShardingSphereDriverUtils.java, agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/exporter/impl/jdbc/JDBCMetaDataInfoExporter.java, agent/plugins/metrics/core/src/main/java/org/apache/shardingsphere/agent/plugin/metrics/core/exporter/impl/jdbc/JDBCStateExporter.java
Fixes #30256.
- Refactor ShardingSphereDriverUtils
---
=> Refactor ShardingSphereDriverUtils

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/encrypt/show-encrypt-algorithm-implementations.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/encrypt/show-encrypt-algorithm-implementations.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/mask/show-mask-algorithm-implementations.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/mask/show-mask-algorithm-implementations.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/readwrite-splitting/show-read-query-load-balance-algorithm-implementations.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/readwrite-splitting/show-read-query-load-balance-algorithm-implementations.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/shadow/show-shadow-algorithm-implementations.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/shadow/show-shadow-algorithm-implementations.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/sharding/show-sharding-algorithm-implementations.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/sharding/show-sharding-algorithm-implementations.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/show-implementations-of-spi.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/show-implementations-of-spi.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/show-key-generate-algorithm-implementations.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-implementation/show-key-generate-algorithm-implementations.en.md
=> Update show SPI plugins docs

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4
Ref #30249.
- Revise BaeseRule for PR 30249
---
=> Revise BaeseRule for PR 30249

agent/core/src/test/java/org/apache/shardingsphere/preconditions/AgentPreconditionsTest.java
Fixes #30264.
- https://github.com/apache/shardingsphere/issues/30264
---
=> Add test cases for AgentPreconditions

infra/url/core/src/test/java/org/apache/shardingsphere/infra/url/core/ShardingSphereURLLoadEngineTest.java
Fixes #30153.
- https://github.com/apache/shardingsphere/issues/30153
---
=> Add test case for ShardingSphereURLLoadEngine

agent/plugins/core/src/test/java/org/apache/shardingsphere/agent/plugin/core/preconditions/PluginPreconditionsTest.java
Fixes #30267.
- https://github.com/apache/shardingsphere/issues/30267
---
=> Add test cases for PluginPreconditions

agent/core/src/test/java/org/apache/shardingsphere/yaml/AgentYamlEngineTest.java
Fixes #30265.
- https://github.com/apache/shardingsphere/issues/30265
---
=> Add test cases for AgentYamlEngine

docs/document/content/user-manual/shardingsphere-proxy/yaml-config/authority.cn.md, docs/document/content/user-manual/shardingsphere-proxy/yaml-config/authority.en.md
Add description that username and hostname are case-insensitive
=> Update authority doc

kernel/data-pipeline/dialect/opengauss/src/test/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPluginTest.java
=> Refactor MppdbDecodingPluginTest

test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_sys_data_for_og.xml, test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_sys_data_for_pg.xml, test/e2e/sql/src/test/resources/cases/dql/dataset/tbl/select_sys_data_for_og.xml, test/e2e/sql/src/test/resources/cases/dql/dataset/tbl/select_sys_data_for_pg.xml, test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-expression.xml, test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema-opengauss.xml, test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema-postgresql.xml, test/e2e/sql/src/test/resources/cases/rql/rql-integration-count.xml, test/e2e/sql/src/test/resources/cases/rql/rql-integration-show.xml, test/e2e/sql/src/test/resources/env/scenario/tbl/data/actual/dataset.xml, test/e2e/sql/src/test/resources/env/scenario/tbl/data/actual/init-sql/h2/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/tbl/data/actual/init-sql/mysql/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/tbl/data/actual/init-sql/opengauss/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/tbl/data/actual/init-sql/postgresql/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/tbl/data/expected/dataset.xml, test/e2e/sql/src/test/resources/env/scenario/tbl/data/expected/init-sql/h2/01-expected-init.sql, test/e2e/sql/src/test/resources/env/scenario/tbl/data/expected/init-sql/mysql/01-expected-init.sql, test/e2e/sql/src/test/resources/env/scenario/tbl/data/expected/init-sql/opengauss/01-expected-init.sql, test/e2e/sql/src/test/resources/env/scenario/tbl/data/expected/init-sql/postgresql/01-expected-init.sql
Ref #21286.
- Remove tbl scenario non-standard table structure
- Adjust some test cases
---
=> Remove tbl scenario non-standard table structure

parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
- Refactored repeat code in the function visit
- In the visitor of SQL Server，there are many repeat parsing codes. Integrate these codes to form a method.
---
=> Refactored repeat code in the function visit

features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/query/ShowBroadcastTableRuleExecutorTest.java, features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/query/ShowEncryptRuleExecutorTest.java, features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/query/ShowMaskRuleExecutorTest.java, features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ShowReadwriteSplittingRuleExecutorTest.java, features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowDefaultShadowAlgorithmExecutorTest.java, features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowAlgorithmsExecutorTest.java, features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowRuleExecutorTest.java, features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowTableRulesExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowDefaultShardingStrategyExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingAlgorithmExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingAuditorsExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingKeyGeneratorExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableNodesExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableReferenceRuleExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRuleExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRulesUsedAlgorithmExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRulesUsedAuditorExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRulesUsedKeyGeneratorExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowUnusedShardingAlgorithmsExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowUnusedShardingAuditorsExecutorTest.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowUnusedShardingKeyGeneratorExecutorTest.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/aware/DistSQLExecutorAwareSetter.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/query/DistSQLQueryExecuteEngine.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/update/DistSQLUpdateExecuteEngine.java, kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/query/ShowDefaultSingleTableStorageUnitExecutorTest.java, kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/query/ShowSingleTableExecutorTest.java
Fixes #30301.
Check database when query/update database rule
=> Refactor DistSQLExecutorAwareSetter and DistSQLExecutor

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/PaginationContext.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/engine/RowNumberPaginationContextEngine.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/pagination/rownum/ExpressionRowNumberValueSegment.java, parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/pagination/rownum/ExpressionRowNumberValueSegmentTest.java
=> support oracle page with parameter cal expression

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/channel/MultiplexPipelineChannel.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/channel/memory/MemoryPipelineChannelCreator.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/ImporterConfiguration.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/PipelineTaskUtils.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/channel/MultiplexPipelineChannelTest.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/channel/memory/MemoryPipelineChannelCreatorTest.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/prepare/CDCJobPreparer.java, kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/preparer/MigrationJobPreparer.java
- Refactor pipeline channel
---
=> Refactor pipeline channel

docs/document/content/user-manual/error-code/sql-error-code.cn.md, docs/document/content/user-manual/error-code/sql-error-code.en.md, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/exception/FileIOException.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportMetaDataExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/ExportUtils.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportDatabaseConfigurationExecutorTest.java
=> Refactor FileIOException

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/migration/alter-migration-rule.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/migration/alter-migration-rule.en.md, docs/document/content/user-manual/shardingsphere-proxy/migration/build.cn.md, docs/document/content/user-manual/shardingsphere-proxy/migration/build.en.md
- Update ALTER MIGRATION RULE DistSQL doc
---
=> Update ALTER MIGRATION RULE DistSQL doc

infra/util/src/main/java/org/apache/shardingsphere/infra/util/directory/ClasspathResourceDirectoryReader.java, infra/util/src/test/java/org/apache/shardingsphere/infra/util/directory/ClasspathResourceDirectoryReaderTest.java, mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoader.java
=> Refactor JDBCRepositorySQLLoader.

docs/document/content/test-manual/module-test/parser-test.cn.md, docs/document/content/test-manual/module-test/parser-test.en.md, docs/document/content/test-manual/module-test/rewrite-test.cn.md, docs/document/content/test-manual/module-test/rewrite-test.en.md
Fixes #30312.
- Adjust parser, rewrite the module positions in the document.
---
=> Adjust parser, rewrite the module positions in the document.

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/user/ShardingSphereUser.java, kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/rule/builder/DefaultAuthorityRuleConfigurationBuilder.java, kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/yaml/config/YamlUserConfiguration.java, kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/yaml/swapper/YamlUserSwapper.java, kernel/authority/core/src/test/java/org/apache/shardingsphere/authority/yaml/swapper/YamlEngineUserConfigurationTest.java
=> Add admin field to ShardingSphereUser

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/BaseDMLE2EIT.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/BatchDMLE2EIT.java
- Minor refactor for BatchDMLE2EIT
---
=> Minor refactor for BatchDMLE2EIT

infra/util/src/main/java/org/apache/shardingsphere/infra/util/directory/ClasspathResourceDirectoryReader.java, infra/util/src/test/java/org/apache/shardingsphere/infra/util/directory/ClasspathResourceDirectoryReaderTest.java, infra/util/src/test/resources/yaml/fixture/fixture.yaml
=> Fix the issue of returning a short path when reading a nested directory.

test/e2e/sql/src/test/resources/cases/rql/rql-integration-count.xml, test/e2e/sql/src/test/resources/cases/rql/rql-integration-show.xml, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/data/actual/dataset.xml, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/data/actual/init-sql/h2/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/data/actual/init-sql/h2/actual-read_ds_0-init.sql, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/data/actual/init-sql/h2/actual-write_ds_0-init.sql, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/data/actual/init-sql/mysql/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/data/actual/init-sql/opengauss/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/data/actual/init-sql/postgresql/01-actual-init.sql, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/data/expected/dataset.xml, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/data/expected/init-sql/h2/01-expected-init.sql, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/data/expected/init-sql/mysql/01-expected-init.sql, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/data/expected/init-sql/opengauss/01-expected-init.sql, test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/data/expected/init-sql/postgresql/01-expected-init.sql
Ref #21286.
- Remove dbtbl_with_readwrite_splitting non-standard table
---
=> Remove dbtbl_with_readwrite_splitting non-standard table

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/YamlDatabaseConfigurationImportExecutor.java
For #30190.
- YamlRuleConfiguration to RuleConfiguration conversion calls spi.
---
=> Refactor YamlDatabaseConfigurationImportExecutor

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSet.java, kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/OptimizerContext.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/planner/OptimizerPlannerContext.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/context/planner/OptimizerPlannerContextFactory.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/schema/SQLFederationDatabase.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/schema/SQLFederationSchema.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/planner/rule/transformation/PushFilterIntoScanRule.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/planner/rule/transformation/PushProjectIntoScanRule.java, kernel/sql-federation/optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/context/OptimizerContextTest.java
- Remove toLowerCase and use CaseInsensitiveMap, CaseInsensitiveSet
---
=> Remove toLowerCase and use CaseInsensitiveMap, CaseInsensitiveSet

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java, kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java
- Support show processlist and kill for sql federation
---
=> Support show processlist and kill for sql federation

test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/readwritesplitting/ReadwriteSplittingInTransactionTestCase.java
=> Fix force startup e2e

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/provider/ShardingImportRuleConfigurationProvider.java, features/sharding/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.engine.update.ral.rule.spi.database.ImportRuleConfigurationProvider, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/provider/ShardingImportRuleConfigurationProviderTest.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/update/ral/rule/spi/database/ImportRuleConfigurationProvider.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/YamlDatabaseConfigurationImportExecutor.java
For #30190.
- Add ImportRuleConfigurationProvider
- Add ShardingImportRuleConfigurationProvider
---
=> Add ImportRuleConfigurationProvider

.gitignore, .idea/vcs.xml
Click the ID in commit message can direct to Pull Request page.
[Screencast from 03-05-2024 10:58:17 PM.webm](https://github.com/apache/shardingsphere/assets/20503072/e1dc631d-ad44-4848-81ea-c29b0205f7f1)
=> Configure IDEA Issue navigation for ShardingSphere

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DCLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4, parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/ddl/OracleDropDatabaseStatement.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalSQLParserIT.java, test/it/parser/src/main/resources/sql/supported/dcl/create-user.xml, test/it/parser/src/main/resources/sql/supported/dcl/drop-user.xml
link  #29988.
- Fix oracle parser create user error [CREATE USER](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CREATE-USER.html#GUID-F0246961-558F-480B-AC0F-14B50134621C)
- delete the wrong sql case about oracle
+ Oracle does not support drop user with host
+ Oracle does not support create user with role
---
=> Fix oracle parser create user error

features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/provider/ReadwriteSplittingImportRuleConfigurationProvider.java, features/readwrite-splitting/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.engine.update.ral.rule.spi.database.ImportRuleConfigurationProvider, features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/provider/ReadwriteSplittingImportRuleConfigurationProviderTest.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/YamlDatabaseConfigurationImportExecutor.java
For #30190 .
- Add ReadwriteSplittingImportRuleConfigurationProvider
---
=> Add ReadwriteSplittingImportRuleConfigurationProvider

features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/provider/EncryptImportRuleConfigurationProvider.java, features/encrypt/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.engine.update.ral.rule.spi.database.ImportRuleConfigurationProvider, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/YamlDatabaseConfigurationImportExecutor.java
For #30190 .
- Add EncryptImportRuleConfigurationProvider
---
=> Add EncryptImportRuleConfigurationProvider

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/manager/SystemSchemaManager.java
=> Fix SystemSchemaManager init error.

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DCLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/Literals.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/PLSQL.g4, parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalSQLParserIT.java, test/it/parser/src/main/resources/sql/supported/ddl/create-cluster.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-control-file.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-java.xml
link #29988.
- Fix alter materialized view log sql syntax parser error
- Fix create cluster sql syntax parser error
- Fix create controlfile sql syntax  parser error
- Fix create role sql syntax parser error
- Fix create user globally syntax parser error
---
=> Fix parser alter materialized view log、 create cluster、create controlfile 、create role sql syntax

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractSeparablePipelineJob.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/persist/PipelineJobProgressPersistService.java
- Improve job progress force persisting
---
=> Improve job progress force persisting

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dal/show/EncryptShowCreateTableMergedResult.java
For #29816.
- when show  create table for encrypted view, retuen original value
---
=> Fix show create table for encrypted view

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDALStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/dal/MySQLShowProcessListStatement.java, proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLAdminExecutorCreator.java, proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowProcessListExecutor.java, proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLAdminExecutorCreatorTest.java, proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowProcessListExecutorTest.java
=> support show full processlist

features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/provider/MaskImportRuleConfigurationProvider.java, features/mask/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.engine.update.ral.rule.spi.database.ImportRuleConfigurationProvider, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/YamlDatabaseConfigurationImportExecutor.java
For #30190.
- Add MaskImportRuleConfigurationProvider
---
=> Add MaskImportRuleConfigurationProvider

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/RecordSingleTableInventoryCalculator.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/sink/type/PipelineDataSourceSink.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/InventoryDumper.java, kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLIncrementalDumper.java, kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLCommandPacketDecoder.java, kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/OpenGaussWALDumper.java, kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPlugin.java, kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/PostgreSQLWALDumper.java, kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPlugin.java
- Add HighFrequencyInvocation annotation for pipeline
---
=> Add HighFrequencyInvocation annotation for pipeline

docs/document/content/user-manual/shardingsphere-proxy/yaml-config/authority.cn.md, docs/document/content/user-manual/shardingsphere-proxy/yaml-config/authority.en.md, kernel/authority/core/src/main/java/org/apache/shardingsphere/authority/checker/AuthorityChecker.java
=> Check admin user in AuthorityChecker.

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/standard/SQLRouteTest.java
- Remove useless unit test in SQLRouteTest
---
=> Remove useless unit test in SQLRouteTest

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingAlgorithmExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingAuditorExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingKeyGeneratorExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleExecutor.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/update/rdl/rule/engine/database/DatabaseRuleDefinitionExecuteEngine.java
=> Fix NPE when drop rule while current rule is null

kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/provider/SingleImportRuleConfigurationProvider.java, kernel/single/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.engine.update.ral.rule.spi.database.ImportRuleConfigurationProvider, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/YamlDatabaseConfigurationImportExecutor.java
For #30190 .
- Add SingleImportRuleConfigurationProvider
---
=> Add SingleImportRuleConfigurationProvider

kernel/data-pipeline/dialect/opengauss/pom.xml
=> Remove unnecessary exclusion of gson

docs/document/content/user-manual/error-code/sql-error-code.cn.md, docs/document/content/user-manual/error-code/sql-error-code.en.md
- Remove useless error code in doc
---
=> Remove useless error code in doc

kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableExecutor.java
Fixes #30501.
- Fixed error when loading single table without single rule
---
=> Fixed error when loading single table without single rule

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/BroadcastSQLRouter.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/context/EncryptSQLRewriteContextDecorator.java, features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/route/ReadwriteSplittingSQLRouter.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/ShadowSQLRouter.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/context/ShardingSQLRewriteContextDecorator.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/ShardingSQLRouter.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/kernel/ExecutorEngine.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/driver/jdbc/JDBCExecutorCallback.java, infra/merge/src/main/java/org/apache/shardingsphere/infra/merge/MergeEngine.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/SQLRewriteEntry.java, infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/SQLRouteEngine.java, infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/impl/PartialSQLRouteExecutor.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/route/SingleSQLRouter.java
- Add @HighFrequencyInvocation annotation for kernel core logic
---
=> Add @HighFrequencyInvocation annotation for kernel core logic

docs/community/content/involved/committer/commiter_rights.cn.md, docs/community/content/involved/committer/commiter_rights.en.md
=> Add : add committer rights

docs/document/content/dev-manual/infra-algorithm.cn.md, docs/document/content/dev-manual/infra-algorithm.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/plugin/show-load-balance-algorithm-plugins.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/plugin/show-load-balance-algorithm-plugins.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/plugin/show-plugins.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/plugin/show-plugins.en.md, infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
- update the document and fix dead link since package load.balancer has been changed to loadbalancer
---
=> Document : update the document and fix dead link since package load.balancer has been changed to loadbalancer

features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/constant/BroadcastDistSQLConstants.java, features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/provider/BroadcastConvertRuleConfigurationProvider.java, features/broadcast/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.engine.query.ral.convert.ConvertRuleConfigurationProvider
For #30496 .
- add convert rule configuration provider for Broadcast.
---
=> add convert rule configuration provider for Broadcast.

docs/community/content/involved/committer/commiter_rights.cn.md, docs/community/content/involved/committer/commiter_rights.en.md
- update the commiter rights content to make the link bold
---
=> Document : update the commiter rights content to make the link bold

distribution/proxy/src/main/release-docs/LICENSE, docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md, infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
Fixes https://github.com/apache/shardingsphere/actions/runs/8331464090/job/22798439484 .
- Fixes NativeTest CI failure due to class name change. Also fixes #30538 .
- Updates the LICENSE of the zookeeper client. For #30507 .
- Updates an incorrectly placed Chinese document.
---
=> Fixes NativeTest CI failure due to class name change

kernel/sql-federation/api/src/main/java/org/apache/shardingsphere/sqlfederation/spi/SQLFederationColumnTypeConverter.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSet.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSetMetaData.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/converter/MySQLColumnTypeConverter.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/converter/OpenGaussColumnTypeConverter.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/converter/OracleColumnTypeConverter.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/converter/PostgreSQLColumnTypeConverter.java, kernel/sql-federation/core/src/main/resources/META-INF/services/org.apache.shardingsphere.sqlfederation.spi.SQLFederationColumnTypeConverter, kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSetTest.java, kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/resultset/fixture/converter/SQLFederationColumnTypeConverterFixture.java, kernel/sql-federation/core/src/test/resources/META-INF/services/org.apache.shardingsphere.sqlfederation.spi.SQLFederationColumnTypeConverter, test/e2e/sql/src/test/resources/cases/dql/dql-integration-select.xml
Fixes #30400.
- Fix mysql jdbc and proxy side boolean type queries in federated queries
---
=> Fix mysql jdbc and proxy side boolean type queries in federated queries

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4, test/it/parser/src/main/resources/case/ddl/create-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
Fixes #27110.
-Enhance the support for Oracle SQL parsing 
---
=> Enhance the support for Oracle SQL parsing

kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java, kernel/sql-federation/executor/src/test/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutorTest.java
- [Fix unit test in EnumerableScanExecutorTest](https://github.com/apache/shardingsphere/commit/5546b84d5e3ce9e676ea89954031ad4eeb8af1c5)
---
=> Fix unit test in EnumerableScanExecutorTest

test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/SQLRewriterIT.java, test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/delete/delete.xml, test/it/rewriter/src/test/resources/scenario/sharding/case/dml/select.xml
link #30227.
-  Add encryption rewrite test of the SQLServer delete statement
---
=> Add encryption rewrite test of the SQLServer delete statement

kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/ConsistencyCheckJobAPI.java, kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/task/ConsistencyCheckTasksRunner.java
- Fix consistency check failed but  job status is Finished
---
=> Fix consistency check failed but  job status is Finished

.github/workflows/nightly-e2e-sql.yml
- add opengauss test in nightly e2e sql
---
=> Add : add opengauss test in nightly e2e sql

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/ITContainers.java, test/e2e/operation/pipeline/pom.xml, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLToPostgreSQLMigrationE2E.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLToMySQLMigrationE2E.java
- Add PostgreSQL migrate to MySQL E2E
---
=> Add PostgreSQL migrate to MySQL E2E

kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/constant/SingleDistSQLConstants.java, kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/provider/SingleRuleConfigurationToDistSQLConverter.java
=> Fix convert single rule configuration to DistSQL

features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/provider/BroadcastRuleConfigurationToDistSQLConverterTest.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/query/ral/convert/DistSQLScriptConstants.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationExecutor.java, proxy/backend/core/src/test/resources/expected/convert-encrypt.yaml, proxy/backend/core/src/test/resources/expected/convert-mix.yaml, proxy/backend/core/src/test/resources/expected/convert-readwrite-splitting.yaml, proxy/backend/core/src/test/resources/expected/convert-shadow.yaml, proxy/backend/core/src/test/resources/expected/convert-sharding-auto-tables.yaml, proxy/backend/core/src/test/resources/expected/convert-sharding.yaml
StringBuilder is no longer passed as a parameter
=> Refactor ConvertYamlConfigurationExecutor

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/ConditionValueTest.java
=> Add null condition value test

parser/sql/dialect/mysql/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/mysql/external/ExternalMySQLParserIT.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/DockerITContainer.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/config/impl/StorageContainerConfigurationFactory.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/config/impl/mysql/MySQLContainerConfigurationFactory.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/util/StorageContainerUtils.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/ExternalSQLParserIT.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/external/loader/StandardExternalTestParameterLoadTemplate.java, test/util/src/main/java/org/apache/shardingsphere/test/loader/MySQLExternalTestParameterLoadTemplate.java, test/util/src/main/java/org/apache/shardingsphere/test/loader/SQLLineComment.java, test/util/src/main/java/org/apache/shardingsphere/test/loader/TestParameterLoader.java, test/util/src/main/java/org/apache/shardingsphere/test/loader/strategy/impl/GitHubTestParameterLoadStrategy.java
=> Refactor TestParameterLoader.

features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleExecutor.java, features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropEncryptRuleExecutor.java, features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/update/AlterMaskRuleExecutor.java, features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/update/DropMaskRuleExecutor.java, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/AlterReadwriteSplittingRuleExecutor.java, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/DropReadwriteSplittingRuleExecutor.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/CreateShadowRuleExecutor.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/DropShadowRuleExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterShardingTableReferenceRuleExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingAlgorithmExecutor.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/DropShardingTableRuleExecutor.java, infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/loader/DialectMetaDataLoader.java
=> Remove unused method

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ColumnSegmentBinder.java
=> Fixing alias binding error in subquery

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/ddl/column/ColumnDefinitionSegment.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/definition/ColumnDefinitionAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/definition/ExpectedColumnDefinition.java, test/it/parser/src/main/resources/case/ddl/create-table.xml
=> ColumnDefinitionSegment add auto increment attribute.

infra/algorithm/message-digest/core/pom.xml, infra/algorithm/message-digest/core/src/main/java/org/apache/shardingsphere/infra/algorithm/messagedigest/core/MessageDigestAlgorithm.java, infra/algorithm/message-digest/pom.xml, infra/algorithm/message-digest/type/md5/pom.xml, infra/algorithm/message-digest/type/md5/src/main/java/org/apache/shardingsphere/infra/algorithm/messagedigest/md5/MD5MessageDigestAlgorithm.java, infra/algorithm/message-digest/type/md5/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.algorithm.messagedigest.core.MessageDigestAlgorithm, infra/algorithm/message-digest/type/md5/src/test/java/org/apache/shardingsphere/infra/algorithm/messagedigest/md5/MD5MessageDigestAlgorithmTest.java, infra/algorithm/message-digest/type/pom.xml
- Add new message-digest module and new MD5MessageDigestAlgorithm
---
=> Add new message-digest module and new MD5MessageDigestAlgorithm

docs/document/content/dev-manual/infra-algorithm.cn.md, docs/document/content/dev-manual/infra-algorithm.en.md, features/encrypt/core/pom.xml, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/assisted/MD5AssistedEncryptAlgorithm.java, features/mask/core/pom.xml, features/mask/core/src/main/java/org/apache/shardingsphere/mask/algorithm/hash/MD5MaskAlgorithm.java
- Use MD5MessageDigestAlgorithm to replace MD5MaskAlgorithm and MD5AssistedEncryptAlgorithm
---
=> Use MD5MessageDigestAlgorithm to replace MD5MaskAlgorithm and MD5AssistedEncryptAlgorithm

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptGroupByItemTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptIndexColumnTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptPredicateColumnTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertCipherNameTokenGenerator.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptGroupByItemTokenGeneratorTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptPredicateColumnTokenGeneratorTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGeneratorTest.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/SubstitutableColumnNameToken.java, infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/SubstitutableColumnNameTokenTest.java
=> fix as `owner.name` rewrite missing ``

.github/workflows/nightly-check.yml
- upgrade the deadlink checker in action
---
=> Refactor : upgrade the deadlink checker in action

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/metadata/reviser/constraint/ShardingConstraintReviserTest.java
Fixes #28523 .
-Add test for ShardingConstraintReviser
---
=> Add test for ShardingConstraintReviser

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/create-operator.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-operator.xml
Fixes #27053.
-Enhance the support for Oracle SQL parsing
---
=> Supplement createOperator Parser Rule

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSet.java, kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSetTest.java
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=apache_shardingsphere&open=AY5fOgnVg0wzFN1Nb25n
---
=> Remove useless ShardingSphereSchema in SQLFederationResultSet
