kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/result/yaml/YamlTableDataConsistencyCheckResultSwapperTest.java

Fixes #28540 .
- Added unit test for YamlTableDataConsistencyCheckResultSwapper with 100% coverage
---

Add unit test for YamlTableDataConsistencyCheckResultSwapper

---

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/data-source.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/data-source.en.md

- Fix data source document
---

Fix data source document

---

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/ShardingSphereDatabaseTest.java

This PR fixes - https://github.com/apache/shardingsphere/issues/28568
Changes proposed in this pull request contains unit tests for the following methods in `ShardingSphereDatabase` class
- `containsSchema`
- `getSchema`
- `addSchema`
- `dropSchema`
- `containsDataSource`
Unit tests for the static `create` method will be included in a follow-up PR
```
./mvnw clean install -Prelease -T1C -DskipTests -Djacoco.skip=true -Dcheckstyle.skip=true -Drat.skip=true -Dmaven.javadoc.skip=true -B
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache ShardingSphere 5.4.1-SNAPSHOT:
[INFO] 
[INFO] Apache ShardingSphere .............................. SUCCESS [  4.895 s]
[INFO] shardingsphere-infra ............................... SUCCESS [  0.269 …
```

Expand unit tests for ShardingSphereDatabase class

---

kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/common/ingest/channel/memory/SimpleMemoryPipelineChannelTest.java
kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPlugin.java
kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPluginTest.java

- Improve SimpleMemoryPipelineChannelTest
- Use UTF-8 for PostgreSQL TestDecodingPlugin
---

Try to fix pipeline CI error on windows

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/sink/PipelineDataSourceSink.java

Extracting methods to the outer layer
- Refactor sequentialFlush at PipelineDataSourceSink
---

Refactor sequentialFlush at PipelineDataSourceSink of Pipeline

---

distribution/proxy-native/src/main/release-docs/LICENSE
distribution/proxy/src/main/release-docs/LICENSE
mode/type/cluster/repository/provider/etcd/pom.xml
pom.xml

- Upgrade jetcd dependency version from 0.7.5 to 0.7.6. But it still reference old version of `grpc-protobuf` (which will be upgraded to `1.58.0` without vulnerabilities)
- Replace `grpc-all` dependency to separated ones to reduce unnecessary dependencies
`grpc-all` includes too much dependencies with compile scope, e.g. `grpc-testing` which depends on `junit` on compile scope, and it'll be removed from dependencies.
```
<dependency>
<groupId>io.grpc</groupId>
<artifactId>grpc-testing</artifactId>
<version>1.58.0</version>
<scope>compile</scope>
```
Simplified dependency chain: `grpc-xxx <- jetcd-grpc <- jetcd-core`.
---

Improve jetcd and grpc dependency

---

kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/common/ingest/channel/memory/SimpleMemoryPipelineChannelTest.java
kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPlugin.java
kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPluginTest.java

- Improve SimpleMemoryPipelineChannelTest
- Use UTF-8 for PostgreSQL TestDecodingPlugin
---

Improve PostgreSQL TestDecodingPlugin encoding

---

distribution/proxy-native/src/main/release-docs/LICENSE
distribution/proxy/src/main/release-docs/LICENSE

- add denpendencies in LICENSE file
---

Add : add denpendencies in LICENSE file

---

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/SQLRewriteEntry.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/engine/GenericSQLRewriteEngine.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/engine/RouteSQLRewriteEngine.java
infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/engine/GenericSQLRewriteEngineTest.java
infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/engine/RouteSQLRewriteEngineTest.java
kernel/sql-translator/api/pom.xml
kernel/sql-translator/api/src/main/java/org/apache/shardingsphere/sqltranslator/spi/SQLTranslator.java
kernel/sql-translator/core/src/main/java/org/apache/shardingsphere/sqltranslator/rule/SQLTranslatorRule.java
kernel/sql-translator/core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/SQLTranslatorRuleTest.java
kernel/sql-translator/core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/fixture/AlwaysFailedSQLTranslator.java
kernel/sql-translator/core/src/test/java/org/apache/shardingsphere/sqltranslator/rule/fixture/ConvertToUpperCaseSQLTranslator.java
kernel/sql-translator/provider/jooq/src/main/java/org/apache/shardingsphere/sqltranslator/jooq/JooQSQLTranslator.java
kernel/sql-translator/provider/native/src/main/java/org/apache/shardingsphere/sqltranslator/natived/NativeSQLTranslator.java

- refactor sql translator interface and modify jooq and native translator
---

Refactor sql translator interface and modify jooq and native translator

---

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AbstractStatementAdapter.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/adapter/StatementAdapterTest.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java

Optimize ShardingSpherePreparedStatement for multi executionContext

---

features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/metadata/reviser/column/EncryptColumnExistedReviserTest.java

Fixes #28548 
-
Added unit tests for EncryptColumnExistedReviser.java
---

add unit tests for EncryptColumnExistedReviser.java

---

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/SQLNodeConverterEngine.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/from/impl/SimpleTableConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/projection/ProjectionsConverter.java
test/it/optimizer/src/test/resources/converter/select.xml

Fixes #28800.
- fix Object 'DUAL' not found exception when execute select 1 from dual with sql federation
- add sql statement convert unit test
---

Fix Object 'DUAL' not found exception when execute select 1 from dual with sql federation

---

agent/core/src/main/java/org/apache/shardingsphere/agent/core/yaml/AgentYamlConstructor.java
agent/core/src/main/java/org/apache/shardingsphere/agent/core/yaml/AgentYamlEngine.java
distribution/proxy-native/src/main/release-docs/LICENSE
distribution/proxy/src/main/release-docs/LICENSE
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/_index.en.md
infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/YamlEngine.java
infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/representer/ShardingSphereYamlRepresenter.java
infra/util/src/test/java/org/apache/shardingsphere/infra/util/yaml/YamlEngineTest.java
infra/util/src/test/java/org/apache/shardingsphere/infra/util/yaml/constructor/ShardingSphereYamlConstructorTest.java
infra/util/src/test/java/org/apache/shardingsphere/infra/util/yaml/representer/ShardingSphereYamlRepresenterTest.java
pom.xml

Fixes #24636.
- Updates ElasticJob to 3.0.4 to block CVEs for SnakeYAML delivery. Refer to https://github.com/apache/shardingsphere-elasticjob/releases/tag/3.0.4 .
- Also fixes #28233.
- Also fixes #28067.
- Also fixes #27370.
- Also fixes #25291.
- Since the CI of the Exmaple module is broken on JDK21, I am not handling the changes to the Example module in this PR. Refer to https://github.com/apache/shardingsphere/actions/runs/6563502380 .
---

Updates ElasticJob to 3.0.4 to block CVEs for SnakeYAML delivery

---

parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/ddl/CreateTableStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/sqlserver/ddl/SQLServerCreateTableStatement.java

Ref #28752.
- Change the definition position of the create table SelectStatement class
- mysql, oracle, sqlserver, opengauss, and postgresql all have syntax definitions for sql statements in the `create table as select `format
---

Change the definition position of the create table SelectStatement class

---

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/operator/common/SQLExtensionOperatorTable.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/operator/dialect/mysql/MySQLMatchAgainstOperator.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/BinaryOperationExpressionConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/CollateExpressionConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/MatchExpressionConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/NotExpressionConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/UnaryOperationExpressionConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/statement/merge/MergeStatementConverter.java
test/it/optimizer/src/test/resources/converter/select-join.xml

Ref #28799.
- Refactor package of sql extension operator table
---

Refactor package of sql extension operator table

---

kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/persist/node/NewGlobalNodeTest.java

Fixes #28493.
- Added unit test for NewGlobalNode#getGlobalRuleVersionNode, asserts expected result
---

Adding Unit test for NewGlobalNode#getGlobalRuleVersionNode

---

pom.xml

Fix the shade plugin does not work with JDK 20 (https://github.com/apache/maven-shade-plugin/releases)

Update maven-shade-plugin from 3.4.1 to 3.5.1

---

test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/job/service/GovernanceRepositoryAPIImplTest.java

Fixes #28545.
-  Added unit tests for persistLatestCheckJobId
-  Added unit tests for getLatestCheckJobId
-  Added unit tests for deleteLatestCheckJobId
---

Add unit test for GovernanceRepositoryAPIImpl

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
test/it/parser/src/main/resources/case/ddl/alter-table.xml
test/it/parser/src/main/resources/case/ddl/alter-tablespace.xml
test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml
test/it/parser/src/main/resources/sql/supported/ddl/alter-tablespace.xml

Fixes #26995.
- Improve alter tablespace syntax rules
- Format alter tablespace rules
- Add create tablespace and alter tablespace defaultTablespaceParams rule
- Change incorrect parsing rules in alter tablespace
- Reference issues: 26996 ~ 27003
- Ref: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-TABLESPACE.html#GUID-CA074861-55D3-4768-8995-43D4DA26365D
---
- [ ✓] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip …

Improve alter tablespace syntax rules

---

test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java

Related to #28849.
After discussing with @RaigorJiang , there're 2 workarounds. Use `statement.execute and then getResultSet` is an easier way, so it's used for now.
- Pipeline E2E use statement.execute and getResultSet to compatible with com.mysql:mysql-connector-j:8.0 for extended DistSQL
- Revert pipeline E2E compatibility code of com.mysql:mysql-connector-j:8.0
---

Pipeline E2E compatible with com.mysql:mysql-connector-j:8.0

---

test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java
test/e2e/operation/pipeline/src/test/resources/logback-test.xml

Because of `serverTimezone=UTC` jdbc parameter, it is important to make sure that the program time zone and the database time zone are the same
- Fix cdc e2e failed.
---

Enable CDC E2E

---

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/RALE2EIT.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/RQLE2EIT.java

- SQL E2E compatible with com.mysql:mysql-connector-j:8.0
---

SQL E2E compatible with com.mysql:mysql-connector-j:8.0

---

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingTableNodesExecutor.java
infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/query/RQLExecutor.java
kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/prepare/datasource/OpenGaussDataSourcePreparer.java
kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/prepare/datasource/PostgreSQLDataSourcePreparer.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationExecutorTest.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/DDLE2EIT.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/RALE2EIT.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/RDLE2EIT.java

Fix empty sql in SQL E2E

---

kernel/data-pipeline/scenario/cdc/client/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/client/CDCClient.java
kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/impl/CDCJobAPI.java

- Add replication slot cleanup when drop CDC tasks
- Add dropStreaming method of CDCClient.
---

Add replication slot cleanup when drop CDC tasks

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4

- Remove duplicate rule definitions in Oracle BaseRule.g4
---
- [  ✓] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [  ✓] I have self-reviewed the commit code.
- [  ✓] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [  ✓] I have added corresponding unit tests for my changes.

Remove duplicate rule definitions in Oracle BaseRule.g4

---

proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/CDCServer.java
proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/ShardingSphereProxy.java

Adjust parameter naming

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/rule/RuleMetaData.java
parser/distsql/engine/src/main/antlr4/imports/Keyword.g4
parser/distsql/engine/src/main/antlr4/imports/RDLStatement.g4
parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java
parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/statement/rdl/drop/UnregisterStorageUnitStatement.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/UnregisterStorageUnitBackendHandler.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/storage/unit/UnregisterStorageUnitBackendHandlerTest.java

Fixes #28910.
- Add ignore broadcast tables when unregister storage unit
- Fix getInUsedStorageUnitNameAndRulesMap error for RuleMetaData
---

Add ignore broadcast tables when unregister storage unit

---

kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/job/PipelineJobCenterTest.java

Fixes #28542 .
-
Added unit tests for PipelineJobCenter to test its public functions to improve unit test coverage. Methods: addJob, isJobExisting, getJob, getJobItemContext, getShardingItems.
---

Add unit test for PipelineJobCenter

---

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java

Optimize ShardingSpherePreparedStatement and ShardingSphereStatement for multi execution

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #28871.
- Support oracle wm_concat function parse
- Add test sql
---

Support oracle wm_concat function parse

---

features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/metadata/reviser/column/EncryptColumnNameReviserTest.java

Fixes #28549 .
-
Added unit tests for EncryptColumnNameReviser to test its public functions to improve unit test coverage.Method:revise()
---

Added unit tests for EncryptColumnNameReviser revive method

---

test/it/parser/src/main/resources/case/ddl/create-tablespace.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-tablespace.xml

Fixes #27118 and ref #26878
- Add create-temporary-tablespace related test SQL
---

SQL parsing Enhancement: add more test case for Oracle CREATE TEMPORARY TABLESPACE sql

---

kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPlugin.java
kernel/data-pipeline/dialect/opengauss/src/test/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPluginTest.java
kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/importer/sink/CDCSocketSink.java
kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/job/CDCJob.java

Related #22500.
- When streaming job failed, send error result to CDC Client
- Add tinyint decode at MppdbDecodingPlugin
---

 Notify the CDC Client if streaming stopped due to exception

---

kernel/data-pipeline/scenario/cdc/core/pom.xml
kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/util/CDCDataNodeUtils.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java

Related #22500.
- CDC support broadcast table 
---

CDC support broadcast table

---

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/unregister-storage-unit.cn.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/unregister-storage-unit.en.md

For #28910.
- update doc of `unregister storage unit` DistSQL
---

update doc of unregister storage unit DistSQL

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select-combine.xml
test/it/parser/src/main/resources/sql/supported/dml/select-combine.xml

- The Oracle select SQL statement union was not parsed
- Fix oracle select union sql parse
- Add test sql
---

Fix oracle select union sql parse

---

agent/core/src/test/java/org/apache/shardingsphere/fixture/log/LogbackConfigurationFixture.java
distribution/proxy-native/src/main/release-docs/LICENSE
distribution/proxy/src/main/release-docs/LICENSE
pom.xml
proxy/bootstrap/src/main/java/org/apache/shardingsphere/proxy/config/LogbackConfiguration.java

For #28826.
- Restore the slf4j version from 2.0.9 to 1.7.36 before Spring Boot 2 ends the OSS life cycle.
- #28826 Increasing the slf4j version to 2.0.9 caused all downstreams running ShardingSphere JDBC on Spring Boot 2.x to receive an Error. 
- The Spring Boot side is restricted by the underlying design. The 2.x branch of Spring Boot will use slf4j 1.x until the end of the OSS life cycle. Due to changes in the API of the corresponding logback implementation, it is impossible to use logback 1.3.x on Spring Boot 2.x. Reference https://github.com/spring-projects/spring-boot/issues/34708.
- I believe the current PR will not affect Spring Boot 3 downstream, because slf4j 2.0 is designed to be compatible with slf4j 1.x. The real issue involved here is …

Restore the slf4j version from 2.0.9 to 1.7.36 before Spring Boot 2 ends the OSS life cycle

---

mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoader.java

For #29000.
- Open the `resource:/` related FileSystem for JDBCRepositorySQLLoader in the GraalVM Native Image environment.
- Also for #21347.
- Under the GraalVM Native Image corresponding to GraalVM CE 21.0.1, although there is `NativeImageResourceFileSystemProvider` , the corresponding `NativeImageResourceFileSystem`  does not autoload. This is mainly to align the behavior of `ZipFileSystemProvider`, so we need to manually open and close the FileSystem corresponding to the `resource:/` scheme. For more background reference https://github.com/oracle/graal/issues/7682 .
- we use the System Property of `org.graalvm.nativeimage.imagecode` to identify whether this class is in the GraalVM Native Image environment. The background of this property comes …

Open the `resource:/` related FileSystem for JDBCRepositorySQLLoader in the GraalVM Native Image environment

---

distribution/proxy-native/src/main/release-docs/LICENSE
distribution/proxy/src/main/release-docs/LICENSE
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/_index.en.md
kernel/sql-federation/core/pom.xml
kernel/sql-federation/executor/pom.xml
kernel/sql-federation/optimizer/pom.xml
kernel/transaction/type/xa/provider/narayana/pom.xml
mode/type/standalone/repository/provider/jdbc/pom.xml
mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoader.java
pom.xml
test/pom.xml

Fixes #29012.
- Migrate JAXB Runtime from `com.sun.xml.bind:jaxb-impl` to `org.glassfish.jaxb:jaxb-runtime`. Refer to https://bugs.openjdk.org/browse/JDK-8193033 . 
---

Migrate JAXB Runtime from `com.sun.xml.bind:jaxb-impl` to `org.glassfish.jaxb:jaxb-runtime`

---

mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoader.java

For #29000.
- Make JDBCRepositorySQLLoader avoid using `Path#toFile` in GraalVM Native Image. Refer to https://github.com/oracle/graal/issues/7804 .
- Also for #21347.
---

Make JDBCRepositorySQLLoader avoid using `Path#toFile` in GraalVM Native Image

---

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/BroadcastSQLRouter.java
features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/engine/type/broadcast/BroadcastDatabaseBroadcastRoutingEngine.java
features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/engine/type/broadcast/BroadcastInstanceBroadcastRoutingEngine.java
features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/engine/type/broadcast/BroadcastTableBroadcastRoutingEngine.java
features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/engine/type/unicast/BroadcastUnicastRoutingEngine.java
features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/rule/BroadcastRule.java
features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/rule/builder/BroadcastRuleBuilder.java
features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/engine/type/broadcast/BroadcastDatabaseBroadcastRoutingEngineTest.java
features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/engine/type/broadcast/BroadcastInstanceBroadcastRoutingEngineTest.java
features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/engine/type/broadcast/BroadcastTableBroadcastRoutingEngineTest.java
features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/engine/type/unicast/BroadcastUnicastRoutingEngineTest.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/YamlDatabaseConfigurationImportExecutor.java

Fixes #28928.
- Fixed the problem of broadcast table execution error when readwrite_splitting rule exist
---

Fixed the problem of broadcast table execution error when readwrite_splitting rule exist

---

kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/util/CDCDataNodeUtils.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/cdc/CDCE2EIT.java

Related: #22500 
- Add single table streaming case at CDC E2E
---

Add single table streaming case at CDC E2E

---

features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/update/CreateBroadcastTableRuleStatementUpdater.java
features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/update/CreateBroadcastTableRuleStatementUpdaterTest.java

Fixes #29027.
- Add check the storage unit is not empty when create broadcast table rule
---

Add check the storage unit is not empty when create broadcast table rule

---

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/readwrite-splitting.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/readwrite-splitting.en.md
features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/rule/ReadwriteSplittingRuleTest.java

For #29000.
- Declare in the document that ReadWriteSplitting Config is parsed by GroovyShell by default and adds corresponding unit tests.
- Also for #21347 .
---

Declare in the document that ReadWriteSplitting Config is parsed by GroovyShell by default and adds corresponding unit tests

---

features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/query/ShowEncryptRuleExecutorTest.java
features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/query/ShowMaskRuleExecutorTest.java
features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/ShowReadwriteSplittingRuleExecutorTest.java
features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowDefaultShadowAlgorithmExecutorTest.java
features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowAlgorithmsExecutorTest.java
features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowRuleExecutorTest.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingAlgorithmExecutorTest.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRuleExecutorTest.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowUnusedShardingAlgorithmsExecutorTest.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowUnusedShardingKeyGeneratorExecutorTest.java
infra/common/src/main/java/org/apache/shardingsphere/infra/props/PropertiesConverter.java
infra/common/src/test/java/org/apache/shardingsphere/infra/props/PropertiesConverterTest.java
kernel/traffic/distsql/handler/src/test/java/org/apache/shardingsphere/traffic/distsql/handler/query/ShowTrafficRuleExecutorTest.java
kernel/transaction/distsql/handler/src/test/java/org/apache/shardingsphere/transaction/distsql/handler/query/ShowTransactionRuleExecutorTest.java
kernel/transaction/distsql/handler/src/test/java/org/apache/shardingsphere/transaction/distsql/handler/update/AlterTransactionRuleStatementUpdaterTest.java

For #29039.
- Refactor parse of properties to JSON
---

Refactor parse of properties

---

test/it/parser/src/main/resources/case/ddl/create-materialized-view-log.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-materialized-view-log.xml

Fixes #27033
- Add more  test case 
---

SQL parsing Enhancement: add more test case for Oracle CREATE MATERIALIZED VIEW LOG sql 

---

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/import-database-configuration.cn.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/import-database-configuration.en.md

Correct IMPORT DATABASE CONFIGURATION syntax document.
---

Correct IMPORT DATABASE CONFIGURATION syntax document

---

features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/query/ShowEncryptRuleExecutorTest.java
features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/query/ShowMaskRuleExecutorTest.java
features/shadow/distsql/handler/src/test/java/org/apache/shardingsphere/shadow/distsql/query/ShowShadowRuleExecutorTest.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowShardingTableRuleExecutorTest.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowUnusedShardingKeyGeneratorExecutorTest.java
infra/common/src/main/java/org/apache/shardingsphere/infra/props/PropertiesConverter.java
infra/common/src/test/java/org/apache/shardingsphere/infra/props/PropertiesConverterTest.java
kernel/traffic/distsql/handler/src/test/java/org/apache/shardingsphere/traffic/distsql/handler/query/ShowTrafficRuleExecutorTest.java

Fixes #29039.
- Outputs an empty string when Properties is empty
- Output after sorting
---

Optimize PropertiesConverter

---

infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/connector/MySQLConnectionPropertiesParser.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/runtime/DataSourceEnvironment.java

Because of upgrade to `MySQL Connector/J 8.x`, Configuring `serverTimezone` alone is effective, however, the default time zone in the program is used when`serverTimezone` is configured individually in `MySQL Connector/J 5.1.x`
So, it's better add the parameter manually if needed
refer 
1. https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html
2. https://dev.mysql.com/doc/connectors/en/connector-j-time-instants.html
3. https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-23.html
-
---

Remove `serverTimezone=UTC` parameter at MySQLConnectionPropertiesParser and E2E

---

test/it/parser/src/main/resources/case/ddl/create-materialized-view.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-materialized-view.xml

Fixes #27040, #27041 and #27045.
- Add test case SQL
---

SQL parsing Enhancement: add more SQL test case for create-materialized-view

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/context/ShardingSQLRewriteContextDecorator.java

- Fix sharding sql rewrite error
---

Fix sharding sql rewrite error

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/context/ShardingSQLRewriteContextDecorator.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/context/ShardingSQLRewriteContextDecoratorTest.java

- Skip sharding sql rewrite when insert statement not contains sharding table
---

Skip sharding sql rewrite when insert statement not contains sharding table

---

pom.xml

Fixes #29092.
- add back the junit-jupiter-engine to make the workflow execute.
---

Refactor : add junit-jupiter-engine back

---

kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/MySQLIncrementalDumper.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/job/service/GovernanceRepositoryAPIImplTest.java

- Use deepEquals instead of equals, because it's support binary data such as `byte[]`, `Byte` 
- Clean invalid job config, avoid affecting other cases
---

Use deepEquals instead of equals at MySQLIncrementalDumper

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilder.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRule.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderRuleTest.java

- Fix NPE of system schema builder rule
---

Fix NPE of system schema builder rule

---

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4
parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/Literals.g4
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

- Support SQLServer convert function parse
- Add test sql
- Ref: https://learn.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver16
---
- [✓] I have self-reviewed the commit code.
- [✓] I have (or in comment I request) added corresponding labels for the pull request.
- [✓] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [✓] I have added corresponding unit tests for my changes.

Support SQLServer convert function parse

---

proxy/bootstrap/src/main/resources/conf/config-sharding.yaml

Related: https://github.com/apache/shardingsphere/pull/29070
- Remove serverTimezone at config-sharding.yaml
---

Remove serverTimezone at config-sharding.yaml

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertOnUpdateTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptFunctionAssignmentToken.java

- Remove java stream api and build sql when execute addAssignment method
---

Remove java stream api and build sql when execute addAssignment method

---

kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/XAShardingSphereTransactionManager.java

- Use CaseInsensitiveMap to avoid npe when databaseName is upper
---

Use CaseInsensitiveMap to avoid npe when databaseName is upper

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4
test/it/parser/src/main/resources/case/ddl/create-index.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-index.xml

Fixes #27084.
- Improve oracle create index syntax parse
- Related reference documents:
- https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CREATE-INDEX.html#GUID-1F89BBC0-825F-4215-AF71-7588E31D8BFE
- https://docs.oracle.com/en/database/oracle/oracle-database/19/adxdb/indexes-for-XMLType-data.html#GUID-BCC7D521-E6B9-4636-98E1-25628BA0FEFC
- https://docs.oracle.com/en/database/oracle/oracle-database/19/adxdb/xquery-and-XML-DB.html#GUID-39CDBF4D-258D-4CFE-AEBF-06ECD660C08D
- https://docs.oracle.com/en/database/oracle/oracle-database/19/arpls/DBMS_SCHEDULER.html#GUID-73622B78-EFF4-4D06-92F5-E358AB2D58F3
---

Improve oracle create index syntax parse

---

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/table/TableMetadataReviseEngineTest.java

Fixes #28535.
- Added UT for TableMetadataReviseEngine w.r.t #28535 
---

Added unit tests for TableMetadataReviseEngine (#28535)

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4

- Merge XmlNameSpacesClause to avoid antlr compile exception on local machine
---

Merge XmlNameSpacesClause to avoid antlr compile exception on local machine

---

features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/BroadcastSqlRouterTest.java

Fixes #28521 
-
Add more unit tests for BroadcastSQLRouter
---
- [√ ] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [√ ] I have self-reviewed the commit code.
- [√ ] I have (or in comment I request) added corresponding labels for the pull request.
- [√] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.

Add more unit tests for BroadcastSQLRouter (#28521)

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/insert/keygen/engine/GeneratedKeyContextEngine.java

- Remove unused method of findGenerateKeyExpressions
---

Remove unused method of findGenerateKeyExpressions

---

mode/type/cluster/repository/provider/consul/pom.xml
mode/type/cluster/repository/provider/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/ShardingSphereQueryParams.java
mode/type/cluster/repository/provider/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/lock/ConsulDistributedLock.java
pom.xml

For #22354.
- Update Consul Client to expose deprecated Consul 1.17 API. Refer to https://github.com/Ecwid/consul-api/issues/246 .
- `com.ecwid.consul.transport.RawResponse` has been renamed at https://github.com/Ecwid/consul-api/commit/fcee76283a2e122212943d58b7d9173f67f8412c .
- `com.ecwid.consul.Utils#toUnsignedString` has been removed at https://github.com/Ecwid/consul-api/commit/ffd9e29df1ab203e2777e012d12b4f6028df1251.
---

Update Consul Client to expose deprecated Consul API

---

infra/exception/dialect/type/mysql/src/main/java/org/apache/shardingsphere/infra/exception/mysql/exception/TooManyPlaceholdersException.java
infra/exception/dialect/type/mysql/src/main/java/org/apache/shardingsphere/infra/exception/mysql/mapper/MySQLDialectExceptionMapper.java
infra/exception/dialect/type/mysql/src/main/java/org/apache/shardingsphere/infra/exception/mysql/vendor/MySQLVendorError.java
proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java
proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutorTest.java

Fixes #29295.
- Throw exception when placeholders exceed 65535 in MySQL prepared statement
---

Throw exception when placeholders exceed 65535 in MySQL prepared statement

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/InsertClauseShardingConditionEngine.java

- Minor refactor in InsertClauseShardingConditionEngine
---

Minor refactor in InsertClauseShardingConditionEngine

---

infra/common/pom.xml
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/type/UnsupportedStorageTypeException.java
infra/database/type/clickhouse/pom.xml
infra/database/type/clickhouse/src/main/java/org/apache/shardingsphere/infra/database/clickhouse/type/ClickHouseDatabaseType.java
infra/database/type/clickhouse/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.database.core.type.DatabaseType
infra/database/type/clickhouse/src/test/java/org/apache/shardingsphere/infra/database/clickhouse/type/ClickHouseDatabaseTypeTest.java
infra/database/type/mariadb/src/main/java/org/apache/shardingsphere/infra/database/mariadb/type/MariaDBDatabaseType.java
infra/database/type/mariadb/src/test/java/org/apache/shardingsphere/infra/database/mariadb/type/MariaDBDatabaseTypeTest.java
infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/type/MySQLDatabaseType.java
infra/database/type/mysql/src/test/java/org/apache/shardingsphere/infra/database/mysql/type/MySQLDatabaseTypeTest.java
infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/type/OracleDatabaseType.java
infra/database/type/oracle/src/test/java/org/apache/shardingsphere/infra/database/oracle/type/OracleDatabaseTypeTest.java
infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/type/PostgreSQLDatabaseTypeTest.java
infra/database/type/sqlserver/src/main/java/org/apache/shardingsphere/infra/database/sqlserver/type/SQLServerDatabaseType.java
infra/database/type/sqlserver/src/test/java/org/apache/shardingsphere/infra/database/sqlserver/type/SQLServerDatabaseTypeTest.java

Fixes #28892.
- Convert DatabaseTypes for Clickhouse and common testcontainers. 
- The jdbcURL prefix for testcontainers comes from the documentation for testcontainers-java. For #29052 .
- Clickhouse currently use SQL92 dialect parsing. This PR is only to avoid direct error reporting and leave room for further implementation in the future. Also fixes #29291 .
- Provide more detailed error reporting for related unadapted databases.
---

Convert DatabaseTypes for Clickhouse and common testcontainers

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/segment/oracle/xml/XmlNamespaceStringAsIdentifierSegment.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/segment/oracle/xml/XmlNamespacesClauseSegment.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/segment/oracle/xml/XmlTableFunctionSegment.java

- Rename xmlNamespacesClause define
---

Rename xmlNamespacesClause define

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/ExpressionSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/InExpressionBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/TableSegmentBinder.java

- Enhance sql binder logic for subquery
---

Enhance sql binder logic for subquery

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/PipelineChannel.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/MemoryPipelineChannelCreator.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/SimpleMemoryPipelineChannel.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/SimpleMemoryPipelineChannelTest.java

- Support SimpleMemoryPipelineChannel use 0 blocking queue size
- Enable fair for incremental
---

Support SimpleMemoryPipelineChannel use 0 blocking queue size

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/Literals.g4
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4
parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/Symbol.g4
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/value/literal/impl/StringLiteralValue.java
test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema-postgresql.xml
test/it/parser/src/main/resources/case/dml/insert.xml
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/insert.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #29152.
- Support parsing SQL Server INSERT INTO sql
1. INSERT INTO dbo.T1 VALUES (1, N'Natalia')
2. SELECT x.$(ColumnName) FROM Person.Person x WHERE x.BusinessEntityID < 5
3. INSERT INTO AdventureWorks2022.dbo.VariableTest(Col1) VALUES('$(tablename)')
- Fix the error parser in oracle Nchar
---

Support parsing SQL Server INSERT INTO sql #29152

---

docs/document/content/dev-manual/sharding.cn.md
docs/document/content/dev-manual/sharding.en.md
docs/document/content/user-manual/common-config/builtin-algorithm/expr.cn.md
docs/document/content/user-manual/common-config/builtin-algorithm/expr.en.md
infra/expr/core/pom.xml
infra/expr/type/interval/pom.xml
infra/expr/type/interval/src/main/java/org/apache/shardingsphere/infra/expr/interval/IntervalInlineExpressionParser.java
infra/expr/type/interval/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.expr.spi.InlineExpressionParser
infra/expr/type/interval/src/test/java/org/apache/shardingsphere/infra/expr/interval/IntervalInlineExpressionParserTest.java

Fixes #22899.
- Add Interval implementation of InlineExpressionParser SPI.
- The function signature of this SPI uses `java.util.List` instead of `java.util.Collection`, which should require another PR to correct the function signature.
- Since the JDK 8 version is used in CI is too old, the relevant `java.time.chrono.JapaneseDate` tests have been set up to be available for JDK11+.
---

Add Interval implementation of InlineExpressionParser SPI

---

infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/SQLRewriteEntryTest.java
infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/engine/GenericSQLRewriteEngineTest.java
infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/engine/RouteSQLRewriteEngineTest.java
kernel/sql-translator/api/src/main/java/org/apache/shardingsphere/sqltranslator/api/config/SQLTranslatorRuleConfiguration.java
kernel/sql-translator/core/src/main/java/org/apache/shardingsphere/sqltranslator/rule/builder/DefaultSQLTranslatorRuleConfigurationBuilder.java
kernel/sql-translator/core/src/test/java/org/apache/shardingsphere/sqltranslator/yaml/swapper/NewYamlSQLTranslatorRuleConfigurationSwapperTest.java
test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/SQLRewriterIT.java

- Refactor SQLTranslatorRuleConfiguration constructor
---

Refactor SQLTranslatorRuleConfiguration constructor

---

docs/document/content/user-manual/common-config/builtin-algorithm/expr.cn.md
docs/document/content/user-manual/common-config/builtin-algorithm/expr.en.md
infra/expr/type/interval/src/test/java/org/apache/shardingsphere/infra/expr/interval/IntervalInlineExpressionParserTest.java

For #29309 .
- Convert `Locale` when executing JapaneseDate related unit tests.
- Refer to https://github.com/apache/shardingsphere/actions/runs/7185460184/job/19568814086 .
---

Convert `Locale` when executing JapaneseDate related unit tests to fix CI

---

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/SubstitutableColumnNameToken.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dql/AdditionalDQLE2EIT.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dql/BaseDQLE2EIT.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dql/GeneralDQLE2EIT.java

- Add column type assert in BaseDQLE2EIT
---

Add column type assert in BaseDQLE2EIT

---

kernel/sql-federation/core/pom.xml
kernel/sql-federation/executor/pom.xml

For #29384.
- Remove sql-federation’s transitive dependency on JAXB. Some unnoticed test scope dependencies are left behind in #29384.
---

Remove sql-federation’s transitive dependency on JAXB

---

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/Comments.g4

- Remove incorrect SqlServer annotation syntax
There are only two annotation rules '--'and '/* */' in the syntax of sqlServer, and there is no '#'，Below is the official website address
https://learn.microsoft.com/zh-cn/sql/t-sql/language-elements/comment-transact-sql?view=sql-server-ver16
This problem will cause the SQL similar to 'SELECT COUNT(*) AS [Number of rows] FROM #Test' to be parsed correctly in DMLStatement.g4, but it will be parsed incorrectly in SQLServerStatement.g4 with an error message indicating a missing EOF because '#' is defined as a comment in Comments.g4, which can lead to confusion when writing parsing rules. like #29230 
**result In DMLStatement.g4**
**result In SQLServerStatement.g4**
---
Before committing …

Remove incorrect SqlServer annotation syntax

---

docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.en.md
docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.cn.md
docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.en.md
infra/database/type/clickhouse/src/main/java/org/apache/shardingsphere/infra/database/clickhouse/type/ClickHouseDatabaseType.java
infra/database/type/clickhouse/src/test/java/org/apache/shardingsphere/infra/database/clickhouse/type/ClickHouseDatabaseTypeTest.java
infra/database/type/mariadb/src/main/java/org/apache/shardingsphere/infra/database/mariadb/type/MariaDBDatabaseType.java
infra/database/type/mariadb/src/test/java/org/apache/shardingsphere/infra/database/mariadb/type/MariaDBDatabaseTypeTest.java
infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/type/MySQLDatabaseType.java
infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/type/OracleDatabaseType.java
infra/database/type/oracle/src/test/java/org/apache/shardingsphere/infra/database/oracle/type/OracleDatabaseTypeTest.java
infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/type/PostgreSQLDatabaseTypeTest.java
infra/database/type/sqlserver/src/main/java/org/apache/shardingsphere/infra/database/sqlserver/type/SQLServerDatabaseType.java
infra/database/type/sqlserver/src/test/java/org/apache/shardingsphere/infra/database/sqlserver/type/SQLServerDatabaseTypeTest.java
infra/database/type/testcontainers/pom.xml
infra/database/type/testcontainers/src/main/java/org/apache/shardingsphere/infra/database/testcontainers/type/AbstractTestcontainersDatabaseType.java
infra/database/type/testcontainers/src/main/java/org/apache/shardingsphere/infra/database/testcontainers/type/TcClickHouseDatabaseType.java
infra/database/type/testcontainers/src/main/java/org/apache/shardingsphere/infra/database/testcontainers/type/TcMariaDBDatabaseType.java
infra/database/type/testcontainers/src/main/java/org/apache/shardingsphere/infra/database/testcontainers/type/TcMySQLDatabaseType.java
infra/database/type/testcontainers/src/main/java/org/apache/shardingsphere/infra/database/testcontainers/type/TcOracleDatabaseType.java
infra/database/type/testcontainers/src/main/java/org/apache/shardingsphere/infra/database/testcontainers/type/TcPostgreSQLDatabaseType.java
infra/database/type/testcontainers/src/main/java/org/apache/shardingsphere/infra/database/testcontainers/type/TcSQLServerDatabaseType.java
infra/database/type/testcontainers/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.database.core.type.DatabaseType
infra/database/type/testcontainers/src/test/java/org/apache/shardingsphere/infra/database/testcontainers/type/TestcontainersDatabaseTypeTest.java
test/native/pom.xml

For #29052.
- Add `shardingsphere-infra-database-testcontainers` optional module to unify JDBC support for testcontainers-java.
- I tend to build it into `shardingsphere-jdbc-core`, because the API of testcontainers-java is actually being widely used downstream.
---

Add `shardingsphere-infra-database-testcontainers` optional module to unify JDBC support for testcontainers-java

---

docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/resource-config.json
test/native/native-image-filter/extra-filter.json
test/native/pom.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/OpenGaussTest.java
test/native/src/test/resources/META-INF/native-image/shardingsphere-test-native-test-metadata/resource-config.json
test/native/src/test/resources/test-native/yaml/databases/opengauss.yaml

For #29052.
- Add GraalVM Reachability Metadata and corresponding nativeTest for OpenGauss integration.
- Fixes a bug where MySQLTest incorrectly created a Docker Image instance when the Maven Profile of `generateMetadata` or `nativeTestInShardingSphere` was not activated.
- Because there is a bug that needs to be verified on the side of TestContainers, the current NativeTest does not allow running through Podman. Modify the corresponding document.
---

Add GraalVM Reachability Metadata and corresponding nativeTest for OpenGauss integration

---

distribution/proxy-native/pom.xml
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
infra/database/type/sqlserver/src/main/java/org/apache/shardingsphere/infra/database/sqlserver/connector/SQLServerConnectionPropertiesParser.java
infra/database/type/sqlserver/src/test/java/org/apache/shardingsphere/infra/database/sqlserver/connector/SQLServerConnectionPropertiesParserTest.java
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
pom.xml
test/native/native-image-filter/extra-filter.json
test/native/pom.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/commons/repository/AddressRepository.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/commons/repository/OrderItemRepository.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/commons/repository/OrderRepository.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/MSSQLServerTest.java
test/native/src/test/resources/META-INF/native-image/shardingsphere-test-native-test-metadata/resource-config.json
test/native/src/test/resources/container-license-acceptance.txt
test/native/src/test/resources/test-native/yaml/databases/mssqlserver.yaml

For #29052.
- Add GraalVM Reachability Metadata and corresponding nativeTest for MS SQL Server integration.
- Examples like https://github.com/apache/beam/blob/v2.52.0/it/jdbc/src/main/java/org/apache/beam/it/jdbc/MSSQLResourceManager.java show that ASF allows the EULA for MS SQL Server's Docker Image during testing. Therefore, I think there is no problem in using the corresponding Docker Image in unit testing.
- Modifications to `SQLServerConnectionPropertiesParser` are unavoidable and cannot be avoided by implementing a new `ConnectionPropertiesParser`. Because in `TcSQLServerDatabaseType.getTrunkDatabaseType()`, all jdbcUrls with the prefix `jdbc:tc:sqlserver:` will be routed to `SQLServer`’s `DatabaseType`. 
- The reason why jdbcUrl prefixed with …

Add GraalVM Reachability Metadata and corresponding nativeTest for MS SQL Server integration

---

.github/workflows/nightly-ci.yml
examples/pom.xml

For #29386.
- Fix example module failed build on JDK21. Refer to #28326 and https://github.com/apache/shardingsphere/actions/runs/7199233000/job/19610473126 .
---

Fix example module failed build on JDK21

---

infra/common/src/main/java/org/apache/shardingsphere/infra/exception/OverallConnectionNotEnoughException.java
infra/exception/core/src/main/java/org/apache/shardingsphere/infra/exception/core/external/sql/type/kernel/category/ConnectionSQLException.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManager.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/datasource/JDBCBackendDataSource.java

- Add cause exception for OverallConnectionNotEnoughException. Ignored SQLException might be caused by connection timeout etc, it's necessary for troubleshooting, so `cause` is added.
---

Add cause exception for OverallConnectionNotEnoughException

---

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java
infra/common/src/main/java/org/apache/shardingsphere/infra/rule/identifier/type/TableNamesMapper.java

- Use CaseInsensitiveMap to replace LinkedHashMap in TableNamesMapper
---

Use CaseInsensitiveMap to replace LinkedHashMap in TableNamesMapper

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4
parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/MySQLKeyword.g4
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
test/it/parser/src/main/resources/sql/supported/dml/select-combine.xml

- Support mysql intersect combine operation sql parse
---

Support mysql intersect combine operation sql parse

---

distribution/proxy/src/main/release-docs/LICENSE
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptTable.java
features/mask/core/src/main/java/org/apache/shardingsphere/mask/rule/MaskTable.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/ddl/ShardingDDLResultMerger.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/ShardingDQLResultMerger.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/CursorToken.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/SQLStatementBinderContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/MergeStatementBinder.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/datatype/DataTypeLoader.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/SubstitutableColumnNameToken.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/DatabaseMetaDataResultSet.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSetUtils.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/BinaryOperationExpressionConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/UnaryOperationExpressionConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/projection/impl/AggregationProjectionConverter.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/XAShardingSphereTransactionManager.java
pom.xml
proxy/backend/type/hbase/src/main/java/org/apache/shardingsphere/proxy/backend/hbase/result/query/HBaseGetResultSet.java

Based on the JMH tests, java-util has significant advantages over commons-collections4 in terms of performance and memory consumption.
- Replacing the org.apache.commons.collections4.map.CaseInsensitiveMap with com.cedarsoftware.util.CaseInsensitiveMap.
- Fix the issue of Cursor Name being rewritten depending on the order of logicAndActualTables.
---

replacing the org.apache.commons.collections4.map.CaseInsensitiveMap with com.cedarsoftware.util.CaseInsensitiveMap.

---

kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/channel/memory/SimpleMemoryPipelineChannelTest.java

- Fix SimpleMemoryPipelineChannelTest.assertFetchRecordsTimeoutCorrectly in nightly CI
---

Fix SimpleMemoryPipelineChannelTest.assertFetchRecordsTimeoutCorrectly in nightly CI

---

infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/resource-config.json
test/native/native-image-filter/extra-filter.json
test/native/native-image-filter/user-code-filter.json
test/native/pom.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/OpenGaussTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/mode/cluster/ZookeeperTest.java
test/native/src/test/resources/META-INF/native-image/shardingsphere-test-native-test-metadata/resource-config.json
test/native/src/test/resources/test-native/yaml/mode/cluster/zookeeper.yaml

For #29052.
- Add GraalVM Reachability Metadata and corresponding nativeTest for Zookeeper integration.
- The destruction of the Docker Image created by `MySQLTest` and `OpenGaussTest` is required to ensure normal execution of unit tests. This PR uses testcontainers-java to ensure that even if nativeTest fails, the corresponding containers can be forcibly destroyed.
- `org.apache.shardingsphere.test.natived.**` should be excluded in advance in User Code Filter instead of being deferred to Extra Filter processing. This reduces the effort of manually processing JSON. This makes the JSON file change dramatically in this PR.
---

Add GraalVM Reachability Metadata and corresponding nativeTest for Zookeeper integration

---

features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/checker/ReadwriteSplittingRuleConfigurationChecker.java
features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/exception/checker/DataSourceNameNotExistedException.java
features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/checker/ReadwriteSplittingRuleConfigurationCheckerTest.java

Fixes #29459.
Support logic data source when `checkReadeDataSourceNames` for readwrite-splitting.
```yaml
- !READWRITE_SPLITTING
dataSources:
readwrite_prod_ds:
writeDataSourceName: writeShadowDataSource
readDataSourceNames:
- readShadowDataSource
loadBalancerName: random
loadBalancers:
random:
type: RANDOM
- !SHADOW
dataSources:
writeShadowDataSource:
productionDataSourceName: write_prod_ds
shadowDataSourceName: write_shadow_ds
readShadowDataSource:
productionDataSourceName: read_prod_ds
shadowDataSourceName: read_shadow_ds
tables:
...
```

Fixes #29459, support logic data source when `checkReadeDataSourceNames` for readwrite-splitting 

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4

Ref #29490.
- Remove useless createMemOptimizeClause rule in oracle DDLStatement.g4
---

Remove useless createMemOptimizeClause rule in oracle DDLStatement.g4

---

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/data/impl/UnicastDatabaseBackendHandler.java

Currently, performing a unicast will cause the `databaseName` in `connectionSession` changed, which is incorrect.
Related to [#16919](https://github.com/apache/shardingsphere/pull/16919/files#diff-029c44ded8d8f1181a78b83d37adc5f2c7873cbe2c6d16f379f7b36166580f5e)

Restore original databaseName in connectionSession after unicast

---

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/statement/JDBCBackendStatement.java
proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java
proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareParameterMarkerExtractor.java
proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareParameterMarkerExtractorTest.java

- Optimize MySQLComStmtPrepareExecutor logic
---

Optimize MySQLComStmtPrepareExecutor logic

---

infra/common/src/main/java/org/apache/shardingsphere/infra/config/props/temporary/TemporaryConfigurationPropertyKey.java
test/e2e/sql/src/test/resources/env/scenario/db/proxy/mode/cluster/server.yaml
test/e2e/sql/src/test/resources/env/scenario/empty_rules/proxy/mode/cluster/server.yaml
test/e2e/sql/src/test/resources/env/scenario/tbl/proxy/mode/cluster/server.yaml

Fixes #29536.
- Adjust proxy-meta-data-collector-enabled default value to false
---

Adjust proxy-meta-data-collector-enabled default value to false

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4

Fixes #29551.
- Simplify Sharing Specification in Create View Oracle
---

Simplify Sharing Specification in Create View Oracle

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4

Fixes #29559.
- Remove Redundancy in Some Specifications Parser in Oracle
---

Remove Redundancy in Some Specifications Parser in Oracle

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/parameter/ParameterMarkerSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/parameter/impl/ParameterMarkerExpressionSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/MergeStatementBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/MergeStatementBinderTest.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/statement/merge/MergeStatementConverter.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/simple/ParameterMarkerExpressionSegment.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/pagination/limit/ParameterMarkerLimitValueSegment.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/pagination/rownum/ParameterMarkerRowNumberValueSegment.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/ParameterMarkerSegment.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/AbstractSQLStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/dml/MergeStatement.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/MergeStatementAssert.java

- Add ParameterMarkerSegmentBinder logic for Oracle MergeStatementBinder
---

Add ParameterMarkerSegmentBinder logic for Oracle MergeStatementBinder

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/MergeStatementBinder.java

- Fix wrong parameter bind logic for sql translator hint bind
---

Fix wrong parameter bind logic for sql translator hint bind

---

infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/rul/RULExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/SQLRULBackendHandler.java

Remove unused default getRows method from RULExecutor

Remove unused default getRows method from RULExecutor

---

infra/context/src/main/java/org/apache/shardingsphere/infra/connection/refresher/type/table/RenameTableStatementSchemaRefresher.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactory.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactoryTest.java

Fixes #29578.
Since `rename table` needs to update TableContainedRule, there is currently no such mechanism, so `rename` is temporarily set to unsupported to avoid misoperation.

Fix #29578, add RenameTableStatement to UnsupportedSQLStatements in Proxy

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/PLSQL.g4
test/it/parser/src/main/resources/case/ddl/create-function.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-function.xml

Fixes #27920.
- Oracle g4 specialDataType conflict with aggregateClause
---

Oracle g4 specialDataType conflict with aggregateClause

---

kernel/sql-federation/optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/it/TestCases.java
kernel/sql-federation/optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/it/TestCasesLoader.java
mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQL.java
mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoader.java

For #29384.
- Check specific properties when deserializing XML file. This is an alignment to the behavior of the JAXB API. Refer to https://github.com/apache/shardingsphere/pull/29384#discussion_r1424781057 .
- `required` only provides Metadata without detecting Null values, which is actually consistent with the design of the JAXB API. See https://github.com/FasterXML/jackson-dataformat-xml/issues/625 .  I don't think using `@JsonCreator` is a reasonable choice, it brings maintenance trouble. Maybe we can check the Annotation Metadata when needed.
---

Check specific properties when deserializing XML file

---

docs/document/content/user-manual/common-config/builtin-algorithm/metadata-repository.cn.md
docs/document/content/user-manual/common-config/builtin-algorithm/metadata-repository.en.md
mode/type/cluster/repository/provider/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/ConsulRepository.java
mode/type/cluster/repository/provider/consul/src/test/java/org/apache/shardingsphere/mode/repository/cluster/consul/ConsulRepositoryTest.java

Fixes #29419.
- Allow `ConsulRawClient` of `cluster-mode-repository-consul` to be configured on ports other than `8500`. This is a practical requirement for integration testing by `testcontainers-java`. It is impossible for Consul Agent to always occupy port `8500`.
- Solve the problem of multiple undetermined null values. Fixes #29509 . 
- This PR was split from #29588 . This PR only solves a partial problem, it still does not solve the bug that `ConsulRepository.watch()` cannot update the local data source with Consul `1.10.12`/`1.15.8`/ `1.17.1`.
---

Allow `ConsulRawClient` of `cluster-mode-repository-consul` to be configured on ports other than `8500`

---

docs/document/content/user-manual/common-config/builtin-algorithm/expr.cn.md
docs/document/content/user-manual/common-config/builtin-algorithm/expr.en.md
docs/document/content/user-manual/common-config/builtin-algorithm/metadata-repository.cn.md
docs/document/content/user-manual/common-config/builtin-algorithm/metadata-repository.en.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md

For #29052.
- Updates documentation for using Java Agent when building ShardingSphere Proxy Native.
- To make a long story short, https://github.com/oracle/graal/pull/8077 gives a solution to use OpenTelemetry Java Agent when building GraalVM Native Image, which requires the introduction of new GraalVM SDK related APIs. This means that the previous section of ShardingSphere Proxy Native on using Java Agent is outdated.
- This PR also adds to the documentation some phenomena that are only verifiable in unit tests.
---

Updates documentation for using Java Agent when building ShardingSphere Proxy Native

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/MySQLKeyword.g4
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java

- Fix mysql TimeStampDiff function parse
---

Fix mysql TimeStampDiff function parse

---

infra/reachability-metadata/src/main/resources/META-INF/native-image/ch.qos.logback/logback-core/1.2.12/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/com.mysql/mysql-connector-j/8.0.31/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.calcite/calcite-core/1.35.0/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere.elasticjob/elasticjob-lite-core/3.0.4/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
test/native/src/test/resources/META-INF/native-image/shardingsphere-test-native-test-metadata/resource-config.json
test/native/src/test/resources/logback-test.xml

For #29052.
- Host GraalVM Reachability Metadata of `ch.qos.logback:logback-core` to fix Error Log in NativeTest. This brought back the previously deleted https://github.com/apache/shardingsphere/blob/57f947153271ab6b55b4c39004b89dab4692c678/test/native/src/test/resources/logback-test.xml file.
- The GraalVM Reachability Metadata of `ch.qos.logback:logback-core` is also temporarily hosted.
- These Error Logs are similar to the following.
```shell
21:34:27,940 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback-test.xml] at [resource:/logback-test.xml]
21:34:27,940 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs multiple times on the classpath.
21:34:27,940 |-WARN in …
```

Host GraalVM Reachability Metadata of `ch.qos.logback:logback-core` to fix Error Log in NativeTest

---

test/it/parser/src/main/resources/case/dal/explain.xml
test/it/parser/src/main/resources/sql/supported/dal/explain.xml

Ref #27144 
`EXPLAIN PLAN FOR
SELECT  t.calendar_month_desc, SUM(s.amount_sold)
FROM  sales s, times t WHERE s.time_id = t.time_id
GROUP BY t.calendar_month_desc;`
`EXPLAIN PLAN FOR
SELECT SUM(amount_sold)
FROM sales
WHERE TO_CHAR(time_id,'yyyy') = '2000';`
`EXPLAIN PLAN FOR
SELECT SUM(quantity_sold)
FROM sales
WHERE time_id = TO_TIMESTAMP('1-jan-2000', 'dd-mon-yyyy');`
`EXPLAIN PLAN FOR
SELECT *
FROM   sh.customers
WHERE  cust_city='Los Angeles'
AND    cust_state_province='CA';`

Support parsing Oracle EXPLAIN PLAN sql

---

proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java
proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandlerTest.java

- Fix multi statements with specified database name
---

Fix multi statements with specified database name

---

test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/expression/ExpressionAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedExpression.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/xmlquery/ExpectedXmlQueryAndExistsFunctionSegment.java
test/it/parser/src/main/resources/case/dal/explain.xml
test/it/parser/src/main/resources/sql/supported/dal/explain.xml

Ref #27146 
XML query and exists segment parsing supported.

Support parsing Oracle EXPLAIN PLAN sql(27146)

---

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
test/it/parser/src/main/resources/case/dml/insert.xml
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/insert.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #29168, #29167, #29166, #29165.
- support parsing SQL Server distinct from syntax [offical link](https://learn.microsoft.com/zh-cn/sql/t-sql/queries/is-distinct-from-transact-sql?view=sql-server-ver16)
-  provide test case for the issues above
```sql
SELECT * FROM #SampleTempTable WHERE id IS NOT DISTINCT FROM NULL
```
```sql
SELECT * FROM #SampleTempTable WHERE id IS DISTINCT FROM 17
```
```sql
INSERT INTO #SampleTempTable VALUES (10, null)
```
```sql
INSERT INTO #SampleTempTable VALUES (null, null)
```
---

Support parsing SQL Server distinct from

---

kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/channel/memory/MemoryPipelineChannelTest.java
kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClient.java
kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLClientTest.java

- Remove ChannelFuture.sync() in MySQLClient.closeChannel to avoid possible sync() blocking
---

Remove ChannelFuture.sync() in MySQLClient.closeChannel to avoid possible sync() blocking

---

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/_index.en.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md

For #29657.
- Add separate documentation for ShardingSphereDriver's URL configuration.
- Updated documentation for Proxy Native as suggested by https://github.com/apache/shardingsphere/pull/29625#discussion_r1442546079 .
---

Add separate documentation for ShardingSphereDriver's URL configuration

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/metadata/DuplicateSharingActualDataNodeException.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java

- Validate duplicate sharding actual data nodes
---

Validate duplicate sharding actual data nodes

---

docs/document/content/user-manual/shardingsphere-proxy/startup/bin.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/bin.en.md

For #29738, update proxy document.

Update proxy document for Etcd.

---

proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowDatabasesExecutor.java
proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowDatabasesExecutorTest.java
test/e2e/sql/src/test/resources/cases/dal/dataset/db/mysql/show_databases.xml
test/e2e/sql/src/test/resources/cases/dal/dataset/dbtbl_with_readwrite_splitting/mysql/show_databases.xml
test/e2e/sql/src/test/resources/cases/dal/dataset/dbtbl_with_readwrite_splitting_and_encrypt/mysql/show_databases.xml
test/e2e/sql/src/test/resources/cases/dal/dataset/encrypt/mysql/show_databases.xml
test/e2e/sql/src/test/resources/cases/dal/dataset/encrypt_and_readwrite_splitting/mysql/show_databases.xml
test/e2e/sql/src/test/resources/cases/dal/dataset/readwrite_splitting/mysql/show_databases.xml
test/e2e/sql/src/test/resources/cases/dal/dataset/sharding_and_encrypt/mysql/show_databases.xml
test/e2e/sql/src/test/resources/cases/dal/dataset/tbl/mysql/show_databases.xml

Fixes #29757.
```sql
mysql> show databases;
+--------------------+
| schema_name        |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| shardingsphere     |
| sys                |
+--------------------+
```
```sql
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| shardingsphere     |
| sys                |
+--------------------+
```
This is come from the result set meta data of native MySQL
```java
// show databases from mysql
com.mysql.jdbc.ResultSetMetaData@197d671 - Field level information: com.mysql.jdbc.Field@402e37bc[catalog=information_schema,tableName=SCHEMATA,originalTableName=SCHEMATA,columnName=Database,originalColumnNam …
```

Fix label of ShowDatabasesExecutor

---

.github/workflows/graalvm.yml
.github/workflows/nightly-build.yml
.github/workflows/nightly-ci.yml
distribution/proxy-native/pom.xml
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoader.java
pom.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/commons/FileTestUtils.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/mode/cluster/EtcdTest.java
test/native/src/test/resources/test-native/yaml/features/sharding.yaml

For #29052.
- Updates the minimum GraalVM CE version for compiling ShardingSphere's Native Image products to JDK 21.0.2. Based on the fix in https://github.com/oracle/graal/pull/8039, ShardingSphere can now be compiled to Native Image by GraalVM For JDK 21. Judging from the way Web Frameworks like Spring Boot handle it, we should follow the changes in GraalVM.
- Handle the table non-existence error in https://github.com/apache/shardingsphere/actions/runs/7567041551/job/20605451778?pr=29764 . Wait for a while after executing CREATE TABLE SQL before executing INSERT SQL.
- This PR will temporarily break the availability of `shardingsphere-infra-expr-espresso`. Since Truffle Espresso was refactored starting with GraalVM Truffle 23.1.0, Truffle Espresso …

Updates the minimum GraalVM CE version for compiling ShardingSphere's Native Image products to JDK 21.0.2

---

.github/workflows/nightly-check.yml
.github/workflows/schedule-report.yml

- update the JDK from 11 to 17 for sonar related plugin
all sonar plugin deprecated JDK 11 support, force to use JDK 17.
> The version of Java (11.0.21) used to run this analysis is deprecated, and SonarCloud no longer supports it. Please upgrade to Java 17 or later.
---

Refactor : update the JDK from 11 to 17 for sonar related plugin

---

docs/document/content/user-manual/error-code/sql-error-code.cn.md
docs/document/content/user-manual/error-code/sql-error-code.en.md
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/data/PipelineUnexpectedDataRecordOrderException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/sink/type/PipelineDataSourceSink.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/DataRecord.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/group/DataRecordGroupEngine.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/DataRecordTest.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/group/DataRecordGroupEngineTest.java

- Recover DataRecordMerger by revert PR 25307
---

Recover DataRecordGroupEngine

---

distribution/proxy/src/main/release-docs/LICENSE
pom.xml

Fixes #29624.
- Updates Curator to 5.6.0 to avoid Cache loading failure when there are too many child nodes. Refer to https://github.com/apache/curator/pull/480 .
---

Updates Curator to 5.6.0 to avoid Cache loading failure when there are too many child nodes

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/listener/PipelineContextManagerLifecycleListener.java
kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/ConsistencyCheckJobType.java

- Manually dispatch pipeline ElasticJob events if job `disable=false`
---

Manually dispatch pipeline ElasticJob events when ShardingSphere-Proxy start

---

kernel/single/core/src/test/java/org/apache/shardingsphere/single/metadata/reviser/index/SingleIndexReviserTest.java

Fixes #28518.
- Add unit tests for SingleIndexReviser
---

#28518 Add unit tests for SingleIndexReviser

---

infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/NotExpressionBinderTest.java

Fixes #28504 
-
Added unit tests for NotExpressionBinder.java
---

NotExpressionBinder unit test added

---

distribution/proxy/Dockerfile

Fixes #29847.
- Change the JDK runtime of the Dockerfile that builds ShardingSphere Proxy from JDK17 to JDK21.
---

Change the JDK runtime of the Dockerfile that builds ShardingSphere Proxy from JDK17 to JDK21

---

features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleExecutor.java
features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/update/AlterMaskRuleExecutor.java
features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/update/AlterMaskRuleStatementUpdaterTest.java
features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/AlterReadwriteSplittingRuleExecutor.java
features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/AlterDefaultShadowAlgorithmExecutor.java
features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/update/AlterShadowRuleExecutor.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterDefaultShardingStrategyExecutor.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterShardingTableReferenceRuleExecutor.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterShardingTableRuleExecutor.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/AlterDefaultShardingStrategyStatementUpdaterTest.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/AlterShardingTableRuleStatementUpdaterTest.java
infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/type/rdl/rule/database/DatabaseRuleAlterExecutor.java
kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableExecutor.java
kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/SetDefaultSingleTableStorageUnitExecutor.java
kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/UnloadSingleTableExecutor.java
kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableStatementUpdaterTest.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/rule/database/execute/type/AlterDatabaseRuleRDLExecuteEngine.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/rule/database/execute/type/CreateDatabaseRuleRDLExecuteEngine.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rdl/rule/legacy/LegacyRuleDefinitionBackendHandler.java

Refactor CreateDatabaseRuleRDLExecuteEngine & AlterDatabaseRuleRDLExecuteEngine
No need to judge `isSinglePersistNode` anymore.

Simplify Create/Alter DatabaseRuleRDLExecuteEngine

---

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.en.md
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/classpath/AbstractClasspathURLProvider.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/classpath/ClasspathURLProvider.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/classpath/ClasspathWithEnvironmentURLProvider.java
jdbc/core/src/main/resources/META-INF/services/org.apache.shardingsphere.driver.jdbc.core.driver.ShardingSphereURLProvider
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/classpath/ClasspathWithEnvironmentURLProviderTest.java
jdbc/core/src/test/resources/config/driver/foo-driver-environment-variables-fixture.yaml

For #29657.
- Add ClasspathURLProvider implementation that reads environment variables.
---

Add ClasspathURLProvider implementation that reads environment variables

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/sink/type/PipelineDataSourceSink.java

- Refactor PipelineDataSourceSink: 1) Disable connection one global transaction on error retry, 2) Add log on update error
---

Refactor PipelineDataSourceSink

---

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/absolutepath/AbstractAbsolutePathURLProvider.java

Fixes https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=apache_shardingsphere&open=AY1YzHwRFXNlR4nWuJUU&tab=code .
- Fix incorrect implementation of AbstractAbsolutePathURLProvider. Refer to https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=apache_shardingsphere&open=AY1YzHwRFXNlR4nWuJUU&tab=code .
---

Fix incorrect implementation of AbstractAbsolutePathURLProvider

---

kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/SQLFederationExecutorContext.java
kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/PreviewExecutor.java

- Refactor PreviewExecutor logic
- rename executionUnits to previewExecutionUnits in SQLFederationExecutorContext
---

Refactor PreviewExecutor logic and rename executionUnits to previewExecutionUnits in SQLFederationExecutorContext

---

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4
parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/DMLStatement.g4
parser/sql/dialect/sqlserver/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/SQLServerStatement.g4
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/UpdateStatementHandler.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/segment/sqlserver/hint/OptionHintSegment.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/sqlserver/dml/SQLServerUpdateStatement.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/UpdateStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/hint/ExpectedOptionHint.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/dml/UpdateStatementTestCase.java
test/it/parser/src/main/resources/case/dml/update.xml
test/it/parser/src/main/resources/sql/supported/dml/update.xml

Fixes #29185.
- support point setXY function feature
- support with table hint and option hint feature
- fix visitSetAssignmentsClause duplicate column
- support sql
```
1. UPDATE dbo.Cities  
SET Location.SetXY(23.5, 23.5)  
WHERE Name = 'Anchorage'
2. UPDATE Production.Product  
WITH (TABLOCK)  
SET ListPrice = ListPrice * 1.10  
WHERE ProductNumber LIKE 'BK-%'
3. UPDATE Production.Product  
SET ListPrice = ListPrice * 1.10  
WHERE ProductNumber LIKE @Product  
OPTION (OPTIMIZE FOR (@Product = 'BK-%') )
4. UPDATE YearlyTotalSales  
SET YearlySalesAmount=  
(SELECT SUM(SalesAmount) FROM FactInternetSales WHERE OrderDateKey >=20040000 AND OrderDateKey < 20050000)  
WHERE Year=2004
5. UPDATE dbo.Table2   
SET dbo.Table2.ColB = dbo.Table2.ColB + …
```

Support parsing SQL Server UPDATE dbo.Cities sql #29185

---

mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoader.java

Fix weblogic.utils.zip.ZipURLConnection cannot be cast to java.net.JarURLConnection issue.

---

infra/database/type/testcontainers/src/main/java/org/apache/shardingsphere/infra/database/testcontainers/type/TcTiDBDatabaseType.java
infra/database/type/testcontainers/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.database.core.type.DatabaseType
infra/database/type/testcontainers/src/test/java/org/apache/shardingsphere/infra/database/testcontainers/type/TestcontainersDatabaseTypeTest.java

For #29388.
- Add support to TestContainers JDBC URL of TiDB to the optional module. Such as `jdbc:tc:tidb://hostname/databasename`. Refer to https://github.com/testcontainers/testcontainers-java/blob/1.19.4/modules/tidb/src/test/java/org/testcontainers/jdbc/tidb/TiDBJDBCDriverTest.java .
- Since TiDB uses MySQL's JDBC Driver, it is routed to the MySQL dialect. Refer to https://docs.pingcap.com/tidb/stable/dev-guide-choose-driver-or-orm#java-drivers .
---

Add support to TestContainers JDBC URL of TiDB to the optional module

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/datetime/IntervalShardingAlgorithm.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/datetime/IntervalShardingAlgorithmTest.java

Fixes #28909.
- Make IntervalShardingAlgorithm loosely match `String`. Prior to this PR, `org.apache.shardingsphere.sharding.algorithm.sharding.datetime.IntervalShardingAlgorithm` did not consider the case where the string length of the shard key was smaller than `datetime-pattern` after the shard key was formatted as `java.lang.String`. This PR further attempts to use a substring of `datetime-pattern` to parse shard keys.
---

Make IntervalShardingAlgorithm loosely match `String`

---

test/it/parser/src/main/resources/case/dml/insert.xml
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/insert.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #29191.
- Support the SQL case parse in issue 29191.
``` sql 
SELECT page_count,
compressed_page_count,
forwarded_record_count,
*
FROM sys.dm_db_index_physical_stats(db_id(), object_id('t3'), NULL, NULL, 'SAMPLED')
```
```sql
SELECT backup_size/compressed_backup_size FROM msdb..backupset
```
```sql
INSERT INTO sales VALUES (N'Canada', N'Alberta', 100)
```
---

Support parsing SQL Server SELECT page_count, sql

---

parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalSQLParserIT.java
test/it/parser/src/main/resources/sql/unsupported/unsupported.xml

- Add EOF to throw exception when parse distsql rollback migration statement
---

Add EOF to throw exception when parse distsql rollback migration statement

---

distribution/agent/pom.xml
distribution/jdbc/pom.xml
distribution/proxy/pom.xml
pom.xml

Fixes #29990.
- refactor the jandex plugin into release profile 
- refactor the maven-source-plugin into release profile
---

Refactor : refactor the jandex and source plugin into release profile (#29990)

---

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.en.md
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/absolutepath/AbsolutePathURLProvider.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/absolutepath/AbsolutePathWithEnvironmentURLProvider.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/classpath/ClasspathURLProvider.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/classpath/ClasspathWithEnvironmentURLProvider.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/classpath/ClasspathWithSystemPropsURLProvider.java
jdbc/core/src/main/resources/META-INF/services/org.apache.shardingsphere.driver.jdbc.core.driver.ShardingSphereURLProvider
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/classpath/ClasspathWithSystemPropsURLProviderTest.java
jdbc/core/src/test/resources/config/driver/foo-driver-system-properties-fixture.yaml
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/MySQLTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/OpenGaussTest.java
test/native/src/test/resources/test-native/yaml/databases/mysql.yaml
test/native/src/test/resources/test-native/yaml/databases/opengauss.yaml

For #29052.
- Add ClasspathURLProvider implementation that reads system properties. For nativeTest, we need a way to dynamically define properties in a YAML file. To cover the JDBC Driver scenario, I don't think the lower level Java API should be used in nativeTest.
- This PR simultaneously modifies some nativeTest, especially to further prevent the problem discovered by #29755 that the ports involved in MySQL's nativeTest are occupied by unknown applications.
---

Add ClasspathURLProvider implementation that reads system properties

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueInOperatorGenerator.java

- Refactor ConditionValueInOperatorGenerator logic
---

Refactor ConditionValueInOperatorGenerator logic

---

kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/ConsistencyCheckJobAPI.java

Example job props
```
props:
stop_time: '2024-02-06 16:38:35'
start_time_millis: '1707208715095'
run_count: '1'
```
- The stop_time_millis is removed, so use `stop_time` instead
---

Fix show consistency check status `stop_time` display

---

docs/document/content/user-manual/common-config/builtin-algorithm/expr.cn.md
docs/document/content/user-manual/common-config/builtin-algorithm/expr.en.md
infra/expr/type/espresso/pom.xml
infra/expr/type/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParser.java
infra/expr/type/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/ReflectContext.java
infra/expr/type/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/ReflectValue.java
infra/expr/type/espresso/src/test/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParserTest.java
pom.xml

For #29052.
- Bump GraalVM SDK version to 23.1.2 to allow `infra-expr-espresso` to be used under Hotspot JDK 21. Starting with GraalVM 23.1.0 For JDK 21, Truffle API can now be used independently of GraalVM. On the ShardingSphere side, it is necessary to avoid introducing JDK21 bytecode during compilation.
- Use the `build/libs/` directory on the classpath to store additional jars. Because this seems more in line with general intuition, like https://github.com/spring-projects-experimental/spring-boot-testjars .
- Due to GR-44722 on the `GraalVM for JDK 17 and GraalVM for JDK 20 (Internal Version 23.0.0)` milestones, it is now possible to determine whether a JVM is a GraalVM CE through the system property of `java.vm.vendor`. Not sure if I need to …

Bump GraalVM SDK version to 23.1.2 to allow `infra-expr-espresso` to be used under Hotspot JDK 21

---

test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/PostgresTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/SQLServerTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/mode/cluster/EtcdTest.java

For #30003.
- Fixes `@EnabledInNativeImage` failure in some unit tests. According to https://github.com/apache/shardingsphere/actions/runs/7804087102/job/21285307640 , unit tests under GraalVM Native Image do not execute when `@EnabledInNativeImage` is on the class. This needs to be investigated on the Junit5 side.
```shell
JUnit Platform on Native Image - report
----------------------------------------
org.apache.shardingsphere.test.natived.jdbc.features.MaskTest > assertMaskInLocalTransactions() SUCCESSFUL
org.apache.shardingsphere.test.natived.jdbc.features.ShadowTest > assertShadowInLocalTransactions() SUCCESSFUL
org.apache.shardingsphere.test.natived.jdbc.features.ShardingTest > assertShardingInLocalTransactions() SUCCESSFUL …
```

Fixes `@EnabledInNativeImage` failure in some unit tests

---

jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/ArgsUtils.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/absolutepath/AbsolutePathURLProvider.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/absolutepath/AbsolutePathWithEnvironmentURLProvider.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/absolutepath/AbstractAbsolutePathURLProvider.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/classpath/AbstractClasspathURLProvider.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/classpath/ClasspathURLProvider.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/classpath/ClasspathWithEnvironmentURLProvider.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/classpath/ClasspathWithSystemPropsURLProvider.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/driver/ShardingSphereURLManagerTest.java
jdbc/core/src/test/java/org/apache/shardingsphere/driver/jdbc/core/driver/spi/classpath/ClasspathWithSystemPropsURLProviderTest.java

For https://github.com/apache/shardingsphere/pull/29995#discussion_r1477636178 .
- Fix nightly build CI on Windows 11. Refer to https://github.com/apache/shardingsphere/actions/runs/7804087102 .
- Fix the following Sonar issue.
- https://sonarcloud.io/project/issues?open=AY1du-r_ewgKJ7XcZbVO&id=apache_shardingsphere
- https://sonarcloud.io/project/issues?open=AY1VlKevuUJFToG6dRU9&id=apache_shardingsphere
-  https://sonarcloud.io/project/issues?open=AY1VlKfAuUJFToG6dRU-&id=apache_shardingsphere
- https://sonarcloud.io/project/issues?open=AY13sgUX1HjqolwrBN9Y&id=apache_shardingsphere
---

Fix nightly build CI on Windows 11

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/hint/HintInlineShardingAlgorithm.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/ComplexInlineShardingAlgorithm.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/InlineShardingAlgorithm.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/fixture/sharding/CoreHintShardingAlgorithmFixture.java
infra/expr/core/src/test/java/org/apache/shardingsphere/infra/expr/core/InlineExpressionParserFactoryTest.java
infra/expr/spi/pom.xml
infra/expr/spi/src/main/java/org/apache/shardingsphere/infra/expr/spi/InlineExpressionParser.java
infra/expr/type/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParser.java
infra/expr/type/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/ReflectValue.java
infra/expr/type/espresso/src/test/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParserTest.java
infra/expr/type/groovy/pom.xml
infra/expr/type/groovy/src/main/java/org/apache/shardingsphere/infra/expr/groovy/GroovyInlineExpressionParser.java
infra/expr/type/groovy/src/test/java/org/apache/shardingsphere/infra/expr/groovy/GroovyInlineExpressionParserTest.java
infra/expr/type/literal/src/test/java/org/apache/shardingsphere/infra/expr/literal/LiteralInlineExpressionParserTest.java

For #29052.
- Refactor InlineExpressionParser to prevent exposing Groovy API. Looking at the overall situation, the use of `groovy.lang.Closure` is rigid, and there is no need to expose additional Groovy classes. This also helps further encapsulate other languages under the GraalVM Truffle API. Such as JavaScript( https://www.graalvm.org/javascript/ ), Python( https://www.graalvm.org/python/ ) and Ruby( https://www.graalvm.org/ruby/ ).
- Avoid using `org.graalvm.polyglot.Value.toString()` in EspressoInlineExpressionParser. The call to `toString()` seems to be due to a limitation of early graal-sdk, where the String should be fetched directly from the guest JVM.
---

Refactor InlineExpressionParser to prevent exposing Groovy API

---

docs/document/content/user-manual/common-config/builtin-algorithm/expr.cn.md
docs/document/content/user-manual/common-config/builtin-algorithm/expr.en.md
infra/expr/type/espresso/src/test/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParserTest.java

Fixes https://github.com/apache/shardingsphere/actions/runs/7804087102/job/21285309544 .
- Block unit tests that execute EspressoInlineExpressionParserTest on MacOS and Windows. 
- Due to the limitations of https://www.graalvm.org/jdk21/reference-manual/java-on-truffle/faq/#does-java-running-on-truffle-run-on-hotspot-too , this module is only ready on Linux when used in environments other than GraalVM Native Image.
- I know this is kind of funny, but Espresso is an implementation of the Truffle API and it can be used in Native Image built in MacOS/Windows/Linux. But if the standard core Java library is provided by HotSpot JDK, it is only available under Linux. Espresso relies on glibc's [dlmopen](https://man7.org/linux/man-pages/man3/dlopen.3.html) …

Block unit tests that execute EspressoInlineExpressionParserTest on MacOS and Windows

---

proxy/bootstrap/src/test/java/org/apache/shardingsphere/proxy/SPIMatchedCheckerTest.java

- Add SPIMatchedCheckerTest to verify invalid SPI registry. Check SPI impl registry in `META-INF/services/`, SPI package starts with `org.apache.shardingsphere.`
Checked cases:
- Name of SPI impl class in `META-INF/services/` is wrong
- Name of SPI interface class of SPI impl is wrong
- SPI interface class is assignable from SPI service class
---

Add SPIMatchedCheckerTest to verify invalid SPI registry

---

docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.en.md
kernel/transaction/type/base/seata-at/pom.xml
kernel/transaction/type/base/seata-at/src/test/resources/file.conf
kernel/transaction/type/base/seata-at/src/test/resources/seata.conf
pom.xml

Fixes #22356 .
- Bump `io.seata:seata-all` for testing to 2.0.0. This involves updating unit tests. Split this PR from the #30138 side for clarification.
- According to https://github.com/apache/incubator-seata/issues/6347 , `service.enableDegrade` has been replaced by `client.tm.degradeCheck`.
- According to https://seata.apache.org/docs/v1.5/ops/upgrade , the default transaction group has been changed from `my_test_tx_group` to `default_tx_group`.
- Document the problems with `org.antlr:antlr4-runtime:4.8` of Seata Client. On the ShardingSphere side `4.10.1` is used.
- Clarify that the `io.seata.spring.annotation.GlobalTransactional` annotation should be avoided.
- Fixes #22356 .
- Fixes #29681 .
- Fixes #29712 .
- Fixes #24586 .
- Fixes #24735 .
- …

Bump `io.seata:seata-all` for testing to 2.0.0

---

infra/common/src/main/java/org/apache/shardingsphere/infra/yaml/config/pojo/YamlRootConfiguration.java
jdbc/core/src/main/java/org/apache/shardingsphere/driver/api/yaml/YamlJDBCConfiguration.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/config/ProxyConfigurationLoader.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/config/yaml/YamlProxyDatabaseConfiguration.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportMetaDataExecutorTest.java

- Remove deprecated schemaName in YamlRootConfiguration
---

Remove deprecated schemaName in YamlRootConfiguration

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNode.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/registrycenter/repository/job/PipelineJobCheckGovernanceRepository.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/PipelineMetaDataNodeTest.java
kernel/data-pipeline/scenario/consistencycheck/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/ConsistencyCheckJobAPI.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/registrycenter/repository/PipelineGovernanceFacadeTest.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/consistencycheck/api/impl/ConsistencyCheckJobAPITest.java

- Fix consistency check job id not persisted in parent job after starting. If commit/rollback migration job before consistency check is finished, then consistency check job could not be dropped.
---

Fix consistency check job id not persisted in parent job after starting

---

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/LiteralExpressionConverter.java

Ref #30169.
- Revise pr 30169 to support number types
---

Revise pr 30169 to support number types

---

jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AbstractStatementAdapter.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
jdbc/src/main/java/org/apache/shardingsphere/driver/state/circuit/statement/CircuitBreakerPreparedStatement.java

- Adjust jdbc processId to statement level to avoid monitor block when run benchmarksql
---

Adjust jdbc processId to statement level to avoid monitor block when run benchmarksql

---

infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/YamlConfiguration.java
infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/YamlEngine.java
infra/util/src/test/java/org/apache/shardingsphere/infra/util/yaml/YamlEngineTest.java
infra/util/src/test/java/org/apache/shardingsphere/infra/util/yaml/fixture/shortcuts/YamlShortcutsConfigurationFixture.java
infra/util/src/test/resources/yaml/empty-config.yaml
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/config/yaml/config/YamlPipelineProcessConfiguration.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/PipelineProcessConfigurationPersistService.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/result/yaml/YamlTableDataConsistencyCheckResultSwapperTest.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/config/ProxyConfigurationLoader.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/config/yaml/YamlProxyDatabaseConfiguration.java

- Modify unmarshal method to return a default object when yaml is empty
---

Modify unmarshal method to return a default object when yaml is empty

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/complex/ShardingComplexRoutingEngine.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/standard/ShardingStandardRoutingEngine.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/complex/ShardingComplexRoutingEngineTest.java

Fixes #30005.
- Fix routing error when joining tables in uppercase
+ When the table sharding rule is lowercase，but the table name is uppercase in the executed sql，the correct logicTableName cannot be found
+ When the query is isShardingStandardQuery, it will enter the getLogicTableName method, but join queries will not enter this method, resulting in an error in obtaining the logic table.
---

Fix routing error when joining tables in uppercase

---

parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java

Fixes #26006.
- Fix postgreSQL NPE when parse columnRef
---

Fix postgreSQL NPE when parse columnRef

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
test/it/parser/src/main/resources/case/ddl/create-table.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml

Fixes #27099.
- support parsing create table table annotations [Table Annotations](https://docs.oracle.com/en/database/oracle/oracle-database/21/jjdbc/statement-and-resultset-caching.html#GUID-1764F69A-8E6B-4B78-AAF0-1D6257B3BBE5)
- support parsing create table parallel clause [Parallel](https://docs.oracle.com/cd/A97630_01/server.920/a96524/c20paral.htm)
```sql
CREATE TABLE employees_obj
( e_name   VARCHAR2(100),
e_number NUMBER,
e_dept   REF department_typ SCOPE IS departments_obj_t );
```
```sql
CREATE TABLE foo (a NUMBER, b VARCHAR2(20)) RESULT_CACHE (MODE FORCE);
```
```sql
CREATE TABLE employees_temp AS SELECT * FROM EMPLOYEES;
```
```sql
CREATE TABLE hr.admin_emp_dept
PARALLEL COMPRESS
AS SELECT * FROM hr.employees
WHERE department_id = 10; …
```

Support parsing Oracle CREATE Table Annotations and parallel clause

---

kernel/sql-federation/executor/pom.xml
kernel/sql-federation/optimizer/pom.xml
pom.xml

- Move calcite and immutables dependency to sql federation optimizer module
---

Move calcite and immutables dependency to sql federation optimizer module

---

infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
infra/url/type/classpath/src/main/java/org/apache/shardingsphere/infra/url/classpath/ClassPathURLLoader.java
mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoader.java
test/native/src/test/resources/META-INF/native-image/shardingsphere-test-native-test-metadata/reflect-config.json
test/native/src/test/resources/META-INF/native-image/shardingsphere-test-native-test-metadata/resource-config.json

For #30139.
- Fixes ClassPathURLLoader cannot find files under GraalVM Native Image. ~~If we can't use `java.io.InputStream` in this class, then obviously we need to manually open `NativeImageResourceFileSystem` under GraalVM Native Image.~~ Split this PR from the #30138 side for clarification.
- Creating a `java.io.File` instance will break usage in both JAR(`ZipFileSystemProvider`) and GraalVM Native Image(`NativeImageResourceFileSystemProvider`). Refer to https://github.com/oracle/graal/issues/7804 .
- Obviously, developers cannot create `java.io.File` instances via URLs like `resource:file:/resources/{entry}` or `jar:file:/resources/{entry}`, because creating `java.io.File` instances is only supported by the File System corresponding to the URL …

Fixes ClassPathURLLoader cannot find files under GraalVM Native Image

---

infra/url/core/src/main/java/org/apache/shardingsphere/infra/url/core/arg/URLArgumentLine.java

Fixes #30289.
- https://github.com/apache/shardingsphere/issues/30289
---

Fix typo in URLArgumentLine class

---

docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.en.md
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/type/UnsupportedStorageTypeException.java
infra/expr/spi/src/main/java/org/apache/shardingsphere/infra/expr/spi/InlineExpressionParser.java

Fixes #29712.
- Updates documentation for restrictions on Seata’s Spring Boot Starter and RPC.
- Fixes #29681
- Fixes #29712
- Added a missing JavaDoc description For `InlineExpressionParser`. For #30038 .
---

Updates documentation for restrictions on Seata’s Spring Boot Starter

---

docs/document/content/user-manual/common-config/builtin-algorithm/encrypt.cn.md
docs/document/content/user-manual/common-config/builtin-algorithm/encrypt.en.md

- Delete the 'CHAR DIGEST LIKE' section in encrypt.md
---

Delete the 'CHAR DIGEST LIKE' section in encrypt.md

---

.asf.yaml

- Update ShardingSphere collaborators list
---

Update ShardingSphere collaborators list

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/MatchingTableInventoryChecker.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/RecordSingleTableInventoryCalculator.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/PipelineJobCanceledException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/PipelineJobCancelingException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractSeparablePipelineJob.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/runner/TransmissionTasksRunner.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/check/consistency/MigrationDataConsistencyChecker.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/preparer/MigrationJobPreparer.java

- Throw PipelineJobCancelingException on task canceling or job stopping
- Merge several exception handling into AbstractSeparablePipelineJob.execute
- Just stop current job item when any job item failure but not whole job. And also stop job item when it succeed
---

Refactor pipeline job cancel and exception handling

---

kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/data/pipeline/migration/distsql/handler/update/MigrateTableExecutor.java
kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/data/pipeline/migration/distsql/handler/update/RegisterMigrationSourceStorageUnitExecutor.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/api/MigrationJobAPI.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/scenario/migration/api/impl/MigrationJobAPITest.java

- Add unsupported mode type check at migration
- Rename method to registerMigrationSourceStorageUnits;
---

Add unsupported mode type check at migration

---

infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/resource-config.json
infra/util/src/main/java/org/apache/shardingsphere/infra/util/directory/ClasspathResourceDirectoryReader.java

Fixes #30345.
- Prevent ClasspathResourceDirectoryReader from accessing closed NativeImageResourceFileSystem . Call @iamhucong to help review.
- Check whether NativeImageResourceFileSystem has been created by a third-party dependency. Fixes #30344 .
---

Prevent ClasspathResourceDirectoryReader from accessing closed NativeImageResourceFileSystem

---

infra/url/core/src/test/java/org/apache/shardingsphere/infra/url/core/ShardingSphereURLLoadEngineTest.java

Fixes https://github.com/apache/shardingsphere/actions/runs/8085008196/job/22091618196.
- Fixes ShardingSphereURLLoadEngineTest failure on Windows 11 .
---

Fixes ShardingSphereURLLoadEngineTest failure on Windows 11

---

parser/sql/dialect/oracle/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/OracleStatement.g4
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalSQLParserIT.java
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Link #29988.
- Fix oracle parse show roles error when add EOF
- Fix cases
+ select_with_expressions_in_projection
+ select_with_model_in
+ set_all_expect_roles
+ set_all_expect_role cases
---

Fix oracle parse show roles error when add EOF

---

infra/util/src/test/java/org/apache/shardingsphere/infra/util/directory/ClasspathResourceDirectoryReaderTest.java

Fixes https://github.com/apache/shardingsphere/actions/runs/8100557441/job/22138852967 .
- Fixes ClasspathResourceDirectoryReaderTest failure on Windows 11.
---

Fixes ClasspathResourceDirectoryReaderTest failure on Windows 11

---

distribution/proxy/src/main/release-docs/LICENSE
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/narayana.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/narayana.en.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/transaction.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/transaction.en.md
docs/document/content/user-manual/shardingsphere-proxy/startup/dependencies-download/add_Narayana_dependency.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/dependencies-download/add_Narayana_dependency.en.md
examples/pom.xml
pom.xml

Fixes https://github.com/apache/shardingsphere/security/dependabot/77 .
- Bump pgjbdc version to prevent CVE-2024-1597 from being passed in Proxy. Synchronously update the dependencies involved in example. It seems that dependabot has some issues and it does not open PRs for dependencies with full CVE scores.
- Fixes https://github.com/apache/shardingsphere/security/dependabot/76 . 
- Fixes #24450 . See CVE-2022-1471.
-  As part of streamlining the content of #27976, updating narayana will be independently moved onto this PR.
---

Bump pgjbdc version to prevent CVE from being passed in Proxy

---

infra/util/src/main/java/org/apache/shardingsphere/infra/util/directory/ClasspathResourceDirectoryReader.java

Fixes https://github.com/apache/shardingsphere/actions/runs/8124502923/job/22206061492 .
- Fixes #30361 causing ClasspathResourceDirectoryReaderTest to fail on Windows.
---

Fixes ClasspathResourceDirectoryReaderTest to fail on Windows.

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DCLStatement.g4
parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalSQLParserIT.java

- Adjust the g4 file to support Oracle grant syntax
---

Fix parser Oracle GRANT grammar error

---

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/OpenGaussContainer.java

- Use opengauss/opengauss:3.1.0 to replace enmotech/opengauss:3.0.0 image
---

Use opengauss/opengauss:3.1.0 to replace enmotech/opengauss:3.0.0 image

---

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/OpenGaussContainer.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/BaseDMLE2EIT.java

- Fix date format exception caused by openGauss data type return timestamp date type
---

Fix date format exception caused by openGauss data type return timestamp date type

---

test/e2e/sql/src/test/resources/env/scenario/passthrough/proxy/conf/opengauss/database-passthrough.yaml

- Add stringtype=unspecified in openGauss jdbc url to solve passthrough uuid insert exception
---

Add stringtype=unspecified in openGauss jdbc url to solve passthrough uuid insert exception

---

distribution/proxy/src/main/release-docs/LICENSE
infra/expr/type/espresso/pom.xml
infra/expr/type/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParser.java
infra/expr/type/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/ReflectContext.java
infra/expr/type/espresso/src/main/java/org/apache/shardingsphere/infra/expr/espresso/ReflectValue.java
infra/expr/type/espresso/src/test/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParserTest.java
pom.xml

Fixes https://github.com/apache/shardingsphere/actions/runs/8144874341/job/22259936246 .
- Refactor EspressoInlineExpressionParser to use Truffle Context with life cycle. Logically no Context instance should be retained here.
- Bump Groovy version to 4.0.19 to try to get around unit test timeouts. 
- Prevent related unit tests from running on stock JDK21. For https://github.com/apache/shardingsphere/actions/runs/8144874341/job/22259936246 . This problem seems quite strange, because https://github.com/apache/shardingsphere/actions/runs/8039815962/job/21957220025 from a week ago is still working fine. Maybe there is something wrong on the GraalVM Truffle side. This requires additional investigation.
- Fix incorrect file separator used by espresso …

Refactor EspressoInlineExpressionParser to use Truffle Context with life cycle

---

docs/document/content/user-manual/error-code/sql-error-code.cn.md
docs/document/content/user-manual/error-code/sql-error-code.en.md
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/MissingRequiredTargetDatabaseException.java
kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/data/pipeline/migration/distsql/handler/update/MigrateTableExecutor.java

- Check targetDatabaseName is valid at MigrateTableExecutor
---

Revise MissingRequiredTargetDatabaseException and check target database is exists

---

infra/util/src/test/java/org/apache/shardingsphere/infra/util/directory/ClasspathResourceDirectoryReaderTest.java

Fixes https://github.com/apache/shardingsphere/actions/runs/8176654071/job/22356570385 .
- Fixes ClasspathResourceDirectoryReaderTest execution failing on Windows 11 CI .
---

Fixes ClasspathResourceDirectoryReaderTest execution failing on Windows 11 CI

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/persist/PipelineJobProgressPersistService.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java

- Compatible with PostgreSQLMigrationGeneralE2EIT failure for now. Need to improve PostgreSQLMigrationGeneralE2EIT later (missing incremental progress sometimes)
---

Compatible with PostgreSQLMigrationGeneralE2EIT failure

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/persist/PipelineJobProgressPersistContext.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/persist/PipelineJobProgressPersistService.java
kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPlugin.java
kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPluginTest.java

Related to #30434
- Fix TestDecodingPlugin.decode BEGIN TX and COMMIT TX event. Position lost. Affect breakpoint resuming
- Recover previous persisting nonnull check on force persisting progress to avoid invalid progress overwriting
- Print exception on job progress persisting failure. So persisting exception could be found early
---

Fix TestDecodingPlugin.decode BEGIN TX and COMMIT TX event

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractSeparablePipelineJob.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/persist/PipelineJobProgressPersistContext.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/persist/PipelineJobProgressPersistService.java

- Improve unhandled event count measuring in job progress persist service
- Try to persist job progress immediately when job item execute successfully. Benefit for breakpoint resuming
---

Improve job progress persisting

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4
test/it/parser/src/main/resources/case/dml/merge.xml
test/it/parser/src/main/resources/sql/supported/dml/merge.xml

Fixes #30453.
- Support oracle merge statement parse when write not matched first
---

Support oracle merge statement parse when write not matched first

---

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/driver/jdbc/JDBCExecutor.java
infra/session/src/main/java/org/apache/shardingsphere/infra/session/connection/ConnectionContext.java
infra/session/src/main/java/org/apache/shardingsphere/infra/session/connection/transaction/TransactionConnectionContext.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManager.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionXAHandler.java

- Modify local transactions to be executed in parallel
---

Modify local transactions to be executed in parallel

---

features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/provider/BroadcastImportRuleConfigurationProvider.java
features/broadcast/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.engine.update.ral.rule.spi.database.ImportRuleConfigurationProvider
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/YamlDatabaseConfigurationImportExecutor.java

For #30190 .
- Add BroadcastImportRuleConfigurationProvider
---

Add BroadcastImportRuleConfigurationProvider

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DALStatement.g4
test/it/parser/src/main/resources/sql/unsupported/unsupported.xml

Ref #30466.
- Fix show databases & show tables parse conflict with oracle database type
---

Fix show databases & show tables parse conflict with oracle database type

---

infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/database/OracleDatabaseMetaData.java

-The Set data structure generally has better performance for lookup operations than the List data structure, because the Set implementation uses a hash table to quickly lookup elements.
---

Change Metadata implementation class

---

.github/workflows/e2e-operation.yml

- upgrade the paths-filter to avoid the nodejs 16 warning
---

Fix : upgrade the paths-filter to avoid the nodejs 16 warning

---

docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/driver/jdbc/JDBCExecutor.java
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/resource-config.json
infra/session/src/main/java/org/apache/shardingsphere/infra/session/connection/transaction/TransactionConnectionContext.java
pom.xml
test/native/native-image-filter/extra-filter.json
test/native/native-image-filter/user-code-filter.json

Fixes https://github.com/apache/shardingsphere/actions/runs/8253659317/job/22576047197 .
- Fixes for unjudged Seata AT transactions caused by #30462. For #30462 .
- Fix NativeTest failure due to class name change. Fixes https://github.com/apache/shardingsphere/actions/runs/8253659317/job/22576047197 .
- Bump GraalVM Native Build Tools to 0.10.1 to further fix unhandled extra File System in #30344 . Refer to https://github.com/graalvm/native-build-tools/pull/548 .
- Due to the merging of https://github.com/oracle/graalvm-reachability-metadata/pull/388 , it makes no sense to continue collecting the GraalVM Reachability Metadata of `java.lang.Thread` and will only cause trouble. Delete related entries in `extra-filter.json`.
---
Before committing this …

Fixes for unjudged Seata AT transactions caused by #30462

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/MergeStatementBinder.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java
test/it/parser/src/main/resources/case/dml/merge.xml
test/it/parser/src/main/resources/sql/supported/dml/merge.xml

- Fix oracle merge parameter index parser when write not matched first
---

Fix oracle merge parameter index parser when write not matched first

---

parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select-pagination.xml

Fixes #30405.
- Fix SQLServer parameter index binding error
- Error creating the wrong Parameter index when parsing the `OFFSET ? ROW FETCH NEXT ? ROWS ONLY `statement in sqlServer，This leads the org.apache.shardingsphere.infra.binder.context.segment.select.pagination.PaginationContext#getValue method to cause an index out of bounds in getParameterIndex().
- I will refactor the operation of parameterMarkerSegments later to make it more elegant.
---

Fix SQLServer parameter index binding error

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSet.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/SQLNodeConverterEngine.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/exception/SQLFederationSQLException.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/exception/convert/OptimizationSQLNodeConvertException.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/exception/syntax/SQLFederationUnsupportedSQLException.java
parser/sql/dialect/mysql/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/MySQLStatement.g4
parser/sql/dialect/mysql/src/test/java/org/apache/shardingsphere/sql/parser/mysql/visitor/format/MySQLFormatVisitorIT.java
test/it/parser/src/main/resources/sql/unsupported/unsupported.xml

- Add SQLFederationUnsupportedSQLException to handle some case that sql federation not support now
---

Add SQLFederationUnsupportedSQLException to handle some case that sql federation not support now

---

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/SystemSchemaManagerTest.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
infra/database/type/mysql/src/main/resources/schema/mysql/information_schema/keywords.yaml
test/e2e/sql/src/test/resources/cases/dql/dataset/db/select_mysql_information_schema_keywords.xml
test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-system-schema-mysql.xml

Fixes #29388.
- Emulate the information_schema.KEYWORDS Table in metadata. Refer to https://dev.mysql.com/doc/refman/8.0/en/information-schema-keywords-table.html .
---

Emulate the information_schema.KEYWORDS Table in metadata

---

agent/core/src/main/java/org/apache/shardingsphere/agent/core/yaml/AgentYamlEngine.java
infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/constructor/ShardingSphereYamlConstructor.java

Default `maxAliasesForCollections` is 50, if over it, will throw `org.yaml.snakeyaml.error.YAMLException: Number of aliases for non-scalar nodes exceeds the specified max=50`
- Set it to Integer.MAX
---

Override maxAliasesForCollections at LoaderOptions

---

.github/workflows/e2e-operation.yml
kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/OpenGaussWALDumper.java
kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/OpenGaussLogicalReplication.java
kernel/data-pipeline/dialect/opengauss/src/main/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPlugin.java
kernel/data-pipeline/dialect/opengauss/src/test/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/OpenGaussWALDumperTest.java
kernel/data-pipeline/dialect/opengauss/src/test/java/org/apache/shardingsphere/data/pipeline/opengauss/ingest/wal/decode/MppdbDecodingPluginTest.java
kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/decode/TestDecodingPlugin.java
kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/event/BeginTXEvent.java
kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/wal/WALEventConverterTest.java

Parallel decoder enabled by default after opengauss 3
Fixes: #29554
- Pipeline support parallel decoding plugin of opengauss
---

Pipeline support parallel decoding plugin of opengauss

---

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/SystemSchemaManagerTest.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/SystemSchemaBuilderTest.java
infra/database/type/mysql/src/main/resources/schema/mysql/information_schema/statistics.yaml
infra/database/type/mysql/src/main/resources/schema/mysql/mysql/role_edges.yaml

- Adjust mysql system table metadata for MySQL 8.x version
---

Adjust mysql system table metadata for MySQL 8.x version

---

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/ShardingDQLResultMergerTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/ddl/ShardingCreateTableStatementValidatorTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/statement/SQLStatementContextFactoryTest.java
infra/database/type/sqlserver/src/main/java/org/apache/shardingsphere/infra/database/sqlserver/metadata/database/SQLServerDatabaseMetaData.java
test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-where.xml
test/it/rewriter/src/test/resources/scenario/sharding/case/dml/delete.xml
test/it/rewriter/src/test/resources/scenario/sharding/case/dml/select.xml

Fixes #30342.
Linked #30227.
- Support SQLServer dml encrypt rewrite with schema
- If a schema is added to the SQL Server statement before, an error will occur and the corresponding table cannot be found.
- According to the official rules of SQL Server, dbo is the default schema. [Ownership and user-schema separation in SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/ownership-and-user-schema-separation?view=sql-server-ver16)
- After completion, rerun the previous SQL to obtain the correct result.
---

Support SQLServer dml encrypt with schema

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java
kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java
kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/row/MemoryEnumerator.java
kernel/sql-federation/executor/src/test/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutorTest.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/util/SQLFederationDataTypeUtils.java

- Fix class cast exception when select columns system table
---

Fix class cast exception when select columns system table

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/SimpleTableSegmentBinderContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/statement/dml/MergeStatementBinder.java

- Bind oracle merge source subquery table projection parameters
---

Bind oracle merge source subquery table projection parameters

---

infra/common/src/main/java/org/apache/shardingsphere/infra/hint/HintValueContext.java

- Remove useless @ToString annotation in HintValueContext
---

Remove useless @ToString annotation in HintValueContext

---

kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/constant/SingleDistSQLConstants.java
kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/provider/SingleConvertRuleConfigurationProvider.java
kernel/single/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.engine.query.ral.convert.ConvertRuleConfigurationProvider

For #30496 .
- add convert rule configuration provider for Single table.
---

add convert rule configuration provider for Single table.

---

kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java

- Minor refactor for EnumerableScanExecutor#createMemoryEnumerable logic
---

Minor refactor for EnumerableScanExecutor#createMemoryEnumerable logic

---

test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/SQLRewriterIT.java
test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/delete/delete.xml
test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-projection.xml
test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-where.xml
test/it/rewriter/src/test/resources/scenario/encrypt/config/query-with-cipher.yaml
test/it/rewriter/src/test/resources/scenario/sharding/case/dml/select.xml

link #30227.
- Support encrypt rewriter test with custom databaseName config
- When the user has specified databaseName in the configuration file, there is no need to use the default databasaeName.
---

Support encrypt rewriter test with custom databaseName config

---

test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/commons/TestShardingService.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/commons/repository/AddressRepository.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/commons/repository/OrderItemRepository.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/transactions/base/SeataTest.java
test/native/src/test/resources/META-INF/native-image/shardingsphere-test-native-test-metadata/resource-config.json
test/native/src/test/resources/test-native/sql/seata-script-client-at-postgresql.sql
test/native/src/test/resources/test-native/yaml/transactions/base/seata.yaml

For #29052 .
- Refactor Seata's nativeTest integrated under GraalVM Native Image. The current design is too bloated.
- Perform rollback tests on sharding's virtual tables rather than on single's real tables. This is to further investigate some suspicious issues.
---

Refactor Seata's nativeTest integrated under GraalVM Native Image

---

infra/expr/core/src/test/java/org/apache/shardingsphere/infra/expr/core/InlineExpressionParserFactoryTest.java
infra/expr/spi/src/main/java/org/apache/shardingsphere/infra/expr/spi/InlineExpressionParser.java
infra/expr/type/interval/src/main/java/org/apache/shardingsphere/infra/expr/interval/IntervalInlineExpressionParser.java
infra/expr/type/literal/src/main/java/org/apache/shardingsphere/infra/expr/literal/LiteralInlineExpressionParser.java
infra/expr/type/literal/src/test/java/org/apache/shardingsphere/infra/expr/literal/LiteralInlineExpressionParserTest.java

For #29052.
- Allow `InlineExpressionParser#handlePlaceHolder` to be an optional implementation.
- This method is currently only used in several algorithm classes in the shardingsphere git. Further transformation of the algorithm classes has not yet been completed. In this case, implementing this method is unnecessary.
---

Allow `InlineExpressionParser#handlePlaceHolder` to be an optional implementation

---

test/e2e/sql/src/test/resources/cases/dql/dql-integration-select-aggregate.xml

- https://github.com/apache/shardingsphere/actions/runs/8411775926/job/23031886707
---

Fix nightly sql federation e2e test case caused by result set order

---

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/schema/SchemaMetaDataReviseEngineTest.java
infra/common/src/test/java/org/apache/shardingsphere/infra/rule/builder/fixture/FixtureMetaDataRevise.java
infra/common/src/test/java/org/apache/shardingsphere/infra/rule/builder/fixture/FixtureSchemaTableAggregationReviser.java
infra/common/src/test/resources/META-INF/services/org.apache.shardingsphere.infra.metadata.database.schema.reviser.MetaDataReviseEntry

Fixes #29856.
- Add test when SchemaMetaDataReviseEngine use SchemaTableAggregationReviser
---

Add coverage for SchemaMetaDataReviseEngineTest

---

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/rule/RuleMetaDataTest.java

Ref #28724.
- Remove wrong unit test when ShardingSphereRule has been refactored
---

Remove wrong unit test when ShardingSphereRule has been refactored

---

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/projection/impl/DataTypeConverter.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/DataTypeLengthSegment.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/DataTypeSegment.java

Fixes #30669.
- Fix null pointer exception caused by obtaining DataLength
- Adjust data type name to uppercase
---

Fix SqlFederation data type converter NullPointerException

---

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/SubstitutableColumnNameToken.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtils.java
parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtilsTest.java

- Support encrypt column rewrite when combine statement contains same table
---

Support encrypt column rewrite when combine statement contains same table

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/caseinsensitive/CaseInsensitiveIdentifier.java

The altered CaseInsensitiveIdentifier has improved throughput and reduced memory allocation. 
Logarithmic scale: 
[jmh code](https://gist.github.com/iamhucong/729a869d921d6cd6c18fa0ba4fab5b96)
[jmh-result.json](https://github.com/apache/shardingsphere/files/14830383/jmh-result.json)
---

Optimize class CaseInsensitiveIdentifier performance.

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/PLSQL.g4
test/it/parser/src/main/resources/case/ddl/create-trigger.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-trigger.xml

Fixes #27069.
- Enhanced support for Oracle SQL parsing, fixed some issues with SQL parsing failure.
- Added test cases for these SQL statements, and all tests passed successfully when running the test suite.
**case1**
```sql
CREATE OR REPLACE TRIGGER check_user
AFTER LOGON ON DATABASE
BEGIN
check_user;
EXCEPTION
WHEN OTHERS THEN
RAISE_APPLICATION_ERROR
(-20000, 'Unexpected error: '|| DBMS_Utility.Format_Error_Stack);
END;
```
**case2**
```sql
CREATE OR REPLACE TRIGGER dept_cascade3
AFTER UPDATE OF Deptno ON dept
BEGIN UPDATE emp
SET Update_id = NULL
WHERE Update_id = Integritypackage.Updateseq;
END;
```
**case3**
```sql
CREATE OR REPLACE TRIGGER dept_del_cascade
AFTER DELETE ON dept
FOR EACH ROW
-- Before row is deleted from dept,
-- delete all rows …
```

Enhanced support for Oracle SQL parsing.

---

infra/exception/dialect/type/mysql/src/main/java/org/apache/shardingsphere/infra/exception/mysql/vendor/MySQLVendorError.java

- Adjust MySQLVendorError order according to error number
---

Adjust MySQLVendorError order according to error number

---

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/metadata/reviser/ShardingMetaDataReviseEntryTest.java

Unit Tests for ShardingMetaDataReviseEntry

---

docs/document/content/reference/sharding/parse.cn.md
docs/document/content/reference/sharding/parse.en.md

- Adjust outdated PARSE ENGINE documents.
- shardingsphere-sql-parser-mysql, The module has been adjusted to shardingsphere-parser-sql-engine
- shardingsphere-sql-parser-engine. The module has been adjusted to shardingsphere-parser-sql-engine
---

Adjust outdated PARSE ENGINE documents.

---

.github/workflows/e2e-operation.yml
.github/workflows/nightly-e2e-operation.yml
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/runtime/DataSourceEnvironment.java
test/e2e/fixture/pom.xml
test/e2e/operation/pipeline/pom.xml
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
test/e2e/operation/pipeline/src/test/resources/env/mysql/mysql8/my.cnf
test/e2e/operation/pipeline/src/test/resources/env/scenario/general/mysql.xml
test/e2e/operation/pipeline/src/test/resources/env/scenario/primary_key/text_primary_key/mysql.xml

Related to #30535
Since get connection of `jdbc:mysql://host:port/xxx` might from mariadb-java-client, it might cause other issues.
- Remove mariadb-java-client dependency in E2E; Replace jdbc:mariadb to jdbc:mysql
- Exclude mariadb in transaction and processlist operation E2E. Only keep MariaDB test for pipeline
---

Revise part of MariaDB E2E

---

infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/where/WhereSegmentBinderTest.java

Fixes #28513 .
-
Added unit test to test the methods of WhereSegmentBinder class. 
---

#28513 add unit tests for where segment binder

---

infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/SelectStatementBinderTest.java
mode/type/standalone/repository/provider/jdbc/src/test/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/JDBCRepositoryTest.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java

- Fix table not exist exception when bind oracle with statement contains select union all
---

Fix table not exist exception when bind oracle with statement contains select union all

---

RELEASE-NOTES.md

Update release note for 5.5.0

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/util/EncryptTokenGeneratorUtils.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptProjectionTokenGeneratorTest.java

- Add unsupported check for combine statement with encrypt columns
---

Add unsupported check for combine statement with encrypt columns

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/builder/ShardingRuleBuilder.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/builder/ShardingRuleBuilderTest.java

- Remove useless null check and use checkNotEmpty to replace checkState in ShardingRuleBuilder
---

Remove useless null check and use checkNotEmpty to replace checkState in ShardingRuleBuilder

---

kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerator/JDBCRowEnumerator.java

Fixes #30764.
- Fix federated query LocalDateTime conversion
---

Fix federated query LocalDateTime conversion

---

test/e2e/agent/plugins/common/src/test/java/org/apache/shardingsphere/test/e2e/agent/common/env/E2ETestEnvironment.java
test/e2e/agent/plugins/logging/file/src/test/java/org/apache/shardingsphere/test/e2e/agent/file/FilePluginE2EIT.java
test/e2e/agent/plugins/logging/file/src/test/resources/env/engine-env.properties
test/e2e/agent/plugins/metrics/prometheus/src/test/java/org/apache/shardingsphere/test/e2e/agent/metrics/MetricsPluginE2EIT.java
test/e2e/agent/plugins/metrics/prometheus/src/test/resources/env/engine-env.properties
test/e2e/agent/plugins/tracing/jaeger/src/test/java/org/apache/shardingsphere/test/e2e/agent/jaeger/JaegerPluginE2EIT.java
test/e2e/agent/plugins/tracing/jaeger/src/test/java/org/apache/shardingsphere/test/e2e/agent/jaeger/asserts/SpanAssert.java
test/e2e/agent/plugins/tracing/jaeger/src/test/resources/env/engine-env.properties
test/e2e/agent/plugins/tracing/zipkin/src/test/java/org/apache/shardingsphere/test/e2e/agent/zipkin/ZipkinPluginE2EIT.java
test/e2e/agent/plugins/tracing/zipkin/src/test/resources/env/engine-env.properties

Fixes #30897.
- Default disable agent e2e test
---

disable agent e2e test when mvn clean install

---

features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/api/config/EncryptRuleConfiguration.java
features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/spi/EncryptAlgorithmMetaData.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/assisted/MD5AssistedEncryptAlgorithm.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/standard/AESEncryptAlgorithm.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/fixture/CoreEncryptAlgorithmFixture.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/fixture/CoreQueryAssistedEncryptAlgorithmFixture.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/fixture/CoreQueryLikeEncryptAlgorithmFixture.java
features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/fixture/DistSQLEncryptAlgorithmFixture.java
infra/spi/src/main/java/org/apache/shardingsphere/infra/spi/type/typed/TypedSPILoader.java
proxy/backend/core/src/test/resources/expected/convert-encrypt.yaml
proxy/backend/core/src/test/resources/expected/convert-mix.yaml
test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/fixture/encrypt/JDBCEncryptAlgorithmFixture.java
test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/fixture/encrypt/JDBCQueryAssistedEncryptAlgorithmFixture.java
test/e2e/fixture/src/test/java/org/apache/shardingsphere/test/e2e/fixture/ITEncryptLikeAlgorithmFixture.java
test/e2e/sql/src/test/resources/cases/rdl/dataset/rdl_empty_rules/alter_encrypt_rule.xml
test/e2e/sql/src/test/resources/cases/rdl/dataset/rdl_empty_rules/create_encrypt_rule.xml
test/e2e/sql/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting_and_encrypt/show_encrypt_rule.xml
test/e2e/sql/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting_and_encrypt/show_encrypt_rules.xml
test/e2e/sql/src/test/resources/cases/rql/dataset/encrypt/show_encrypt_rule.xml
test/e2e/sql/src/test/resources/cases/rql/dataset/encrypt/show_encrypt_rules.xml
test/e2e/sql/src/test/resources/cases/rql/dataset/encrypt_and_readwrite_splitting/show_encrypt_rule.xml
test/e2e/sql/src/test/resources/cases/rql/dataset/encrypt_and_readwrite_splitting/show_encrypt_rules.xml
test/e2e/sql/src/test/resources/cases/rql/dataset/sharding_and_encrypt/show_encrypt_rule.xml
test/e2e/sql/src/test/resources/cases/rql/dataset/sharding_and_encrypt/show_encrypt_rules.xml
test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/fixture/encrypt/RewriteEncryptLikeAlgorithmFixture.java
test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/fixture/encrypt/RewriteNormalEncryptAlgorithmFixture.java
test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/fixture/encrypt/RewriteQueryAssistedEncryptAlgorithmFixture.java
test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/fixture/encrypt/RewriteQueryLikeEncryptAlgorithmFixture.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/commons/algorithm/TestQueryAssistedShardingEncryptAlgorithm.java

Add EncryptAlgorithmMetaData defaultProperties.

---

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/sql/SQLDialectFactory.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/sql/dialect/CustomMySQLSQLDialect.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/sql/dialect/CustomPostgreSQLSQLDialect.java
test/e2e/sql/src/test/resources/cases/dql/dql-integration-select.xml

Fixes #30918.
- Fix push down sql execute error when sql contains chinese character with sql federation
---

Fix push down sql execute error when sql contains chinese character with sql federation

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/engine/ProjectionsContextEngineTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContextTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/projection/impl/ShorthandProjectionSegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/statement/MergeStatementBinderTest.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java
parser/sql/dialect/sql92/src/main/java/org/apache/shardingsphere/sql/parser/sql92/visitor/statement/type/SQL92DMLStatementVisitor.java
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/table/SubqueryTableSegment.java
parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtilsTest.java
parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/WhereExtractUtilsTest.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/table/TableAssert.java
test/it/parser/src/main/resources/case/dml/delete.xml
test/it/parser/src/main/resources/case/dml/insert.xml
test/it/parser/src/main/resources/case/dml/merge.xml
test/it/parser/src/main/resources/case/dml/select-expression.xml
test/it/parser/src/main/resources/case/dml/select-join.xml
test/it/parser/src/main/resources/case/dml/select-pagination-group-by-order-by.xml
test/it/parser/src/main/resources/case/dml/select-pagination.xml
test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/case/dml/select-start-with-connect-by.xml
test/it/parser/src/main/resources/case/dml/select-sub-query.xml
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/case/dml/table.xml
test/it/parser/src/main/resources/case/dml/values.xml

- Adjust SubqueryTableSegment start index and stop index visit logic and add test assert
---

Adjust SubqueryTableSegment start index and stop index visit logic and add test assert

---

features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/route/qualified/type/QualifiedReadwriteSplittingTransactionalDataSourceRouter.java
infra/session/src/main/java/org/apache/shardingsphere/infra/session/connection/transaction/TransactionConnectionContext.java

- Add getReadWriteSplitReplicaRoute and return optional in TransactionConnectionContext
---

Add getReadWriteSplitReplicaRoute and return optional in TransactionConnectionContext

---

features/encrypt/core/pom.xml
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/EncryptResultDecoratorEngine.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dal/EncryptDALResultDecorator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dal/show/DecoratedEncryptShowCreateTableMergedResult.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dal/show/EncryptShowCreateTableMergedResult.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dal/show/MergedEncryptShowCreateTableMergedResult.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/EncryptResultDecoratorEngineTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dal/EncryptDALResultDecoratorTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dal/show/DecoratedEncryptShowCreateTableMergedResultTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dal/show/MergedEncryptShowCreateTableMergedResultTest.java
features/mask/core/src/main/java/org/apache/shardingsphere/mask/merge/MaskResultDecoratorEngine.java
features/mask/core/src/test/java/org/apache/shardingsphere/mask/merge/MaskResultDecoratorEngineTest.java
infra/merge/src/main/java/org/apache/shardingsphere/infra/merge/MergeEngine.java
infra/merge/src/main/java/org/apache/shardingsphere/infra/merge/engine/decorator/ResultDecoratorEngine.java
infra/merge/src/test/java/org/apache/shardingsphere/infra/merge/MergeEngineTest.java
infra/merge/src/test/java/org/apache/shardingsphere/infra/merge/fixture/decorator/ResultDecoratorEngineFixture.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java

Fixes #31025.
- Fix show create table wrong result with encrypt when data type contains float
---

Fix show create table wrong result with encrypt when data type contains float

---

parser/sql/dialect/postgresql/src/main/antlr4/imports/postgresql/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #30993.
- Support PostgreSQL COLLATION and CONSTRAINT keywords
The following case parsing is supported
```sql
SELECT
ci.relname AS index_name,
con.conname,
i.indexrelid AS oid,
ct.relname AS TABLE_NAME,
i.indrelid AS table_oid,
am.amname AS index_type,
i.indisunique AS is_unique,
i.indisclustered AS is_clustered,
i.indisprimary AS is_primary,
pg_get_expr ( indpred, indrelid, TRUE ) AS CONSTRAINT,
ts.spcname AS tablespace_name,
pa.rolname AS OWNER,
ci.reloptions,
i.indkey,
i.indclass,
i.indnatts,
i.indoption,
i.indcollation AS COLLATION,
ci.relpages AS index_pages,
obj_description ( indexrelid ) AS COMMENT 
FROM
pg_index i
LEFT JOIN pg_class ct ON ct.oid = i.indrelid
LEFT JOIN pg_class ci ON ci.oid = i.indexrelid
LEFT JOIN pg_namespace tns ON …
```

Support PostgreSQL COLLATION and CONSTRAINT keywords

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DCLStatement.g4
parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/MySQLKeyword.g4
test/it/parser/src/main/resources/case/dcl/alter-user.xml
test/it/parser/src/main/resources/sql/supported/dcl/alter-user.xml

Fixes #30950.
-Added FIDO authentication support for MySQL, 
optimized user modifications, and improved keyword definitions.
---

Enhance the support for MySQL SQL parsing in ShardingSphere

---

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/type/DatabaseTypeFactory.java
infra/database/core/src/test/java/org/apache/shardingsphere/infra/database/core/connector/fixture/ConnectionPropertiesParserFixture.java
infra/database/core/src/test/java/org/apache/shardingsphere/infra/database/core/type/DatabaseTypeFactoryTest.java
test/fixture/database/src/main/java/org/apache/shardingsphere/test/fixture/connector/MockedConnectionPropertiesParser.java

- Refactor DatabaseTypeFactory logic to return trunk database type and update unit test
---

Refactor DatabaseTypeFactory logic to return trunk database type and update unit test

---

kernel/sql-parser/core/src/main/java/org/apache/shardingsphere/parser/rule/SQLParserRule.java

- Remove useless getTrunkDataBaseType method in SQLParserRule
---

Remove useless getTrunkDataBaseType method in SQLParserRule

---

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDCLStatementVisitor.java
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/type/SQLServerDCLStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dcl/UserSegment.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/dcl/CreateUserStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/dcl/MySQLGrantStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/dcl/MySQLRevokeStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/sqlserver/dcl/SQLServerAlterUserStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/sqlserver/dcl/SQLServerSetUserStatement.java

- Move UserSegment from mysql dialect to common dcl segment
---

Move UserSegment from mysql dialect to common dcl segment

---

infra/util/src/test/java/org/apache/shardingsphere/infra/util/close/DataSourcesCloserTest.java
infra/util/src/test/java/org/apache/shardingsphere/infra/util/close/QuietlyCloserTest.java

Add unit test for DataSourcesCloserTest

---

docs/community/content/involved/_index.cn.md

Update _index.cn.md ：Chinese document link redirection error modified，corresponding to the Chinese part of issue #31126 error.
Fixes #31126.
- Fix link jump 404 error in document，After modification, the jump result is shown as follows: 
The results of the test were all right.
---

Fixed link jump 404 error in documentation：The error part of the Chinese document is modified.

---

docs/community/content/involved/_index.cn.md

Reverts apache/shardingsphere#31127
The original link in website is correct. The md files are serviced for website, so please do not care about link on md files.

Revert "Fixed link jump 404 error in documentation：The error part of the Chinese document is modified."

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDMLStatementVisitor.java
test/it/parser/src/main/resources/case/dml/call.xml
test/it/parser/src/main/resources/sql/supported/dml/call.xml

Fixes #30951, #30952.
- Support Mysql CALL sql with mysql prefix
SQL Case
```sql
CALL mysql.sp_firewall_group_enlist('fwgrp', 'member2@localhost')
```
---

Support Mysql CALL sql with mysql prefix

---

.github/workflows/nightly-ci.yml

Fixes #31144.
- Migrate the OpenJDK8 used by nightly CI from Temurin to Zulu.
---

Migrate the OpenJDK8 used by nightly CI from Temurin to Zulu

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
test/it/parser/src/main/resources/case/ddl/prepared.xml
test/it/parser/src/main/resources/case/dml/load-data.xml
test/it/parser/src/main/resources/sql/supported/ddl/prepared.xml
test/it/parser/src/main/resources/sql/supported/dml/load-data.xml

Fixes #30973.
- Support parsing MySQL LOAD DATA with @ variable
SQL Case
```sql
LOAD DATA INFILE 'file.txt'
INTO TABLE t1
(column1, @var1)
SET column2 = @var1/100;
```
```sql
LOAD DATA INFILE 'file.txt'
INTO TABLE t1
(column1, @dummy, column2, @dummy, column3);
```
```sql
EXECUTE STMT USING @skip, @numrows;
```
---

Support parsing MySQL LOAD DATA with @ variable

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DALStatement.g4
parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DDLStatement.g4
test/it/parser/src/main/resources/case/dal/create.xml
test/it/parser/src/main/resources/case/ddl/create-index.xml
test/it/parser/src/main/resources/sql/supported/dal/create.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-index.xml

Fixes #30962.
- Support parsing MySQL CREATE INDEX with ENGINE_ATTRIBUTE
SQL Case
```sql
CREATE INDEX i1 ON t1 (c1) ENGINE_ATTRIBUTE='{"key":"value"}';
```
```sql
CREATE RESOURCE GROUP rg2
TYPE = SYSTEM
THREAD_PRIORITY = -20
DISABLE;
```
---

Support parsing MySQL CREATE INDEX with ENGINE_ATTRIBUTE

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DALStatement.g4
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/dal/CreateLoadableFunctionTestCase.java
test/it/parser/src/main/resources/case/dal/create-loadable-function.xml
test/it/parser/src/main/resources/sql/supported/dal/create-loadable-function.xml

Fixes #30961.
- Support Mysql create loadable function returns int/dec
- In the official MySQL syntax documentation, there is no mention of the usage of RETURNS INT/DEC. However, through testing, it was found that this notation can be executed normally. [CREATE FUNCTION Statement for Loadable Functions](https://dev.mysql.com/doc/refman/8.0/en/create-function-loadable.html)
- When searching the official documentation, it is found that in MySQL, INT and INTEGER are defined as synonyms, and DEC and DECIMAL are defined as synonyms. [Numeric Data Types](https://dev.mysql.com/doc/refman/8.0/en/numeric-types.html)
---

Support Mysql create loadable function returns int/dec

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DDLStatement.g4
test/it/parser/src/main/resources/case/ddl/create-table.xml
test/it/parser/src/main/resources/case/ddl/create-tablespace.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
test/it/parser/src/main/resources/sql/supported/ddl/create-tablespace.xml

Fixes #30963.
- Adjust resolution file to support parsing MySQL CREATE TABLESPACE/TABLE in Mysql-8
- [CREATE TABLESPACE Statement](https://dev.mysql.com/doc/refman/8.0/en/create-tablespace.html)
- [CREATE TABLE Statement](https://dev.mysql.com/doc/refman/8.0/en/create-table.html)
SQL Case
```sql
CREATE TABLESPACE TS1
ADD DATAFILE 'data1.dat'
EXTENT_SIZE 8M
INITIAL_SIZE 2G
ENGINE NDBCLUSTER;
```
```sql
CREATE TABLESPACE ts1 ENGINE_ATTRIBUTE='{"key":"value"}';
```
```sql
CREATE TABLE t1 (c1 INT) AUTOEXTEND_SIZE = 4M;
```
```sql
CREATE TABLESPACE ts1 AUTOEXTEND_SIZE = 4M;
```
---

Support parsing MySQL CREATE TABLESPACE/TABLE in Mysql-8

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/RLStatement.g4
parser/sql/dialect/mysql/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/MySQLStatement.g4
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLRLStatementVisitor.java
parser/sql/engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/rl/MySQLStartReplicaStatement.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rl/StartReplicaStatementTestCase.java
test/it/parser/src/main/resources/case/rl/start-replica.xml
test/it/parser/src/main/resources/sql/supported/rl/start-replica.xml

Fixes #30969,  #30970. 
- Support parsing MySQL START REPLICA statement
- [START REPLICA Statement](https://dev.mysql.com/doc/refman/8.0/en/start-replica.html)
case 1
```sql
START REPLICA UNTIL SQL_AFTER_MTS_GAPS;
```
case2
```sql
START REPLICA SQL_THREAD;
```
---

Support parsing MySQL START REPLICA statement

---

kernel/sql-parser/distsql/handler/src/test/java/org/apache/shardingsphere/parser/distsql/handler/update/AlterSQLParserRuleExecutorTest.java

Fixes #30083.
- Refactor AlterSQLParserRuleExecutorTest Test Case
---

Refactor AlterSQLParserRuleExecutorTest Test Case

---

kernel/traffic/distsql/handler/src/test/java/org/apache/shardingsphere/traffic/distsql/handler/fixture/DistSQLLoadBalanceAlgorithmFixture.java
kernel/traffic/distsql/handler/src/test/java/org/apache/shardingsphere/traffic/distsql/handler/update/AlterTrafficRuleExecutorTest.java
kernel/traffic/distsql/handler/src/test/resources/META-INF/services/org.apache.shardingsphere.infra.algorithm.loadbalancer.core.LoadBalanceAlgorithm

For #30083.
- Refactor AlterTrafficRuleExecutorTest Test Case
---

Refactor AlterTrafficRuleExecutorTest Test Case

---

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/segment/oracle/join/OuterJoinExpression.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/column/OuterJoinExpressionAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedOuterJoinExpression.java
test/it/parser/src/main/resources/case/ddl/create-view.xml
test/it/parser/src/main/resources/case/dml/select-join.xml

- Correct OuterJoinExpression getText logic and add text assertion in sql parse test case
---

Correct OuterJoinExpression getText logic and add text assertion in sql parse test case

---

.github/workflows/e2e-operation.yml

- remove opengauss from e2e-operation, only keep it in nightly e2e-operation
---

Refactor : remove opengauss from e2e-operation, only keep it in nightly

---

infra/common/pom.xml
infra/common/src/main/java/org/apache/shardingsphere/infra/hint/HintManager.java

Fixes #31042.
- Replace ThreadLocal with TransmittableThreadLocal in HintManager to support cross Thread usage
---

Replace ThreadLocal with TransmittableThreadLocal in HintManager to support cross Thread usage

---

mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/StateChangedSubscriberTest.java
proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowTablesExecutor.java

Revise #31299
no order when execute `show tables`

Refactor ShowTablesExecutor, fix sort without like filter

---

docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/com.github.ben-manes.caffeine/caffeine/2.9.3/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
pom.xml

For https://github.com/apache/shardingsphere/actions/runs/9149540776/job/25153282542 .
- Fixes nativeTest failure under GraalVM Native Image due to class information changes.
- Updates outdated documentation. Due to the Truffle 24.0.0 runtime milestone, GraalVM for JDK17 is no longer a target of our attention.
- Updates GraalVM Native Build Tools to benefit from https://github.com/oracle/graalvm-reachability-metadata/pull/388 and remove duplicate JSON entries.
---

Fixes nativeTest failure under GraalVM Native Image due to class information changes

---

infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/MySQLTest.java
test/native/src/test/resources/test-native/yaml/databases/postgresql.yaml
test/native/src/test/resources/test-native/yaml/databases/sqlserver.yaml
test/native/src/test/resources/test-native/yaml/transactions/base/seata.yaml

For #29052.
- Remove NativeTest's useless TC_DAEMON parameters under Graalvm Native Image.
- Fixes nativeTest failure under GraalVM Native Image due to class information changes. For https://github.com/apache/shardingsphere/actions/runs/9196231415/job/25293863433 .
---

Remove NativeTest's useless TC_DAEMON parameters under Graalvm Native Image

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSet.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/converter/impl/MySQLColumnTypeConverter.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dql/BaseDQLE2EIT.java
test/e2e/sql/src/test/resources/cases/dql/dql-integration-select.xml

Fixes #31247.
Fix federated query failed to get binary type data, test single projection column and multiple projection column queries in e2e federated query scenario.
In the MetaData assertion test for the federated query scenario, the assertion test for the ColumnType is skipped, and mysql makes some implicit transformations to the query result according to the type. Obtained through SQLFederationResultSetMetaData ColumnType is difficult with mysql ColumnType consistent.
```
SELECT 1=1;
actual: BOOLEAN  expected: BIGINT
SELECT type_bit FROM t_product_extend;
actual: BIGINT  expected: BIT
SELECT type_binary FROM t_product_extend;
actual: VARBINARY expected: BINARY
```
---

Fix federation query binary type data query

---

parser/sql/dialect/postgresql/src/main/antlr4/imports/postgresql/BaseRule.g4
parser/sql/dialect/postgresql/src/main/antlr4/imports/postgresql/DDLStatement.g4
parser/sql/dialect/postgresql/src/main/antlr4/imports/postgresql/PostgreSQLKeyword.g4
parser/sql/dialect/postgresql/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/PostgreSQLStatementParser.g4
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/type/PostgreSQLDDLStatementVisitor.java
parser/sql/engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/ddl/OpenStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/postgresql/ddl/PostgreSQLOpenStatement.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ddl/DDLStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ddl/impl/OpenStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ddl/OpenStatementTestCase.java
test/it/parser/src/main/resources/case/ddl/open.xml
test/it/parser/src/main/resources/sql/supported/ddl/open.xml

For #18414
- Support [PostgreSQL Open statement](https://www.postgresql.org/docs/16/ecpg-sql-open.html) parse.
- Small ANTLR change for [PostgreSQL Declare statement](https://www.postgresql.org/docs/current/sql-declare.html) according to the definition.
---

Support PostgreSQL Open statement parse and small ANTLR change for PostgreSQL Declare statement

---

infra/common/src/main/java/org/apache/shardingsphere/infra/config/rule/checker/RuleConfigurationCheckEngine.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportMetaDataExecutor.java

Fixes #31425 .
Before:
After:
---

Fix NPE when import metadata

---

docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.en.md
docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.cn.md
docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.en.md
infra/common/src/main/java/org/apache/shardingsphere/infra/database/DatabaseTypeEngine.java
infra/database/type/clickhouse/src/test/java/org/apache/shardingsphere/infra/database/clickhouse/connector/ClickHouseConnectionPropertiesTest.java
infra/database/type/clickhouse/src/test/java/org/apache/shardingsphere/infra/database/clickhouse/metadata/database/ClickHouseDatabaseMetaDataTest.java
infra/database/type/hive/src/main/java/org/apache/shardingsphere/infra/database/hive/connector/HiveConnectionPropertiesParser.java
infra/database/type/hive/src/main/java/org/apache/shardingsphere/infra/database/hive/metadata/database/HiveDatabaseMetaData.java
infra/database/type/hive/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.database.core.connector.ConnectionPropertiesParser
infra/database/type/hive/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.database.core.metadata.database.DialectDatabaseMetaData
infra/database/type/hive/src/test/java/org/apache/shardingsphere/infra/database/hive/connector/HiveConnectionPropertiesTest.java
infra/database/type/hive/src/test/java/org/apache/shardingsphere/infra/database/hive/metadata/database/HiveDatabaseMetaDataTest.java

For #31526.
- Fixes the connection of Remote HiveServer2 through HiveServer2 JDBC Driver. HiveServer2 JDBC Driver did not implement the `java.sql.dataBasemetadata#getUrl()`, which caused us to deal with additional processing.
- This PR is the split of #31526 to expose the core logic.
- Supplement the Clickhouse unit test.
- Fix the document of seata and optional modules.
- **Note that this PR only addresses the `?hive_conf_list` part of `jdbc:hive2://<host1>:<port1>,<host2>:<port2>/dbName;initFile=<file>;sess_var_list?hive_conf_list#hive_var_list`.** `sess_var_list` and `hive_var_list` in https://cwiki.apache.org/confluence/display/Hive/HiveServer2+Clients#HiveServer2Clients-JDBC are not considered and parsed yet. This actually brings up a new issue …

Fixes the connection of Remote HiveServer2 through HiveServer2 JDBC Driver

---

test/e2e/sql/src/test/resources/env/mysql/my.cnf

- Modify mysql e2e sql mode config to support mysql select column not in aggregate column
---

Modify mysql e2e sql mode config to support mysql select column not in aggregate column

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDMLStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #30966 
-
This pull request modify the parsing of the following sql:
```sql
SELECT * FROM t1 USE INDEX (i1) IGNORE INDEX (i2) USE INDEX (i2);
SELECT * FROM t1
USE INDEX () IGNORE INDEX (i2) USE INDEX (i1) USE INDEX (i2);
SELECT * FROM t1
USE INDEX (i1,i2) IGNORE INDEX (i2);
```
Syntax specifications in official documentation，index_list can be empty when using `IGNORE` or `FORCE`. So I modified the syntax of `indexHintList` and split the `indexHint` in DMLStatement.g4.
```sql
tbl_name [[AS] alias] [index_hint_list]
index_hint_list:
index_hint [index_hint] ...
index_hint:
USE {INDEX|KEY}
[FOR {JOIN|ORDER BY|GROUP BY}] ([index_list])
| {IGNORE|FORCE} {INDEX|KEY}
[FOR {JOIN|ORDER BY|GROUP BY}] (index_list)
index_list:
index_name [, index_name] ... …
```

Fix the error in parsing the MySQL query with index hints.

---

infra/data-source-pool/core/src/main/java/org/apache/shardingsphere/infra/datasource/pool/creator/DataSourcePoolReflection.java
infra/data-source-pool/core/src/test/java/org/apache/shardingsphere/infra/datasource/pool/creator/DataSourcePoolCreatorTest.java
infra/data-source-pool/core/src/test/java/org/apache/shardingsphere/infra/datasource/pool/props/domain/DataSourcePoolPropertiesTest.java
infra/data-source-pool/type/hikari/src/test/java/org/apache/shardingsphere/infra/datasource/pool/hikari/creator/HikariDataSourcePoolCreatorTest.java
kernel/metadata/core/src/test/resources/yaml/persist/data-source-foo.yaml

For #31618.
- Revert #15409 to save driverClassName related properties. Also fixes #27921 .
---

Revert #15409 to save driverClassName related properties

---

jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/StatementManager.java
test/e2e/agent/plugins/logging/file/src/test/java/org/apache/shardingsphere/test/e2e/agent/file/FilePluginE2EIT.java

- Remove useless cachedStatements when statement is close and close cachedStatements when close connection
---

Remove useless cachedStatements when statement is close and close cachedStatements when close connection

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/WhereClauseShardingConditionEngine.java
test/it/rewriter/src/test/resources/scenario/sharding/case/dml/select.xml

Fixes #31656.
- Fix Sharding column not tracked through aliases
- When there is an alias for our sharded column, errors may occur in judging the shard condition, leading to routing all tables in the database.
- When the alias of our regular column happens to be the same as the partitioned column, it will also incorrectly judge the slice condition, resulting in an incorrect route.
``` sql
-- alias for sharding column
SELECT * FROM (SELECT account_id aliased_account_id FROM t_account) t1 WHERE aliased_account_id  = 100
-- Incorrect routing result
SELECT * FROM (SELECT account_id aliased_account_id FROM t_account_0) t1 WHERE aliased_account_id  = 100
SELECT * FROM (SELECT account_id aliased_account_id FROM t_account_1) t1 WHERE aliased_account_id  = 100 …
```

Fix Sharding column not tracked through aliases

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/converter/impl/MySQLColumnTypeConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/function/mysql/MySQLBitCountFunction.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/planner/util/SQLFederationFunctionUtils.java
test/e2e/sql/src/test/resources/cases/dql/dql-integration-select.xml

- Support sql federation bit_count function for mysql
- ref: https://github.com/mysql/mysql-server/blob/trunk/sql/item_func.cc#L4441
---

Support sql federation bit_count function for mysql

---

kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/engine/fixture/decider/SQLFederationDeciderMatchFixture.java

- Adjust SQLFederationDeciderMatchFixture order to 1 to avoid conflict with ShardingOrder
---

Adjust SQLFederationDeciderMatchFixture order to 1 to avoid conflict with ShardingOrder

---

kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/engine/fixture/decider/SQLFederationDeciderNotMatchFixture.java

- Adjust SQLFederationDeciderNotMatchFixture order to 11 to avoid conflict with EncryptOrder
---

Adjust SQLFederationDeciderNotMatchFixture order to 11 to avoid conflict with EncryptOrder

---

jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
jdbc/src/test/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnectionTest.java

Fix transaction context not cleaned up when xa transaction is committed

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dal/KillStatementContext.java
parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/type/DorisDALStatementVisitor.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDALStatementVisitor.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dal/LoadTableIndexSegment.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/dal/DropResourceGroupStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/dal/HelpStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/dal/InstallComponentStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/dal/InstallPluginStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/dal/KillStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/dal/LoadIndexInfoStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/doris/dal/DorisHelpStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/doris/dal/DorisInstallComponentStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/doris/dal/DorisInstallPluginStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/doris/dal/DorisKillStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/doris/dal/DorisLoadIndexInfoStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/dal/MySQLDropResourceGroupStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/dal/MySQLHelpStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/dal/MySQLInstallComponentStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/dal/MySQLInstallPluginStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/dal/MySQLKillStatement.java
parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/dal/MySQLLoadIndexInfoStatement.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dal/DALStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dal/impl/DropResourceGroupStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dal/impl/InstallComponentStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dal/impl/InstallPluginStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dal/impl/KillStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dal/impl/LoadIndexInfoStatementAssert.java

- Extract DropResourceGroupStatement ...  LoadIndexInfoStatement to reduce duplicate logic for MySQL and Doris
---

Extract DropResourceGroupStatement ... LoadIndexInfoStatement to reduce duplicate logic for MySQL and Doris

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/AggregationDistinctTokenGenerator.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/generator/AggregationDistinctTokenGeneratorTest.java

Add judgment for aggregation distinct token generator

---

kernel/sql-federation/core/pom.xml
kernel/sql-federation/executor/pom.xml
kernel/sql-federation/optimizer/pom.xml
parser/sql/dialect/pom.xml
pom.xml
test/e2e/agent/pom.xml
test/e2e/pom.xml
test/it/pom.xml
test/it/yaml/src/main/java/org/apache/shardingsphere/test/it/yaml/RepositoryTupleSwapperEngineIT.java

Fixes #31634
- failsafe plugin in the root pom to trigger all test cases end with suffix IT
---

Make failsafe plugin in the root pom to trigger all test cases end with suffix IT

---

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/PreviewExecutor.java

- Remove useless isReturnGeneratedKeys in preview sql federation logic
---

Remove useless isReturnGeneratedKeys in preview sql federation logic

---

features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/spi/EncryptAlgorithmMetaData.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/generator/generic/RemoveTokenGenerator.java

- Add EqualsAndHashCode for EncryptAlgorithmMetaData to solve encryptor equals wrong
---

Add EqualsAndHashCode for EncryptAlgorithmMetaData to solve encryptor equals wrong

---

infra/session/src/main/java/org/apache/shardingsphere/infra/session/query/QueryContext.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/session/ConnectionSession.java
proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutor.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutorTest.java

- Remove useless databaseName and schemaName in QueryContext
---

Remove useless databaseName and schemaName in QueryContext

---

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/planner/util/SQLFederationFunctionUtils.java
test/e2e/sql/src/test/resources/cases/dql/dql-integration-select.xml

Ref #31912.
- Improve atan and anan2 sql function for mysql
mysql is compatible with calls to different numbers of parameters
---

Improve atan and anan2 sql function for mysql

---

test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/autocommit/MySQLAutoCommitTestCase.java

Add mysql E2E case of transaction execution exception and then commit

---

docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.en.md

For #31715.
- Add instructions for Apache Seata 2.1.0-RC4 to Seata AT integration documentation. Refer to https://lists.apache.org/thread/s0gxv49802kk8y3dnxr8ytxy6ghkkjr6 .
- Updates to the Docker Image are available at https://github.com/apache/incubator-seata/pull/6349 .
---

Add instructions for Apache Seata 2.1.0-RC4 to Seata AT integration documentation

---

test/it/parser/src/main/resources/case/dml/select-aggregate.xml
test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/sql/supported/dml/select-aggregate.xml
test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml

Improve the parsing of methods in MySQL,fix issue #31547

---

docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
infra/common/src/main/java/org/apache/shardingsphere/infra/database/DatabaseTypeEngine.java
infra/reachability-metadata/src/main/resources/META-INF/native-image/com.h2database/h2/2.2.224/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json

For #29052.
- Add documentation for using XA distributed transactions in GraalVM Native Image. Refer to https://www.graalvm.org/docs/reference-manual/native-image/assets/reflect-config-schema-v1.0.0.json .
- For https://github.com/apache/shardingsphere/actions/runs/9782731559/job/27009752037 . Fixes nativeTest failure under GraalVM Native Image due to class information changes.
- For https://github.com/oracle/graal/issues/8723 . Removes invalid reference to `libz-dev` from documentation.
- For #31573 and #31526 . Fixes the issue that the HiveServer2 JDBC Driver could not be connected through the HikariCP connection pool.
---

Add documentation for using XA distributed transactions in GraalVM Native Image

---

test/native/pom.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/MySQLTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/OpenGaussTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/transactions/base/SeataTest.java

For #31982.
- Removes the incorrectly placed Junit4 class in nativeTest under GraalVM Native Image.
---

Removes the incorrectly placed Junit4 class in nativeTest under GraalVM Native Image

---

test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml

Improve the parsing of methods in MySQL(#31548)

---

infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/BinaryOperationExpressionBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/ExistsSubqueryExpressionBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/FunctionExpressionSegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/InExpressionBinderTest.java

Fixes #28538.
Add more unit tests for ExpressionSegmentBinder
---

Add more unit tests for ExpressionSegmentBinder(#28538)

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/parameter/impl/ParameterMarkerExpressionSegmentBinder.java

- Remove useless method in ParameterMarkerExpressionSegmentBinder
---

Remove useless method in ParameterMarkerExpressionSegmentBinder

---

.github/workflows/nightly-check.yml

- add label restriction for stale workflow
---

Refactor : add label restriction for stale workflow

---

infra/exception/core/src/main/java/org/apache/shardingsphere/infra/exception/core/external/sql/type/kernel/category/PipelineSQLException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/data/PipelineDataException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/data/PipelineUnexpectedDataRecordOrderException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/data/UnsupportedPipelineDatabaseTypeException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/ConsistencyCheckJobNotFoundException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/CreateTableSQLGenerateException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/MissingRequiredTargetDatabaseException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PipelineJobCreationWithInvalidShardingCountException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PipelineJobException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PipelineJobNotFoundException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithInvalidSourceDataSourceException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithTargetTableNotEmptyException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithoutEnoughPrivilegeException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/PrepareJobWithoutUserException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/TableNotFoundWhenSplitPipelineJobByRangeException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/job/UncompletedConsistencyCheckJobExistsException.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/exception/param/PipelineInvalidParameterException.java
kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/exception/PipelineCDCException.java
kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/exception/StreamDatabaseNotFoundException.java

- Remove varargs in pipeline exception constructor to avoid transfer cause to varargs
---

Remove varargs in pipeline exception constructor to avoid transfer cause to varargs

---

infra/exception/core/src/main/java/org/apache/shardingsphere/infra/exception/core/external/sql/ShardingSphereSQLException.java
infra/exception/core/src/main/java/org/apache/shardingsphere/infra/exception/core/internal/ShardingSphereInternalException.java
infra/exception/core/src/test/java/org/apache/shardingsphere/infra/exception/core/sql/ShardingSphereSQLExceptionTest.java

- No String.format when varargs is empty to avoid possible formatting error
---

Improve ShardingSphereSQLException error message formatting

---

docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.en.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
kernel/transaction/type/base/seata-at/src/main/java/org/apache/shardingsphere/transaction/base/seata/at/SeataATShardingSphereTransactionManager.java

Fixes https://github.com/apache/shardingsphere/discussions/32012 .
- Fixes the problem that the Seata integration module cannot correctly determine the status of distributed transactions in multi-microservice scenarios . Refer to https://github.com/apache/shardingsphere/discussions/32012#discussioncomment-10031799 .
> `@Famezyy`: I think the root reason is that in `SeataATShardingSphereTransactionManager:isInTransaction` it's just checking `null != RootContext.getXID()`, if it is true then the `ShardingSphereConnection:beginDistributedTransaction` will not be triggered when executing `ShardingSphereConnection:processDistributedTransaction`, and `TransactionConnectionContext:beginTransaction` is not called, so that the …

Fixes the problem that the Seata integration module cannot correctly determine the status of distributed transactions in multi-microservice scenarios

---

docs/document/content/user-manual/shardingsphere-jdbc/special-api/sharding/hint.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/sharding/hint.en.md

Fixes #25985.
- Fixes the incorrect description of hint algorithm in Sharding and Readwrite Splitting features in the doc.
---

Fixes the incorrect description of hint algorithm in Sharding and Readwrite Splitting features in the doc

---

.github/workflows/nightly-check.yml

- refactor the stale timeout days from 30 to 7
---

Refactor : refactor the stale timeout days from 30 to 7

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueInOperatorGenerator.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/generator/impl/ConditionValueInOperatorGeneratorTest.java

Fixes #32076.
- excluding the case of `not in` in ConditionValueInOperatorGenerator 
---

ConditionValueInOperatorGenerator not excluding the case of not in. (#32076)

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/from/type/SimpleTableSegmentBinder.java

- Minor refactor for SimpleTableSegmentBinder#createSimpleTableBinderContext method
---

Minor refactor for SimpleTableSegmentBinder#createSimpleTableBinderContext method

---

.github/workflows/nightly-check.yml

- refactor the stale timeout from 7 days to 14 days
---

Refactor : refactor the stale timeout from 7 days to 14 days

---

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/checker/DialectDatabaseEnvironmentChecker.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/checker/PrivilegeCheckType.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/exception/CheckDatabaseEnvironmentFailedException.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/exception/MissingRequiredPrivilegeException.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/exception/UnexpectedVariableValueException.java
infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/checker/MySQLDatabaseEnvironmentChecker.java
infra/database/type/mysql/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.database.core.checker.DialectDatabaseEnvironmentChecker
infra/database/type/mysql/src/test/java/org/apache/shardingsphere/infra/database/mysql/checker/MySQLDatabaseEnvironmentCheckerTest.java

For #32044
- Add database environment checker for MySQL
TODO
- Merge XATransactionPrivilegeChecker & DialectDataSourceChecker to DialectDatabaseEnvironmentChecker
- Add SELECT privilege check when register storage unit
- Update docs for error code

Add database environment checker for MySQL

---

docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.en.md
pom.xml

Fixes https://github.com/apache/shardingsphere/discussions/32023 .
- Fixes the incorrect description of Seata TCC Mode in the doc.
- Updates Curator to 5.7.0 to prevent unstable CI failures. See https://issues.apache.org/jira/browse/CURATOR-688 .
---

Fixes the incorrect description of Seata TCC Mode in the doc

---

pom.xml

- bump the OWASP dependency-check-maven to 10.0.3
---

Chore : bump the OWASP dependency-check-maven to 10.0.3

---

pom.xml

- remove the docker-compose plugin
---

Refactor : remove the docker-compose plugin

---

test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml

Improve the parsing of methods in MySQL #31551

---

agent/plugins/metrics/core/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/SQLParseCountAdviceTest.java
infra/common/src/main/java/org/apache/shardingsphere/infra/exception/kernel/metadata/resource/storageunit/StorageUnitsValidateException.java
infra/data-source-pool/core/src/main/java/org/apache/shardingsphere/infra/datasource/pool/props/validator/DataSourcePoolPropertiesValidator.java
infra/data-source-pool/core/src/test/java/org/apache/shardingsphere/infra/datasource/pool/props/validator/DataSourcePoolPropertiesValidatorTest.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/checker/PrivilegeCheckType.java
infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/rdl/resource/AlterStorageUnitExecutor.java
infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/rdl/resource/RegisterStorageUnitExecutor.java
infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/validate/DistSQLDataSourcePoolPropertiesValidator.java
infra/distsql-handler/src/test/java/org/apache/shardingsphere/distsql/handler/executor/rdl/resource/AlterStorageUnitExecutorTest.java
infra/distsql-handler/src/test/java/org/apache/shardingsphere/distsql/handler/executor/rdl/resource/RegisterStorageUnitExecutorTest.java
kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/util/AutoCommitUtilsTest.java
parser/distsql/engine/src/main/antlr4/imports/Keyword.g4
parser/distsql/engine/src/main/antlr4/imports/RDLStatement.g4
parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java
parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/statement/rdl/resource/unit/type/AlterStorageUnitStatement.java
parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/statement/rdl/resource/unit/type/RegisterStorageUnitStatement.java

For #32044 , check privilege when register or alter storage unit

Check privilege when register or alter storage unit

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContext.java

- Minor refactor for SelectStatementContext#isAllSubqueryTableInJoinTable
---

Minor refactor for SelectStatementContext#isAllSubqueryTableInJoinTable

---

test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml

Improve the parsing of methods in MySQL #31565

---

db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/text/impl/PostgreSQLDateValueParser.java
db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/text/impl/PostgreSQLDateValueParserTest.java

Optimize the timezone support of PostgreSQLDateValueParser.

---

docs/document/content/user-manual/common-config/builtin-algorithm/metadata-repository.cn.md
docs/document/content/user-manual/common-config/builtin-algorithm/metadata-repository.en.md
mode/type/standalone/repository/provider/jdbc/src/main/resources/sql/DerbyNetworkServer.xml
mode/type/standalone/repository/provider/jdbc/src/main/resources/sql/EmbeddedDerby.xml
mode/type/standalone/repository/provider/jdbc/src/main/resources/sql/HSQLDB.xml
mode/type/standalone/repository/provider/jdbc/src/test/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/sql/JDBCRepositorySQLLoaderTest.java

Fixes #30926.
- Provides Standalone Mode implementations of Embedded Derby, Derby Network Server, HyperSQL HSQL Server, HyperSQL HTTP Server, HyperSQL HTTP Servlet and (Embedded) HyperSQL .
- For a potential Docker image for HyperSQL HSQL Server, I opened https://sourceforge.net/p/hsqldb/feature-requests/371/ .
- apache/derby uses svn ( https://svn.apache.org/repos/asf/db/derby/code/trunk/ ) instead of git for collaboration. As a result, the content of https://github.com/apache/derby is actually out of date. But Derby Network Server is indeed encouraged to use JAR to start, and there is no Docker Image available. Refer to https://issues.apache.org/jira/browse/DERBY-7165 and https://issues.apache.org/jira/browse/DERBY-7166 .
- …

Provides Standalone Mode implementations of hsqldb and apache/derby

---

.github/workflows/graalvm.yml
.github/workflows/nightly-build.yml
.github/workflows/nightly-ci.yml
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
pom.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/MySQLTest.java
test/native/src/test/resources/container-license-acceptance.txt
test/native/src/test/resources/test-native/yaml/databases/clickhouse.yaml
test/native/src/test/resources/test-native/yaml/databases/sqlserver.yaml

Fixes https://github.com/apache/shardingsphere/actions/runs/9453545898/job/26039164284 .
- Bump the Docker Images involved in testcontainers-java, clickhouse-java and nativeTest under GraalVM Native Image.
- Uses GraalVM CE For JDK 22.0.2 in CI to prevent OutOfMemoryError. This mainly concerns `Added a few OutOfMemoryError-related fixes.` mentioned in https://www.graalvm.org/release-notes/JDK_22/. This PR was forked from https://github.com/apache/shardingsphere/pull/31526 .
```shell
Build resources:
- 7.43GB of memory (47.6% of 15.61GB system memory, determined at start)
- 4 thread(s) (100.0% of 4 available processor(s), determined at start)
[junit-platform-native] Running in 'test listener' mode using files matching pattern …
```

Uses GraalVM CE For JDK 22.0.2 in CI to prevent OutOfMemoryError

---

.github/workflows/e2e-agent.yml
.github/workflows/nightly-e2e-operation.yml
.github/workflows/nightly-e2e-sql.yml

- upgrade the jdk to 21 in operation workflow
- upgrade the jdk to 21 in sql e2e workflow
- upgrade the jdk to 21 in agent workflow
---

Refactor : upgrade the jdk to 21 in workflow

---

.github/workflows/nightly-e2e-sql.yml

- update the JDK version to 21 in e2e workflow
---

Refactor : update the JDK version to 21 in e2e workflow

---

docs/document/content/user-manual/common-config/builtin-algorithm/expr.cn.md
docs/document/content/user-manual/common-config/builtin-algorithm/expr.en.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
infra/expr/type/espresso/pom.xml
infra/expr/type/espresso/src/test/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParserTest.java

Fixes https://github.com/apache/shardingsphere/actions/runs/10081728571/job/27887106603 .
- Fixes HotSpot JDK 22 CI failure due to GR-54293. Refer to https://github.com/oracle/graal/pull/9020 . This is the change introduced by https://github.com/apache/shardingsphere/pull/32246 .
- Starting from GraalVM CE For JDK 22.0.2, using Truffle's Espresso implementation in OpenJDK requires including the `RuntimeResourceId` related Maven dependencies in the classpath, because Espresso's `RuntimeResourceId` is allowed to have multiple configurations. Currently, there is only one known implementation of RuntimeResourceId, which is `org.graalvm.espresso:espresso-runtime-resources-linux-amd64:24.0.2`. But I still think this is not reasonable, after all, I also …

Fixes HotSpot JDK 22 CI failure due to GR-54293

---

jdbc/src/test/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManagerTest.java

- fix the assertGetConnectionsWhenConnectionCreateFailed in windows environment
---

Fix : fix the assertGetConnectionsWhenConnectionCreateFailed in windows

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContext.java

- Minor refactor for SelectStatementContext#containsTableSubquery
---

Minor refactor for SelectStatementContext#containsTableSubquery

---

pom.xml

-  remove the dependency-check-maven since there is no uploaded nvd key
---

Refactor : remove the dependency-check-maven since there is no uploaded nvd key

---

infra/common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintTokenType.java
infra/common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintUtils.java
infra/common/src/test/java/org/apache/shardingsphere/infra/hint/SQLHintUtilsTest.java
infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/DistSQLConnectionContext.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/DistSQLQueryBackendHandler.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/PreviewExecutor.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariableExecutorTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowDistVariablesExecutorTest.java
test/it/rewriter/src/test/resources/scenario/sharding/case/dml/select.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/features/ShadowTest.java

- Support sql hint extract when sql contains dbeaver hint comment
---

Support sql hint extract when sql contains dbeaver hint comment

---

infra/util/src/main/java/org/apache/shardingsphere/infra/util/eventbus/EventBusContext.java
pom.xml
proxy/bootstrap/pom.xml
proxy/bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java

ShardingSphere-JDBC is a SDK. When integrating ShardingSphere-JDBC into project which using JUL for logging, StackOverflowError would be occurred.
---

Make jul-to-slf4j work in ShardingSphere-Proxy only

---

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/pojo/generic/SubstitutableColumnNameToken.java

- Remove useless lastColumn in SubstitutableColumnNameToken
---

Remove useless lastColumn in SubstitutableColumnNameToken

---

kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/data/ShardingSphereDataPersistService.java
mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/ShardingSphereStatisticsRefreshEngine.java
mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/event/subscriber/dispatch/ListenerAssistedSubscriber.java
mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/event/subscriber/dispatch/ResourceMetaDataChangedSubscriber.java

Fixes #32407.
- Clear the collected system metadata when drop the database
- Remove useless judgments from ListenerAssistedSubscriber
- Remove useless judgments from ResourceMetaDataChangedSubscriber
---

Clear the collected system metadata when database is droped

---

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/ComboITContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/ITContainers.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/AdapterContainerFactory.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/impl/ShardingSphereMultiProxyClusterContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/impl/ShardingSphereProxyClusterContainer.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/container/compose/ContainerComposerRegistry.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/TotalSuitesCountCalculator.java
test/e2e/sql/src/test/resources/env/it-env.properties

Add proxy_random to it.cluster.adapters

---

infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/proxy-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
kernel/logging/core/pom.xml

Fixes #32377 .
- Block `shardingsphere-logging-core` from passing `logback-classic` dependencies to downstream modules. Once merged, logging behavior for most modules will look the same as if the following dependencies were added. Unless the downstream module declares a declaration for some Slf4j implementation, such as Log4j1, Log4j2, Reload4j, Logback and the defunct Jakarta Commons Logging, which has been defunct for ten years. Of course Apache Commons Logging https://github.com/apache/commons-logging was recently resurrected.
```xml
<dependency>
<groupId>org.slf4j</groupId>
<artifactId>slf4j-nop</artifactId>
<version>1.7.36</version>
</dependency>
```
---

Block `shardingsphere-logging-core` from passing `logback-classic` dependencies to downstream modules

---

kernel/logging/core/pom.xml
kernel/logging/core/src/main/java/org/apache/shardingsphere/logging/rule/builder/DefaultLoggingRuleConfigurationBuilder.java
pom.xml

Fixes #32377.
- Refactor `DefaultLoggingRuleConfigurationBuilder` to reduce usage of `logback-classic`. Apparently the adapter for `org.slf4j.impl.StaticLoggerBinder` is not in `logback-core`. It looks like there is no other way. Keep logback-classic in the classpath of shardingsphere jdbc.
```shell
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/linghengqian/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.18.0/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/linghengqian/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in …
```

Refactor `DefaultLoggingRuleConfigurationBuilder` to reduce usage of `logback-classic`

---

parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/util/ColumnExtractUtils.java

- Add extract combine left select in extractFromSelectStatementWithoutProjection method
---

Add extract combine left select in extractFromSelectStatementWithoutProjection method

---

test/e2e/sql/src/test/resources/cases/ral/dataset/empty_rules/export_metadata_to_file.xml
test/e2e/sql/src/test/resources/cases/ral/e2e-ral-export.xml

- Add e2e test for export metadata to file DistSQL
---

Add e2e test for export metadata to file DistSQL

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSet.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/function/mysql/impl/MySQLBinFunction.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/function/mysql/impl/MySQLBitCountFunction.java
test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select.xml

Fixes #32417.
- Fix null result in federated query for a single projected column
- Adjusts the return value of the function for an invalid argument
---

Fix null result in federated query for a single projected column

---

parser/sql/dialect/doris/src/main/antlr4/imports/doris/BaseRule.g4
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Fixes #32283.
- support reserved words in parsing doris sql.
---

support reserved words in parsing doris sql.

---

proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/information/SelectInformationSchemataExecutor.java

Fixes #32510.
- fix column mapping error when `select *`
- fix incorrect label when using alias query

Fix incorrect results for querying information_schema.SCHEMATA

---

test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/QueryableRALStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ral/impl/queryable/ExportMetaDataStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ral/ExportMetaDataToFileStatementTestCase.java
test/it/parser/src/main/resources/case/ral/queryable.xml
test/it/parser/src/main/resources/sql/supported/ral/queryable.xml

- Add sql parser test for export metadata to file DistSQL
---

Add sql parser test for export metadata to file DistSQL

---

.github/workflows/graalvm.yml
.github/workflows/nightly-build.yml
.github/workflows/nightly-ci-dynamic.yml
.github/workflows/nightly-ci.yml
distribution/proxy/src/main/release-docs/LICENSE
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
infra/expr/type/espresso/src/test/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParserTest.java
pom.xml

For #29052.
- Prevent use of GraalVM Native Build Tools Maven Plugin in parallel builds of project. This is one of the findings from https://github.com/linghengqian/hive-server2-jdbc-driver/issues/3. The Maven Plugin of GraalVM Native Build Tools is not thread-safe, and using the features of https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3 will cause problems. But it is hard to say that I know how to implement parallel construction of GraalVM Native Image on the GraalVM Native Build Tools side. The Native Image constructor uses up 3/4 of the system's maximum memory by default.
- Fixes https://github.com/apache/shardingsphere/actions/runs/10424218529/job/28872589371 . Temporarily blocked …

Prevent use of GraalVM Native Build Tools Maven Plugin in parallel builds of project

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTable.java

- Use CaseInsensitiveMap to replace toLowerCase method call
---

Use CaseInsensitiveMap to replace toLowerCase method call

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/preparer/inventory/InventoryPositionCalculator.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/preparer/inventory/splitter/InventoryDumperContextSplitter.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/IntervalToRangeIterator.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/preparer/inventory/InventoryPositionCalculatorTest.java

- InventoryTaskSplitter compatible with large integer primary key
---

InventoryTaskSplitter compatible with large integer primary key

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/DataConsistencyCheckUtils.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/result/RecordSingleTableInventoryCalculatedResult.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/TableInventoryCheckParameter.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/CalculationContext.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/RecordSingleTableInventoryCalculator.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/SingleTableInventoryCalculateParameter.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/InventoryDumper.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/InventoryDumperContext.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/InventoryQueryParameter.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/QueryRange.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/QueryType.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/dialect/DialectPipelineSQLBuilder.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/sql/PipelineDataConsistencyCalculateSQLBuilder.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/sql/PipelineImportSQLBuilder.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/sql/PipelineInventoryDumpSQLBuilder.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/sql/PipelinePrepareSQLBuilder.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/DatabaseTypeUtils.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/PipelineDataConsistencyCalculateSQLBuilderTest.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/PipelineInventoryDumpSQLBuilderTest.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/consistencycheck/table/calculator/RecordSingleTableInventoryCalculatorTest.java

- Refactor inventory dumper and data consistency streaming query to page query. Support: 1) Duplicated PK values, 2) Multiple columns PK
---

Refactor inventory dumper and data consistency streaming query to page query

---

docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md

Fixes #31526.
- Fixes incorrect source reference URL in Hive documentation. Affects English documents only.
---

Fixes incorrect source reference URL in Hive documentation

---

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/loader/type/ColumnMetaDataLoader.java
infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/metadata/data/loader/MySQLMetaDataLoader.java
infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussMetaDataLoader.java
infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLMetaDataLoader.java

For #29816
After this update, we can show table type by DistSQL

Collect table type in PostgreSQLMetaDataLoader

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/DataConsistencyCheckUtils.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/loader/StandardPipelineTableMetaDataLoader.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/model/PipelineIndexMetaData.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/model/PipelineTableMetaData.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineStringUtils.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineStringUtilsTest.java

- Support primary key columns ordering for standard pipeline table metadata loader
---

Support primary key columns ordering for standard pipeline table metadata loader

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/loader/StandardPipelineTableMetaDataLoader.java

- Set DatabaseMetaData.getIndexInfo approximate param from false to true. To improve performance in some databases
---

Set DatabaseMetaData.getIndexInfo approximate param from false to true

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/Keyword.g4
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml

Fixes #31558.
- Improve the parsing of methods in MySQL
---

Improve the parsing of methods in MySQL

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/ShardingSphereDatabaseData.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/ShardingSphereSchemaData.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/ShardingSphereStatistics.java

- Use CaseInsensitiveMap to replace toLowerCase method in ShardingSphereStatistics, ShardingSphereDatabaseData, ShardingSphereSchemaData
---

Use CaseInsensitiveMap to replace toLowerCase method in ShardingSphereStatistics, ShardingSphereDatabaseData, ShardingSphereSchemaData

---

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSetMetaData.java
kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/utils/EnumeratorUtils.java

- Fix sql federation unknown type exception caused by calcite wrong result type with bigint
---

Fix sql federation unknown type exception caused by calcite wrong result type with bigint

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/insert/keygen/engine/GeneratedKeyContextEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/InsertStatementContext.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/insert/keygen/engine/GeneratedKeyContextEngineTest.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereSchema.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTable.java
test/e2e/sql/src/test/resources/cases/dml/dataset/db/insert_single_with_generate_key_column.xml
test/e2e/sql/src/test/resources/cases/dml/e2e-dml-insert.xml
test/e2e/sql/src/test/resources/env/scenario/db/data/actual/init-sql/mysql/01-actual-init.sql

Fix the generated key column name case insensitivity error(#32756)

---

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/DDLE2EIT.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/RALE2EIT.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/RDLE2EIT.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/BatchDMLE2EIT.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/GeneralDMLE2EIT.java

Move the teardown code for the DML E2E test to the finally block.

---

infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/commons/TestShardingService.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/modes/cluster/EtcdTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/modes/cluster/ZookeeperTest.java

Fixes https://github.com/apache/shardingsphere/actions/runs/10671433372/job/29577234822 .
- Design a longer wait time before executing INSERT SQL in nativeTest of Zookeeper and Etcd. Currently, the waiting time for these two unit tests is still too short, and the metadata is often not fully refreshed. Manually refreshing metadata involves a lot of Java APIs that are not documented at all.
- I found that the `DETELE` statement of Clickhouse JDBC Driver sometimes takes a long time to execute. I think this is a bug in Clickhouse JDBC Driver, but the reproduction is not stable and can only be reproduced unstably in GraalVM Native Image.
---

Design a longer wait time before executing INSERT SQL in nativeTest of Zookeeper and Etcd

---

.github/workflows/nightly-check.yml

- update the swap script since apache does not accept the pierotofy action
---

Refactor : update the swap script since apache does not accept the pierotofy action

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dal/show/ShowTableStatusMergedResult.java

Fixes #32680 .
To safely handle cases where either object is null and avoid NPE during type conversion, you can add an early return check for null values and return 0 if either object is null. This approach ensures that your method won't attempt to perform operations on null objects, which would cause an NPE.
---

NPE occurs when execute show table status

---

pom.xml

Fixes https://github.com/apache/shardingsphere/security/dependabot/80 .
- Bump the Presto JDBC Driver version used in the unit test. Warnings like https://github.com/apache/shardingsphere/security/dependabot/80 were plaguing committer mailbox, and the dependency in question was only used to execute unit tests. These are GHSA-86q5-qcjc-7pv4 and GHSA-xm7x-f3w2-4hjm respectively.
- Before the release of Presto 0.289, we were unable to add shardingsphere's Presto integration to nativeTest under GraalVM Native Image because it was blocked by https://github.com/prestodb/presto/issues/15916 and https://github.com/prestodb/presto/issues/23226.
---

Bump the Presto JDBC Driver version used in the unit test

---

mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/MetaDataRefreshEngine.java

- Optimize MetaDataRefreshEngine, use storage unit database type when refresh metadata
---

Optimize MetaDataRefreshEngine, use storage unit database type when refresh metadata

---

agent/plugins/tracing/type/opentelemetry/pom.xml
pom.xml

Fixes #32786.
- Bump `opentelemetry-bom` to 1.41.0.
- Introducing `opentelemetry-semconv`. See https://opentelemetry.io/docs/languages/java/exporters/#otlp-dependencies .
- Apparently, https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-exporter-jaeger is no longer updated. Because according to https://opentelemetry.io/docs/languages/java/exporters/#jaeger we don't need something like that.
> [Jaeger](https://www.jaegertracing.io/) natively supports OTLP to receive trace data.
---

Bump `opentelemetry-bom` to 1.41.0

---

test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select-join.xml

- Remove duplicate e2e case in db, tbl scenario
---

Remove duplicate e2e case in db, tbl scenario

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/DMLStatement.g4
test/it/parser/src/main/resources/sql/supported/dml/update.xml

- Enhance Oracle update statement as alias parse and add test case
---

Enhance Oracle update statement as alias parse and add test case

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptInsertValueParameterRewriter.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertCipherNameTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertDefaultColumnsTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertDerivedColumnsTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertOnUpdateTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertValuesTokenGenerator.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertDerivedColumnsTokenGeneratorTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertOnUpdateTokenGeneratorTest.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/InsertClauseShardingConditionEngine.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/validator/dml/impl/ShardingInsertStatementValidator.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/InsertClauseShardingConditionEngineTest.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/insert/keygen/engine/GeneratedKeyContextEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/InsertStatementContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/InsertStatementBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/statement/InsertStatementBinderTest.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/statement/insert/InsertStatementConverter.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/dml/InsertStatement.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/util/TableExtractor.java
parser/sql/statement/core/src/test/java/org/apache/shardingsphere/sql/parser/statement/core/util/TableExtractorTest.java
proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareParameterMarkerExtractor.java
proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutor.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutorTest.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/InsertStatementAssert.java

- Modify InsertStatement#getTable method return Optional to adapt Oracle insert multi statements
---

Modify InsertStatement#getTable method return Optional to adapt Oracle insert multi statements

---

db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLBinaryProtocolValueFactory.java
db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLBoolBinaryProtocolValue.java
infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLMetaDataLoader.java

Fixes #32857.
- When loading column metadata, distinguish between bit and bool
- Add binary protocol value for bool

For #32857, support binary type bool value for PostgreSQL

---

.github/workflows/nightly-build.yml
distribution/agent/pom.xml
docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.en.md

Fixes #32777.
- Supports building ShardingSphere Agent's Docker Image locally
---

Supports building ShardingSphere Agent's Docker Image locally

---

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/operator/common/SQLExtensionOperatorTable.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/LiteralExpressionConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/NotExpressionConverter.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/function/mysql/MySQLOperatorTable.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/function/mysql/impl/MySQLNotFunction.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/planner/util/SQLFederationPlannerUtils.java
test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select.xml
test/it/optimizer/src/test/resources/converter/select.xml
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Ref #31912.
- Improved calcite sql node not operator conversion
- Support for federated query NOT operator
---

Support for federated query NOT operator

---

mode/core/src/test/java/org/apache/shardingsphere/mode/persist/service/QualifiedDataSourceStatePersistServiceTest.java

-
Replaced the newLine character \n with System.lineSeparator() as \n was giving test failure in different environment.
\n was giving the error as "" Argument(s) are different! ""
Used environment independent new Line Character System.ineSepaartor() which solves this issue.
---

assertUpdate Test error due to environment dependency of newLine character in class QualifiedDataSourceStatePersistServiceTest

---

pom.xml

For #32765 .
- Publish the Source JAR to the local Maven repository when building locally.
- This is mainly for debugging convenience for contributors. When executing a command like `./mvnw clean install -Prelease -T1C -DskipTests`, `shardingsphere-jdbc-5.5.1-SNAPSHOT-sources.jar` will be generated, which helps to trace the stack in IntelliJ IDEA. This helps with the debugging experience.
- Obviously, gitea and gitlab in the figure are the metadata of the mirror source, not from shardingsphere.
- ![image](https://github.com/user-attachments/assets/f61fc39c-31df-4bd7-aa3f-502af981e94c)
---

Publish the Source JAR to the local Maven repository when building locally

---

jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/unsupported/AbstractUnsupportedOperationConnection.java
jdbc/src/test/java/org/apache/shardingsphere/driver/jdbc/unsupported/UnsupportedOperationConnectionTest.java

For https://github.com/apache/shardingsphere/issues/32765#issuecomment-2374469288 .
- Mock get/set networkTimeout of `java.sql.Connection` in JDBC Driver to prevent HikariCP's Warning. See https://github.com/pgjdbc/pgjdbc/pull/849 .
- The default value of `java.net.Socket#getSoTimeout()` is normally `0`. A quick test using `org.apache.httpcomponents:httpclient:4.5.14`,
```java
@Test
public void test() throws SocketException {
int soTimeout = org.apache.http.conn.scheme.PlainSocketFactory.getSocketFactory().createSocket().getSoTimeout();
System.out.println(soTimeout);
}
```
- Also fixes https://github.com/brettwooldridge/HikariCP/issues/2196 .
```shell
13:01:12.583 [main] INFO com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Driver does not support …
```

Mock get/set networkTimeout of `java.sql.Connection` in JDBC Driver to prevent HikariCP's Warning

---

RELEASE-NOTES.md

- Add 5.5.1-SNAPSHOT to the release notes to guide developers to update the release notes
---

Add 5.5.1-SNAPSHOT to the release notes to guide developers to update the release notes

---

RELEASE-NOTES.md
docs/community/content/involved/contribute/contributor.cn.md
docs/community/content/involved/contribute/contributor.en.md

- Update contributor doc for update release note when submit new pr
---

Update contributor doc for update release note when submit new pr

---

features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/algorithm/shadow/hint/SQLHintShadowAlgorithm.java
features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/condition/ShadowDetermineCondition.java
features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/engine/ShadowRouteEngineFactory.java
features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/engine/determiner/HintShadowAlgorithmDeterminer.java
features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/engine/dml/AbstractShadowDMLStatementRouteEngine.java
features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/engine/dml/ShadowDeleteStatementRoutingEngine.java
features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/engine/dml/ShadowInsertStatementRoutingEngine.java
features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/engine/dml/ShadowSelectStatementRoutingEngine.java
features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/engine/dml/ShadowUpdateStatementRoutingEngine.java
features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/engine/impl/ShadowNonDMLStatementRoutingEngine.java
features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/algorithm/shadow/hint/SQLHintShadowAlgorithmTest.java
features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/route/engine/determiner/HintShadowAlgorithmDeterminerTest.java
features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/route/engine/impl/ShadowNonDMLStatementRoutingEngineTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/features/ShadowTest.java

Fixes #33045.
- Use hintValueContext to replace extract sql hint from sql statement for solving shadow sql hint bug
---

Use hintValueContext to replace extract sql hint from sql statement for solving shadow sql hint bug

---

RELEASE-NOTES.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
pom.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/features/ShadowTest.java

For #33063.
- Make Shadow feature available again in GraalVM Native Image. After #33063 was merged, unit test failures were actually due to missing GRM.
- Updated versions of test libraries and NMP. Junit 5.11 is now available under the GraalVM Native Image thanks to https://github.com/graalvm/native-build-tools/pull/603 being merged.
- Also for #29052 .
---

Make Shadow feature available again in GraalVM Native Image

---

.github/workflows/nightly-build.yml
RELEASE-NOTES.md
distribution/proxy-native/pom.xml
distribution/proxy-native/src/main/assembly/shardingsphere-proxy-native-binary-distribution.xml
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/com.zaxxer/HikariCP/4.0.3/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.seata/seata-all/2.1.0/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/proxy-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
test/native/native-image-filter/extra-filter.json
test/native/pom.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/proxy/commons/ProxyTestingServer.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/proxy/features/ShardingTest.java
test/native/src/test/resources/test-native/yaml/proxy/features/global.yaml

For #29052.
- Support running DistSQL under Proxy Native in the form of GraalVM Native Image.
- In order to directly collect the GraalVM Reachability Metadata of ShardingSphere Proxy through unit testing, we must directly start ShardingSphere Proxy without using the Docker Image.
- The most embarrassing part is that ShardingSphere Proxy cannot actually connect to H2database, which requires starting a MySQL container.
- The most awkward part of this PR is the splicing of DistSQL in `org.apache.shardingsphere.test.natived.proxy.features.ShardingTest`. Since we need to use the MySQL port of the MySQL container obtained from the testcontainers-java API, we always need to manually splice DistSQL instead of directly reading the `.sql` file. But the problem …

Support running DistSQL under Proxy Native in the form of GraalVM Native Image

---

features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/update/DropMaskRuleExecutorTest.java

Refactor DropMaskRuleExecutorTest

---

RELEASE-NOTES.md
docs/blog/content/material/2022_04_06_A_Holistic_Pluggable_Platform_for_Data_Sharding_ICDE_2022_Understanding_Apache_ShardingSphere.en.md
docs/blog/content/material/Feb_18_Apache_ShardingSphere_5.1.0_Now_Avaliable.en.md
docs/blog/content/material/Jan_28_Blog_Apache_ShardingSphere_Enterprise_Applications.en.md
docs/document/content/user-manual/common-config/builtin-algorithm/sharding.en.md
docs/document/content/user-manual/error-code/sql-error-code.cn.md
docs/document/content/user-manual/error-code/sql-error-code.en.md
docs/document/content/user-manual/shardingsphere-proxy/cdc/build.cn.md
docs/document/content/user-manual/shardingsphere-proxy/cdc/build.en.md
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/inline/ComplexInlineShardingAlgorithm.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/algorithm/MismatchedComplexInlineShardingAlgorithmColumnAndValueSizeException.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/metadata/DuplicateShardingActualDataNodeException.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/checker/ShardingRuleChecker.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/yaml/config/strategy/audit/YamlShardingAuditStrategyConfiguration.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/checker/ShardingTableRuleStatementChecker.java

- Rename wrong typo sharing to sharding in sharding feature related class and document
---

Rename wrong typo sharing to sharding in sharding feature related class and document

---

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDMLStatementVisitor.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/dml/DeleteStatement.java
parser/sql/statement/type/mysql/src/main/java/org/apache/shardingsphere/sql/parser/statement/mysql/dml/MySQLDeleteStatement.java
parser/sql/statement/type/mysql/src/main/java/org/apache/shardingsphere/sql/parser/statement/mysql/dml/MySQLInsertStatement.java
test/it/parser/src/main/resources/case/dml/delete.xml
test/it/parser/src/main/resources/case/dml/insert.xml
test/it/parser/src/main/resources/case/dml/replace.xml
test/it/parser/src/main/resources/sql/supported/dml/delete.xml
test/it/parser/src/main/resources/sql/supported/dml/insert.xml
test/it/parser/src/main/resources/sql/supported/dml/replace.xml

For #33094.
The syntax supported by MariaDB:
[INSERT...RETURNING](https://mariadb.com/kb/en/insertreturning/)
[REPLACE...RETURNING](https://mariadb.com/kb/en/replacereturning/)
[DELETE...RETURNING](https://mariadb.com/kb/en/delete/#returning)

Support MariaDB DML Returning Clause (#33094)

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/checker/ShardingRuleChecker.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/checker/ShardingTableRuleStatementChecker.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/converter/ShardingTableRuleStatementConverter.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/AlterShardingTableRuleExecutor.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/update/CreateShardingTableRuleExecutor.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/AlterShardingTableRuleExecutorTest.java
features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/update/CreateShardingTableRuleExecutorTest.java

Fixes #33050
- Check actual data nodes before update rule configuration
- Add unit tests

Check duplicate actual data nodes when create or alter sharding table rule

---

features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/query/ShowBroadcastTableRuleExecutorTest.java
features/broadcast/distsql/handler/src/test/resources/cases/show-broadcast-table-rules-current-config.yaml
features/broadcast/distsql/handler/src/test/resources/cases/show-broadcast-table-rules.xml
features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/route/ReadwriteSplittingSQLRouterTest.java
test/it/distsql/src/main/java/org/apache/shardingsphere/test/it/distsql/handler/engine/query/DistSQLDatabaseRuleQueryExecutorAssert.java

For #33142.
- Use parameterized `DistSQLDatabaseRuleQueryExecutorAssert` to instead of `DistSQLDatabaseRuleQueryExecutorTest`
---

Implement DistSQLDatabaseRuleQueryExecutorAssert on ShowBroadcastTableRuleExecutorTest

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingTable.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/resource/PhysicalResourceAggregator.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/loader/type/SchemaMetaDataLoader.java
infra/database/type/mysql/src/test/java/org/apache/shardingsphere/infra/database/mysql/metadata/data/loader/MySQLSchemaMetaDataLoaderTest.java
infra/database/type/opengauss/src/test/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussSchemaMetaDataLoaderTest.java
infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLSchemaMetaDataLoaderTest.java
kernel/single/core/src/main/java/org/apache/shardingsphere/single/datanode/SingleTableDataNodeLoader.java
kernel/single/core/src/main/java/org/apache/shardingsphere/single/decorator/SingleRuleConfigurationDecorator.java
kernel/single/core/src/main/java/org/apache/shardingsphere/single/rule/SingleRule.java
kernel/single/core/src/main/java/org/apache/shardingsphere/single/util/SingleTableLoadUtils.java
kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/query/ShowUnloadedSingleTablesExecutor.java
kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableExecutor.java
kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableExecutorTest.java

- Move getAggregatedDataSourceMap from SingleTableLoadUtils to PhysicalResourceAggregator
---

Move getAggregatedDataSourceMap from SingleTableLoadUtils to PhysicalResourceAggregator

---

RELEASE-NOTES.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/alter-storage-unit.cn.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/alter-storage-unit.en.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/register-storage-unit.cn.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/register-storage-unit.en.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/unregister-storage-unit.cn.md
docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/unregister-storage-unit.en.md

For #32172.
- Update DistSQL docs and RELEASE-NOTES

Update docs for storage unit RDL

---

.github/workflows/nightly-ci.yml
.mvn/wrapper/maven-wrapper.properties
RELEASE-NOTES.md
agent/core/src/test/java/org/apache/shardingsphere/agent/core/plugin/PluginLifecycleServiceManagerTest.java
mvnw
mvnw.cmd
pom.xml

For #32927.
- Support compiling and using ShardingSphere under OpenJDK 23.
- According to https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#proc , switch the value of `maven.compiler.proc`.
- Update Maven Wrapper version. Multi-threaded deadlock problems in the Maven lifecycle often plague CI.
---

Support compiling and using ShardingSphere under OpenJDK 23

---

RELEASE-NOTES.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
pom.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/HiveTest.java

For #29052.
- Support Hive integration module to connect to HiveServer2 4.0.1.
- Due to the ongoing dispute at https://issues.apache.org/jira/browse/HIVE-28445, no PR is expected to happen, so I am still maintaining the Thin JAR build of HiveServer2 JDBC Driver 4.0.1 in my personal repository https://github.com/linghengqian/hive-server2-jdbc-driver . This directly reduces the maintenance cost of thousands of lines of POM.
---

Support Hive integration module to connect to HiveServer2 4.0.1

---

parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/enums/SubqueryType.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/util/SubqueryExtractUtils.java

- Minor refactor for SubqueryExtractUtils
---

Minor refactor for SubqueryExtractUtils

---

RELEASE-NOTES.md
docs/document/content/user-manual/common-config/builtin-algorithm/expr.cn.md
docs/document/content/user-manual/common-config/builtin-algorithm/expr.en.md
examples/pom.xml
infra/expr/type/espresso/pom.xml
pom.xml

For #32927.
- Support building Example module with OpenJDK 23. Fixes https://github.com/apache/shardingsphere/actions/runs/11297151161/job/31423492593 .
- Due to the ongoing dispute at https://github.com/oracle/graal/issues/9382 , GraalVM Truffle's Espresso implementation currently does not have a GPL V2 LICENSE JAR. Cross-compiling GraalVM Truffle's Espresso implementation JAR via LLVM would only cause annoyance to contributors in the shardingsphere. Therefore, I need to import the non-OSI approved LICENSE `org.graalvm.polyglot:java:24.1.0` in the unit test. 
---

Support building Example module with OpenJDK 23

---

RELEASE-NOTES.md
distribution/proxy-native/Dockerfile
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
infra/expr/type/espresso/src/test/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParserTest.java

Fixes #33263.
- Change the Base Docker Image of ShardingSphere Proxy Native.
- Change `org.apache.shardingsphere.infra.expr.espresso.EspressoInlineExpressionParserTest` to restrict it from running on JDK22. See https://shardingsphere.apache.org/document/current/en/user-manual/common-config/builtin-algorithm/expr/#row-value-expressions-that-uses-the-groovy-syntax-based-on-graalvm-truffles-espresso-implementation for the Truffle API compatibility table https://medium.com/graalvm/40027a59c401 .
- ![image](https://github.com/user-attachments/assets/b7c02cca-ce27-453b-94ef-6de673b1f01c)
- ![image](https://github.com/user-attachments/assets/d7e74cd2-c583-462e-a267-faa821a477b3)
---
Before committing this PR, I'm sure that I have checked the following …

Change the Base Docker Image of ShardingSphere Proxy Native

---

RELEASE-NOTES.md
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDALStatementVisitor.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/dal/KillStatement.java
proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/KillProcessExecutor.java

Add query parameters and check for mysql kill processId

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/from/type/SimpleTableSegmentBinder.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/common/pojo/generic/SubstitutableColumnNameToken.java

- Add exclude field in SubstitutableColumnNameToken to avoid token duplicate
---

Add exclude field in SubstitutableColumnNameToken to avoid token duplicate

---

RELEASE-NOTES.md
parser/sql/dialect/doris/src/main/antlr4/imports/doris/BaseRule.g4
parser/sql/dialect/doris/src/main/antlr4/imports/doris/DorisKeyword.g4
parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/DorisStatementVisitor.java
test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml

As part of hacktoberfest, this is a POC for adding more parsing logic to Doris support. If this is successful, I will look at the other Doris SQL keywords in subsequent PRs. Continues to address #31508.
Note that
- Doris: `SELECT INSTR('foobar','bar')`
- MySQL: `SELECT POSITION('bar' IN 'foobar')` and `SELECT LOCATE('bar','foobar')` are the equivalent
I understand that I cannot add the labels to the PR and maintainers have to do it.
- Made g4 changes
- Includes test case additions to XML
- Added  `// DORIS ADDED BEGIN|END` markers to code for both this change and #33258
- Moved related code around to better reflect order in the g4
- Added to release notes
---
- [✅] My code follows the [code of …

Added INSTR to Doris parsing support (#31508)

---

.github/workflows/resources/scripts/unit-test-coverage-merge/code-coverage-merge.sh

- refactor the exclude jacoco exec files
---

Refactor : refactor the exclude jacoco exec files

---

proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/information/SelectInformationSchemataExecutor.java

Optimize  #33346.
- If `originalColumnName` is not SCHEMA_NAME, use alias to get result.

Fix missing logic db when query information_schema.SCHEMATA with NOT IN clause

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/combine/CombineSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/SelectStatementBinder.java

Fix the combine statement cannot find the outer table when bind

---

RELEASE-NOTES.md
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGenerator.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContext.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/util/SubqueryExtractUtils.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/util/WhereExtractUtils.java
parser/sql/statement/core/src/test/java/org/apache/shardingsphere/sql/parser/statement/core/util/SubqueryExtractUtilsTest.java

- Fix SQL performance issues caused by repeated subquery fetches
---

Fix SQL performance issues caused by repeated subquery fetches

---

RELEASE-NOTES.md
distribution/agent/Dockerfile
distribution/agent/pom.xml
docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.en.md

For #33350.
- Simplify the use of Agent's Docker Image. This properly aligns with the sidecar image processing of the skywalking agent. See https://hub.docker.com/r/apache/skywalking-java-agent .
- Bump Base Image to JDK23.
- I've verified this helps with https://github.com/apache/shardingsphere/issues/32793 .
---

Simplify the use of Agent's Docker Image

---

RELEASE-NOTES.md
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/SQLBindEngine.java
jdbc/src/test/java/org/apache/shardingsphere/driver/ShardingSphereDriverTest.java

Fixes #33366.
- Fix table does not exist exception when use HintManager#setDatabaseName to transparent
---

Fix table does not exist exception when use HintManager#setDatabaseName to transparent

---

RELEASE-NOTES.md
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/strategy/type/standard/StandardShardingStrategy.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/standard/ShardingStandardRoutingEngineTest.java

Fixes #33341.
- Remove ShardingRouteAlgorithmException check logic temporarily to support different actual table name config
---

Remove ShardingRouteAlgorithmException check logic temporarily to support different actual table name config

---

RELEASE-NOTES.md
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/select/EncryptIndexColumnTokenGenerator.java

Add index columns not empty judgement for IndexColumnTokenGenerator

---

distribution/agent/pom.xml
docs/community/content/involved/release/shardingsphere.cn.md
docs/community/content/involved/release/shardingsphere.en.md
docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.en.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md

Fixes #33350 .
- Add the release process of ShardingSphere Agent's Docker Image to the release guide.
- Neither Github Packages nor Docker Hub are actually official distribution channels for ASF, so I thought publishing only to Github Packages would simplify the communication process with ASF Infra.
- Publishing to Github Packages also avoids issues like #33263. Even ASF is limited by Docker Hub's rate limiting policy, which is not conducive to unit testing.
---

Add the release process of ShardingSphere Agent's Docker Image to the release guide

---

parser/sql/dialect/clickhouse/src/main/java/org/apache/shardingsphere/sql/parser/clickhouse/visitor/statement/type/ClickHouseDMLStatementVisitor.java
parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/DorisStatementVisitor.java
parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDMLStatementVisitor.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java
parser/sql/dialect/presto/src/main/java/org/apache/shardingsphere/sql/parser/presto/visitor/statement/type/PrestoDMLStatementVisitor.java
parser/sql/dialect/sql92/src/main/java/org/apache/shardingsphere/sql/parser/sql92/visitor/statement/type/SQL92DMLStatementVisitor.java
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java

Fix LiteralExpressionSegment cast exception in sql parser.

---

RELEASE-NOTES.md
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByMemoryMergedResult.java
test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select-group-by.xml

Fixes #6118.
- Fix avg, sum, min, max function return empty data when no query result
---

Fix avg, sum, min, max function return empty data when no query result return

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/comparator/InsertSelectColumnsEncryptorComparator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertCipherNameTokenGenerator.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/DistinctProjectionPrefixToken.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/OrderByToken.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/ProjectionsToken.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/InsertStatementContext.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/impl/AbstractSQLBuilder.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/common/pojo/SQLToken.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/common/pojo/generic/ColumnDefinitionToken.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/common/pojo/generic/InsertColumnsToken.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/common/pojo/generic/UseDefaultInsertColumnsToken.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/keygen/pojo/GeneratedKeyAssignmentToken.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/keygen/pojo/GeneratedKeyInsertColumnToken.java
infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/impl/RouteSQLBuilderTest.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java

- Refactor AbstractSQLBuilder logic and add getStopIndex in SQLToken
---

Refactor AbstractSQLBuilder logic and add getStopIndex in SQLToken

---

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/SQLRewriteEntry.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/context/SQLRewriteContext.java
infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/context/SQLRewriteContextTest.java
infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/engine/GenericSQLRewriteEngineTest.java
infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/engine/RouteSQLRewriteEngineTest.java

- Refactor SQLRewriteEntry to remove too much parameters
---

Refactor SQLRewriteEntry to remove too much parameters

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateColumnTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/select/EncryptGroupByItemTokenGenerator.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/common/pojo/generic/SubstitutableColumnNameToken.java

- Remove EqualsAndHashCode in SubstitutableColumnNameToken and change related LinkedHashSet ti LinkedList
---

Remove EqualsAndHashCode in SubstitutableColumnNameToken and change related LinkedHashSet ti LinkedList

---

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/impl/AbstractSQLBuilder.java

- Minor refactor for AbstractSQLBuilder
---

Minor refactor for AbstractSQLBuilder

---

RELEASE-NOTES.md
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/ColumnSegmentBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/ColumnSegmentBinderTest.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/generic/bound/TableSegmentBoundInfo.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/generic/table/TableNameSegment.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/util/TableExtractor.java

Add binding to owner table

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptRule.java

- Minor refactor for buildRuleAttributes in EncryptRule
---

Minor refactor for buildRuleAttributes in EncryptRule

---

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnectorFactory.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/StandardDatabaseConnector.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/StandardDatabaseConnectorTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/data/DatabaseBackendHandlerFactoryTest.java
proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/MySQLSetVariableAdminExecutorTest.java

- Add DatabaseConnector interface, and move execute logic to StandardDatabaseConnector
---

Add DatabaseConnector interface, and move execute logic to StandardDatabaseConnector

---

infra/util/src/main/java/org/apache/shardingsphere/infra/util/directory/ClasspathResourceDirectoryReader.java

Remove redundant null check of directoryUrlEnumeration in ClasspathResourceDirectoryReader

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/comparator/InsertSelectColumnsEncryptorComparator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertCipherNameTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGenerator.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/InsertStatementContext.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/parameter/builder/impl/StandardParameterBuilder.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/impl/AbstractSQLBuilder.java
infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/common/pojo/generic/SubstitutableColumnNameToken.java
test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/SQLRewriterIT.java
test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/parameter/SQLRewriteEngineTestParameters.java
test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/parameter/SQLRewriteEngineTestParametersBuilder.java
test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/type/SQLExecuteType.java

- Refactor encrypt token generator and encrypt sql rewrite it
---

Refactor encrypt token generator and encrypt sql rewrite it

---

RELEASE-NOTES.md
examples/pom.xml
kernel/sql-federation/optimizer/pom.xml
pom.xml

For #32927.
- Avoid using `-proc:full` when compiling ShardingSphere with OpenJDK23. This is mostly to align the behavior of https://github.com/apache/shardingsphere-elasticjob/pull/2454. Changing the default value of `-proc` on JDK23 is probably not a good idea.
- Since `org.apache.shardingsphere.sqlfederation.optimizer.planner.rule.transformation.PushProjectIntoScanRule` is generating **`org.apache.shardingsphere.sqlfederation.optimizer.planner.rule.transformation.ImmutablePushProjectIntoScanRule`** through `org.immutables.processor.ProxyProcessor`, the scope of `annotationProcessorPaths` is quite scattered. See https://github.com/immutables/immutables/issues/713 .
- Bump Lombok to 1.18.36 for further support of JDK23. See …

Avoid using `-proc:full` when compiling ShardingSphere with OpenJDK23

---

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/stream/JDBCStreamQueryResult.java
infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/stream/JDBCStreamQueryResultTest.java

Fixes #33660 
- Support Sharding-JDBC to parse dateTime as ZonedDateTime.
---

ResultSet support ZonedDateTime(#33660)

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/checker/sql/predicate/EncryptPredicateColumnSupportedChecker.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/context/EncryptSQLRewriteContextDecorator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptPredicateParameterRewriter.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateColumnTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptPredicateEqualRightValueToken.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptPredicateFunctionRightValueToken.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptPredicateInRightValueToken.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/util/EncryptPredicateSegmentUtils.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/checker/sql/predicate/EncryptPredicateColumnSupportedCheckerTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/util/EncryptPredicateSegmentUtilsTest.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/InsertStatementContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/combine/CombineSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/SubquerySegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/from/type/SubqueryTableSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/SelectStatementBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/ExistsSubqueryExpressionBinderTest.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/projection/impl/SubqueryProjectionConverter.java
parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/DorisStatementVisitor.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/dml/expr/subquery/SubquerySegment.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/dml/SelectStatement.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/util/SubqueryExtractUtils.java
test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-subquery.xml
test/it/rewriter/src/test/resources/scenario/mix/case/query-with-cipher/dml/select/select-subquery.xml

- Extract subquery context for encrypt predicate rewrite and refactor subquery type to SelectStatement
---

Extract subquery context for encrypt predicate rewrite and refactor subquery type to SelectStatement

---

RELEASE-NOTES.md
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptMergedResult.java

Fix merge exception without encrypt rule in database

---

test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml

Fixes #31554.
- I've verified all sql can be parsed by the parser
- I've check SQLStatement can correctly capture the params in the method
- added corresponding test case for each sql, and SQL Parser IT run successfully.
---

Improve the parsing of methods in MySQL (#31554)

---

RELEASE-NOTES.md
parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Ref #33719.
- Fix mysql parse zone unreversed keyword error
---

Fix mysql parse zone unreserved keyword error

---

RELEASE-NOTES.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.en.md
infra/database/type/hive/src/main/java/org/apache/shardingsphere/infra/database/hive/connector/HiveConnectionPropertiesParser.java
infra/database/type/hive/src/main/java/org/apache/shardingsphere/infra/database/hive/metadata/data/loader/HiveMetaDataLoader.java
infra/database/type/hive/src/test/java/org/apache/shardingsphere/infra/database/hive/connector/HiveConnectionPropertiesParserTest.java

For #29052.
- Support setting `hive_conf_list`, `hive_var_list` and `sess_var_list` for jdbcURL when connecting to HiveServer2. This is actually a prerequisite for the nativeTest test under GraalVM Native Image to connect to HiveServer2 with Zookeeper service discovery enabled.
- Due to the change in https://github.com/apache/hive/pull/2153, `org.apache.hadoop.hive.metastore.HiveMetaStoreClient#(String, String)` has been replaced by `org.apache.hadoop.hive.metastore.HiveMetaStoreClient#(org.apache.hadoop.hive.metastore.api.GetTableRequest)`. Considering that shardingsphere do not test HiveServer2 for `2.x` and `3.x` like DBeaver, this will not break any unit tests.
---

Support setting `hive_conf_list`, `hive_var_list` and `sess_var_list` for jdbcURL when connecting to HiveServer2

---

RELEASE-NOTES.md
docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/testcontainers/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/testcontainers/_index.en.md
infra/common/src/main/java/org/apache/shardingsphere/infra/database/DatabaseTypeEngine.java
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/PostgresTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/SQLServerTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/transactions/base/SeataTest.java

For #29052.
- Support connecting to HiveServer2 through database connection pools other than HikariCP. HiveServer2 JDBC Driver seems to deliberately bypass all the convenient ways to implement JDBC specification. There are simple public methods to use in https://github.com/apache/hive/blob/rel/release-4.0.1/jdbc/src/java/org/apache/hive/jdbc/HiveDriver.java and https://github.com/apache/hive/blob/rel/release-4.0.1/jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java . What I am referring to is exactly `org.apache.hive.jdbc.HiveConnection#getConnectedUrl()`. This creates an easy access.
- ![image](https://github.com/user-attachments/assets/87b894a0-d464-40c3-865a-3e1d2a5bbcfc)
- As a successor to #33377 , add description of shardingsphere agent …

Support connecting to HiveServer2 through database connection pools other than HikariCP

---

RELEASE-NOTES.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/testcontainers/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/testcontainers/_index.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/com.github.docker-java/docker-java-api/3.4.0/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.testcontainers/junit-jupiter/1.20.1/reflect-config.json
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/hive/HiveSimpleTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/hive/HiveZookeeperServiceDiscoveryTest.java
test/native/src/test/resources/META-INF/native-image/shardingsphere-test-native-test-metadata/reflect-config.json
test/native/src/test/resources/test-native/yaml/jdbc/databases/hive/simple.yaml
test/native/src/test/resources/test-native/yaml/jdbc/databases/hive/zookeeper-sde.yaml

For #29052.
- Support connecting to HiveServer2 with ZooKeeper Service Discovery enabled in GraalVM Native Image.
- The testcontainers java documentation was missing a reference to the postgresql jdbc driver. This PR adds it.
- Simplifies the description of Docker Compose in HiveServer2 documentation to improve focus.
---

Support connecting to HiveServer2 with ZooKeeper Service Discovery enabled in GraalVM Native Image

---

RELEASE-NOTES.md
infra/database/type/clickhouse/src/main/java/org/apache/shardingsphere/infra/database/clickhouse/type/ClickHouseDatabaseType.java
infra/database/type/clickhouse/src/test/java/org/apache/shardingsphere/infra/database/clickhouse/type/ClickHouseDatabaseTypeTest.java

For #29052.
- Partial support for connecting to embedded ClickHouse `chDB`. See https://clickhouse.com/docs/en/chdb .
- There is apparently controversy in https://github.com/chdb-io/chdb/issues/243 , and it is a big question whether embedded ClickHouse should only use FFM on JDK22+. Corresponding to https://github.com/linux-china/chdb-java-ffm/issues/1, it seems that the result of merging the projects is nothing.
- But whether it is https://github.com/chdb-io/chdb-java or https://github.com/linux-china/chdb-java-ffm , the two different chDB JDBC Drivers use `jdbc:chdb` as the jdbcUrl prefix. At the ShardingSphere level, it is not a problem to support 4 drivers for a single database dialect parsing module at the same time.
- Since this is a standalone …

Partial support for connecting to embedded ClickHouse `chDB`

---

RELEASE-NOTES.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/clickhouse/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/clickhouse/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/testcontainers/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/testcontainers/_index.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
test/native/pom.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/commons/TestShardingService.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/ClickHouseTest.java

For #29052.
- Adds documentation for ClickHouse support.
- TL;DR, no developer would like to see a long discussion about ClickHouse in the documentation of GraalVM Native Image integration. It is necessary to separate the independent documentation of ClickHouse.
- Add additional instructions for `org.testcontainers.jdbc.ContainerDatabaseDriver#killContainers()` in the testcontainers document. Some downstream projects have enabled the parallel execution feature of unit tests in Junit5, but this feature is basically useless for testcontainers-java because the concurrency capability of the Client/Server architecture of Docker Engine may not be that strong.
- Update docs for hiveserver2 integration. Since #33279 was merged, the …

Adds documentation for ClickHouse support

---

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/BroadcastSQLRouter.java
features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/BroadcastSQLRouterTest.java
features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/route/ReadwriteSplittingSQLRouter.java
features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/route/ReadwriteSplittingSQLRouterTest.java
features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/ShadowSQLRouter.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/cache/route/CachedShardingSQLRouter.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/ShardingSQLRouter.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/ShardingRouteEngineFactory.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/cache/route/CachedShardingSQLRouterTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/ShardingRouteEngineFactoryTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java
infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/SQLRouteEngine.java
infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/tableless/TablelessRouteEngineFactory.java
infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/tableless/type/broadcast/DatabaseInstanceBroadcastRouteEngine.java
infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/tableless/type/broadcast/InstanceBroadcastRouteEngine.java
infra/route/src/main/java/org/apache/shardingsphere/infra/route/type/DecorateSQLRouter.java
infra/route/src/test/java/org/apache/shardingsphere/infra/route/engine/tableless/TablelessRouteEngineFactoryTest.java
infra/route/src/test/java/org/apache/shardingsphere/infra/route/fixture/router/DataSourceSQLRouterFixture.java
infra/route/src/test/java/org/apache/shardingsphere/infra/route/fixture/router/TableSQLRouterFailureFixture.java
infra/route/src/test/java/org/apache/shardingsphere/infra/route/fixture/router/TableSQLRouterFixture.java
kernel/single/core/src/main/java/org/apache/shardingsphere/single/route/SingleSQLRouter.java
kernel/single/core/src/test/java/org/apache/shardingsphere/single/route/SingleSQLRouterTest.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/AbstractMigrationE2EIT.java

Ref #33811.
- Move tableless sql route in sharding to TablelessRouteEngineFactory
---

Move tableless sql route in sharding to TablelessRouteEngineFactory

---

RELEASE-NOTES.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/resource-config.json
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/hive/AcidTableTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/hive/IcebergTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/hive/ZookeeperServiceDiscoveryTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/transactions/base/SeataTest.java
test/native/src/test/resources/META-INF/native-image/shardingsphere-test-native-test-metadata/reflect-config.json
test/native/src/test/resources/test-native/sql/test-native-databases-hive-acid.sql
test/native/src/test/resources/test-native/sql/test-native-databases-hive-iceberg.sql
test/native/src/test/resources/test-native/yaml/jdbc/databases/hive/acid.yaml
test/native/src/test/resources/test-native/yaml/jdbc/databases/hive/iceberg.yaml
test/native/src/test/resources/test-native/yaml/jdbc/databases/hive/zsd.yaml

For #29052.
- Removes use of `iceberg.mr.schema.auto.conversion` from documentation due to HIVE-26507 . See https://github.com/apache/hive/pull/3570 and https://github.com/apache/hive/pull/3593 .
- Add nativeTest for connecting to HiveServer2 using ACID tables under GraalVM Native Image.
- Update the unreasonable Seata AT documentation. According to further investigation of third-party documents like https://www.yuque.com/linghengqian/meve2v/es8d3a8a18odao7x , it is not necessary to set global interceptors for all microservices.
- Introduces additions to `initFile` in HiveServer2 documentation to partially support the use of `set` statements.
- I personally don't understand why the unit test of HiveServer2 is so slow. Can't believe how slow …

Removes use of `iceberg.mr.schema.auto.conversion` from documentation due to HIVE-26507

---

RELEASE-NOTES.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.hadoop/hadoop-common/3.3.6/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.hadoop/hadoop-common/3.3.6/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.hive/hive-jdbc/4.0.1/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/proxy-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/resource-config.json
pom.xml
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java
test/native/native-image-filter/extra-filter.json
test/native/pom.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/hive/StandaloneMetastoreTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/hive/ZookeeperServiceDiscoveryTest.java
test/native/src/test/resources/META-INF/native-image/shardingsphere-test-native-test-metadata/reflect-config.json
test/native/src/test/resources/test-native/yaml/jdbc/databases/hive/standalone-hms.yaml

For #29052.
- Fixes the issue that ShardingSphere cannot connect to HiveServer2 using remote Hive Metastore Server.
- Fixes https://github.com/apache/shardingsphere/pull/33840 E2E .
- I did further confirm at https://github.com/linghengqian/hive-server2-jdbc-driver/pull/15 and https://issues.apache.org/jira/browse/HIVE-28652 that HiveServer2 JDBC Driver never uses `org.apache.hadoop.hive.conf.HiveConf`. I think HiveServer2's use of `org.apache.hadoop.hive.conf.HiveConf` is problematic.
- Updates to documentation to help explain the Error Log below.
```shell
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/apache/hadoop/mapred/JobConf …
```

Fix the issue that ShardingSphere cannot connect to HiveServer2 using remote Hive Metastore Server

---

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereSchema.java
kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/util/CDCSchemaTableUtils.java

Use ShardingSphereMetaDataIdentifier on ShardingSphereSchema

---

RELEASE-NOTES.md
parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

- Fix mysql range parse error when use table owner
---

Fix mysql range parse error when use table owner

---

pom.xml

Fixes #33880.
- refactor the compiler plugin to avoid the JDK 8 source warning
---

Refactor : refactor the compiler plugin to avoid the JDK 8 source warning

---

RELEASE-NOTES.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.en.md
docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/seata-at/_index.cn.md
docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/seata-at/_index.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/proxy-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
kernel/transaction/type/base/seata-at/src/main/java/org/apache/shardingsphere/transaction/base/seata/at/SeataATShardingSphereTransactionManager.java
pom.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/commons/repository/OrderRepository.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/ClickHouseTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/proxy/transactions/base/SeataTest.java
test/native/src/test/resources/META-INF/native-image/io.grpc/grpc-netty-shaded/native-image.properties
test/native/src/test/resources/META-INF/native-image/shardingsphere-test-native-test-metadata/reflect-config.json
test/native/src/test/resources/seata-script-client-conf-file.conf
test/native/src/test/resources/test-native/sh/postgres.sh
test/native/src/test/resources/test-native/yaml/proxy/transactions/base/global.yaml

For #29052.
- Support Seata AT integration under Proxy Native in GraalVM Native Image.
- Add `org.apache.seata.config.ConfigurationFactory#reload()` to the lifecycle of Seata integration according to the discussion at https://github.com/apache/incubator-seata/issues/7039 .
- Also fixes #33791 . Add doc for using Seata AT integration with ShardingSphere Proxy and ShardingSphere Proxy Native.
- Bump the version of https://github.com/linghengqian/hive-server2-jdbc-driver used for nativeTest. The original Apache Hive issue is mired in huge controversy.
---

Support Seata AT integration under Proxy Native in GraalVM Native Image

---

docs/document/content/user-manual/common-config/props.cn.md
docs/document/content/user-manual/common-config/props.en.md

@terrymanu So sorry ,There is something wrong with document I just merged. I select a wrong branch. Please merge this.

[Fix][Doc]Fixed document hyperlinks and removed redundancy

---

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/loader/MetaDataLoader.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/datatype/DataTypeRegistry.java
infra/database/type/h2/src/main/java/org/apache/shardingsphere/infra/database/h2/metadata/data/loader/H2MetaDataLoader.java
infra/database/type/h2/src/test/java/org/apache/shardingsphere/infra/database/h2/metadata/data/loader/H2MetaDataLoaderTest.java
infra/database/type/hive/src/main/java/org/apache/shardingsphere/infra/database/hive/metadata/data/loader/HiveMetaDataLoader.java
infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/metadata/data/loader/MySQLMetaDataLoader.java
infra/database/type/mysql/src/test/java/org/apache/shardingsphere/infra/database/mysql/metadata/data/loader/MySQLMetaDataLoaderTest.java
infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussMetaDataLoader.java
infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/database/OpenGaussDatabaseMetaData.java
infra/database/type/opengauss/src/test/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussMetaDataLoaderTest.java
infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/data/loader/OracleMetaDataLoader.java
infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/database/OracleDatabaseMetaData.java
infra/database/type/oracle/src/test/java/org/apache/shardingsphere/infra/database/oracle/metadata/data/loader/OracleMetaDataLoaderTest.java
infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLMetaDataLoader.java
infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/database/PostgreSQLDatabaseMetaData.java
infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLMetaDataLoaderTest.java
infra/database/type/sqlserver/src/main/java/org/apache/shardingsphere/infra/database/sqlserver/metadata/data/loader/SQLServerMetaDataLoader.java
infra/database/type/sqlserver/src/test/java/org/apache/shardingsphere/infra/database/sqlserver/metadata/data/loader/SQLServerMetaDataLoaderTest.java

- Use DataTypeRegistry to cache date type load and reuse in different scenario
---

Use DataTypeRegistry to cache date type load and reuse in different scenario

---

proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/execute/MySQLComStmtExecuteExecutor.java
proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/fieldlist/MySQLComFieldListPacketExecutor.java

Ref: #33766
- Fix NPE error when MySQLComStmtExecuteExecutor and MySQLComFieldListPacketExecutor executing close
---

Fix NPE error when MySQLComStmtExecuteExecutor and MySQLComFieldListPacketExecutor executing close

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGenerator.java

- Remove useless isNeedRewrite call in EncryptProjectionTokenGenerator
---

Remove useless isNeedRewrite call in EncryptProjectionTokenGenerator

---

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/rule/BroadcastRule.java
features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/route/engine/BroadcastRouteEngineFactoryTest.java
features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/rule/BroadcastRuleTest.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaData.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportMetaDataExecutor.java

Use ShardingSphereMetaDataIdentifier on ShardingSphereMetaData.databases

---

infra/database/type/testcontainers/src/main/java/org/apache/shardingsphere/infra/database/testcontainers/type/TcFirebirdDatabaseType.java
infra/database/type/testcontainers/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.database.core.type.DatabaseType
infra/database/type/testcontainers/src/test/java/org/apache/shardingsphere/infra/database/testcontainers/type/TestcontainersDatabaseTypeTest.java

Fixes #33782.
-  Add support to TestContainers JDBC URL of Firebird to the optional module
---

Added support to TestContainers JDBC URL of Firebird

---

docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/testcontainers/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/testcontainers/_index.en.md

Ref #33782.
- Adds documentation for Firebird support
---

Adds documentation for Firebird support

---

infra/common/pom.xml
jdbc/pom.xml

- Add module shardingsphere-infra-database-firebird to infra/common pom.xml
- Add module shardingsphere-parser-sql-firebird to jdbc/pom.xml
I don't know how I missed this when I was testing firebird modules when creating the first pr, but without it SPILodaer doesn't load firebird classes at all.
---

Add firebird classes to infra/common and jdbc POMs

---

features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/metadata/EncryptMetaDataReviseEngineTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/metadata/ShardingMetaDataReviseEngineTest.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/GenericSchemaBuilder.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereColumn.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereConstraint.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereIndex.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTable.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereView.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/MetaDataReviseEngine.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/column/ColumnReviseEngine.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/constraint/ConstraintReviseEngine.java
infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/index/IndexReviseEngine.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTableTest.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/constraint/ConstraintReviseEngineTest.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/index/IndexReviseEngineTest.java
infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/schema/SchemaMetaDataReviseEngineTest.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/model/ColumnMetaData.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/model/ConstraintMetaData.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/model/IndexMetaData.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/model/SchemaMetaData.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/model/TableMetaData.java
infra/database/type/h2/src/test/java/org/apache/shardingsphere/infra/database/h2/metadata/data/loader/H2MetaDataLoaderTest.java
infra/database/type/mysql/src/test/java/org/apache/shardingsphere/infra/database/mysql/metadata/data/loader/MySQLMetaDataLoaderTest.java
infra/database/type/opengauss/src/test/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussMetaDataLoaderTest.java
infra/database/type/oracle/src/test/java/org/apache/shardingsphere/infra/database/oracle/metadata/data/loader/OracleMetaDataLoaderTest.java
infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLMetaDataLoaderTest.java
infra/database/type/sqlserver/src/test/java/org/apache/shardingsphere/infra/database/sqlserver/metadata/data/loader/SQLServerMetaDataLoaderTest.java
kernel/single/core/src/test/java/org/apache/shardingsphere/single/metadata/SingleMetaDataReviseEngineTest.java

- Remove useless EqualsAndHashCode in ColumnMetaData, ShardingSphereColumn and other objects
---

Remove useless EqualsAndHashCode in ColumnMetaData, ShardingSphereColumn and other objects

---

features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/yaml/swapper/YamlReadwriteSplittingRuleConfigurationSwapper.java
infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/YamlEngine.java
infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/constructor/ShardingSphereYamlConstructor.java

- Optimize loader options config of YAML, change maxAliasesForCollections from by default 50 to 1000
---

Optimize loader options config of YAML, change maxAliasesForCollections from by default 50 to 1000

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/checker/sql/projection/EncryptSelectProjectionSupportedChecker.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/checker/sql/predicate/EncryptPredicateColumnSupportedCheckerTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/checker/sql/projection/EncryptSelectProjectionSupportedCheckerTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptMergedResultTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/comparator/InsertSelectColumnsEncryptorComparatorTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/fixture/EncryptGeneratorFixtureBuilder.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGeneratorTest.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/ColumnSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/from/type/SimpleTableSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/util/SubqueryTableBindUtils.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/ColumnProjectionTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/assign/AssignmentSegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/ColumnSegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/SubquerySegmentBinderTest.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/generator/PipelineDDLGenerator.java
kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/context/SQLFederationExecutorContext.java
kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java
kernel/sql-federation/executor/src/test/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutorTest.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/generic/bound/ColumnSegmentBoundInfo.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/generic/bound/TableSegmentBoundInfo.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/PreviewExecutor.java
proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/fieldlist/MySQLComFieldListPacketExecutor.java
proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java
proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLComQueryPacketExecutorTest.java
proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandlerTest.java
proxy/frontend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/command/query/extended/bind/OpenGaussComBatchBindExecutorTest.java
proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutor.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLAggregatedBatchedStatementsCommandExecutorTest.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutorTest.java

- Refactor ColumnSegmentBoundInfo and correct pass to SQLBindEngine databaseName
---

Refactor ColumnSegmentBoundInfo and correct pass to SQLBindEngine databaseName

---

distribution/proxy/src/main/resources/bin/start.bat

Fixes #34018.
1. windows start.bat uses javaw to run in the background
2. redirect the output log file
---

Fix Windows startup script runs in the background and outputs log files

---

RELEASE-NOTES.md
infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/checker/MySQLDatabasePrivilegeChecker.java
infra/database/type/mysql/src/test/java/org/apache/shardingsphere/infra/database/mysql/checker/MySQLDatabasePrivilegeCheckerTest.java

Fixes #34036.
- User privilege
- Register storage unit

Support ALL PRIVILEGES ON `DB`.* in MySQLDatabasePrivilegeChecker

---

parser/sql/dialect/firebird/src/main/antlr4/imports/firebird/DMLStatement.g4
parser/sql/dialect/firebird/src/main/java/org/apache/shardingsphere/sql/parser/firebird/visitor/statement/type/FirebirdDMLStatementVisitor.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/dml/UpdateStatement.java
parser/sql/statement/type/firebird/src/main/java/org/apache/shardingsphere/sql/parser/statement/firebird/dml/FirebirdDeleteStatement.java
parser/sql/statement/type/firebird/src/main/java/org/apache/shardingsphere/sql/parser/statement/firebird/dml/FirebirdInsertStatement.java
parser/sql/statement/type/firebird/src/main/java/org/apache/shardingsphere/sql/parser/statement/firebird/dml/FirebirdUpdateStatement.java
test/it/parser/src/main/resources/case/dml/update.xml
test/it/parser/src/main/resources/sql/supported/dml/delete.xml
test/it/parser/src/main/resources/sql/supported/dml/insert.xml
test/it/parser/src/main/resources/sql/supported/dml/update.xml

Fixes #33977.
- Added support returning for insert statement
- Added support returning for update statement
- Added support returning for delete statement
---

Added support returning for some firebird requests

---

test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select-aggregate.xml

- Remove openGauss db-types for group_concat e2e test case
---

Remove openGauss db-types for group_concat e2e test case

---

db-protocol/opengauss/src/main/java/org/apache/shardingsphere/db/protocol/opengauss/constant/OpenGaussProtocolDefaultVersionProvider.java
infra/database/type/opengauss/src/main/resources/schema/opengauss/pg_catalog/pg_attrdef.yaml
infra/database/type/opengauss/src/main/resources/schema/opengauss/pg_catalog/pg_attribute.yaml
infra/database/type/opengauss/src/main/resources/schema/opengauss/pg_catalog/pg_description.yaml
infra/database/type/opengauss/src/main/resources/schema/opengauss/pg_catalog/pg_type.yaml

- Add oid column for pg_description, pg_attribute, pg_type, pg_attrdef table of OpenGauss
- Change default version from 12.3 to 9.2.4 of openGauss
---

Add oid column for pg_description, pg_attribute, pg_type, pg_attrdef table of OpenGauss

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/from/type/SimpleTableSegmentBinder.java

- Optimize SimpleTableSegmentBinder, add table of pg_catalog
---

Optimize SimpleTableSegmentBinder, add table of pg_catalog

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/from/type/SimpleTableSegmentBinder.java

Ref #34075
- Optimize system table judgment in SimpleTableSegmentBinder
---

Optimize system table judgment in SimpleTableSegmentBinder

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/data/ShardingStatisticsTableCollector.java

- Optimize ShardingStatisticsTableCollector to support aggregated datasource
---

Optimize ShardingStatisticsTableCollector to support aggregated datasource

---

test/e2e/sql/src/test/resources/cases/dql/dataset/empty_storage_units/opengauss/select_opengauss_pg_catalog_pg_attrdef.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/empty_storage_units/opengauss/select_opengauss_pg_catalog_pg_attribute.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/empty_storage_units/opengauss/select_opengauss_pg_catalog_pg_description.xml
test/e2e/sql/src/test/resources/cases/dql/dataset/empty_storage_units/opengauss/select_opengauss_pg_catalog_pg_type.xml

Ref #34073
- Fix errors caused by missing oid column in pg_description, pg_attribute, pg_type, pg_attrdef table of OpenGauss
---

Fix errors caused by missing oid column in pg_description, pg_attribute, pg_type, pg_attrdef table of OpenGauss

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/SQLBindEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/combine/CombineSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/SubquerySegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/from/type/SimpleTableSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/from/type/SubqueryTableSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/SQLStatementBinderContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/type/DDLStatementBindEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/type/DMLStatementBindEngine.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/ColumnSegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/ExistsSubqueryExpressionBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/FunctionExpressionSegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/SubquerySegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/from/type/JoinTableSegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/from/type/SimpleTableSegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/from/type/SubqueryTableSegmentBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/DeleteStatementBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/InsertStatementBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/SelectStatementBinderTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/UpdateStatementBinderTest.java

- Skip table exist validate when bind create table statement with skipMetaDadaValidate
---

Skip table exist validate when bind create table statement with skipMetaDadaValidate

---

RELEASE-NOTES.md
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptInsertPredicateColumnTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateColumnTokenGenerator.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/fixture/EncryptGeneratorFixtureBuilder.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateColumnTokenGeneratorTest.java
test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select-sub-query.xml

- Use sql bind info in EncryptInsertPredicateColumnTokenGenerator to avoid wrong column table mapping
---

Use sql bind info in EncryptInsertPredicateColumnTokenGenerator to avoid wrong column table mapping

---

RELEASE-NOTES.md
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/checker/sql/ddl/ShardingCreateIndexSupportedCheckerTest.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/CreateIndexStatementBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/type/DDLStatementBindEngine.java
parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/type/OpenGaussDDLStatementVisitor.java
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/type/PostgreSQLDDLStatementVisitor.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/ddl/CreateIndexStatement.java
parser/sql/statement/type/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/statement/postgresql/ddl/PostgreSQLCreateIndexStatement.java
test/it/binder/src/test/java/org/apache/shardingsphere/test/it/sql/binder/dialect/opengauss/OpenGaussBinderIT.java
test/it/binder/src/test/java/org/apache/shardingsphere/test/it/sql/binder/dialect/postgresql/PostgreSQLBinderIT.java
test/it/binder/src/test/resources/cases/ddl/create-index.xml
test/it/binder/src/test/resources/sqls/ddl/create-index.xml

Ref #34029.
- Support create index statement sql bind
---

Support create index statement sql bind

---

RELEASE-NOTES.md
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
parser/sql/statement/type/mysql/src/main/java/org/apache/shardingsphere/sql/parser/statement/mysql/dml/MySQLUpdateStatement.java

- Support MySQL update with statement parse
---

Support MySQL update with statement parse

---

RELEASE-NOTES.md
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/checker/sql/orderby/EncryptOrderByItemSupportedChecker.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/checker/sql/predicate/EncryptPredicateColumnSupportedChecker.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/condition/EncryptConditionEngine.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/context/EncryptSQLRewriteContextDecorator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/select/EncryptGroupByItemTokenGenerator.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/checker/sql/orderby/EncryptOrderByItemSupportedCheckerTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/checker/sql/predicate/EncryptPredicateColumnSupportedCheckerTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateRightValueTokenGeneratorTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/select/EncryptGroupByItemTokenGeneratorTest.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/WhereClauseShardingConditionEngine.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/WhereClauseShardingConditionEngineTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/ExpressionSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/BetweenExpressionSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/order/GroupBySegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/order/OrderBySegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/order/item/ColumnOrderByItemSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/order/item/ExpressionOrderByItemSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/order/item/OrderByItemSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/predicate/HavingSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/predicate/WhereSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/DeleteStatementBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/SelectStatementBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/UpdateStatementBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContextTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/predicate/WhereSegmentBinderTest.java

Ref #34029.
- Remove TablesContext#findTableNames method and use sql bind info to replace
---

Remove TablesContext#findTableNames method and implement select order by, group by bind logic

---

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dql/GeneralDQLE2EIT.java

Add skip execute query method in general dql E2E

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/cache/checker/ShardingRouteCacheableChecker.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/InsertClauseShardingConditionEngine.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/ShardingConditionEngine.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/WhereClauseShardingConditionEngine.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/WhereClauseShardingConditionEngineTest.java

Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZP39K9yV8A_QVcGzsqc

Fix sonar issue on WhereClauseShardingConditionEngine

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/cache/checker/ShardingRouteCacheableChecker.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/InsertClauseShardingConditionEngine.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/ShardingConditionEngine.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/WhereClauseShardingConditionEngine.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/WhereClauseShardingConditionEngineTest.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/generator/PipelineDDLGenerator.java

Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&id=apache_shardingsphere&open=AZPx8iwgHNwUBn8QqLke

Fix sonar issue on PipelineDDLGenerator

---

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportDatabaseConfigurationExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportMetaDataExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportMetaDataExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/ClusterExportMetaDataGenerator.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/DatabaseExportMetaDataGenerator.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/ExportUtils.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/MetaDataImportExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/YamlDatabaseConfigurationImportExecutor.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportDatabaseConfigurationExecutorTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportMetaDataExecutorTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportDatabaseConfigurationExecutorTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportMetaDataExecutorTest.java

- Refactor export and import metadata
---

Refactor export and import metadata

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/extractor/DialectProjectionIdentifierExtractor.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/extractor/ProjectionIdentifierExtractEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/extractor/dialect/OpenGaussProjectionIdentifierExtractor.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/extractor/dialect/OracleProjectionIdentifierExtractor.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/extractor/dialect/PostgreSQLProjectionIdentifierExtractor.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/ExpressionProjection.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/util/SubqueryTableBindUtils.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/extractor/ProjectionIdentifierExtractEngineTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/extractor/dialect/OpenGaussProjectionIdentifierExtractorTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/extractor/dialect/OracleProjectionIdentifierExtractorTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/extractor/dialect/PostgreSQLProjectionIdentifierExtractorTest.java

Support extracting column name from function for postgresql

---

RELEASE-NOTES.md
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/ColumnSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/projection/ProjectionsSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/projection/type/ColumnProjectionSegmentBinder.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/driver/jdbc/JDBCExecutorCallback.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/DriverExecutionPrepareEngine.java
proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandlerTest.java
proxy/frontend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/command/query/extended/bind/OpenGaussComBatchBindExecutorTest.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLAggregatedBatchedStatementsCommandExecutorTest.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutorTest.java
test/it/binder/src/test/resources/cases/dml/select.xml
test/it/binder/src/test/resources/sqls/dml/select.xml

Ref #34029.
- Support sql bind for select with current select projection reference
---

Support sql bind for select with current select projection reference

---

agent/plugins/metrics/type/prometheus/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/prometheus/PrometheusPluginLifecycleServiceTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/cache/checker/ShardingRouteCacheableCheckerTest.java
infra/common/src/main/java/org/apache/shardingsphere/infra/instance/ComputeNodeInstanceContext.java
infra/common/src/test/java/org/apache/shardingsphere/infra/instance/ComputeNodeInstanceContextTest.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/preparer/MigrationJobPreparer.java
mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java
mode/core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java
mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/ClusterContextManagerBuilder.java
mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneContextManagerBuilder.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManager.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/LockClusterExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/UnlockClusterExecutor.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/ProxyDatabaseConnectionManagerTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/ProxySQLExecutorTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/context/ProxyContextTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/admin/DatabaseAdminQueryBackendHandlerTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/DistSQLQueryBackendHandlerTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ExportMetaDataExecutorTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportMetaDataExecutorTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableExecutorTest.java
proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/protocol/FrontDatabaseProtocolTypeFactoryTest.java
proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/state/impl/OKProxyStateTest.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/PostgreSQLCommandExecuteEngineTest.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/util/PipelineContextUtils.java

Reverts apache/shardingsphere#34186

Revert "Move ComputeNodeInstanceContext.LockContext to ContextManager"

---

RELEASE-NOTES.md
mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/JDBCRepository.java

- Support modifying Hikari-CP configurations via props in standalone mode
---

Support modifying Hikari-CP configurations via props in standalone mode

---

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/RefreshTableMetaDataExecutor.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/DistSQLUpdateBackendHandlerTest.java

- check storage unit, schema and table when refresh table metadata
- add unit test cases

Optimize param check in refresh table meta data executor

---

RELEASE-NOTES.md
infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/database/OpenGaussDatabaseMetaData.java
infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/database/PostgreSQLDatabaseMetaData.java

- Support postgresql and opengauss CHARACTER VARYING type metadata load
---

Support postgresql and opengauss CHARACTER VARYING type metadata load

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/context/EncryptSQLRewriteContextDecorator.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/context/EncryptSQLRewriteContextDecoratorTest.java

- Minor refactor for EncryptSQLRewriteContextDecorator
---

Minor refactor for EncryptSQLRewriteContextDecorator

---

RELEASE-NOTES.md
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dal/filter/ShowFilterSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dal/ShowColumnsStatementBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dal/ShowCreateTableStatementBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dal/ShowIndexStatementBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/type/DALStatementBindEngine.java
test/it/binder/src/test/resources/cases/dal/show-columns.xml
test/it/binder/src/test/resources/cases/dal/show-create-table.xml
test/it/binder/src/test/resources/cases/dal/show-index.xml
test/it/binder/src/test/resources/sqls/dal/show-columns.xml
test/it/binder/src/test/resources/sqls/dal/show-create-table.xml
test/it/binder/src/test/resources/sqls/dal/show-index.xml
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dal/impl/ShowCreateTableStatementAssert.java

Ref #34029.
- Support show create table, show columns, show index statement bind
---

Support show create table, show columns, show index statement bind

---

RELEASE-NOTES.md
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGenerator.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/checker/sql/ddl/ShardingAlterViewSupportedCheckerTest.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/SQLStatementContextFactory.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/ddl/AlterViewStatementContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/ddl/CreateViewStatementContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/from/type/SimpleTableSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/CreateViewStatementBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/statement/ddl/AlterViewStatementContextTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/statement/ddl/CreateViewStatementContextTest.java
parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/type/DorisDDLStatementVisitor.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java
parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/type/OpenGaussDDLStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/type/PostgreSQLDDLStatementVisitor.java
parser/sql/dialect/presto/src/main/java/org/apache/shardingsphere/sql/parser/presto/visitor/statement/type/PrestoDDLStatementVisitor.java
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/type/SQLServerDDLStatementVisitor.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/enums/SubqueryType.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/ddl/CreateViewStatement.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/ddl/DropViewStatement.java
parser/sql/statement/type/mysql/src/main/java/org/apache/shardingsphere/sql/parser/statement/mysql/ddl/MySQLDropViewStatement.java

- Enhance create view, alter view, drop view sql parser
---

Enhance create view, alter view, drop view sql parser

---

test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/deadlock/TransactionDeadlockTestCase.java

Fix transaction deadlock assertion in different mysql versions

---

parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/type/DorisDDLStatementVisitor.java
parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/type/OpenGaussDDLStatementVisitor.java
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/type/PostgreSQLDDLStatementVisitor.java
parser/sql/dialect/presto/src/main/java/org/apache/shardingsphere/sql/parser/presto/visitor/statement/type/PrestoDDLStatementVisitor.java
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/type/SQLServerDDLStatementVisitor.java
parser/sql/statement/type/doris/src/main/java/org/apache/shardingsphere/sql/parser/statement/doris/ddl/DorisDropViewStatement.java
parser/sql/statement/type/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/statement/opengauss/ddl/OpenGaussDropViewStatement.java
parser/sql/statement/type/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/statement/postgresql/ddl/PostgreSQLDropViewStatement.java
parser/sql/statement/type/presto/src/main/java/org/apache/shardingsphere/sql/parser/statement/presto/ddl/PrestoDropViewStatement.java
parser/sql/statement/type/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/statement/sqlserver/ddl/SQLServerDropViewStatement.java

- Minor refactor for view statement
---

Minor refactor for view statement

---

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/cases/value/SQLValue.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/BaseDMLE2EIT.java

Add clob data type for E2E assertion

---

infra/reachability-metadata/src/main/resources/META-INF/native-image/com.github.docker-java/docker-java-api/3.4.0/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/modes/cluster/EtcdTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/modes/cluster/ZookeeperTest.java

Fixes https://github.com/apache/shardingsphere/actions/runs/12690522092/job/35371566763 .
- Fix NativeTest failure due to class changes. Also for #29052 .
- For cluster mode nativeTest, it has been changed to pause for 5 seconds immediately after executing `CREATE TABLE`, and then execute `TRUNCATE TABLE`. I reproduced the instability of CI on a local device.
---

Fix NativeTest failure due to class changes

---

proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java

Fixes #34287.
Add judgment logic,determine whether the number of parameters is greater than the number of inserted fields
-
---

Fix issue:Add parameter index judgment logic in MySQLComStmtPrepareExecutor

---

kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/query/ShowUnloadedSingleTablesExecutor.java

Keep the original table name case when showing unloaded single tables

---

RELEASE-NOTES.md
infra/database/type/firebird/pom.xml
infra/database/type/firebird/src/main/java/org/apache/shardingsphere/infra/database/firebird/connector/FirebirdConnectionPropertiesParser.java
infra/database/type/firebird/src/test/java/org/apache/shardingsphere/infra/database/firebird/connector/FirebirdConnectionPropertiesParserTest.java
pom.xml

For #29052.
- Support connecting to Firebird via jdbcUrl containing the absolute path to fdb. The current PR was split from #34307 to facilitate review.
- This is due to #33773 which does not support resolving jdbcUrls like `jdbc:firebird://localhost:32783//var/lib/firebird/data/demo_ds_2.fdb`.
- The current PR is affected by multiple external issues.
- Done discussion around LICENSE for `org.firebirdsql.jdbc:jaybird:5.0.6.java8` not being distributed under the ASF license at https://github.com/apache/gravitino/issues/4352#issuecomment-2453295083 .
- Due to the change of the minimum supported JDK version to JDK17 as reported by https://firebirdsql.org/en/news/jaybird-6-0-0-released , it is not possible to use `org.firebirdsql.jdbc:jaybird:6.0.0` in …

Support connecting to Firebird via jdbcUrl containing the absolute path to fdb

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/condition/EncryptConditionEngine.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/context/EncryptSQLRewriteContextDecorator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptPredicateParameterRewriter.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/EncryptTokenGenerateBuilder.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptInsertPredicateValueTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateColumnTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateValueTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptPredicateEqualRightValueToken.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptMergedResultTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/EncryptTokenGenerateBuilderTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateValueTokenGeneratorTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/ShardingProjectionsTokenGeneratorTest.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/extractor/SQLStatementContextExtractor.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/engine/ProjectionEngine.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/AggregationDistinctProjection.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/AggregationProjection.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/ddl/AlterViewStatementContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/ddl/CreateViewStatementContext.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/ExpressionSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/type/AggregationDistinctProjectionSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/type/AggregationProjectionSegmentBinder.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/ProjectionsContextTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/AggregationDistinctProjectionTest.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/AggregationProjectionTest.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/extractor/ColumnExtractor.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dql/GeneralDQLE2EIT.java

- Refactor sql bind and encrypt logic
---

Refactor sql bind and encrypt logic

---

RELEASE-NOTES.md
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/loader/type/SchemaMetaDataLoader.java
infra/database/type/mysql/src/test/java/org/apache/shardingsphere/infra/database/mysql/metadata/data/loader/MySQLSchemaMetaDataLoaderTest.java
infra/database/type/opengauss/src/test/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussSchemaMetaDataLoaderTest.java
infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLSchemaMetaDataLoaderTest.java
kernel/single/core/src/test/java/org/apache/shardingsphere/single/datanode/SingleTableDataNodeLoaderTest.java
kernel/single/core/src/test/java/org/apache/shardingsphere/single/rule/SingleRuleTest.java

Add support for partition tables in Postgresql

---

agent/plugins/logging/type/file/src/main/java/org/apache/shardingsphere/agent/plugin/logging/file/advice/MetaDataContextsFactoryAdvice.java
agent/plugins/logging/type/file/src/main/resources/META-INF/conf/file-advisors.yaml

Fix agent file error

---

parser/distsql/engine/src/main/antlr4/imports/RALStatement.g4

The `*` is in the wrong position

Fix g4 syntax for DistSQL show table metadata

---

kernel/transaction/type/xa/core/pom.xml
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/connection/dialect/FirebirdXAConnectionWrapper.java
kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/datasource/properties/dialect/FirebirdXADataSourceDefinition.java
kernel/transaction/type/xa/core/src/main/resources/META-INF/services/org.apache.shardingsphere.transaction.xa.jta.connection.XAConnectionWrapper
kernel/transaction/type/xa/core/src/main/resources/META-INF/services/org.apache.shardingsphere.transaction.xa.jta.datasource.properties.XADataSourceDefinition
kernel/transaction/type/xa/core/src/test/java/org/apache/shardingsphere/transaction/xa/fixture/DataSourceUtils.java
kernel/transaction/type/xa/core/src/test/java/org/apache/shardingsphere/transaction/xa/jta/connection/dialect/FirebirdXAConnectionWrapperTest.java
kernel/transaction/type/xa/core/src/test/java/org/apache/shardingsphere/transaction/xa/jta/datasource/properties/dialect/FirebirdXADataSourceDefinitionTest.java

- Added FirebirdXADataSourceDefinition 
- Added FirebirdXAConnectionWrapper
---

Implement Firebird XA transaction support

---

RELEASE-NOTES.md
infra/database/type/presto/src/main/java/org/apache/shardingsphere/infra/database/presto/metadata/data/loader/PrestoMetaDataLoader.java
infra/database/type/presto/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.database.core.metadata.data.loader.DialectMetaDataLoader
infra/database/type/presto/src/test/java/org/apache/shardingsphere/infra/database/presto/database/PrestoDatabaseMetaDataTest.java

For #29052.
- Support for connecting to Presto's Memory Connector in ShardingSphere config.
- The current implementation does not record the table's index, primary keys, generated info, or column visibility. This obviously requires Presto to have a table like `INFORMATION_SCHEMA.INDEXES`. Presto Server's implementation of `INFORMATION_SCHEMA.COLUMNS` is also not perfect.
- This PR was split from #34429 for easier review.
---

Support for connecting to Presto's Memory Connector in ShardingSphere config

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/context/EncryptSQLRewriteContextDecorator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/EncryptParameterRewritersRegistry.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/EncryptTokenGenerateBuilder.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/parameter/EncryptParameterRewritersRegistryTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/EncryptTokenGenerateBuilderTest.java
mode/type/standalone/core/src/test/java/org/apache/shardingsphere/mode/manager/standalone/persist/service/StandaloneMetaDataManagerPersistServiceTest.java

- Minor refactor EncryptSQLRewriteContextDecorator
---

Minor refactor EncryptSQLRewriteContextDecorator

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/condition/EncryptConditionEngine.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/complex/ShardingComplexRouteEngine.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/strategy/type/complex/ComplexShardingStrategy.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/strategy/type/hint/HintShardingStrategy.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/strategy/type/standard/StandardShardingStrategy.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingTable.java
kernel/single/core/src/main/java/org/apache/shardingsphere/single/util/SingleTableLoadUtils.java
proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussAdminExecutorCreator.java

- Use CaseInsensitiveSet to replace TreeSet<>(String.CASE_INSENSITIVE_ORDER)
---

Use CaseInsensitiveSet to replace TreeSet<>(String.CASE_INSENSITIVE_ORDER)

---

RELEASE-NOTES.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/proxy-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManager.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/transactions/base/SeataTest.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/proxy/transactions/base/SeataTest.java

Fixes #33831.
- Alleviate connection leaks caused by Seata Client throwing exceptions. The real connection leak bug occurs inside Seata Client `2.2.0`. The related bug was first reproduced in the CI environment of https://github.com/apache/shardingsphere/pull/34307#pullrequestreview-2545454034 .
- Also fixes #34418 .
- Fix https://github.com/apache/shardingsphere/actions/runs/12929853521/job/36060093185 . Fix nativeTest failing due to class changes. Also for #29052 .
- After closing HikariCP DataSource, Seata Client's nativeTest will repeatedly throw exceptions due to an undocumented bug in Seata Client. At this time, the error handling of `ShardingSphere DriverDatabaseConnectionManager` is superimposed, resulting in a connection leak bug in other …

Alleviate connection leaks caused by Seata Client throwing exceptions

---

RELEASE-NOTES.md
distribution/proxy/src/main/release-docs/LICENSE
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
pom.xml
test/native/pom.xml

Fixes #34414.
- Bump Zookeeper Client to 3.9.3.
- Actively mark the impact of https://github.com/apache/incubator-seata/issues/7045 and https://github.com/testcontainers/testcontainers-java/issues/8338 in POM to resolve dependency conflict warnings.
- Parts not relevant to this PR have been split into #34463 .
---

Bump Zookeeper Client to 3.9.3

---

parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java
parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java
parser/sql/statement/type/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/statement/opengauss/dml/OpenGaussInsertStatement.java
parser/sql/statement/type/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/statement/postgresql/dml/PostgreSQLInsertStatement.java

Fixes [34424](https://github.com/apache/shardingsphere/issues/34424)
-
---

Fix set OnDuplicateKeyColumnsSegment on PostgreSQLInsertStatement

---

features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingTableRuleExecutorTest.java
features/sharding/distsql/handler/src/test/resources/cases/show-sharding-table-rules-current-config.yaml
features/sharding/distsql/handler/src/test/resources/cases/show-sharding-table-rules.xml

For #33142.
- Use `DistSQLDatabaseRuleQueryExecutorAssert` in `ShowShardingTableRuleExecutorTest`
---

Use DistSQLDatabaseRuleQueryExecutorAssert in ShowShardingTableRuleExecutorTest

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertCipherNameTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertDerivedColumnsTokenGenerator.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertDerivedColumnsTokenGeneratorTest.java

- Minor refactor for encrypt insert token generator
---

Minor refactor for encrypt insert token generator

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateColumnTokenGenerator.java
mode/core/src/test/java/org/apache/shardingsphere/mode/metadata/persist/metadata/ViewMetaDataPersistServiceTest.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/extractor/ColumnExtractor.java

- Minor refactor for EncryptPredicateColumnTokenGenerator
---

Minor refactor for EncryptPredicateColumnTokenGenerator

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/with/CommonTableExpressionSegmentBinder.java
test/it/binder/src/test/resources/cases/dml/select.xml

- Remove wrong owner set for CommonTableExpressionSegmentBinder
---

Remove wrong owner set for CommonTableExpressionSegmentBinder

---

RELEASE-NOTES.md
parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select-special-function.xml
test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml

- Support MySQL SELECT CAST AS YEAR statement parse
---

Support MySQL SELECT CAST AS YEAR statement parse

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/IncrementalTaskAckCallback.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/task/runner/TransmissionTasksRunner.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/task/IncrementalTaskAckCallbackTest.java

- Improve pipeline job progress incremental latestActiveTimeMillis persistence
---

Improve pipeline job progress incremental latestActiveTimeMillis persistence

---

infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/rdl/resource/AlterStorageUnitExecutor.java

- Optimize connection properties comparison in AlterStorageUnitExecutor
---

Optimize connection properties comparison in AlterStorageUnitExecutor

---

RELEASE-NOTES.md
parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

- Fix mysql sql parser error when sql contains implicit concat expression
---

Fix mysql sql parser error when sql contains implicit concat expression

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/sink/type/PipelineDataSourceSink.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/group/DataRecordGroupEngine.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/group/DataRecordGroupEngineTest.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/preparer/MigrationJobPreparer.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/primarykey/IndexesMigrationE2EIT.java

Related to #29664
- Recover value of migration incremental importer batch size
- Compatible with table without unique key migration. Several previous refactor caused a bug
---

Recover value of migration incremental importer batch size

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Support SQL parsing of Oracle comparison operators containing spaces

---

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

Support SQL parsing of Oracle not equals operators containing spaces

---

RELEASE-NOTES.md
parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
parser/sql/statement/type/mysql/src/main/java/org/apache/shardingsphere/sql/parser/statement/mysql/dml/MySQLDeleteStatement.java
test/it/parser/src/main/resources/case/dml/delete.xml
test/it/parser/src/main/resources/sql/supported/dml/delete.xml

-
Added Support for With Segment In Delete Statement of MySQL.
---

Support With Clause in Delete Statement in MySQL.

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/type/ColumnSegmentBinder.java
infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/util/SubqueryTableBindUtils.java

- Remove comment in ColumnSegmentBinder and SubqueryTableBindUtils
---

Remove comment in ColumnSegmentBinder and SubqueryTableBindUtils

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/enums/EncryptDerivedColumnSuffix.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateColumnTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGenerator.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateColumnTokenGeneratorTest.java
test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-subquery.xml
test/it/rewriter/src/test/resources/scenario/mix/case/query-with-cipher/dml/select/select-subquery.xml

- Simplify EncryptDerivedColumnSuffix to avoid identifier too long
---

Simplify EncryptDerivedColumnSuffix to avoid identifier too long

---

docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
infra/expr/type/espresso/src/test/java/org/apache/shardingsphere/infra/expr/espresso/EspressoInlineExpressionParserTest.java
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/jni-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/proxy-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
pom.xml
test/native/src/test/resources/test-native/yaml/jdbc/databases/hive/acid.yaml
test/native/src/test/resources/test-native/yaml/jdbc/databases/hive/iceberg.yaml
test/native/src/test/resources/test-native/yaml/jdbc/databases/hive/standalone-hms.yaml
test/native/src/test/resources/test-native/yaml/jdbc/databases/hive/zsd.yaml

Fixes https://github.com/apache/shardingsphere/actions/runs/13765475376 .
- Fix nativeTest failing due to class changes.
- Bump GraalVM Native Build Tools to `0.10.5`.
- Bump GraalVM SDK for `org.apache.shardingsphere:shardingsphere-infra-expr-espresso` to `24.1.2`.
- Another particular issue is that HiveServer2's insert efficiency is particularly slow after https://github.com/apache/shardingsphere/issues/34816 was fixed, resulting in the need to set `max-tolerate-time-difference-milliseconds`. This problem does not occur on mysql, postgres, clickhouse, h2database, firebird, opengauss and ms sql server. Maybe something happened inside hiveserver2 .
```shell
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 53.07 s <<< FAILURE! …
```

Fix nativeTest failing due to class changes

---

RELEASE-NOTES.md
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AdaptedDatabaseMetaData.java
jdbc/src/test/java/org/apache/shardingsphere/driver/jdbc/core/datasource/metadata/ShardingSphereDatabaseMetaDataTest.java

- Fix wrong jdbc database metadata pass through logic
---

Fix wrong jdbc database metadata pass through logic

---

proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLAdminExecutorCreator.java
proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLInformationSchemaExecutorFactory.java
proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLMySQLSchemaExecutorFactory.java
proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLPerformanceSchemaExecutorFactory.java
proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLSysSchemaExecutorFactory.java
proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLAdminExecutorCreatorTest.java

- Optimize mysql admin executor creator
---

Optimize mysql admin executor creator

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/comparator/EncryptorComparator.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContextTest.java

- Remove useless EncryptorComparator import
---

Remove useless EncryptorComparator import

---

jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/DriverExecuteExecutor.java
jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/facade/DriverExecutorFacade.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngineFactory.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/impl/StandardSQLFederationEngine.java
kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/engine/StandardSQLFederationEngineTest.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxySQLExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/StandardDatabaseConnector.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/PreviewExecutor.java
proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussSystemCatalogAdminQueryExecutor.java

- Add SQLFederationEngine interface to standardize sql federation query engine calls
---

Add SQLFederationEngine interface to standardize sql federation query engine calls

---

features/sharding/distsql/statement/src/main/java/org/apache/shardingsphere/sharding/distsql/segment/table/TableRuleSegment.java

-
Made changes in the name of the parameter from `dataSourcesNote` to `dataSourcesNodes`
---

Minor refactor in TableRuleSegment's constructor parameter.

---

RELEASE-NOTES.md
features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/InUsedReadwriteSplittingStorageUnitRetriever.java
features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/InUsedReadwriteSplittingStorageUnitRetrieverTest.java

Fix duplicate result when show rules used storage unit with readwrite-splitting rule

---

test/e2e/sql/src/test/resources/cases/dql/cases/db_tbl_sql_federation/e2e-dql-select-for-db-tbl-sql-federation.xml

- Modify sql federation e2e test to add order in subquery
---

Modify sql federation e2e test to add order in subquery

---

distribution/proxy/src/main/release-docs/LICENSE
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/testcontainers/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/testcontainers/_index.en.md
docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/seata-at/_index.cn.md
docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/seata-at/_index.en.md
examples/pom.xml
pom.xml

Fixes #23499 Fixes #23597
-
Update the PostgreSQL version in the pom.xml file to ensure that ShardingSphere-Proxy supports the conversion of numeric infinity to BigDecimal.
For Example previously PostgreSQL query like - 
`Select 'infinity'::numeric` were not supported.
But now it works fine.
---

Update PostgreSQL version for ShardingSphere-Proxy to support BigDecimal with infinity

---

agent/core/src/main/java/org/apache/shardingsphere/agent/core/advisor/config/AdvisorConfigurationLoader.java

- Fix error that AdvisorConfigurationLoader cannot read the configuration file in the window environment
---

Fix error that AdvisorConfigurationLoader cannot read the configuration file in the window environment

---

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/ColumnProjection.java
infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/ColumnProjectionTest.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/DialectDatabaseMetaData.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/option/column/DialectColumnOption.java
infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/metadata/database/MySQLDatabaseMetaData.java

- Refactor ColumnProjection to remove instance of MySQLDatabaseType
---

Refactor ColumnProjection to remove instance of MySQLDatabaseType

---

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/ClusterExportMetaDataGenerator.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/export/ExportMetaDataExecutorTest.java

- Optimize properties data export in ClusterExportMetaDataGenerator
---

Optimize properties data export in ClusterExportMetaDataGenerator

---

RELEASE-NOTES.md
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/DriverExecutionPrepareEngine.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/ExecutorStatementManager.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/SQLExecutionUnitBuilder.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/jdbc/builder/PreparedStatementExecutionUnitBuilder.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/jdbc/builder/StatementExecutionUnitBuilder.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/StatementManager.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/processor/SQLFederationProcessor.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/processor/impl/StandardSQLFederationProcessor.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/schema/SQLFederationTable.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/statement/JDBCBackendStatement.java
proxy/frontend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/command/query/extended/bind/OpenGaussComBatchBindExecutorTest.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLAggregatedBatchedStatementsCommandExecutorTest.java
proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutorTest.java

Fixes #33363.
- Fix Operation not allowed after ResultSet closed exception when use sql federation
---

Fix Operation not allowed after ResultSet closed exception when use sql federation

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/DataMatchTableDataConsistencyChecker.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/MatchingTableInventoryChecker.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/TableInventoryChecker.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/DataMatchTableInventoryCheckerTest.java
kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/check/consistency/MigrationDataConsistencyChecker.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/scenario/migration/check/consistency/MigrationDataConsistencyCheckerTest.java

- Improve data consistency check table without unique key with DATA_MATCH
---

Improve data consistency check table without unique key with DATA_MATCH

---

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/loader/type/SchemaMetaDataLoader.java

- Extract DialectSchemaOption to a separate variable for better readability
- Simplify the condition to check for default schema presence

refactor(infra): optimize schema names loading logic

---

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/loader/type/SchemaMetaDataLoader.java
infra/database/type/mysql/src/test/java/org/apache/shardingsphere/infra/database/mysql/metadata/data/loader/MySQLSchemaMetaDataLoaderTest.java
infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussMetaDataLoader.java
infra/database/type/opengauss/src/test/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussSchemaMetaDataLoaderTest.java
infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLMetaDataLoader.java
infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLSchemaMetaDataLoaderTest.java
kernel/single/core/src/main/java/org/apache/shardingsphere/single/datanode/SingleTableDataNodeLoader.java

- Remove static methods and make SchemaMetaDataLoader a utility class
- Update related test cases to use the new utility class
- Modify OpenGaussMetaDataLoader and PostgreSQLMetaDataLoader to use the new utility class- Update SingleTableDataNodeLoader to use the new utility class

refactor(metadata): turn SchemaMetaDataLoader into a utility class

---

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/option/datatype/DefaultDataTypeOption.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/option/datatype/DialectDataTypeOption.java
infra/database/core/src/test/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/option/datatype/DefaultDataTypeOptionTest.java
infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/metadata/database/option/MySQLDataTypeOption.java
infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/database/option/OpenGaussDataTypeOption.java
infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/database/option/OracleDataTypeOption.java
infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/database/option/PostgreSQLDataTypeOption.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/preparer/inventory/splitter/InventoryDumperContextSplitter.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineJdbcUtilsTest.java
kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/incremental/binlog/data/binary/MySQLBinlogBinaryStringHandler.java

- Remove integer, string, and binary column type checks from PipelineJdbcUtils
- Add corresponding methods to DialectDataTypeOption interface
- Implement these methods in DefaultDataTypeOption and database-specific classes
- Update InventoryDumperContextSplitter and MySQLBinlogBinaryStringHandler to use new methods- Remove redundant tests from PipelineJdbcUtilsTest

Remove PipelineJdbcUtils and use DialectDataTypeOption instead

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/util/PipelineJdbcUtils.java

- Remove isIntegerColumn, isStringColumn, and isBinaryColumn methods
- These methods were not being used in the codebase
- Simplifies the PipelineJdbcUtils class

Remove unused column type check methods

---

infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/metadata/database/option/MySQLDataTypeOption.java
infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/database/option/OpenGaussDataTypeOption.java
infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/database/option/OracleDataTypeOption.java
infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/database/option/PostgreSQLDataTypeOption.java

- Renamed dataTypeOption to delegate in MySQLDataTypeOption, OpenGaussDataTypeOption, OracleDataTypeOption, and PostgreSQLDataTypeOption classes
- Updated method calls to use the new delegate variable
- This change improves code readability and consistency across database type implementations

Rename dataTypeOption to delegate in DataTypeOption classes

---

infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/metadata/database/option/MySQLDataTypeOption.java
infra/database/type/opengauss/pom.xml
infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/database/option/OpenGaussDataTypeOption.java
infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/database/option/OracleDataTypeOption.java
infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/database/option/PostgreSQLDataTypeOption.java

- MySQLDataTypeOption: Use a static final map for extra data types
- OpenGaussDataTypeOption: Delegate to PostgreSQLDataTypeOption
- OracleDataTypeOption: Use a static final map for extra data types
- PostgreSQLDataTypeOption: Use a static final map for extra data types

Optimize data type option implementations

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/enums/EncryptDerivedColumnSuffix.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/loader/type/TableMetaDataLoader.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/DialectDatabaseMetaData.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/option/IdentifierNamePatternType.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/type/DatabaseTypeRegistry.java
infra/database/type/firebird/src/main/java/org/apache/shardingsphere/infra/database/firebird/metadata/database/FirebirdDatabaseMetaData.java
infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/database/OpenGaussDatabaseMetaData.java
infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/database/OracleDatabaseMetaData.java
infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/database/PostgreSQLDatabaseMetaData.java
mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/util/TableRefreshUtils.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/env/DataSetEnvironmentManager.java

- Rename TableNamePatternType to IdentifierNamePatternType
- Update related methods and classes to use the new IdentifierNamePatternType
- Modify the formatTableNamePattern method to formatIdentifierPattern

Rename table name pattern to identifier pattern

---

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/DialectDatabaseMetaData.java
infra/database/core/src/test/java/org/apache/shardingsphere/infra/database/core/metadata/database/fixture/BranchDialectDatabaseMetaData.java
infra/database/core/src/test/java/org/apache/shardingsphere/infra/database/core/metadata/database/fixture/TrunkDialectDatabaseMetaData.java
infra/database/type/clickhouse/src/main/java/org/apache/shardingsphere/infra/database/clickhouse/metadata/database/ClickHouseDatabaseMetaData.java
infra/database/type/firebird/src/main/java/org/apache/shardingsphere/infra/database/firebird/metadata/database/FirebirdDatabaseMetaData.java
infra/database/type/h2/src/main/java/org/apache/shardingsphere/infra/database/h2/metadata/database/H2DatabaseMetaData.java
infra/database/type/hive/src/main/java/org/apache/shardingsphere/infra/database/hive/metadata/database/HiveDatabaseMetaData.java
infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/metadata/database/MySQLDatabaseMetaData.java
infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/database/OpenGaussDatabaseMetaData.java
infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/database/OracleDatabaseMetaData.java
infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/database/PostgreSQLDatabaseMetaData.java
infra/database/type/presto/src/main/java/org/apache/shardingsphere/infra/database/presto/metadata/database/PrestoDatabaseMetaData.java
infra/database/type/sql92/src/main/java/org/apache/shardingsphere/infra/database/sql92/metadata/database/SQL92DatabaseMetaData.java
infra/database/type/sqlserver/src/main/java/org/apache/shardingsphere/infra/database/sqlserver/metadata/database/SQLServerDatabaseMetaData.java
test/fixture/database/src/main/java/org/apache/shardingsphere/test/fixture/database/DialectDatabaseMetaDataFixture.java

- Move getIdentifierPatternType method from DialectDatabaseMetaData to individual database metadata classes
- Update ClickHouse, Firebird, H2, Hive, MySQL, OpenGauss, Oracle, PostgreSQL, Presto, SQL92, and SQLServer database metadata classes
- Remove default implementation from DialectDatabaseMetaData

Move getIdentifierPatternType method

---

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/DialectDatabaseMetaData.java
infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/database/OpenGaussDatabaseMetaData.java

- Move getSchemaOption method to a more appropriate position in the DialectDatabaseMetaData class
- Update the implementation of getSchemaOption in OpenGaussDatabaseMetaData class

Reorganize schema option method in database metadata

---

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/option/schema/DefaultSchemaOption.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/option/schema/DialectSchemaOption.java
infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/database/option/OpenGaussSchemaOption.java
infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/database/option/OracleSchemaOption.java
infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/database/option/PostgreSQLSchemaOption.java

- Move default system schema logic from OpenGaussSchemaOption to PostgreSQLSchemaOption
- Update OpenGaussSchemaOption to delegate schema-related methods to PostgreSQLSchemaOption
- Modify OracleSchemaOption to use DefaultSchemaOption for default schema logic
- Refactor DefaultSchemaOption to implement default system schema method
- Adjust DialectSchemaOption interface to make default system schema method non-default

Abstract default system schema logic

---

features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/rule/builder/BroadcastRuleBuilderTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/builder/EncryptRuleBuilderTest.java
features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/rule/builder/ReadwriteSplittingRuleBuilderTest.java
infra/database/type/opengauss/src/test/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussMetaDataLoaderTest.java
mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/persist/service/ClusterMetaDataManagerPersistServiceTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/variable/SetDistVariableExecutorTest.java

- Remove getDialectTableMetaDataLoader() method
- Directly use TypedSPILoader and DatabaseTypedSPILoader services
- Add databaseType and dialectMetaDataLoader as test class fields
- Update test methods to use the new approach
- Add JDBCResourceOpenedButNotSafelyClosed annotation to relevant tests

Remove redundant method and optimize test structure

---

features/broadcast/core/src/test/java/org/apache/shardingsphere/broadcast/rule/builder/BroadcastRuleBuilderTest.java
features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/builder/EncryptRuleBuilderTest.java
features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/rule/builder/ReadwriteSplittingRuleBuilderTest.java
infra/database/type/opengauss/src/test/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussMetaDataLoaderTest.java
mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/persist/service/ClusterMetaDataManagerPersistServiceTest.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/variable/SetDistVariableExecutorTest.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/OpenGaussContainer.java

- Replace specific OpenGaussDatabaseType checks with a generic getDatabaseType() method
- Improve code readability and maintainability by removing class type comparisons

Generalize OpenGaussContainer database type checking

---

infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLMetaDataLoaderTest.java

- Remove direct usage of PostgreSQLDatabaseType
- Use TypedSPILoader to get DatabaseType instance for PostgreSQL
- Update test methods to use the new DatabaseType instance
- Add JDBCResourceOpenedButNotSafelyClosed suppression to relevant test methods

Refactor PostgreSQLMetaDataLoaderTest to use DatabaseType

---

proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PortalTest.java

- Replace direct usage of PostgreSQLDatabaseType with a more generic DatabaseType
- Use TypedSPILoader.getService to get the PostgreSQL DatabaseType instance
- Update mockDatabase method to use the new DatabaseType instance
- Adjust unit tests to use the new DatabaseType instance

refactor(postgresql): Remove redundant PostgreSQLDatabaseType usage

---

infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/engine/RowNumberPaginationContextEngineTest.java

- Remove multiple instances of new OracleDatabaseType() in test cases
- Use TypedSPILoader.getService(DatabaseType.class, "Oracle") to get DatabaseType instance
- Update test methods to use the shared DatabaseType instance
- Improve code readability and maintainability by reducing redundancy

Replace new OracleDatabaseType() with TypedSPILoader in RowNumberPaginationContextEngineTest

---

infra/database/type/oracle/src/test/java/org/apache/shardingsphere/infra/database/oracle/metadata/data/loader/OracleMetaDataLoaderTest.java

- Replace multiple OracleDatabaseType instances with a single TypedSPILoader
- Update test methods to use the shared DatabaseType instance
- Add @SuppressWarnings("JDBCResourceOpenedButNotSafelyClosed") annotation to test methods

Remove redundant OracleDatabaseType instantiation

---

test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/container/compose/DockerContainerComposer.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/container/compose/NativeContainerComposer.java

- Remove unused import of OracleDatabaseType
- Simplify Oracle-specific logic in DockerContainerComposer and NativeContainerComposer
- Use string comparison instead of instance check for Oracle database type
- Refactor PipelineContainerComposer to use DatabaseTypeRegistry for identifier formatting

Optimize Oracle database handling in container composers

---

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/fixture/ShardingRouteEngineFixtureBuilder.java
infra/database/type/h2/src/test/java/org/apache/shardingsphere/infra/database/h2/metadata/data/loader/H2MetaDataLoaderTest.java

- Remove direct usage of H2DatabaseType class
- Use DatabaseType interface with TypedSPILoader to get H2 database type
- Update test cases to use the new DatabaseType instance

Replace H2DatabaseType with DatabaseType in H2MetaDataLoaderTest

---

infra/database/type/mysql/src/test/java/org/apache/shardingsphere/infra/database/mysql/metadata/data/loader/MySQLMetaDataLoaderTest.java

- Replace direct MySQLDatabaseType usage with TypedSPILoader
- Add @SuppressWarnings("JDBCResourceOpenedButNotSafelyClosed") annotation for test methods
- Refactor test methods to use a class-level databaseType field

Optimize MySQLMetaDataLoaderTest and ensure resource safety

---

proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowProcessListExecutorTest.java
proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/execute/MySQLComStmtExecuteExecutorTest.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/MariaDBContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/MySQLContainer.java

- Use DatabaseType interface instead of MySQLDatabaseType implementation
- Utilize TypedSPILoader to get MySQL DatabaseType instance- Update related test classes to use the new DatabaseType reference
- This change is part of a larger effort to decouple the codebase from specific database implementations

Replace MySQLDatabaseType with DatabaseType in tests

---

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/MariaDBContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/MySQLContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/OpenGaussContainer.java

- Remove unnecessary line breaks in getDatabaseNames and getExpectedDatabaseNames methods
- Affected classes: MariaDBContainer, MySQLContainer, OpenGaussContainer

Format code in database container classes

---

RELEASE-NOTES.md
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/lock/ProcessOperationLock.java
infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/lock/ProcessOperationLockRegistry.java
infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/process/lock/ProcessOperationLockRegistryTest.java
mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/persist/service/ClusterProcessPersistService.java
mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/persist/service/ClusterProcessPersistServiceTest.java

Fixes #35299.
Change ReentrantLock to CountDownLatch and wait for all nodes to respond.
This adjustment affects both the `show processlist` and `kill query` functions.

Fix `show processlist` not wait for all nodes

---

infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/token/common/pojo/generic/SubstitutableColumnNameTokenTest.java

- Remove unnecessary mock creation for DatabaseType
- Use the existing databaseType instance variable in test cases
- Improve code readability and reduce test complexity

Replace mock(DatabaseType.class) with databaseType in test cases

---

distribution/proxy/pom.xml
docs/community/content/involved/release/shardingsphere.cn.md
docs/community/content/involved/release/shardingsphere.en.md

For #35346
- Create a new profile 'default-dep' in pom.xml for default dependencies
- Move MySQL, PostgreSQL, OpenGauss, Oracle and SQL Server parser dependencies to the new profile
- Update release instructions in both Chinese and English to include the new profile
- This change allows for more flexible dependency management and reduces the size of the default distribution

Move default dependencies to a separate profile

---

infra/database/type/hive/pom.xml
pom.xml

- Add Hive JDBC version 4.0.1 as a test dependency in pom.xml
- This change supports improved Hive integration and testing

Add Hive JDBC dependency for testing

---

kernel/data-pipeline/dialect/mysql/pom.xml
kernel/data-pipeline/dialect/opengauss/pom.xml
kernel/data-pipeline/dialect/postgresql/pom.xml

- Add shardingsphere-parser-sql dependencies for MySQL, OpenGauss and PostgreSQL dialects
- Scope the new dependencies as 'runtime' to optimize class loading

Add parser dependencies for MySQL, OpenGauss and PostgreSQL

---

db-protocol/core/pom.xml

- Removed the 'shardingsphere-infra-database-mysql' dependency from the 'db-protocol/core' module
- This dependency was only used for testing and has been removed to simplify the project structure

Remove unused MySQL dependency

---

proxy/bootstrap/pom.xml
proxy/frontend/core/pom.xml
proxy/frontend/spi/pom.xml

- Removed shardingsphere-db-protocol-core dependency from proxy-bootstrap, proxy-frontend-core, and proxy-frontend-spi modules

Remove unused shardingsphere-db-protocol-core dependency

---

proxy/frontend/core/pom.xml
proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/protocol/FrontDatabaseProtocolTypeFactoryTest.java

- Changed test case to use FIXTURE database type instead of PostgreSQL
- Removed unnecessary test dependencies for PostgreSQL and MySQL database infrastructures

Update database protocol type test to use FIXTURE instead of PostgreSQL

---

proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/protocol/FrontDatabaseProtocolTypeFactory.java
proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/protocol/FrontDatabaseProtocolTypeFactoryTest.java

- Remove static DEFAULT_FRONTEND_DATABASE_PROTOCOL_TYPE
- Use SPI to determine the default database protocol frontend engine
- Add error checking for empty SPI implementation
- Simplify code structure and improve readability

Use loaded database type in front database protocol type to replace default definition

---

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/DialectDatabaseMetaData.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/option/transaction/DialectTransactionOption.java
infra/database/type/firebird/src/main/java/org/apache/shardingsphere/infra/database/firebird/metadata/database/FirebirdDatabaseMetaData.java
infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/metadata/database/MySQLDatabaseMetaData.java
infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/database/OpenGaussDatabaseMetaData.java
infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/database/PostgreSQLDatabaseMetaData.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/tcl/SetTransactionHandler.java

- Add default isolation level to DialectTransactionOption
- Update getTransactionOption() for Firebird, MySQL, OpenGauss, and PostgreSQL
- Modify SetTransactionHandler to use default isolation level based on database type

Add default isolation level for databases

---

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/data/DatabaseBackendHandlerFactory.java

- Replace MySQLShowTablesStatement with ShowTablesStatement
- Replace MySQLShowTableStatusStatement with ShowTableStatusStatement
- Replace MySQLShowCreateTableStatement with ShowCreateTableStatement
- Update isDatabaseRequiredDALStatement to use core show statement classes

Replace MySQL-specific show statement classes with core show statement classes

---

.github/workflows/e2e-operation.yml

- Fix dorny/paths-filter error in Operation E2E
---

Fix dorny/paths-filter error in Operation E2E

---

test/e2e/operation/pipeline/pom.xml
test/e2e/operation/transaction/pom.xml

- Removed shardingsphere-proxy-frontend-core dependency from e2e operation pipeline and transaction modules
- This change simplifies the project structure and reduces redundant dependencies

Remove useless shardingsphere-proxy-frontend-core dependency

---

infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/tableless/type/unicast/TablelessDataSourceUnicastRouteEngine.java

- Use SecureRandom instead of ThreadLocalRandom for generating random numbers
- This change improves the security of the random selection process
- The performance impact is negligible for this specific use case
Fixes https://sonarcloud.io/project/security_hotspots?id=apache_shardingsphere&sinceLeakPeriod=true&tab=code

Replace ThreadLocalRandom with SecureRandom for better security

---

test/e2e/fixture/pom.xml

- Removed the shardingsphere-cluster-mode-repository-etcd dependency from the pom.xml file
- This change reduces the complexity of the project's dependencies

Remove useless Etcd dependency from e2e test fixture

---

infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/tableless/type/unicast/TablelessDataSourceUnicastRouteEngine.java

- Add @HighFrequencyInvocation annotation to TablelessDataSourceUnicastRouteEngine class
- This change helps identify the class as frequently used, potentially for performance monitoring or optimization

Add high frequency invocation annotation for tableless route engine

---

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/DialectDatabaseMetaData.java
infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/option/keygen/DialectGeneratedKeyOption.java
infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/metadata/database/MySQLDatabaseMetaData.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxySQLExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/StandardDatabaseConnector.java

- Introduce DialectGeneratedKeyOption to indicate generated key support
- Add getGeneratedKeyOption method to DialectDatabaseMetaData
- Update MySQLDatabaseMetaData to support generated keys
- Modify ProxySQLExecutor and StandardDatabaseConnector to use the new generated key option

Add generated key support check for database dialects

---

kernel/data-pipeline/distsql/handler/src/main/java/org/apache/shardingsphere/data/pipeline/distsql/handler/migration/query/ShowMigrationListExecutor.java

Related to #35053
- Fix "show migration list" getting job sharding infos failure when job is inactive
When job is inactive.
Before:
```
mysql> show migration list;
ERROR 30000 (HY000): Unknown exception.
More details: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
```
Current:
```
mysql> show migration list;
+--------------------------------------------+-------------------+--------+---------------------+---------------------+----------------+--------------------+
| id                                         | tables            | active | create_time         | stop_time           | job_item_count | job_sharding_nodes |
+--------------------------------------------+-------------------+--------+---------------------+- …
```

Fix "show migration list" getting job sharding infos failure when job is inactive

---

infra/exception/dialect/type/mysql/src/main/java/org/apache/shardingsphere/infra/exception/mysql/vendor/MySQLVendorError.java

- Update SQL state for ER_DUP_ENTRY from INTEGRITY_CONSTRAINT_VIOLATION to SYNTAX_ERROR
- Update SQL state for ER_PARSE_ERROR from INTEGRITY_CONSTRAINT_VIOLATION to SYNTAX_ERROR
- Correct error message format for ER_DUP_ENTRY
- Correct error message format for ER_PARSE_ERROR
Fixes issue which came from #35321

Correct SQL state and error message for MySQL duplicate entry errors

---

infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/engine/ProjectionsContextEngineTest.java

- Remove unnecessary setup code for SelectStatementContext
- Use TypedSPILoader to get DatabaseType instance
- Reduce test case complexity by focusing on essential parts
- Improve code readability and maintainability

Simplify test cases for ProjectionsContextEngine

---

parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/DorisStatementVisitor.java
parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDMLStatementVisitor.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
parser/sql/dialect/presto/src/main/java/org/apache/shardingsphere/sql/parser/presto/visitor/statement/type/PrestoDMLStatementVisitor.java
parser/sql/statement/type/doris/src/main/java/org/apache/shardingsphere/sql/parser/statement/doris/dml/DorisSelectStatement.java
parser/sql/statement/type/hive/src/main/java/org/apache/shardingsphere/sql/parser/statement/hive/dml/HiveSelectStatement.java
parser/sql/statement/type/mysql/src/main/java/org/apache/shardingsphere/sql/parser/statement/mysql/dml/MySQLSelectStatement.java
parser/sql/statement/type/presto/src/main/java/org/apache/shardingsphere/sql/parser/statement/presto/dml/PrestoSelectStatement.java
proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/sane/SaneQueryResultEngineTest.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/SelectStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/dml/SelectStatementTestCase.java

- Remove SimpleTableSegment from DorisSelectStatement, HiveSelectStatement, MySQLSelectStatement, and PrestoSelectStatement
- Update related test cases and assertions to remove checks for simpleTable
- This change simplifies the SelectStatement structure and reduces redundancy

Remove redundant SimpleTableSegment in SelectStatement

---

parser/sql/dialect/clickhouse/src/main/java/org/apache/shardingsphere/sql/parser/clickhouse/visitor/statement/ClickHouseStatementVisitor.java
parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/DorisStatementVisitor.java
parser/sql/dialect/firebird/src/main/java/org/apache/shardingsphere/sql/parser/firebird/visitor/statement/FirebirdStatementVisitor.java
parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/HiveStatementVisitor.java
parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java
parser/sql/dialect/presto/src/main/java/org/apache/shardingsphere/sql/parser/presto/visitor/statement/PrestoStatementVisitor.java
parser/sql/dialect/sql92/src/main/java/org/apache/shardingsphere/sql/parser/sql92/visitor/statement/SQL92StatementVisitor.java
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java

- Replace specific select statement classes with the generic SelectStatement class in subquery contexts
- Update imports to remove unused statement classes and add the SelectStatement class
- Adjust type casting in subquery-related code to use the SelectStatement class

Generalize subquery statement type

---

proxy/backend/type/postgresql/pom.xml
proxy/frontend/type/mysql/pom.xml

- Removed shardingsphere-test-fixture-database dependency from PostgreSQL and MySQL backend modules
- This change simplifies the project structure and reduces unnecessary dependencies

Remove useless test fixture database dependency

---

infra/database/type/presto/src/main/java/org/apache/shardingsphere/infra/database/presto/metadata/data/loader/PrestoMetaDataLoader.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/ITContainers.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/AdapterContainerFactory.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/impl/ShardingSphereJdbcEmbeddedContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/impl/ShardingSphereProxyEmbeddedContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/NativeStorageContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/OpenGaussContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/PostgreSQLContainer.java
test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/runtime/E2ETestEnvironment.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/container/compose/DockerContainerComposer.java
test/e2e/operation/showprocesslist/src/test/java/org/apache/shardingsphere/test/e2e/showprocesslist/container/composer/ClusterShowProcessListContainerComposer.java
test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/framework/container/compose/DockerContainerComposer.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/env/container/compose/mode/ClusterContainerComposer.java
test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/env/container/compose/mode/StandaloneContainerComposer.java
test/e2e/sql/src/test/resources/env/it-env.properties

- Support e2e sql execute proxy adapter sql in NATIVE mode
---

Support e2e sql execute proxy adapter sql in NATIVE mode

---

kernel/sql-federation/api/src/main/java/org/apache/shardingsphere/sqlfederation/config/SQLFederationCacheOption.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/rule/builder/DefaultSQLFederationRuleConfigurationBuilder.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/yaml/swapper/YamlSQLFederationExecutionPlanCacheConfigurationSwapper.java
kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/yaml/swapper/YamlSQLFederationRuleConfigurationSwapper.java
kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngineTest.java
kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/engine/fixture/rule/SQLFederationDeciderRuleMatchFixture.java
kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/engine/fixture/rule/SQLFederationDeciderRuleNotMatchFixture.java
kernel/sql-federation/core/src/test/java/org/apache/shardingsphere/sqlfederation/yaml/SQLFederationRuleConfigurationYamlIT.java
kernel/sql-federation/distsql/handler/src/main/java/org/apache/shardingsphere/sqlfederation/distsql/handler/update/AlterSQLFederationRuleExecutor.java
kernel/sql-federation/distsql/handler/src/test/java/org/apache/shardingsphere/sqlfederation/distsql/handler/update/AlterSQLFederationRuleExecutorTest.java
kernel/sql-federation/optimizer/pom.xml
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/SQLFederationCompilerEngine.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/planner/cache/ExecutionPlanCacheBuilder.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/statement/SQLStatementCompilerEngine.java
kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/statement/SQLStatementCompilerEngineFactory.java
proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussSystemCatalogAdminQueryExecutorTest.java

- Use SQLFederationCacheOption to replace CacheOption in SQLFederationRuleConfiguration
---

Use SQLFederationCacheOption to replace CacheOption in SQLFederationRuleConfiguration

---

mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/federation/FederationMetaDataRefreshEngine.java
mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/federation/FederationMetaDataRefresher.java
mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/federation/type/AlterViewFederationMetaDataRefresher.java
mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/federation/type/CreateViewFederationMetaDataRefresher.java
mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/federation/type/DropViewFederationMetaDataRefresher.java

- Add DatabaseType parameter to refresh methods in AlterView, CreateView, and DropView federated metadata refresher classes
- Update FederationMetaDataRefresher interface to include DatabaseType parameter
- Modify FederationMetaDataRefreshEngine to pass DatabaseType to refresher methods
- This change allows for more flexible and database-aware metadata refreshing in federated queries

Add databaseType parameter to federation metadata refresher methods

---

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/ddl/ShardingDDLResultMergerTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/ddl/fetch/FetchStreamMergedResultTest.java
features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowShardingTableNodesExecutor.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/tcl/SetTransactionHandler.java
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/tcl/TCLBackendHandlerFactory.java

- Remove unnecessary database type mocking from FetchStreamMergedResultTest and ShardingDDLResultMergerTest
- This change simplifies the test setup by removing redundant mock configurations

Remove redundant database type mocks

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/generator/PipelineDDLDecorator.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/preparer/datasource/PipelineJobDataSourcePreparer.java

- Remove parserDatabaseType parameter from PipelineDDLDecorator methods
- Update method signatures and internal logic to use databaseType instead
- Simplify code by reducing the number of parameters passed around

Remove unused parserDatabaseType parameter

---

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/ShardingResultMergerEngineTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/common/IteratorStreamMergedResultTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/ddl/ShardingDDLResultMergerTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/ShardingDQLResultMergerTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByMemoryMergedResultTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByRowComparatorTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByStreamMergedResultTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/orderby/OrderByStreamMergedResultTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/orderby/OrderByValueTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/pagination/LimitDecoratorMergedResultTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/pagination/RowNumberDecoratorMergedResultTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/pagination/TopAndRowNumberDecoratorMergedResultTest.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/ShardingRemoveTokenGeneratorTest.java
infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/SQLStatementContextFactory.java
infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/ddl/AlterViewStatementContext.java
infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/ddl/CreateViewStatementContext.java
infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/ddl/CursorStatementContext.java
infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/InsertStatementContext.java
infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContext.java
infra/binder/core/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/PaginationContextTest.java
infra/binder/core/src/test/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContextTest.java
proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussSystemCatalogAdminQueryExecutorTest.java

- Reorder parameters to improve readability and consistency across usage
- Update related test cases and classes to reflect the new constructor signature
- Adjust subquery context creation to match the new parameter order

Rearrange SelectStatementContext constructor parameters

---

docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/development/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/development/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/clickhouse/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/clickhouse/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/hiveserver2/_index.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/com.github.docker-java/docker-java-api/3.4.0/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.junit.jupiter/junit-jupiter/5.11.1/reflect-config.json
pom.xml
test/native/pom.xml
test/native/src/test/java/org/apache/shardingsphere/test/natived/commons/algorithm/testcontainers/TcClickhouseDatabaseType.java
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/ClickHouseTest.java
test/native/src/test/resources/META-INF/services/org.apache.shardingsphere.infra.database.core.type.DatabaseType
test/native/src/test/resources/test-native/sql/clickhouse-init.sql
test/native/src/test/resources/test-native/yaml/jdbc/databases/clickhouse.yaml

For #29052.
- Refactor ClickHouse's nativeTest. 
- Bump Testcontainers and GraalVM Native Build Tools. Influenced by the merge of https://github.com/testcontainers/testcontainers-java/pull/8738 , refactored to simplify nativeTest for clickhouse integration, which obviously helps to remove boilerplate code that is not convenient to understand.
- Update doc. After a series of complicated refactorings, `org.apache.shardingsphere:shardingsphere-infra-database-hive` no longer needs to be introduced separately.
- `org.graalvm.buildtools:native-maven-plugin:0.10.6` does not recognize `pom.xml` without source code, which affects all `org.apache.shardingsphere:shardingsphere-proxy-dialect-*`. See https://github.com/graalvm/native-build-tools/issues/727 .
--- …

Refactor ClickHouse's nativeTest

---

infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/SQLStatementBinderContext.java

- Removed the unused constructor that took SQLStatement as a parameter
- This change simplifies the class structure and removes unnecessary code

Remove unused constructor from SQLStatementBinderContext

---

proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/fieldlist/MySQLComFieldListPacketExecutor.java

- Add a private final DatabaseType field initialized with "MySQL"
- Replace inline DatabaseType retrieval with the new field for better readability and performance

Optimize MySQLComFieldListPacketExecutor with DatabaseType

---

proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java

- Extract DatabaseType instance as a private field to improve performance
- Update SQLParserEngine initialization to use the pre-loaded DatabaseType
- Modify SQLBindEngine invocation to include DatabaseType as a parameter

Optimize MySQL multi-statements handling

---

docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/presto/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/presto/_index.en.md
test/native/src/test/java/org/apache/shardingsphere/test/natived/commons/TestShardingService.java

For #29052.
- Update the outdated description of transaction support in Presto doc.
- There are bugs with Presto's own transaction support, see https://github.com/prestodb/presto/issues/25204 . This has nothing to do with shardingsphere or `org.apache.shardingsphere.test.natived.jdbc.databases.PrestoTest`.
---

Update the outdated description of transaction support in Presto doc

---

.github/workflows/nightly-ci.yml
RELEASE-NOTES.md
examples/pom.xml
pom.xml

For #32927 .
- Support compiling and using ShardingSphere under OpenJDK 24.
- This apparently avoids the exception thrown when executing `./mvnw clean install -Prelease -T1C -DskipTests "-Djacoco.skip=true" "-Dcheckstyle.skip=true" "-Drat.skip=true" "-Dmaven.javadoc.skip=true"` with GraalVM CE For JDK 24.
```shell
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by org.fusesource.jansi.internal.JansiLoader in an unnamed module (file:/C:/Users/lingh/.m2/wrapper/dists/apache-maven-3.9.9/977a63e90f436cd6ade95b4c0e10c20c/lib/jansi-2.4.1.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future …
```

Support compiling and using ShardingSphere under OpenJDK 24

---

docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
test/native/src/test/java/org/apache/shardingsphere/test/natived/commons/proxy/ProxyTestingServer.java

For #29052.
- Remove the use of `Force Start` parameter in Proxy Native. This is largely an addition to #35413. `org.apache.shardingsphere.proxy.arguments.BootstrapArguments` no longer checks this argument.
---

Remove the use of `Force Start` parameter in Proxy Native

---

.github/workflows/nightly-build.yml
distribution/proxy-native/pom.xml
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md

Fixes https://github.com/apache/shardingsphere/actions/runs/15422331873/job/43400481456 .
- Fix CI failure for arm64 Image build of Proxy Native.
- Although it is possible to start QEMU emulation directly on the x64 actions runner using `docker/setup-qemu-action@v3`, I noticed from https://github.com/linghengqian/shardingsphere/actions/runs/15435456332/job/43440876993 that QEMU emulation to build docker images will easily exceed the 90 minute CI timeout. I prefer to use the arm64 actions runner directly. A build result without timeout comes from https://github.com/linghengqian/shardingsphere/actions/runs/15437501326/job/43447197500 . One reason why the use of QEMU causes a timeout is that the construction of the GraalVM Native Image goes through …

Fix CI failure for arm64 Image build of Proxy Native

---

distribution/proxy/src/main/release-docs/LICENSE
infra/common/src/main/java/org/apache/shardingsphere/infra/instance/ComputeNodeInstance.java
infra/common/src/main/java/org/apache/shardingsphere/infra/instance/ComputeNodeInstanceContext.java
infra/parser/src/main/java/org/apache/shardingsphere/infra/parser/cache/SQLStatementCacheLoader.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/DataConsistencyCheckUtils.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/SingleTableInventoryCalculateParameter.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/sql/PipelineDataConsistencyCalculateSQLBuilder.java
kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/task/CDCIncrementalTask.java
kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/core/task/CDCInventoryTask.java
kernel/sql-federation/compiler/pom.xml
kernel/sql-federation/compiler/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/planner/cache/ExecutionPlanCacheLoader.java
mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/MetaDataContexts.java
parser/sql/engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/cache/ParseTreeCacheLoader.java
parser/sql/engine/src/test/java/org/apache/shardingsphere/sql/parser/api/SQLParserExecutorTest.java
parser/sql/engine/src/test/java/org/apache/shardingsphere/sql/parser/core/SQLParserEngineTest.java
pom.xml

For #26041 .
- Migrate from `jsr305` to `jspecify` and `error_prone_annotations`. For more background, see https://github.com/google/guava/issues/2960 , Guava no longer uses `com.google.code.findbugs:jsr305`.
- The current PR is unfortunately affected by https://github.com/immutables/immutables/issues/1403 and https://github.com/immutables/immutables/issues/1500 .
```shell
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project shardingsphere-sql-federation-optimizer: Compilation failure: Compilation failure:
[ERROR] /D:/TwinklingLiftWorks/git/public/shardingsphere/kernel/sql-federation/optimizer/target/generated-sources/annotations/org/apache/shardingsphere/sqlfederation/optimizer/plan …
```

Migrate from `jsr305` to `jspecify` and `error_prone_annotations`

---

parser/sql/engine/src/main/java/org/apache/shardingsphere/sql/parser/api/SQLStatementVisitorEngine.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/AbstractSQLStatement.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/SQLStatement.java
parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/dal/EmptyStatement.java
parser/sql/statement/type/oracle/src/main/java/org/apache/shardingsphere/sql/parser/statement/oracle/ddl/OraclePLSQLBlockStatement.java
proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java
proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/parse/PostgreSQLComParseExecutor.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/comment/CommentAssert.java

- Move getParameterCount, getParameterMarkerSegments, addParameterMarkerSegments, getVariableNames, and getCommentSegments to SQLStatement interface
- Implement these methods in AbstractSQLStatement
- Update related test cases and classes to use the new interface methods
- Remove redundant implementations in EmptyStatement and OraclePLSQLBlockStatement

Move common methods to SQLStatement interface

---

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/decider/ShardingSQLFederationDecider.java
features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/decider/ShardingSQLFederationDeciderTest.java

- Optimize ShardingSQLFederationDecider logic to pass sql with same condition to kernel
---

Optimize ShardingSQLFederationDecider logic to pass sql with same condition to kernel

---

docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/graalvm-native-image/_index.en.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json
test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/databases/SQLServerTest.java

For https://github.com/apache/shardingsphere/actions/runs/15779757463/job/44482253592 .
- Temporarily disable nativeTest for MS SQL Server's `DROP TABLE IF EXISTS` statement due to refactoring.
- The documentation for Hive's GraalVM Native Image integration is out of date due to the merge of https://github.com/apache/hive/pull/5404 . Update it appropriately.
- Since the merge of an unknown PR, shardingsphere cannot execute statements like `DROP TABLE IF EXISTS t_order` for MS SQL Server.
```shell
java.sql.SQLException: Can not support operation 'DROP TABLE ... CASCADE' with sharding table 't_order'.
at org.apache.shardingsphere.infra.exception.core.external.sql.ShardingSphereSQLException.toSQLException(ShardingSphereSQLException.java:81)
at …
```

Temporarily disable nativeTest for MS SQL Server's `DROP TABLE IF EXISTS` statement due to refactoring

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/DataMatchTableDataConsistencyChecker.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/RecordSingleTableInventoryCalculator.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/StreamingRangeType.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/sql/PipelineDataConsistencyCalculateSQLBuilder.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/DataMatchTableDataConsistencyCheckerTest.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/fixture/FixturePipelineSQLBuilder.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/sql/PipelineDataConsistencyCalculateSQLBuilderTest.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/sql/PipelineInventoryDumpSQLBuilderTest.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/AbstractMigrationE2EIT.java
test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/MySQLMigrationGeneralE2EIT.java
test/it/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/RecordSingleTableInventoryCalculatorTest.java

- Add large range streaming query in RecordSingleTableInventoryCalculator
- Add streaming-range-type prop for DATA_MATCH consistency check
- Add more RecordSingleTableInventoryCalculator test cases; Update SQL builder test cases
---
`ResultSet.close()` disadvantage of MySQL JDBC driver on streaming mode: It'll "drain the rest of the records" before close.
Related stack trace:
```
at com.mysql.cj.protocol.a.result.ResultsetRowsStreaming.close(ResultsetRowsStreaming.java:124)
- locked <0x27f9> (a com.mysql.cj.jdbc.ConnectionImpl)
at com.mysql.cj.jdbc.result.ResultSetImpl.realClose(ResultSetImpl.java:1874)
at com.mysql.cj.jdbc.result.ResultSetImpl.close(ResultSetImpl.java:560)
at com.zaxxer.hikari.pool.HikariProxyResultSet.close(HikariProxyResultSet.java …
```

Add new streaming query impl in DATA_MATCH consistency check for sharding table on MySQL

---

RELEASE-NOTES.md
db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLBoolBinaryProtocolValue.java
db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLBinaryProtocolValueFactoryTest.java
db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLBoolBinaryProtocolValueTest.java

For #35830.
1. Create a table with a bool column in PostgreSQL
```sql
CREATE TABLE IF NOT EXISTS member_summary (
mid VARCHAR(9) PRIMARY KEY,
nickname VARCHAR(63),
previous_champions_season_id BIGINT NOT NULL,
previous_champions_tier_id  BIGINT NOT NULL,
account_level BIGINT NOT NULL,
profile_id BIGINT NOT NULL,
hide_champions_raid_tier_border boolean NOT NULL,
title_id BIGINT NOT NULL,
block_party_invite boolean NOT NULL
);
```
2. Insert some records
3. Use the Go client to query the bool column through Proxy
```sql
SELECT mid, hide_champions_raid_tier_border, title_id, block_party_invite from member_summary where mid = $1
```
- Why not use the `Boolean.parseBoolean()` method?
Because `Boolean.parseBoolean()` only matches the case where the string is "true", and the default bool output …

Implement write method in PostgreSQLBoolBinaryProtocolValue

---

jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AbstractStatementAdapter.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManager.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java
jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java

For #35123.
- Auto clear cached connections in DriverDatabaseConnectionManager, to avoid long-term IN USE of physical connections
TODO
- Completely remove the cachedConnections Map object
---

Auto clear cached connections in DriverDatabaseConnectionManager

---

RELEASE-NOTES.md
proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxyDatabaseConnectionManager.java
proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/FrontendChannelInboundHandler.java

Fixes #35866.
- Make sure to call the `connection.close()` method in the finally block
- If close fails, print a warn log
---

Fix the connection leak caused by rollback failure in Proxy

---

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxyDatabaseConnectionManager.java

Releated to  #35867.
- Ignore SQLException for rollback
- If connection is closed, do not add exception to result

Optimize exception for close cached connections in proxy

---

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

official document:https://learn.microsoft.com/zh-cn/sql/relational-databases/system-functions/managed-backup-fn-available-backups-transact-sql?view=sql-server-ver17
-
---

fix:Support for three-level naming of table-valued function

---

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4
parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/SQLServerKeyword.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

official document:https://learn.microsoft.com/zh-cn/sql/t-sql/functions/percent-rank-transact-sql?view=sql-server-ver17
-
---

fix:Support for the PERCENT_RANK function

---

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
test/it/parser/src/main/resources/case/dml/insert.xml
test/it/parser/src/main/resources/sql/supported/dml/insert.xml

official document:https://learn.microsoft.com/zh-cn/sql/t-sql/statements/insert-transact-sql?view=sql-server-ver17
-
---

fix:Support for the OPENDATASOURCE function in INSERT statements

---

kernel/sql-federation/compiler/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/rel/converter/SQLFederationRelConverter.java
kernel/sql-federation/compiler/src/test/java/org/apache/shardingsphere/sqlfederation/compiler/compiler/it/SQLStatementCompilerIT.java

- Remove useless parameter in SQLFederationRelConverter
---

Remove useless parameter in SQLFederationRelConverter

---

RELEASE-NOTES.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/jakarta-transactions/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/jakarta-transactions/_index.en.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/_index.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/_index.en.md
infra/reachability-metadata/src/main/resources/META-INF/native-image/com.microsoft.sqlserver/mssql-jdbc/12.10.1.jre8/reachability-metadata.json
kernel/transaction/type/xa-jakarta/core/pom.xml
kernel/transaction/type/xa-jakarta/pom.xml
kernel/transaction/type/xa-jakarta/provider/atomikos/pom.xml
kernel/transaction/type/xa-jakarta/provider/narayana/pom.xml
kernel/transaction/type/xa-jakarta/provider/pom.xml
kernel/transaction/type/xa-jakarta/spi/pom.xml
pom.xml

Fixes #26041 .
- Add optional module for Jakarta Transactions impl of Jakarta EE 9 Spec. This is an alternative to #27976 . The main difference is that the current PR does not switch the JAXB version used by the test suite.
- `shardingsphere-transaction-xa-jakarta` basically reuses all the definitions of `shardingsphere-transaction-xa`, but switches `javax.transaction` java package to `jakarta.transaction` java package, and uses a different set of third-party dependencies.
-  It is intentional that the Jakarta EE 8 namespace counterpart `org.apache.shardingsphere.transaction.api.TransactionType#XA` is still used, because `org.apache.shardingsphere:shardingsphere-transaction-xa-jakarta-core` and …

Add optional module for Jakarta Transactions impl of Jakarta EE 9 Spec

---

RELEASE-NOTES.md
pom.xml

Upgrade protobuf-java to 3.25.8 to fix https://www.cve.org/CVERecord?id=CVE-2024-7254

Fixes CVE-2024-7254

---

distribution/proxy/src/main/release-docs/LICENSE
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.cn.md
docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.en.md
kernel/transaction/type/base/seata-at/pom.xml
pom.xml
test/native/pom.xml

Upgrade aggdesigner-algorithm to 6.1 and refactor usage of commons-lang to fix https://www.cve.org/CVERecord?id=CVE-2025-48924
For #36085

Fixes CVE-2025-48924

---

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertOnUpdateTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGenerator.java
features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptLiteralAssignmentToken.java

- Remove java stream api usage in encrypt
---

Remove java stream api usage in encrypt

---

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/DMLStatement.g4
test/it/parser/src/main/resources/case/dml/select.xml
test/it/parser/src/main/resources/sql/supported/dml/select.xml

official document:https://learn.microsoft.com/zh-cn/sql/t-sql/queries/option-clause-transact-sql?view=sql-server-ver17
-
---

fix:Support for OPTION clause in SELECT statements

---

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/DMLStatement.g4
test/it/parser/src/main/resources/case/dml/delete.xml
test/it/parser/src/main/resources/sql/supported/dml/delete.xml

official document:https://learn.microsoft.com/zh-cn/sql/t-sql/statements/delete-transact-sql?view=sql-server-ver17
-
---

fix:Support for the WITH table hint in DELETE statements

---

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/DMLStatement.g4
parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/standard/type/DeleteStatementAssert.java
test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/dml/standard/DeleteStatementTestCase.java
test/it/parser/src/main/resources/case/dml/delete.xml
test/it/parser/src/main/resources/sql/supported/dml/delete.xml

official document:https://learn.microsoft.com/zh-cn/sql/t-sql/statements/delete-transact-sql?view=sql-server-ver17
-
---

fix:Support for the rowSetFunction in DELETE statements

---

proxy/bootstrap/pom.xml

- Add shardingsphere-infra-data-source-pool-hikari dependency for proxy
---

Add shardingsphere-infra-data-source-pool-hikari dependency for proxy

---

test/e2e/sql/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting/show_readwrite_splitting_rules.xml
test/e2e/sql/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting_and_encrypt/show_readwrite_splitting_rules.xml
test/e2e/sql/src/test/resources/cases/rql/dataset/encrypt_and_readwrite_splitting/show_readwrite_splitting_rules.xml
test/e2e/sql/src/test/resources/cases/rql/dataset/readwrite_splitting/show_readwrite_splitting_rules.xml

- Fix readwrite_splitting rql e2e test case
---

Fix readwrite_splitting rql e2e test case

---

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/type/docker/DockerStorageContainer.java

- Fix DockerStorageContainer startup timeout overwritten in E2E
---

Fix DockerStorageContainer startup timeout overwritten in E2E

---

kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/datasource/MySQLJdbcQueryPropertiesExtension.java
kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/datasource/MySQLJdbcQueryPropertiesExtensionTest.java

- Fix MySQL JDBC query properties extension when SSL is required on server
---

Fix MySQL JDBC query properties extension when SSL is required on server

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/InventoryDumper.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/InventoryDumperContext.java

- Simplify InventoryDumper usage of PipelineTableMetaData
---

Simplify InventoryDumper usage of PipelineTableMetaData

---

distribution/proxy/Dockerfile

Fixes #36722 .
- Change the JDK runtime of the Dockerfile that builds ShardingSphere Proxy from `JDK21` to `JDK25`. See https://github.com/docker-library/official-images/pull/19956 .
---

Change the JDK runtime of the Dockerfile that builds ShardingSphere Proxy from `JDK21` to `JDK25`

---

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/CRC32MatchTableDataConsistencyChecker.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/DataMatchTableDataConsistencyChecker.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/MatchingTableInventoryChecker.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/AbstractSingleTableInventoryCalculator.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/AbstractStreamingSingleTableInventoryCalculator.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/CRC32SingleTableInventoryCheckCalculator.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/RecordSingleTableInventoryCalculator.java
kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/query/calculator/SingleTableInventoryCalculator.java
kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/CRC32SingleTableInventoryCheckCalculatorTest.java

- Add generic type RESULT for SingleTableInventoryCalculator
---

Add generic type RESULT for SingleTableInventoryCalculator

---

test/e2e/operation/pipeline/src/test/resources/env/e2e-env.properties

- Add e2e.timezone in e2e-env.properties
If `e2e.timezone` is not configured in `e2e-env.properties`, then UTC time zone will be used in `E2ETestEnvironment`:
```
TimeZone.setDefault(TimeZone.getTimeZone(props.getProperty("e2e.timezone", "UTC")));
```
When OS time zone is not UTC, or database time zone is not UTC, pipeline E2E might run failed on data consistency check because of time zone offset.
---

Add e2e.timezone in e2e-env.properties

---

RELEASE-NOTES.md
pom.xml

Upgrade netty to 4.1.126.Final to fix:
https://www.cve.org/CVERecord?id=CVE-2025-55163
https://www.cve.org/CVERecord?id=CVE-2025-58056
https://www.cve.org/CVERecord?id=CVE-2025-58057

Fixes CVE-2025-55163, CVE-2025-58056, CVE-2025-58057
