infra/util/src/main/java/org/apache/shardingsphere/infra/util/directory/ClasspathResourceDirectoryReader.java
=> Fix sonar issues.

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/combine/CombineSegmentBinder.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/statement/select/SelectStatementConverter.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/combine/CombineSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/ColumnExtractor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtils.java, parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractorTest.java, parser/sql/statement/src/test/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtilsTest.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/SelectStatementAssert.java
- Refactor select combine statement parse result to SubquerySegment
---
=> Refactor select combine statement parse result to SubquerySegment

.github/workflows/nightly-check.yml
- refactor the parameters for actions in nightly check
---
=> Refactor : refactor the parameters for actions in nightly check

pom.xml
- update the reports and site plugin version
---
=> Bump : update the reports and site plugin version

pom.xml
- add dependency-check-maven report plugin
---
=> Add : add dependency-check-maven report plugin

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java
=> make subquery expression bind return column projection

.github/workflows/nightly-check.yml, pom.xml
- add dependency convergence check
---
=> Add dependency convergence check

agent/plugins/tracing/type/opentelemetry/pom.xml, test/e2e/agent/plugins/common/pom.xml
Fixes #30745.
- Fix dependency conflicts in agent
---
=> Fix dependency conflicts in agent

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/engine/PaginationContextEngine.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/engine/RowNumberPaginationContextEngine.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContext.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/engine/PaginationContextEngineTest.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/engine/RowNumberPaginationContextEngineTest.java
- Minor refactor PaginationContextEngine init logic
---
=> Minor refactor PaginationContextEngine init logic

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/BackendDataSource.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/OnlineDatabaseConnectionManager.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManager.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxyDatabaseConnectionManager.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/datasource/JDBCBackendDataSource.java
=> refactor BackendDataSource

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SubqueryTableSegmentBinder.java
- Minor refactor SubqueryTableSegmentBinder to reduce duplicate logic
---
=> Minor refactor SubqueryTableSegmentBinder to reduce duplicate logic

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/PLSQL.g4, test/it/parser/src/main/resources/case/ddl/create-trigger.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-trigger.xml
Fixes #27077.
-Enhance the support for Oracle SQL parsing in ShardingSphere 
---
=> Enhance the support for Oracle SQL parsing in ShardingSphere 

infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/SubquerySegmentBinderTest.java
Fixes #28507.
-
Add unit tests for SubquerySegmentBinder.java
---
=> Add unit tests for SubquerySegmentBinder

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationExecutor.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ConvertYamlConfigurationExecutorTest.java, proxy/backend/core/src/test/resources/conf/convert/database-empty.yaml, proxy/backend/core/src/test/resources/expected/convert-empty-database.yaml
=> Check null data sources or null rules when convert yaml configuration

kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableExecutor.java, kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableExecutorTest.java
=> Fixes #30824, check empty storage units before load single table

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/node/config/processor/JobConfigurationChangedProcessEngine.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/AbstractMigrationE2EIT.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLMigrationGeneralE2EIT.java
- Fix PostgreSQL replication slot not cleaned on job deleted
---
=> Fix PostgreSQL replication slot not cleaned on job deleted

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/DALE2EIT.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/RALE2EIT.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/RDLE2EIT.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/BaseDMLE2EIT.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dql/BaseDQLE2EIT.java
=> Fix expected data set rows message

infra/common/src/main/java/org/apache/shardingsphere/infra/instance/mode/ModeContextManager.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/ClusterModeContextManager.java, mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneModeContextManager.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportMetaDataExecutor.java
- Refactor import metadata & remove deprecated api
---
=> Refactor import metadata & remove deprecated api

proxy/backend/type/hbase/src/test/java/org/apache/shardingsphere/proxy/backend/hbase/result/query/HBaseDescribeResultSetTest.java, proxy/backend/type/hbase/src/test/java/org/apache/shardingsphere/proxy/backend/hbase/result/query/HBaseListResultSetTest.java
=> Fix : fix test compile

proxy/backend/type/hbase/src/test/java/org/apache/shardingsphere/proxy/backend/hbase/result/query/HBaseDescribeResultSetTest.java
=> Fix : fix test errors

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/OnlineDatabaseConnectionManager.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManager.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxyDatabaseConnectionManager.java
=> change OnlineDatabaseConnectionManager to interface

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/caseinsensitive/CaseInsensitiveIdentifier.java
=> Fix sonar.

infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/where/WhereSegmentBinderTest.java
Refactor WhereSegmentBinderTest.
---
=> Refactor WhereSegmentBinderTest

kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/constant/EnumerableConstants.java
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=apache_shardingsphere&open=AY5bkr5n2QySt99iJN1U
---
=> Fix sonar issue caused by collection change and public modifier

examples/pom.xml, pom.xml
=> Upgrade mysql-connector-j to 8.3.0

.github/workflows/e2e-sql.yml, .github/workflows/nightly-e2e-sql.yml, docs/document/content/user-manual/shardingsphere-proxy/cdc/build.cn.md, docs/document/content/user-manual/shardingsphere-proxy/cdc/build.en.md, docs/document/content/user-manual/shardingsphere-proxy/migration/build.cn.md, docs/document/content/user-manual/shardingsphere-proxy/migration/build.en.md, examples/shardingsphere-jdbc-example-generator/src/main/resources/template/pom.ftl
=> Upgrade mysql-connector-j to 8.3.0 in doc and e2e

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/index/IndexReviseEngineTest.java
Refactor IndexReviseEngineTest.
---
=> Refactor IndexReviseEngineTest

examples/pom.xml
=> Change example project version to 5.5.0 for release

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/checker/ShardingRuleChecker.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/cache/checker/ShardingRouteCacheableCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java
=> Add inline sharding algorithms match actual data nodes check

README.md, README_ZH.md
Fixes #30877.
- Fix the problem of Landscapes images not displaying on the homepage
---
=> Fix the problem of Landscapes images not displaying on the homepage

docs/document/content/user-manual/error-code/sql-error-code.cn.md, docs/document/content/user-manual/error-code/sql-error-code.en.md, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/exception/EncryptSQLException.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/exception/data/DecryptFailedException.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptMergedResult.java, infra/exception/core/src/main/java/org/apache/shardingsphere/infra/exception/core/external/sql/ShardingSphereSQLException.java, infra/exception/core/src/main/java/org/apache/shardingsphere/infra/exception/core/external/sql/sqlstate/XOpenSQLState.java, infra/exception/core/src/main/java/org/apache/shardingsphere/infra/exception/core/external/sql/type/feature/FeatureSQLException.java
=> Throw DecryptFailedException when a decryption error occurs.

test/e2e/operation/pipeline/src/test/resources/env/scenario/create-table-generator/mysql/create-table-sql-generator.xml
=> fix CreateTableSQLGeneratorIT error.

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/strategy/YamlKeyGenerateStrategyConfigurationSwapperTest.java
=> YamlKeyGenerateStrategyConfigurationSwapperTest adding UTs

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/strategy/YamlShardingAuditStrategyConfigurationSwapperTest.java
=> YamlShardingAuditStrategyConfigurationSwapperTest UTs

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/strategy/YamlShardingStrategyConfigurationSwapperTest.java
=> YamlShardingStrategyConfigurationSwapperTest Unit Test

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/rule/YamlShardingTableReferenceRuleConfigurationConverterTest.java
=> YamlShardingTableReferenceRuleConfigurationConverterTest Unit Tests

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/rule/YamlShardingTableRuleConfigurationSwapperTest.java
=> YamlShardingTableRuleConfigurationSwapperTest Unit Test

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/ShardingRuleConfigurationConverterTest.java
=> ShardingRuleConfigurationConverterTest Unit Test

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/yaml/swapper/YamlShardingRuleConfigurationSwapperTest.java
=> YamlShardingRuleConfigurationSwapperTest Adding UTs

test/e2e/agent/plugins/logging/file/src/test/java/org/apache/shardingsphere/test/e2e/agent/file/FilePluginE2EIT.java, test/e2e/agent/plugins/logging/file/src/test/java/org/apache/shardingsphere/test/e2e/agent/file/cases/IntegrationTestCases.java, test/e2e/agent/plugins/logging/file/src/test/java/org/apache/shardingsphere/test/e2e/agent/file/cases/IntegrationTestCasesLoader.java, test/e2e/agent/plugins/logging/file/src/test/java/org/apache/shardingsphere/test/e2e/agent/file/cases/LogTestCase.java, test/e2e/agent/plugins/logging/file/src/test/resources/cases/jdbc/logs.xml, test/e2e/agent/plugins/logging/file/src/test/resources/cases/proxy/logs.xml
Fixes #30898.
- Refactor agent logging e2e test in agent
---
=> Refactor agent logging e2e test

test/e2e/agent/plugins/common/src/test/java/org/apache/shardingsphere/test/e2e/agent/common/container/JaegerContainer.java, test/e2e/agent/plugins/common/src/test/java/org/apache/shardingsphere/test/e2e/agent/common/container/MySQLContainer.java, test/e2e/agent/plugins/common/src/test/java/org/apache/shardingsphere/test/e2e/agent/common/container/PrometheusContainer.java, test/e2e/agent/plugins/common/src/test/java/org/apache/shardingsphere/test/e2e/agent/common/container/ShardingSphereJdbcContainer.java, test/e2e/agent/plugins/common/src/test/java/org/apache/shardingsphere/test/e2e/agent/common/container/ShardingSphereProxyContainer.java, test/e2e/agent/plugins/common/src/test/java/org/apache/shardingsphere/test/e2e/agent/common/container/ZipkinContainer.java, test/e2e/agent/plugins/common/src/test/java/org/apache/shardingsphere/test/e2e/agent/common/env/E2ETestEnvironment.java, test/e2e/agent/plugins/common/src/test/resources/env/image.properties, test/e2e/agent/plugins/logging/file/src/test/java/org/apache/shardingsphere/test/e2e/agent/file/asserts/ContentAssert.java
Fixes #30898.
- Improve agent e2e test, add image version config
---
=> Improve agent e2e test, add image version config

features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/api/config/EncryptRuleConfiguration.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/EncryptRuleTest.java
=> Fix EncryptRuleConfiguration defaultProperties.

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/engine/GenericSQLRewriteEngine.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/engine/RouteSQLRewriteEngine.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/impl/AbstractSQLBuilder.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/impl/DefaultSQLBuilder.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/impl/RouteSQLBuilder.java, infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/impl/DefaultSQLBuilderTest.java, infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/sql/impl/RouteSQLBuilderTest.java
- Refactor AbstractSQLBuilder to reduce input parameter
---
=> Refactor AbstractSQLBuilder to reduce input parameter

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/session/transaction/TransactionStatus.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/session/ConnectionSessionTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/session/transaction/TransactionStatusTest.java
=> Remove unused setTransactionType method

infra/session/src/main/java/org/apache/shardingsphere/infra/session/connection/transaction/TransactionConnectionContext.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AbstractStatementAdapter.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManager.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java, jdbc/src/test/java/org/apache/shardingsphere/driver/state/DriverStateContextTest.java, kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/ConnectionTransaction.java, kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/rule/TransactionRule.java, kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/ConnectionTransactionTest.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManager.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManagerTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionBackendHandlerFactoryTest.java
=> Support for switching transaction types

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxyDatabaseConnectionManager.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxySQLExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManager.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionXAHandler.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/session/ConnectionSession.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/session/transaction/TransactionStatus.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/TransactionUtils.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/ProxyDatabaseConnectionManagerTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/ProxySQLExecutorTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManagerTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactoryTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/SetDistVariableUpdatableRALBackendHandlerTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/session/ConnectionSessionTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/session/transaction/TransactionStatusTest.java, proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowProcessListExecutorTest.java, proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/sysvar/provider/TransactionIsolationValueProviderTest.java, proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/sysvar/provider/TransactionReadOnlyValueProviderTest.java, proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/sysvar/provider/VersionValueProviderTest.java, proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/FrontendChannelInboundHandler.java, proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/state/impl/OKProxyState.java, proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/state/impl/OKProxyStateTest.java, proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/admin/MySQLComResetConnectionExecutorTest.java, proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/reset/MySQLComStmtResetExecutorTest.java, proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/PostgreSQLCommandExecuteEngineTest.java, proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/sync/PostgreSQLComSyncExecutorTest.java
=> Replace TransactionStatus.transactionType with transactionRule.defaultType

infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/data/loader/OracleMetaDataLoader.java
=> Refactor OracleMetaDataLoader.

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DCLStatement.g4, test/it/parser/src/main/resources/case/dcl/create-user.xml, test/it/parser/src/main/resources/sql/supported/dcl/create-user.xml
Fixes #30964.
-Added support for MySQL user creation options and updated Sql cases.
---
=> Support parsing MySQL CREATE USER sql

test/e2e/sql/src/test/resources/cases/dql/dql-integration-select.xml
- Add datetime type convert e2e test
- Append e2e tests for #30935 using the t_product_extend table
---
=> Add datetime type convert e2e test

jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java, kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/ConnectionTransaction.java
=> Use same transaction type in one transaction in jdbc adapter

features/mask/core/src/test/java/org/apache/shardingsphere/mask/checker/MaskRuleConfigurationCheckerTest.java
Fixes #30582.
- Add test cases for MaskRuleConfigurationChecker
---
=> Add test cases for MaskRuleConfigurationChecker

kernel/global-clock/distsql/handler/src/test/java/org/apache/shardingsphere/globalclock/distsql/handler/update/AlterGlobalClockRuleExecutorTest.java
Ref #30083.
- Enhance AlterGlobalClockRuleExecutorTest test case
---
=> Enhance AlterGlobalClockRuleExecutorTest test case

features/mask/core/src/test/java/org/apache/shardingsphere/mask/checker/MaskRuleConfigurationCheckerTest.java
=> Refactor MaskRuleConfigurationCheckerTest

kernel/global-clock/distsql/handler/src/test/java/org/apache/shardingsphere/globalclock/distsql/handler/update/AlterGlobalClockRuleExecutorTest.java
=> Revise AlterGlobalClockRuleExecutorTest

kernel/global-clock/distsql/handler/src/test/java/org/apache/shardingsphere/globalclock/distsql/handler/update/AlterGlobalClockRuleExecutorTest.java
Ref #30083.
- Refactor AlterGlobalClockRuleExecutorTest Test Case
---
=> Refactor AlterGlobalClockRuleExecutorTest Test Case

infra/algorithm/core/pom.xml, infra/algorithm/message-digest/type/md5/pom.xml, infra/url/core/pom.xml, kernel/schedule/core/pom.xml
Fixes #31128.
- Removes test modules that are not deployed to Maven Central Repository.
---
=> Removes test modules that are not deployed to Maven Central Repository

features/encrypt/api/src/main/java/org/apache/shardingsphere/encrypt/api/config/EncryptRuleConfiguration.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/standard/AESEncryptAlgorithm.java, infra/util/src/main/java/org/apache/shardingsphere/infra/util/props/MultiSourceProperties.java, infra/util/src/test/java/org/apache/shardingsphere/infra/util/props/MultiSourcePropertiesTest.java
=> Add MultiSourceProperties to support Properties with defaults.

infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/shardingsphere-infra-reachability-metadata/reflect-config.json, test/native/pom.xml, test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/transactions/base/SeataTest.java
Fixes https://github.com/apache/shardingsphere/actions/runs/8990155213/job/24694870508 .
- Fixes NativeTest failure under GraalVM Native Image due to class changes.
- Updated some outdated comments.
---
=> Fixes NativeTest failure under GraalVM Native Image due to class changes

kernel/sql-federation/distsql/handler/src/test/java/org/apache/shardingsphere/sqlfederation/distsql/handler/update/AlterSQLFederationRuleExecutorTest.java
Fixes #30083.
- Refactor AlterSQLFederationRuleExecutorTest Test Case
---
=> Refactor AlterSQLFederationRuleExecutorTest Test Case

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/context/ShardingSQLRewriteContextDecorator.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/IndexToken.java, test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/scenario/ShardingSQLRewriterIT.java, test/it/rewriter/src/test/resources/scenario/sharding/case/ddl/alter-table.xml, test/it/rewriter/src/test/resources/scenario/sharding/case/ddl/create-table.xml, test/it/rewriter/src/test/resources/scenario/sharding/case/ddl/index.xml
Ref #31171.
- Remove useless single and broadcast table index name rewrite in IndexToken
---
=> Remove useless single and broadcast table index name rewrite in IndexToken

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/Process.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/ProcessRegistry.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/yaml/swapper/YamlProcessSwapper.java, infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/process/yaml/swapper/YamlProcessListSwapperTest.java, infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/process/yaml/swapper/YamlProcessSwapperTest.java, mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/process/subscriber/ProcessListChangedSubscriberTest.java, proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowProcessListExecutor.java, proxy/backend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowProcessListExecutorTest.java
=> optimize Process code

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-expression.xml
- Enhance mysql json function visit statement result
---
=> Enhance mysql json function visit statement result

kernel/sql-translator/distsql/handler/src/test/java/org/apache/shardingsphere/sqltranslator/distsql/handler/update/AlterSQLTranslatorRuleExecutorTest.java
Ref #30083.
- Refactor AlterSQLTranslatorRuleExecutorTest Test Case
---
=> Refactor AlterSQLTranslatorRuleExecutorTest Test Case

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/MatchExpressionConverter.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/ExpressionExtractUtils.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/segment/mysql/match/MatchAgainstExpression.java, src/resources/checkstyle.xml, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/expr/ExpectedMatchExpression.java, test/it/parser/src/main/resources/case/dml/select.xml
=> Optimize the parsing of match expressions.

.github/workflows/nightly-check.yml
- add filter to fix deadlink
---
=> Fix : add filter to fix deadlink

jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AbstractStatementAdapter.java
=> Modify in transaction judgement of implicitly committed transactions

jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AbstractStatementAdapter.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
=> Extract duplicate executeWithImplicitCommitTransaction methods

docs/blog/content/material/2023_03_07_ShardingSphere_5.3.x_Update_Spring_Configuration_Update_Guide.en.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-namespace/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-namespace/_index.en.md
- Use HikariDataSource to replace SimpleDriverDataSource in doc
---
=> Use HikariDataSource to replace SimpleDriverDataSource in doc

infra/database/type/hive/pom.xml, infra/database/type/hive/src/main/java/org/apache/shardingsphere/infra/database/hive/type/HiveDatabaseType.java, infra/database/type/hive/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.database.core.type.DatabaseType, infra/database/type/hive/src/test/java/org/apache/shardingsphere/infra/database/hive/type/HiveDatabaseTypeTest.java, parser/sql/dialect/hive/pom.xml, parser/sql/dialect/hive/src/main/antlr4/imports/hive/Alphabet.g4, parser/sql/dialect/hive/src/main/antlr4/imports/hive/BaseRule.g4, parser/sql/dialect/hive/src/main/antlr4/imports/hive/Comments.g4, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DMLStatement.g4, parser/sql/dialect/hive/src/main/antlr4/imports/hive/HiveKeyword.g4, parser/sql/dialect/hive/src/main/antlr4/imports/hive/Keyword.g4, parser/sql/dialect/hive/src/main/antlr4/imports/hive/Literals.g4, parser/sql/dialect/hive/src/main/antlr4/imports/hive/Symbol.g4, parser/sql/dialect/hive/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/HiveStatement.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/parser/HiveLexer.java, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/parser/HiveParser.java, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/parser/HiveParserFacade.java, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/HiveStatementVisitor.java, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/HiveStatementVisitorFacade.java, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDMLStatementVisitor.java, parser/sql/dialect/hive/src/main/resources/META-INF/services/org.apache.shardingsphere.sql.parser.spi.DialectSQLParserFacade, parser/sql/dialect/hive/src/main/resources/META-INF/services/org.apache.shardingsphere.sql.parser.spi.SQLStatementVisitorFacade, parser/sql/dialect/pom.xml, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/hive/HiveStatement.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/hive/dml/HiveDeleteStatement.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/hive/dml/HiveInsertStatement.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/hive/dml/HiveSelectStatement.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/hive/dml/HiveUpdateStatement.java
Ref #31256.
- Add hive sql parser logic and hive database type module
---
=> Add hive sql parser logic and hive database type module

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/CommonSQLStatementContext.java
Fixes #31256.
- Add Doris, Hive and Presto databaseType in CommonSQLStatementContext
---
=> Add Doris, Hive and Presto databaseType in CommonSQLStatementContext

jdbc/src/test/java/org/apache/shardingsphere/driver/jdbc/core/datasource/ShardingSphereDataSourceTest.java, jdbc/src/test/java/org/apache/shardingsphere/driver/state/DriverStateContextTest.java, mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java, mode/core/src/main/java/org/apache/shardingsphere/mode/state/StateContext.java, mode/core/src/main/java/org/apache/shardingsphere/mode/state/StateService.java, mode/core/src/test/java/org/apache/shardingsphere/mode/manager/ContextManagerTest.java, mode/core/src/test/java/org/apache/shardingsphere/mode/state/StateContextTest.java, mode/core/src/test/java/org/apache/shardingsphere/mode/state/StateServiceTest.java, mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/subscriber/StateChangedSubscriberTest.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactory.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/LockClusterExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/UnlockClusterExecutor.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/context/ProxyContextTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactoryTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/LockClusterExecutorTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/UnlockClusterExecutorTest.java, proxy/frontend/core/src/test/java/org/apache/shardingsphere/proxy/frontend/command/CommandExecutorTaskTest.java
- rename ClusterStateContext to StateContext
- move StateContext to mode
- add StateService to persist and load state from repository
=> Rename ClusterStateContext to StateContext and move it to mode

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptRule.java
=> Fix the case-sensitive issue when partially updating encryption rules.

parser/sql/dialect/doris/src/main/antlr4/imports/doris/BaseRule.g4, parser/sql/dialect/doris/src/main/antlr4/imports/doris/DDLStatement.g4, parser/sql/dialect/doris/src/main/antlr4/imports/doris/DMLStatement.g4, parser/sql/dialect/doris/src/main/antlr4/imports/doris/DorisKeyword.g4, parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/DorisStatementVisitor.java, parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/type/DorisDDLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CreateTableStatementHandler.java, test/it/parser/src/main/resources/case/ddl/create-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
Ref #31270.
- Add difference comment for doris special parse logic and rename test case identifier name
---
=> Add difference comment for doris special parse logic and rename test case identifier name

proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowTablesExecutor.java
=> Fixes #31279, make the results of show tables in order

examples/README.md
Improve unreasonable formatting in documents
- Improve unreasonable formatting in documents
---
=> Update README.md:Improve unreasonable formatting in documents

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/global-rule/alter-transaction-rule.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/global-rule/alter-transaction-rule.en.md
=> Fix alter transaction rule documentation

docs/blog/content/material/database.en.md
…cters appear normally.
Improve unreasonable formatting in document
- Modify the bolded characters in the document to make the bolded characters appear normally.
---
=> Modify the bolded characters in the document to make the bolded characters appear normally.

docs/blog/content/material/realization.cn.md
- According to the numbers in the document and the spacing between the English format and the Chinese format, the document format is adjusted to achieve the standardization of the document.
---
=> Update realization.cn.md：Optimize docs

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptRule.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/rule/MaskRule.java
=> Fix case insensitive issue when partial update encrypt and mask rule.

docs/blog/content/material/solution.cn.md, docs/document/content/user-manual/shardingsphere-proxy/cdc/build.cn.md, docs/document/content/user-manual/shardingsphere-proxy/cdc/build.en.md
- Correct unreasonable formatting errors in documents and adjust the formatting between Chinese and English in documents according to the semantics.
---
=> Correct unreasonable formatting errors in documents and adjust the formatting between Chinese and English in documents according to the semantics.

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/util/ContainerUtils.java
=> Refactor : remove ueless code

docs/blog/content/material/2022_06_16_Understanding_Apache_ShardingSphere's_SPI_and_why_it’s_simpler_than_Dubbo’s.en.md, docs/blog/content/material/2022_06_28_Cloud_native_deployment_for_a_high-performance_data_gateway_new_API_driver_Apache_ShardingSphere_5.1.2_is_released.en.md
- Modify an unreasonable format error in the document:
1. Delete the unrelated disorderly list according to semantics;
2. Divide the related sub -blocks and add a three -level title.
---
=> According to semantics, modify unreasonable format errors in the document.

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/util/ContainerUtils.java
=> Refactor : remove container id variable

mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/JDBCRepository.java, mode/type/standalone/repository/provider/jdbc/src/test/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/JDBCRepositoryTest.java
=> Fix #31372 problem

docs/document/content/test-manual/integration-test/_index.cn.md, docs/document/content/test-manual/integration-test/_index.en.md
=> Document : update the IT document

proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/simple/PostgreSQLComQueryExecutor.java
=> Fix PostgreSQLComQueryExecutor databaseType.

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContext.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/from/impl/SimpleTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/with/CommonTableExpressionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/with/WithSegmentBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/expression/impl/SubquerySegmentBinderTest.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/with/WithConverter.java, parser/sql/dialect/doris/src/main/antlr4/imports/doris/DMLStatement.g4, parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/DorisStatementVisitor.java, parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/format/MySQLFormatVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDMLStatementVisitor.java, parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/DMLStatement.g4, parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/extractor/TableExtractor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/expr/complex/CommonTableExpressionSegment.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/dml/SelectStatement.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/ColumnExtractor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/ExpressionExtractUtils.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/SubqueryExtractUtils.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/doris/dml/DorisSelectStatement.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/dml/MySQLSelectStatement.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/oracle/dml/OracleSelectStatement.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/sqlserver/dml/SQLServerSelectStatement.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/with/WithClauseAssert.java
=>  Optimize CTE in parser.

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/WithSegment.java
=> Optimize CTE in parser.

docs/document/content/features/transaction/_index.en.md
XA supports strong consistency.
-
---
=> Fix xa doc error

infra/database/type/hive/src/test/java/org/apache/shardingsphere/infra/database/hive/metadata/database/HiveDatabaseMetaDataTest.java, infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/database/OracleDatabaseMetaData.java
=> Set oracle is instance connection available to true

infra/common/src/main/java/org/apache/shardingsphere/infra/datanode/DataNodes.java
=> Modify the getDataNodesByTableName method without using stream

src/resources/idea/inspections.xml
- make default value for `AnonymousInnerClassMayBeStatic` as false
---
=> Refactor : make default value for AnonymousInnerClassMayBeStatic as false

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/rule/BroadcastRule.java, infra/common/src/main/java/org/apache/shardingsphere/infra/datanode/DataNodes.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/impl/AbstractSQLBuilder.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/rule/SingleRule.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/rule/SingleTableMapperRuleAttribute.java
=> Use CaseInsensitiveSet in broadcast rule

features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/datanode/ReadwriteSplittingDataNodeBuilder.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/datanode/ShadowDataNodeBuilder.java, infra/common/src/main/java/org/apache/shardingsphere/infra/datanode/DataNodes.java
=> Reduce repeated calls to DataSourceMapperRuleAttribute

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/config/AdaptorContainerConfiguration.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/config/ProxyClusterContainerConfigurationFactory.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/impl/ShardingSphereProxyClusterContainer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/container/config/proxy/PipelineProxyClusterContainerConfigurationFactory.java, test/e2e/operation/showprocesslist/src/test/java/org/apache/shardingsphere/test/e2e/showprocesslist/container/composer/ClusterShowProcessListContainerComposer.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/engine/base/TransactionBaseE2EIT.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/env/TransactionE2EEnvironment.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/framework/container/compose/DockerContainerComposer.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/framework/container/config/proxy/ProxyClusterContainerConfigurationFactory.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/framework/param/TransactionTestParameter.java, test/e2e/operation/transaction/src/test/resources/env/it-env.properties, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/container/config/ProxyClusterContainerConfigurationFactory.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/container/config/ProxyStandaloneContainerConfigurationFactory.java
- add debug mode for transaction E2E
---
=> Add : add debug mode for transaction E2E

infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/database/OracleDatabaseMetaData.java
=> OracleDatabaseMetaData add datatype NUMBER.

parser/sql/dialect/doris/src/main/antlr4/imports/doris/DMLStatement.g4, parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/type/DorisDMLStatementVisitor.java, test/it/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #31674 .
-
Modify DMLStatement.g4 about Doris, reference this [PR:31643](https://github.com/apache/shardingsphere/pull/31643).
---
=> Fix the error in parsing the Doris query with index hints.

docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/_index.en.md, docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.cn.md, docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.en.md
- Update shardingsphere optional plugin doc
---
=> Update shardingsphere optional plugin doc

agent/plugins/logging/type/file/src/main/resources/META-INF/conf/file-advisors.yaml, test/e2e/agent/plugins/logging/file/src/test/java/org/apache/shardingsphere/test/e2e/agent/file/FilePluginE2EIT.java
Fixes #31679.
- Remove disable from FilePluginE2EIT
---
=> Remove disable from FilePluginE2EIT

jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManager.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
=> Extract the usage of cachedConnections.values

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/statistics/ShardingSphereStatisticsTest.java
Fixes #28489 .
- Adding unit tests for the class `ShardingSphereStatistics`
---
=> Add unit tests for ShardingSphereStatistics

test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/autocommit/AutoCommitTestCase.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/autocommit/MySQLAutoCommitTestCase.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/autocommit/PostgreSQLAutoCommitTestCase.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/base/BaseTransactionTestCase.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/commitrollback/MultiOperationsCommitAndRollbackTestCase.java
=> Add auto commit test case

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/metadata/reviser/index/ShardingIndexReviserTest.java
Fixes #28524.
- Add unit tests for `ShardingIndexReviser`
---
=> Add unit tests for ShardingIndexReviser

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/function/mysql/MySQLBitCountFunction.java
Fixes https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=apache_shardingsphere&open=AZAb1iSFDHEnZc8iD59F&tab=code
=> Fix sonar issue for MySQLBitCountFunction

test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/savepoint/BaseSavePointTestCase.java, test/e2e/operation/transaction/src/test/resources/env/it-env.properties
=> Add savepoint without name E2E

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/Process.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/ProcessEngine.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/process/ProcessRegistry.java
- Remove useless method in Process, remove mysql judge logic in ProcessEngine, refactor ProcessRegistry#merge logic
---
=> Remove useless method in Process, remove mysql judge logic in ProcessEngine, refactor ProcessRegistry#merge logic

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/TableTokenGenerator.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/ddl/CloseStatementContext.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/ddl/FetchStatementContext.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/ddl/MoveStatementContext.java, test/it/rewriter/src/test/resources/scenario/sharding/case/ddl/close.xml, test/it/rewriter/src/test/resources/scenario/sharding/case/ddl/fetch.xml, test/it/rewriter/src/test/resources/scenario/sharding/case/ddl/move.xml
- Add TableAvailable interface for CloseStatementContext, MoveStatementContext, FetchStatementContext and fix sql rewrite test case
---
=> Add TableAvailable interface for CloseStatementContext, MoveStatementContext, FetchStatementContext and fix sql rewrite test case

infra/database/type/hive/pom.xml, kernel/global-clock/type/tso/provider/redis/pom.xml, pom.xml
=> Optimize dependency.

pom.xml
=> Remove org.glassfish.javax.el dependency of hive

kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/SetDefaultSingleTableStorageUnitExecutor.java, kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/update/SetDefaultSingleTableStorageUnitExecutorTest.java
=> Fixes #31773, support logic data source when set default single table storage unit.

docs/community/content/involved/release/shardingsphere.cn.md, docs/community/content/involved/release/shardingsphere.en.md
- add the modification for ShardingSphereDriver in release process
---
=> Document : add the modification for ShardingSphereDriver in release process

jdbc/src/test/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManagerTest.java
=> Fix sonar issue of assertBeginTransaction method

parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/DorisStatementVisitor.java
- fix Doris visit json_table function space text bug
---
=> fix doris visit json_table function space text bug

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxyDatabaseConnectionManager.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxySQLExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/session/ConnectionSession.java, proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/sysvar/provider/TransactionIsolationValueProvider.java, proxy/backend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/executor/PostgreSQLShowVariableExecutor.java
=> Modify the get isolation level method to return Optional

test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/autocommit/AutoCommitTestCase.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/autocommit/MySQLAutoCommitTestCase.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/autocommit/PostgreSQLAutoCommitTestCase.java
=> Add test case for setting autoCommit without committing

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/constant/EncryptOrder.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/constant/MaskOrder.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/constant/SingleOrder.java
=> Change the single order to before the encrypt order

agent/core/src/main/java/org/apache/shardingsphere/agent/core/advisor/config/yaml/entity/YamlPointcutConfiguration.java, agent/core/src/main/java/org/apache/shardingsphere/agent/core/advisor/config/yaml/swapper/YamlPointcutConfigurationSwapper.java, agent/core/src/test/java/org/apache/shardingsphere/agent/core/advisor/config/yaml/fixture/YamlTargetObjectFixture.java, agent/core/src/test/java/org/apache/shardingsphere/agent/core/advisor/config/yaml/loader/YamlAdvisorsConfigurationLoaderTest.java, agent/core/src/test/java/org/apache/shardingsphere/agent/core/advisor/config/yaml/swapper/YamlAdvisorsConfigurationSwapperTest.java, agent/core/src/test/resources/META-INF/conf/advisors.yaml, agent/plugins/metrics/type/prometheus/src/main/resources/META-INF/conf/prometheus-advisors.yaml, agent/plugins/tracing/type/opentelemetry/src/main/resources/META-INF/conf/opentelemetry-advisors.yaml, distribution/agent/src/main/resources/conf/agent.yaml
Fixes #31841.
- Add modifiers and return type for pointcut configuration
---
=> Add modifiers and return type for pointcut configuration

parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/dml/expr/ExpressionWithParamsSegment.java
- Add todo for ExpressionWithParamsSegment
---
=> Add todo for ExpressionWithParamsSegment

infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/update/rdl/rule/spi/database/DatabaseRuleDropExecutor.java
=> Refactor : remove useless space

mode/core/src/main/java/org/apache/shardingsphere/mode/lock/LockPersistService.java
=> Refactor : remove space

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4, parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DALStatement.g4, parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DCLStatement.g4, parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DDLStatement.g4, parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/RLStatement.g4, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDALStatementVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDCLStatementVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java
=> Rename schemaName to databaseName in mysql sql parser

infra/util/src/main/java/org/apache/shardingsphere/infra/util/directory/ClasspathResourceDirectoryReader.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/column/ColumnValueReaderEngine.java
https://sonarcloud.io/project/issues?impactSeverities=MEDIUM&resolved=false&id=apache_shardingsphere&open=AY3yqW-EzWMEFkWag-WW&tab=code
=> Fix sonar issue on ClasspathResourceDirectoryReader

infra/parser/src/main/java/org/apache/shardingsphere/infra/parser/ShardingSphereSQLParserEngine.java
https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&rules=java%3AS1905&id=apache_shardingsphere&open=AY7BSKh5LvnJTKA3QP8f
=> Fix sonar issue on ShardingSphereSQLParserEngine

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManager.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/LocalTransactionManager.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManagerTest.java
=> Fix savepoint manager not cleaned up in distributed transactions

test/it/parser/src/main/resources/case/dml/insert.xml, test/it/parser/src/main/resources/case/dml/select-math-function.xml, test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/sql/supported/dml/insert.xml, test/it/parser/src/main/resources/sql/supported/dml/select-math-function.xml, test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml
Fixes #31546 .
-
- I've verified all sql can be parsed by the parsor normally,and table field parameters in methods are accurately mapped to parameters in the Statement.
- added corresponding unit case for each SQL,and SQL Parser IT run successfully.
---
=> verify the functions involved in #31546 and add test cases

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/generator/generic/RemoveTokenGenerator.java
- Minor refactor for RemoveTokenGenerator
---
=> Minor refactor for RemoveTokenGenerator

proxy/bootstrap/src/main/java/org/apache/shardingsphere/proxy/version/ShardingSphereProxyVersion.java
=> Refactor ShardingSphereProxyVersion

test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml
Fixes #31562.
- I've verified all sql can be parsed by the parser normally, and table field parameters in methods are accurately mapped to parameters in the Statement.
- Added test cases for SQL function for MYSQL parsing.
---
=> verify the functions involved in #31562 and add test cases

mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/manager/ResourceSwitchManager.java
=> Keep inused storage node when unregister storage unit

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/register-storage-unit.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/register-storage-unit.en.md, parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/segment/DataSourceSegment.java
- Correct storage unit name and db name
- Add allowPublicKeyRetrieval to URL method
=> Update doc for register storage unit

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/alter-storage-unit.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/alter-storage-unit.en.md
=> Update doc for alter storage unit

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/engine/type/broadcast/BroadcastInstanceBroadcastRoutingEngine.java, infra/common/src/main/java/org/apache/shardingsphere/infra/lock/GlobalLockNames.java, kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/StatisticsCollectJob.java, kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/StatisticsCollectJobWorker.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/ShardingSphereStatisticsRefreshEngine.java, mode/core/src/test/java/org/apache/shardingsphere/mode/fixture/StatisticsCollectorFixture.java, mode/core/src/test/java/org/apache/shardingsphere/mode/metadata/refresher/ShardingSphereStatisticsRefreshEngineTest.java, mode/core/src/test/resources/META-INF/services/org.apache.shardingsphere.infra.metadata.statistics.collector.ShardingSphereStatisticsCollector, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/event/subscriber/dispatch/ListenerAssistedSubscriber.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/event/subscriber/dispatch/ResourceMetaDataChangedSubscriber.java
Fixes #31988.
- rigger metadata collection when creating and deleting database and table
---
=> Trigger metadata collection when creating and deleting database and table

test/it/parser/src/main/resources/case/ddl/alter-profile.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-profile.xml
Fixes #20395.
support parse alter profile add test cases
---
=> support parse alter profile(#20395)

infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/metadata/data/loader/MySQLMetaDataLoader.java
=> Avoid syntax error when loading index meta data for MySQL

examples/shardingsphere-jdbc-example-generator/src/main/resources/template/java/config/Configuration.ftl
Fixes #32050 
- refactor import package AlgorithmConfiguration in the examples\shardingsphere-jdbc-example-generator\src\main\resources\template\java\config\Configuration.ftl
=> fix: import package AlgorithmConfiguration in Configuration.ftl

docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/encrypt.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/encrypt.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/mask.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/mask.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/shadow.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/shadow.en.md
Fixes #32052
- changed AlgorithmConfiguration full class name in docs
=> fix: changed AlgorithmConfiguration full class name in docs

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/collector/ShardingSphereTableDataCollectorUtils.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/collector/tables/PgClassTableCollector.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/collector/tables/PgNamespaceTableCollector.java
Fixes #32065.
- Refactor data collection for pg_namespace and pg_class tables
---
=> Refactor data collection for pg_namespace and pg_class tables

test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml
Fixes #31550.
-
- I've verified that the SQL queries using certain MySQL functions mentioned in issue #31550 can be parsed by the parser.
- I have added the corresponding SQL cases and case assertions.
---
=> Verify the functions mentioned in issue #31550 and add test cases

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/manager/SystemSchemaManager.java
=> Optimize SystemSchemaManager.

examples/shardingsphere-parser-example/src/main/java/org/apache/shardingsphere/example/parser/mysql/statement/MySQLParserStatementExample.java, examples/shardingsphere-parser-example/src/main/java/org/apache/shardingsphere/example/parser/opengauss/statement/OpenGaussParserStatementExample.java, examples/shardingsphere-parser-example/src/main/java/org/apache/shardingsphere/example/parser/oracle/statement/OracleParserStatementExample.java, examples/shardingsphere-parser-example/src/main/java/org/apache/shardingsphere/example/parser/sql92/statement/SQL92ParserStatementExample.java, examples/shardingsphere-parser-example/src/main/java/org/apache/shardingsphere/example/parser/sqlserver/statement/SQLServerParserStatementExample.java, infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json
Fixes https://github.com/apache/shardingsphere/actions/runs/9929761811/job/27427724413 .
- Fixes Example nightly CI failing due to class changes.
- Also fixes https://github.com/apache/shardingsphere/actions/runs/9929761811/job/27427724148 . Fixes nativeTest failure under GraalVM Native Image due to class information changes.
---
=> Fixes Example nightly CI failing due to class changes

features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/query/ShowEncryptRuleExecutor.java, features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropEncryptRuleExecutor.java, features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/query/ShowEncryptRuleExecutorTest.java, features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropEncryptRuleExecutorTest.java
=> Make encrypt syntax consistent with upper and lower case

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/exception/MissingRequiredPrivilegeException.java, infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/exception/MissingRequiredUserException.java, infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/exception/UnexpectedVariableValueException.java, infra/database/type/h2/src/main/java/org/apache/shardingsphere/infra/database/h2/checker/H2DatabaseEnvironmentChecker.java, infra/database/type/h2/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.database.core.checker.DialectDatabaseEnvironmentChecker, infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/checker/OpenGaussDatabaseEnvironmentChecker.java, infra/database/type/opengauss/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.database.core.checker.DialectDatabaseEnvironmentChecker, infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/checker/PostgreSQLDatabaseEnvironmentChecker.java, infra/database/type/postgresql/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.database.core.checker.DialectDatabaseEnvironmentChecker
=> Add database environment checker for PG/OG/H2

infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/checker/MySQLDatabaseEnvironmentChecker.java
https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&id=apache_shardingsphere&open=AZC__DT5E2jmg_bqISsy
=> Fix sonar issue, use EnumMap in MySQLDatabaseEnvironmentChecker

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/manager/SystemSchemaManager.java
- Fix column count assert exception caused by postgresql system table judge
---
=> Fix column count assert exception caused by postgresql system table judge

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereSchema.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/update/rdl/rule/engine/database/type/AlterDatabaseRuleOperator.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/update/rdl/rule/engine/database/type/CreateDatabaseRuleOperator.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/update/rdl/rule/engine/database/type/DropDatabaseRuleOperator.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/rdl/resource/AlterStorageUnitExecutor.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/rdl/resource/RegisterStorageUnitExecutor.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/rdl/resource/UnregisterStorageUnitExecutor.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/MetaDataPersistService.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/database/DatabaseMetaDataPersistService.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/MetaDataContextManager.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/MetaDataContextsFactory.java, mode/core/src/main/java/org/apache/shardingsphere/mode/persist/service/MetaDataManagerPersistService.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/event/builder/ListenerAssistedDispatchEventBuilder.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/persist/ClusterMetaDataManagerPersistService.java, mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/persist/StandaloneMetaDataManagerPersistService.java
refer https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&id=apache_shardingsphere&open=AZCmBqbLxBCtCIlvmvWd
=> Fix sonar issue, use different methods to instead of isDropConfig

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/exception/CheckDatabaseEnvironmentFailedException.java, infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/exception/MissingRequiredPrivilegeException.java, infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/exception/MissingRequiredUserException.java, infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/checker/MySQLDatabaseEnvironmentChecker.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/rdl/resource/AlterStorageUnitExecutor.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/rdl/resource/RegisterStorageUnitExecutor.java
=> Add SELECT privilege check for MySQL when register or alter storage unit

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContext.java
- Add JoinTableSegment us all subquery table judge logic in SelectStatementContext#containsTableSubquery
---
=> Add JoinTableSegment us all subquery table judge logic in SelectStatementContext#containsTableSubquery

docs/document/content/reference/encrypt/_index.cn.md, docs/document/content/reference/encrypt/_index.en.md, docs/document/content/user-manual/common-config/builtin-algorithm/encrypt.cn.md, docs/document/content/user-manual/common-config/builtin-algorithm/encrypt.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/encrypt.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/encrypt.en.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/mix.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/java-api/rules/mix.en.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/encrypt.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/encrypt.en.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/mix.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/mix.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/encrypt/show-encrypt-rule.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/encrypt/show-encrypt-rule.en.md, examples/shardingsphere-jdbc-example-generator/src/main/resources/template/java/config/encrypt.ftl, examples/shardingsphere-jdbc-example-generator/src/main/resources/template/resources/yaml/feature/encrypt.ftl, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/algorithm/standard/AESEncryptAlgorithmTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/it/EncryptRuleConfigurationYamlIT.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rule/EncryptRuleTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/config/ProxyConfigurationLoaderTest.java, proxy/bootstrap/src/main/resources/conf/database-encrypt.yaml, test/it/parser/src/main/resources/case/rdl/alter.xml, test/it/parser/src/main/resources/case/rdl/create.xml, test/native/src/test/resources/test-native/yaml/features/encrypt.yaml
=> Complete the documentation and testing of the code modifications in #32236.

.github/workflows/e2e-agent.yml
- refactor the agent test JDK to 21
---
=> Refactor : refactor the agent test JDK to 21

README.md, README_ZH.md
=> Add : add ci badge in README

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/ddl/column/ColumnDefinitionSegment.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/ddl/table/CreateTableOptionSegment.java
=> Add mysql charset sql parsing

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/cases/dataset/DataSetLoader.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/env/DataSetEnvironmentManager.java
=> Refactor E2E.

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/generator/PipelineDDLGenerator.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/preparer/datasource/PipelineJobDataSourcePreparer.java
=> Fix: fix DDL handling error with semicolon

parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/type/DorisDDLStatementVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/segment/definition/ColumnDefinitionAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/segment/impl/definition/ExpectedColumnDefinition.java, test/it/parser/src/main/resources/case/ddl/create-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml
=> Add mysql column not null sql parsing

kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/StatisticsCollectContextManagerLifecycleListener.java, kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/StatisticsCollectJobWorker.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/event/subscriber/dispatch/ListenerAssistedSubscriber.java, mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/event/subscriber/dispatch/ResourceMetaDataChangedSubscriber.java, proxy/bootstrap/src/main/java/org/apache/shardingsphere/proxy/Bootstrap.java
Fixes #32338.
- Fix the error that the process does not exit after proxy startup fail
---
=> Fix the error that the process does not exit after proxy startup fail

.github/workflows/nightly-ci-dynamic.yml, .github/workflows/nightly-ci.yml, .github/workflows/nightly-e2e-operation-dynamic.yml, .github/workflows/nightly-e2e-sql-dynamic.yml
- add dynamic ci in nightly CI
---
=> Add dynamic matrix workflows

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/EncryptIndexColumnTokenGenerator.java
=> Add table names judgment for EncryptIndexColumnTokenGenerator

.github/workflows/nightly-e2e-operation-dynamic.yml, .github/workflows/nightly-e2e-sql-dynamic.yml
- add dyamic trigger for operation
---
=> Refactor : add dyamic trigger for operation

test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml
=> Improve the parsing of methods in MySQL #31552

.github/workflows/nightly-ci-dynamic.yml, .github/workflows/nightly-e2e-operation-dynamic.yml, .github/workflows/nightly-e2e-sql-dynamic.yml
- fix the incorrect inputs format 
---
=> Fix : fix the incorrect inputs format

.github/workflows/e2e-sql.yml, .github/workflows/nightly-e2e-operation-dynamic.yml, .github/workflows/nightly-e2e-operation.yml, .github/workflows/nightly-e2e-sql-dynamic.yml, .github/workflows/nightly-e2e-sql.yml
- update the timeout for e2e sql
---
=> Refactor : update the timeout for e2e sql

agent/plugins/metrics/core/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/SQLParseCountAdviceTest.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/rql/resource/ShowStorageUnitExecutor.java, infra/distsql-handler/src/test/java/org/apache/shardingsphere/distsql/handler/executor/rql/resource/ShowStorageUnitExecutorTest.java, parser/distsql/engine/src/main/antlr4/imports/RQLStatement.g4, parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java, parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/statement/rql/resource/ShowStorageUnitsStatement.java
=> Add like support for DistSQL show storage units

test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml
=> Improve the parsing of methods in MySQL #31561

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/function/mysql/MySQLBinFunction.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/planner/util/SQLFederationFunctionUtils.java, test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select.xml
Ref #31912.
- Support federated query mysql bin function
---
=> Support federated query mysql bin function

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/env/E2EEnvironmentSetupProcessor.java
=> Refactor E2E environment setup code.

mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/MetaDataContextsFactory.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/decorator/RuleConfigurationPersistDecorateEngine.java
Fix SPI type not match for RuleConfigurationPersistDecorator
=> Refactor RuleConfigurationPersistDecorateEngine

.mvn/jvm.config, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/ShardingDQLResultMergerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/pagination/LimitDecoratorMergedResultTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/merge/dql/pagination/TopAndRowNumberDecoratorMergedResultTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/generator/ShardingRowCountTokenGeneratorTest.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/PaginationContext.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/engine/RowNumberPaginationContextEngine.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/engine/TopPaginationContextEngine.java, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/dml/pagination/NumberLiteralPaginationValueSegment.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/dml/pagination/limit/NumberLiteralLimitValueSegment.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/dml/pagination/rownum/NumberLiteralRowNumberValueSegment.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/cases/value/SQLValue.java, test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select-pagination.xml
=> Support postgresql limit and offset as null

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #32283.
support reserved word parse in parser engine.
---
=> support reserved word parse in parser engine.

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/util/YamlDatabaseConfigurationImportExecutor.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportMetaDataExecutorTest.java
=> Rollback if import database configuration failed

proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/ImportMetaDataExecutorTest.java
=> Revise ImportMetaDataExecutorTest

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/storage-unit-query/show-storage-units.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/storage-unit-query/show-storage-units.en.md
=> Update syntax doc for show storage units

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/storage-unit-query/show-storage-units.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/storage-unit-query/show-storage-units.en.md, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rql/impl/ShowStorageUnitsStatementAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rql/storage/unit/ShowStorageUnitsStatementTestCase.java, test/it/parser/src/main/resources/case/rql/show.xml, test/it/parser/src/main/resources/sql/supported/rql/show.xml
For #32387.
- update syntax doc
- add parser test case
=> Add parser test case for show storage unit with like

kernel/single/core/src/main/java/org/apache/shardingsphere/single/decorator/SingleRuleConfigurationDecorator.java
=> For #32487, fix load single table error after creating logical data source

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/AdditionalDMLE2EIT.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/BaseDMLE2EIT.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/BatchDMLE2EIT.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/GeneralDMLE2EIT.java
=> Add DML E2E support init and destory sql

kernel/single/core/src/main/java/org/apache/shardingsphere/single/decorator/SingleRuleConfigurationDecorator.java
https://sonarcloud.io/project/issues?sinceLeakPeriod=true2CCONFIRMED&id=apache_shardingsphere&open=AZFK0SaoY_WmmT5Uxq9X
=> Fix sonar issue for SingleRuleConfigurationDecorator

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/incremental/CreateIncrementalDumperParameter.java
Reverts apache/shardingsphere#32514
=> Revert "Remove useless CreateIncrementalDumperParameter.dataSourceManager"

pom.xml, test/e2e/sql/pom.xml
=> Fix E2E in java 21.

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dml/AdditionalDMLE2EIT.java
=> Add the override annotation above tearDown method

jdbc/src/main/java/org/apache/shardingsphere/driver/ShardingSphereDriver.java
- Remove unused method from ShardingSphereDriver
---
=> Remove unused method from ShardingSphereDriver

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContext.java
=> Fix no database selected exception in the query sql(#32498)

proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/information/SelectInformationSchemataExecutor.java
=> Fix duplicate results when querying information_schema.SCHEMATA

infra/algorithm/type/cryptographic/core/pom.xml, infra/algorithm/type/cryptographic/core/src/main/java/org/apache/shardingsphere/infra/algorithm/cryptographic/core/CryptographicAlgorithm.java, infra/algorithm/type/cryptographic/pom.xml, infra/algorithm/type/cryptographic/type/aes/pom.xml, infra/algorithm/type/cryptographic/type/aes/src/main/java/org/apache/shardingsphere/infra/algorithm/cryptographic/aes/AESCryptographicAlgorithm.java, infra/algorithm/type/cryptographic/type/aes/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.algorithm.cryptographic.core.CryptographicAlgorithm, infra/algorithm/type/cryptographic/type/aes/src/test/java/org/apache/shardingsphere/infra/algorithm/cryptographic/aes/AESCryptographicAlgorithmTest.java, infra/algorithm/type/cryptographic/type/pom.xml
- Add new cryptographic module and add aes cryptographic algorithm
---
=> Add new cryptographic module and add aes cryptographic algorithm

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
Fixes #32548.
- Fix oracle nvl function and interval hour parse error
---
=> Fix oracle nvl function and interval hour parse error

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/ITContainers.java
=> Fix host resolve in postgresql e2e.

kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/MySQLBinlogClient.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZFVwQvKaRYUm-iCaxCl
=> Fix sonar issue on MySQLBinlogClient

features/encrypt/core/pom.xml, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/standard/AESEncryptAlgorithm.java
- Use AESCryptographicAlgorithm in AESEncryptAlgorithm to reduce duplicate code
---
=> Use AESCryptographicAlgorithm in AESEncryptAlgorithm to reduce duplicate code

kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/incremental/binlog/event/rows/MySQLBaseRowsBinlogEvent.java
Fixes https://sonarcloud.io/project/issues?open=AZFgsoIo7hRxvh0Oj2fe&id=apache_shardingsphere
=> Fix sonar issue on MySQLBaseRowsBinlogEvent

test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/commons/TestShardingService.java, test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/commons/repository/AddressRepository.java
Fixes https://sonarcloud.io/project/issues?open=AZFasRWj9EzvBGpT3JoL&id=apache_shardingsphere .
- Removes utility functions that are no longer used due to ClickHouse's nativeTest refactoring.
---
=> Removes utility functions that are no longer used due to ClickHouse's nativeTest refactoring

infra/common/src/test/java/org/apache/shardingsphere/infra/hint/SQLHintUtilsTest.java
Fixes: https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZEDlT293j69GRluxZ3d
=> Fix sonar issue on SQLHintUtilsTest

test/e2e/env/pom.xml, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/MySQLContainer.java
=> Add MySQLContainer startup timeout.

mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/util/TableRefreshUtils.java
=> Optimize TableRefreshUtils.

agent/plugins/core/src/test/java/org/apache/shardingsphere/agent/plugin/core/recorder/MethodTimeRecorderTest.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&2CCONFIRMED&id=apache_shardingsphere&open=AZFy8W38J4tBkJIFaick
=> Fix sonar issue on MethodTimeRecorderTest

agent/core/src/test/java/org/apache/shardingsphere/agent/core/advisor/config/yaml/fixture/YamlTargetObjectFixture.java, agent/core/src/test/java/org/apache/shardingsphere/fixture/targeted/TargetObjectFixture.java
Fixes https://sonarcloud.io/project/issues?id=apache_shardingsphere&open=AY919vFO1K9nhkXZ7x_f
=> Fix sonar issue on YamlTargetObjectFixture

.github/workflows/nightly-e2e-operation.yml
- remove the mariadb from operation daily
---
=> Refactor : remove the mariadb from operation daily

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/InventoryDumper.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZFy8WYiJ4tBkJIFaicg
=> Fix sonar issue on InventoryDumper

infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/rql/resource/ShowLogicalTableExecutor.java, infra/distsql-handler/src/test/java/org/apache/shardingsphere/distsql/handler/executor/rql/resource/ShowLogicalTableExecutorTest.java, infra/distsql-handler/src/test/java/org/apache/shardingsphere/distsql/handler/executor/rql/resource/ShowStorageUnitExecutorTest.java, parser/distsql/engine/src/main/antlr4/imports/Keyword.g4, parser/distsql/engine/src/main/antlr4/imports/RQLStatement.g4, parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java, parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/statement/rql/resource/ShowLogicalTablesStatement.java, proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowTablesExecutor.java, test/it/parser/src/main/resources/case/rql/show.xml, test/it/parser/src/main/resources/sql/supported/rql/show.xml
=> Improve show logical tables, add table type to result set

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/InventoryDumper.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/sql/PipelineInventoryDumpSQLBuilder.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/PipelineInventoryDumpSQLBuilderTest.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZFy8WZ3J4tBkJIFaich&tab=code
=> Fix sonar issue on PipelineInventoryDumpSQLBuilder

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxySQLExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/session/ConnectionSession.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnectorFactoryTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnectorTest.java
=> Fix NPE when no database is specified(#32637)

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/execute/ShardingTotalCountUsageJobExecutorServiceHandler.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/service/PipelineJobConfigurationManager.java, kernel/data-pipeline/core/src/main/resources/META-INF/services/org.apache.shardingsphere.elasticjob.infra.handler.threadpool.JobExecutorServiceHandler, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/PipelineDataConsistencyCalculateSQLBuilderTest.java
- Add SHARDING_TOTAL_COUNT impl of JobExecutorServiceHandler to improve CPU core requirement
---
=> Add SHARDING_TOTAL_COUNT impl of JobExecutorServiceHandler to improve CPU core requirement

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/loader/StandardPipelineTableMetaDataLoader.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/model/PipelineIndexMetaData.java
- Pipeline metadata loader use case-insensitive key
---
=> Pipeline metadata loader use case-insensitive key

.github/workflows/resources/scripts/unit-test-coverage-merge/code-coverage-merge.sh
-Added HTML path on script to fit request
-Generate HTML by jacocoCli
---
=> Added HTML path for Request

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/InventoryDumper.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/sql/BuildDivisibleSQLParameter.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/sql/PipelineInventoryDumpSQLBuilder.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/result/RecordSingleTableInventoryCalculatedResultTest.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/PipelineInventoryDumpSQLBuilderTest.java, test/it/pipeline/src/test/java/org/apache/shardingsphere/test/it/data/pipeline/core/consistencycheck/table/calculator/RecordSingleTableInventoryCalculatorTest.java
- Fix sonar issue for pipeline
---
=> Fix sonar issue for pipeline

test/it/spi/src/test/java/org/apache/shardingsphere/test/it/spi/SPIMatchedCheckIT.java
- SPIMatchedCheckIT compatible with jar path
---
=> SPIMatchedCheckIT compatible with jar path

test/it/spi/src/test/java/org/apache/shardingsphere/test/it/spi/SPIMatchedCheckIT.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZGEv9IS8LWSi8bCpSH8
=> Fix sonar issue on SPIMatchedCheckIT

parser/sql/statement/core/src/test/java/org/apache/shardingsphere/sql/parser/statement/core/util/SubqueryExtractUtilsTest.java
https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZA6FVz5zLaB748UMiGx&tab=code
=> Fix sonar issue on SubqueryExtractUtilsTest

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxySQLExecutor.java
=> Fix no database selected exception in the query sql

.github/workflows/nightly-check.yml
- update the sonarcloud coverage report
---
=> Refactor : update the sonarcloud coverage report

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/dml/expr/FunctionSegment.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZGMshOJQ4zOCu9F2juF&tab=code
=> Fix sonar issue on MySQLStatementVisitor

.github/workflows/nightly-check.yml
- update the JDK version for sonar coverage
---
=> Refactor : update the JDK version for sonar coverage

agent/plugins/metrics/core/src/test/java/org/apache/shardingsphere/agent/plugin/metrics/core/advice/SQLParseCountAdviceTest.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/rql/resource/ShowStorageUnitExecutor.java, infra/distsql-handler/src/test/java/org/apache/shardingsphere/distsql/handler/executor/rql/resource/ShowStorageUnitExecutorTest.java, parser/distsql/engine/src/main/antlr4/imports/Keyword.g4, parser/distsql/engine/src/main/antlr4/imports/RQLStatement.g4, parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java, parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/statement/rql/resource/ShowStorageUnitsStatement.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/rql/impl/ShowStorageUnitsStatementAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/rql/storage/unit/ShowStorageUnitsStatementTestCase.java, test/it/parser/src/main/resources/case/rql/show.xml, test/it/parser/src/main/resources/sql/supported/rql/show.xml
Related to #21671
- Remove the useless usageCount, which does little but complicates the code
After refactoring, it works well
=> Remove usageCount from showStorageUnits

.github/workflows/nightly-check.yml
- update sonar coverage token
---
=> Refactor : update sonar coverage token

infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/rql/resource/ShowLogicalTableExecutor.java, proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/executor/ShowTablesExecutor.java
=> Optimize the way to obtain like pattern in ShowTablesExecutor

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertValuesTokenGenerator.java
=> Copy value expressions when creating an insert value

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/AbstractSeparablePipelineJob.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/TransmissionJobItemProgress.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/job/progress/yaml/swapper/YamlTransmissionJobItemProgressSwapper.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/job/progress/PipelineJobProgressDetectorTest.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/api/CDCJobAPI.java
Reverts apache/shardingsphere#32736
=> Revert "Refactor TransmissionJobItemProgress"

README.md, README_ZH.md
Fixes #26521.
- Add Geographical Distribution of Star, Pull Request Creator and Issue Creator in README. Image source: PingCAP. The README of `apache/superset` also uses PingCAP images.
- For more configuration items, refer to,
- https://next.ossinsight.io/widgets/official/analyze-repo-stars-map?activity=stars&repo_id=49876476
- https://next.ossinsight.io/widgets/official/analyze-repo-stars-map?activity=pull-request-creators&repo_id=49876476
- https://next.ossinsight.io/widgets/official/analyze-repo-stars-map?activity=issue-creators&repo_id=49876476
- Markdown doesn’t seem to support CSS3 very well, and the flexible box model doesn’t work in Markdown, so I used HTML tags directly.
- ![image](https://github.com/user-attachments/assets/24f1df1f-5fe2-4cd …
=> Add Geographical Distribution of Star, Pull Request Creator and Issue Creator in README

features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/query/ShowMaskRuleExecutor.java, features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/update/DropMaskRuleExecutor.java, features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/query/ShowMaskRuleExecutorTest.java, features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/update/DropMaskRuleExecutorTest.java
=> Make mask syntax consistent with upper and lower case

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/InsertStatementContext.java
=> Fix sonar issue of InsertStatementContext

.github/workflows/nightly-check.yml
- add swap to sonar checkstyle
---
=> Add : add swap to sonar checkstyle

.github/workflows/nightly-check.yml
- update the checkstyle command
---
=> Refactor : update the checkstyle command

.github/workflows/nightly-check.yml
- update the checkstyle action for sonarcloud
---
=> Refactor : update the checkstyle action for sonarcloud

infra/common/src/main/java/org/apache/shardingsphere/infra/instance/ComputeNodeInstanceContext.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZBbZvss7zsW3EZM5xe-
=> Fix sonar issue on ComputeNodeInstanceContext

test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml
Fixes #31564.
- Improve the parsing of methods in MySQL and Doris
---
=> Improve the parsing of methods in MySQL and Doris

mode/type/standalone/core/src/test/java/org/apache/shardingsphere/mode/manager/standalone/persist/StandaloneProcessPersistServiceTest.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZHSNyxgF4dh-Ibq8tr1
=> Fix sonar issue on StandaloneProcessPersistServiceTest

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/pojo/AlterSchemaPOJO.java, mode/type/standalone/core/src/test/java/org/apache/shardingsphere/mode/manager/standalone/persist/StandaloneMetaDataManagerPersistServiceTest.java
=> Add test cases for StandaloneMetaDataManagerPersistService

.github/workflows/nightly-check.yml, .github/workflows/resources/scripts/unit-test-coverage-merge/code-coverage-merge.sh, pom.xml
- update jacoco check workflow
---
=> update jacoco check workflow to avoid useless analysis

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/InsertClauseShardingConditionEngine.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContext.java, test/e2e/sql/src/test/resources/cases/dml/dataset/tbl/batch_insert_all_into_order_table.xml
- Minor refactor for sharding insert clause condition handle logic
---
=> Minor refactor for sharding insert clause condition handle logic

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.en.md, infra/url/core/src/main/java/org/apache/shardingsphere/infra/url/core/arg/URLArgumentLine.java, infra/url/core/src/test/java/org/apache/shardingsphere/infra/url/core/arg/URLArgumentLineTest.java
=> URLArgumentLine to support multiple expressions on the one line

parser/sql/dialect/opengauss/src/main/antlr4/imports/opengauss/DMLStatement.g4, parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java, parser/sql/dialect/postgresql/src/main/antlr4/imports/postgresql/DMLStatement.g4, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java
=> Support cte with postgres and openGauss

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/impl/AbstractSQLBuilder.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/impl/DefaultSQLBuilder.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/impl/RouteSQLBuilder.java
=> Remove duplicate SubstitutableColumnNameToken judgments in SQL Builder

db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/PostgreSQLColumnType.java, db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/text/impl/PostgreSQLTextArrayValueParser.java, db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/text/impl/PostgreSQLVarcharArrayValueParser.java
=> Support array type prepared param in PostgreSQL

test/e2e/env/pom.xml, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/ITContainers.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/AdapterContainerFactory.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/impl/ShardingSphereJdbcContainer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/container/compose/DockerContainerComposer.java, test/e2e/operation/showprocesslist/src/test/java/org/apache/shardingsphere/test/e2e/showprocesslist/container/composer/ClusterShowProcessListContainerComposer.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/framework/container/compose/DockerContainerComposer.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/container/compose/mode/ClusterContainerComposer.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/container/compose/mode/StandaloneContainerComposer.java
=> Refactor ShardingSphereJdbcContainer.

.github/workflows/nightly-check.yml, .github/workflows/schedule-report.yml
- refactor schedule workflow
---
=> Refactor : refactor schedule workflow

mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/persist/ReservationPersistServiceTest.java, mode/type/cluster/repository/api/src/main/java/org/apache/shardingsphere/mode/repository/cluster/lock/impl/DefaultDistributedLock.java, mode/type/cluster/repository/api/src/test/java/org/apache/shardingsphere/mode/repository/cluster/lock/impl/DefaultDistributedLockTest.java
=> Add test cases on DefaultDistributedLock

db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLBinaryProtocolValueFactory.java, db-protocol/postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTextArrayBinaryProtocolValue.java
Fixes #32846.
- Sample of portocol package
=> For #32846, add binary protocol value for text array for PostgreSQL

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/_index.en.md
For #32817.
- Restructures known implementations  documentation for JDBC Driver
---
=> Restructures known implementations  documentation for JDBC Driver

features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/route/ReadwriteSplittingDataSourceRouter.java, features/readwrite-splitting/core/src/test/java/org/apache/shardingsphere/readwritesplitting/route/ReadwriteSplittingDataSourceRouterTest.java
=> Add test cases on ReadwriteSplittingDataSourceRouter

features/shadow/core/src/test/java/org/apache/shardingsphere/shadow/yaml/swapper/YamlShadowRuleConfigurationSwapperTest.java
=> Add test cases on YamlShadowRuleConfigurationSwapperTest

features/readwrite-splitting/core/src/main/java/org/apache/shardingsphere/readwritesplitting/constant/ReadwriteSplittingOrder.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/constant/ShadowOrder.java
=> Modify readwrite-splitting and shadow order

.github/workflows/nightly-build.yml, distribution/agent/Dockerfile, distribution/agent/pom.xml, docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.en.md
For #32777.
- Provides nightly builds on ghcr.io for ShardingSphere Agent.
---
=> Provides nightly builds on ghcr.io for ShardingSphere Agent

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/insert/keygen/engine/GeneratedKeyContextEngine.java
- Minor refactor in GeneratedKeyContextEngine to avoid IndexOutOfBoundException
---
=> Minor refactor in GeneratedKeyContextEngine to avoid IndexOutOfBoundException

kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/function/mysql/impl/MySQLNotFunction.java
Ref #32961.
- Revise code style for MySQLNotFunction
---
=> Revise code style for MySQLNotFunction

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateRightValueTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptPredicateFunctionRightValueToken.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/pojo/EncryptPredicateFunctionRightValueTokenTest.java, test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select-aggregate.xml, test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-where.xml
- Support like concat nested concat statement rewrite with encrypt feature
---
=> Support like concat nested concat statement rewrite with encrypt feature

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/UpdateStatementBinder.java, parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java, parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/DMLStatement.g4, parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/dml/assignment/SetAssignmentSegment.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/dml/UpdateStatement.java, parser/sql/statement/type/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/statement/opengauss/dml/OpenGaussUpdateStatement.java, parser/sql/statement/type/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/statement/postgresql/dml/PostgreSQLUpdateStatement.java, parser/sql/statement/type/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/statement/sqlserver/dml/SQLServerUpdateStatement.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/UpdateStatementAssert.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/dml/UpdateStatementTestCase.java, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/case/dml/update.xml, test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml, test/it/parser/src/main/resources/sql/supported/dml/update.xml
- Support PostgreSQL, openGauss function table and update from parse
---
=> Support PostgreSQL, openGauss function table and update from parse

jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/invocation/MethodInvocationRecorder.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManager.java
=> Fix setSavepoint method invocation not cleaning up

test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/savepoint/OpenGaussSavePointTestCase.java
=> Fix openGauss savepoint test case

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/rule/RuleMetaDataShardingSphereRuleFixture.java, infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/rule/RuleMetaDataTest.java
=> Add test cases on RuleMetaData.getInUsedStorageUnitNameAndRulesMap()

parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/util/SubqueryExtractUtils.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/util/TableExtractor.java
- Support table and subquery extract for more expression segment
---
=> Support table and subquery extract for more expression segment

kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/persist/service/metadata/table/TableMetaDataPersistServiceTest.java, src/resources/checkstyle.xml, test/it/yaml/pom.xml, test/it/yaml/src/main/java/org/apache/shardingsphere/test/it/yaml/YamlRuleConfigurationIT.java, test/util/src/main/java/org/apache/shardingsphere/test/matcher/ShardingSphereArgumentVerifyMatchers.java, test/util/src/main/java/org/apache/shardingsphere/test/matcher/ShardingSphereAssertionMatchers.java, test/util/src/main/java/org/apache/shardingsphere/test/verify/ShardingSphereArgumentMatchers.java
Assertion and verify with deepEquals
=> Upgrade test framework: Add ShardingSphereArgumentMatchers and ShardingSphereAssertionMatchers

RELEASE-NOTES.md
Ref #33063.
- Update release note for shadow sql hint bug
---
=> Update release note for shadow sql hint bug

test/util/src/main/java/org/apache/shardingsphere/test/matcher/ShardingSphereArgumentVerifyMatchers.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZI_NzLBhQFn1NPRZcSf
=> Fix sonar issue of ShardingSphereArgumentVerifyMatchers

.github/workflows/ci.yml, .github/workflows/e2e-agent.yml, .github/workflows/e2e-sql.yml, .github/workflows/nightly-build.yml, .github/workflows/nightly-check.yml, .github/workflows/nightly-ci.yml, .github/workflows/nightly-e2e-operation.yml, .github/workflows/nightly-e2e-sql.yml
- update workflow variables
---
=> Refactor : update workflow variables

kernel/authority/provider/database/src/main/java/org/apache/shardingsphere/authority/provider/database/DatabasePermittedPrivilegeProvider.java
=> Removed inappropriate variable isAnyOtherHost

kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/SetDefaultSingleTableStorageUnitExecutor.java, kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/update/SetDefaultSingleTableStorageUnitExecutorTest.java
=> Refactor SetDefaultSingleTableStorageUnitExecutorTest

kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/query/ShowSingleTablesExecutorTest.java
=> Refactor ShowSingleTablesExecutorTest

kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableExecutor.java, kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableExecutorTest.java, kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/update/SetDefaultSingleTableStorageUnitExecutorTest.java
=> Refactor LoadSingleTableExecutorTest

kernel/sql-translator/distsql/handler/src/test/java/org/apache/shardingsphere/sqltranslator/distsql/handler/update/AlterSQLTranslatorRuleExecutorTest.java, kernel/transaction/distsql/handler/src/main/java/org/apache/shardingsphere/transaction/distsql/handler/update/AlterTransactionRuleExecutor.java, kernel/transaction/distsql/handler/src/test/java/org/apache/shardingsphere/transaction/distsql/handler/fixture/ShardingSphereTransactionManagerFixture.java, kernel/transaction/distsql/handler/src/test/java/org/apache/shardingsphere/transaction/distsql/handler/update/AlterTransactionRuleExecutorTest.java
=> Add AlterTransactionRuleExecutorTest

kernel/global-clock/distsql/handler/src/test/java/org/apache/shardingsphere/globalclock/distsql/handler/query/ShowGlobalClockRuleExecutorTest.java, kernel/global-clock/distsql/handler/src/test/java/org/apache/shardingsphere/globalclock/distsql/handler/update/AlterGlobalClockRuleExecutorTest.java
=> Add more assertions for AlterGlobalClockRuleExecutorTest

kernel/sql-parser/distsql/handler/pom.xml, kernel/sql-parser/distsql/handler/src/test/java/org/apache/shardingsphere/parser/distsql/handler/query/ShowSQLParserRuleExecutorTest.java, kernel/sql-parser/distsql/handler/src/test/java/org/apache/shardingsphere/parser/distsql/handler/update/AlterSQLParserRuleExecutorTest.java
=> Add more assertions for AlterSQLParserRuleExecutorTest

features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/query/ShowBroadcastTableRuleExecutorTest.java, kernel/sql-translator/distsql/handler/src/test/java/org/apache/shardingsphere/sqltranslator/distsql/handler/query/ShowSQLTranslatorRuleExecutorTest.java, kernel/transaction/distsql/handler/src/test/java/org/apache/shardingsphere/transaction/distsql/handler/query/ShowTransactionRuleExecutorTest.java
=> refactor ShowBroadcastTableRuleExecutorTest

features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/update/CreateBroadcastTableRuleExecutor.java, features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/update/CreateBroadcastTableRuleExecutorTest.java, kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/update/SetDefaultSingleTableStorageUnitExecutorTest.java
=> Add test cases of CreateBroadcastTableRuleExecutor

features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/update/DropBroadcastTableRuleExecutor.java, features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/update/CreateBroadcastTableRuleExecutorTest.java, features/broadcast/distsql/handler/src/test/java/org/apache/shardingsphere/broadcast/distsql/handler/update/DropBroadcastTableRuleExecutorTest.java
=> Add test cases of DropBroadcastTableRuleExecutorTest

features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/query/ShowEncryptRuleExecutorTest.java, features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleExecutorTest.java
=> Refactor AlterEncryptRuleExecutorTest

features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/AlterEncryptRuleExecutorTest.java, features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/update/AlterMaskRuleExecutorTest.java
=> Refactor test cases on AlterMaskRuleExecutorTest

features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleExecutorTest.java
=> Refactor test cases on CreateEncryptRuleExecutorTest

features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/CreateEncryptRuleExecutorTest.java, features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/update/CreateMaskRuleExecutorTest.java
=> Refactor test cases on CreateMaskRuleExecutorTest

features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropEncryptRuleExecutorTest.java
=> Refactor test cases on DropEncryptRuleExecutorTest

features/encrypt/distsql/handler/src/test/java/org/apache/shardingsphere/encrypt/distsql/handler/update/DropEncryptRuleExecutorTest.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZJTnLYoZcv_5LtGQ79y
=> Fix sonar issue on DropEncryptRuleExecutorTest

features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowDefaultShardingStrategyExecutorTest.java
=> Refactor ShowDefaultShardingStrategyExecutorTest

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/ShowUnusedShardingKeyGeneratorExecutor.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/query/ShowUnusedShardingKeyGeneratorExecutorTest.java
=> Refactor ShowUnusedShardingKeyGeneratorExecutorTest

infra/data-source-pool/core/src/test/java/org/apache/shardingsphere/infra/datasource/pool/props/domain/DataSourcePoolPropertiesTest.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AY9oceB_FGCA14_jOORA
---
=> Fix sonar issue on DataSourcePoolPropertiesTest

RELEASE-NOTES.md, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/yaml/EncryptRuleConfigurationYamlIT.java
- Minor refactor for EncryptRuleConfigurationYamlIT
---
=> Minor refactor for EncryptRuleConfigurationYamlIT

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/mask/create-mask-rule.en.md
=> Update create-mask-rule.en.md for typo

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/mask/alter-mask-rule.en.md
=> Update alter-mask-rule.en.md for typo

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/mask/drop-mask-rule.en.md
=> Update drop-mask-rule.en.md for typo

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/sharding/show-unused-sharding-key-generators.en.md
=> Update show-unused-sharding-key-generators.en.md for typo

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/sharding/show-sharding-table-rules-used-algorithm.en.md
=> Update show-sharding-table-rules-used-algorithm.en.md for typo

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/sharding/show-sharding-table-rules-used-key-generator.en.md
=> Update show-sharding-table-rules-used-key-generator.en.md for typo

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/sharding/show-sharding-table-rules-used-auditor.en.md
=> Update show-sharding-table-rules-used-auditor.en.md for typo

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow/show-shadow-rule.en.md
=> Update show-shadow-rule.en.md for typo

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow/show-shadow-table-rule.en.md
=> Update show-shadow-table-rule.en.md for typo

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow/show-shadow-algorithm.en.md
=> Update show-shadow-algorithm.en.md for typo

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/shadow/show-default-shadow-algorithm.en.md
=> Update show-default-shadow-algorithm.en.md for typo

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/show-compute-node-mode.en.md
=> Update show-compute-node-mode.en.md for typo

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rul/format-sql.en.md
=> Update format-sql.en.md for typo

examples/shardingsphere-jdbc-example-generator/src/main/resources/template/pom.ftl
Fixes #33177 .
- update lombok version to 1.18.30 in examples/shardingsphere-jdbc-example-generator/src/main/resources/template/pom.ftl
=> update lombok version to 1.18.30 in examples (#33177)

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/EncryptRule.java
- Minor refactor for EncryptRule build RuleAttributes
---
=> Minor refactor for EncryptRule build RuleAttributes

features/encrypt/distsql/handler/src/test/resources/cases/show-encrypt-rules-current-config.yaml, features/encrypt/distsql/handler/src/test/resources/cases/show-encrypt-rules.xml
=> Fix ShowEncryptRuleExecutorTest

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/loader/type/SchemaMetaDataLoader.java, infra/database/type/mysql/src/test/java/org/apache/shardingsphere/infra/database/mysql/metadata/data/loader/MySQLSchemaMetaDataLoaderTest.java, infra/database/type/opengauss/src/test/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussSchemaMetaDataLoaderTest.java, infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLSchemaMetaDataLoaderTest.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/datanode/SingleTableDataNodeLoader.java, kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableExecutor.java
- Minor refactor SchemaMetaDataLoader to add excludedTables filter logic
---
=> Minor refactor SchemaMetaDataLoader to add excludedTables filter logic

distribution/proxy/src/main/release-docs/LICENSE
=> Refactor : update the license file

docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/alter-storage-unit.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/alter-storage-unit.en.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/register-storage-unit.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/register-storage-unit.en.md
=> Update docs for storage unit RDL

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java
=> Fix is need accumulate logic

RELEASE-NOTES.md
- Update release note for 5.1.1 version which related to sql parser, sql federation, sharding and encrypt
---
=> Update release note for 5.1.1 version which related to sql parser, sql federation, sharding and encrypt

RELEASE-NOTES.md
- Update 5.1.1 release note for pr #32395
---
=> Update 5.5.1 release note for pr#32395

docs/document/content/user-manual/shardingsphere-proxy/yaml-config/authority.cn.md, docs/document/content/user-manual/shardingsphere-proxy/yaml-config/authority.en.md, kernel/authority/provider/simple/src/main/java/org/apache/shardingsphere/authority/provider/simple/AllPermittedPrivilegeProvider.java
=> Mark ALL_PERMITTED privilege provider as deprecated

kernel/single/core/src/main/java/org/apache/shardingsphere/single/rule/SingleRule.java
=> Modify dataSourceName property of SingleRule to use CaseInsensitiveSet

.github/workflows/resources/scripts/unit-test-coverage-merge/code-coverage-merge.sh
- refactor jacoco aggregation directories
---
=> Refactor : refactor jacoco aggregation directories

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/context/EncryptSQLRewriteContextDecorator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptInsertPredicateParameterRewriter.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptInsertPredicateColumnTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptInsertPredicateRightValueTokenGenerator.java
- https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&sinceLeakPeriod=true&id=apache_shardingsphere
---
=> Remove useless WhereAvailable cast in encrypt rewrite token generator

.github/workflows/ci.yml, .github/workflows/e2e-agent.yml, .github/workflows/e2e-operation.yml, .github/workflows/e2e-sql.yml
- refactor the trigger and variables in PR workflow
---
=> Refactor : refactor the trigger and variables in PR workflow

RELEASE-NOTES.md
- Refactor release note doc
---
=> Refactor release note doc

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/StorageContainerFactory.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/runtime/cluster/ClusterEnvironment.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/container/compose/mode/ClusterContainerComposer.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/container/compose/mode/StandaloneContainerComposer.java, test/e2e/sql/src/test/resources/env/it-env.properties
=> support alter database image in e2e.

docs/document/content/user-manual/shardingsphere-proxy/session/_index.cn.md, docs/document/content/user-manual/shardingsphere-proxy/session/_index.en.md
=> Add kill query documentation

infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/common/pojo/generic/SubstitutableColumnNameToken.java
=> Remove unnecessary toLowercase when using CaseInsensitiveMap

docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/observability/_index.en.md, docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md, docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
- update the rest 5.5.1-SNAPSHOT in documents
---
=> Refactor : update the rest 5.5.1-SNAPSHOT in documents

docs/community/content/involved/release/elasticjob-ui.cn.md, docs/community/content/involved/release/elasticjob-ui.en.md, docs/community/content/involved/release/elasticjob.cn.md, docs/community/content/involved/release/elasticjob.en.md, docs/community/content/involved/release/shardingsphere-on-cloud.cn.md, docs/community/content/involved/release/shardingsphere-on-cloud.en.md, docs/community/content/involved/release/shardingsphere.cn.md, docs/community/content/involved/release/shardingsphere.en.md
- update the release document
---
=> update the release document

parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/generic/bound/ColumnSegmentBoundInfo.java
=> ColumnSegmentBoundedInfo avoids returning null values.

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGenerator.java
=> Refactor EncryptProjectionTokenGenerator.

RELEASE-NOTES.md
=> Add release note for #33357

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/expression/type/ColumnSegmentBinder.java
=> Refactor ColumnSegmentBinder.

RELEASE-NOTES.md, infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/context/ExecutionContextBuilderTest.java, infra/route/src/main/java/org/apache/shardingsphere/infra/route/context/RouteUnit.java, infra/route/src/test/java/org/apache/shardingsphere/infra/route/context/RouteUnitTest.java
=> Add arguments not null check when creating RouteUnit

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/ddl/EncryptCreateTableTokenGenerator.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/ddl/EncryptAlterTableTokenGeneratorTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/ddl/EncryptCreateTableTokenGeneratorTest.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/common/pojo/generic/ColumnDefinitionToken.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/common/pojo/generic/SubstituteColumnDefinitionToken.java, parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/type/DorisDDLStatementVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor.java, parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/type/OpenGaussDDLStatementVisitor.java, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/type/PostgreSQLDDLStatementVisitor.java, parser/sql/dialect/presto/src/main/java/org/apache/shardingsphere/sql/parser/presto/visitor/statement/type/PrestoDDLStatementVisitor.java, parser/sql/dialect/sql92/src/main/java/org/apache/shardingsphere/sql/parser/sql92/visitor/statement/type/SQL92DDLStatementVisitor.java, parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/type/SQLServerDDLStatementVisitor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/ddl/column/ColumnDefinitionSegment.java, test/it/rewriter/src/test/resources/scenario/mix/case/query-with-cipher/ddl/create/create-table.xml
=> Refactor encrypt rewrite to use SubstituteColumnDefinitionToken

kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/pojo/PipelineJobMetaDataTest.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZLC-UYxC_93LIKjmP1B
=> Fix sonar issue on PipelineJobMetaDataTest

RELEASE-NOTES.md
=> Add RELEASE-NOTES.

features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/constant/BroadcastDistSQLConstants.java, features/broadcast/distsql/handler/src/main/java/org/apache/shardingsphere/broadcast/distsql/handler/converter/BroadcastRuleConfigurationToDistSQLConverter.java, features/encrypt/distsql/handler/src/main/java/org/apache/shardingsphere/encrypt/distsql/handler/converter/EncryptRuleConfigurationToDistSQLConverter.java, features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/constant/MaskDistSQLConstants.java, features/mask/distsql/handler/src/main/java/org/apache/shardingsphere/mask/distsql/handler/converter/MaskRuleConfigurationToDistSQLConverter.java, features/mask/distsql/handler/src/test/java/org/apache/shardingsphere/mask/distsql/handler/converter/MaskRuleConfigurationToDistSQLConverterTest.java, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/converter/ReadwriteSplittingRuleConfigurationToDistSQLConverter.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/constant/ShadowDistSQLConstants.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/converter/ShadowRuleConfigurationToDistSQLConverter.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/constant/ShardingDistSQLConstants.java, features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/converter/ShardingRuleConfigurationToDistSQLConverter.java, kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/constant/SingleDistSQLConstants.java, kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/converter/SingleRuleConfigurationToDistSQLConverter.java, kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/converter/SingleRuleConfigurationToDistSQLConverterTest.java
Refactor:
- BroadcastRuleConfigurationToDistSQLConverter
- MaskRuleConfigurationToDistSQLConverter
- SingleRuleConfigurationToDistSQLConverter
=> Refactor DistSQL converter

infra/context/src/main/java/org/apache/shardingsphere/infra/connection/kernel/KernelProcessor.java, infra/context/src/test/java/org/apache/shardingsphere/infra/connection/kernel/KernelProcessorTest.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/SQLRewriteEntry.java, infra/rewrite/src/test/java/org/apache/shardingsphere/infra/rewrite/SQLRewriteEntryTest.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/DriverExecuteExecutor.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/DriverExecuteUpdateExecutor.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/batch/preparedstatement/DriverExecuteBatchExecutor.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/pushdown/jdbc/DriverJDBCPushDownExecuteQueryExecutor.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/pushdown/raw/DriverRawPushDownExecuteQueryExecutor.java, kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/PreviewExecutor.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java, proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutor.java, proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutor.java, test/it/rewriter/src/test/java/org/apache/shardingsphere/test/it/rewrite/engine/SQLRewriterIT.java
- https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&id=apache_shardingsphere&open=AZLbeFLHoiIh8xF0VXna
---
=> Fix sonar issue for useless connectionContext parameter

RELEASE-NOTES.md, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByMemoryMergedResult.java, test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select-group-by.xml
Ref #33380.
- Revise pr#33380 codestyle and update release note
---
=> Revise pr#33380 codestyle and update release note

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/groupby/GroupByMemoryMergedResult.java
- https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&id=apache_shardingsphere&open=AZLgdxWru7hJZVSc4JP1
---
=> Fix sonar issue in GroupByMemoryMergedResult

.github/workflows/nightly-check.yml, .github/workflows/nightly-ci-dynamic.yml, .github/workflows/required-check.yml
- update the workflow and remove some useless condition
---
=> Refactor workflow

.github/workflows/nightly-check.yml
- refactor the nightly check workflow
---
=> Refactor : refactor the nightly check workflow

.github/workflows/graalvm.yml
- add dispatch for graalvm workflow
---
=> Refactor : add dispatch for graalvm workflow

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/BroadcastSQLRouter.java, features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/engine/type/broadcast/BroadcastDatabaseBroadcastRouteEngine.java
This reverts commit 2b7ded0ca497fc8ca12cc3bcacc98399e2e27e8e.
-
---
=> Revert "Refactor BroadcastDatabaseBroadcastRouteEngine (#33508)"

test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/features/ShardingTest.java, test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/transactions/xa/AtomikosTest.java, test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/transactions/xa/NarayanaTest.java
This reverts commit d658d874b33da5b722bac09e468f44ce796310d2.
-
---
=> Revert "Disable failed test cases (#33512)"

features/broadcast/core/src/main/java/org/apache/shardingsphere/broadcast/route/BroadcastSQLRouter.java
=> Refactor broadcast sql router

infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reflect-config.json, infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/resource-config.json
Fixes https://github.com/apache/shardingsphere/actions/runs/11651587827/job/32441740762 .
- Fixes nativeTest failing under GraalVM Native Image due to class changes.
---
=> Fixes nativeTest failing under GraalVM Native Image due to class changes

proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/protocol/FrontDatabaseProtocolTypeFactory.java
=> Refactor FrontDatabaseProtocolTypeFactory.

features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/AlterReadwriteSplittingRuleExecutor.java, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/update/UnusedAlgorithmFinder.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/update/rdl/rule/engine/database/type/AlterDatabaseRuleOperator.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/update/rdl/rule/spi/database/DatabaseRuleAlterExecutor.java
- Add unused algorithm finder for readwrite-splitting
- Refactor AlterDatabaseRuleOperator
=> Add unused algorithm finder for readwrite-splitting

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/InventoryDumper.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/NormalColumn.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/group/DataRecordGroupEngine.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/DataRecordTest.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/RecordUtilsTest.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/ingest/record/group/DataRecordGroupEngineTest.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/sql/PipelineImportSQLBuilderTest.java, kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/incremental/dumper/MySQLIncrementalDumper.java, kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/sqlbuilder/MySQLPipelineSQLBuilderTest.java, kernel/data-pipeline/dialect/opengauss/src/test/java/org/apache/shardingsphere/data/pipeline/opengauss/sqlbuilder/OpenGaussPipelineSQLBuilderTest.java, kernel/data-pipeline/dialect/postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/ingest/incremental/wal/WALEventConverter.java, kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/sqlbuilder/PostgreSQLPipelineSQLBuilderTest.java, kernel/data-pipeline/scenario/cdc/core/src/test/java/org/apache/shardingsphere/data/pipeline/cdc/util/DataRecordResultConvertUtilsTest.java, test/it/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/importer/sink/type/PipelineDataSourceSinkTest.java
=> Refactor pipeline Column.

.github/workflows/nightly-check.yml
- add duplicated label to stale plugin
---
=> Add duplicated label to stale plugin

.github/workflows/nightly-ci-dynamic.yml
- refactor dynamic workflow
---
=> Refactor dynamic workflow

.github/workflows/nightly-check.yml
- update the timeout for dependencies check
---
=> Refactor : update the timeout for dependencies check

kernel/transaction/type/xa/core/pom.xml, kernel/transaction/type/xa/core/src/test/java/org/apache/shardingsphere/transaction/xa/jta/connection/dialect/MySQLXAConnectionWrapperTest.java, kernel/transaction/type/xa/core/src/test/java/org/apache/shardingsphere/transaction/xa/jta/connection/dialect/OracleXAConnectionWrapperTest.java
Fixes #20369.
- Added the Test Class for OracleXaConnectionWrapper
- Added Oracle driver in Pom
=> Test cases for oracle xa connection wrapper

.github/workflows/resources/scripts/unit-test-coverage-merge/code-coverage-merge.sh, .github/workflows/schedule-report.yml
- optimized the jacoco workflow
---
=> Refactor : optimized the jacoco workflow

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGenerator.java
=> Add with subquery type to generate table subquery projections

README.md, README_ZH.md
- update the used count in README
---
=> Document : update the used count in README

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGenerator.java
=> Add shorthand projection isNeedRewrite judgement

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTable.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/identifier/DatabaseDialectMetaDataIdentifierHandler.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/identifier/ShardingSphereMetaDataIdentifier.java, kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java, kernel/sql-federation/executor/src/test/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutorTest.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java
=> Add ShardingSphereMetaDataIdentifier and try to use in ShardingSphereTable.columns

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/DialectDatabaseMetaData.java, infra/database/type/firebird/src/main/java/org/apache/shardingsphere/infra/database/firebird/metadata/database/FirebirdDatabaseMetaData.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/pushdown/jdbc/DriverJDBCPushDownExecuteExecutor.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/pushdown/jdbc/DriverJDBCPushDownExecuteUpdateExecutor.java
=> Add DialectDatabaseMetaData.isDDLNeedImplicitCommit() to decouple Firebrid database type in driver module

.github/workflows/nightly-check.yml, .github/workflows/schedule-report.yml, pom.xml
- refactor the jacoco switch
---
=> Refactor : refactor the jacoco switch

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/ShardingInsertValuesTokenGenerator.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/ShardingInsertValuesTokenGeneratorTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/ShardingInsertValuesTokenTest.java, infra/rewrite/src/main/java/org/apache/shardingsphere/infra/rewrite/sql/token/common/pojo/generic/InsertValue.java
=> Add insert values not empty judgement and test

.github/workflows/nightly-check.yml
=> Refactor : refactor the workflow

parser/sql/statement/type/firebird/src/main/java/org/apache/shardingsphere/sql/parser/statement/firebird/dml/FirebirdSelectStatement.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/MySQLCommandExecuteEngine.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/ServerStatusFlagCalculator.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/admin/MySQLComResetConnectionExecutor.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/admin/MySQLComSetOptionExecutor.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/admin/initdb/MySQLComInitDbExecutor.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/admin/ping/MySQLComPingExecutor.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/execute/MySQLComStmtExecuteExecutor.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareExecutor.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/reset/MySQLComStmtResetExecutor.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/fieldlist/MySQLComFieldListPacketExecutor.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLComQueryPacketExecutor.java, proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/ServerStatusFlagCalculatorTest.java
- https://sonarcloud.io/project/issues?open=AZNdeZLu6C2c-2KuIIy7&id=apache_shardingsphere
- https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&id=apache_shardingsphere&open=AZNi1RbDS5UJN9ZHyjdv
---
=> Fix sonar issue for FirebirdSelectStatement and ServerStatusFlagCalculator

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGenerator.java
=> Fix duplicated like rewrite columns

.github/workflows/nightly-sql-parser.yml
- fix a workflow naming issue
---
=> Fix : fix a workflow naming issue

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/env/E2EEnvironmentEngine.java
=> Refactor E2EEnvironmentEngine.

.github/workflows/nightly-check.yml, .github/workflows/schedule-report.yml
=> Refactor : refactor the key name

.github/workflows/schedule-report.yml
- update the hashFiles content for report
---
=> Refactor : update the hashFiles content for report

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/ShardingSQLRouter.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/ShardingRouteContextChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/ShardingRouteContextCheckerFactory.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingAlterTableRouteContextChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingCreateTableRouteContextChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingCreateViewRouteContextChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingDropIndexRouteContextChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingDropTableRouteContextChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingPrepareRouteContextChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingRenameTableRouteContextChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/dml/ShardingDeleteRouteContextChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/dml/ShardingInsertRouteContextChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/dml/ShardingUpdateRouteContextChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/util/ShardingRouteContextCheckUtils.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingAlterTableRouteContextCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingCreateTableRouteContextCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingCreateViewRouteContextCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingDropIndexRouteContextCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingDropTableRouteContextCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingPrepareRouteContextCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingRenameTableRouteContextCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/checker/dml/ShardingInsertRouteContextCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/checker/dml/ShardingUpdateRouteContextCheckerTest.java
Ref #33811.
- Refactor ShardingStatementValidator to ShardingRouteContextChecker
---
=> Refactor ShardingStatementValidator to ShardingRouteContextChecker

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/comparator/EncryptorComparator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/comparator/JoinConditionsEncryptorComparator.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/comparator/InsertSelectColumnsEncryptorComparatorTest.java
=> Refactor encrypt comparator and add insert select test

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rule/table/EncryptTable.java
=> Simplify find query encryptor method

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/checker/sql/util/ShardingSupportedCheckUtils.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/IndexToken.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingDropIndexRouteContextChecker.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/checker/sql/ddl/ShardingAlterIndexSupportedCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/checker/sql/ddl/ShardingDropIndexSupportedCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/IndexTokenTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/checker/ddl/ShardingDropIndexRouteContextCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/broadcast/ShardingTableBroadcastRouteEngineTest.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/util/IndexMetaDataUtils.java, infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereSchemaTest.java, kernel/data-pipeline/scenario/cdc/core/src/main/java/org/apache/shardingsphere/data/pipeline/cdc/util/CDCSchemaTableUtils.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/checker/sql/schema/SingleDropSchemaSupportedChecker.java, kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/utils/StatisticsAssembleUtils.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/type/index/AlterIndexStatementSchemaRefresher.java, mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/persist/StandaloneMetaDataManagerPersistService.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowTableMetaDataExecutor.java
=> Merge ShardingSphereSchema.getAllTableNames and getAllTables

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereSchema.java
=> Remove ShardingSphereSchema.getAllTables

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/insert/keygen/engine/GeneratedKeyContextEngine.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/manager/GenericSchemaManager.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/type/view/federation/AlterViewFederationMetaDataRefresher.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/ShowTableMetaDataExecutor.java
=> Remove toLowercase usage of ShardingSphereSchema

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/checker/sql/ddl/ShardingCreateFunctionSupportedCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/checker/sql/ddl/ShardingCreateProcedureSupportedCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/checker/dml/ShardingUpdateRouteContextCheckerTest.java
- https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&id=apache_shardingsphere&open=AZNxNR5w91XSXdzipd_e
- https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&id=apache_shardingsphere&open=AZNxNR5V91XSXdzipd_c
- https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&id=apache_shardingsphere&open=AZN1X-7-TiVuA_WC_otF
---
=> Fix sonar issue in ShardingSupportedCheckerTest and ShardingRouteContextTest

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/builder/dialect/PostgreSQLShardingSphereStatisticsBuilder.java
=> Try to fix #33860

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/ShardingSphereDatabase.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/service/metadata/schema/SchemaMetaDataPersistService.java, kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/factory/InternalMetaDataFactoryTest.java, kernel/metadata/core/src/test/java/org/apache/shardingsphere/metadata/persist/service/metadata/schema/SchemaMetaDataPersistServiceTest.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/manager/StorageUnitManager.java
=> Refactor ShardingSphereDatabase.create()

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/ShardingSphereDatabase.java
=> Remove useless ShardingSphereDatabase's Map schemas constructor

.github/workflows/nightly-check.yml, pom.xml
=> Refactor : fix the sonar hashFiles method

.github/workflows/nightly-check.yml, .github/workflows/nightly-ci.yml
- refactor the graalvm test condition
---
=> Refactor : refactor the graalvm test condition

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/type/standard/assertion/ShardingRouteAssert.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/projection/ProjectionsSegmentBinder.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/extractor/ColumnExtractor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/dml/item/AggregationProjectionSegment.java
- Minor refactor ProjectionsSegmentBinder
---
=> Minor refactor ProjectionsSegmentBinder

.github/workflows/nightly-build.yml
- update the build workflow
---
=> Refactor : update the build workflow

.github/workflows/nightly-ci.yml
- update the graalvm trigger condition
---
=> Refactor : update the graalvm trigger condition

docs/document/content/user-manual/common-config/props.cn.md, docs/document/content/user-manual/common-config/props.en.md
I think the documentation here needs to be properly supplemented.
---
=> [Improve][Doc] add props config notes

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaData.java
=> Remove ShardingSphereMetaData's constructor with ShardingSphereDatabase map

.github/workflows/nightly-build.yml, .github/workflows/nightly-check.yml, .github/workflows/nightly-ci.yml, .github/workflows/nightly-e2e-operation.yml, .github/workflows/nightly-e2e-sql.yml, .github/workflows/nightly-sql-parser.yml
- update the workflow trigger time
---
=> Refactor : update the workflow trigger time

infra/database/type/hive/src/main/java/org/apache/shardingsphere/infra/database/hive/metadata/data/loader/HiveMetaDataLoader.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZOUtWNcNP41Jf1S5oAg
=> Fix sonar issue on HiveMetaDataLoader

infra/common/src/main/java/org/apache/shardingsphere/infra/rule/builder/global/GlobalRulesBuilder.java, infra/common/src/test/java/org/apache/shardingsphere/infra/rule/builder/global/GlobalRulesBuilderTest.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/manager/GlobalConfigurationManager.java
=> Refactor GlobalRulesBuilder

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/impl/ShardingSphereProxyClusterContainer.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/impl/MySQLContainer.java
=> Alter container startup timeout.

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/InventoryDumper.java
=> Refactor InventoryDumper.

mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/manager/StorageUnitManager.java
=> Refactor StorageUnitManager

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/RefreshDatabaseMetaDataExecutor.java
=> Refactor RefreshDatabaseMetaDataExecutor

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaData.java
=> Refactor getter of ShardingSphereMetaData.databases

features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/fixture/EncryptGeneratorFixtureBuilder.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContext.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContextTest.java, infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereSchemaTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/ProxyBackendHandlerFactoryTest.java, proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutorTest.java
=> Refactor TablesContext.findTableNameFromMetaData() with case-insensitive

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTable.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareParameterMarkerExtractor.java, proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutor.java
=> Refactor ShardingSphereTable.columnNames type as ShardingSphereIdentifier

infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/tableless/TablelessRouteEngineFactory.java, infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/tableless/type/unicast/TablelessDataSourceUnicastRouteEngine.java, infra/route/src/test/java/org/apache/shardingsphere/infra/route/engine/tableless/TablelessRouteEngineFactoryTest.java, infra/route/src/test/java/org/apache/shardingsphere/infra/route/engine/tableless/type/broadcast/TablelessDataSourceBroadcastRouteEngineTest.java, infra/route/src/test/java/org/apache/shardingsphere/infra/route/engine/tableless/type/broadcast/TablelessInstanceBroadcastRouteEngineTest.java, infra/route/src/test/java/org/apache/shardingsphere/infra/route/engine/tableless/type/ignore/TablelessIgnoreRouteEngineTest.java, infra/route/src/test/java/org/apache/shardingsphere/infra/route/engine/tableless/type/unicast/TablelessDataSourceUnicastRouteEngineTest.java
Ref #33811.
- Refactor Tableless route logic and add more unit test
---
=> Refactor Tableless route logic and add more unit test

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/condition/engine/WhereClauseShardingConditionEngine.java
=> Fix sharding column route

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/GenericSchemaBuilder.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereColumn.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereConstraint.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereIndex.java, infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/model/TableMetaData.java
=> Refactor GenericSchemaBuilder

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/ShardingSphereDatabase.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/GenericSchemaBuilder.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/GenericSchemaBuilderMaterial.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/reviser/MetaDataReviseEngine.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/util/SchemaMetaDataUtils.java, infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/ShardingSphereDatabaseTest.java, infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/GenericSchemaBuilderMaterialTest.java, infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/builder/GenericSchemaBuilderTest.java, infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/util/SchemaMetaDataUtilsTest.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/factory/ExternalMetaDataFactory.java, mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/type/table/AlterTableStatementSchemaRefresher.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/type/table/CreateTableStatementSchemaRefresher.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/type/table/RenameTableStatementSchemaRefresher.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/type/view/AlterViewStatementSchemaRefresher.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/type/view/CreateViewStatementSchemaRefresher.java
=> Refactor GenericSchemaBuilderMaterial

.github/workflows/nightly-build.yml, .github/workflows/nightly-check.yml, .github/workflows/nightly-ci.yml, .github/workflows/nightly-e2e-operation.yml, .github/workflows/nightly-e2e-sql.yml, .github/workflows/nightly-sql-parser.yml
- refactor the nightly job trigger
---
=> Refactor : refactor the nightly job trigger

proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/ShardingSphereProxy.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/config/ProxyClusterContainerConfigurationFactory.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/impl/ShardingSphereProxyContainer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/PipelineContainerComposer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/env/PipelineE2EEnvironment.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/env/enums/PipelineProxyTypeEnum.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/container/compose/DockerContainerComposer.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/framework/container/config/proxy/PipelineProxyClusterContainerConfigurationFactory.java, test/e2e/operation/pipeline/src/test/resources/env/it-env.properties
=> Support internal proxy in e2e.

RELEASE-NOTES.md, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/from/type/JoinTableSegmentBinder.java
=> Fixes the expression segment cannot find the outer table when binding.

proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/ShardingSphereProxy.java
=> Add isClosed in ShardingSphereProxy.

.github/workflows/nightly-check.yml
- add invalid in stale check
---
=> Add : add invalid in stale check

proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussAdminExecutorCreator.java, proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussShowVariableExecutor.java, proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussAdminExecutorFactoryTest.java, proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussShowVariableExecutorTest.java
Fixes #34043.
- Add show variable executor for OpenGauss
---
=> Add show variable executor for OpenGauss

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/ShardingSphereDatabaseData.java, infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/statistics/ShardingSphereDatabaseDataTest.java, kernel/metadata/core/src/main/java/org/apache/shardingsphere/metadata/persist/data/ShardingSphereDataPersistService.java
=> Add ShardingSphereDatabaseDataTest

distribution/agent/pom.xml, distribution/jdbc/pom.xml, distribution/proxy/pom.xml, distribution/src/pom.xml, pom.xml
fix #34094
- disable maven remote resources plugin
---
=> Refactor : disable maven remote resources plugin

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/EncryptTokenGenerateBuilder.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/projection/EncryptProjectionTokenGenerator.java
- Minor refactor for EncryptProjectionTokenGenerator
---
=> Minor refactor for EncryptProjectionTokenGenerator

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/condition/EncryptCondition.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/condition/EncryptConditionEngine.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/condition/impl/EncryptBinaryCondition.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/condition/impl/EncryptInCondition.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/context/EncryptSQLRewriteContextDecorator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/parameter/rewriter/EncryptPredicateParameterRewriter.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptInsertPredicateRightValueTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateRightValueTokenGenerator.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/condition/impl/EncryptBinaryConditionTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/condition/impl/EncryptInConditionTest.java
=> Refactor get column to get column segment in encrypt condition

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/admin/executor/AbstractDatabaseMetaDataExecutor.java
- Fix query some system data error when there are multiple logical database
---
=> Fix query some system data error when there are multiple logical database

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateRightValueTokenGenerator.java
=> Refactor duplicate column names usage

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/type/dql/GeneralDQLE2EIT.java
=> Add prepared statement query for xml assertions

features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/checker/ReadwriteSplittingRuleStatementChecker.java, infra/algorithm/core/src/main/java/org/apache/shardingsphere/infra/algorithm/core/exception/InvalidAlgorithmConfigurationException.java
=> Optimize props check for weight load balancer

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/cache/checker/ShardingRouteCacheableChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/checker/sql/common/ShardingSupportedCommonChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/checker/sql/ddl/ShardingAlterViewSupportedChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/checker/sql/dml/ShardingInsertSupportedChecker.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/checker/sql/util/ShardingSupportedCheckUtils.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/decider/ShardingSQLFederationDecider.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/ShardingTableTokenGenerator.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/ShardingRouteEngineFactory.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/broadcast/ShardingTableBroadcastRouteEngine.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/checker/sql/ddl/ShardingCreateViewSupportedCheckerTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/decider/ShardingSQLFederationDeciderTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/generator/impl/ShardingTableTokenGeneratorTest.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/rule/ShardingRuleTest.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/column/ColumnDefinitionSegmentBinder.java
- https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&id=apache_shardingsphere&open=AZP39LCtV8A_QVcGzsqd
- https://sonarcloud.io/project/issues?open=AZP39K4hV8A_QVcGzsqb&id=apache_shardingsphere
- https://sonarcloud.io/project/issues?open=AZPUVifrKbmqnlHGjKHw&id=apache_shardingsphere
---
=> Remove useless parameter in ShardingRule to fix sonar issue

.github/workflows/nightly-e2e-agent.yml, .github/workflows/nightly-e2e-operation.yml
- add nightly workflow for agent
---
=> Add : add nightly workflow for agent

.github/workflows/nightly-e2e-agent.yml
- refactor the building time for agent workflow
---
=> Refactor : refactor the building time for agent workflow

test/it/binder/src/test/resources/cases/dml/delete.xml, test/it/binder/src/test/resources/cases/dml/update.xml, test/it/binder/src/test/resources/sqls/dml/delete.xml, test/it/binder/src/test/resources/sqls/dml/update.xml
Ref #34029.
- Add more sql bind test case for delete and update statement
---
=> Add more sql bind test case for delete and update statement

RELEASE-NOTES.md, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/TruncateStatementBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/type/DDLStatementBindEngine.java, test/it/binder/src/test/resources/cases/ddl/cursor.xml, test/it/binder/src/test/resources/cases/ddl/truncate-table.xml, test/it/binder/src/test/resources/sqls/ddl/truncate-table.xml, test/it/binder/src/test/resources/sqls/dml/cursor.xml
Ref #34029.
- Support truncate table sql bind and add test case
---
=> Support truncate table sql bind and add test case

mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/persist/service/ClusterMetaDataManagerPersistService.java
=> Fix invalid version exception after data source unit altered

RELEASE-NOTES.md, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/checker/sql/ddl/ShardingAlterViewSupportedChecker.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/ddl/AlterViewStatementContext.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/from/type/SimpleTableSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/AlterViewStatementBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/CreateViewStatementBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/DropViewStatementBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/type/DDLStatementBindEngine.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/ddl/AlterViewStatement.java, parser/sql/statement/type/doris/src/main/java/org/apache/shardingsphere/sql/parser/statement/doris/ddl/DorisAlterViewStatement.java, parser/sql/statement/type/mysql/src/main/java/org/apache/shardingsphere/sql/parser/statement/mysql/ddl/MySQLAlterViewStatement.java, parser/sql/statement/type/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/statement/sqlserver/ddl/SQLServerAlterViewStatement.java, test/it/binder/src/test/java/org/apache/shardingsphere/test/it/sql/binder/SQLBinderIT.java, test/it/binder/src/test/resources/cases/ddl/alter-view.xml, test/it/binder/src/test/resources/cases/ddl/create-view.xml, test/it/binder/src/test/resources/cases/ddl/drop-index.xml, test/it/binder/src/test/resources/cases/ddl/drop-view.xml, test/it/binder/src/test/resources/sqls/ddl/alter-view.xml, test/it/binder/src/test/resources/sqls/ddl/create-view.xml, test/it/binder/src/test/resources/sqls/ddl/drop-view.xml, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/ddl/impl/AlterViewStatementAssert.java, test/it/rewriter/src/test/resources/scenario/sharding/case/ddl/create-table.xml
Ref #34029.
- Support create view, alter view, drop view sql bind logic
---
=> Support create view, alter view, drop view sql bind logic

RELEASE-NOTES.md, infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/tableless/TablelessRouteEngineFactory.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/DriverExecuteExecutor.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/facade/DriverExecutorFacade.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/transaction/DriverTransactionSQLStatementExecutor.java
=> Add transaction executor for driver to handle TCL statements

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContext.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/table/TablesContextTest.java, infra/executor/src/test/java/org/apache/shardingsphere/infra/executor/sql/process/ProcessEngineTest.java, infra/session/src/main/java/org/apache/shardingsphere/infra/session/query/QueryContext.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/session/ConnectionSession.java, proxy/frontend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/frontend/opengauss/command/query/extended/bind/OpenGaussComBatchBindExecutorTest.java
- Move multiple logic database check to QueryContext
---
=> Move multiple logic database check to QueryContext

test/e2e/operation/transaction/src/test/resources/env/jdbc/mysql/database-sharding-xa-atomikos.yaml, test/e2e/operation/transaction/src/test/resources/env/jdbc/mysql/database-sharding-xa-narayana.yaml
=> Add jdbc data source config for transaction E2E

mode/type/standalone/repository/provider/jdbc/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/JDBCRepository.java
=> Revise JDBCRepository

mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java, mode/core/src/main/java/org/apache/shardingsphere/mode/persist/PersistServiceFacade.java
Add PersistServiceFacade.close
=> Add PersistServiceFacade.close

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManager.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/transaction/TransactionBackendHandlerFactoryTest.java
=> Use same transaction manager in one transaction

test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/alterresource/SwitchingTransactionRuleTestCase.java
=> Add switching transaction rule test case

infra/session/src/main/java/org/apache/shardingsphere/infra/session/connection/transaction/TransactionConnectionContext.java, test/e2e/operation/transaction/src/test/java/org/apache/shardingsphere/test/e2e/transaction/cases/alterresource/SwitchingTransactionRuleTestCase.java
=> Fix sonar issue of transaction test

docs/blog/content/material/2022_03_25_A_Deep_Dive_Into_Observability_Apache_ShardingSphere_Agent.en.md, docs/blog/content/material/2022_04_21_Apache_ShardingSphere_openGauss_Breaking_the_Distributed_Database_Performance_Record_with_10_Million_tpmC.en.md, docs/blog/content/material/2022_05_10_What’s_the_Database_Plus_concept_and_what_challenges_can_it_solve.en.md, docs/blog/content/material/2022_06_02_Database_Mesh_2.0_Database_Governance_in_a_Cloud_Native_Environment.en.md, docs/blog/content/material/Jan_28_Full_Link_Online_Stress_Testing_for_Production_Database_Apache_ShardingSphere_Shadow_Database_Feature_Upgrade.en.md, docs/blog/content/material/Nov_23_1_Integrate_SCTL_into_RAL.en.md, docs/document/content/overview/_index.en.md
- I have corrected some spelling mistakes I found.
---
=> Correcting spelling mistakes

mode/type/cluster/core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/dispatch/handler/global/GlobalRuleChangedHandler.java
=> Fix failure to obtain decorator SPI in GlobalRuleChangedHandler

RELEASE-NOTES.md
=> Add release note to support insert statement rewrite using quotes

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/preparer/inventory/calculator/InventoryRecordsCountCalculator.java
=> Fix NPE when getting estimated count result set is empty

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/segment/PipelineSQLSegmentBuilder.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/segment/PipelineSQLSegmentBuilderTest.java, kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/sqlbuilder/MySQLPipelineSQLBuilderTest.java, kernel/data-pipeline/dialect/opengauss/src/test/java/org/apache/shardingsphere/data/pipeline/opengauss/sqlbuilder/OpenGaussPipelineSQLBuilderTest.java, kernel/data-pipeline/dialect/postgresql/src/test/java/org/apache/shardingsphere/data/pipeline/postgresql/sqlbuilder/PostgreSQLPipelineSQLBuilderTest.java
=> Quote column in PipelineSQLSegmentBuilder.

.github/workflows/nightly-e2e-agent.yml
- refactor the timeout for agent e2e
---
=> Refactor : refactor the timeout for agent e2e

examples/pom.xml
- update the ShardingSphere version in example
---
=> Refactor : update the ShardingSphere version in example

RELEASE-NOTES.md, docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md, docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md
- update the release version for docs and release note
---
=> Refactor : update the release version for docs and release note

infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/statistics/builder/dialect/MySQLShardingSphereStatisticsBuilderTest.java
=> Add test cases on MySQLShardingSphereStatisticsBuilder

RELEASE-NOTES.md
Ref #34346.
- Update release note for pr#34346
---
=> Update release note for pr#34346

examples/pom.xml
- refactor the example version issue
---
=> Fix : refactor the example version issue

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateColumnTokenGenerator.java
- Refactor EncryptPredicateColumnTokenGenerator encrypt logic
---
=> Refactor EncryptPredicateColumnTokenGenerator encrypt logic

distribution/proxy/Dockerfile
Fixes #32666.
- Update Dockerfile with new format
---
=> Update Dockerfile with new format

infra/algorithm/type/cryptographic/core/src/main/java/org/apache/shardingsphere/infra/algorithm/cryptographic/core/CryptographicPropertiesProvider.java, infra/algorithm/type/cryptographic/type/aes/src/main/java/org/apache/shardingsphere/infra/algorithm/cryptographic/aes/AESCryptographicAlgorithm.java, infra/algorithm/type/cryptographic/type/aes/src/main/java/org/apache/shardingsphere/infra/algorithm/cryptographic/aes/props/DefaultAESPropertiesProvider.java, infra/algorithm/type/cryptographic/type/aes/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.algorithm.cryptographic.core.CryptographicPropertiesProvider, infra/algorithm/type/cryptographic/type/aes/src/test/java/org/apache/shardingsphere/infra/algorithm/cryptographic/aes/props/DefaultAESPropertiesProviderTest.java
=> Add provider of cryptographic properties

docs/community/themes/hugo-theme-learn/layouts/partials/header.html, docs/document/themes/hugo-theme-learn/layouts/partials/header.html
Fixes #34415.
- Remove Google & Baidu Analytics from the ShardingSphere Website
---
=> Remove Google & Baidu Analytics from the ShardingSphere Website

kernel/transaction/type/xa/core/src/test/java/org/apache/shardingsphere/transaction/xa/jta/connection/dialect/FirebirdXAConnectionWrapperTest.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZSIkp3zIGU1NOvOqUvG
=> Fix sonar issue on FirebirdXAConnectionWrapperTest

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/builder/ShardingSphereStatisticsFactory.java
- Optimize ShardingSphereStatisticsFactory
---
=> Optimize ShardingSphereStatisticsFactory

mode/core/pom.xml, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/metadata/pushdown/type/table/CreateTablePushDownMetaDataRefresher.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/metadata/pushdown/type/table/DropTablePushDownMetaDataRefresher.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/metadata/util/TableRefreshUtils.java
Reverts apache/shardingsphere#34486
=> Revert "Refactor TableRefreshUtils"

RELEASE-NOTES.md
- Update release note for pr#34425
---
=> Update release note for pr#34425

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertDerivedColumnsTokenGenerator.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZTbNEZj-Bhta_DQtpSu
=> Fix sonar issue on EncryptInsertDerivedColumnsTokenGenerator

RELEASE-NOTES.md, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/ExpressionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/type/CaseWhenExpressionBinder.java
- Support case when then else segment bind
---
=> Support case when then else segment bind

mode/node/src/main/java/org/apache/shardingsphere/mode/node/path/config/rule/item/UniqueRuleItemNodePath.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZThMy20JPpN_qxMAaVL
=> Fix sonar issue on UniqueRuleItemNodePath

infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/metadata/database/PostgreSQLDatabaseMetaDataTest.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZTkohm5GIuaPaPJco3a
=> Fix sonar issue for PostgreSQLDatabaseMetaDataTest

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/collector/opengauss/OpenGaussStatisticsCollector.java, infra/common/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.metadata.statistics.collector.DialectDatabaseStatisticsCollector, proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/handler/admin/MySQLInformationSchemaExecutorFactory.java, proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussAdminExecutorCreator.java, proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussAdminExecutorCreatorTest.java, proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussAdminExecutorFactoryTest.java, proxy/backend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/PostgreSQLAdminExecutorCreator.java
Ref: #34568
- Optimize database admin executor creator
---
=> Optimize database admin executor creator

RELEASE-NOTES.md, parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/format/MySQLFormatVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDALStatementVisitor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/value/literal/impl/StringLiteralValue.java, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select-escape.xml
=> Support Quoted strings placed next to each other in MySQL parser.

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/collector/DialectDatabaseStatisticsCollector.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/collector/opengauss/OpenGaussStatisticsCollector.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/collector/postgresql/PostgreSQLStatisticsCollector.java, infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/statistics/collector/shardingsphere/ShardingSphereStatisticsCollector.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/refresher/statistics/StatisticsRefreshEngine.java, proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussAdminExecutorCreator.java, proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussAdminExecutorCreatorTest.java, proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussAdminExecutorFactoryTest.java, proxy/backend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/backend/postgresql/handler/admin/PostgreSQLAdminExecutorCreator.java
Ref: #34568
- Optimize DialectDatabaseStatisticsCollector
---
=> Optimize DialectDatabaseStatisticsCollector

parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleDDLStatementVisitor.java
=> Fix Oracle PLSQL block statements not extracted

docs/document/content/faq/_index.cn.md, docs/document/content/faq/_index.en.md
Currently, each question is distributed under a specific category. 
There is no need to set a category label for each question.
-
---
=> Remove duplicate category tags in FAQ

kernel/data-pipeline/dialect/mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/incremental/client/MySQLBinlogClient.java, kernel/data-pipeline/dialect/mysql/src/test/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/incremental/client/MySQLBinlogClientTest.java
- Add master slave replication heartbeat configuration in binlog client
---
=> Add master slave replication heartbeat configuration in binlog client

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
=> Support Oracle IS NAN SQL parse

kernel/single/core/src/main/java/org/apache/shardingsphere/single/exception/SingleDefinitionException.java, kernel/single/core/src/main/java/org/apache/shardingsphere/single/exception/SingleTablesLoadingException.java
=> Correct the cause exception in SingleTablesLoadingException.

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/assisted/MD5AssistedEncryptAlgorithm.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/standard/AESEncryptAlgorithm.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/algorithm/assisted/MD5AssistedEncryptAlgorithmTest.java
=> Optimize EncryptAlgorithm#toConfiguration.

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateColumnTokenGenerator.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZUhk_hwPdv5oyr-ID9a
=> Fix sonar issue on EncryptPredicateColumnTokenGenerator

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/loader/type/SchemaMetaDataLoader.java, infra/database/type/mysql/src/test/java/org/apache/shardingsphere/infra/database/mysql/metadata/data/loader/MySQLSchemaMetaDataLoaderTest.java, infra/database/type/opengauss/src/test/java/org/apache/shardingsphere/infra/database/opengauss/metadata/data/loader/OpenGaussSchemaMetaDataLoaderTest.java, infra/database/type/postgresql/src/test/java/org/apache/shardingsphere/infra/database/postgresql/metadata/data/loader/PostgreSQLSchemaMetaDataLoaderTest.java, kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/update/LoadSingleTableExecutor.java
=> Fix load single table tip message and use CaseInsensitiveSet

mode/node/src/test/java/org/apache/shardingsphere/mode/node/path/type/metadata/rule/DatabaseRuleNodePathTest.java
https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZU36BAJSU_7Lyvgqgtl
=> Fix sonar issues on DatabaseRuleNodePathTest

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
=> Add "inner" to oracle's unreservedWord.

features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptMergedResultTest.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZVfByQKJEQwY918rTiq
=> Fix sonar issue on EncryptMergedResultTest

mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/manager/rule/GlobalConfigurationManager.java
- Optimize close resource when rebuild global rule
---
=> Optimize close resource when rebuild global rule

RELEASE-NOTES.md, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java
=> Fix getting database name from sql statement context

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/UpdateStatementContext.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/extractor/WhereExtractor.java, test/it/parser/src/main/resources/case/dml/insert.xml, test/it/parser/src/main/resources/case/dml/update.xml
=> Fix mysql assignment column value parsing

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertCipherNameTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/insert/EncryptInsertDerivedColumnsTokenGenerator.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZWEEFIK4KR7jJ1zKzMM
=> Fix sonar issue on EncryptInsertCipherNameTokenGenerator

mode/type/cluster/core/src/test/java/org/apache/shardingsphere/mode/manager/cluster/persist/service/ClusterMetaDataManagerPersistServiceTest.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZVrLA3hJBDdM-mrCSbw
=> Fix sonar issue on ClusterMetaDataManagerPersistServiceTest

mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/persist/service/StandaloneMetaDataManagerPersistService.java
Fixes https://sonarcloud.io/project/issues?sinceLeakPeriod=true&id=apache_shardingsphere&open=AZWKEb4tIdoZQ4MOiU7b
=> Fix sonar issue on StandaloneMetaDataManagerPersistService

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/DeleteStatementContext.java
=> Refactor extract delete where segments

RELEASE-NOTES.md, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/ExpressionSegmentBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/type/OuterJoinExpressionBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/type/OuterJoinExpressionBinderTest.java, test/it/binder/src/test/java/org/apache/shardingsphere/test/it/sql/binder/dialect/oracle/OracleBinderIT.java, test/it/binder/src/test/resources/cases/dml/select.xml, test/it/binder/src/test/resources/sqls/dml/select.xml
=> Support outer join expression bind

test/e2e/sql/src/test/resources/cases/ddl/dataset/db/create_broadcast_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/db/create_broadcast_unique_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/db/create_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/db/create_unique_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/dbtbl_with_readwrite_splitting/create_broadcast_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/dbtbl_with_readwrite_splitting/create_broadcast_unique_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/dbtbl_with_readwrite_splitting/create_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/dbtbl_with_readwrite_splitting/create_unique_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/readwrite_splitting/create_broadcast_unique_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/readwrite_splitting/create_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/readwrite_splitting/create_unique_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/shadow/create_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/shadow/create_unique_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/sharding_governance/create_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/sharding_governance/create_unique_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/tbl/create_broadcast_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/tbl/create_index.xml, test/e2e/sql/src/test/resources/cases/ddl/dataset/tbl/create_unique_index.xml, test/e2e/sql/src/test/resources/cases/ddl/e2e-ddl-create-index.xml, test/e2e/sql/src/test/resources/cases/ddl/e2e-ddl-drop-index.xml, test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select-order-by.xml, test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select.xml
- Refactor db, tbl e2e case
---
=> Refactor db, tbl e2e case

RELEASE-NOTES.md, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/exception/syntax/SelectMultipleDataSourcesWithCombineException.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/ShardingRouteContextCheckerFactory.java, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/checker/dml/ShardingSelectRouteContextChecker.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/route/engine/checker/dml/ShardingSelectRouteContextCheckerTest.java
=> Add check for select with union all routing to multi data sources

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/select/EncryptGroupByItemTokenGenerator.java, test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-group-by.xml, test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-subquery.xml
=> Add quote for encrypt group by item

test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/impl/ShardingSphereJdbcContainer.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/DockerStorageContainer.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/EmbeddedStorageContainer.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/storage/StorageContainer.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/util/SQLScriptUtils.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/env/E2EEnvironmentEngine.java
=> Refactor StorageContainer.

test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select-combine.xml
=> Fix openGauss select combine E2E cases

infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/tableless/TablelessRouteEngineFactory.java
=> Optimize DDL route in TablelessRouteEngineFactory.

infra/data-source-pool/core/src/main/java/org/apache/shardingsphere/infra/datasource/pool/props/domain/DataSourcePoolProperties.java, parser/distsql/statement/src/test/java/org/apache/shardingsphere/distsql/segment/converter/DataSourceSegmentsConverterTest.java
=> Support underscore property name for storage units

agent/core/src/main/java/org/apache/shardingsphere/agent/core/plugin/jar/PluginJarLoader.java
- Optimize PluginJarLoader, filter out hidden jar file
---
=> Optimize PluginJarLoader, filter out hidden jar file

kernel/global-clock/core/src/main/java/org/apache/shardingsphere/globalclock/executor/GlobalClockTransactionHook.java, kernel/transaction/api/src/main/java/org/apache/shardingsphere/transaction/spi/TransactionHook.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManager.java
=> Fix transaction lock when commit

test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-subquery.xml
=> Add select with concat in subquery rewrite case

RELEASE-NOTES.md, features/readwrite-splitting/distsql/handler/src/main/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/InUsedReadwriteSplittingStorageUnitRetriever.java, features/readwrite-splitting/distsql/handler/src/test/java/org/apache/shardingsphere/readwritesplitting/distsql/handler/query/InUsedReadwriteSplittingStorageUnitRetrieverTest.java, features/shadow/distsql/handler/src/main/java/org/apache/shardingsphere/shadow/distsql/handler/query/InUsedShadowStorageUnitRetriever.java, infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/executor/rql/resource/ShowRulesUsedStorageUnitExecutor.java, kernel/single/distsql/handler/src/main/java/org/apache/shardingsphere/single/distsql/handler/query/InUsedSingleStorageUnitRetriever.java, kernel/single/distsql/handler/src/main/resources/META-INF/services/org.apache.shardingsphere.distsql.handler.executor.rql.resource.InUsedStorageUnitRetriever, kernel/single/distsql/handler/src/test/java/org/apache/shardingsphere/single/distsql/handler/query/InUsedSingleStorageUnitRetrieverTest.java, parser/distsql/statement/src/main/java/org/apache/shardingsphere/distsql/statement/rql/rule/database/ShowRulesUsedStorageUnitStatement.java
=> Add InUsedStorageUnitRetriever for single rule

RELEASE-NOTES.md, parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DCLStatement.g4, test/it/parser/src/main/resources/case/dcl/revoke.xml, test/it/parser/src/main/resources/sql/supported/dcl/revoke-user.xml
=> Support parsing MySQL stored procedure syntax

RELEASE-NOTES.md, docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/special-api/transaction/seata.en.md, docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/seata-at/_index.cn.md, docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/seata-at/_index.en.md, docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md, docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.en.md, kernel/transaction/type/base/seata-at/src/test/resources/file.conf, pom.xml, test/native/pom.xml, test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/transactions/base/SeataTest.java, test/native/src/test/java/org/apache/shardingsphere/test/natived/proxy/transactions/base/SeataTest.java, test/native/src/test/resources/seata-script-client-conf-file.conf
For #29052 .
- Fix conflicting dependencies of BASE transaction integration module. See https://github.com/apache/incubator-seata/pull/7046 .
- Remove unit test temporary change to `client.rm.tableMetaCheckEnable` config option. See https://github.com/apache/incubator-seata/pull/7044 .
---
=> Fix conflicting dependencies of BASE transaction integration module

agent/core/src/main/java/org/apache/shardingsphere/agent/core/advisor/config/AdvisorConfigurationLoader.java
- Add log when configuration file for advice of plugins is not found
---
=> Add log when configuration file for advice of plugins is not found

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/ColumnProjection.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/ColumnProjectionTest.java
Reverts apache/shardingsphere#35176
=> Revert "Refactor ColumnProjection.getColumnName()"

features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/sharding/distsql/handler/query/InUsedShardingStorageUnitRetriever.java, features/sharding/distsql/handler/src/test/java/org/apache/shardingsphere/sharding/distsql/handler/query/InUsedShardingStorageUnitRetrieverTest.java
=> Fix InUsedShardingStorageUnitRetriever

infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/tableless/TablelessRouteEngineFactory.java, infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/tableless/type/unicast/TablelessDataSourceUnicastRouteEngine.java, infra/route/src/test/java/org/apache/shardingsphere/infra/route/engine/tableless/type/unicast/TablelessDataSourceUnicastRouteEngineTest.java
Ensure return logic datasource name.
-
---
=> Use provided dataSourceNames instead of usedDataSourceNames.

jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/datasource/ShardingSphereDataSource.java, proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/ShardingSphereProxy.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/atomic/adapter/impl/ShardingSphereProxyContainer.java
=> Optimize startup log, print instance id, IP and port.

infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/InsertStatementBinder.java, infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/context/statement/SQLStatementContextFactoryTest.java, test/it/binder/src/test/resources/cases/dml/insert.xml, test/it/binder/src/test/resources/sqls/dml/insert.xml
=> Add insert statement assignments bind

docs/document/content/user-manual/error-code/sql-error-code.cn.md, docs/document/content/user-manual/error-code/sql-error-code.en.md, infra/algorithm/core/src/main/java/org/apache/shardingsphere/infra/algorithm/core/exception/AlgorithmInitializationException.java
=> Fix the error message of AlgorithmInitializationException

docs/document/content/user-manual/error-code/sql-error-code.cn.md, docs/document/content/user-manual/error-code/sql-error-code.en.md, infra/algorithm/core/src/main/java/org/apache/shardingsphere/infra/algorithm/core/exception/AlgorithmExecuteException.java
=> Fix the error message of AlgorithmExecuteException

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DDLStatement.g4, test/it/parser/src/main/resources/case/ddl/create-procedure.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-procedure.xml
=> Support parsing MySQL stored procedure syntax part1

distribution/proxy/src/main/resources/bin/start.sh, test/e2e/fixture/src/test/assembly/bin/start.sh
=> Remove the force start parameter in startup script

parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, test/it/parser/src/main/resources/case/dml/insert.xml, test/it/parser/src/main/resources/case/dml/select-lock.xml, test/it/parser/src/main/resources/sql/supported/dml/insert.xml, test/it/parser/src/main/resources/sql/supported/dml/select-lock.xml
=> Support MySQL lock in combines and parenthesized selects SQL parsing

parser/sql/dialect/doris/src/main/antlr4/imports/doris/DMLStatement.g4, parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/DorisStatementVisitor.java, parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DMLStatement.g4, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/format/MySQLFormatVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/create-table.xml, test/it/parser/src/main/resources/case/ddl/create-view.xml, test/it/parser/src/main/resources/case/dml/select-combine.xml, test/it/parser/src/main/resources/case/dml/select-lock.xml, test/it/parser/src/main/resources/case/dml/select-with.xml, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/case/dml/table.xml, test/it/parser/src/main/resources/sql/supported/dml/select-combine.xml
- Refactor mysql combine parse rule to support intersect priority
---
=> Refactor mysql combine parse rule to support intersect priority

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/Keyword.g4, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/OracleKeyword.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml
=> Support Oracle json_object function parsing

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
=> Fix mysql match against statement visit

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/data/loader/type/SchemaMetaDataLoader.java
- Add import for DialectDatabaseMetaData
- Refactor schemaOption initialization for better readability and maintainability
=> Improve code readability in SchemaMetaDataLoader

infra/common/src/test/java/org/apache/shardingsphere/infra/database/DatabaseTypeEngineTest.java
- Remove specific database type imports (MySQL, PostgreSQL, H2)
- Use TypedSPILoader to get database types dynamically
- Update assertions to use is() instead of instanceOf()
- Simplify test cases by removing repeated code
=> Improve DatabaseTypeEngineTest with more generic approach

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/result/TableDataConsistencyCheckResult.java, kernel/data-pipeline/scenario/consistency-check/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/api/ConsistencyCheckJobAPI.java, kernel/data-pipeline/scenario/consistency-check/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/task/ConsistencyCheckTasksRunner.java
- Ignored table in data consistency check handled as successful
---
=> Ignored table in data consistency check handled as successful

infra/common/src/main/java/org/apache/shardingsphere/infra/metadata/database/schema/QualifiedTable.java, infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/QualifiedTableTest.java, kernel/data-pipeline/scenario/migration/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/check/consistency/MigrationDataConsistencyChecker.java
- Improve "show migration check status jobId": update table formatting
---
=> Improve "show migration check status jobId": update table formatting

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/reviser/schema/ShardingSchemaTableAggregationReviser.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/metadata/reviser/schema/ShardingSchemaTableAggregationReviserTest.java
=> Fix table metadata check uniformed

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/metadata/data/ShardingTableStatisticsCollector.java
- Remove void methods and replace with returning Collection
- Wrap naked return with Collections.emptyList()
- Extract method to collect table statistics
- Improve code readability and maintainability
=> Optimize code structure and improve return type handling

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/processor/SQLFederationProcessor.java, kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/processor/impl/StandardSQLFederationProcessor.java
- Minor refactor for SQLFederationProcessor
---
=> Minor refactor for SQLFederationProcessor

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/AbstractExecutionPrepareEngine.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/DriverExecutionPrepareEngine.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/jdbc/builder/PreparedStatementExecutionUnitBuilder.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/raw/RawExecutionPrepareEngine.java
- Add @HighFrequencyInvocation annotation to relevant classes
- Improve data structure usage for better performance
- Refactor method names for consistency and clarity
=> Optimize execution prepare engine for high frequency invocation

db-protocol/opengauss/pom.xml, db-protocol/postgresql/pom.xml, proxy/backend/core/pom.xml, proxy/bootstrap/pom.xml
=> Add runtime scope for database infrastructure dependencies

jdbc/pom.xml, kernel/data-pipeline/core/pom.xml, kernel/data-pipeline/scenario/cdc/core/pom.xml, proxy/backend/core/pom.xml, proxy/backend/type/mysql/pom.xml, proxy/backend/type/opengauss/pom.xml, proxy/backend/type/postgresql/pom.xml, test/e2e/agent/fixture/jdbc-fixture/pom.xml, test/e2e/driver/pom.xml, test/e2e/operation/pipeline/pom.xml, test/it/pipeline/pom.xml
- Removed parser dependencies for various SQL dialects
- Removed infrastructure dependencies for multiple database types
- Removed test dependencies for PostgreSQL, MySQL, and SQL Server
=> Remove unused dependencies in pom.xml

agent/plugins/metrics/core/pom.xml, distribution/pom.xml, proxy/bootstrap/pom.xml, test/e2e/fixture/pom.xml, test/e2e/operation/pipeline/pom.xml, test/e2e/operation/transaction/pom.xml, test/it/spi/pom.xml, test/native/pom.xml
- Add new dependencies for PostgreSQL, MySQL, and OpenGauss
- Update existing dependencies to include version and scope
- Remove redundant dependencies from proxy/bootstrap/pom.xml
- Reorganize pom.xml structure for better readability and maintainability
For #35346.
=> Update dependencies and reorganize pom structure

distribution/proxy/src/main/release-docs/LICENSE, pom.xml
- Upgrade netty.version from 4.1.112.Final to 4.1.121.Final in pom.xml
=> Update netty version to 4.1.121.Final

proxy/frontend/core/pom.xml, proxy/frontend/type/mysql/pom.xml, proxy/frontend/type/opengauss/pom.xml, proxy/frontend/type/postgresql/pom.xml
- Remove backend dependencies from frontend-core
- Update backend dependency versions in frontend-type modules
- Remove redundant frontend-spi dependencies
- Adjust module dependencies to align with new architecture
=> Adjust frontend module dependencies and structure

proxy/backend/core/pom.xml, proxy/backend/type/mysql/pom.xml, proxy/backend/type/opengauss/pom.xml, proxy/backend/type/postgresql/pom.xml
- Add runtime scope to data pipeline dependencies in proxy-backend-core
- Add MySQL and PostgreSQL protocol dependencies in respective backend modules
- Update OpenGauss backend to use specific protocol dependency
- Adjust dependencies in PostgreSQL backend
=> Update dependencies and adjust protocol for different databases

infra/parser/src/main/java/org/apache/shardingsphere/infra/parser/cache/CacheManager.java, infra/parser/src/main/java/org/apache/shardingsphere/infra/parser/cache/SQLStatementCacheBuilder.java, infra/parser/src/main/java/org/apache/shardingsphere/infra/parser/cache/SQLStatementCacheLoader.java, infra/parser/src/main/java/org/apache/shardingsphere/infra/parser/sql/SQLStatementParserEngine.java, infra/parser/src/main/java/org/apache/shardingsphere/infra/parser/sql/SQLStatementParserEngineFactory.java, infra/parser/src/main/java/org/apache/shardingsphere/infra/parser/sql/SQLStatementParserExecutor.java, infra/parser/src/test/java/org/apache/shardingsphere/infra/parser/sql/SQLStatementParserEngineFactoryTest.java, parser/sql/engine/src/main/java/org/apache/shardingsphere/sql/parser/api/SQLParserEngine.java
=> Update cache option when getSQLStatementParserEngine.

distribution/pom.xml, proxy/backend/core/pom.xml, proxy/bootstrap/pom.xml, proxy/frontend/core/pom.xml
- Add shardingsphere-data-pipeline dependencies for MySQL, PostgreSQL, and OpenGauss
- Remove duplicate dependencies in proxy-backend core
- Adjust dependency versions and scopes across multiple sections
=> Update dependencies and remove duplicates

infra/exception/dialect/core/src/main/java/org/apache/shardingsphere/infra/exception/dialect/exception/connection/AccessDeniedException.java, infra/exception/dialect/core/src/main/java/org/apache/shardingsphere/infra/exception/dialect/exception/syntax/column/ColumnNotFoundException.java, infra/exception/dialect/type/mysql/src/main/java/org/apache/shardingsphere/infra/exception/mysql/mapper/MySQLDialectExceptionMapper.java, infra/exception/dialect/type/mysql/src/test/java/org/apache/shardingsphere/infra/exception/mysql/mapper/MySQLDialectExceptionMapperTest.java, infra/exception/dialect/type/postgresql/src/main/java/org/apache/shardingsphere/infra/exception/postgresql/mapper/PostgreSQLDialectExceptionMapper.java, proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/CDCChannelInboundHandler.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/authentication/MySQLAuthenticationEngine.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/binary/prepare/MySQLComStmtPrepareParameterMarkerExtractor.java, proxy/frontend/type/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/authentication/MySQLAuthenticationEngineTest.java, proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutor.java, proxy/frontend/type/postgresql/src/test/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/describe/PostgreSQLComDescribeExecutorTest.java
- Move AccessDeniedException to dialect.exception.connection package
- Move ColumnNotFoundException to dialect.exception.syntax.column package
- Update related imports in multiple files
=> Reorganize exception package structure

jdbc/pom.xml
- Removed dependencies for MySQL and PostgreSQL dialect exceptions
- This change simplifies the project structure by eliminating unused dependencies
=> Remove dialect exception dependencies

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/assignment/EncryptAssignmentTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/assignment/EncryptInsertAssignmentTokenGenerator.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/assignment/EncryptUpdateAssignmentTokenGenerator.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/assignment/EncryptAssignmentTokenGeneratorTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/assignment/EncryptInsertAssignmentTokenGeneratorTest.java, features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/assignment/EncryptUpdateAssignmentTokenGeneratorTest.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/enums/SubqueryType.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/generic/bound/ColumnSegmentBoundInfo.java
- Minor refactor for EncryptAssignmentTokenGenerator
---
=> Minor refactor for EncryptAssignmentTokenGenerator

RELEASE-NOTES.md, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
=> Support Oracle in literal sql parsing

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/state/impl/UnavailableProxyState.java
- Replace MySQLShowTablesStatement with ShowTablesStatement
- Replace MySQLShowTableStatusStatement with ShowTableStatusStatement
- Replace MySQLShowCreateTableStatement with ShowCreateTableStatement
- Update isDatabaseRequiredDALStatement to use core show statement classes
=> Generalize SQL statement handling in UnavailableProxyState

features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/checker/sql/predicate/EncryptPredicateColumnSupportedChecker.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/condition/EncryptConditionEngine.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/predicate/EncryptPredicateColumnTokenGenerator.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/extractor/ColumnExtractor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/extractor/ExpressionExtractor.java, parser/sql/statement/core/src/test/java/org/apache/shardingsphere/sql/parser/statement/core/extractor/ExpressionExtractorTest.java
=> Add extractAllExpressions method to replace extractAndPredicates

test/e2e/fixture/pom.xml
- Add database dependencies in test/e2e/fixture/pom.xml it.env.docker profile
---
=> Fix Operation E2E dependencies error

docs/document/content/quick-start/shardingsphere-proxy-quick-start.cn.md, docs/document/content/quick-start/shardingsphere-proxy-quick-start.en.md, docs/document/content/user-manual/shardingsphere-proxy/startup/graalvm-native-image.cn.md
=> Remove force start document

infra/route/src/main/java/org/apache/shardingsphere/infra/route/engine/tableless/type/unicast/TablelessDataSourceUnicastRouteEngine.java
Reverts apache/shardingsphere#35411
=> Revert "Replace ThreadLocalRandom with SecureRandom for better security"

proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/protocol/FrontDatabaseProtocolTypeFactory.java
Fix issue for connect blocking if multiple database protocols and connect with error database type.
The issue comes from #35386.
=> Improve default database protocol type handling

infra/database/type/oracle/src/main/java/org/apache/shardingsphere/infra/database/oracle/metadata/database/option/OracleSchemaOption.java
- Update Oracle option schema available flag
---
=> Update Oracle option schema available flag

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/importer/ImporterConfiguration.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/sqlbuilder/segment/PipelineSQLSegmentBuilder.java, test/e2e/operation/pipeline/src/test/java/org/apache/shardingsphere/test/e2e/data/pipeline/cases/migration/general/PostgreSQLToMySQLMigrationE2EIT.java
- Improve heterogeneous databases migration
---
=> Improve heterogeneous databases migration

proxy/bootstrap/pom.xml
- Add dev profile to provide dependencies for developers (Run proxy in IDE)
- These dependencies will not be packaged into proxy distribution
=> Add dev profile to proxy bootstrap module

features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/retriever/dml/table/column/impl/ShadowDeleteStatementDataSourceMappingsRetriever.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/retriever/dml/table/column/impl/ShadowSelectStatementDataSourceMappingsRetriever.java, features/shadow/core/src/main/java/org/apache/shardingsphere/shadow/route/retriever/dml/table/column/impl/ShadowUpdateStatementDataSourceMappingsRetriever.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/engine/RowNumberPaginationContextEngine.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/pagination/engine/TopPaginationContextEngine.java
=> Use extractAllExpressions method to replace extractAndPredicates

proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/tcl/TCLBackendHandler.java
- Remove MySQL-specific logic for setting autocommit
- Implement generic solution for handling autocommit in nested transactions
- Use dialect-specific transaction option to determine if autocommit is supported in nested transactions
=> Optimize handling of autocommit in transactions

RELEASE-NOTES.md, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dal/ExplainStatementBinder.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/type/DALStatementBindEngine.java, infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/engine/type/DMLStatementBindEngine.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/dal/ExplainStatement.java
- Support explain statement sql bind
---
=> Support explain statement sql bind

infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/DialectDatabaseMetaData.java, infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/metadata/database/metadata/option/transaction/DialectTransactionOption.java, infra/database/type/firebird/src/main/java/org/apache/shardingsphere/infra/database/firebird/metadata/database/FirebirdDatabaseMetaData.java, infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/metadata/database/MySQLDatabaseMetaData.java, infra/database/type/opengauss/src/main/java/org/apache/shardingsphere/infra/database/opengauss/metadata/database/OpenGaussDatabaseMetaData.java, infra/database/type/postgresql/src/main/java/org/apache/shardingsphere/infra/database/postgresql/metadata/database/PostgreSQLDatabaseMetaData.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/DialectSQLStatementCreator.java, parser/sql/statement/type/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/statement/opengauss/OpenGaussStatementCreator.java, parser/sql/statement/type/opengauss/src/main/resources/META-INF/services/org.apache.shardingsphere.sql.parser.statement.core.DialectSQLStatementCreator, parser/sql/statement/type/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/statement/postgresql/PostgreSQLStatementCreator.java, parser/sql/statement/type/postgresql/src/main/resources/META-INF/services/org.apache.shardingsphere.sql.parser.statement.core.DialectSQLStatementCreator, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/tcl/TCLBackendHandler.java
- Add DialectSQLStatementCreator interface for creating rollback statements
- Implement OpenGaussStatementCreator and PostgreSQLStatementCreator
- Update DialectTransactionOption to include isReturnRollbackStatementWhenCommitFailed flag
- Modify TCLBackendHandler to use new rollback statement creation logic
=> Add DialectSQLStatementCreator

parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/type/DorisDMLStatementVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDMLStatementVisitor.java, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/type/PostgreSQLDMLStatementVisitor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/dml/CallStatement.java, parser/sql/statement/type/doris/src/main/java/org/apache/shardingsphere/sql/parser/statement/doris/dml/DorisCallStatement.java, parser/sql/statement/type/mysql/src/main/java/org/apache/shardingsphere/sql/parser/statement/mysql/dml/MySQLCallStatement.java, parser/sql/statement/type/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/statement/postgresql/dml/PostgreSQLCallStatement.java, parser/sql/statement/type/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/statement/sqlserver/dml/SQLServerCallStatement.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/CallStatementAssert.java
- Extract common properties to CallStatement base class
- Use getter and setter for procedureName and parameters
- Simplify parameter parsing logic using stream API
- Remove redundant code and improve code readability
=> Optimize CallStatement structure and parsing logic

features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/checker/sql/dml/ShardingCopySupportedCheckerTest.java
- Remove PostgreSQLCopyStatement and OpenGaussCopyStatement specific tests
- Create generic CopyStatementContext for testing
- Simplify test cases for checking sharding and non-sharding tables
- Improve test structure for easier understanding and future modifications
=> Refactor ShardingCopySupportedCheckerTest for better readability and maintainability

parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/type/DorisDMLStatementVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDMLStatementVisitor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/dml/DoStatement.java, parser/sql/statement/type/doris/src/main/java/org/apache/shardingsphere/sql/parser/statement/doris/dml/DorisDoStatement.java, parser/sql/statement/type/mysql/src/main/java/org/apache/shardingsphere/sql/parser/statement/mysql/dml/MySQLDoStatement.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/asserts/statement/dml/impl/DoStatementAssert.java
- Remove redundant List<ExpressionSegment> parameters from DorisDoStatement and MySQLDoStatement
- Add parameters list to DoStatement base class
- Update DoStatement parsing logic in Doris and MySQL visitors
- Adjust DoStatement assertion in test cases
=> Optimize DoStatement structure and parsing logic

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java, kernel/sql-federation/executor/src/main/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutor.java, kernel/sql-federation/executor/src/test/java/org/apache/shardingsphere/sqlfederation/executor/enumerable/EnumerableScanExecutorTest.java, kernel/sql-federation/optimizer/src/test/java/org/apache/shardingsphere/sqlfederation/optimizer/it/SQLStatementCompilerIT.java, proxy/backend/type/opengauss/src/test/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussSystemCatalogAdminQueryExecutorTest.java, test/e2e/sql/src/test/resources/cases/dql/e2e-dql-complex-select-system-schema.xml
- https://github.com/apache/shardingsphere/actions/runs/15064867100
---
=> Fix empty_storage_units e2e exception

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/expression/impl/FunctionConverter.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/from/impl/SimpleTableConverter.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/generic/OwnerConverter.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/function/opengauss/OpenGaussFunctionRegister.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/function/postgresql/PostgreSQLFunctionRegister.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/catalog/SQLFederationCatalogReader.java, kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/metadata/util/SQLFederationValidatorUtils.java, parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/PostgreSQLStatementVisitor.java, test/e2e/sql/src/test/resources/cases/dql/e2e-dql-complex-select-system-schema.xml
Ref #35450.
- Fix pg, og system table query exception caused by sql federation refactor
---
=> Fix pg, og system table query exception caused by sql federation refactor

parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/OpenGaussStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/sql/supported/dml/select-special-function.xml
- Remove useless openGauss visit logic
---
=> Remove useless openGauss visit logic

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/prepare/driver/DriverExecutionPrepareEngine.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/batch/preparedstatement/DriverExecuteBatchExecutor.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/facade/DriverExecutorFacade.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSphereStatement.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxySQLExecutor.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/StandardDatabaseConnector.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/rul/PreviewExecutor.java, proxy/backend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/backend/opengauss/handler/admin/OpenGaussSystemCatalogAdminQueryExecutor.java, proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/command/query/text/query/MySQLMultiStatementsHandler.java, proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/command/query/extended/PostgreSQLBatchedStatementsExecutor.java
- Refactor DriverExecutionPrepareEngine to use metaData
---
=> Refactor DriverExecutionPrepareEngine to use metaData

infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/DeleteStatementContext.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/SelectStatementContext.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/context/statement/dml/UpdateStatementContext.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/extractor/ColumnExtractor.java, parser/sql/statement/core/src/test/java/org/apache/shardingsphere/sql/parser/statement/core/extractor/ColumnExtractorTest.java
- Modify ColumnExtractor to return a new Collection instead of updating an existing one
- Update related test cases to use the new method signature
- Refactor DeleteStatementContext, SelectStatementContext, and UpdateStatementContext to use the new column extraction approach
- Extract common logic for creating where segments into separate methods
=> Optimize column segment extraction in SQL parsing

docs/document/content/test-manual/integration-test/_index.cn.md, docs/document/content/test-manual/integration-test/_index.en.md
=> Update doc for e2e sql

infra/common/src/main/java/org/apache/shardingsphere/infra/config/props/temporary/TemporaryConfigurationPropertyKey.java, kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/StatisticsCollectContextManagerLifecycleListener.java, kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/StatisticsCollectJob.java, kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/StatisticsCollectJobWorker.java, kernel/schedule/core/src/main/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/listener/StatisticsCollectScheduleJobCronUpdateListener.java, kernel/schedule/core/src/main/resources/META-INF/services/org.apache.shardingsphere.mode.manager.listener.StatisticsCollectJobCronUpdateListener, kernel/schedule/core/src/test/java/org/apache/shardingsphere/schedule/core/job/statistics/collect/StatisticsCollectJobWorkerTest.java, mode/core/src/main/java/org/apache/shardingsphere/mode/manager/listener/StatisticsCollectJobCronUpdateListener.java, mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/manager/rule/GlobalConfigurationManager.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/variable/SetDistVariableExecutor.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/queryable/variable/ShowDistVariablesExecutorTest.java, test/e2e/sql/src/test/resources/cases/ral/dataset/empty_rules/show_dist_variables.xml
- Improve statistics collect job, collect data at startup
---
=> Improve statistics collect job, collect data at startup

RELEASE-NOTES.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/global-rule/alter-sql-federation-rule.cn.md, docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/global-rule/alter-sql-federation-rule.en.md, kernel/sql-federation/distsql/parser/src/main/antlr4/imports/sql-federation/RALStatement.g4
=> Fix missing comma in `ALTER SQL_FEDERATION RULE`

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/cases/value/SQLValue.java
- Modify SQLValue to support more e2e test type
---
=> Modify SQLValue to support more e2e test type

infra/util/src/main/java/org/apache/shardingsphere/infra/util/datetime/DateTimeFormatterFactory.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/cases/value/SQLValue.java
- Support more e2e type in SQLValue and date format in DateTimeFormatterFactory
---
=> Support more e2e type in SQLValue and date format in DateTimeFormatterFactory

features/mask/core/src/main/java/org/apache/shardingsphere/mask/merge/MaskResultDecoratorEngine.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/merge/dql/MaskDQLResultDecorator.java, features/mask/core/src/main/java/org/apache/shardingsphere/mask/merge/dql/MaskMergedResult.java, features/mask/core/src/test/java/org/apache/shardingsphere/mask/merge/dql/MaskDQLResultDecoratorTest.java, features/mask/core/src/test/java/org/apache/shardingsphere/mask/merge/dql/MaskMergedResultTest.java
- Refactor MaskMergedResult logic
---
=> Refactor MaskMergedResult logic

kernel/sql-federation/compiler/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/sql/ast/converter/segment/expression/impl/LiteralExpressionConverter.java, parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/BaseRule.g4, parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/MySQLKeyword.g4, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java
=> Extractor interval unit from mysql TIMESTAMPADD function

infra/util/src/main/java/org/apache/shardingsphere/infra/util/datetime/DateTimeFormatterFactory.java, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/cases/value/SQLValue.java
=> Add double millis formatter and update SQLValue parsing logic

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/cases/value/SQLValue.java
=> Add support for "tinyblob" type in SQLValue parsing logic

parser/sql/dialect/clickhouse/src/main/java/org/apache/shardingsphere/sql/parser/clickhouse/visitor/statement/type/ClickHouseTCLStatementVisitor.java, parser/sql/dialect/doris/src/main/java/org/apache/shardingsphere/sql/parser/doris/visitor/statement/type/DorisTCLStatementVisitor.java, parser/sql/dialect/firebird/src/main/java/org/apache/shardingsphere/sql/parser/firebird/visitor/statement/type/FirebirdTCLStatementVisitor.java, parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLTCLStatementVisitor.java, parser/sql/dialect/opengauss/src/main/java/org/apache/shardingsphere/sql/parser/opengauss/visitor/statement/type/OpenGaussTCLStatementVisitor.java, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/type/OracleTCLStatementVisitor.java, parser/sql/dialect/postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/type/PostgreSQLTCLStatementVisitor.java, parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/type/SQLServerTCLStatementVisitor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/BeginDistributedTransactionStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/BeginTransactionStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/CheckpointStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/CommitPreparedStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/CommitStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/LockStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/PrepareTransactionStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/ReleaseSavepointStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/RollbackPreparedStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/RollbackStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/SavepointStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/SetAutoCommitStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/SetConstraintsStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/SetTransactionStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/StartTransactionStatement.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/tcl/UnlockStatement.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/tcl/SetTransactionHandler.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/handler/tcl/TCLBackendHandlerFactory.java
=> Refactor TCLStatement

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, test/it/parser/src/main/resources/case/dml/insert.xml, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/parser/src/main/resources/case/dml/select-special-function.xml, test/it/parser/src/main/resources/case/dml/select.xml
=> Fix mysql convert function extract params

kernel/sql-federation/compiler/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/sql/ast/converter/operator/common/SQLExtensionOperatorTable.java, kernel/sql-federation/compiler/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/sql/ast/converter/segment/expression/impl/BinaryOperationExpressionConverter.java
=> Add rlike sql convert

features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/classbased/ClassBasedShardingAlgorithmFactory.java
=> Fix #35552 to try multiple classloaders in sequence

kernel/sql-federation/compiler/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/compiler/SQLStatementCompiler.java, kernel/sql-federation/compiler/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/planner/builder/SQLFederationPlannerBuilder.java, kernel/sql-federation/compiler/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/rel/operator/logical/LogicalScan.java, kernel/sql-federation/compiler/src/test/resources/cases/federation-query-sql-cases.xml, test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/it/sql/dal/DALE2EIT.java
- Minor refactor sql federation and DALE2EIT
---
=> Minor refactor sql federation and DALE2EIT

infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/type/FunctionExpressionSegmentBinder.java, kernel/sql-federation/compiler/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/sql/ast/converter/segment/expression/impl/FunctionConverter.java, kernel/sql-federation/compiler/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/sql/ast/converter/segment/window/WindowConverter.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/dml/expr/FunctionSegment.java
=> Add window sql convert

parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/MySQLStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-expression.xml, test/it/rewriter/src/test/resources/scenario/sharding/case/dml/select.xml
=> Enhance MySQLStatementVisitor.

test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/it/sql/dml/BaseDMLE2EIT.java
=> Add E2E null date value assertions

kernel/sql-federation/compiler/pom.xml, pom.xml
=> Move calcite maven dependency version to root pom

RELEASE-NOTES.md, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/adapter/AbstractStatementAdapter.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java
=> Resolve statement manager leaks when creating multiple statements.

features/sharding/distsql/parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/util/SQLUtils.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/value/identifier/IdentifierValue.java, parser/sql/statement/core/src/test/java/org/apache/shardingsphere/sql/parser/statement/core/value/identifier/IdentifierValueTest.java
=> Refactor IdentifierValue

parser/sql/statement/core/src/test/java/org/apache/shardingsphere/sql/parser/statement/core/value/identifier/IdentifierValueTest.java
=> Add test for IdentifierValue with reserved brackets

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/resultset/SQLFederationResultSet.java
=> Refactor federation result set get current is called twice

parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/extractor/SubqueryExtractor.java
=> Add support for QuantifySubqueryExpression in SubqueryExtractor

RELEASE-NOTES.md, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/condition/impl/EncryptBinaryCondition.java, features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/pojo/EncryptPredicateFunctionRightValueToken.java, test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-where.xml
=> Resolve rewrite issue in nested concat function.

examples/shardingsphere-jdbc-example-generator/src/main/resources/template/pom.ftl, examples/shardingsphere-jdbc-example-generator/src/test/java/PomTemplateTest.java
Fixes #35694.
- Added JDBC implementation for StandalonePersistRepository
- Added PomTemplateTest for standalone JDBC example
- Updated pom.ftl template to include necessary JDBC dependencies
---
=> Add PomTemplateTest and update pom.ftl for standalone JDBC example

db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/protocol/MySQLDateBinaryProtocolValue.java
=> Fix LocalDate type cast

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/QueryResult.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/memory/JDBCMemoryQueryResult.java, infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/result/query/impl/driver/jdbc/type/stream/JDBCStreamQueryResult.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/callback/execute/ExecuteQueryCallback.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSetFactory.java
=> Reduce the number of getResultSet method calls

RELEASE-NOTES.md, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/from/type/SimpleTableSegmentBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/util/AlterTableMetadataCheckUtils.java, infra/binder/core/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/util/AlterTableMetadataCheckUtilsTest.java, infra/common/src/main/java/org/apache/shardingsphere/infra/exception/kernel/metadata/DuplicateColumnException.java, test/it/binder/src/test/java/org/apache/shardingsphere/test/it/sql/binder/SQLBinderIT.java, test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/ddl/alter/alter-table.xml, test/it/rewriter/src/test/resources/scenario/sharding/case/ddl/index.xml
=> Add alter table metadata check

infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dal/ExplainStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/AlterIndexStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/AlterTableStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/AlterViewStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/CreateIndexStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/CreateTableStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/CreateViewStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/CursorStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/DropIndexStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/DropTableStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/DropViewStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/RenameTableStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/TruncateStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/DeleteStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/InsertStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/SelectStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/dml/UpdateStatementBinder.java, infra/binder/dialect/mysql/src/main/java/org/apache/shardingsphere/infra/binder/mysql/bind/type/MySQLLoadDataStatementBinder.java, infra/binder/dialect/mysql/src/main/java/org/apache/shardingsphere/infra/binder/mysql/bind/type/MySQLLoadXMLStatementBinder.java, infra/binder/dialect/mysql/src/main/java/org/apache/shardingsphere/infra/binder/mysql/bind/type/MySQLOptimizeTableStatementBinder.java, infra/binder/dialect/mysql/src/main/java/org/apache/shardingsphere/infra/binder/mysql/bind/type/MySQLShowColumnsStatementBinder.java, infra/binder/dialect/mysql/src/main/java/org/apache/shardingsphere/infra/binder/mysql/bind/type/MySQLShowCreateTableStatementBinder.java, infra/binder/dialect/mysql/src/main/java/org/apache/shardingsphere/infra/binder/mysql/bind/type/MySQLShowIndexStatementBinder.java, infra/binder/dialect/postgresql/src/main/java/org/apache/shardingsphere/infra/binder/postgresql/bind/type/PostgreSQLCopyStatementBinder.java, infra/binder/dialect/sqlserver/src/main/java/org/apache/shardingsphere/infra/binder/sqlserver/bind/type/SQLServerDenyUserStatementBinder.java
Reverts apache/shardingsphere#35897
=> Revert "Add database type setter on Statement binder"

db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLBoolBinaryProtocolValueTest.java, db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLInt4BinaryProtocolValueTest.java, db-protocol/postgresql/src/test/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/extended/bind/protocol/PostgreSQLTimeBinaryProtocolValueTest.java
=> Refactor PostgreSQLBinaryProtocolValue related test cases #35841

RELEASE-NOTES.md, parser/sql/dialect/hive/pom.xml, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DDLStatement.g4, parser/sql/dialect/hive/src/main/antlr4/imports/hive/HiveKeyword.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/HiveStatementVisitor.java, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/HiveStatementVisitorFacade.java, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDDLStatementVisitor.java, parser/sql/dialect/hive/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/hive/internal/InternalHiveParserIT.java, parser/sql/dialect/hive/src/test/java/org/apache/shardingsphere/test/it/sql/parser/it/hive/internal/InternalUnsupportedHiveParserIT.java, test/it/parser/src/main/resources/case/ddl/create-database.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-database.xml
official document:https://hive.apache.org/docs/latest/languagemanual-ddl_27362034/#createdropalteruse-database
-
---
=> fix:Support Hive CREATE DATABASE statment parse

mode/core/src/main/java/org/apache/shardingsphere/mode/metadata/factory/init/type/LocalConfigurationMetaDataContextsInitFactory.java
=> Persist tables to repository when persistSchemasEnabled turned on

db-protocol/firebird/pom.xml, jdbc/pom.xml
=> Remove firebird driver dependency from jdbc module

kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/engine/SQLFederationEngine.java
- Add error log when sql federation execution failed
---
=> Add error log when sql federation execution failed

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4, parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/SQLServerKeyword.g4, parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
official document:https://learn.microsoft.com/zh-cn/sql/t-sql/functions/ntile-transact-sql?view=sql-server-ver17
-
---
=> fix:Support for the NTILE function

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
official document:https://learn.microsoft.com/zh-cn/sql/t-sql/functions/replace-transact-sql?view=sql-server-ver17
-
---
=> fix:Support for the COLLATE rule

RELEASE-NOTES.md, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DDLStatement.g4, parser/sql/dialect/hive/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/HiveStatement.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDDLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/drop-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/drop-table.xml
official document:https://hive.apache.org/docs/latest/languagemanual-ddl_27362034/#createdroptruncate-table
-
---
=> fix:Support Hive DROP TABLE statement parse

kernel/transaction/type/xa/core/src/main/java/org/apache/shardingsphere/transaction/xa/jta/datasource/XATransactionDataSource.java, kernel/transaction/type/xa/core/src/test/java/org/apache/shardingsphere/transaction/xa/jta/datasource/XATransactionDataSourceTest.java, kernel/transaction/type/xa/spi/src/main/java/org/apache/shardingsphere/transaction/xa/spi/SingleXAResource.java
=> Support XA transaction enlist multiple XA connections by one data source

infra/binder/core/src/test/java/org/apache/shardingsphere/infra/binder/context/statement/type/dml/InsertStatementContextTest.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/SQLStatement.java
=> Use set to deduplicate parameterMarkers

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4, parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select-join.xml, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
official document:https://learn.microsoft.com/zh-cn/sql/t-sql/functions/string-agg-transact-sql?view=sql-server-ver17
-
---
=> fix:Support for the STRING AGG aggregation function

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4, parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/SQLServerKeyword.g4, parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
official document:https://learn.microsoft.com/zh-cn/sql/t-sql/functions/percentile-cont-transact-sql?view=sql-server-ver17
-
---
=> fix:Support for the PERCENTILE function

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4, parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/SQLServerKeyword.g4, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
official document:https://learn.microsoft.com/zh-cn/sql/t-sql/functions/dense-rank-transact-sql?view=sql-server-ver17
-
---
=> fix:Support for the DENSE_RANK function

RELEASE-NOTES.md, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DDLStatement.g4, parser/sql/dialect/hive/src/main/antlr4/imports/hive/HiveKeyword.g4, parser/sql/dialect/hive/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/HiveStatement.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDDLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/alter-table.xml, test/it/parser/src/main/resources/case/ddl/drop-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-table.xml, test/it/parser/src/main/resources/sql/supported/ddl/drop-table.xml
official document:https://hive.apache.org/docs/latest/languagemanual-ddl_27362034/#alter-tablepartitioncolumn
-
---
=> fix:Support Hive ALTER TABLE statement parse

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/DMLStatement.g4, parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/SQLServerKeyword.g4, parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/segment/generic/table/JoinTableSegment.java, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
official document:https://learn.microsoft.com/zh-cn/sql/t-sql/queries/hints-transact-sql-join?view=sql-server-ver17
-
---
=> fix:Support for join hints

RELEASE-NOTES.md, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/ExpressionSegmentBinder.java, test/e2e/sql/src/test/resources/cases/dql/e2e-dql-select-expression.xml
=> Fix is unable to find the outer table in the ExistsSubqueryExpressionBinder.

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
official document:https://learn.microsoft.com/zh-cn/sql/t-sql/functions/max-transact-sql?view=sql-server-ver17
-
---
=> fix:Support for the OVER clause of aggregation function

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/BaseRule.g4, parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java, test/it/parser/src/main/resources/case/dml/insert.xml, test/it/parser/src/main/resources/sql/supported/dml/insert.xml
official document:https://learn.microsoft.com/zh-cn/sql/t-sql/statements/insert-transact-sql?view=sql-server-ver17
-
---
=> fix:Support for naming of the four parts

RELEASE-NOTES.md, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
=> Add support for COLON_ parameter marker in Oracle

RELEASE-NOTES.md, parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4
Reverts apache/shardingsphere#36076
=> Revert "Add support for COLON_ parameter marker in Oracle"

parser/sql/dialect/oracle/src/main/antlr4/imports/oracle/BaseRule.g4, parser/sql/dialect/oracle/src/main/java/org/apache/shardingsphere/sql/parser/oracle/visitor/statement/OracleStatementVisitor.java, test/it/parser/src/main/resources/case/dal/explain.xml, test/it/parser/src/main/resources/sql/supported/dal/explain.xml
=> Remove bindLiterals in Oracle.

infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/type/ColumnSegmentBinder.java
- Minor refactor for ColumnSegmentBinder
---
=> Minor refactor for ColumnSegmentBinder

RELEASE-NOTES.md, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DDLStatement.g4, parser/sql/dialect/hive/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/HiveStatement.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDDLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/create-view.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-view.xml
official document:https://hive.apache.org/docs/latest/languagemanual-ddl_27362034/#createdropalter-view
-
---
=> fix:Support Hive CREATE VIEW statement parse

RELEASE-NOTES.md, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DDLStatement.g4, parser/sql/dialect/hive/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/HiveStatement.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDDLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/drop-view.xml, test/it/parser/src/main/resources/sql/supported/ddl/drop-view.xml
official document:https://hive.apache.org/docs/latest/languagemanual-ddl_27362034/#createdropalter-view
-
---
=> fix:Support Hive DROP VIEW statement parse

RELEASE-NOTES.md, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DDLStatement.g4, parser/sql/dialect/hive/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/HiveStatement.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDDLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/alter-materialized-view.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-materialized-view.xml
official document:https://hive.apache.org/docs/latest/languagemanual-ddl_27362034/#createdropalter-materialized-view
-
---
=> fix:Support Hive ALTER MATERIALIZED VIEW statement parse

parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/DMLStatement.g4, parser/sql/dialect/sqlserver/src/main/antlr4/imports/sqlserver/SQLServerKeyword.g4, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
official document:https://learn.microsoft.com/zh-cn/sql/t-sql/queries/from-transact-sql?view=sql-server-ver17
-
---
=> fix:Support the FOR SYSTEM TIME rule in the FROM clause

RELEASE-NOTES.md, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/ExpressionSegmentBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/type/NotExpressionBinder.java, infra/binder/core/src/test/java/org/apache/shardingsphere/infra/binder/engine/segment/dml/expression/type/NotExpressionBinderTest.java, test/it/rewriter/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/select/select-subquery.xml
=> Fix is unable to find the outer table in the NotExpressionBinder.

RELEASE-NOTES.md, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DDLStatement.g4, parser/sql/dialect/hive/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/HiveStatement.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDDLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/drop-index.xml, test/it/parser/src/main/resources/sql/supported/ddl/drop-index.xml
official document:https://hive.apache.org/docs/latest/languagemanual-ddl_27362034/#createdropalterindex
-
---
=> fix:Support Hive DROP INDEX statement parse

RELEASE-NOTES.md, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DDLStatement.g4, parser/sql/dialect/hive/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/HiveStatement.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDDLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/alter-index.xml, test/it/parser/src/main/resources/sql/supported/ddl/alter-index.xml
official document:https://hive.apache.org/docs/latest/languagemanual-ddl_27362034/#createdropalterindex
-
---
=> fix:Support Hive ALTER INDEX statement parse

RELEASE-NOTES.md, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/context/SQLStatementContextFactory.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/PrepareStatementBinder.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/engine/type/DDLStatementBindEngine.java, infra/binder/core/src/test/java/org/apache/shardingsphere/infra/binder/engine/statement/ddl/PrepareStatementBinderTest.java
Ref https://github.com/apache/shardingsphere/issues/34029
- Support prepare statement SQL bind
---
=> Support PrepareStatement SQL bind

features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/merge/dql/EncryptDQLResultDecoratorTest.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/engine/ProjectionEngine.java, infra/binder/core/src/main/java/org/apache/shardingsphere/infra/binder/context/segment/select/projection/impl/ColumnProjection.java
=> Refactor ColumnProjection and ProjectionEngine

RELEASE-NOTES.md, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DDLStatement.g4, parser/sql/dialect/hive/src/main/antlr4/imports/hive/HiveKeyword.g4, parser/sql/dialect/hive/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen/HiveStatement.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDDLStatementVisitor.java, test/it/parser/src/main/resources/case/ddl/create-function.xml, test/it/parser/src/main/resources/sql/supported/ddl/create-function.xml
official document:https://hive.apache.org/docs/latest/languagemanual-ddl_27362034/#createdropreload-function
-
---
=> fix:Support Hive CREATE FUNCTION statement parse

RELEASE-NOTES.md, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DDLStatement.g4, parser/sql/dialect/hive/src/main/antlr4/imports/hive/HiveKeyword.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDDLStatementVisitor.java, parser/sql/engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java, parser/sql/statement/core/src/main/java/org/apache/shardingsphere/sql/parser/statement/core/statement/type/ddl/function/ReloadFunctionStatement.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/RootSQLParserTestCases.java, test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/cases/parser/jaxb/statement/ddl/standard/function/ReloadFunctionStatementTestCase.java, test/it/parser/src/main/resources/case/ddl/reload-function.xml, test/it/parser/src/main/resources/sql/supported/ddl/reload-function.xml
official document:https://hive.apache.org/docs/latest/languagemanual-ddl_27362034/#createdropreload-function
-
---
=> fix:Support Hive RELOAD FUNCTION statement parse

infra/common/src/main/java/org/apache/shardingsphere/infra/datanode/DataNode.java, infra/common/src/test/java/org/apache/shardingsphere/infra/datanode/DataNodeTest.java
- Remove duplication within DataNode Constructor
---
=> Remove duplication within DataNode Constructor

infra/binder/core/src/test/java/org/apache/shardingsphere/infra/binder/engine/statement/dal/ExplainStatementBinderTest.java, test/it/binder/src/test/resources/cases/dal/explain.xml, test/it/binder/src/test/resources/sqls/dal/explain.xml
Ref https://github.com/apache/shardingsphere/issues/34029
- Add test for explain statement SQL bind
---
=> Add test for explain statement SQL bind

RELEASE-NOTES.md, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DALStatement.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDALStatementVisitor.java, parser/sql/statement/type/hive/src/main/java/org/apache/shardingsphere/sql/parser/statement/hive/dal/show/HiveShowTablesExtendedStatement.java, parser/sql/statement/type/hive/src/main/java/org/apache/shardingsphere/sql/parser/statement/hive/dal/show/HiveShowTblpropertiesStatement.java, test/it/parser/src/main/resources/case/dal/show.xml, test/it/parser/src/main/resources/sql/supported/dal/show.xml
official document:https://hive.apache.org/docs/latest/language/languagemanual-ddl_27362034/#show
-
---
=> Support Hive SHOW TABLE EXTENDED & SHOW TBLPROPERTIES & SHOW CREATE TABLE statement parse

RELEASE-NOTES.md, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DALStatement.g4, parser/sql/dialect/hive/src/main/antlr4/imports/hive/HiveKeyword.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDALStatementVisitor.java, parser/sql/dialect/sqlserver/src/main/java/org/apache/shardingsphere/sql/parser/sqlserver/visitor/statement/SQLServerStatementVisitor.java, parser/sql/statement/type/hive/src/main/java/org/apache/shardingsphere/sql/parser/statement/hive/dal/show/HiveShowFunctionsStatement.java, test/it/parser/src/main/resources/case/dal/show.xml, test/it/parser/src/main/resources/sql/supported/dal/show.xml
official document:https://hive.apache.org/docs/latest/language/languagemanual-ddl_27362034/#show
-
---
=> Support Hive SHOW INDEX & SHOW COLUMNS & SHOW FUNCTIONS statement parse

RELEASE-NOTES.md, parser/sql/dialect/hive/src/main/antlr4/imports/hive/DALStatement.g4, parser/sql/dialect/hive/src/main/antlr4/imports/hive/HiveKeyword.g4, parser/sql/dialect/hive/src/main/java/org/apache/shardingsphere/sql/parser/hive/visitor/statement/type/HiveDALStatementVisitor.java, parser/sql/statement/type/hive/src/main/java/org/apache/shardingsphere/sql/parser/statement/hive/dal/show/HiveShowCompactionsStatement.java, parser/sql/statement/type/hive/src/main/java/org/apache/shardingsphere/sql/parser/statement/hive/dal/show/HiveShowTransactionsStatement.java, test/it/parser/src/main/resources/case/dal/show.xml, test/it/parser/src/main/resources/sql/supported/dal/show.xml
official document:https://hive.apache.org/docs/latest/language/languagemanual-ddl_27362034/#show
-
---
=> Support Hive SHOW TRANSACTIONS & SHOW COMPACTIONS statement parse

database/protocol/type/opengauss/src/test/java/org/apache/shardingsphere/database/protocol/opengauss/packet/command/codec/OpenGaussPacketCodecEngineTest.java, database/protocol/type/opengauss/src/test/java/org/apache/shardingsphere/database/protocol/opengauss/packet/command/packet/authentication/OpenGaussAuthenticationHexDataTest.java, database/protocol/type/opengauss/src/test/java/org/apache/shardingsphere/database/protocol/opengauss/packet/command/packet/authentication/OpenGaussAuthenticationSCRAMSha256PacketTest.java, database/protocol/type/opengauss/src/test/java/org/apache/shardingsphere/database/protocol/opengauss/packet/command/packet/command/OpenGaussCommandPacketFactoryTest.java, database/protocol/type/opengauss/src/test/java/org/apache/shardingsphere/database/protocol/opengauss/packet/command/packet/command/OpenGaussCommandPacketTypeTest.java, infra/reachability-metadata/src/main/resources/META-INF/native-image/org.apache.shardingsphere/generated-reachability-metadata/reachability-metadata.json
=> Rename package name from org.apache.shardingsphere.db.protocol to org.apache.shardingsphere.database.protocol

docs/document/content/user-manual/shardingsphere-proxy/optional-plugins/_index.cn.md
=> Rename module names from shardingsphere-dialect_xxx-protocol to shardingsphere-protocol-dialect_xxx

RELEASE-NOTES.md, features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/algorithm/sharding/mod/ModShardingAlgorithm.java, features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/mod/ModShardingAlgorithmTest.java
=> Fix mod sharding algorithm judgement

kernel/sql-federation/compiler/pom.xml, pom.xml, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/distsql/ral/updatable/variable/SetDistVariableExecutorTest.java
- Refactor sql federation calcite pom dependency
---
=> Refactor sql federation calcite pom dependency

infra/distsql-handler/src/main/java/org/apache/shardingsphere/distsql/handler/engine/update/DistSQLUpdateExecuteEngine.java
=> Revert contains database judgement

.github/workflows/resources/filter/operation-filters.yml
=> Add distsql-handler module to transaction operation filter

docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/readwrite-splitting.cn.md, docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/rules/readwrite-splitting.en.md
- Update readwrite_splitting yaml api doc
---
=> Update readwrite_splitting yaml api doc

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/position/type/pk/PrimaryKeyIngestPositionFactory.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/preparer/inventory/calculator/InventoryPositionCalculator.java, kernel/data-pipeline/core/src/test/java/org/apache/shardingsphere/data/pipeline/core/preparer/inventory/calculator/InventoryPositionCalculatorTest.java, kernel/data-pipeline/scenario/consistency-check/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/consistencycheck/task/ConsistencyCheckTasksRunner.java
- Refactor InventoryPositionCalculator and PrimaryKeyIngestPositionFactory method return type
---
=> Refactor InventoryPositionCalculator and PrimaryKeyIngestPositionFactory method return type

kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/ShardingSphereTransactionManagerEngine.java, kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/rule/TransactionRule.java, kernel/transaction/core/src/test/java/org/apache/shardingsphere/transaction/rule/TransactionRuleTest.java
=> Refactor transaction rule close

infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/execute/engine/driver/jdbc/JDBCExecutor.java, infra/session/src/main/java/org/apache/shardingsphere/infra/session/connection/transaction/TransactionConnectionContext.java, infra/session/src/test/java/org/apache/shardingsphere/infra/session/connection/transaction/TransactionConnectionContextTest.java, jdbc/src/main/java/org/apache/shardingsphere/driver/executor/engine/transaction/DriverTransactionalExecutor.java, jdbc/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/DriverDatabaseConnectionManager.java, kernel/transaction/core/src/main/java/org/apache/shardingsphere/transaction/ConnectionTransaction.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/ProxyDatabaseConnectionManager.java, proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManager.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/ProxyDatabaseConnectionManagerTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/connector/jdbc/transaction/BackendTransactionManagerTest.java, proxy/backend/core/src/test/java/org/apache/shardingsphere/proxy/backend/handler/tcl/TCLBackendHandlerTest.java, test/e2e/env/src/test/java/org/apache/shardingsphere/test/e2e/env/container/adapter/impl/ShardingSphereProxyEmbeddedContainer.java
=> Refactor transaction context

parser/sql/engine/dialect/sqlserver/src/main/antlr4/imports/sqlserver/DMLStatement.g4, parser/sql/engine/dialect/sqlserver/src/main/antlr4/imports/sqlserver/SQLServerKeyword.g4, test/it/parser/src/main/resources/case/dml/select.xml, test/it/parser/src/main/resources/sql/supported/dml/select.xml
for https://github.com/apache/shardingsphere/issues/35908
official document:https://learn.microsoft.com/zh-cn/sql/t-sql/queries/hints-transact-sql-query?view=sql-server-ver17
-
---
=> Support for the FORCE SINGLE NODE PLAN query hint

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/DataConsistencyCheckUtils.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/DataMatchTableDataConsistencyChecker.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/AbstractRecordSingleTableInventoryCalculator.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/CalculationContext.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/RecordSingleTableInventoryCheckCalculator.java, test/it/pipeline/src/test/java/org/apache/shardingsphere/data/pipeline/core/consistencycheck/table/calculator/RecordSingleTableInventoryCheckCalculatorTest.java
- Extract AbstractRecordSingleTableInventoryCalculator
---
=> Extract AbstractRecordSingleTableInventoryCalculator

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/datasource/creator/ShardingSpherePipelineDataSourceCreator.java
- Refactor ShardingSpherePipelineDataSourceCreator.updateConfigurationProperties
---
=> Refactor ShardingSpherePipelineDataSourceCreator.updateConfigurationProperties

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/InventoryDumper.java, kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/ingest/dumper/inventory/InventoryDumperContext.java
- Remove unused InventoryDumperContext fields
---
=> Remove unused InventoryDumperContext fields

kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/core/datasource/creator/ShardingSpherePipelineDataSourceCreator.java
- Refactor ShardingSpherePipelineDataSourceCreator createConfigurationProperties
---
=> Refactor ShardingSpherePipelineDataSourceCreator createConfigurationProperties
